<?php

?>
<div class="contentforterms">
<!-- <?php echo $this->translate("Site_Contactus")?>


						<div class='report-panel-header'>
							<span class="campaign-name"><?php echo $activeCampaign["name"]?></span>
							<span class="tab-description"> <?php echo $this->translate('Report_Contact_Description')?><span>
						</div> -->
</div>

<div class="article-box">
	<div class="article-box-inner">
		<div class="contact-text">
			<p><h2><?php echo $this->translate('Contact_Text_Title')?></h2><p> 
			<p><?php echo $this->translate('Contact_Text_desc'); ?></p>
			<p><img style="width:30px;height:30px;" src="../image/email.jpg"><?php echo $this->translate('Contact_Text_email')?></p>
	    <p><img style="width:30px;height:30px;" src='../image/yahoo.jpg'/><?php echo $this->translate('Contact_Text_Yahoo')?></p>
	    <p><img style="width:30px;height:30px;" src='../image/facebook.jpg'/><?php echo $this->translate('Contact_Text_Facebook')?></p>
	    <p><img style="width:30px;height:30px;" src='../image/mobile.jpg'/><?php echo $this->translate('Contact_Text_Mobile')?></p>
	  </div> 
</div>
</div>
