<div align="center">
		<h1 style="padding-top:40px;"><?php echo $this->translate("Admin_Reports")?></h1>
		<p>Total:<?php echo $this->totalReports;?><br/>
			Approved:<?php echo $this->totalApprovedReports;?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</p>
		<table class="survey-history" style ="width:900px;">
		<tr>
			<td>筛选
				<form name="form" action="<?php echo $this->url(array('controller'=>'report','action'=>'adminreport'));?>"  method="post" enctype="application/x-www-form-urlencoded" id="filter_form">
					<input type="hidden" name="id" value="<?php echo $this->campaign_id;?>" />
					<input type="hidden" name="pest" value="0" />
					<select name="select_status" id="report_status" onchange="javascript:jQuery('#filter_form').submit()">
						<option value="all" >全部</option>
						<option value="LOCKED" <?php if($this->select_status == "LOCKED") echo "selected";?>>已被选定</option>
						<option value="APPROVED" <?php if($this->select_status == "APPROVED") echo "selected";?>>审核通过</option>
						<option value="UNAPPROVED" <?php if($this->select_status == "UNAPPROVED") echo "selected";?>>审核未通过</option>
						<option value="NEW" <?php if($this->select_status == "NEW") echo "selected";?>>未审核</option>
					</select>
				</form>
			</td>
		</tr>
		<form name="form"
	action="<?php echo $this->url(array('controller'=>'report','action'=>'admincreatebatch'));?>"
	method="post">
			<input type="hidden" name="id" value="<?php echo $this->campaign_id;?>" />
			<tr>
				<!--<th></th>
				-->
				<th><?php echo $this->translate("His_No.")?></th>
				<th><?php echo $this->translate("Amin_Consumer_email")?></th>
				<th><?php echo $this->translate("His_Reports_date")?></th>
				<th><?php echo $this->translate("Admin_Conumer_Report_Total")?></th>
				<th><?php echo $this->translate("His_Reports_state")?></th>
				<th><?php echo $this->translate("Admin_Grade")?></th>
				<?php if ($this->currentAdmin->id=='2'){?><th><?php echo $this->translate("负责人") ?></th><?php }?>
				<th><input type="submit" value="领取"></input></th>
				<?php if($this->campaign->type == 'mission'){?>
				<th>Action</th>
				<?php }?>
				
			</tr>
			<?php $i = $this->NoInitValue ;
				foreach ($this->paginator as $report):
				$report_id = $report['id'];
			?>
			
				<tr	>
				<!--<td><input type="checkbox" id="checkbox_<?php echo $i; ?>" name="checkbox_<?php echo $i; ?>"></td>
				-->
				<td><?php echo $i;?></td>
				<td><?php if(isset($report['email'])&& $report['email']!= ''){echo $report['email'];}else{echo $report['login_phone'];}
				if($report['source'] != 'application'){echo '(报告来源：'.$report['source'].')';}?></td>
				<td><?php echo $report['create_date']?></td>
				<td>&nbsp;&nbsp;<?php if(array_key_exists($report['consumer_id'],$this->reportAmountArray)){
					
					if(array_key_exists($report['consumer_id'],$this->reportCampaignAmountArray)){
						echo $this->reportCampaignAmountArray[$report['consumer_id']];
					}
					echo '/'.$this->reportAmountArray[$report['consumer_id']];
				}?></td>
				<td>
					<select id='state_<?php echo $i; ?>' name='state_<?php echo $i; ?>' onclick = "javascript:saveSelectedReportState('<?php echo $i; ?>')" >	
						<OPTION VALUE="LOCKED" <?php if($report['state'] !=null && $report['state'] == 'LOCKED'){?>Selected<?php }?> ><?php echo $this->translate("已被选定")?></OPTION>		
						<OPTION style= "BACKGROUND-COLOR: #CFDDED" VALUE="APPROVED" <?php if($report['state'] !=null && $report['state'] == 'APPROVED'){?>Selected<?php }?> ><?php echo $this->translate("His_Reports_APPROVED")?></OPTION>
						<OPTION style= "BACKGROUND-COLOR: #CFDDED" VALUE="UNAPPROVED" <?php if($report['state'] !=null && $report['state'] == 'UNAPPROVED'){?>Selected<?php }?>><?php echo $this->translate("His_Reports_UNAPPROVED")?></OPTION>
						<OPTION VALUE="NEW" <?php if($report['state'] != null && $report['state'] == 'NEW'){?>Selected<?php }?> ><?php echo $this->translate("His_Reports_NEW")?></OPTION>
					</select>
				</td>
				<td>
					<select id='grade_<?php echo $i; ?>' name='grade_<?php echo $i; ?>'>				
							<OPTION VALUE="0" <?php if(!array_key_exists($report_id,$this->pointArray) || $this->pointArray[$report_id] == '0'){?>Selected <?php }?> >0</OPTION>
							<OPTION VALUE="100" <?php if(array_key_exists($report_id,$this->pointArray) && $this->pointArray[$report_id] == '100'){?>Selected <?php }?> >100</OPTION>
							<OPTION VALUE="200" <?php if(array_key_exists($report_id,$this->pointArray) && $this->pointArray[$report_id] == '200'){?>Selected <?php }?> >200</OPTION>
							<OPTION VALUE="300" <?php if(array_key_exists($report_id,$this->pointArray) && $this->pointArray[$report_id] == '300'){?>Selected <?php }?> >300</OPTION>
							<OPTION VALUE="400" <?php if(array_key_exists($report_id,$this->pointArray) && $this->pointArray[$report_id] == '400'){?>Selected <?php }?> >400</OPTION>
							<OPTION VALUE="500" <?php if(array_key_exists($report_id,$this->pointArray) && $this->pointArray[$report_id] == '500'){?>Selected <?php }?> >500</OPTION>
					</select>
				</td>
				<?php if ($this->currentAdmin->id=='2'){?>
					<?php if ($report['adminname']!=null && $report['adminname']!=""){?><td> <?php echo $report['adminname']?> </td><?php } else {?><td><?php echo $this->translate("暂时没有人")?></td> <?php }?> 
				<?php }?>	
					<input type="text" id="consumer_id_<?php echo $i; ?>" name='consumer_id' value=<?php echo $report['consumer_id']?> style="display:none;"/>
					<input type="text" id="report_id_<?php echo $i; ?>" name='report_id' value=<?php echo $report['id']?> style="display:none;"/>
				<td>
					<!--<a href='#' onclick = "javascript:setStatus('<?php echo $i; ?>')" ><?php echo $this->translate('His_Reports_setting');?></a>
					--><a href="#" onclick = "javascript:showReport('<?php echo $i; ?>', '<?php echo $report['accesscode']?>', '<?php echo $report['id']?>')" ><?php echo $this->translate('Admin_Show');?></a>
					<?php if ($report['state'] !=null && $report['state'] == 'NEW'){ 
						echo $this->translate('Admin_Select_Report');
						echo "<input type='checkbox' name='reportInBatch[]' value='".$report['id']."'></input>";
					}else{
						if($report['state'] !=null && $report['state'] == 'LOCKED'){
							echo $this->translate('Admin_Report_Selected');
						}else{
							echo $this->translate('Admin_Report_Finished');
						}
					}		
					?>
					</td>
				<?php if($this->campaign->type == 'mission'){?>
				<?php if($report['cistate'] == 'COMPLETED'){?>
				<td>已经完成</td>
				<?php }else{?>
				<td><input type="button" onclick="javascript:completeMission('<?php echo $report['consumer_id']?>','<?php echo $report['campaign_id']?>')" value = "完成"/></td>
				<?php }?>
				<?php }?>
				</tr>

			
			<tr id = "tr_<?php echo $i; ?>" name = "tr_<?php echo $i; ?>" style="display:none;">		
				<td colspan="6" style ="width: 700px;"><div id = "div_<?php echo $i++; ?>" ></div></td>
			</tr>
			<?php endforeach;?>
			<input ty       pe="text" id="tr_record" value="" style="display:none;">
			<input type="text" id="reportAmount" value=<?php echo $i-1; ?> style="display:none;">
			</form>
		</table>
		 <?= $this->paginationControl($this->paginator, 'Sliding', 'pagination/pagelist.phtml', array("controller" => $this->controller, "action" => $this->action,"id"=>$this->campaign_id,"pest"=>0,"select_status"=>$this->select_status)); ?> 
		<br>
</div>
<script type="text/javascript">
function showReport(i,accesscode,report_id){
	
//	var tr = $('tr_'+i); 
	if($('tr_record').value != null && $('tr_record').value == i){
		document.getElementsByName('tr_'+i)[0].style.display = "none";
		$('tr_record').value = '';
	}else{
		if($('tr_record').value != ''){
			var j = $('tr_record').value;
			document.getElementsByName('tr_'+j)[0].style.display = "none";
		}
		document.getElementsByName('tr_'+i)[0].style.display = "";
		$('tr_record').value = i;
	}
	var url='<?php echo $this->url(array('controller'=>'report','action'=>'ajaxreport'));?>';
	var params = 'url='+'/report/showAnswer/accessCode/'+accesscode+'&accessReportId='+report_id;
	// notice the use of a proxy to circumvent the Same Origin Policy. 
	new Ajax.Request(url, 
			{
				method: 'get',   
				parameters:params,
				onSuccess: function(transport) {
				     var div = $('div_'+i);  
				     div.innerHTML =  transport.responseText;
//				     alert($F("div"));  
				}
	}); 
}


function completeMission(consumer,campaign){
	var answer = confirm ("确认完成任务吗?")
	if (answer){
		jQuery.ajax({
			   type: "POST",
			   url: "<?php echo $this->baseUrl();?>/report/admincompletemission",
			   data: "consumer=" + consumer + "&campaign=" + campaign,
			   success: function(msg){
			        alert(msg);
			        window.location.reload( true );
			   }
			 });
	}else{
		return false;
	}	
}
//根据报告的状态筛选。
function selectYesOrNo(val){
	if(val=="all"){
		val="";
	}else if (val=="nono"){
		val="NEW";
	}else if (val=="yes"){
		val="APPROVED";
	}else if (val=="nopass"){
		val="UNAPPROVED";
	}else if (val=="ordered"){
		val="LOCKED";
	}
	alert(val);
}
</script>