<img src="<?php echo $this->baseUrl();?>/images/popup-fillout-logo.gif" class="logo"/>
<div class="top-content" >
<h1><?php echo $this->translate("Submit_you_report_1"); echo ' "'.$this->campaing_name.'" '; echo $this->translate("Submit_you_report_2");?></h1>
<p><?php echo $this->translate("Wom_instruction")?></p>
</div>
<div class="clear"></div>

<?php 
if (isset($this->file)) {  // if static file exist
?>
<!--
ajax的请求放前面
-->
<script language="JavaScript" type="text/javascript">
  $('id').value = '';
  $('submit').disabled='disabled';

  var url = "<?php echo $this->url(array('controller'=>'common','action'=>'getaccesscode'));?>";
  var params = 'surveyId='+ <?php echo $this->surveyId ;?>;
  new Ajax.Request(
      url,
      {
      method: 'get',
      parameters: params,
      onSuccess: function(msg) {
          var accessCode = msg.responseText;
          $('id').value = accessCode.substring(1,accessCode.length-1);
          $('submit').disabled='';
          }
      }
  );
</script>

<?php
 include($this->file); 
} else {
    readfile("$this->filloutPage");
    
} ?>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
      Element.hide("nextPageButton");
    } else {
      Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
    var _pageElement = $("page_"+_pageIndex);
    var _currElement = $("page_"+currentPage);
    
    Element.hide(_currElement);
    Element.show(_pageElement);
  
  if($("pageNum" + _pageIndex) != undefined) {
    $("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
    $("pageNum" + _pageIndex).style.textDecoration = "underline";
  }
    if($("pageNum" + currentPage) != undefined) {   
      $("pageNum" + currentPage).style.fontWeight = "normal"; 
    $("pageNum" + currentPage).style.textDecoration = "none";
  }
  

    currentPage = _pageIndex;
  
  if(_pageIndex == pageNum) {
    Element.show($('submit'));
  } else if ( _pageIndex < pageNum) {
    Element.hide($('submit'));
  }
  }
  
  function showNextPage(){
    showPage(currentPage+1);
  }
  
  function showPrevPage(){
    showPage(currentPage-1);
  }
  
  function initPages() {
    var i;

    for (i=0; i<=pageNum; i++) {
      Element.hide($("page_"+i));
    }
    
 
    var _pageBar = document.getElementById("pageBar");
    if (pageNum==0) {
      _pageBar.innerHTML = "";
    } else {
      for (i=0; i<=pageNum; i++) {
      var s ="";
      if( i == 0 ) {
        s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
      }

      if (noPage0){
         if (i!=0){ 
          s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
          }
        }else{
          s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
        }
        
      if( i == pageNum ) {
        s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
      }
        _pageBar.innerHTML = _pageBar.innerHTML + s ;
      }   
    }
  }
  
  initPages();
  if (noPage0){
    showPage(1);
  }else{
    showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
  if(typeof checkNoAnswer=="undefined") {
    checkNoAnswer=function(index,checkbox) {
      var question = $("question_" + index);
      var checked = checkbox.checked;
      if( checked) {
        question.disabled="disabled";
        checkbox.value=false;
      } else {
        question.disabled="";
        checkbox.value=true;
      }
    };
  };
  
    if(typeof checkRadioNoAnswer=="undefined") {
    checkRadioNoAnswer = function(index,checkbox) {
      var clazz = "question_radio_" +index;
      var radios = document.getElementsByClassName(clazz).each(function(radio) {
        var checked = checkbox.checked;
          if( checked) {
          if(radio.checked="checked")radio.checked="";
          radio.disabled="disabled";
          checkbox.value=false;
          } else {
          radio.disabled="";
          checkbox.value=true;
          }
      });
    };
  }
  
  if(typeof checkSubboxes=="undefined") {
    checkSubboxes = function(qc_id) {
      //get the question context checkbox's value
      var qc_value = $("qc_checkbox_" + qc_id).checked;
      //get the checkBoxed belongs to the above question context
      var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
      for(var i = 0; i < checkBoxes.length;i++) {
        var checkBox = checkBoxes[i];
        //to reuse checkRadioNoAnswer and checkNoAnswer
        checkBox.checked=qc_value;
        var clazzName = checkBox.className;
        var question_id = clazzName.split(" ")[0].split("_")[1];
        if( clazzName.indexOf("radio") != -1) {
          checkRadioNoAnswer(question_id,checkBox);
        } else {
          checkNoAnswer(question_id,checkBox);
        }
      }
    }
    
  }
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  function loading() {
    var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
    WebDialog.showMessageBox(html, "none", "center", 600);
  }
  
  function checkMandatory() {
      var fillMandatory = true;
      for(var j=0; j < mandatoryElements.length; j++) {
        var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
      if(elements.length > 1) {
        var filled = false;
        for(var i=0; i < elements.length; i++) {
          var element = elements[i];
        if(element.checked) {
          filled = true;
          break;
        }
        }
        if(!filled) {
          fillMandatory = false;
          break;
        }
      } else {
        var element = elements[0];
        if(element.hasClassName("selection")) {
          if(element.value.strip() == '') {
            fillMandatory =  false;
            break;                                  
          }
        } else if (element.hasClassName("input-text")) {
        if(element.value == 0) {
          fillMandatory = false;
          break;
        }
        }
      }
      }
      if(!fillMandatory) {
        var html = '提交失败：必填的题目不能为空';
          jQuery("#check-alert-dialog .content").html(html);
          jQuery("#check-alert-dialog").dialog('open');
      }
    return fillMandatory;
  }
  
  function checkMandatoryOfSelectionQuestion() {
   var mandatory = false;
   $$('input.selection').each(function(element) {
                    if(element.checked) {
                      filled = true;
                      throw $break;
                    }
                                  });
   if(!filled) {
   $$('select.selection').each(function(element) {
                    if(element.value != 0) {
                      filled = true;
                      throw $break;
                    }
                                  });
   }                      
    return filled;
  }


  function checkAnswerSet() {
    if( checkAnswersOfSelectionQuestions() && checkAnswersOfRatingQuestions() && checkAnswersOfCommentQuestions()) {
        return true;
    } else {
      var html = '提交失败：不能提交空报告';
        jQuery("#check-alert-dialog .content").html(html);
        jQuery("#check-alert-dialog").dialog('open');
      return false;
    }
  }
  
  function checkAnswersOfSelectionQuestions() {
   var filled = false;
   $$('input.selection').each(function(element) {
                    if(element.checked) {
                      filled = true;
                      throw $break;
                    }
                                  });
   if(!filled) {
   $$('select.selection').each(function(element) {
                    if(element.value != 0) {
                      filled = true;
                      throw $break;
                    }
                                  });
   }                      
    return filled;
  }
  
  function checkAnswersOfRatingQuestions() {
      var filled = false;
      $$('input.rating').each(function(element) {
                    if(element.checked) {
                      filled = true;
                      throw $break;  
                    }
                                  });

     return filled;
  }
  
  function checkAnswersOfCommentQuestions() {
      var filled = false;
      $$('.input-text').each(function(element) {
                                      if(element.value.strip() != '') {
                                          filled = true;
                                        throw $break;                                 
                                      }
                                  });
     return filled;
  }
  
  function locateErrorPage() {
    var errorElements = $$('span.error-content') ;
    var hasError = false;
    var errorElementsPointer = 0;
    for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
      var html = errorElements[errorElementsPointer].innerHTML;
      if (html != "") {
        hasError = true;
        break;
      }
    }
    if( hasError ) {
      var errorParentElement = errorElements[errorElementsPointer].up('div');
      while (errorParentElement != undefined) {
      var elementId = errorParentElement.id;
      if (elementId != undefined && elementId.indexOf('page') != -1) {
        var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
        showPage(errorPageNum);
        break;
    }
    errorParentElement = errorParentElement.up('div');
    }
    }
  }
  locateErrorPage();
  
  function showOtherValueInputInSelect(element) {
      var options = element.options;
      var selectedOption;
      for( var i = 0; i < options.length; i++) {
         if( options[i].selected) {
           selectedOption = options[i];
         }
      }
      var selectedOptionId = selectedOption.id;
      if( selectedOptionId.indexOf("other") != -1) {
        $(element.id + "_other").show();
      } else {
          $(element.id + "_other").value = "";
        $(element.id + "_other").hide();
      }
  }
  
  function showOtherValueInputInRadio(element) {
    var elementId = element.id.split("_")[0];
    var value = element.value;
    if( value == 0 ) {
      $(elementId + "_other_input").show();
    } else {
        $(elementId + "_other_input").value = "";
      $(elementId + "_other_input").hide();
    }
  }
  function showOtherValueInputInCheckBox(element) {
    var elementId = element.id.split("_")[0];
    var value = element.value;
    if( element.checked ) {
      $(elementId + "_other_input").show();
    } else {
        $(elementId + "_other_input").value = "";
      $(elementId + "_other_input").hide();
    }
  }

  /*
  new PeriodicalExecuter(function() {
    $('fillout').request({
        method: 'post',
        parameters: { 'command.pause':"Continue Later"}
    });
    }, 5);
  */

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


  
// ]]>
-->
</script>