<!-- <img src="<?php echo $this->baseUrl();?>/images/popup-fillout-logo.gif" class="logo"/> -->
<img style="width:107px;" src="<?php echo $this->baseUrl();?>/images/logo_wildfire02.png" class="logo"/>
<div class="top-content" >
<h1><?php echo $this->translate("Submit_you_report_1"); echo $this->campaing_name; echo $this->translate("Submit_you_report_2");?></h1>
<p><?php echo $this->translate("Wom_instruction")?></p>
</div>
<div class="clear"></div>

<?php 
if (isset($this->file)) {  // if static file exist
?>
<!--
ajax的请求放前面
-->
<script language="JavaScript" type="text/javascript">
  $('id').value = '';
  $('submit').disabled='disabled';

  var url = "<?php echo $this->url(array('controller'=>'common','action'=>'getaccesscode'));?>";
  var params = 'surveyId='+ <?php echo $this->surveyId ;?>;
  new Ajax.Request(
      url,
      {
      method: 'get',
      parameters: params,
      onSuccess: function(msg) {
          var accessCode = msg.responseText;
          $('id').value = accessCode.substring(1,accessCode.length-1);
          $('submit').disabled='';
          }
      }
  );
</script>

<?php
 include($this->file); 
} else {
    readfile("$this->filloutPage");
    
} ?>

<!--<?php if (isset($this->file)) { ?>
<script language="JavaScript" type="text/javascript">
  $('id').value = '';
  $('submit').disabled='disabled';
  alert(3);
  var url = "<?php echo $this->url(array('controller'=>'common','action'=>'getaccesscode'));?>";
  var params = 'surveyId='+ <?php echo $this->surveyId ;?>;
  new Ajax.Request(
      url,
      {
      method: 'get',
      parameters: params,
      onSuccess: function(msg) {
          var accessCode = msg.responseText;
          $('id').value = accessCode.substring(1,accessCode.length-1);
          $('submit').disabled='';
          }
      }
  );
</script>
<?php }else { ?>
<script language="JavaScript" type="text/javascript">
alert(4);
</script>
<?php }?>
--><!-- 
<div class="content" style="background:#fff;padding-top:0;">
	<div class="buttons-bar">
	<a href='<?php echo $this->url(array('controller'=>'campaign','action'=>'description', 'id'=>$this->id));?>'>Back</a>
	<div style="clear:both"></div>
	</div>
</div>
 -->