<link href="<?php echo $this->baseUrl();?>/uploadify/uploadify.css" type="text/css" rel="stylesheet" />
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/uploadify/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/uploadify/swfobject.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/uploadify/jquery.uploadify.v2.1.4.min.js"></script>
<script type="text/javascript">
jQuery(document).ready(function() {
  jQuery('#file_upload').uploadify({
    'uploader'  : '<?php echo $this->baseUrl();?>/uploadify/uploadify.swf',
    'script'    : '<?php echo $this->baseUrl();?>/uploadify/uploadify.php?param=<?php echo $this->reportId;?>_<?php echo $this->consumer;?>',
    'cancelImg' : '<?php echo $this->baseUrl();?>/images/cancel.png',
    'folder'    : '<?php echo $this->baseUrl();?>/uploads',
    'auto'           : true,
    'fileExt'        : '*.jpg;*.gif;*.png',
    'fileDesc'       : 'Image Files (.JPG, .GIF, .PNG)',
    'queueID'        : 'custom-queue',
    'queueSizeLimit' : 3,
    'simUploadLimit' : 3,
    'removeCompleted': false,
    'multi'          : true,
    'sizeLimit'      : 10240000,  //10MB
    'onAllComplete'  : function(event,data) {
	    //jQuery('#status-message').text(data.filesUploaded + ' 文件上传成功, ' + data.errors + ' 错误.');
  }

});
});
</script>

<div id='fb-root'></div>
<script src='http://connect.facebook.net/en_US/all.js'></script>

<script> 
  FB.init({appId: "234132663359597", status: true, cookie: false});

  function postToFeed() {
    // calling the API ...
    var obj = {
      method: 'feed',
      link: 'community.wildfire.asia/public/report/thankyou',
      // picture: 'http://fbrell.com/f8.jpg',
      name: 'Wildfire Asia',
      caption: 'Wildfire Asia',
      description: 'Try a product, share your experience with your friends, let us know what they say and get rewards.'
    };
    FB.ui(obj, function(response) {
      post_id = response.post_id;
      data = {post_id: post_id, platform: 'facebook'};
      jQuery.ajax({
        type: "GET",
        url: "recordsns",
        contentType: "application/json",
        data: data,
        success: function(data){
        }
      });
    });
  }

</script>


<div class="article-box" style="height:120px;">
	<div class="article-box-inner" style="margin-bottom: 20px;">
		<h2><?php echo $this->translate('Thanks_For_report')?></h2>
		<p style="padding-top: 10px;"><?php echo $this->translate('Thanks_For_Report_Content1')?>
          <br/>
      </p>
      <p><?php echo $this->translate('Choose_file')?></p>
      <form  id="uploadImage" action="" method="post" enctype="multipart/form-data">
        <table>
            <tr>
                <td><?php echo $this->form->image;?></td>
                <td style="color:red">&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->translate('Upload_hint');?></td>
            </tr>
            <tr>
                <td><?php echo $this->form->submit;?></td>
                <tr>
                </table>
            </form>
            <?php if($this->saved == 1){?>
            <h3><?php echo $this->translate('Successful_upload')?></h3>
            <?php }?>
            <?php if($this->saved == -1){?>
            <h3><?php echo $this->translate('Unsuccessful_upload');?></h3>
            <?php }?>

            <div class="buttons-bar" style="padding-top: 10px;">
               <a class="big-button-blue" target="_parent"  href="<?php echo $this->url(array('controller'=>'home','action'=>'index'));?>">
                <?php echo $this->translate('Take_Me_Home')?>
            </a>
        </div>
    </div>

    <a onclick='postToFeed(); return false;' style="float: left;margin: 1px 5px 0 0;"><img src="<?php echo $this->baseUrl()?>/images/sns/facebook.png"></a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <a href="https://twitter.com/share" class="twitter-share-button" data-lang="en">Tweet</a>
</div>

