

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" lang="en-gb">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="robots" content="index, follow" />
<meta name="keywords" content="word-of-mouth marketing" />
<meta name="title" content="Sign Up" />
<meta name="author" content="Wang Weiqi" />
<meta name="description"
	content="Wildfire XingXingHuo - Asias Word-of-Mouth Community" />
<meta name="generator"
	content="Joomla! 1.5 - Open Source Content Management" />
<title><?php echo $this->translate('Login_Title');?></title>
<link href="/public/favicon.ico" rel="shortcut icon" type="image/x-icon" />
<link rel="stylesheet"
	href="<?php echo $this->joomlahome;?>/modules/mod_jflanguageselection/tmpl/mod_jflanguageselection.css"
	type="text/css" />
<link rel="stylesheet"
	href="<?php echo $this->joomlahome;?>/modules/mod_jflanguageselection/tmpl/mod_jflanguageselection.css"
	type="text/css" />
<script type="text/javascript" media="screen"
	src="<?php echo $this->baseUrl();?>/js/prototype-1.6.0.2.js"></script>


<link rel="stylesheet"
	href="<?php echo $this->joomlahome;?>/templates/wildfire_obsidian/css/general.css"
	type="text/css" />
<!--[if lte IE 6]>
<link href="<?php echo $this->joomlahome;?>/templates/wildfire_obsidian/css/ieonly.css"  rel="stylesheet" type="text/css" />
<![endif]-->
</head>

<body>
	<div class="header"><div class="header-inner">
		<div class="logo">
			<a href="<?php echo $this->joomlahome;?>"><img src="<?php echo $this->joomlahome;?>/templates/wildfire_obsidian/images/mainlogo.gif" /></a>
		</div>
		<div class="login-panel">
			<form action="<?php echo $this->url(array('controller'=>'login','action'=>'login'));?>" method="post">
				<div class="user-info">
					<label for="username" style='width:65px;'><?php echo $this->translate("Common_Username")?></label>

					<input type="text" name="username" id="username"/>
					<label for="password"><?php echo $this->translate("Common_Password")?></label>
					<input type="password" name="password" id="password"/>
				</div>
				<input type="submit" name="login" value=<?php echo $this->translate("Common_login")?> />
				<input type="button" name="help" value=<?php echo $this->translate("Common_help")?> />
			</form>
		</div>

		<div class="navigator">
			<ul id="mainlevel-nav"><li><a href="<?php echo $this->joomlahome;?>/index.php?option=com_content&amp;view=frontpage&amp;Itemid=1&amp;lang=zh" class="mainlevel-nav" ><?php echo $this->translate("Common_home")?></a></li>
			<li><a href="<?php echo $this->joomlahome;?>/index.php?option=com_content&amp;view=article&amp;id=48&amp;Itemid=53&amp;lang=zh" class="mainlevel-nav" id="active_menu-nav"><?php echo $this->translate("Common_about_us")?></a></li>
			<li><a href="<?php echo $this->joomlahome;?>/index.php?option=com_content&amp;view=article&amp;id=49&amp;Itemid=54&amp;lang=zh" class="mainlevel-nav" ><?php echo $this->translate("Common_about_Sparks")?></a></li>
			<li><a href="<?php echo $this->joomlahome;?>/index.php?option=com_content&amp;view=article&amp;id=50&amp;Itemid=56&amp;lang=zh" class="mainlevel-nav" ><?php echo $this->translate("Common_hire_us")?></a></li></ul>
			<div class="language-selector">
			<div id="jflanguageselection">
				<ul class="jflanguageselection"><li id="active_language"><a href="<?php echo $this->url(array('controller'=>'language','action'=>'index','lang'=>'zh'));?>"><span lang="zh" xml:lang="zh">中文&nbsp;&nbsp;&nbsp;&nbsp;</span></a></li><li><a href="<?php echo $this->url(array('controller'=>'language','action'=>'index','lang'=>'en'));?>" ><span lang="en" xml:lang="en">English</span></a></li></ul></div>		
				<div id="jflanguageselection"></div>
			</div>
		</div>

		<div class="clear"></div>
	</div></div>
	<div class="container"><div class="container-inner">
		<div class="banner">
			<img src="<?php echo $this->joomlahome;?>/templates/wildfire_obsidian/images/banner-sample.jpg"/>
		</div>
		
		<div class="contents-3-col">
			<div class="edit-profile">
			<?php if($this->phoneErr == null ){?>
			<h1 style="margin-left:0;"><?php echo $this->translate("Check_you_phone")?></h1>
			<div style="clear: both;"></div>
			<p><?php echo $this->translate("Check_you_phone_Content1")?><?php echo $this->crypt_login_phone;?><?php echo $this->translate("Check_you_phone_Content2")?></p>

            <div style="clear: both;"></div>
            <div class="buttons-bar">
                <input id="gotoreset" target='_parent' class="button" onclick="window.location.href='<?php echo $this->url(array('controller'=>'forgetpassword', 'action'=>'reset'));?>'" type='button'  value='<?php echo $this->translate("Reset_password")?>'></input>
            </div>

			<?php } else{?>
					<h1 style="margin-left:0;"><?php echo $this->phoneErr; ?></h1>
			
					<div style="clear: both;"></div>
					<div class="buttons-bar">
                        <input id="changepassword" target='_parent' class="button" onclick="window.location.href='<?php echo $this->url(array('controller'=>'forgetpassword', 'action'=>'index'));?>'" type='button'  value='<?php echo $this->translate("Back")?>'></input>
					</div>
			<?php }?>
			
			</div>
		</div>
		<div class="clear"></div>
	</div></div>

	<div class="footer">
	<div class="footer-inner">
		<div class="moduletable bottom_menu">
	
			<table width="100%" border="0" cellpadding="0" cellspacing="1">
			<tr><td nowrap="nowrap"><a href="<?php echo $this->joomlahome;?>/index.php?option=com_content&amp;view=article&amp;id=51&amp;Itemid=58&amp;lang=zh" class="mainlevel" ><?php echo $this->translate('Common_Contacts');?></a>
			<a href="<?php echo $this->joomlahome;?>/index.php?option=com_content&amp;view=article&amp;id=87&amp;Itemid=59&amp;lang=zh" class="mainlevel" ><?php echo $this->translate('Common_Privacy_Policy');?></a>
			<a href="<?php echo $this->joomlahome;?>/index.php?option=com_content&amp;view=article&amp;id=88&amp;Itemid=60&amp;lang=zh" class="mainlevel" ><?php echo $this->translate('Common_Terms_and_Conditions');?></a>
			<a href="<?php echo $this->joomlahome;?>/index.php?option=com_content&amp;view=article&amp;id=89&amp;Itemid=61&amp;lang=zh" class="mainlevel" ><?php echo $this->translate('Common_Jobs');?></a>
			<a href="<?php echo $this->joomlahome;?>/index.php?option=com_content&amp;view=article&amp;id=90&amp;Itemid=62&amp;lang=zh" class="mainlevel" ><?php echo $this->translate('Common_Investors');?></a></td>
			</tr></table>
		</div>
    </div></div>
</body>
</html>