<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/sns.js"></script>
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/sns.css" />

<div style="padding-left: 15px;font-size: 16px;">
	Manage your sns accounts
</div>

<div id="snss-panel">
	<?php if(isset($this->users)) {?>
		<? foreach ($this->users as $user) { ?>
			<div class="sns-box" sns-id="<?php echo $user.id ?>" source="<?php echo $user.source ?>">
        <img src="<?php echo $user.big_profile_img_path ?>" style="width:150px;margin:10px;"/>
				<div style="font-size:120%;font-weight:bold;">
					<span class="snsico <?php echo $user.source ?>_ico"><?php echo $user.nick ?></span>
				</div>
			</div>
		<?}
		}
	?>	
	<div class="sns-box new">
			<div style="padding-top:90px;font-size: 150%;"><a href="javascript:void(0);">添加账户</a></div>
	</div>
	<div style="clear:both;"></div>
</div>

<div id="editSnsModal" class="modal hide fade">
	<div class="modal-header">
	    <a data-dismiss="modal" class="close">×</a>
	    <h3 id="editSnsModalTitle">添加账户</h3>
	</div>
	<div class="modal-body">
		<ul class="thumbnails">
			<?php foreach($this->sns_enabled_source as $sns) {?>
	        <li class="span3" style="width:auto;">
	          <a class="thumbnail" href="javascript:void(0);" onclick='requestToken("<?php echo $sns['name']?>", "<?php echo $this->writer_host?>");'>
	            <img style="width:128px; height:128px;" alt="" src="<?php echo $this->baseUrl().'/images/sns/'.$sns['name']?>.png">
	          </a>
	        </li>
			<?}?>
	  </ul>
		<iframe id="oauthWindow" style="display:none;border:none;overflow-y:auto;overflow-x:hidden;" width="100%" height="100%"></iframe>
	</div>
	<div class="modal-footer">
	    <a data-dismiss="modal" class="btn" href="#">Close</a>
	</div>
</div>