<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<META NAME="ROBOTS" CONTENT="NOINDEX,NOFOLLOW">
	<title>Indicate - Fill out survey</title>
	<link href="/css/crystal.css" rel="stylesheet" type="text/css" media="screen, print" />
	<!--[if IE]>
	<link href="/css/crystal-ie.css" rel="stylesheet" type="text/css" media="screen" />
	<![endif]-->
	<link href="/css/fillout_default.css" rel="stylesheet" type="text/css" media="screen" />
	<!--[if IE]>
	<link href="/css/fillout_default-ie.css" rel="stylesheet" type="text/css" media="screen" />
	<![endif]-->
	<link href="/css/niftyCorners.css" rel="stylesheet" type="text/css" media="screen" />
	<script src="/js/all.js" language="JavaScript" type="text/javascript"></script>
	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
</head>

<body>
<div class="main-container-outer">
	<div id="container">
		<div id="header" class="header">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<!--<div class="main-logo" id="main-logo">
				<a href="http://www.wildfire.asia" target="_blank">
					<img src="/survey/logoImage/13" style="height:70px; width:301px" />
				</a>
			</div>-->
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content">
 		

<div id="content">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://i2.wildfire.asia/fillout" onsubmit="return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">

<div class="questionnaire-title">Nestle Pre-Campaign Survey</div>


<input type="hidden" name="id" value="" id="id" />
<input type="hidden" name="theme" value="default" id="theme" />

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_39" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						How likely are you to recommend NAN MOM&amp;me to your family, colleagues or friends?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[104].value" ></span>
<input type="hidden" name="answers[104].id" value="" id="answers[104].id" />
<table>
<tr>

<td>

<div class="left-label">&nbsp;&nbsp;&nbsp;&nbsp;0:will not recommend</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[104].value" value="0" id="104_0" group="104" class="question_radio_104 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[104].value" value="1" id="104_1" group="104" class="question_radio_104 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[104].value" value="2" id="104_2" group="104" class="question_radio_104 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[104].value" value="3" id="104_3" group="104" class="question_radio_104 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[104].value" value="4" id="104_4" group="104" class="question_radio_104 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[104].value" value="5" id="104_5" group="104" class="question_radio_104 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[104].value" value="6" id="104_6" group="104" class="question_radio_104 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[104].value" value="7" id="104_7" group="104" class="question_radio_104 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[104].value" value="8" id="104_8" group="104" class="question_radio_104 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[104].value" value="9" id="104_9" group="104" class="question_radio_104 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[104].value" value="10" id="104_10" group="104" class="question_radio_104 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">&nbsp;10:certainly recommend</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[104].value" value="" id="answers[104].value" class="q_104 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_40" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						If you were to recommend NAN MOM&amp;me, why would you recommend it?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[105].id" value="" id="answers[105].id" />
<textarea name="answers[105].value" id="question_105" cols="40" group="105" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[105].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_41" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Have you bought NAN MOM&amp;me in the past 3 months?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[106].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[106].id" value="" id="answers[106].id" />
<ul>
	<li>
			<input group="106" type="radio" id="106_0" name="answers[106].value" value="148"  class="selection question_radio_106" onclick="showOrHide()"  />		<label for="106_0">yes</label>
	</li>
	<li>
			<input group="106" type="radio" id="106_1" name="answers[106].value" value="149"  class="selection question_radio_106"  onclick="showOrHide()" />		<label for="106_1">no</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_106  qc_0 radio" type="radio" name="answers[106].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
function showOrHide(){
	if(document.getElementById("106_0").checked){
		document.getElementById("q_42").style.display="";
		document.getElementById("q_43").style.display="";
		document.getElementById("q_44").style.display="";
	}else{
		document.getElementById("q_42").style.display="none";
		document.getElementById("q_43").style.display="none";
		document.getElementById("q_44").style.display="none";
	}
	
}
</script>
		  <div id="q_42" style="margin-bottom:0px; display:none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						How often have you bought NAN MOM&amp;me in the past 3 months?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[107].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[107].id" value="" id="answers[107].id" />
<ul>
	<li>
			<input group="107" type="radio" id="107_0" name="answers[107].value" value="150"  class="selection question_radio_107"  />		<label for="107_0">Once</label>
	</li>
	<li>
			<input group="107" type="radio" id="107_1" name="answers[107].value" value="151"  class="selection question_radio_107"  />		<label for="107_1">About once per month</label>
	</li>
	<li>
			<input group="107" type="radio" id="107_2" name="answers[107].value" value="152"  class="selection question_radio_107"  />		<label for="107_2">About twice per month</label>
	</li>
	<li>
			<input group="107" type="radio" id="107_3" name="answers[107].value" value="153"  class="selection question_radio_107"  />		<label for="107_3">About three times per month</label>
	</li>
	<li>
			<input group="107" type="radio" id="107_4" name="answers[107].value" value="154"  class="selection question_radio_107"  />		<label for="107_4">More than three times per month</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_107  qc_0 radio" type="radio" name="answers[107].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_43" style="margin-bottom:0px; display:none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						How many packs do you usually buy together?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[108].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[108].id" value="" id="answers[108].id" />
<ul>
	<li>
			<input group="108" type="radio" id="108_0" name="answers[108].value" value="155"  class="selection question_radio_108"  />		<label for="108_0">One</label>
	</li>
	<li>
			<input group="108" type="radio" id="108_1" name="answers[108].value" value="156"  class="selection question_radio_108"  />		<label for="108_1">Two</label>
	</li>
	<li>
			<input group="108" type="radio" id="108_2" name="answers[108].value" value="157"  class="selection question_radio_108"  />		<label for="108_2">Three</label>
	</li>
	<li>
			<input group="108" type="radio" id="108_3" name="answers[108].value" value="158"  class="selection question_radio_108"  />		<label for="108_3">Four</label>
	</li>
	<li>
			<input group="108" type="radio" id="108_4" name="answers[108].value" value="159"  class="selection question_radio_108"  />		<label for="108_4">More than four</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_108  qc_0 radio" type="radio" name="answers[108].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_44" style="margin-bottom:0px; display:none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Where did you buy the product?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[109].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[109].id" value="" id="answers[109].id" />




<span id="hint_109">
</span>
<ul>
	<li>
			<input group="109" class="question_radio_109 selection" type="checkbox" id="109_0" name="answers[109].value" value="160" 	onclick=" showOrHide2()"/>		<label for="109_0">FairPrice</label>
	</li>
	<li>
			<input group="109" class="question_radio_109 selection" type="checkbox" id="109_1" name="answers[109].value" value="161" 	onclick=" showOrHide2()"/>		<label for="109_1">ColdStorage</label>
	</li>
	<li>
			<input group="109" class="question_radio_109 selection" type="checkbox" id="109_2" name="answers[109].value" value="162" 	onclick=" showOrHide2()"/>		<label for="109_2">Giant</label>
	</li>
	<li>
			<input group="109" class="question_radio_109 selection" type="checkbox" id="109_3" name="answers[109].value" value="163" 	onclick=" showOrHide2()"/>		<label for="109_3">ShengSiong</label>
	</li>
	<li>
			<input group="109" class="question_radio_109 selection" type="checkbox" id="109_4" name="answers[109].value" value="164" 	onclick=" showOrHide2()"/>		<label for="109_4">Carrefour</label>
	</li>
	<li>
			<input group="109" class="question_radio_109 selection" type="checkbox" id="109_5" name="answers[109].value" value="165" 	onclick=" showOrHide2()"/>		<label for="109_5">Other: [please specify]</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
function showOrHide2(){
	if(document.getElementById("109_5").checked){
		document.getElementById("q_45").style.display="";
	}else{
		document.getElementById("q_45").style.display="none";
	}
}
</script>
		  <div id="q_45" style="margin-bottom:0px; display:none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Other place
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[110].id" value="" id="answers[110].id" />
<input type="text" name="answers[110].value" value="" id="question_110" group="110" class="input-text" />

<span class="error-content" id="err_answers[110].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_46" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Where would you prefer to shop for prenantal/maternal supplement?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[111].id" value="" id="answers[111].id" />
<input type="text" name="answers[111].value" value="" id="question_111" group="111" class="input-text" />

<span class="error-content" id="err_answers[111].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_47" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						How likely are you to buy NAN MOM&amp;me in the coming three months?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[112].value" ></span>
<input type="hidden" name="answers[112].id" value="" id="answers[112].id" />
<table>
<tr>

<td>

<div class="left-label">&nbsp;&nbsp;&nbsp;&nbsp;0:definitely not buy&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[112].value" value="0" id="112_0" group="112" class="question_radio_112 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[112].value" value="1" id="112_1" group="112" class="question_radio_112 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[112].value" value="2" id="112_2" group="112" class="question_radio_112 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[112].value" value="3" id="112_3" group="112" class="question_radio_112 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[112].value" value="4" id="112_4" group="112" class="question_radio_112 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[112].value" value="5" id="112_5" group="112" class="question_radio_112 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">&nbsp;&nbsp;5:will definitely buy</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[112].value" value="" id="answers[112].value" class="q_112 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_48" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						In the past 3 months, have you tried NAN MOM&amp;me?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[113].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[113].id" value="" id="answers[113].id" />
<ul>
	<li>
			<input group="113" type="radio" id="113_0" name="answers[113].value" value="166"  class="selection question_radio_113"  />		<label for="113_0">yes</label>
	</li>
	<li>
			<input group="113" type="radio" id="113_1" name="answers[113].value" value="167"  class="selection question_radio_113"  />		<label for="113_1">no</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_113  qc_0 radio" type="radio" name="answers[113].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_49" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Before this campaign started, had you heard of the brand NAN MOM&amp;me?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[114].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[114].id" value="" id="answers[114].id" />
<ul>
	<li>
			<input group="114" type="radio" id="114_0" name="answers[114].value" value="168"  class="selection question_radio_114"  />		<label for="114_0">yes</label>
	</li>
	<li>
			<input group="114" type="radio" id="114_1" name="answers[114].value" value="169"  class="selection question_radio_114"  />		<label for="114_1">no</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_114  qc_0 radio" type="radio" name="answers[114].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_50" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Where did you hear of this brand?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[115].id" value="" id="answers[115].id" />
<input type="text" name="answers[115].value" value="" id="question_115" group="115" class="input-text" />

<span class="error-content" id="err_answers[115].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_51" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Before this campaign started, were you aware of any pre-natal nutrition product?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[116].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[116].id" value="" id="answers[116].id" />
<ul>
	<li>
			<input group="116" type="radio" id="116_0" name="answers[116].value" value="170"  class="selection question_radio_116"  />		<label for="116_0">yes</label>
	</li>
	<li>
			<input group="116" type="radio" id="116_1" name="answers[116].value" value="171"  class="selection question_radio_116"  />		<label for="116_1">no</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_116  qc_0 radio" type="radio" name="answers[116].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_52" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						If yes, which brand(s)?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[117].id" value="" id="answers[117].id" />
<textarea name="answers[117].value" id="question_117" cols="40" group="117" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[117].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
<div class="question-title">
How would you rate NAN MOM&me on the following attributes? <br>
						(If you don't know, please leave it blank.)
</div>
		  <div id="q_53" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
						&nbsp;&nbsp;&nbsp;&nbsp;NAN MOM&amp;me is high in folic acid, which supports the foetus’s  overall growth &amp; development
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[118].value" ></span>
<input type="hidden" name="answers[118].id" value="" id="answers[118].id" />
<table>
<tr>

<td>

<div class="left-label">disagree</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[118].value" value="1" id="118_1" group="118" class="question_radio_118 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[118].value" value="2" id="118_2" group="118" class="question_radio_118 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[118].value" value="3" id="118_3" group="118" class="question_radio_118 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[118].value" value="4" id="118_4" group="118" class="question_radio_118 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[118].value" value="5" id="118_5" group="118" class="question_radio_118 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">agree</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[118].value" value="" id="answers[118].value" class="q_118 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_54" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
						&nbsp;&nbsp;&nbsp;&nbsp;NAN MOM&amp;me is the highest in DHA compared to all other maternal milks in Singapore
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[119].value" ></span>
<input type="hidden" name="answers[119].id" value="" id="answers[119].id" />
<table>
<tr>

<td>

<div class="left-label">disagree</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[119].value" value="1" id="119_1" group="119" class="question_radio_119 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[119].value" value="2" id="119_2" group="119" class="question_radio_119 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[119].value" value="3" id="119_3" group="119" class="question_radio_119 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[119].value" value="4" id="119_4" group="119" class="question_radio_119 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[119].value" value="5" id="119_5" group="119" class="question_radio_119 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">agree</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[119].value" value="" id="answers[119].value" class="q_119 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_55" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
						&nbsp;&nbsp;&nbsp;&nbsp;NAN MOM&amp;me contains calcium for strong bones&amp; teeth
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[120].value" ></span>
<input type="hidden" name="answers[120].id" value="" id="answers[120].id" />
<table>
<tr>

<td>

<div class="left-label">disagree</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[120].value" value="1" id="120_1" group="120" class="question_radio_120 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[120].value" value="2" id="120_2" group="120" class="question_radio_120 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[120].value" value="3" id="120_3" group="120" class="question_radio_120 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[120].value" value="4" id="120_4" group="120" class="question_radio_120 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[120].value" value="5" id="120_5" group="120" class="question_radio_120 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">agree</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[120].value" value="" id="answers[120].value" class="q_120 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_56" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
						&nbsp;&nbsp;&nbsp;&nbsp;NAN MOM&amp;me is lower in fat than other brands of maternal milk
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[121].value" ></span>
<input type="hidden" name="answers[121].id" value="" id="answers[121].id" />
<table>
<tr>

<td>

<div class="left-label">disagree</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[121].value" value="1" id="121_1" group="121" class="question_radio_121 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[121].value" value="2" id="121_2" group="121" class="question_radio_121 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[121].value" value="3" id="121_3" group="121" class="question_radio_121 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[121].value" value="4" id="121_4" group="121" class="question_radio_121 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[121].value" value="5" id="121_5" group="121" class="question_radio_121 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">agree</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[121].value" value="" id="answers[121].value" class="q_121 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_57" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
						&nbsp;&nbsp;&nbsp;&nbsp;NAN MOM&amp;me provides additional nutrients to support pregnancy &amp; breastfeeding
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[122].value" ></span>
<input type="hidden" name="answers[122].id" value="" id="answers[122].id" />
<table>
<tr>

<td>

<div class="left-label">disagree</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[122].value" value="1" id="122_1" group="122" class="question_radio_122 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[122].value" value="2" id="122_2" group="122" class="question_radio_122 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[122].value" value="3" id="122_3" group="122" class="question_radio_122 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[122].value" value="4" id="122_4" group="122" class="question_radio_122 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[122].value" value="5" id="122_5" group="122" class="question_radio_122 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">agree</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[122].value" value="" id="answers[122].value" class="q_122 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_58" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
						&nbsp;&nbsp;&nbsp;&nbsp;NAN MOM&amp;me provides important vitamins and minerals (iron, zinc, vitamin A,D,E,C)
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[123].value" ></span>
<input type="hidden" name="answers[123].id" value="" id="answers[123].id" />
<table>
<tr>

<td>

<div class="left-label">disagree</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[123].value" value="1" id="123_1" group="123" class="question_radio_123 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[123].value" value="2" id="123_2" group="123" class="question_radio_123 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[123].value" value="3" id="123_3" group="123" class="question_radio_123 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[123].value" value="4" id="123_4" group="123" class="question_radio_123 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[123].value" value="5" id="123_5" group="123" class="question_radio_123 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">agree</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[123].value" value="" id="answers[123].value" class="q_123 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_59" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Have you ever received a sample of NAN MOM&amp;me?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[124].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[124].id" value="" id="answers[124].id" />
<ul>
	<li>
			<input group="124" type="radio" id="124_0" name="answers[124].value" value="172"  class="selection question_radio_124"  />		<label for="124_0">yes</label>
	</li>
	<li>
			<input group="124" type="radio" id="124_1" name="answers[124].value" value="173"  class="selection question_radio_124"  />		<label for="124_1">no</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_124  qc_0 radio" type="radio" name="answers[124].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_60" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Where did you receive this sample?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[125].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[125].id" value="" id="answers[125].id" />
<ul>
	<li>
			<input group="125" type="radio" id="125_0" name="answers[125].value" value="174"  class="selection question_radio_125" onclick="showOrHide3()" />		<label for="125_0">Prenatal class</label>
	</li>
	<li>
			<input group="125" type="radio" id="125_1" name="answers[125].value" value="175"  class="selection question_radio_125"  onclick="showOrHide3()"/>		<label for="125_1">Doctor</label>
	</li>
	<li>
			<input group="125" type="radio" id="125_2" name="answers[125].value" value="176"  class="selection question_radio_125" onclick="showOrHide3()" />		<label for="125_2">Friend</label>
	</li>
	<li>
			<input group="125" type="radio" id="125_3" name="answers[125].value" value="177"  class="selection question_radio_125"  onclick="showOrHide3()"/>		<label for="125_3">Relatives</label>
	</li>
	<li>
			<input group="125" type="radio" id="125_4" name="answers[125].value" value="178"  class="selection question_radio_125" onclick="showOrHide3()" />		<label for="125_4">Pharmacy</label>
	</li>
	<li>
			<input group="125" type="radio" id="125_5" name="answers[125].value" value="179"  class="selection question_radio_125"  onclick="showOrHide3()" />		<label for="125_5">Other: [please specify]</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_125  qc_0 radio" type="radio" name="answers[125].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
function showOrHide3(){
	if(document.getElementById("125_5").checked){
		document.getElementById("q_61").style.display="";
	}else{
		document.getElementById("q_61").style.display="none";
	}
}
</script>
		  <div id="q_61" style="margin-bottom:0px; display:none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Other
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[126].id" value="" id="answers[126].id" />
<input type="text" name="answers[126].value" value="" id="question_126" group="126" class="input-text" />

<span class="error-content" id="err_answers[126].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_62" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Whose advice would you trust most when recommending maternal supplements?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[127].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[127].id" value="" id="answers[127].id" />
<ul>
	<li>
			<input group="127" type="radio" id="127_0" name="answers[127].value" value="180"  class="selection question_radio_127" onclick="showOrHide4()" />		<label for="127_0">Gynecologist or doctor</label>
	</li>
	<li>
			<input group="127" type="radio" id="127_1" name="answers[127].value" value="181"  class="selection question_radio_127" onclick="showOrHide4()" />		<label for="127_1">Friends</label>
	</li>
	<li>
			<input group="127" type="radio" id="127_2" name="answers[127].value" value="182"  class="selection question_radio_127"  onclick="showOrHide4()"/>		<label for="127_2">Relatives</label>
	</li>
	<li>
			<input group="127" type="radio" id="127_3" name="answers[127].value" value="183"  class="selection question_radio_127" onclick="showOrHide4()" />		<label for="127_3">Husband</label>
	</li>
	<li>
			<input group="127" type="radio" id="127_4" name="answers[127].value" value="184"  class="selection question_radio_127" onclick="showOrHide4()" />		<label for="127_4">Hospital/clinic nurses</label>
	</li>
	<li>
			<input group="127" type="radio" id="127_5" name="answers[127].value" value="185"  class="selection question_radio_127" onclick="showOrHide4()" />		<label for="127_5">Pharmacist</label>
	</li>
	<li>
			<input group="127" type="radio" id="127_6" name="answers[127].value" value="186"  class="selection question_radio_127"  onclick="showOrHide4()" />		<label for="127_6">Online sources, [please specify]</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_127  qc_0 radio" type="radio" name="answers[127].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide4(){
	if(document.getElementById("127_6").checked){
		document.getElementById("q_30").style.display="";
	}else{
		document.getElementById("q_30").style.display="none";
	}
}
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_30" style="margin-bottom:0px; display:none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Other people
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[128].id" value="" id="answers[128].id" />
<input type="text" name="answers[128].value" value="" id="question_128" group="128" class="input-text" />

<span class="error-content" id="err_answers[128].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_64" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Which is your most preferred form of prenatal/ maternal supplement?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[129].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[129].id" value="" id="answers[129].id" />
<ul>
	<li>
			<input group="129" type="radio" id="129_0" name="answers[129].value" value="187"  class="selection question_radio_129" onclick="showOrHide5()" />		<label for="129_0">Pills</label>
	</li>
	<li>
			<input group="129" type="radio" id="129_1" name="answers[129].value" value="188"  class="selection question_radio_129"  onclick="showOrHide5()"/>		<label for="129_1">Cereal bar</label>
	</li>
	<li>
			<input group="129" type="radio" id="129_2" name="answers[129].value" value="189"  class="selection question_radio_129" onclick="showOrHide5()" />		<label for="129_2">Milk-based beverage</label>
	</li>
	<li>
			<input group="129" type="radio" id="129_3" name="answers[129].value" value="190"  class="selection question_radio_129"  onclick="showOrHide5()"/>		<label for="129_3">Non-dairy beverage (fruit based)</label>
	</li>
	<li>
			<input group="129" type="radio" id="129_4" name="answers[129].value" value="191"  class="selection question_radio_129" onclick="showOrHide5()" />		<label for="129_4">Snack (biscuit, oatmeal, etc)</label>
	</li>
	<li>
			<input group="129" type="radio" id="129_5" name="answers[129].value" value="192"  class="selection question_radio_129" onclick="showOrHide5()"  />		<label for="129_5">Other: [please specify]</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_129  qc_0 radio" type="radio" name="answers[129].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
function showOrHide5(){
	if(document.getElementById("129_5").checked){
		document.getElementById("q_65").style.display="";
	}else{
		document.getElementById("q_65").style.display="none";
	}
}
</script>
		  <div id="q_65" style="margin-bottom:0px; display:none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						which
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[130].id" value="" id="answers[130].id" />
<input type="text" name="answers[130].value" value="" id="question_130" group="130" class="input-text" />

<span class="error-content" id="err_answers[130].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_66" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Have you tried any other brands of prenatal/ maternal milk?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[131].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[131].id" value="" id="answers[131].id" />
<ul>
	<li>
			<input group="131" type="radio" id="131_0" name="answers[131].value" value="193"  class="selection question_radio_131"  />		<label for="131_0">yes</label>
	</li>
	<li>
			<input group="131" type="radio" id="131_1" name="answers[131].value" value="194"  class="selection question_radio_131"  />		<label for="131_1">no</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_131  qc_0 radio" type="radio" name="answers[131].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_67" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						In your mind, how is NAN MOM&amp;me different from other maternal milk products available?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[132].id" value="" id="answers[132].id" />
<textarea name="answers[132].value" id="question_132" cols="40" group="132" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[132].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="Submit" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://i2.wildfire.asia/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://i2.wildfire.asia/images/web_dialog_m_t.gif"><img src="http://i2.wildfire.asia/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://i2.wildfire.asia/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://i2.wildfire.asia/images/web_dialog_l_m.gif"><img src="http://i2.wildfire.asia/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://i2.wildfire.asia/images/web_dialog_r_m.gif"><img src="http://i2.wildfire.asia/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://i2.wildfire.asia/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://i2.wildfire.asia/images/web_dialog_m_b.gif"><img src="http://i2.wildfire.asia/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://i2.wildfire.asia/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://i2.wildfire.asia/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = 'Mandatory questions must be filled out';
	        jQuery("#check-alert-dialog .content").html(html);
	        jQuery("#check-alert-dialog").dialog('open');
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = 'Can not submit empty questionnaire form';
		    jQuery("#check-alert-dialog .content").html(html);
		    jQuery("#check-alert-dialog").dialog('open');
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow"></div>
	<div style="clear: both"></div>
	
</div> 
</body>
</html>

<script language="JavaScript" type="text/javascript">
	//rule for question start
	//1nd > 8=>NPS MOTIVATION
	jQuery("#q_40").hide();
	jQuery("input.question_radio_104").bind("click",function(){
		if(jQuery(this).val()*1>7){
			jQuery("#q_40").show();
		}else{
			jQuery("#question_105").val("");
			jQuery("#q_40").hide();
		}
	}).change();
	//3th yes=>P3M PURCHASE FREQUENCY,P3M PURCHASE VOLUME,P3M PURCHASE LOCATION
	//done by i2
	
	//10 yes=>SOURCE OF AWARENESS
	jQuery("#q_50").hide();
	jQuery("input.question_radio_114").bind("click",function(){
		if(jQuery(this).val()=="168"){
			jQuery("#q_50").show();
		}else{
			jQuery("#question_115").val("");
			jQuery("#q_50").hide();
		}
	}).change();
	//12 yes=>CATEGORY AWARENESS
	jQuery("#q_52").hide();
	jQuery("input.question_radio_116").bind("click",function(){
		if(jQuery(this).val()=="170"){
			jQuery("#q_52").show();
		}else{
			jQuery("#q_52").hide();
			jQuery("#question_117").val("");
		}
	}).change();
	//15 yes=>SOURCE OF SAMPLE
	jQuery("#q_60").hide();
	jQuery("input.question_radio_124").bind("click",function(){
		if(jQuery(this).val()=="172"){
			jQuery("#q_60").show();
		}else{
			jQuery("input.question_radio_125:checked").attr("checked",false);
			jQuery("#q_60").hide();
		}
	}).change();
	//9&19 yes=>CATEGORY PERCEPTION
	jQuery("#q_67").hide();
	jQuery("input.question_radio_131,input.question_radio_113").bind("click",function(){
		if(jQuery("#113_0").attr("checked")&&jQuery("#131_0").attr("checked")){
			jQuery("#q_67").show();
		}else{
			jQuery("#question_132").val("");
			jQuery("#q_67").hide();
		}
	}).change();
	//rule for question end
</script>
