<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<META NAME="ROBOTS" CONTENT="NOINDEX,NOFOLLOW">
	<title>Indicate - Fill out survey</title>
	<link href="/css/crystal.css" rel="stylesheet" type="text/css" media="screen, print" />
	<!--[if IE]>
	<link href="/css/crystal-ie.css" rel="stylesheet" type="text/css" media="screen" />
	<![endif]-->
	<link href="/css/fillout_default.css" rel="stylesheet" type="text/css" media="screen" />
	<!--[if IE]>
	<link href="/css/fillout_default-ie.css" rel="stylesheet" type="text/css" media="screen" />
	<![endif]-->
	<link href="/css/niftyCorners.css" rel="stylesheet" type="text/css" media="screen" />
	<script src="/js/all.js" language="JavaScript" type="text/javascript"></script>
	<script language="JavaScript" type="text/javascript">

<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
</head>
<script language="JavaScript" type="text/javascript">
function loadDecu(){
	$("q_92").style.display="none";
	$("q_86").style.display="none";
	$("q_122").style.display="none";
	$("q_123").style.display="none";
	$("question_575").value="consumer";
	$("question_576").value="consumer";
	$("question_577").value="consumer";
	$("question_578").value="consumer";
	$('q_42').style.display="none";
	$('q_43').style.display="none";
	$('q_119').style.display="none";
	$('q_120').style.display="none";
	$('q_63').style.display="none";
	$('q_61').style.display="none";
}
</script>
<body onload="loadDecu();">
<div class="main-container-outer">
	<div id="container">
		<div id="header" class="header">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.wildfire.asia" target="_blank">
					
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content">
 		

<div id="content">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://i2.wildfire.asia/fillout" onsubmit="loading();return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">
<div class="questionnaire-title"></div>


<input type="hidden" name="id" value="CfS1hIDSsVoB" id="id" />
<input type="hidden" name="theme" value="default" id="theme" />
<input type="hidden" name="surveyId" value="CfS1hIDSsVoB"/>

<div class="mandatory"><span style="color: red;">* </span>- It is mandatory</div>
<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">

</script>
		  <div id="q_118" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						How likely are you to recommend NAN MOM&amp;me to your family, colleagues or friends?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[550].value" ></span>
<input type="hidden" name="answers[550].id" value="" id="answers[550].id" />
<table>
<tr>

<td>

<div class="left-label">0: will not recommend</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[550].value" value="0" id="550_0" group="550" class="question_radio_550 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[550].value" value="1" id="550_1" group="550" class="question_radio_550 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[550].value" value="2" id="550_2" group="550" class="question_radio_550 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[550].value" value="3" id="550_3" group="550" class="question_radio_550 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[550].value" value="4" id="550_4" group="550" class="question_radio_550 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[550].value" value="5" id="550_5" group="550" class="question_radio_550 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[550].value" value="6" id="550_6" group="550" class="question_radio_550 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[550].value" value="7" id="550_7" group="550" class="question_radio_550 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[550].value" value="8" id="550_8" group="550" class="question_radio_550 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[550].value" value="9" id="550_9" group="550" class="question_radio_550 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[550].value" value="10" id="550_10" group="550" class="question_radio_550 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table><div class="right-label">10: will recommend</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[550].value" value="" id="answers[550].value" class="q_550 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_99" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Please motivate your choice:
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[551].id" value="" id="answers[551].id" />
<input type="text" name="answers[551].value" value="" id="question_551" group="551" class="input-text" />

<span class="error-content" id="err_answers[551].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_100" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						During the past 3 months, how many times have you mentioned NAN MOM&amp;me?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[552].id" value="" id="answers[552].id" />
<input type="text" name="answers[552].value" value="" id="question_552" group="552" class="input-text" />

<span class="error-content" id="err_answers[552].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_101" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						In total, to how many people did you mention NAN MOM&amp;me?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[553].id" value="" id="answers[553].id" />
<input type="text" name="answers[553].value" value="" id="question_553" group="553" class="input-text" />

<span class="error-content" id="err_answers[553].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_102" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						How many of these people were pregnant at the time or had just delivered a baby?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[554].id" value="" id="answers[554].id" />
<input type="text" name="answers[554].value" value="" id="question_554" group="554" class="input-text" />

<span class="error-content" id="err_answers[554].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_103" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						What spurred you to talk about NAN MOM&amp;me?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[555].id" value="" id="answers[555].id" />
<input type="text" name="answers[555].value" value="" id="question_555" group="555" class="input-text" />

<span class="error-content" id="err_answers[555].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_104" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Have you bought NAN MOM&amp;me in the past 3 months?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[556].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[556].id" value="" id="answers[556].id" />
<ul>
	<li>
			<input group="556" type="radio" id="556_0" name="answers[556].value" value="299" onclick="showOrHide()"  class="selection question_radio_556"  />		<label for="556_0">Yes</label>
	</li>
	<li>
			<input group="556" type="radio" id="556_1" name="answers[556].value" value="300" onclick="showOrHide()" class="selection question_radio_556"  />		<label for="556_1">No</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_556  qc_0 radio" type="radio" name="answers[556].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide(){
	if($('556_0').checked){
		$('q_42').style.display="";
		$('q_43').style.display="";
                $('q_119').style.display="";
	}else{
                $('q_42').style.display="none";
                $('q_43').style.display="none";
                $('q_119').style.display="none";
	}
}
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_42" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						How often have you bought NAN MOM&amp;me in the past 3 months?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[557].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[557].id" value="" id="answers[557].id" />
<ul>
	<li>
			<input group="557" type="radio" id="557_0" name="answers[557].value" value="150"  class="selection question_radio_557"  />		<label for="557_0">Once</label>
	</li>
	<li>
			<input group="557" type="radio" id="557_1" name="answers[557].value" value="151"  class="selection question_radio_557"  />		<label for="557_1">About once per month</label>
	</li>
	<li>
			<input group="557" type="radio" id="557_2" name="answers[557].value" value="152"  class="selection question_radio_557"  />		<label for="557_2">About twice per month</label>
	</li>
	<li>
			<input group="557" type="radio" id="557_3" name="answers[557].value" value="153"  class="selection question_radio_557"  />		<label for="557_3">About three times per month</label>
	</li>
	<li>
			<input group="557" type="radio" id="557_4" name="answers[557].value" value="154"  class="selection question_radio_557"  />		<label for="557_4">More than three times per month</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_557  qc_0 radio" type="radio" name="answers[557].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_43" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						How many packs do you usually buy together?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[558].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[558].id" value="" id="answers[558].id" />
<ul>
	<li>
			<input group="558" type="radio" id="558_0" name="answers[558].value" value="155"  class="selection question_radio_558"  />		<label for="558_0">One</label>
	</li>
	<li>
			<input group="558" type="radio" id="558_1" name="answers[558].value" value="156"  class="selection question_radio_558"  />		<label for="558_1">Two</label>
	</li>
	<li>
			<input group="558" type="radio" id="558_2" name="answers[558].value" value="157"  class="selection question_radio_558"  />		<label for="558_2">Three</label>
	</li>
	<li>
			<input group="558" type="radio" id="558_3" name="answers[558].value" value="158"  class="selection question_radio_558"  />		<label for="558_3">Four</label>
	</li>
	<li>
			<input group="558" type="radio" id="558_4" name="answers[558].value" value="159"  class="selection question_radio_558"  />		<label for="558_4">More than four</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_558  qc_0 radio" type="radio" name="answers[558].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_119" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Where did you buy the product?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[559].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[559].id" value="" id="answers[559].id" />




<span id="hint_559">
</span>
<ul>
	<li>
			<input group="559" class="question_radio_559 selection" type="checkbox" id="559_0" name="answers[559].value" value="324" 	onclick=" "/>		<label for="559_0">FairPrice</label>
	</li>
	<li>
			<input group="559" class="question_radio_559 selection" type="checkbox" id="559_1" name="answers[559].value" value="325" 	onclick=" "/>		<label for="559_1">ColdStorage</label>
	</li>
	<li>
			<input group="559" class="question_radio_559 selection" type="checkbox" id="559_2" name="answers[559].value" value="326" 	onclick=" "/>		<label for="559_2">Giant</label>
	</li>
	<li>
			<input group="559" class="question_radio_559 selection" type="checkbox" id="559_3" name="answers[559].value" value="327" 	onclick=" "/>		<label for="559_3">ShengSiong</label>
	</li>
	<li>
			<input group="559" class="question_radio_559 selection" type="checkbox" id="559_4" name="answers[559].value" value="328" 	onclick=" "/>		<label for="559_4">Carrefour</label>
	</li>
	<li>
			<input group="559" class="question_radio_559 selection" type="checkbox" id="559_5" name="answers[559].value" value="329" 	onclick="showOrHide2() "/>		<label for="559_5">Other</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide2(){
        if($('559_5').checked){
                $('q_120').style.display="";
        }else{
                $('q_120').style.display="none";
        }
}

</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_120" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Other:
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[560].id" value="" id="answers[560].id" />
<input type="text" name="answers[560].value" value="" id="question_560" group="560" class="input-text" />

<span class="error-content" id="err_answers[560].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_121" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						How likely are you to buy NAN MOM&amp;me in the coming three months?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[561].value" ></span>
<input type="hidden" name="answers[561].id" value="" id="answers[561].id" />
<table>
<tr>

<td>

<div class="left-label">will not buy</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[561].value" value="1" id="561_1" group="561" class="question_radio_561 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[561].value" value="2" id="561_2" group="561" class="question_radio_561 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[561].value" value="3" id="561_3" group="561" class="question_radio_561 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[561].value" value="4" id="561_4" group="561" class="question_radio_561 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[561].value" value="5" id="561_5" group="561" class="question_radio_561 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">will definitely buy</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[561].value" value="" id="answers[561].value" class="q_561 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_107" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						In the past 3 months, have you tried NAN MOM&amp;me?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[562].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[562].id" value="" id="answers[562].id" />
<ul>
	<li>
			<input group="562" type="radio" id="562_0" name="answers[562].value" value="307"  class="selection question_radio_562"  />		<label for="562_0">Yes</label>
	</li>
	<li>
			<input group="562" type="radio" id="562_1" name="answers[562].value" value="308"  class="selection question_radio_562"  />		<label for="562_1">No</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_562  qc_0 radio" type="radio" name="answers[562].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>

<div class="question-title">How would you rate NAN MOM&me on the following attributes? 
  </div>
<br><br>

		  <div id="q_53" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
						        NAN MOM&amp;me is high in folic acid, which supports the foetus’s  overall growth &amp; development
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[563].value" ></span>
<input type="hidden" name="answers[563].id" value="" id="answers[563].id" />
<table>
<tr>

<td>

<div class="left-label">completely disagree</div>
	<table class="rating-table" style="width:70px;">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[563].value" value="1" id="563_1" group="563" class="question_radio_563 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[563].value" value="2" id="563_2" group="563" class="question_radio_563 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[563].value" value="3" id="563_3" group="563" class="question_radio_563 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[563].value" value="4" id="563_4" group="563" class="question_radio_563 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[563].value" value="5" id="563_5" group="563" class="question_radio_563 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">completely agree</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[563].value" value="" id="answers[563].value" class="q_563 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_54" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
						        NAN MOM&amp;me is the highest in DHA compared to all other maternal milks in Singapore
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[564].value" ></span>
<input type="hidden" name="answers[564].id" value="" id="answers[564].id" />
<table>
<tr>

<td>

<div class="left-label">completely disagree</div>
	<table class="rating-table"  style="width:70px;">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[564].value" value="1" id="564_1" group="564" class="question_radio_564 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[564].value" value="2" id="564_2" group="564" class="question_radio_564 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[564].value" value="3" id="564_3" group="564" class="question_radio_564 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[564].value" value="4" id="564_4" group="564" class="question_radio_564 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[564].value" value="5" id="564_5" group="564" class="question_radio_564 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">completely agree</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[564].value" value="" id="answers[564].value" class="q_564 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_55" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table" >
			<tr>
				<td width=50% valign="top">
					<div class="">
					 	        NAN MOM&amp;me contains calcium for strong bones&amp; teeth
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[565].value" ></span>
<input type="hidden" name="answers[565].id" value="" id="answers[565].id" />
<table>
<tr>

<td>

<div class="left-label">completely disagree</div>
	<table class="rating-table"  style="width:70px;">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[565].value" value="1" id="565_1" group="565" class="question_radio_565 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[565].value" value="2" id="565_2" group="565" class="question_radio_565 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[565].value" value="3" id="565_3" group="565" class="question_radio_565 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[565].value" value="4" id="565_4" group="565" class="question_radio_565 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[565].value" value="5" id="565_5" group="565" class="question_radio_565 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">completely agree</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[565].value" value="" id="answers[565].value" class="q_565 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_56" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
					 	        NAN MOM&amp;me is lower in fat than other brands of maternal milk
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[566].value" ></span>
<input type="hidden" name="answers[566].id" value="" id="answers[566].id" />
<table>
<tr>

<td>

<div class="left-label">completely disagree</div>
	<table class="rating-table"  style="width:70px;">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[566].value" value="1" id="566_1" group="566" class="question_radio_566 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[566].value" value="2" id="566_2" group="566" class="question_radio_566 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[566].value" value="3" id="566_3" group="566" class="question_radio_566 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[566].value" value="4" id="566_4" group="566" class="question_radio_566 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[566].value" value="5" id="566_5" group="566" class="question_radio_566 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">completely agree</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[566].value" value="" id="answers[566].value" class="q_566 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_57" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
						        NAN MOM&amp;me provides additional nutrients to support pregnancy &amp; breastfeeding
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[567].value" ></span>
<input type="hidden" name="answers[567].id" value="" id="answers[567].id" />
<table>
<tr>

<td>

<div class="left-label">completely disagree</div>
	<table class="rating-table"  style="width:70px;">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[567].value" value="1" id="567_1" group="567" class="question_radio_567 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[567].value" value="2" id="567_2" group="567" class="question_radio_567 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[567].value" value="3" id="567_3" group="567" class="question_radio_567 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[567].value" value="4" id="567_4" group="567" class="question_radio_567 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[567].value" value="5" id="567_5" group="567" class="question_radio_567 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">completely agree</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[567].value" value="" id="answers[567].value" class="q_567 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_58" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
						        NAN MOM&amp;me provides important vitamins and minerals (iron, zinc, vitamin A,D,E,C)
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[568].value" ></span>
<input type="hidden" name="answers[568].id" value="" id="answers[568].id" />
<table>
<tr>

<td>

<div class="left-label">completely disagree</div>
	<table class="rating-table"  style="width:70px;">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[568].value" value="1" id="568_1" group="568" class="question_radio_568 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[568].value" value="2" id="568_2" group="568" class="question_radio_568 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[568].value" value="3" id="568_3" group="568" class="question_radio_568 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[568].value" value="4" id="568_4" group="568" class="question_radio_568 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[568].value" value="5" id="568_5" group="568" class="question_radio_568 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">completely agree</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[568].value" value="" id="answers[568].value" class="q_568 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_114" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Whose advice would you trust most when recommending maternal supplements?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[569].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[569].id" value="" id="answers[569].id" />
<ul>
	<li>
			<input group="569" type="radio" id="569_0" name="answers[569].value" value="309" onclick="showOrHide3()"  class="selection question_radio_569"  />		<label for="569_0">Gynecologist or doctor</label>
	</li>
	<li>
			<input group="569" type="radio" id="569_1" name="answers[569].value" value="310" onclick="showOrHide3()"  class="selection question_radio_569"  />		<label for="569_1">Friends</label>
	</li>
	<li>
			<input group="569" type="radio" id="569_2" name="answers[569].value" value="311" onclick="showOrHide3()"  class="selection question_radio_569"  />		<label for="569_2">Relatives</label>
	</li>
	<li>
			<input group="569" type="radio" id="569_3" name="answers[569].value" value="312" onclick="showOrHide3()"  class="selection question_radio_569"  />		<label for="569_3">Husband</label>
	</li>
	<li>
			<input group="569" type="radio" id="569_4" name="answers[569].value" value="313" onclick="showOrHide3()"  class="selection question_radio_569"  />		<label for="569_4">Hospital/clinic nurses</label>
	</li>
	<li>
			<input group="569" type="radio" id="569_5" name="answers[569].value" value="314" onclick="showOrHide3()"  class="selection question_radio_569"  />		<label for="569_5">Pharmacist</label>
	</li>
	<li>
			<input group="569" type="radio" id="569_6" name="answers[569].value" value="315" onclick="showOrHide3()" class="selection question_radio_569"  />		<label for="569_6">Online sources(please specify)</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_569  qc_0 radio" type="radio" name="answers[569].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide3(){
        if($('569_6').checked){
                $('q_63').style.display="";
        }else{
                $('q_63').style.display="none";
        }
}

</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_63" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Online sources
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[570].id" value="" id="answers[570].id" />
<input type="text" name="answers[570].value" value="" id="question_570" group="570" class="input-text" />

<span class="error-content" id="err_answers[570].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_115" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Which is your most preferred form of prenatal/ maternal supplement?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[571].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[571].id" value="" id="answers[571].id" />
<ul>
	<li>
			<input group="571" type="radio" id="571_0" name="answers[571].value" value="316" onclick="showOrHide4()"   class="selection question_radio_571"  />		<label for="571_0">Pills</label>
	</li>
	<li>
			<input group="571" type="radio" id="571_1" name="answers[571].value" value="317" onclick="showOrHide4()"   class="selection question_radio_571"  />		<label for="571_1">Cereal bar</label>
	</li>
	<li>
			<input group="571" type="radio" id="571_2" name="answers[571].value" value="318" onclick="showOrHide4()"   class="selection question_radio_571"  />		<label for="571_2">Milk-based beverage</label>
	</li>
	<li>
			<input group="571" type="radio" id="571_3" name="answers[571].value" value="319" onclick="showOrHide4()"   class="selection question_radio_571"  />		<label for="571_3">Non-dairy beverage (fruit based)</label>
	</li>
	<li>
			<input group="571" type="radio" id="571_4" name="answers[571].value" value="320" onclick="showOrHide4()"  class="selection question_radio_571"  />		<label for="571_4">Snack (biscuit, oatmeal, etc)</label>
	</li>
	<li>
			<input group="571" type="radio" id="571_5" name="answers[571].value" value="321" onclick="showOrHide4()"  class="selection question_radio_571"  />		<label for="571_5">Other</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_571  qc_0 radio" type="radio" name="answers[571].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide4(){
        if($('571_5').checked){
                $('q_61').style.display="";
        }else{
                $('q_61').style.display="none";
        }
}


</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_61" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Other
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[572].id" value="" id="answers[572].id" />
<input type="text" name="answers[572].value" value="" id="question_572" group="572" class="input-text" />

<span class="error-content" id="err_answers[572].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_116" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Have you tried any other brands of prenatal/ maternal milk?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[573].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[573].id" value="" id="answers[573].id" />
<ul>
	<li>
			<input group="573" type="radio" id="573_0" name="answers[573].value" value="322"  class="selection question_radio_573"  />		<label for="573_0">Yes</label>
	</li>
	<li>
			<input group="573" type="radio" id="573_1" name="answers[573].value" value="323"  class="selection question_radio_573"  />		<label for="573_1">No</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_573  qc_0 radio" type="radio" name="answers[573].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_117" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						In your mind, what are the most important, key benefits of NAN MOM&amp;me?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[574].id" value="" id="answers[574].id" />
<input type="text" name="answers[574].value" value="" id="question_574" group="574" class="input-text" />

<span class="error-content" id="err_answers[574].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("575");
// ]]>
-->
</script>
		  <div id="q_92" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Name
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[575].id" value="" id="answers[575].id" />
<input type="text" name="answers[575].value" value="" id="question_575" group="575" class="input-text" />

<span class="error-content" id="err_answers[575].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("576");
// ]]>
-->
</script>
		  <div id="q_86" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Email
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[576].id" value="" id="answers[576].id" />
<input type="text" name="answers[576].value" value="" id="question_576" group="576" class="input-text" />

<span class="error-content" id="err_answers[576].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("577");
// ]]>
-->
</script>
		  <div id="q_122" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Phone
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[577].id" value="" id="answers[577].id" />
<input type="text" name="answers[577].value" value="" id="question_577" group="577" class="input-text" />

<span class="error-content" id="err_answers[577].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("578");
// ]]>
-->
</script>
		  <div id="q_123" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Singapore Shipping Address
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[578].id" value="" id="answers[578].id" />
<input type="text" name="answers[578].value" value="" id="question_578" group="578" class="input-text" />

<span class="error-content" id="err_answers[578].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="Submit" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://i2.wildfire.asia/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://i2.wildfire.asia/images/web_dialog_m_t.gif"><img src="http://i2.wildfire.asia/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://i2.wildfire.asia/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://i2.wildfire.asia/images/web_dialog_l_m.gif"><img src="http://i2.wildfire.asia/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://i2.wildfire.asia/images/web_dialog_r_m.gif"><img src="http://i2.wildfire.asia/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://i2.wildfire.asia/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://i2.wildfire.asia/images/web_dialog_m_b.gif"><img src="http://i2.wildfire.asia/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://i2.wildfire.asia/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://i2.wildfire.asia/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '<span style="color:red">*&nbsp;&nbsp;</span>Mandatory questions must be filled out';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '<span style="color:red">*&nbsp;&nbsp;</span>Can not submit empty questionnaire form';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
		
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow"></div>
	<div style="clear: both"></div>
	
</div> 
</body>
</html>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

Framework.registerAjaxSensors();
// ]]>
-->
</script>
