	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/294" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="loading();return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="URfpxovGXh2Z" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_944" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在过去的两个月，您与多少位朋友谈论了益等果汁吧活动？（不包括在博客、在线评论、网站社区上的交流）
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[4098].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[4098].id" value="" id="answers[4098].id" />

	<select group="4098" class="selection" id="question_4098" name="answers[4098].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="3536" style=""  >0</option>
<option value="2957" style=""  >1</option>
<option value="2958" style=""  >2</option>
<option value="2959" style=""  >3</option>
<option value="2960" style=""  >4</option>
<option value="2961" style=""  >5</option>
<option value="2962" style=""  >6</option>
<option value="2963" style=""  >7</option>
<option value="2964" style=""  >8</option>
<option value="2965" style=""  >9</option>
<option value="2966" style=""  >10</option>
<option value="2967" style=""  >11</option>
<option value="2968" style=""  >12</option>
<option value="2969" style=""  >13</option>
<option value="2970" style=""  >14</option>
<option value="2971" style=""  >15</option>
<option value="2972" style=""  >16</option>
<option value="2973" style=""  >17</option>
<option value="2974" style=""  >18</option>
<option value="2975" style=""  >19</option>
<option value="2976" style=""  >20+</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_945" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在这些人中，有多少人事先已经听说过益等果汁吧？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[4099].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[4099].id" value="" id="answers[4099].id" />

	<select group="4099" class="selection" id="question_4099" name="answers[4099].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="2977" style=""  >1</option>
<option value="2978" style=""  >2</option>
<option value="2979" style=""  >3</option>
<option value="2980" style=""  >4</option>
<option value="2981" style=""  >5</option>
<option value="2982" style=""  >6</option>
<option value="2983" style=""  >7</option>
<option value="2984" style=""  >8</option>
<option value="2985" style=""  >9</option>
<option value="2986" style=""  >10</option>
<option value="2987" style=""  >11</option>
<option value="2988" style=""  >12</option>
<option value="2989" style=""  >13</option>
<option value="2990" style=""  >14</option>
<option value="2991" style=""  >15</option>
<option value="2992" style=""  >16</option>
<option value="2993" style=""  >17</option>
<option value="2994" style=""  >18</option>
<option value="2995" style=""  >19</option>
<option value="2996" style=""  >20+</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_946" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在过去的两个月，您一共去过几次益等果汁吧？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[4100].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[4100].id" value="" id="answers[4100].id" />

	<select group="4100" class="selection" id="question_4100" name="answers[4100].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="2997" style=""  >0</option>
<option value="2998" style=""  >1</option>
<option value="2999" style=""  >2</option>
<option value="3000" style=""  >3</option>
<option value="3001" style=""  >4-6</option>
<option value="3002" style=""  >7-10</option>
<option value="3003" style=""  >11+</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_947" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您是否使用了星星火提供给您的免费三明治和果汁优惠券？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[4101].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[4101].id" value="" id="answers[4101].id" />
<ul>
	<li>
			<input group="4101" type="radio" id="4101_0" name="answers[4101].value" value="3004"  class="selection question_radio_4101"  />		<label for="4101_0">是的</label>
	</li>
	<li>
			<input group="4101" type="radio" id="4101_1" name="answers[4101].value" value="3005"  class="selection question_radio_4101"  />		<label for="4101_1">没有</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_4101  qc_0 radio" type="radio" name="answers[4101].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_948" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您是否把50%折扣优惠券送给您的朋友？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[4102].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[4102].id" value="" id="answers[4102].id" />
<ul>
	<li>
			<input group="4102" type="radio" id="4102_0" name="answers[4102].value" value="3006"  class="selection question_radio_4102"  />		<label for="4102_0">是的</label>
	</li>
	<li>
			<input group="4102" type="radio" id="4102_1" name="answers[4102].value" value="3007"  class="selection question_radio_4102"  />		<label for="4102_1">没有</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_4102  qc_0 radio" type="radio" name="answers[4102].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_949" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您在多少个博客、在线评论、网站社区上发布过益等果汁吧信息？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[4103].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[4103].id" value="" id="answers[4103].id" />

	<select group="4103" class="selection" id="question_4103" name="answers[4103].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="3008" style=""  >0</option>
<option value="3009" style=""  >1</option>
<option value="3010" style=""  >2</option>
<option value="3011" style=""  >3</option>
<option value="3012" style=""  >4</option>
<option value="3013" style=""  >5+</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_950" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						到今天之前，您是否听说过益等水果吧？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[4104].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[4104].id" value="" id="answers[4104].id" />
<ul>
	<li>
			<input group="4104" type="radio" id="4104_0" name="answers[4104].value" value="3014"  class="selection question_radio_4104"  />		<label for="4104_0">是的，听说过</label>
	</li>
	<li>
			<input group="4104" type="radio" id="4104_1" name="answers[4104].value" value="3015"  class="selection question_radio_4104"  />		<label for="4104_1">没有，没听说过</label>
	</li>
	<li>
			<input group="4104" type="radio" id="4104_2" name="answers[4104].value" value="3016"  class="selection question_radio_4104"  />		<label for="4104_2">不清楚</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_4104  qc_0 radio" type="radio" name="answers[4104].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_621" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您目前对于益等水果吧的态度是什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[4105].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[4105].id" value="" id="answers[4105].id" />

	<select group="4105" class="selection" id="question_4105" name="answers[4105].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="1301" style=""  >非常看好</option>
<option value="1302" style=""  >有些积极的看法</option>
<option value="1303" style=""  >中立</option>
<option value="1304" style=""  >有些消极的看法</option>
<option value="1305" style=""  >很不看好</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_622" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您对益等水果吧的三明治的感觉是什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[4106].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[4106].id" value="" id="answers[4106].id" />

	<select group="4106" class="selection" id="question_4106" name="answers[4106].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="1306" style=""  >非常好</option>
<option value="1307" style=""  >一般，不过还好</option>
<option value="1308" style=""  >不好不坏</option>
<option value="1309" style=""  >不是太好</option>
<option value="1310" style=""  >很不好</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_623" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您感觉益等水果吧的服务态度怎么样？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[4107].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[4107].id" value="" id="answers[4107].id" />

	<select group="4107" class="selection" id="question_4107" name="answers[4107].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="1311" style=""  >非常好</option>
<option value="1312" style=""  >一般，不过还好</option>
<option value="1313" style=""  >不好也不坏</option>
<option value="1314" style=""  >不是太好</option>
<option value="1315" style=""  >很不好</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_630" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=100% valign="top">
					<div class="question-title">
						有多大的可能，您会跟您的朋友或者同事推荐益等水果吧？
					</div>
							<div class="elementInfoText " >
							   
							</div>
				</td>
			</tr>
			 <tr>
				<td width=100% valign="top" class="question-td twoColumnLayout" style="padding-left:15px;">
<span class="error-content" id="err_answers[4108].value" ></span>
<input type="hidden" name="answers[4108].id" value="" id="answers[4108].id" />
<table>
<tr>

<td>

<div class="left-label">没有可能</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[4108].value" value="0" id="4108_0" group="4108" class="question_radio_4108 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[4108].value" value="1" id="4108_1" group="4108" class="question_radio_4108 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[4108].value" value="2" id="4108_2" group="4108" class="question_radio_4108 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[4108].value" value="3" id="4108_3" group="4108" class="question_radio_4108 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[4108].value" value="4" id="4108_4" group="4108" class="question_radio_4108 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[4108].value" value="5" id="4108_5" group="4108" class="question_radio_4108 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[4108].value" value="6" id="4108_6" group="4108" class="question_radio_4108 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[4108].value" value="7" id="4108_7" group="4108" class="question_radio_4108 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[4108].value" value="8" id="4108_8" group="4108" class="question_radio_4108 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[4108].value" value="9" id="4108_9" group="4108" class="question_radio_4108 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[4108].value" value="10" id="4108_10" group="4108" class="question_radio_4108 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">绝对会推荐</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[4108].value" value="" id="answers[4108].value" class="q_4108 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_632" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						环境和社会氛围对您选择饭店时起到什么作用？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[4109].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[4109].id" value="" id="answers[4109].id" />

	<select group="4109" class="selection" id="question_4109" name="answers[4109].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="1341" style=""  >起到了非常重要的责任</option>
<option value="1342" style=""  >比较重要</option>
<option value="1343" style=""  >无所谓</option>
<option value="1344" style=""  >不重要</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_951" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在这次活动中，您邀请了多少位朋友加入星星火社区？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[4110].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[4110].id" value="" id="answers[4110].id" />

	<select group="4110" class="selection" id="question_4110" name="answers[4110].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="3017" style=""  >1</option>
<option value="3018" style=""  >2</option>
<option value="3019" style=""  >3</option>
<option value="3020" style=""  >4</option>
<option value="3021" style=""  >5+</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="Submit" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = 'Mandatory questions must be filled out';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = 'Can not submit empty questionnaire form';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

Framework.registerAjaxSensors();
// ]]>
-->
</script>
