	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" style="background: #fff;width:100%;">
	<div id="container" style="background: #fff;">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" style="background:#fff;width:100%;">
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="loading();return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			$('mask').show();
		}
	}
// ]]>
-->
</script>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />

<div class="mandatory"><span style="color: red;">* </span>- It is mandatory</div>
<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>

	<div id="page_0">





<div class="header-section" id="h_169">
	<h3></h3>
<span class="header-title">
<h2>关于您对杂志的兴趣:</h2>
</span>
	<h3></h3>
</div>
<!-- <span  class="no-answer-all">No answer all <input type="checkbox" name="qc_checkbox_169" value="" id="qc_checkbox_169" onClick="checkSubboxes(169)" />
 </span>-->
<div style="clear: both ;"></div><script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_169_1232" style="margin-bottom:0px;" class="question-even question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					您经常阅读哪类杂志？
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[6267].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[6267].id" value="" id="answers[6267].id" />




<span id="hint_6267">
</span>
<ul>
	<li>
			<input group="6267" class="question_radio_6267 selection" type="checkbox" id="6267_0" name="answers[6267].value" value="3847" 	onclick=" "/>		<label for="6267_0">经济</label>
	</li>
	<li>
			<input group="6267" class="question_radio_6267 selection" type="checkbox" id="6267_1" name="answers[6267].value" value="3848" 	onclick=" "/>		<label for="6267_1">时尚生活</label>
	</li>
	<li>
			<input group="6267" class="question_radio_6267 selection" type="checkbox" id="6267_2" name="answers[6267].value" value="3849" 	onclick=" "/>		<label for="6267_2">汽车</label>
	</li>
	<li>
			<input group="6267" class="question_radio_6267 selection" type="checkbox" id="6267_3" name="answers[6267].value" value="3850" 	onclick=" "/>		<label for="6267_3">体育</label>
	</li>
	<li>
			<input group="6267" class="question_radio_6267 selection" type="checkbox" id="6267_4" name="answers[6267].value" value="3851" 	onclick=" "/>		<label for="6267_4">工业技术</label>
	</li>
	<li>
			<input group="6267" class="question_radio_6267 selection" type="checkbox" id="6267_5" name="answers[6267].value" value="3852" 	onclick=" "/>		<label for="6267_5">健康</label>
	</li>
	<li>
			<input group="6267" class="question_radio_6267 selection" type="checkbox" id="6267_6" name="answers[6267].value" value="3853" 	onclick=" "/>		<label for="6267_6">军事</label>
	</li>
	<li>
			<input group="6267" class="question_radio_6267 selection" type="checkbox" id="6267_7" name="answers[6267].value" value="3854" 	onclick=" "/>		<label for="6267_7">时事</label>
	</li>
		<li>
			<input class="question_radio_6267" type="checkbox" id="6267_other"   value="0" onclick="showOtherValueInputInCheckBox(this)" />			<label for="6267_other">其他</label>
			<input id="6267_other_input" type="text" name="answers[6267].otherValue" value="" style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_169_1254" style="margin-bottom:0px;" class="question-odd question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					您通常在哪里购买杂志?
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[6268].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[6268].id" value="" id="answers[6268].id" />




<span id="hint_6268">
</span>
<ul>
	<li>
			<input group="6268" class="question_radio_6268 selection" type="checkbox" id="6268_0" name="answers[6268].value" value="3941" 	onclick=" "/>		<label for="6268_0">书店</label>
	</li>
	<li>
			<input group="6268" class="question_radio_6268 selection" type="checkbox" id="6268_1" name="answers[6268].value" value="3942" 	onclick=" "/>		<label for="6268_1">地铁书报摊</label>
	</li>
	<li>
			<input group="6268" class="question_radio_6268 selection" type="checkbox" id="6268_2" name="answers[6268].value" value="3943" 	onclick=" "/>		<label for="6268_2">街报摊</label>
	</li>
	<li>
			<input group="6268" class="question_radio_6268 selection" type="checkbox" id="6268_3" name="answers[6268].value" value="3944" 	onclick=" "/>		<label for="6268_3">超市</label>
	</li>
	<li>
			<input group="6268" class="question_radio_6268 selection" type="checkbox" id="6268_4" name="answers[6268].value" value="3945" 	onclick=" "/>		<label for="6268_4">网上</label>
	</li>
	<li>
			<input group="6268" class="question_radio_6268 selection" type="checkbox" id="6268_5" name="answers[6268].value" value="3946" 	onclick=" "/>		<label for="6268_5">从朋友那得到</label>
	</li>
	<li>
			<input group="6268" class="question_radio_6268 selection" type="checkbox" id="6268_6" name="answers[6268].value" value="3947" 	onclick=" "/>		<label for="6268_6">二手市场</label>
	</li>
		<li>
			<input class="question_radio_6268" type="checkbox" id="6268_other"   value="0" onclick="showOtherValueInputInCheckBox(this)" />			<label for="6268_other">其他</label>
			<input id="6268_other_input" type="text" name="answers[6268].otherValue" value="" style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_169_1234" style="margin-bottom:0px;" class="question-even question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					您或者您的朋友有订阅过杂志吗?
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[6269].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[6269].id" value="" id="answers[6269].id" />
<ul>
	<li>
			<input group="6269" type="radio" id="6269_0" name="answers[6269].value" value="3862"  class="selection question_radio_6269"  />		<label for="6269_0">是的</label>
	</li>
	<li>
			<input group="6269" type="radio" id="6269_1" name="answers[6269].value" value="3863"  class="selection question_radio_6269"  />		<label for="6269_1">没有</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_6269  qc_169 radio" type="radio" name="answers[6269].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_169_1235" style="margin-bottom:0px;" class="question-odd question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					如果是, 它们的名字是?
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[6270].id" value="" id="answers[6270].id" />
<input type="text" name="answers[6270].value" value="" id="question_6270" group="6270" class="input-text" />

<span class="error-content" id="err_answers[6270].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_169_1236" style="margin-bottom:0px;" class="question-even question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					您经常和多少人分享您阅读过的杂志?
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[6271].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[6271].id" value="" id="answers[6271].id" />

	<select group="6271" class="selection" id="question_6271" name="answers[6271].value" title="title"  size = "1" >
	<option selected="selected" value="0">请选择</option>
<option value="3864" style=""  >0</option>
<option value="3865" style=""  >1</option>
<option value="3866" style=""  >2</option>
<option value="3867" style=""  >3</option>
<option value="3868" style=""  >4</option>
<option value="3869" style=""  >5</option>
<option value="3870" style=""  >6</option>
<option value="3871" style=""  >7</option>
<option value="3872" style=""  >8</option>
<option value="3873" style=""  >9</option>
<option value="3874" style=""  >10</option>
<option value="3875" style=""  >10+</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_169_1238" style="margin-bottom:0px;" class="question-odd question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					您经常在网络上阅读杂志吗?
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">
<span class="error-content" id="err_answers[6272].value" ></span>
<input type="hidden" name="answers[6272].id" value="" id="answers[6272].id" />
<table>
<tr>

<td>

<div class="left-label">很少</div>
	<table class="rating-table">
		<tr class="radio-line">
					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[6272].value" value="1" id="6272_1" group="6272" class="question_radio_6272 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6272].value" value="2" id="6272_2" group="6272" class="question_radio_6272 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6272].value" value="3" id="6272_3" group="6272" class="question_radio_6272 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6272].value" value="4" id="6272_4" group="6272" class="question_radio_6272 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[6272].value" value="5" id="6272_5" group="6272" class="question_radio_6272 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">经常</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[6272].value" value="" id="answers[6272].value" class="q_6272 qc_169 radio" />
</td>
</tr>
</table>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_169_1239" style="margin-bottom:0px;" class="question-even question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					如果您经常阅读: 请问是哪个杂志(请提供网站)
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[6273].id" value="" id="answers[6273].id" />
<input type="text" name="answers[6273].value" value="" id="question_6273" group="6273" class="input-text" />

<span class="error-content" id="err_answers[6273].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>




<div class="header-section" id="h_170">
	<h3></h3>
<span class="header-title">
<h2>关于时尚杂志</h2>
</span>
	<h3></h3>
</div>
<!-- <span  class="no-answer-all">No answer all <input type="checkbox" name="qc_checkbox_170" value="" id="qc_checkbox_170" onClick="checkSubboxes(170)" />
 </span>-->
<div style="clear: both ;"></div><script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_170_1240" style="margin-bottom:0px;" class="question-even question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					您非常喜欢阅读时尚或生活时尚杂志吗?
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">
<span class="error-content" id="err_answers[6274].value" ></span>
<input type="hidden" name="answers[6274].id" value="" id="answers[6274].id" />
<table>
<tr>

<td>

<div class="left-label">不喜欢</div>
	<table class="rating-table">
		<tr class="radio-line">
					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[6274].value" value="1" id="6274_1" group="6274" class="question_radio_6274 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6274].value" value="2" id="6274_2" group="6274" class="question_radio_6274 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6274].value" value="3" id="6274_3" group="6274" class="question_radio_6274 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6274].value" value="4" id="6274_4" group="6274" class="question_radio_6274 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[6274].value" value="5" id="6274_5" group="6274" class="question_radio_6274 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">非常喜欢</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[6274].value" value="" id="answers[6274].value" class="q_6274 qc_170 radio" />
</td>
</tr>
</table>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_170_1242" style="margin-bottom:0px;" class="question-odd question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					您喜欢阅读时尚杂志的什么内容:
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[6275].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[6275].id" value="" id="answers[6275].id" />




<span id="hint_6275">
</span>
<ul>
	<li>
			<input group="6275" class="question_radio_6275 selection" type="checkbox" id="6275_0" name="answers[6275].value" value="3877" 	onclick=" "/>		<label for="6275_0">服饰搭配</label>
	</li>
	<li>
			<input group="6275" class="question_radio_6275 selection" type="checkbox" id="6275_1" name="answers[6275].value" value="3878" 	onclick=" "/>		<label for="6275_1">化妆品</label>
	</li>
	<li>
			<input group="6275" class="question_radio_6275 selection" type="checkbox" id="6275_2" name="answers[6275].value" value="3879" 	onclick=" "/>		<label for="6275_2">健康</label>
	</li>
	<li>
			<input group="6275" class="question_radio_6275 selection" type="checkbox" id="6275_3" name="answers[6275].value" value="3880" 	onclick=" "/>		<label for="6275_3">美容护肤</label>
	</li>
	<li>
			<input group="6275" class="question_radio_6275 selection" type="checkbox" id="6275_4" name="answers[6275].value" value="3881" 	onclick=" "/>		<label for="6275_4">购物</label>
	</li>
	<li>
			<input group="6275" class="question_radio_6275 selection" type="checkbox" id="6275_5" name="answers[6275].value" value="3882" 	onclick=" "/>		<label for="6275_5">娱乐</label>
	</li>
	<li>
			<input group="6275" class="question_radio_6275 selection" type="checkbox" id="6275_6" name="answers[6275].value" value="3883" 	onclick=" "/>		<label for="6275_6">家居</label>
	</li>
		<li>
			<input class="question_radio_6275" type="checkbox" id="6275_other"   value="0" onclick="showOtherValueInputInCheckBox(this)" />			<label for="6275_other">其他</label>
			<input id="6275_other_input" type="text" name="answers[6275].otherValue" value="" style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_170_1243" style="margin-bottom:0px;" class="question-even question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					对您来说,时尚杂志附带什么礼物最有吸引力:
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[6276].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[6276].id" value="" id="answers[6276].id" />




<span id="hint_6276">
</span>
<ul>
	<li>
			<input group="6276" class="question_radio_6276 selection" type="checkbox" id="6276_0" name="answers[6276].value" value="3884" 	onclick=" "/>		<label for="6276_0">化妆品小样</label>
	</li>
	<li>
			<input group="6276" class="question_radio_6276 selection" type="checkbox" id="6276_1" name="answers[6276].value" value="3885" 	onclick=" "/>		<label for="6276_1">优惠券，打折卡</label>
	</li>
	<li>
			<input group="6276" class="question_radio_6276 selection" type="checkbox" id="6276_2" name="answers[6276].value" value="3886" 	onclick=" "/>		<label for="6276_2">小饰品</label>
	</li>
	<li>
			<input group="6276" class="question_radio_6276 selection" type="checkbox" id="6276_3" name="answers[6276].value" value="3887" 	onclick=" "/>		<label for="6276_3">电子产品</label>
	</li>
	<li>
			<input group="6276" class="question_radio_6276 selection" type="checkbox" id="6276_4" name="answers[6276].value" value="3888" 	onclick=" "/>		<label for="6276_4">海报</label>
	</li>
		<li>
			<input class="question_radio_6276" type="checkbox" id="6276_other"   value="0" onclick="showOtherValueInputInCheckBox(this)" />			<label for="6276_other">其他</label>
			<input id="6276_other_input" type="text" name="answers[6276].otherValue" value="" style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_170_1253" style="margin-bottom:0px;" class="question-odd question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					以下哪本是您最喜欢的时尚杂志(请选择一项)
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[6277].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[6277].id" value="" id="answers[6277].id" />
<ul>
	<li>
			<input group="6277" type="radio" id="6277_0" name="answers[6277].value" value="3931"  class="selection question_radio_6277" onclick="showOtherValueInputInRadio(this)" />		<label for="6277_0">瑞丽 Rayli</label>
	</li>
	<li>
			<input group="6277" type="radio" id="6277_1" name="answers[6277].value" value="3932"  class="selection question_radio_6277" onclick="showOtherValueInputInRadio(this)" />		<label for="6277_1">米娜 Mina</label>
	</li>
	<li>
			<input group="6277" type="radio" id="6277_2" name="answers[6277].value" value="3933"  class="selection question_radio_6277" onclick="showOtherValueInputInRadio(this)" />		<label for="6277_2">世界时装之苑 ELLE</label>
	</li>
	<li>
			<input group="6277" type="radio" id="6277_3" name="answers[6277].value" value="3934"  class="selection question_radio_6277" onclick="showOtherValueInputInRadio(this)" />		<label for="6277_3">Vogue服饰与美容</label>
	</li>
	<li>
			<input group="6277" type="radio" id="6277_4" name="answers[6277].value" value="3935"  class="selection question_radio_6277" onclick="showOtherValueInputInRadio(this)" />		<label for="6277_4">悦己 Self</label>
	</li>
	<li>
			<input group="6277" type="radio" id="6277_5" name="answers[6277].value" value="3936"  class="selection question_radio_6277" onclick="showOtherValueInputInRadio(this)" />		<label for="6277_5">时尚芭莎 BASAAR</label>
	</li>
	<li>
			<input group="6277" type="radio" id="6277_6" name="answers[6277].value" value="3937"  class="selection question_radio_6277" onclick="showOtherValueInputInRadio(this)" />		<label for="6277_6">时尚 Vogue</label>
	</li>
	<li>
			<input group="6277" type="radio" id="6277_7" name="answers[6277].value" value="3938"  class="selection question_radio_6277" onclick="showOtherValueInputInRadio(this)" />		<label for="6277_7">昕薇 VIVI</label>
	</li>
	<li>
			<input group="6277" type="radio" id="6277_8" name="answers[6277].value" value="3939"  class="selection question_radio_6277" onclick="showOtherValueInputInRadio(this)" />		<label for="6277_8">型时代</label>
	</li>
	<li>
			<input group="6277" type="radio" id="6277_9" name="answers[6277].value" value="3940"  class="selection question_radio_6277" onclick="showOtherValueInputInRadio(this)" />		<label for="6277_9">男人装</label>
	</li>
		<li>
			<input type="radio" id="6277_other" name="answers[6277].value" value="0" class="question_radio_6277" onclick="showOtherValueInputInRadio(this)" />			<label for="6277_other">其他</label>
			<input id="6277_other_input" type="text" name="answers[6277].otherValue" value=""  style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_6277  qc_170 radio" type="radio" name="answers[6277].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_170_1248" style="margin-bottom:0px;" class="question-even question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					对于您最喜欢的这本杂志,您最喜欢它的哪些方面:
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[6278].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[6278].id" value="" id="answers[6278].id" />




<span id="hint_6278">
</span>
<ul>
	<li>
			<input group="6278" class="question_radio_6278 selection" type="checkbox" id="6278_0" name="answers[6278].value" value="3906" 	onclick=" "/>		<label for="6278_0">内容丰富</label>
	</li>
	<li>
			<input group="6278" class="question_radio_6278 selection" type="checkbox" id="6278_1" name="answers[6278].value" value="3907" 	onclick=" "/>		<label for="6278_1">时尚新颖</label>
	</li>
	<li>
			<input group="6278" class="question_radio_6278 selection" type="checkbox" id="6278_2" name="answers[6278].value" value="3908" 	onclick=" "/>		<label for="6278_2">知识性强</label>
	</li>
	<li>
			<input group="6278" class="question_radio_6278 selection" type="checkbox" id="6278_3" name="answers[6278].value" value="3909" 	onclick=" "/>		<label for="6278_3">图片精美</label>
	</li>
	<li>
			<input group="6278" class="question_radio_6278 selection" type="checkbox" id="6278_4" name="answers[6278].value" value="3910" 	onclick=" "/>		<label for="6278_4">封面精致</label>
	</li>
	<li>
			<input group="6278" class="question_radio_6278 selection" type="checkbox" id="6278_5" name="answers[6278].value" value="3911" 	onclick=" "/>		<label for="6278_5">互动活动</label>
	</li>
		<li>
			<input class="question_radio_6278" type="checkbox" id="6278_other"   value="0" onclick="showOtherValueInputInCheckBox(this)" />			<label for="6278_other">其他</label>
			<input id="6278_other_input" type="text" name="answers[6278].otherValue" value="" style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_170_1249" style="margin-bottom:0px;" class="question-odd question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					对于您最喜欢的杂志,您最不喜欢它的哪些方面:
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[6279].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[6279].id" value="" id="answers[6279].id" />




<span id="hint_6279">
</span>
<ul>
	<li>
			<input group="6279" class="question_radio_6279 selection" type="checkbox" id="6279_0" name="answers[6279].value" value="3912" 	onclick=" "/>		<label for="6279_0">广告太多</label>
	</li>
	<li>
			<input group="6279" class="question_radio_6279 selection" type="checkbox" id="6279_1" name="answers[6279].value" value="3913" 	onclick=" "/>		<label for="6279_1">内容陈旧</label>
	</li>
	<li>
			<input group="6279" class="question_radio_6279 selection" type="checkbox" id="6279_2" name="answers[6279].value" value="3914" 	onclick=" "/>		<label for="6279_2">封面设计差</label>
	</li>
	<li>
			<input group="6279" class="question_radio_6279 selection" type="checkbox" id="6279_3" name="answers[6279].value" value="3915" 	onclick=" "/>		<label for="6279_3">排版印刷粗糙</label>
	</li>
	<li>
			<input group="6279" class="question_radio_6279 selection" type="checkbox" id="6279_4" name="answers[6279].value" value="3916" 	onclick=" "/>		<label for="6279_4">价格偏高</label>
	</li>
	<li>
			<input group="6279" class="question_radio_6279 selection" type="checkbox" id="6279_5" name="answers[6279].value" value="3917" 	onclick=" "/>		<label for="6279_5">专业术语太多</label>
	</li>
		<li>
			<input class="question_radio_6279" type="checkbox" id="6279_other"   value="0" onclick="showOtherValueInputInCheckBox(this)" />			<label for="6279_other">其他</label>
			<input id="6279_other_input" type="text" name="answers[6279].otherValue" value="" style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_170_1245" style="margin-bottom:0px;" class="question-even question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=100% valign="top">
				<div class="question-title">
					您会把这本您最喜欢的杂志推荐给朋友吗?
				</div>
				  <div class="questionnaireElementInfoText ">
				    
				  </div>
			</td>
			</tr>
			<tr>
				<td width=100% valign="top" class="question-td twoColumnLayout">
<span class="error-content" id="err_answers[6281].value" ></span>
<input type="hidden" name="answers[6281].id" value="" id="answers[6281].id" />
<table>
<tr>

<td>

<div class="left-label">完全不会</div>
	<table class="rating-table">
		<tr class="radio-line">
					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[6281].value" value="0" id="6281_0" group="6281" class="question_radio_6281 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6281].value" value="1" id="6281_1" group="6281" class="question_radio_6281 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6281].value" value="2" id="6281_2" group="6281" class="question_radio_6281 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6281].value" value="3" id="6281_3" group="6281" class="question_radio_6281 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6281].value" value="4" id="6281_4" group="6281" class="question_radio_6281 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6281].value" value="5" id="6281_5" group="6281" class="question_radio_6281 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6281].value" value="6" id="6281_6" group="6281" class="question_radio_6281 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6281].value" value="7" id="6281_7" group="6281" class="question_radio_6281 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6281].value" value="8" id="6281_8" group="6281" class="question_radio_6281 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6281].value" value="9" id="6281_9" group="6281" class="question_radio_6281 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[6281].value" value="10" id="6281_10" group="6281" class="question_radio_6281 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">肯定会</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[6281].value" value="" id="answers[6281].value" class="q_6281 qc_170 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_170_1250" style="margin-bottom:0px;" class="question-odd question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					今年您买过悦己或者VOGUE服饰与美容杂志吗?
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[6280].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[6280].id" value="" id="answers[6280].id" />
<ul>
	<li>
			<input group="6280" type="radio" id="6280_0" name="answers[6280].value" value="3918"  class="selection question_radio_6280"  />		<label for="6280_0">两本都买过</label>
	</li>
	<li>
			<input group="6280" type="radio" id="6280_1" name="answers[6280].value" value="3919"  class="selection question_radio_6280"  />		<label for="6280_1">只买过悦己</label>
	</li>
	<li>
			<input group="6280" type="radio" id="6280_2" name="answers[6280].value" value="3920"  class="selection question_radio_6280"  />		<label for="6280_2">只买过Vogue</label>
	</li>
	<li>
			<input group="6280" type="radio" id="6280_3" name="answers[6280].value" value="3921"  class="selection question_radio_6280"  />		<label for="6280_3">都没有买过</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_6280  qc_170 radio" type="radio" name="answers[6280].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>

</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="提交" />
</div>

</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = 'Mandatory questions must be filled out';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
            return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = 'Can not submit empty questionnaire form';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[


	 Element.hide("q_169_1235");
	 Element.hide("q_169_1239");


var myrules = {
	   
	   "input#6269_0": function(el){
			el.onclick = function(){
				if ($("6269_0").checked){
						Element.show($("q_169_1235"));
				}
			}
		}
	,
	   
	   "input#6272_5": function(el){
			el.onclick = function(){
				if ($("6272_5").checked){
						Element.show($("q_169_1239"));
				}
			}
		}
	,
	   
	   "input#6272_1": function(el){
			el.onclick = function(){
				if ($("6272_1").checked){
						Element.hide($("q_169_1239"));
				}
			}
		}
	,
	   
	   "input#6272_3": function(el){
			el.onclick = function(){
				if ($("6272_3").checked){
						Element.hide($("q_169_1239"));
				}
			}
		}
	,
	   
	   "input#6269_1": function(el){
			el.onclick = function(){
				if ($("6269_1").checked){
						Element.hide($("q_169_1235"));
				}
			}
		}
	,
	   
	   "input#6272_2": function(el){
			el.onclick = function(){
				if ($("6272_2").checked){
						Element.hide($("q_169_1239"));
				}
			}
		}
	,
	   
	   "input#6272_4": function(el){
			el.onclick = function(){
				if ($("6272_4").checked){
						Element.show($("q_169_1239"));
				}
			}
		}
}

Behaviour.register(myrules);

// ]]>
-->
</script>
