	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" style="background: #fff;width:100%;">
	<div id="container" style="background: #fff;">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" style="background:#fff;width:100%;">
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="loading();return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			$('mask').show();
		}
	}
// ]]>
-->
</script>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />

<div class="mandatory"><span style="color: red;">* </span>- It is mandatory</div>
<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>

	<div id="page_0">





<div class="header-section" id="h_180">
	<h3></h3>
<span class="header-title">
<h2>About Hand Hygiene</h2>
</span>
	<h3></h3>
</div>
<!-- <span  class="no-answer-all">No answer all <input type="checkbox" name="qc_checkbox_180" value="" id="qc_checkbox_180" onClick="checkSubboxes(180)" />
 </span>-->
<div style="clear: both ;"></div><script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_180_1199" style="margin-bottom:0px;" class="question-even question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					Did you know that 80% of all disease is transmitted through hands?
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[6834].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[6834].id" value="" id="answers[6834].id" />
<ul>
	<li>
			<input group="6834" type="radio" id="6834_0" name="answers[6834].value" value="3760"  class="selection question_radio_6834"  />		<label for="6834_0">Yes</label>
	</li>
	<li>
			<input group="6834" type="radio" id="6834_1" name="answers[6834].value" value="3761"  class="selection question_radio_6834"  />		<label for="6834_1">No</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_6834  qc_180 radio" type="radio" name="answers[6834].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_180_1200" style="margin-bottom:0px;" class="question-odd question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					Do you pay much attention on news of swine flu?
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">
<span class="error-content" id="err_answers[6835].value" ></span>
<input type="hidden" name="answers[6835].id" value="" id="answers[6835].id" />
<table>
<tr>

<td>

<div class="left-label">Not much</div>
	<table class="rating-table">
		<tr class="radio-line">
					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[6835].value" value="1" id="6835_1" group="6835" class="question_radio_6835 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6835].value" value="2" id="6835_2" group="6835" class="question_radio_6835 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6835].value" value="3" id="6835_3" group="6835" class="question_radio_6835 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6835].value" value="4" id="6835_4" group="6835" class="question_radio_6835 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[6835].value" value="5" id="6835_5" group="6835" class="question_radio_6835 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">Very</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[6835].value" value="" id="answers[6835].value" class="q_6835 qc_180 radio" />
</td>
</tr>
</table>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_180_1202" style="margin-bottom:0px;" class="question-even question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					What will you do to avoid swine flu?
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[6836].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[6836].id" value="" id="answers[6836].id" />




<span id="hint_6836">
</span>
<ul>
	<li>
			<input group="6836" class="question_radio_6836 selection" type="checkbox" id="6836_0" name="answers[6836].value" value="3764" 	onclick=" "/>		<label for="6836_0">Become vegetarian</label>
	</li>
	<li>
			<input group="6836" class="question_radio_6836 selection" type="checkbox" id="6836_1" name="answers[6836].value" value="3765" 	onclick=" "/>		<label for="6836_1">Wipe everything with alcohol</label>
	</li>
	<li>
			<input group="6836" class="question_radio_6836 selection" type="checkbox" id="6836_2" name="answers[6836].value" value="3766" 	onclick=" "/>		<label for="6836_2">Don’t eat foods outside</label>
	</li>
	<li>
			<input group="6836" class="question_radio_6836 selection" type="checkbox" id="6836_3" name="answers[6836].value" value="3767" 	onclick=" "/>		<label for="6836_3">Wash hands a lot</label>
	</li>
	<li>
			<input group="6836" class="question_radio_6836 selection" type="checkbox" id="6836_4" name="answers[6836].value" value="3768" 	onclick=" "/>		<label for="6836_4">Just be more cautious</label>
	</li>
	<li>
			<input group="6836" class="question_radio_6836 selection" type="checkbox" id="6836_5" name="answers[6836].value" value="3769" 	onclick=" "/>		<label for="6836_5">Nothing unusual</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_180_1203" style="margin-bottom:0px;" class="question-odd question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					How frequently do you wash your hands?
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[6837].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[6837].id" value="" id="answers[6837].id" />
<ul>
	<li>
			<input group="6837" type="radio" id="6837_0" name="answers[6837].value" value="3770"  class="selection question_radio_6837"  />		<label for="6837_0">Less than 5 time in one day</label>
	</li>
	<li>
			<input group="6837" type="radio" id="6837_1" name="answers[6837].value" value="3771"  class="selection question_radio_6837"  />		<label for="6837_1">5-10 times a day</label>
	</li>
	<li>
			<input group="6837" type="radio" id="6837_2" name="answers[6837].value" value="3772"  class="selection question_radio_6837"  />		<label for="6837_2">Once every hour</label>
	</li>
	<li>
			<input group="6837" type="radio" id="6837_3" name="answers[6837].value" value="3773"  class="selection question_radio_6837"  />		<label for="6837_3">Several time every hour</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_6837  qc_180 radio" type="radio" name="answers[6837].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_180_1204" style="margin-bottom:0px;" class="question-even question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					Do you have children?
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[6838].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[6838].id" value="" id="answers[6838].id" />
<ul>
	<li>
			<input group="6838" type="radio" id="6838_0" name="answers[6838].value" value="3774"  class="selection question_radio_6838"  />		<label for="6838_0">Yes</label>
	</li>
	<li>
			<input group="6838" type="radio" id="6838_1" name="answers[6838].value" value="3775"  class="selection question_radio_6838"  />		<label for="6838_1">No</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_6838  qc_180 radio" type="radio" name="answers[6838].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_180_1205" style="margin-bottom:0px;" class="question-odd question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					What do you use to sanitize for your Children?
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[6839].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[6839].id" value="" id="answers[6839].id" />




<span id="hint_6839">
</span>
<ul>
	<li>
			<input group="6839" class="question_radio_6839 selection" type="checkbox" id="6839_0" name="answers[6839].value" value="3776" 	onclick=" "/>		<label for="6839_0">Soap</label>
	</li>
	<li>
			<input group="6839" class="question_radio_6839 selection" type="checkbox" id="6839_1" name="answers[6839].value" value="3777" 	onclick=" "/>		<label for="6839_1">Liquid soap</label>
	</li>
	<li>
			<input group="6839" class="question_radio_6839 selection" type="checkbox" id="6839_2" name="answers[6839].value" value="3778" 	onclick=" "/>		<label for="6839_2">Wet paper towel</label>
	</li>
	<li>
			<input group="6839" class="question_radio_6839 selection" type="checkbox" id="6839_3" name="answers[6839].value" value="3779" 	onclick=" "/>		<label for="6839_3">Alcohol</label>
	</li>
	<li>
			<input group="6839" class="question_radio_6839 selection" type="checkbox" id="6839_4" name="answers[6839].value" value="3780" 	onclick=" "/>		<label for="6839_4">Hand sanitizer</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_180_1206" style="margin-bottom:0px;" class="question-even question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					Have you used Hand sanitizer yourself?
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[6840].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[6840].id" value="" id="answers[6840].id" />
<ul>
	<li>
			<input group="6840" type="radio" id="6840_0" name="answers[6840].value" value="3781"  class="selection question_radio_6840"  />		<label for="6840_0">Yes</label>
	</li>
	<li>
			<input group="6840" type="radio" id="6840_1" name="answers[6840].value" value="3782"  class="selection question_radio_6840"  />		<label for="6840_1">No</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_6840  qc_180 radio" type="radio" name="answers[6840].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_180_1207" style="margin-bottom:0px;" class="question-odd question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					Why do you use hand sanitizer (more than one choice)
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[6841].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[6841].id" value="" id="answers[6841].id" />




<span id="hint_6841">
</span>
<ul>
	<li>
			<input group="6841" class="question_radio_6841 selection" type="checkbox" id="6841_0" name="answers[6841].value" value="3783" 	onclick=" "/>		<label for="6841_0">Squeeze intake, convenient &amp; instant</label>
	</li>
	<li>
			<input group="6841" class="question_radio_6841 selection" type="checkbox" id="6841_1" name="answers[6841].value" value="3784" 	onclick=" "/>		<label for="6841_1">Uperization &amp; degerming; safety, moisten</label>
	</li>
	<li>
			<input group="6841" class="question_radio_6841 selection" type="checkbox" id="6841_2" name="answers[6841].value" value="3785" 	onclick=" "/>		<label for="6841_2">Convenient portable/ using anytime &amp; anyplace</label>
	</li>
	<li>
			<input group="6841" class="question_radio_6841 selection" type="checkbox" id="6841_3" name="answers[6841].value" value="3786" 	onclick=" "/>		<label for="6841_3">Clean &amp; health; avoid cross-infection</label>
	</li>
	<li>
			<input group="6841" class="question_radio_6841 selection" type="checkbox" id="6841_4" name="answers[6841].value" value="3787" 	onclick=" "/>		<label for="6841_4">Environmental protection &amp; water conservation</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_180_1301" style="margin-bottom:0px;" class="question-even question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					What brand you are familiar with?
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[6842].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[6842].id" value="" id="answers[6842].id" />




<span id="hint_6842">
</span>
<ul>
	<li>
			<input group="6842" class="question_radio_6842 selection" type="checkbox" id="6842_0" name="answers[6842].value" value="4232" 	onclick=" "/>		<label for="6842_0">PURELL</label>
	</li>
	<li>
			<input group="6842" class="question_radio_6842 selection" type="checkbox" id="6842_1" name="answers[6842].value" value="4233" 	onclick=" "/>		<label for="6842_1">Anyway</label>
	</li>
	<li>
			<input group="6842" class="question_radio_6842 selection" type="checkbox" id="6842_2" name="answers[6842].value" value="4234" 	onclick=" "/>		<label for="6842_2">Walch</label>
	</li>
	<li>
			<input group="6842" class="question_radio_6842 selection" type="checkbox" id="6842_3" name="answers[6842].value" value="4235" 	onclick=" "/>		<label for="6842_3">Watson</label>
	</li>
	<li>
			<input group="6842" class="question_radio_6842 selection" type="checkbox" id="6842_4" name="answers[6842].value" value="4236" 	onclick=" "/>		<label for="6842_4">WOODWARD’S</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
	<div id="q_180_1209" style="margin-bottom:0px;" class="question-odd question-area">
		<table class="question-table">
		    		   
			<tr>
			<td width=50% valign="top">
				<div class="question-title">
					Do you talk about cleaning ways with your friends after swine flu boosted?
				</div>
				  <div class="questionnaireElementInfoText twoColumnLayout">
				    
				  </div>
			</td>
			<td width=50% valign="top" class="question-td" style="padding-left:15px;">
<span class="error-content" id="err_answers[6843].value" ></span>
<input type="hidden" name="answers[6843].id" value="" id="answers[6843].id" />
<table>
<tr>

<td>

<div class="left-label">Not much</div>
	<table class="rating-table">
		<tr class="radio-line">
					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[6843].value" value="1" id="6843_1" group="6843" class="question_radio_6843 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6843].value" value="2" id="6843_2" group="6843" class="question_radio_6843 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6843].value" value="3" id="6843_3" group="6843" class="question_radio_6843 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[6843].value" value="4" id="6843_4" group="6843" class="question_radio_6843 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[6843].value" value="5" id="6843_5" group="6843" class="question_radio_6843 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">A lot</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[6843].value" value="" id="answers[6843].value" class="q_6843 qc_180 radio" />
</td>
</tr>
</table>
			</td>
			</tr>
	    </table>
    </div>
    <div style="clear:both;"></div>

</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="Submit" />
</div>

</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = 'Mandatory questions must be filled out';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
            return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = 'Can not submit empty questionnaire form';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[


	 Element.hide("q_180_1205");
	 Element.hide("q_180_1207");


var myrules = {
	   
	   "input#6840_0": function(el){
			el.onclick = function(){
				if ($("6840_0").checked){
						Element.show($("q_180_1207"));
				}
			}
		}
	,
	   
	   "input#6838_1": function(el){
			el.onclick = function(){
				if ($("6838_1").checked){
						Element.hide($("q_180_1205"));
				}
			}
		}
	,
	   
	   "input#6840_1": function(el){
			el.onclick = function(){
				if ($("6840_1").checked){
						Element.hide($("q_180_1207"));
				}
			}
		}
	,
	   
	   "input#6838_0": function(el){
			el.onclick = function(){
				if ($("6838_0").checked){
						Element.show($("q_180_1205"));
				}
			}
		}
}

Behaviour.register(myrules);

// ]]>
-->
</script>
