<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<META NAME="ROBOTS" CONTENT="NOINDEX,NOFOLLOW">
	<title>Indicate - Fill out survey</title>
	<link href="/css/crystal.css" rel="stylesheet" type="text/css" media="screen, print" />
	<!--[if IE]>
	<link href="/css/crystal-ie.css" rel="stylesheet" type="text/css" media="screen" />
	<![endif]-->
	<link href="/css/fillout_default.css" rel="stylesheet" type="text/css" media="screen" />
	<!--[if IE]>
	<link href="/css/fillout_default-ie.css" rel="stylesheet" type="text/css" media="screen" />
	<![endif]-->
	<link href="/css/niftyCorners.css" rel="stylesheet" type="text/css" media="screen" />
	<script src="/js/all.js" language="JavaScript" type="text/javascript"></script>
	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
</head>

<body>
<div class="main-container-outer">
	<div id="container">
		<div id="header" class="header">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.wildfire.asia" target="_blank">
					<img src="/survey/logoImage/37" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content">
 		

<div id="content">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://i2.wildfire.asia/fillout" onsubmit="loading();return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">
<div class="questionnaire-title">DSM</div>


<input type="hidden" name="id" value="53oGgOEhv4Qk" id="id" />
<input type="hidden" name="theme" value="default" id="theme" />
<input type="hidden" name="surveyId" value="53oGgOEhv4Qk"/>

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_160" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						How often do you do exercise (walking, jogging, sports etc.)
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[1173].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[1173].id" value="" id="answers[1173].id" />
<ul>
	<li>
			<input group="1173" type="radio" id="1173_0" name="answers[1173].value" value="403"  class="selection question_radio_1173"  />		<label for="1173_0">Never</label>
	</li>
	<li>
			<input group="1173" type="radio" id="1173_1" name="answers[1173].value" value="404"  class="selection question_radio_1173"  />		<label for="1173_1">Less than once a month</label>
	</li>
	<li>
			<input group="1173" type="radio" id="1173_2" name="answers[1173].value" value="405"  class="selection question_radio_1173"  />		<label for="1173_2">About once or twice a month</label>
	</li>
	<li>
			<input group="1173" type="radio" id="1173_3" name="answers[1173].value" value="406"  class="selection question_radio_1173"  />		<label for="1173_3">About once or twice per week</label>
	</li>
	<li>
			<input group="1173" type="radio" id="1173_4" name="answers[1173].value" value="407"  class="selection question_radio_1173"  />		<label for="1173_4">More often than twice per week</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_1173  qc_0 radio" type="radio" name="answers[1173].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_136" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Do you drink energy drink? 
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[1174].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[1174].id" value="" id="answers[1174].id" />
<ul>
	<li>
			<input group="1174" type="radio" id="1174_0" name="answers[1174].value" value="350"  class="selection question_radio_1174"  />		<label for="1174_0">no, never</label>
	</li>
	<li>
			<input group="1174" type="radio" id="1174_1" name="answers[1174].value" value="351"  class="selection question_radio_1174"  />		<label for="1174_1">never, but would like to try</label>
	</li>
	<li>
			<input group="1174" type="radio" id="1174_2" name="answers[1174].value" value="352"  class="selection question_radio_1174"  />		<label for="1174_2">very little, less than once a month</label>
	</li>
	<li>
			<input group="1174" type="radio" id="1174_3" name="answers[1174].value" value="353"  class="selection question_radio_1174"  />		<label for="1174_3">about once or twice a month</label>
	</li>
	<li>
			<input group="1174" type="radio" id="1174_4" name="answers[1174].value" value="354"  class="selection question_radio_1174"  />		<label for="1174_4">about once or twice per week</label>
	</li>
	<li>
			<input group="1174" type="radio" id="1174_5" name="answers[1174].value" value="355"  class="selection question_radio_1174"  />		<label for="1174_5">more often than twice per week</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_1174  qc_0 radio" type="radio" name="answers[1174].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_137" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Which brands of energy drink can you name?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[1175].id" value="" id="answers[1175].id" />
<input type="text" name="answers[1175].value" value="" id="question_1175" group="1175" class="input-text" />

<span class="error-content" id="err_answers[1175].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_138" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Do you think supplement is beneficial for you to take?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[1176].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[1176].id" value="" id="answers[1176].id" />
<ul>
	<li>
			<input group="1176" type="radio" id="1176_0" name="answers[1176].value" value="356"  class="selection question_radio_1176"  />		<label for="1176_0">Yes</label>
	</li>
	<li>
			<input group="1176" type="radio" id="1176_1" name="answers[1176].value" value="357"  class="selection question_radio_1176"  />		<label for="1176_1">No</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_1176  qc_0 radio" type="radio" name="answers[1176].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_161" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Which of the vitamins below do you know?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[1177].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[1177].id" value="" id="answers[1177].id" />




<span id="hint_1177">
</span>
<ul>
	<li>
			<input group="1177" class="question_radio_1177 selection" type="checkbox" id="1177_0" name="answers[1177].value" value="408" 	onclick=" "/>		<label for="1177_0">I DON'T TAKE ANY SUPPLEMENTS</label>
	</li>
	<li>
			<input group="1177" class="question_radio_1177 selection" type="checkbox" id="1177_1" name="answers[1177].value" value="409" 	onclick=" "/>		<label for="1177_1">Vitamin (A, B, C, D, E, K)</label>
	</li>
	<li>
			<input group="1177" class="question_radio_1177 selection" type="checkbox" id="1177_2" name="answers[1177].value" value="410" 	onclick=" "/>		<label for="1177_2">Minerals (iron, zinc, calcium, etc.)</label>
	</li>
	<li>
			<input group="1177" class="question_radio_1177 selection" type="checkbox" id="1177_3" name="answers[1177].value" value="411" 	onclick=" "/>		<label for="1177_3">Protein</label>
	</li>
	<li>
			<input group="1177" class="question_radio_1177 selection" type="checkbox" id="1177_4" name="answers[1177].value" value="412" 	onclick=" "/>		<label for="1177_4">Creatine</label>
	</li>
	<li>
			<input group="1177" class="question_radio_1177 selection" type="checkbox" id="1177_5" name="answers[1177].value" value="413" 	onclick=" "/>		<label for="1177_5">Fish oil (omega 3/6/9)</label>
	</li>
	<li>
			<input group="1177" class="question_radio_1177 selection" type="checkbox" id="1177_6" name="answers[1177].value" value="414" 	onclick=" "/>		<label for="1177_6">Fiber supplement</label>
	</li>
	<li>
			<input group="1177" class="question_radio_1177 selection" type="checkbox" id="1177_7" name="answers[1177].value" value="415" 	onclick=" "/>		<label for="1177_7">Probiotics</label>
	</li>
	<li>
			<input group="1177" class="question_radio_1177 selection" type="checkbox" id="1177_8" name="answers[1177].value" value="416" 	onclick=" "/>		<label for="1177_8">Chinese medicine</label>
	</li>
		<li>
			<input class="question_radio_1177" type="checkbox" id="1177_other"   value="0" onclick="showOtherValueInputInCheckBox(this)" />			<label for="1177_other">Other</label>
			<input id="1177_other_input" type="text" name="answers[1177].otherValue" value="" style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_164" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Which of the vitamins below do you take as a supplement?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[1178].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[1178].id" value="" id="answers[1178].id" />




<span id="hint_1178">
</span>
<ul>
	<li>
			<input group="1178" class="question_radio_1178 selection" type="checkbox" id="1178_0" name="answers[1178].value" value="426" 	onclick=" "/>		<label for="1178_0">I DON'T TAKE ANY SUPPLEMENTS</label>
	</li>
	<li>
			<input group="1178" class="question_radio_1178 selection" type="checkbox" id="1178_1" name="answers[1178].value" value="427" 	onclick=" "/>		<label for="1178_1">Vitamin (A, B, C, D, E, K)</label>
	</li>
	<li>
			<input group="1178" class="question_radio_1178 selection" type="checkbox" id="1178_2" name="answers[1178].value" value="428" 	onclick=" "/>		<label for="1178_2">Minerals (iron, zinc, calcium, etc.)</label>
	</li>
	<li>
			<input group="1178" class="question_radio_1178 selection" type="checkbox" id="1178_3" name="answers[1178].value" value="429" 	onclick=" "/>		<label for="1178_3">Protein</label>
	</li>
	<li>
			<input group="1178" class="question_radio_1178 selection" type="checkbox" id="1178_4" name="answers[1178].value" value="430" 	onclick=" "/>		<label for="1178_4">Creatinine</label>
	</li>
	<li>
			<input group="1178" class="question_radio_1178 selection" type="checkbox" id="1178_5" name="answers[1178].value" value="431" 	onclick=" "/>		<label for="1178_5">Fish oil (omega 3/6/9)</label>
	</li>
	<li>
			<input group="1178" class="question_radio_1178 selection" type="checkbox" id="1178_6" name="answers[1178].value" value="432" 	onclick=" "/>		<label for="1178_6">Fiber supplement</label>
	</li>
	<li>
			<input group="1178" class="question_radio_1178 selection" type="checkbox" id="1178_7" name="answers[1178].value" value="433" 	onclick=" "/>		<label for="1178_7">Probiotics</label>
	</li>
	<li>
			<input group="1178" class="question_radio_1178 selection" type="checkbox" id="1178_8" name="answers[1178].value" value="434" 	onclick=" "/>		<label for="1178_8">Chinese medicine</label>
	</li>
		<li>
			<input class="question_radio_1178" type="checkbox" id="1178_other"   value="0" onclick="showOtherValueInputInCheckBox(this)" />			<label for="1178_other">Other</label>
			<input id="1178_other_input" type="text" name="answers[1178].otherValue" value="" style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_141" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						medically proven benefits
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[1179].value" ></span>
<input type="hidden" name="answers[1179].id" value="" id="answers[1179].id" />
<table>
<tr>

<td>

<div class="left-label">Left Label</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[1179].value" value="1" id="1179_1" group="1179" class="question_radio_1179 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[1179].value" value="2" id="1179_2" group="1179" class="question_radio_1179 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[1179].value" value="3" id="1179_3" group="1179" class="question_radio_1179 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[1179].value" value="4" id="1179_4" group="1179" class="question_radio_1179 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[1179].value" value="5" id="1179_5" group="1179" class="question_radio_1179 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">Right Label</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[1179].value" value="" id="answers[1179].value" class="q_1179 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_142" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						recommended by friends/family
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[1180].value" ></span>
<input type="hidden" name="answers[1180].id" value="" id="answers[1180].id" />
<table>
<tr>

<td>

<div class="left-label">Left Label</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[1180].value" value="1" id="1180_1" group="1180" class="question_radio_1180 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[1180].value" value="2" id="1180_2" group="1180" class="question_radio_1180 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[1180].value" value="3" id="1180_3" group="1180" class="question_radio_1180 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[1180].value" value="4" id="1180_4" group="1180" class="question_radio_1180 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[1180].value" value="5" id="1180_5" group="1180" class="question_radio_1180 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">Right Label</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[1180].value" value="" id="answers[1180].value" class="q_1180 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_143" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						tastes good
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[1181].value" ></span>
<input type="hidden" name="answers[1181].id" value="" id="answers[1181].id" />
<table>
<tr>

<td>

<div class="left-label">Left Label</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[1181].value" value="1" id="1181_1" group="1181" class="question_radio_1181 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[1181].value" value="2" id="1181_2" group="1181" class="question_radio_1181 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[1181].value" value="3" id="1181_3" group="1181" class="question_radio_1181 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[1181].value" value="4" id="1181_4" group="1181" class="question_radio_1181 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[1181].value" value="5" id="1181_5" group="1181" class="question_radio_1181 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">Right Label</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[1181].value" value="" id="answers[1181].value" class="q_1181 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_144" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						is not expensive
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[1182].value" ></span>
<input type="hidden" name="answers[1182].id" value="" id="answers[1182].id" />
<table>
<tr>

<td>

<div class="left-label">Left Label</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[1182].value" value="1" id="1182_1" group="1182" class="question_radio_1182 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[1182].value" value="2" id="1182_2" group="1182" class="question_radio_1182 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[1182].value" value="3" id="1182_3" group="1182" class="question_radio_1182 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[1182].value" value="4" id="1182_4" group="1182" class="question_radio_1182 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[1182].value" value="5" id="1182_5" group="1182" class="question_radio_1182 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">Right Label</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[1182].value" value="" id="answers[1182].value" class="q_1182 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_145" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						high-quality ingredients
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[1183].value" ></span>
<input type="hidden" name="answers[1183].id" value="" id="answers[1183].id" />
<table>
<tr>

<td>

<div class="left-label">Left Label</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[1183].value" value="1" id="1183_1" group="1183" class="question_radio_1183 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[1183].value" value="2" id="1183_2" group="1183" class="question_radio_1183 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[1183].value" value="3" id="1183_3" group="1183" class="question_radio_1183 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[1183].value" value="4" id="1183_4" group="1183" class="question_radio_1183 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[1183].value" value="5" id="1183_5" group="1183" class="question_radio_1183 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">Right Label</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[1183].value" value="" id="answers[1183].value" class="q_1183 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_146" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						product is from Europe/USA
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[1184].value" ></span>
<input type="hidden" name="answers[1184].id" value="" id="answers[1184].id" />
<table>
<tr>

<td>

<div class="left-label">Left Label</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[1184].value" value="1" id="1184_1" group="1184" class="question_radio_1184 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[1184].value" value="2" id="1184_2" group="1184" class="question_radio_1184 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[1184].value" value="3" id="1184_3" group="1184" class="question_radio_1184 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[1184].value" value="4" id="1184_4" group="1184" class="question_radio_1184 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[1184].value" value="5" id="1184_5" group="1184" class="question_radio_1184 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">Right Label</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[1184].value" value="" id="answers[1184].value" class="q_1184 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_159" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						When you want to know more about a product, where do you go for information?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[1185].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[1185].id" value="" id="answers[1185].id" />




<span id="hint_1185">
</span>
<ul>
	<li>
			<input group="1185" class="question_radio_1185 selection" type="checkbox" id="1185_0" name="answers[1185].value" value="396" 	onclick=" "/>		<label for="1185_0">I ask my family and friends</label>
	</li>
	<li>
			<input group="1185" class="question_radio_1185 selection" type="checkbox" id="1185_1" name="answers[1185].value" value="397" 	onclick=" "/>		<label for="1185_1">I search the internet</label>
	</li>
	<li>
			<input group="1185" class="question_radio_1185 selection" type="checkbox" id="1185_2" name="answers[1185].value" value="398" 	onclick=" "/>		<label for="1185_2">I look on social media like Facebook</label>
	</li>
	<li>
			<input group="1185" class="question_radio_1185 selection" type="checkbox" id="1185_3" name="answers[1185].value" value="399" 	onclick=" "/>		<label for="1185_3">I read books/magazines related to that product</label>
	</li>
	<li>
			<input group="1185" class="question_radio_1185 selection" type="checkbox" id="1185_4" name="answers[1185].value" value="400" 	onclick=" "/>		<label for="1185_4">I get the information I need from TV advertisements</label>
	</li>
	<li>
			<input group="1185" class="question_radio_1185 selection" type="checkbox" id="1185_5" name="answers[1185].value" value="401" 	onclick=" "/>		<label for="1185_5">I read the label on the product itself</label>
	</li>
	<li>
			<input group="1185" class="question_radio_1185 selection" type="checkbox" id="1185_6" name="answers[1185].value" value="402" 	onclick=" "/>		<label for="1185_6">I talk to my doctor</label>
	</li>
		<li>
			<input class="question_radio_1185" type="checkbox" id="1185_other"   value="0" onclick="showOtherValueInputInCheckBox(this)" />			<label for="1185_other">Other</label>
			<input id="1185_other_input" type="text" name="answers[1185].otherValue" value="" style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_156" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Do you check the nutrition information on the products you buy?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[1186].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[1186].id" value="" id="answers[1186].id" />
<ul>
	<li>
			<input group="1186" type="radio" id="1186_0" name="answers[1186].value" value="384"  class="selection question_radio_1186"  />		<label for="1186_0">No</label>
	</li>
	<li>
			<input group="1186" type="radio" id="1186_1" name="answers[1186].value" value="385"  class="selection question_radio_1186"  />		<label for="1186_1">Yes</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_1186  qc_0 radio" type="radio" name="answers[1186].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_157" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						what do you pay attention to?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[1187].id" value="" id="answers[1187].id" />
<input type="text" name="answers[1187].value" value="" id="question_1187" group="1187" class="input-text" />

<span class="error-content" id="err_answers[1187].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_150" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						What's your highest completed education level?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[1188].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[1188].id" value="" id="answers[1188].id" />
<ul>
	<li>
			<input group="1188" type="radio" id="1188_0" name="answers[1188].value" value="379"  class="selection question_radio_1188"  />		<label for="1188_0">none</label>
	</li>
	<li>
			<input group="1188" type="radio" id="1188_1" name="answers[1188].value" value="380"  class="selection question_radio_1188"  />		<label for="1188_1">highschool</label>
	</li>
	<li>
			<input group="1188" type="radio" id="1188_2" name="answers[1188].value" value="381"  class="selection question_radio_1188"  />		<label for="1188_2">bachelor's</label>
	</li>
	<li>
			<input group="1188" type="radio" id="1188_3" name="answers[1188].value" value="382"  class="selection question_radio_1188"  />		<label for="1188_3">master's</label>
	</li>
	<li>
			<input group="1188" type="radio" id="1188_4" name="answers[1188].value" value="383"  class="selection question_radio_1188"  />		<label for="1188_4">PhD.</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_1188  qc_0 radio" type="radio" name="answers[1188].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_86" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Email
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[1189].id" value="" id="answers[1189].id" />
<input type="text" name="answers[1189].value" value="" id="question_1189" group="1189" class="input-text" />

<span class="error-content" id="err_answers[1189].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_92" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Name
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[1190].id" value="" id="answers[1190].id" />
<input type="text" name="answers[1190].value" value="" id="question_1190" group="1190" class="input-text" />

<span class="error-content" id="err_answers[1190].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_122" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Phone
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[1191].id" value="" id="answers[1191].id" />
<input type="text" name="answers[1191].value" value="" id="question_1191" group="1191" class="input-text" />

<span class="error-content" id="err_answers[1191].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_151" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Age
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[1192].id" value="" id="answers[1192].id" />
<input type="text" name="answers[1192].value" value="" id="question_1192" group="1192" class="input-text" />

<span class="error-content" id="err_answers[1192].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_152" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						HH inc
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[1193].id" value="" id="answers[1193].id" />
<input type="text" name="answers[1193].value" value="" id="question_1193" group="1193" class="input-text" />

<span class="error-content" id="err_answers[1193].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_163" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Location
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[1194].id" value="" id="answers[1194].id" />
<input type="text" name="answers[1194].value" value="" id="question_1194" group="1194" class="input-text" />

<span class="error-content" id="err_answers[1194].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_154" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Gender
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[1195].id" value="" id="answers[1195].id" />
<input type="text" name="answers[1195].value" value="" id="question_1195" group="1195" class="input-text" />

<span class="error-content" id="err_answers[1195].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="Submit" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://i2.wildfire.asia/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://i2.wildfire.asia/images/web_dialog_m_t.gif"><img src="http://i2.wildfire.asia/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://i2.wildfire.asia/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://i2.wildfire.asia/images/web_dialog_l_m.gif"><img src="http://i2.wildfire.asia/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://i2.wildfire.asia/images/web_dialog_r_m.gif"><img src="http://i2.wildfire.asia/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://i2.wildfire.asia/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://i2.wildfire.asia/images/web_dialog_m_b.gif"><img src="http://i2.wildfire.asia/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://i2.wildfire.asia/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://i2.wildfire.asia/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '<span style="color:red">*&nbsp;&nbsp;</span>Mandatory questions must be filled out';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '<span style="color:red">*&nbsp;&nbsp;</span>Can not submit empty questionnaire form';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow"></div>
	<div style="clear: both"></div>
	
</div> 
</body>
</html>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

Framework.registerAjaxSensors();
// ]]>
-->
</script>
