	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/398" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="loading();return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="KMJoU2F55wx0" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1550" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在过去的三个月，不论线上或线下，您一共在多少场景提到过蓝泉书店？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[8135].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[8135].id" value="" id="answers[8135].id" />

	<select group="8135" class="selection" id="question_8135" name="answers[8135].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="5367" style=""  >0</option>
<option value="5368" style=""  >1</option>
<option value="5369" style=""  >2</option>
<option value="5370" style=""  >3</option>
<option value="5371" style=""  >4</option>
<option value="5372" style=""  >5</option>
<option value="5373" style=""  >6</option>
<option value="5374" style=""  >7</option>
<option value="5375" style=""  >8</option>
<option value="5376" style=""  >9</option>
<option value="5377" style=""  >10</option>
<option value="5378" style=""  >11</option>
<option value="5379" style=""  >12</option>
<option value="5380" style=""  >13</option>
<option value="5381" style=""  >14</option>
<option value="5382" style=""  >15</option>
<option value="5383" style=""  >16</option>
<option value="5384" style=""  >17</option>
<option value="5385" style=""  >18</option>
<option value="5386" style=""  >19</option>
<option value="5387" style=""  >20</option>
<option value="5388" style=""  >20+</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1482" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您在蓝泉书店买过书吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[8136].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[8136].id" value="" id="answers[8136].id" />
<ul>
	<li>
			<input group="8136" type="radio" id="8136_0" name="answers[8136].value" value="5020"  class="selection question_radio_8136"  />		<label for="8136_0">是的</label>
	</li>
	<li>
			<input group="8136" type="radio" id="8136_1" name="answers[8136].value" value="5021"  class="selection question_radio_8136"  />		<label for="8136_1">没有</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_8136  qc_0 radio" type="radio" name="answers[8136].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1539" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请给出详细描述
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[8137].id" value="" id="answers[8137].id" />
<textarea name="answers[8137].value" id="question_8137" cols="40" group="8137" rows="2" class="input-text" ></textarea>
<span class="error-content" id="err_answers[8137].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1540" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请给出原因
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[8138].id" value="" id="answers[8138].id" />
<textarea name="answers[8138].value" id="question_8138" cols="40" group="8138" rows="2" class="input-text" ></textarea>
<span class="error-content" id="err_answers[8138].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1483" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您或您的朋友使用优惠券的时候遇到过问题吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[8139].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[8139].id" value="" id="answers[8139].id" />
<ul>
	<li>
			<input group="8139" type="radio" id="8139_0" name="answers[8139].value" value="5022"  class="selection question_radio_8139"  />		<label for="8139_0">是的，遇到过</label>
	</li>
	<li>
			<input group="8139" type="radio" id="8139_1" name="answers[8139].value" value="5023"  class="selection question_radio_8139"  />		<label for="8139_1">没有</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_8139  qc_0 radio" type="radio" name="answers[8139].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1541" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请给出对优惠券的评价
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[8140].id" value="" id="answers[8140].id" />
<textarea name="answers[8140].value" id="question_8140" cols="40" group="8140" rows="2" class="input-text" ></textarea>
<span class="error-content" id="err_answers[8140].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1485" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=100% valign="top">
					<div class="question-title">
						有多大可能，您将来会把蓝泉书店推荐给您的朋友？
					</div>
							<div class="elementInfoText " >
							   
							</div>
				</td>
			</tr>
			 <tr>
				<td width=100% valign="top" class="question-td twoColumnLayout" style="padding-left:15px;">
<span class="error-content" id="err_answers[8141].value" ></span>
<input type="hidden" name="answers[8141].id" value="" id="answers[8141].id" />
<table>
<tr>

<td>

<div class="left-label">根本不会</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[8141].value" value="0" id="8141_0" group="8141" class="question_radio_8141 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[8141].value" value="1" id="8141_1" group="8141" class="question_radio_8141 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[8141].value" value="2" id="8141_2" group="8141" class="question_radio_8141 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[8141].value" value="3" id="8141_3" group="8141" class="question_radio_8141 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[8141].value" value="4" id="8141_4" group="8141" class="question_radio_8141 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[8141].value" value="5" id="8141_5" group="8141" class="question_radio_8141 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[8141].value" value="6" id="8141_6" group="8141" class="question_radio_8141 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[8141].value" value="7" id="8141_7" group="8141" class="question_radio_8141 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[8141].value" value="8" id="8141_8" group="8141" class="question_radio_8141 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[8141].value" value="9" id="8141_9" group="8141" class="question_radio_8141 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[8141].value" value="10" id="8141_10" group="8141" class="question_radio_8141 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">非常乐意</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[8141].value" value="" id="answers[8141].value" class="q_8141 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1542" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						推荐/不推荐的原因是
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[8142].id" value="" id="answers[8142].id" />
<input type="text" name="answers[8142].value" value="" id="question_8142" group="8142" class="input-text" />

<span class="error-content" id="err_answers[8142].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1543" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您对蓝泉书店的整体感觉是什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[8143].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[8143].id" value="" id="answers[8143].id" />
<ul>
	<li>
			<input group="8143" type="radio" id="8143_0" name="answers[8143].value" value="5323"  class="selection question_radio_8143"  />		<label for="8143_0">非常看好</label>
	</li>
	<li>
			<input group="8143" type="radio" id="8143_1" name="answers[8143].value" value="5324"  class="selection question_radio_8143"  />		<label for="8143_1">有些积极的看法</label>
	</li>
	<li>
			<input group="8143" type="radio" id="8143_2" name="answers[8143].value" value="5325"  class="selection question_radio_8143"  />		<label for="8143_2">中立</label>
	</li>
	<li>
			<input group="8143" type="radio" id="8143_3" name="answers[8143].value" value="5326"  class="selection question_radio_8143"  />		<label for="8143_3">有些消极的看法</label>
	</li>
	<li>
			<input group="8143" type="radio" id="8143_4" name="answers[8143].value" value="5327"  class="selection question_radio_8143"  />		<label for="8143_4">很不看好</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_8143  qc_0 radio" type="radio" name="answers[8143].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1544" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您对蓝泉的图书有何感受？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[8144].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[8144].id" value="" id="answers[8144].id" />
<ul>
	<li>
			<input group="8144" type="radio" id="8144_0" name="answers[8144].value" value="5328"  class="selection question_radio_8144"  />		<label for="8144_0">非常好</label>
	</li>
	<li>
			<input group="8144" type="radio" id="8144_1" name="answers[8144].value" value="5329"  class="selection question_radio_8144"  />		<label for="8144_1">一般，不过还好</label>
	</li>
	<li>
			<input group="8144" type="radio" id="8144_2" name="answers[8144].value" value="5330"  class="selection question_radio_8144"  />		<label for="8144_2">不好不坏</label>
	</li>
	<li>
			<input group="8144" type="radio" id="8144_3" name="answers[8144].value" value="5331"  class="selection question_radio_8144"  />		<label for="8144_3">不是太好</label>
	</li>
	<li>
			<input group="8144" type="radio" id="8144_4" name="answers[8144].value" value="5332"  class="selection question_radio_8144"  />		<label for="8144_4">很不好</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_8144  qc_0 radio" type="radio" name="answers[8144].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1545" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您对蓝泉网站的整体印象如何？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[8145].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[8145].id" value="" id="answers[8145].id" />
<ul>
	<li>
			<input group="8145" type="radio" id="8145_0" name="answers[8145].value" value="5333"  class="selection question_radio_8145"  />		<label for="8145_0">设计非常好，很乐意使用</label>
	</li>
	<li>
			<input group="8145" type="radio" id="8145_1" name="answers[8145].value" value="5334"  class="selection question_radio_8145"  />		<label for="8145_1">设计好，使用方便</label>
	</li>
	<li>
			<input group="8145" type="radio" id="8145_2" name="answers[8145].value" value="5335"  class="selection question_radio_8145"  />		<label for="8145_2">不好也不坏</label>
	</li>
	<li>
			<input group="8145" type="radio" id="8145_3" name="answers[8145].value" value="5336"  class="selection question_radio_8145"  />		<label for="8145_3">设计不是太好，使用不方便</label>
	</li>
	<li>
			<input group="8145" type="radio" id="8145_4" name="answers[8145].value" value="5337"  class="selection question_radio_8145"  />		<label for="8145_4">设计很不好，不愿意使用</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_8145  qc_0 radio" type="radio" name="answers[8145].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1546" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请给出对蓝泉网站的评价：
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[8146].id" value="" id="answers[8146].id" />
<textarea name="answers[8146].value" id="question_8146" cols="40" group="8146" rows="2" class="input-text" ></textarea>
<span class="error-content" id="err_answers[8146].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1547" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您对蓝泉的价格有何评价？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[8147].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[8147].id" value="" id="answers[8147].id" />
<ul>
	<li>
			<input group="8147" type="radio" id="8147_0" name="answers[8147].value" value="5338"  class="selection question_radio_8147"  />		<label for="8147_0">很便宜</label>
	</li>
	<li>
			<input group="8147" type="radio" id="8147_1" name="answers[8147].value" value="5339"  class="selection question_radio_8147"  />		<label for="8147_1">比较便宜</label>
	</li>
	<li>
			<input group="8147" type="radio" id="8147_2" name="answers[8147].value" value="5340"  class="selection question_radio_8147"  />		<label for="8147_2">不便宜也不贵</label>
	</li>
	<li>
			<input group="8147" type="radio" id="8147_3" name="answers[8147].value" value="5341"  class="selection question_radio_8147"  />		<label for="8147_3">比较贵</label>
	</li>
	<li>
			<input group="8147" type="radio" id="8147_4" name="answers[8147].value" value="5342"  class="selection question_radio_8147"  />		<label for="8147_4">非常贵</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_8147  qc_0 radio" type="radio" name="answers[8147].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1491" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在此次活动中，您给您的朋友多少张优惠券？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[8148].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[8148].id" value="" id="answers[8148].id" />

	<select group="8148" class="selection" id="question_8148" name="answers[8148].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="5044" style=""  >0</option>
<option value="5045" style=""  >1</option>
<option value="5046" style=""  >2</option>
<option value="5047" style=""  >3</option>
<option value="5048" style=""  >4</option>
<option value="5049" style=""  >5</option>
<option value="5050" style=""  >6</option>
<option value="5051" style=""  >7</option>
<option value="5052" style=""  >8</option>
<option value="5053" style=""  >9</option>
<option value="5054" style=""  >10</option>
<option value="5055" style=""  >10+</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1548" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在此次活动中，您从蓝泉购买了几本图书？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[8149].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[8149].id" value="" id="answers[8149].id" />

	<select group="8149" class="selection" id="question_8149" name="answers[8149].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="5343" style=""  >0</option>
<option value="5344" style=""  >1</option>
<option value="5345" style=""  >2</option>
<option value="5346" style=""  >3</option>
<option value="5347" style=""  >4</option>
<option value="5348" style=""  >5</option>
<option value="5349" style=""  >6</option>
<option value="5350" style=""  >7</option>
<option value="5351" style=""  >8</option>
<option value="5352" style=""  >9</option>
<option value="5353" style=""  >10</option>
<option value="5354" style=""  >10+</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1549" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在此次活动中，您的朋友跟您提起过他们从蓝泉购买过几本图书？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[8150].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[8150].id" value="" id="answers[8150].id" />

	<select group="8150" class="selection" id="question_8150" name="answers[8150].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="5355" style=""  >0</option>
<option value="5356" style=""  >1</option>
<option value="5357" style=""  >2</option>
<option value="5358" style=""  >3</option>
<option value="5359" style=""  >4</option>
<option value="5360" style=""  >5</option>
<option value="5361" style=""  >6</option>
<option value="5362" style=""  >7</option>
<option value="5363" style=""  >8</option>
<option value="5364" style=""  >9</option>
<option value="5365" style=""  >10</option>
<option value="5366" style=""  >10+</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="Submit" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = 'Mandatory questions must be filled out';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = 'Can not submit empty questionnaire form';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[


	 Element.hide("q_1539");
	 Element.hide("q_1540");
	 Element.hide("q_1541");


var myrules = {
	   
	   "input#8136_0": function(el){
			el.onclick = function(){
				if ($("8136_0").checked){
						Element.show($("q_1539"));
						Element.hide($("q_1540"));
				}
			}
		}
	,
	   
	   "input#8139_0": function(el){
			el.onclick = function(){
				if ($("8139_0").checked){
						Element.show($("q_1541"));
				}
			}
		}
	,
	   
	   "input#8139_1": function(el){
			el.onclick = function(){
				if ($("8139_1").checked){
						Element.hide($("q_1541"));
				}
			}
		}
	,
	   
	   "input#8136_1": function(el){
			el.onclick = function(){
				if ($("8136_1").checked){
						Element.hide($("q_1539"));
						Element.show($("q_1540"));
				}
			}
		}
}

Behaviour.register(myrules);

Framework.registerAjaxSensors();
// ]]>
-->
</script>
