	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" style="background: #fff;width:100%;">
	<div id="container" style="background: #fff;">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<!-- <img src="/survey/logoImage/449" style="height:70px; width:301px" />-->
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" style="background:#fff;width:100%;">
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="loading();return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			$('mask').show();
		}
	}
// ]]>
-->
</script>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />
<input type="hidden" name="surveyId" value="Kc0xDgKvCELv"/>

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1846" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						In how many occasions did you mention PURELL, online or offline, during the last three months?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9632].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9632].id" value="" id="answers[9632].id" />

	<select group="9632" class="selection" id="question_9632" name="answers[9632].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="7249" style=""  >0</option>
<option value="7250" style=""  >1</option>
<option value="7251" style=""  >2</option>
<option value="7252" style=""  >3</option>
<option value="7253" style=""  >4</option>
<option value="7254" style=""  >5</option>
<option value="7255" style=""  >6</option>
<option value="7256" style=""  >7</option>
<option value="7257" style=""  >8</option>
<option value="7258" style=""  >9</option>
<option value="7259" style=""  >10</option>
<option value="7260" style=""  >11~15</option>
<option value="7261" style=""  >16~20</option>
<option value="7262" style=""  >20+</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1847" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						How many times did you post a comment about PURELL online (BBS/forum)?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9633].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9633].id" value="" id="answers[9633].id" />

	<select group="9633" class="selection" id="question_9633" name="answers[9633].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="7263" style=""  >0</option>
<option value="7264" style=""  >1</option>
<option value="7265" style=""  >2</option>
<option value="7266" style=""  >3</option>
<option value="7267" style=""  >4</option>
<option value="7268" style=""  >5</option>
<option value="7269" style=""  >6</option>
<option value="7270" style=""  >7</option>
<option value="7271" style=""  >8</option>
<option value="7272" style=""  >9</option>
<option value="7273" style=""  >10</option>
<option value="7274" style=""  >10+</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1848" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Did you make use of PURELL during the campaign?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9634].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9634].id" value="" id="answers[9634].id" />
<ul>
	<li>
			<input group="9634" type="radio" id="9634_0" name="answers[9634].value" value="7275"  class="selection question_radio_9634"  />		<label for="9634_0">Yes</label>
	</li>
	<li>
			<input group="9634" type="radio" id="9634_1" name="answers[9634].value" value="7276"  class="selection question_radio_9634"  />		<label for="9634_1">No</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_9634  qc_0 radio" type="radio" name="answers[9634].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1849" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Why not?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[9635].id" value="" id="answers[9635].id" />
<textarea name="answers[9635].value" id="question_9635" cols="40" group="9635" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[9635].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1850" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						How many coupons did you pass on to your friends?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9636].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9636].id" value="" id="answers[9636].id" />
<ul>
	<li>
			<input group="9636" type="radio" id="9636_0" name="answers[9636].value" value="7277"  class="selection question_radio_9636"  />		<label for="9636_0">0</label>
	</li>
	<li>
			<input group="9636" type="radio" id="9636_1" name="answers[9636].value" value="7278"  class="selection question_radio_9636"  />		<label for="9636_1">1~5</label>
	</li>
	<li>
			<input group="9636" type="radio" id="9636_2" name="answers[9636].value" value="7279"  class="selection question_radio_9636"  />		<label for="9636_2">6~10</label>
	</li>
	<li>
			<input group="9636" type="radio" id="9636_3" name="answers[9636].value" value="7280"  class="selection question_radio_9636"  />		<label for="9636_3">11~15</label>
	</li>
	<li>
			<input group="9636" type="radio" id="9636_4" name="answers[9636].value" value="7281"  class="selection question_radio_9636"  />		<label for="9636_4">16~20</label>
	</li>
	<li>
			<input group="9636" type="radio" id="9636_5" name="answers[9636].value" value="7282"  class="selection question_radio_9636"  />		<label for="9636_5">21~24</label>
	</li>
	<li>
			<input group="9636" type="radio" id="9636_6" name="answers[9636].value" value="7283"  class="selection question_radio_9636"  />		<label for="9636_6">25</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_9636  qc_0 radio" type="radio" name="answers[9636].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1865" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=100% valign="top">
					<div class="question-title">
						How likely is it that you would recommend PURELL to a friend or colleague?
					</div>
							<div class="elementInfoText " >
							   
							</div>
				</td>
			</tr>
			 <tr>
				<td width=100% valign="top" class="question-td twoColumnLayout" style="padding-left:15px;">
<span class="error-content" id="err_answers[9639].value" ></span>
<input type="hidden" name="answers[9639].id" value="" id="answers[9639].id" />
<table>
<tr>

<td>

<div class="left-label">Not at all likely</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[9639].value" value="0" id="9639_0" group="9639" class="question_radio_9639 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9639].value" value="1" id="9639_1" group="9639" class="question_radio_9639 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9639].value" value="2" id="9639_2" group="9639" class="question_radio_9639 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9639].value" value="3" id="9639_3" group="9639" class="question_radio_9639 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9639].value" value="4" id="9639_4" group="9639" class="question_radio_9639 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9639].value" value="5" id="9639_5" group="9639" class="question_radio_9639 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9639].value" value="6" id="9639_6" group="9639" class="question_radio_9639 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9639].value" value="7" id="9639_7" group="9639" class="question_radio_9639 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9639].value" value="8" id="9639_8" group="9639" class="question_radio_9639 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9639].value" value="9" id="9639_9" group="9639" class="question_radio_9639 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[9639].value" value="10" id="9639_10" group="9639" class="question_radio_9639 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">Extremely likely</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[9639].value" value="" id="answers[9639].value" class="q_9639 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1793" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Why?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[9640].id" value="" id="answers[9640].id" />
<input type="text" name="answers[9640].value" value="" id="question_9640" group="9640" class="input-text" />

<span class="error-content" id="err_answers[9640].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1854" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						How often do you use PURELL?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9641].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9641].id" value="" id="answers[9641].id" />
<ul>
	<li>
			<input group="9641" type="radio" id="9641_0" name="answers[9641].value" value="7286"  class="selection question_radio_9641"  />		<label for="9641_0">Rarely or never</label>
	</li>
	<li>
			<input group="9641" type="radio" id="9641_1" name="answers[9641].value" value="7287"  class="selection question_radio_9641"  />		<label for="9641_1">Once a month</label>
	</li>
	<li>
			<input group="9641" type="radio" id="9641_2" name="answers[9641].value" value="7288"  class="selection question_radio_9641"  />		<label for="9641_2">Twice or thrice a month</label>
	</li>
	<li>
			<input group="9641" type="radio" id="9641_3" name="answers[9641].value" value="7289"  class="selection question_radio_9641"  />		<label for="9641_3">Once or twice a week</label>
	</li>
	<li>
			<input group="9641" type="radio" id="9641_4" name="answers[9641].value" value="7290"  class="selection question_radio_9641"  />		<label for="9641_4">More than twice a week</label>
	</li>
	<li>
			<input group="9641" type="radio" id="9641_5" name="answers[9641].value" value="7291"  class="selection question_radio_9641"  />		<label for="9641_5">Everyday or almost everyday</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_9641  qc_0 radio" type="radio" name="answers[9641].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1856" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						What is your overall opinion of PURELL?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9642].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9642].id" value="" id="answers[9642].id" />
<ul>
	<li>
			<input group="9642" type="radio" id="9642_0" name="answers[9642].value" value="7297"  class="selection question_radio_9642"  />		<label for="9642_0">Very positive</label>
	</li>
	<li>
			<input group="9642" type="radio" id="9642_1" name="answers[9642].value" value="7298"  class="selection question_radio_9642"  />		<label for="9642_1">Somewhat positive</label>
	</li>
	<li>
			<input group="9642" type="radio" id="9642_2" name="answers[9642].value" value="7299"  class="selection question_radio_9642"  />		<label for="9642_2">Neutral</label>
	</li>
	<li>
			<input group="9642" type="radio" id="9642_3" name="answers[9642].value" value="7300"  class="selection question_radio_9642"  />		<label for="9642_3">Somewhat negative</label>
	</li>
	<li>
			<input group="9642" type="radio" id="9642_4" name="answers[9642].value" value="7301"  class="selection question_radio_9642"  />		<label for="9642_4">Negative</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_9642  qc_0 radio" type="radio" name="answers[9642].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1857" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						What is your overall opinion of the effectiveness of PURELL in sterilizing your hands?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9643].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9643].id" value="" id="answers[9643].id" />
<ul>
	<li>
			<input group="9643" type="radio" id="9643_0" name="answers[9643].value" value="7302"  class="selection question_radio_9643"  />		<label for="9643_0">Very effective</label>
	</li>
	<li>
			<input group="9643" type="radio" id="9643_1" name="answers[9643].value" value="7303"  class="selection question_radio_9643"  />		<label for="9643_1">Somewhat effective</label>
	</li>
	<li>
			<input group="9643" type="radio" id="9643_2" name="answers[9643].value" value="7304"  class="selection question_radio_9643"  />		<label for="9643_2">Neutral</label>
	</li>
	<li>
			<input group="9643" type="radio" id="9643_3" name="answers[9643].value" value="7305"  class="selection question_radio_9643"  />		<label for="9643_3">Somewhat ineffective</label>
	</li>
	<li>
			<input group="9643" type="radio" id="9643_4" name="answers[9643].value" value="7306"  class="selection question_radio_9643"  />		<label for="9643_4">Ineffective</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_9643  qc_0 radio" type="radio" name="answers[9643].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1858" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						What is your overall opinion of the price of PURELL?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9644].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9644].id" value="" id="answers[9644].id" />
<ul>
	<li>
			<input group="9644" type="radio" id="9644_0" name="answers[9644].value" value="7307"  class="selection question_radio_9644"  />		<label for="9644_0">What a fantastic price!</label>
	</li>
	<li>
			<input group="9644" type="radio" id="9644_1" name="answers[9644].value" value="7308"  class="selection question_radio_9644"  />		<label for="9644_1">It's a pretty good deal.</label>
	</li>
	<li>
			<input group="9644" type="radio" id="9644_2" name="answers[9644].value" value="7309"  class="selection question_radio_9644"  />		<label for="9644_2">Its reasonably priced.</label>
	</li>
	<li>
			<input group="9644" type="radio" id="9644_3" name="answers[9644].value" value="7310"  class="selection question_radio_9644"  />		<label for="9644_3">It's a bit too expensive.</label>
	</li>
	<li>
			<input group="9644" type="radio" id="9644_4" name="answers[9644].value" value="7311"  class="selection question_radio_9644"  />		<label for="9644_4">It's way too expensive!</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_9644  qc_0 radio" type="radio" name="answers[9644].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1859" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						What is your overall opinion of the Spark Kit's packaging?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9645].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9645].id" value="" id="answers[9645].id" />
<ul>
	<li>
			<input group="9645" type="radio" id="9645_0" name="answers[9645].value" value="7312"  class="selection question_radio_9645"  />		<label for="9645_0">Excellent</label>
	</li>
	<li>
			<input group="9645" type="radio" id="9645_1" name="answers[9645].value" value="7313"  class="selection question_radio_9645"  />		<label for="9645_1">Above average</label>
	</li>
	<li>
			<input group="9645" type="radio" id="9645_2" name="answers[9645].value" value="7314"  class="selection question_radio_9645"  />		<label for="9645_2">Average</label>
	</li>
	<li>
			<input group="9645" type="radio" id="9645_3" name="answers[9645].value" value="7315"  class="selection question_radio_9645"  />		<label for="9645_3">Below average</label>
	</li>
	<li>
			<input group="9645" type="radio" id="9645_4" name="answers[9645].value" value="7316"  class="selection question_radio_9645"  />		<label for="9645_4">Poor</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_9645  qc_0 radio" type="radio" name="answers[9645].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1860" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						How many times/items, if any, did you purchase PURELL during the past 3 months?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9646].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9646].id" value="" id="answers[9646].id" />

	<select group="9646" class="selection" id="question_9646" name="answers[9646].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="7317" style=""  >0</option>
<option value="7318" style=""  >1</option>
<option value="7319" style=""  >2</option>
<option value="7320" style=""  >3</option>
<option value="7321" style=""  >4</option>
<option value="7322" style=""  >5</option>
<option value="7323" style=""  >6</option>
<option value="7324" style=""  >7</option>
<option value="7325" style=""  >8</option>
<option value="7326" style=""  >9</option>
<option value="7327" style=""  >10</option>
<option value="7328" style=""  >11~20</option>
<option value="7329" style=""  >20+</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1861" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						If purchased, from where
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[9647].id" value="" id="answers[9647].id" />
<input type="text" name="answers[9647].value" value="" id="question_9647" group="9647" class="input-text" />

<span class="error-content" id="err_answers[9647].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1862" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=100% valign="top">
					<div class="question-title">
						What's the likelyhood that you will purchase PURELL in the future?
					</div>
							<div class="elementInfoText " >
							   
							</div>
				</td>
			</tr>
			 <tr>
				<td width=100% valign="top" class="question-td twoColumnLayout" style="padding-left:15px;">
<span class="error-content" id="err_answers[9648].value" ></span>
<input type="hidden" name="answers[9648].id" value="" id="answers[9648].id" />
<table>
<tr>

<td>

<div class="left-label">Not at all likely</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[9648].value" value="0" id="9648_0" group="9648" class="question_radio_9648 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9648].value" value="1" id="9648_1" group="9648" class="question_radio_9648 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9648].value" value="2" id="9648_2" group="9648" class="question_radio_9648 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9648].value" value="3" id="9648_3" group="9648" class="question_radio_9648 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9648].value" value="4" id="9648_4" group="9648" class="question_radio_9648 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9648].value" value="5" id="9648_5" group="9648" class="question_radio_9648 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9648].value" value="6" id="9648_6" group="9648" class="question_radio_9648 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9648].value" value="7" id="9648_7" group="9648" class="question_radio_9648 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9648].value" value="8" id="9648_8" group="9648" class="question_radio_9648 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9648].value" value="9" id="9648_9" group="9648" class="question_radio_9648 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[9648].value" value="10" id="9648_10" group="9648" class="question_radio_9648 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">Extremely likely</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[9648].value" value="" id="answers[9648].value" class="q_9648 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1851" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Did any of your friends purchase PURELL?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9637].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9637].id" value="" id="answers[9637].id" />
<ul>
	<li>
			<input group="9637" type="radio" id="9637_0" name="answers[9637].value" value="7284"  class="selection question_radio_9637"  />		<label for="9637_0">Yes</label>
	</li>
	<li>
			<input group="9637" type="radio" id="9637_1" name="answers[9637].value" value="7285"  class="selection question_radio_9637"  />		<label for="9637_1">No</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_9637  qc_0 radio" type="radio" name="answers[9637].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1852" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						From where?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[9638].id" value="" id="answers[9638].id" />
<input type="text" name="answers[9638].value" value="" id="question_9638" group="9638" class="input-text" />

<span class="error-content" id="err_answers[9638].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1863" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						What is, in your opinion, PURELL's main advantage versus other hand sanitation products?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[9649].id" value="" id="answers[9649].id" />
<textarea name="answers[9649].value" id="question_9649" cols="40" group="9649" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[9649].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1864" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Did you enjoy this campaign?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9650].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9650].id" value="" id="answers[9650].id" />
<ul>
	<li>
			<input group="9650" type="radio" id="9650_0" name="answers[9650].value" value="7330"  class="selection question_radio_9650"  />		<label for="9650_0">I was so excited!!</label>
	</li>
	<li>
			<input group="9650" type="radio" id="9650_1" name="answers[9650].value" value="7331"  class="selection question_radio_9650"  />		<label for="9650_1">It's a good campaign</label>
	</li>
	<li>
			<input group="9650" type="radio" id="9650_2" name="answers[9650].value" value="7332"  class="selection question_radio_9650"  />		<label for="9650_2">So so</label>
	</li>
	<li>
			<input group="9650" type="radio" id="9650_3" name="answers[9650].value" value="7333"  class="selection question_radio_9650"  />		<label for="9650_3">Not excited at all.</label>
	</li>
	<li>
			<input group="9650" type="radio" id="9650_4" name="answers[9650].value" value="7334"  class="selection question_radio_9650"  />		<label for="9650_4">I hate this campaign</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_9650  qc_0 radio" type="radio" name="answers[9650].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="Submit" />
</div>

</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = 'Mandatory questions must be filled out';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = 'Can not submit empty questionnaire form';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[




var myrules = {
	   
	   "input#9634_1": function(el){
			el.onclick = function(){
				if ($("9634_1").checked){
						Element.show($("q_1849"));
				}
			}
		}
	,
	   
	   "input#9636_4": function(el){
			el.onclick = function(){
				if ($("9636_4").checked){
						Element.show($("q_1851"));
						Element.show($("q_1852"));
				}
			}
		}
	,
	   
	   "input#9636_2": function(el){
			el.onclick = function(){
				if ($("9636_2").checked){
						Element.show($("q_1851"));
						Element.show($("q_1852"));
				}
			}
		}
	,
	   
	   "input#9636_0": function(el){
			el.onclick = function(){
				if ($("9636_0").checked){
						Element.hide($("q_1851"));
						Element.hide($("q_1852"));
				}
			}
		}
	,
	   
	   "input#9636_6": function(el){
			el.onclick = function(){
				if ($("9636_6").checked){
						Element.show($("q_1851"));
						Element.show($("q_1852"));
				}
			}
		}
	,
	   
	   "input#9637_1": function(el){
			el.onclick = function(){
				if ($("9637_1").checked){
						Element.hide($("q_1852"));
				}
			}
		}
	,
	   
	   "input#9636_3": function(el){
			el.onclick = function(){
				if ($("9636_3").checked){
						Element.show($("q_1851"));
						Element.show($("q_1852"));
				}
			}
		}
	,
	   
	   "input#9636_5": function(el){
			el.onclick = function(){
				if ($("9636_5").checked){
						Element.show($("q_1851"));
						Element.show($("q_1852"));
				}
			}
		}
	,
	   
	   "input#9637_0": function(el){
			el.onclick = function(){
				if ($("9637_0").checked){
						Element.show($("q_1852"));
				}
			}
		}
	,
	   
	   "input#9634_0": function(el){
			el.onclick = function(){
				if ($("9634_0").checked){
						Element.hide($("q_1849"));
				}
			}
		}
	,
	   
	   "input#9636_1": function(el){
			el.onclick = function(){
				if ($("9636_1").checked){
						Element.show($("q_1851"));
						Element.show($("q_1852"));
				}
			}
		}
}

Behaviour.register(myrules);

// ]]>
-->
</script>
