	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/460" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="loading();return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="D1BBUGyNhw2e" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1905" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						我们送给您的礼包中有4个馅饼饼是为您的朋友们准备的，请问您和几个家人以外的朋友分享了馅饼呢？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9866].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9866].id" value="" id="answers[9866].id" />

	<select group="9866" class="selection" id="question_9866" name="answers[9866].value" title="title"  size = "1" onchange="showOtherValueInputInSelect(this)">
	<option selected="selected" value="0">Please choose</option>
<option value="7447" style=""  >0</option>
<option value="7448" style=""  >1</option>
<option value="7449" style=""  >2</option>
<option value="7450" style=""  >3</option>
<option value="7451" style=""  >4</option>
		<option id="9866_other" value="0"  >Other</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>
<tr>
	<td><input id="question_9866_other" style="display:none;" type="text" name="answers[9866].otherValue" value=""/></td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1906" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问您在过去三个月的活动过程中跟身边的人提起过几次优冠馅饼？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9867].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9867].id" value="" id="answers[9867].id" />

	<select group="9867" class="selection" id="question_9867" name="answers[9867].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="7452" style=""  >0</option>
<option value="7453" style=""  >1</option>
<option value="7454" style=""  >2</option>
<option value="7455" style=""  >3</option>
<option value="7456" style=""  >4</option>
<option value="7457" style=""  >5</option>
<option value="7458" style=""  >6</option>
<option value="7459" style=""  >7</option>
<option value="7460" style=""  >8</option>
<option value="7461" style=""  >9</option>
<option value="7462" style=""  >10</option>
<option value="7463" style=""  >11~15</option>
<option value="7464" style=""  >16~20</option>
<option value="7465" style=""  >20+</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1907" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您最常用的和朋友交流的方式是：
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9868].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9868].id" value="" id="answers[9868].id" />
<ul>
	<li>
			<input group="9868" type="radio" id="9868_0" name="answers[9868].value" value="7466"  class="selection question_radio_9868" onclick="showOtherValueInputInRadio(this)" />		<label for="9868_0">电话</label>
	</li>
	<li>
			<input group="9868" type="radio" id="9868_1" name="answers[9868].value" value="7467"  class="selection question_radio_9868" onclick="showOtherValueInputInRadio(this)" />		<label for="9868_1">QQ</label>
	</li>
	<li>
			<input group="9868" type="radio" id="9868_2" name="answers[9868].value" value="7468"  class="selection question_radio_9868" onclick="showOtherValueInputInRadio(this)" />		<label for="9868_2">MSN</label>
	</li>
	<li>
			<input group="9868" type="radio" id="9868_3" name="answers[9868].value" value="7469"  class="selection question_radio_9868" onclick="showOtherValueInputInRadio(this)" />		<label for="9868_3">电子邮件</label>
	</li>
	<li>
			<input group="9868" type="radio" id="9868_4" name="answers[9868].value" value="7470"  class="selection question_radio_9868" onclick="showOtherValueInputInRadio(this)" />		<label for="9868_4">面对面</label>
	</li>
		<li>
			<input type="radio" id="9868_other" name="answers[9868].value" value="0" class="question_radio_9868" onclick="showOtherValueInputInRadio(this)" />			<label for="9868_other">Other</label>
			<input id="9868_other_input" type="text" name="answers[9868].otherValue" value=""  style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_9868  qc_0 radio" type="radio" name="answers[9868].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1908" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您最常在哪里和您的朋友们聊起优冠馅饼：（请选择一个最常见场合）
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9869].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9869].id" value="" id="answers[9869].id" />
<ul>
	<li>
			<input group="9869" type="radio" id="9869_0" name="answers[9869].value" value="7471"  class="selection question_radio_9869" onclick="showOtherValueInputInRadio(this)" />		<label for="9869_0">家里</label>
	</li>
	<li>
			<input group="9869" type="radio" id="9869_1" name="answers[9869].value" value="7472"  class="selection question_radio_9869" onclick="showOtherValueInputInRadio(this)" />		<label for="9869_1">学校</label>
	</li>
	<li>
			<input group="9869" type="radio" id="9869_2" name="answers[9869].value" value="7473"  class="selection question_radio_9869" onclick="showOtherValueInputInRadio(this)" />		<label for="9869_2">办公室</label>
	</li>
	<li>
			<input group="9869" type="radio" id="9869_3" name="answers[9869].value" value="7474"  class="selection question_radio_9869" onclick="showOtherValueInputInRadio(this)" />		<label for="9869_3">购物商场或超市</label>
	</li>
	<li>
			<input group="9869" type="radio" id="9869_4" name="answers[9869].value" value="7475"  class="selection question_radio_9869" onclick="showOtherValueInputInRadio(this)" />		<label for="9869_4">朋友聚会</label>
	</li>
	<li>
			<input group="9869" type="radio" id="9869_5" name="answers[9869].value" value="7476"  class="selection question_radio_9869" onclick="showOtherValueInputInRadio(this)" />		<label for="9869_5">户外</label>
	</li>
	<li>
			<input group="9869" type="radio" id="9869_6" name="answers[9869].value" value="7477"  class="selection question_radio_9869" onclick="showOtherValueInputInRadio(this)" />		<label for="9869_6">网络</label>
	</li>
		<li>
			<input type="radio" id="9869_other" name="answers[9869].value" value="0" class="question_radio_9869" onclick="showOtherValueInputInRadio(this)" />			<label for="9869_other">Other</label>
			<input id="9869_other_input" type="text" name="answers[9869].otherValue" value=""  style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_9869  qc_0 radio" type="radio" name="answers[9869].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1909" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=100% valign="top">
					<div class="question-title">
						您有多大可能性把优冠馅饼推荐给身边人？
					</div>
							<div class="elementInfoText " >
							   
							</div>
				</td>
			</tr>
			 <tr>
				<td width=100% valign="top" class="question-td twoColumnLayout" style="padding-left:15px;">
<span class="error-content" id="err_answers[9870].value" ></span>
<input type="hidden" name="answers[9870].id" value="" id="answers[9870].id" />
<table>
<tr>

<td>

<div class="left-label">肯定不会</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[9870].value" value="0" id="9870_0" group="9870" class="question_radio_9870 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9870].value" value="1" id="9870_1" group="9870" class="question_radio_9870 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9870].value" value="2" id="9870_2" group="9870" class="question_radio_9870 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9870].value" value="3" id="9870_3" group="9870" class="question_radio_9870 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9870].value" value="4" id="9870_4" group="9870" class="question_radio_9870 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9870].value" value="5" id="9870_5" group="9870" class="question_radio_9870 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9870].value" value="6" id="9870_6" group="9870" class="question_radio_9870 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9870].value" value="7" id="9870_7" group="9870" class="question_radio_9870 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9870].value" value="8" id="9870_8" group="9870" class="question_radio_9870 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[9870].value" value="9" id="9870_9" group="9870" class="question_radio_9870 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[9870].value" value="10" id="9870_10" group="9870" class="question_radio_9870 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">肯定会</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[9870].value" value="" id="answers[9870].value" class="q_9870 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1910" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						本次优冠馅饼的主题是“你是我的太阳”，您觉得本次活动给您的感受如何呢？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[9871].id" value="" id="answers[9871].id" />
<textarea name="answers[9871].value" id="question_9871" cols="40" group="9871" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[9871].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1911" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						过去三个月中，您购买过优冠馅饼几次？（请给出确切数字）
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9872].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9872].id" value="" id="answers[9872].id" />

	<select group="9872" class="selection" id="question_9872" name="answers[9872].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="7478" style=""  >0</option>
<option value="7479" style=""  >1</option>
<option value="7480" style=""  >2</option>
<option value="7481" style=""  >3</option>
<option value="7482" style=""  >4</option>
<option value="7483" style=""  >5</option>
<option value="7484" style=""  >6</option>
<option value="7485" style=""  >7</option>
<option value="7486" style=""  >8</option>
<option value="7487" style=""  >9</option>
<option value="7488" style=""  >10</option>
<option value="7489" style=""  >11~20</option>
<option value="7490" style=""  >20+</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1912" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						据您了解，过去三个月中，您有几个朋友曾经购买过优冠馅饼？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9873].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9873].id" value="" id="answers[9873].id" />

	<select group="9873" class="selection" id="question_9873" name="answers[9873].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="7491" style=""  >0</option>
<option value="7492" style=""  >1</option>
<option value="7493" style=""  >2</option>
<option value="7494" style=""  >3</option>
<option value="7495" style=""  >4</option>
<option value="7496" style=""  >5</option>
<option value="7497" style=""  >6</option>
<option value="7498" style=""  >7</option>
<option value="7499" style=""  >8</option>
<option value="7500" style=""  >9</option>
<option value="7501" style=""  >10</option>
<option value="7502" style=""  >11~20</option>
<option value="7503" style=""  >20+</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1913" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您今后会经常购买优冠馅饼吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9874].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9874].id" value="" id="answers[9874].id" />
<ul>
	<li>
			<input group="9874" type="radio" id="9874_0" name="answers[9874].value" value="7504"  class="selection question_radio_9874"  />		<label for="9874_0">肯定会</label>
	</li>
	<li>
			<input group="9874" type="radio" id="9874_1" name="answers[9874].value" value="7505"  class="selection question_radio_9874"  />		<label for="9874_1">可能会</label>
	</li>
	<li>
			<input group="9874" type="radio" id="9874_2" name="answers[9874].value" value="7506"  class="selection question_radio_9874"  />		<label for="9874_2">不会</label>
	</li>
	<li>
			<input group="9874" type="radio" id="9874_3" name="answers[9874].value" value="7507"  class="selection question_radio_9874"  />		<label for="9874_3">可能不会</label>
	</li>
	<li>
			<input group="9874" type="radio" id="9874_4" name="answers[9874].value" value="7508"  class="selection question_radio_9874"  />		<label for="9874_4">肯定不会</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_9874  qc_0 radio" type="radio" name="answers[9874].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1914" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的孩子通常在哪里吃优冠馅饼？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9875].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9875].id" value="" id="answers[9875].id" />
<ul>
	<li>
			<input group="9875" type="radio" id="9875_0" name="answers[9875].value" value="7509"  class="selection question_radio_9875" onclick="showOtherValueInputInRadio(this)" />		<label for="9875_0">家里</label>
	</li>
	<li>
			<input group="9875" type="radio" id="9875_1" name="answers[9875].value" value="7510"  class="selection question_radio_9875" onclick="showOtherValueInputInRadio(this)" />		<label for="9875_1">上学放学</label>
	</li>
	<li>
			<input group="9875" type="radio" id="9875_2" name="answers[9875].value" value="7511"  class="selection question_radio_9875" onclick="showOtherValueInputInRadio(this)" />		<label for="9875_2">少年宫</label>
	</li>
	<li>
			<input group="9875" type="radio" id="9875_3" name="answers[9875].value" value="7512"  class="selection question_radio_9875" onclick="showOtherValueInputInRadio(this)" />		<label for="9875_3">户外</label>
	</li>
		<li>
			<input type="radio" id="9875_other" name="answers[9875].value" value="0" class="question_radio_9875" onclick="showOtherValueInputInRadio(this)" />			<label for="9875_other">Other</label>
			<input id="9875_other_input" type="text" name="answers[9875].otherValue" value=""  style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_9875  qc_0 radio" type="radio" name="answers[9875].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1915" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您的孩子通常在哪个时间吃优冠馅饼？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9876].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9876].id" value="" id="answers[9876].id" />
<ul>
	<li>
			<input group="9876" type="radio" id="9876_0" name="answers[9876].value" value="7513"  class="selection question_radio_9876"  />		<label for="9876_0">早餐吃</label>
	</li>
	<li>
			<input group="9876" type="radio" id="9876_1" name="answers[9876].value" value="7514"  class="selection question_radio_9876"  />		<label for="9876_1">上午当点心吃</label>
	</li>
	<li>
			<input group="9876" type="radio" id="9876_2" name="answers[9876].value" value="7515"  class="selection question_radio_9876"  />		<label for="9876_2">下午当担心吃</label>
	</li>
	<li>
			<input group="9876" type="radio" id="9876_3" name="answers[9876].value" value="7516"  class="selection question_radio_9876"  />		<label for="9876_3">晚上吃</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_9876  qc_0 radio" type="radio" name="answers[9876].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1916" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您购买优冠馅饼通常是为了
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9877].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9877].id" value="" id="answers[9877].id" />




<span id="hint_9877">
</span>
<ul>
	<li>
			<input group="9877" class="question_radio_9877 selection" type="checkbox" id="9877_0" name="answers[9877].value" value="7517" 	onclick=" "/>		<label for="9877_0">营养</label>
	</li>
	<li>
			<input group="9877" class="question_radio_9877 selection" type="checkbox" id="9877_1" name="answers[9877].value" value="7518" 	onclick=" "/>		<label for="9877_1">美味</label>
	</li>
	<li>
			<input group="9877" class="question_radio_9877 selection" type="checkbox" id="9877_2" name="answers[9877].value" value="7519" 	onclick=" "/>		<label for="9877_2">方便</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_1917" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您觉得优冠馅饼的价位如何？（2个饼包装的6块9，4个饼包装的12块6）
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[9878].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[9878].id" value="" id="answers[9878].id" />
<ul>
	<li>
			<input group="9878" type="radio" id="9878_0" name="answers[9878].value" value="7520"  class="selection question_radio_9878"  />		<label for="9878_0">偏贵</label>
	</li>
	<li>
			<input group="9878" type="radio" id="9878_1" name="answers[9878].value" value="7521"  class="selection question_radio_9878"  />		<label for="9878_1">可以接受</label>
	</li>
	<li>
			<input group="9878" type="radio" id="9878_2" name="answers[9878].value" value="7522"  class="selection question_radio_9878"  />		<label for="9878_2">便宜</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_9878  qc_0 radio" type="radio" name="answers[9878].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="Submit" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = 'Mandatory questions must be filled out';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = 'Can not submit empty questionnaire form';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

Framework.registerAjaxSensors();
// ]]>
-->
</script>
