<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<META NAME="ROBOTS" CONTENT="NOINDEX,NOFOLLOW">
	<title>Indicate - Fill out survey</title>
	<link href="/css/crystal.css" rel="stylesheet" type="text/css" media="screen, print" />
	<!--[if IE]>
	<link href="/css/crystal-ie.css" rel="stylesheet" type="text/css" media="screen" />
	<![endif]-->
	<link href="/css/fillout_default.css" rel="stylesheet" type="text/css" media="screen" />
	<!--[if IE]>
	<link href="/css/fillout_default-ie.css" rel="stylesheet" type="text/css" media="screen" />
	<![endif]-->
	<link href="/css/niftyCorners.css" rel="stylesheet" type="text/css" media="screen" />
	<script src="/js/all.js" language="JavaScript" type="text/javascript"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/uploadify/jquery.uploadify.v2.1.4.min.js"></script>
	<script src="http://malsup.github.com/jquery.form.js"></script>
	<script language="JavaScript" type="text/javascript">


	jQuery(document).ready(function() {
	  jQuery('#file_upload').uploadify({
	    'uploader'  : '<?php echo $this->baseUrl();?>/uploadify/uploadify.swf',
	    'script'    : '<?php echo $this->baseUrl();?>/uploadify/uploadify.php?param=<?php echo $this->reportId;?>_<?php echo $this->consumer;?>',
	    'cancelImg' : '<?php echo $this->baseUrl();?>/images/cancel.png',
	    'folder'    : '<?php echo $this->baseUrl();?>/uploads',
	    'auto'           : true,
	    'fileExt'        : '*.jpg;*.gif;*.png',
	    'fileDesc'       : 'Image Files (.JPG, .GIF, .PNG)',
	    'queueID'        : 'custom-queue',
	    'queueSizeLimit' : 3,
	    'simUploadLimit' : 3,
	    'removeCompleted': false,
	    'multi'          : true,
	    'sizeLimit'      : 10240000,  //10MB
	    'onAllComplete'  : function(event,data) {
		    //jQuery('#status-message').text(data.filesUploaded + ' 文件上传成功, ' + data.errors + ' 错误.');
	      }

	  });
	});


	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>


</head>

<body>
<div class="main-container-outer">
	<div id="container">
		<!-- <div id="header" class="header">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.wildfire.asia" target="_blank">
					<img src="/survey/logoImage/47" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> --> <!-- header -->
		<div id="nav" class="navigation">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content">
 		

<div id="content">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://i2.wildfire.asia/fillout" onsubmit="loading();return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">
<div class="questionnaire-title">Quality for Life Report</div>

<div class="survey-intro"></div>
<br/>

<input type="hidden" name="id" value="ZJYs5uCxbDZ6" id="id" />
<input type="hidden" name="theme" value="default" id="theme" />

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_188" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Do you want to type your report or upload a photo?
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[1278].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[1278].id" value="" id="answers[1278].id" />
<ul>
	<li>
			<input group="1278" type="radio" id="1278_0" name="answers[1278].value" value="470"  class="selection question_radio_1278" onclick="showOrHide(this.id)"  />		<label for="1278_0">I want to type my conversation report</label>
	</li>
	<li>
			<input group="1278" type="radio" id="1278_1" name="answers[1278].value" value="471"  class="selection question_radio_1278" onclick="showOrHide(this.id)"  />		<label for="1278_1">I want to upload a screenshot/photo of my conversation report</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_1278  qc_0 radio" type="radio" name="answers[1278].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
function showOrHide(val){
	if(val=="1278_0"){
		jQuery("#question_statement").css("display","block");
		jQuery("#upload_statement").css("display","none");
		jQuery("#submit").css("display","block");
		jQuery("#submit_two").css("display","none");
	}else{
		jQuery("#question_statement").css("display","none");
		jQuery("#upload_statement").css("display","block");
		jQuery("#submit").css("display","none");
		jQuery("#submit_two").css("display","block");
	}
}
</script>
<!-- ====================================================== -->
<div id = "question_statement" style="display:none">


		  <div id="q_68" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		

		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						How did you communicate with your friends?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[1279].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[1279].id" value="" id="answers[1279].id" />

	<select group="1279" class="selection" id="question_1279" name="answers[1279].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="195" style=""  >face-to-face</option>
<option value="196" style=""  >Web (Forum, social media, blog)</option>
<option value="197" style=""  >Telephone or SMS</option>
<option value="198" style=""  >Instant Messenger Service</option>
<option value="199" style=""  >Other</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_69" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Other way
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[1280].id" value="" id="answers[1280].id" />
<input type="text" name="answers[1280].value" value="" id="question_1280" group="1280" class="input-text" />

<span class="error-content" id="err_answers[1280].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_70" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						How many people have you been talking with this time?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[1281].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[1281].id" value="" id="answers[1281].id" />

	<select group="1281" class="selection" id="question_1281" name="answers[1281].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="200" style=""  >0</option>
<option value="201" style=""  >1</option>
<option value="202" style=""  >2</option>
<option value="203" style=""  >3</option>
<option value="204" style=""  >4</option>
<option value="205" style=""  >5</option>
<option value="206" style=""  >6</option>
<option value="207" style=""  >7</option>
<option value="208" style=""  >8</option>
<option value="209" style=""  >9</option>
<option value="210" style=""  >10</option>
<option value="211" style=""  >11-15</option>
<option value="212" style=""  >16-20</option>
<option value="213" style=""  >21-25</option>
<option value="214" style=""  >26-50</option>
<option value="215" style=""  >51~100</option>
<option value="216" style=""  >more than 100</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_71" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Among these people, with how many did you talk about the product?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[1282].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[1282].id" value="" id="answers[1282].id" />

	<select group="1282" class="selection" id="question_1282" name="answers[1282].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="217" style=""  >0</option>
<option value="218" style=""  >1</option>
<option value="219" style=""  >2</option>
<option value="220" style=""  >3</option>
<option value="221" style=""  >4</option>
<option value="222" style=""  >5</option>
<option value="223" style=""  >6</option>
<option value="224" style=""  >7</option>
<option value="225" style=""  >8</option>
<option value="226" style=""  >9</option>
<option value="227" style=""  >more than 9</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_72" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Among these people, how many people have heard about the product before?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[1283].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[1283].id" value="" id="answers[1283].id" />

	<select group="1283" class="selection" id="question_1283" name="answers[1283].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="228" style=""  >0</option>
<option value="229" style=""  >1</option>
<option value="230" style=""  >2</option>
<option value="231" style=""  >3</option>
<option value="232" style=""  >4</option>
<option value="233" style=""  >5</option>
<option value="234" style=""  >6</option>
<option value="235" style=""  >7</option>
<option value="236" style=""  >8</option>
<option value="237" style=""  >9</option>
<option value="238" style=""  >10</option>
<option value="239" style=""  >11-15</option>
<option value="240" style=""  >16-20</option>
<option value="241" style=""  >21-25</option>
<option value="242" style=""  >26-50</option>
<option value="243" style=""  >51-100</option>
<option value="244" style=""  >more than 100</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_73" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						What was the overall reaction?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[1284].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[1284].id" value="" id="answers[1284].id" />

	<select group="1284" class="selection" id="question_1284" name="answers[1284].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="245" style=""  >No Comments</option>
<option value="246" style=""  >1 point（completely not interested）</option>
<option value="247" style=""  >2 points</option>
<option value="248" style=""  >3points（slightly interested）</option>
<option value="249" style=""  >4 points</option>
<option value="250" style=""  >5 points（interested）</option>
<option value="251" style=""  >6 points</option>
<option value="252" style=""  >7 points（very interested）</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_74" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						How long did the conversation last?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[1285].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[1285].id" value="" id="answers[1285].id" />

	<select group="1285" class="selection" id="question_1285" name="answers[1285].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="253" style=""  >Less than 1 minute</option>
<option value="254" style=""  >1-2 minutes</option>
<option value="255" style=""  >3-4 minutes</option>
<option value="256" style=""  >5-9 minutes</option>
<option value="257" style=""  >10-14 minutes</option>
<option value="258" style=""  >15-19 minutes</option>
<option value="259" style=""  >20-30 minutes</option>
<option value="260" style=""  >more than 30 minutes</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_76" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						If you have talked with friends on the internet, please leave the URL:
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[1286].id" value="" id="answers[1286].id" />
<textarea name="answers[1286].value" id="question_1286" cols="40" group="1286" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[1286].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_77" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Your conversation contents (or chatting records)<a href='http://home.xingxinghuo.com/public/training/samplereport' target='_blank'>(please check the example report)</a>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[1287].id" value="" id="answers[1287].id" />
<textarea name="answers[1287].value" id="question_1287" cols="40" group="1287" rows="12" class="input-text" ></textarea>
<span class="error-content" id="err_answers[1287].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_78" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Does each person whom you've talked with know that you are a member of Wildfire Community?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[1288].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[1288].id" value="" id="answers[1288].id" />

	<select group="1288" class="selection" id="question_1288" name="answers[1288].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="261" style=""  >Yes, I'm certain that I claimed that I am a Wildfire Community member</option>
<option value="262" style=""  >No, I didn't claim that I am a Wildfire Community member</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_79" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Can we please share this report with other Wildfire Community members?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[1289].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[1289].id" value="" id="answers[1289].id" />
<ul>
	<li>
			<input group="1289" type="radio" id="1289_0" name="answers[1289].value" value="263"  class="selection question_radio_1289"  />		<label for="1289_0">yes</label>
	</li>
	<li>
			<input group="1289" type="radio" id="1289_1" name="answers[1289].value" value="264"  class="selection question_radio_1289"  />		<label for="1289_1">no</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_1289  qc_0 radio" type="radio" name="answers[1289].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_80" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Please fill out the exact number whom you've talked with
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[1290].id" value="" id="answers[1290].id" />
<input type="text" name="answers[1290].value" value="" id="question_1290" group="1290" class="input-text" />

<span class="error-content" id="err_answers[1290].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_81" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						When did the conversation take place?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[1291].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[1291].id" value="" id="answers[1291].id" />

	<select group="1291" class="selection" id="question_1291" name="answers[1291].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="265" style=""  >Today</option>
<option value="266" style=""  >Yesterday</option>
<option value="267" style=""  >The day before yesterday</option>
<option value="268" style=""  >Last week</option>
<option value="269" style=""  >When I received the gift</option>
<option value="270" style=""  >When I was invited</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 


</div>

</div>

<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<!-- <input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' /> -->
<input id="submit" type="submit"  class="button" style="display:none" name="command.submit" value="Submit" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://i2.wildfire.asia/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://i2.wildfire.asia/images/web_dialog_m_t.gif"><img src="http://i2.wildfire.asia/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://i2.wildfire.asia/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://i2.wildfire.asia/images/web_dialog_l_m.gif"><img src="http://i2.wildfire.asia/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://i2.wildfire.asia/images/web_dialog_r_m.gif"><img src="http://i2.wildfire.asia/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://i2.wildfire.asia/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://i2.wildfire.asia/images/web_dialog_m_b.gif"><img src="http://i2.wildfire.asia/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://i2.wildfire.asia/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
<div id = "upload_statement" style="display:none;">
		<!-- <p><?php echo $this->translate('Choose_file')?></p> -->
                <form  id="uploadImage" action="report/thankyou" method="post" enctype="multipart/form-data">
                    <table>
                        <tr>
                            <td><input id="image" type="file" name="image"></td>
                            <td style="color:red;font-size:10px">&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->translate('Upload_hint');?></td>
                        </tr>
                        <tr>
                            <td><input type="button" value="Submit" id="submit_photo" name="submit"></td>
                        <tr>
                    </table>
                </form>
                
<!--                 <h3><?php echo $this->translate('Successful_upload')?></h3>
                <h3><?php echo $this->translate('Unsuccessful_upload');?></h3> -->

                <!-- <div class="buttons-bar" style="padding-top: 10px;">
			<a class="big-button-blue" target="_parent"  href="<?php echo $this->url(array('controller'=>'home','action'=>'index'));?>">
                            <?php echo $this->translate('Take_Me_Home')?>
                        </a> -->
</div>
</div> 
<div class="fillout-submit">
<input id="submit_two" type="button"  class="button" style="display:none;margin-left: 130px;" name="command.submit" value="Submit" />
</div>
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
jQuery(function(){
	jQuery("#submit_photo").bind("click",function(){
		jQuery('#uploadImage').ajaxSubmit(function() { 
                alert("Thank you for your comment!"); 
            });
	});
});
jQuery(function(){
	jQuery("#submit_two").bind("click",function(){
		jQuery("#submit").submit;
	})

});
<!--
// <![CDATA[
 /* var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }*/
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://i2.wildfire.asia/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '<span style="color:red">*&nbsp;&nbsp;</span>Mandatory questions must be filled out';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '<span style="color:red">*&nbsp;&nbsp;</span>Can not submit empty questionnaire form';
			jQuery("#check-alert-dialog .content").html(html);
		    jQuery("#check-alert-dialog").dialog('open');
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<!-- <div class="footer">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div> -->
	<div class="bottom-shadow"></div>
	<div style="clear: both"></div>
	
</div> 
</body>
</html>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

Framework.registerAjaxSensors();
// ]]>
-->
</script>
