

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>
	无标题页
</title></head>
<body>
    <form name="form1" method="post" action="dns.aspx?404%3bhttp%3a%2f%2fq.xingxinghuo.cn%2fc%2fyTwD2XbKepDC%2ftheme%2fwildfire" id="form1">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUJNzgzNDMwNTMzZGQE7uw30aPU2ZHxFzzMkZtlWBczFw==" />

    <div>
    
    </div>
    </form>
</body>
</html>
