	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/508" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2023" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						过去2年来，您用过多少个不同品牌的洗发护发产品？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[10634].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[10634].id" value="" id="answers[10634].id" />
<ul>
	<li>
			<input group="10634" type="radio" id="10634_0" name="answers[10634].value" value="7817"  class="selection question_radio_10634"  />		<label for="10634_0">1</label>
	</li>
	<li>
			<input group="10634" type="radio" id="10634_1" name="answers[10634].value" value="7818"  class="selection question_radio_10634"  />		<label for="10634_1">2~3</label>
	</li>
	<li>
			<input group="10634" type="radio" id="10634_2" name="answers[10634].value" value="7819"  class="selection question_radio_10634"  />		<label for="10634_2">3~5</label>
	</li>
	<li>
			<input group="10634" type="radio" id="10634_3" name="answers[10634].value" value="7820"  class="selection question_radio_10634"  />		<label for="10634_3">5~10</label>
	</li>
	<li>
			<input group="10634" type="radio" id="10634_4" name="answers[10634].value" value="7821"  class="selection question_radio_10634"  />		<label for="10634_4">&gt;10</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_10634  qc_0 radio" type="radio" name="answers[10634].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2024" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您每天花多长时间化妆，护肤或打理头发？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[10635].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[10635].id" value="" id="answers[10635].id" />
<ul>
	<li>
			<input group="10635" type="radio" id="10635_0" name="answers[10635].value" value="7822"  class="selection question_radio_10635"  />		<label for="10635_0">0-5 分钟</label>
	</li>
	<li>
			<input group="10635" type="radio" id="10635_1" name="answers[10635].value" value="7823"  class="selection question_radio_10635"  />		<label for="10635_1">5-10 分钟</label>
	</li>
	<li>
			<input group="10635" type="radio" id="10635_2" name="answers[10635].value" value="7824"  class="selection question_radio_10635"  />		<label for="10635_2">10-20 分钟</label>
	</li>
	<li>
			<input group="10635" type="radio" id="10635_3" name="answers[10635].value" value="7825"  class="selection question_radio_10635"  />		<label for="10635_3">20-40 分钟</label>
	</li>
	<li>
			<input group="10635" type="radio" id="10635_4" name="answers[10635].value" value="7826"  class="selection question_radio_10635"  />		<label for="10635_4">&gt; 40 分钟</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_10635  qc_0 radio" type="radio" name="answers[10635].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2025" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您多久和朋友一起去一次美容美发场所？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[10636].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[10636].id" value="" id="answers[10636].id" />
<ul>
	<li>
			<input group="10636" type="radio" id="10636_0" name="answers[10636].value" value="7827"  class="selection question_radio_10636"  />		<label for="10636_0">从不</label>
	</li>
	<li>
			<input group="10636" type="radio" id="10636_1" name="answers[10636].value" value="7828"  class="selection question_radio_10636"  />		<label for="10636_1">一年3-4次</label>
	</li>
	<li>
			<input group="10636" type="radio" id="10636_2" name="answers[10636].value" value="7829"  class="selection question_radio_10636"  />		<label for="10636_2">每两个月去一次</label>
	</li>
	<li>
			<input group="10636" type="radio" id="10636_3" name="answers[10636].value" value="7830"  class="selection question_radio_10636"  />		<label for="10636_3">每月一次</label>
	</li>
	<li>
			<input group="10636" type="radio" id="10636_4" name="answers[10636].value" value="7831"  class="selection question_radio_10636"  />		<label for="10636_4">每月多次</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_10636  qc_0 radio" type="radio" name="answers[10636].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2026" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您平均每月在时尚用品、化妆品、护肤品花费多少？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[10637].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[10637].id" value="" id="answers[10637].id" />
<ul>
	<li>
			<input group="10637" type="radio" id="10637_0" name="answers[10637].value" value="7832"  class="selection question_radio_10637"  />		<label for="10637_0">&lt;500</label>
	</li>
	<li>
			<input group="10637" type="radio" id="10637_1" name="answers[10637].value" value="7833"  class="selection question_radio_10637"  />		<label for="10637_1">500-1000</label>
	</li>
	<li>
			<input group="10637" type="radio" id="10637_2" name="answers[10637].value" value="7834"  class="selection question_radio_10637"  />		<label for="10637_2">1000-1500</label>
	</li>
	<li>
			<input group="10637" type="radio" id="10637_3" name="answers[10637].value" value="7835"  class="selection question_radio_10637"  />		<label for="10637_3">1500-3000</label>
	</li>
	<li>
			<input group="10637" type="radio" id="10637_4" name="answers[10637].value" value="7836"  class="selection question_radio_10637"  />		<label for="10637_4">3000-4500</label>
	</li>
	<li>
			<input group="10637" type="radio" id="10637_5" name="answers[10637].value" value="7837"  class="selection question_radio_10637"  />		<label for="10637_5">&gt;4500</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_10637  qc_0 radio" type="radio" name="answers[10637].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2027" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						价格是决定您购买护发产品的一个重要因素?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[10638].value" ></span>
<input type="hidden" name="answers[10638].id" value="" id="answers[10638].id" />
<table>
<tr>

<td>

<div class="left-label">不是</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[10638].value" value="1" id="10638_1" group="10638" class="question_radio_10638 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[10638].value" value="2" id="10638_2" group="10638" class="question_radio_10638 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[10638].value" value="3" id="10638_3" group="10638" class="question_radio_10638 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[10638].value" value="4" id="10638_4" group="10638" class="question_radio_10638 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[10638].value" value="5" id="10638_5" group="10638" class="question_radio_10638 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">是</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[10638].value" value="" id="answers[10638].value" class="q_10638 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2028" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您最喜欢的护发素是？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[10639].id" value="" id="answers[10639].id" />
<input type="text" name="answers[10639].value" value="" id="question_10639" group="10639" class="input-text" />

<span class="error-content" id="err_answers[10639].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2040" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您有多大可能把这个产品推荐给您的朋友？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[10640].value" ></span>
<input type="hidden" name="answers[10640].id" value="" id="answers[10640].id" />
<table>
<tr>

<td>

<div class="left-label">不可能</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[10640].value" value="0" id="10640_0" group="10640" class="question_radio_10640 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[10640].value" value="1" id="10640_1" group="10640" class="question_radio_10640 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[10640].value" value="2" id="10640_2" group="10640" class="question_radio_10640 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[10640].value" value="3" id="10640_3" group="10640" class="question_radio_10640 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[10640].value" value="4" id="10640_4" group="10640" class="question_radio_10640 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[10640].value" value="5" id="10640_5" group="10640" class="question_radio_10640 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[10640].value" value="6" id="10640_6" group="10640" class="question_radio_10640 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[10640].value" value="7" id="10640_7" group="10640" class="question_radio_10640 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[10640].value" value="8" id="10640_8" group="10640" class="question_radio_10640 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[10640].value" value="9" id="10640_9" group="10640" class="question_radio_10640 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[10640].value" value="10" id="10640_10" group="10640" class="question_radio_10640 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">一定会推荐</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[10640].value" value="" id="answers[10640].value" class="q_10640 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2041" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在您的办公室有多少女同事？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[10641].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[10641].id" value="" id="answers[10641].id" />
<ul>
	<li>
			<input group="10641" type="radio" id="10641_0" name="answers[10641].value" value="7864"  class="selection question_radio_10641"  />		<label for="10641_0">0-1</label>
	</li>
	<li>
			<input group="10641" type="radio" id="10641_1" name="answers[10641].value" value="7865"  class="selection question_radio_10641"  />		<label for="10641_1">2~5</label>
	</li>
	<li>
			<input group="10641" type="radio" id="10641_2" name="answers[10641].value" value="7866"  class="selection question_radio_10641"  />		<label for="10641_2">6~10</label>
	</li>
	<li>
			<input group="10641" type="radio" id="10641_3" name="answers[10641].value" value="7867"  class="selection question_radio_10641"  />		<label for="10641_3">11-15</label>
	</li>
	<li>
			<input group="10641" type="radio" id="10641_4" name="answers[10641].value" value="7868"  class="selection question_radio_10641"  />		<label for="10641_4">16-20</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_10641  qc_0 radio" type="radio" name="answers[10641].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2031" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您上个月在各种网站、微薄、博客发帖的数量？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[10642].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[10642].id" value="" id="answers[10642].id" />
<ul>
	<li>
			<input group="10642" type="radio" id="10642_0" name="answers[10642].value" value="7843"  class="selection question_radio_10642"  />		<label for="10642_0">1~5</label>
	</li>
	<li>
			<input group="10642" type="radio" id="10642_1" name="answers[10642].value" value="7844"  class="selection question_radio_10642"  />		<label for="10642_1">6~10</label>
	</li>
	<li>
			<input group="10642" type="radio" id="10642_2" name="answers[10642].value" value="7845"  class="selection question_radio_10642"  />		<label for="10642_2">11~15</label>
	</li>
	<li>
			<input group="10642" type="radio" id="10642_3" name="answers[10642].value" value="7846"  class="selection question_radio_10642"  />		<label for="10642_3">16~20</label>
	</li>
	<li>
			<input group="10642" type="radio" id="10642_4" name="answers[10642].value" value="7847"  class="selection question_radio_10642"  />		<label for="10642_4">20+</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_10642  qc_0 radio" type="radio" name="answers[10642].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2032" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您上个月有在美容护肤相关的网站和博客发帖吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[10643].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[10643].id" value="" id="answers[10643].id" />
<ul>
	<li>
			<input group="10643" type="radio" id="10643_0" name="answers[10643].value" value="7848"  class="selection question_radio_10643"  />		<label for="10643_0">有</label>
	</li>
	<li>
			<input group="10643" type="radio" id="10643_1" name="answers[10643].value" value="7849"  class="selection question_radio_10643"  />		<label for="10643_1">没有</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_10643  qc_0 radio" type="radio" name="answers[10643].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2033" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您多经常在MSN、QQ等聊天工具上群聊？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[10644].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[10644].id" value="" id="answers[10644].id" />
<ul>
	<li>
			<input group="10644" type="radio" id="10644_0" name="answers[10644].value" value="7850"  class="selection question_radio_10644"  />		<label for="10644_0">从不</label>
	</li>
	<li>
			<input group="10644" type="radio" id="10644_1" name="answers[10644].value" value="7851"  class="selection question_radio_10644"  />		<label for="10644_1">每月一两次</label>
	</li>
	<li>
			<input group="10644" type="radio" id="10644_2" name="answers[10644].value" value="7852"  class="selection question_radio_10644"  />		<label for="10644_2">每周一次</label>
	</li>
	<li>
			<input group="10644" type="radio" id="10644_3" name="answers[10644].value" value="7853"  class="selection question_radio_10644"  />		<label for="10644_3">每周多次</label>
	</li>
	<li>
			<input group="10644" type="radio" id="10644_4" name="answers[10644].value" value="7854"  class="selection question_radio_10644"  />		<label for="10644_4">每天</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_10644  qc_0 radio" type="radio" name="answers[10644].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2034" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在您的朋友圈中，大家出去玩时，您
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[10645].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[10645].id" value="" id="answers[10645].id" />
<ul>
	<li>
			<input group="10645" type="radio" id="10645_0" name="answers[10645].value" value="7855"  class="selection question_radio_10645"  />		<label for="10645_0">总是计划者之一</label>
	</li>
	<li>
			<input group="10645" type="radio" id="10645_1" name="answers[10645].value" value="7856"  class="selection question_radio_10645"  />		<label for="10645_1">偶尔参与计划</label>
	</li>
	<li>
			<input group="10645" type="radio" id="10645_2" name="answers[10645].value" value="7857"  class="selection question_radio_10645"  />		<label for="10645_2">只是跟着走</label>
	</li>
	<li>
			<input group="10645" type="radio" id="10645_3" name="answers[10645].value" value="7858"  class="selection question_radio_10645"  />		<label for="10645_3">不常参加</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_10645  qc_0 radio" type="radio" name="answers[10645].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2035" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您什么情况下会特意注意穿着？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[10646].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[10646].id" value="" id="answers[10646].id" />
<ul>
	<li>
			<input group="10646" type="radio" id="10646_0" name="answers[10646].value" value="7859"  class="selection question_radio_10646"  />		<label for="10646_0">仅在周末</label>
	</li>
	<li>
			<input group="10646" type="radio" id="10646_1" name="answers[10646].value" value="7860"  class="selection question_radio_10646"  />		<label for="10646_1">仅在周中</label>
	</li>
	<li>
			<input group="10646" type="radio" id="10646_2" name="answers[10646].value" value="7861"  class="selection question_radio_10646"  />		<label for="10646_2">仅在特别场合</label>
	</li>
	<li>
			<input group="10646" type="radio" id="10646_3" name="answers[10646].value" value="7862"  class="selection question_radio_10646"  />		<label for="10646_3">几乎每天</label>
	</li>
	<li>
			<input group="10646" type="radio" id="10646_4" name="answers[10646].value" value="7863"  class="selection question_radio_10646"  />		<label for="10646_4">从不</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_10646  qc_0 radio" type="radio" name="answers[10646].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2036" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您在周末喜欢做些什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[10647].id" value="" id="answers[10647].id" />
<input type="text" name="answers[10647].value" value="" id="question_10647" group="10647" class="input-text" />

<span class="error-content" id="err_answers[10647].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="提交" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
	        jQuery("#check-alert-dialog .content").html(html);
	        jQuery("#check-alert-dialog").dialog('open');
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '提交失败：不能提交空报告';
		    jQuery("#check-alert-dialog .content").html(html);
		    jQuery("#check-alert-dialog").dialog('open');
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

// ]]>
-->
</script>
