	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/546" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2216" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						过去的三个月中，你在多少场合提起过金宝汤？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11047].id" value="" id="answers[11047].id" />
<input type="text" name="answers[11047].value" value="" id="question_11047" group="11047" class="input-text" />

<span class="error-content" id="err_answers[11047].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2217" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你在网上发表过多少次关于金宝汤的评价（例如BBS，论坛）？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11048].id" value="" id="answers[11048].id" />
<input type="text" name="answers[11048].value" value="" id="question_11048" group="11048" class="input-text" />

<span class="error-content" id="err_answers[11048].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2202" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						有多大可能性你会向其他人推荐金宝汤？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11049].value" ></span>
<input type="hidden" name="answers[11049].id" value="" id="answers[11049].id" />
<table>
<tr>

<td>

<div class="left-label"></div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11049].value" value="0" id="11049_0" group="11049" class="question_radio_11049 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11049].value" value="1" id="11049_1" group="11049" class="question_radio_11049 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11049].value" value="2" id="11049_2" group="11049" class="question_radio_11049 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11049].value" value="3" id="11049_3" group="11049" class="question_radio_11049 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11049].value" value="4" id="11049_4" group="11049" class="question_radio_11049 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11049].value" value="5" id="11049_5" group="11049" class="question_radio_11049 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11049].value" value="6" id="11049_6" group="11049" class="question_radio_11049 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11049].value" value="7" id="11049_7" group="11049" class="question_radio_11049 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11049].value" value="8" id="11049_8" group="11049" class="question_radio_11049 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11049].value" value="9" id="11049_9" group="11049" class="question_radio_11049 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11049].value" value="10" id="11049_10" group="11049" class="question_radio_11049 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label"></div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11049].value" value="" id="answers[11049].value" class="q_11049 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2203" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						为什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11050].id" value="" id="answers[11050].id" />
<textarea name="answers[11050].value" id="question_11050" cols="40" group="11050" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[11050].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2204" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您同意“没有汤的晚餐是不完整的”这种说法吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11051].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11051].id" value="" id="answers[11051].id" />
<ul>
	<li>
			<input group="11051" type="radio" id="11051_0" name="answers[11051].value" value="8473"  class="selection question_radio_11051"  />		<label for="11051_0">同意</label>
	</li>
	<li>
			<input group="11051" type="radio" id="11051_1" name="answers[11051].value" value="8474"  class="selection question_radio_11051"  />		<label for="11051_1">不同意</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11051  qc_0 radio" type="radio" name="answers[11051].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2205" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						有多少你的朋友你确定购买过金宝汤？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11052].id" value="" id="answers[11052].id" />
<input type="text" name="answers[11052].value" value="" id="question_11052" group="11052" class="input-text" />

<span class="error-content" id="err_answers[11052].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2206" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						从金宝汤活动开始到现在你买过几次金宝汤？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11053].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11053].id" value="" id="answers[11053].id" />
<ul>
	<li>
			<input group="11053" type="radio" id="11053_0" name="answers[11053].value" value="8475"  class="selection question_radio_11053"  />		<label for="11053_0">每周多于3包</label>
	</li>
	<li>
			<input group="11053" type="radio" id="11053_1" name="answers[11053].value" value="8476"  class="selection question_radio_11053"  />		<label for="11053_1">每周1至3包</label>
	</li>
	<li>
			<input group="11053" type="radio" id="11053_2" name="answers[11053].value" value="8477"  class="selection question_radio_11053"  />		<label for="11053_2">每月1至3包</label>
	</li>
	<li>
			<input group="11053" type="radio" id="11053_3" name="answers[11053].value" value="8478"  class="selection question_radio_11053"  />		<label for="11053_3">每月少于3包</label>
	</li>
	<li>
			<input group="11053" type="radio" id="11053_4" name="answers[11053].value" value="8479"  class="selection question_radio_11053"  />		<label for="11053_4">没有购买过</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11053  qc_0 radio" type="radio" name="answers[11053].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2207" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你将来有可能买金宝汤吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11054].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11054].id" value="" id="answers[11054].id" />
<ul>
	<li>
			<input group="11054" type="radio" id="11054_0" name="answers[11054].value" value="8480"  class="selection question_radio_11054"  />		<label for="11054_0">一定会购买</label>
	</li>
	<li>
			<input group="11054" type="radio" id="11054_1" name="answers[11054].value" value="8481"  class="selection question_radio_11054"  />		<label for="11054_1">会购买</label>
	</li>
	<li>
			<input group="11054" type="radio" id="11054_2" name="answers[11054].value" value="8482"  class="selection question_radio_11054"  />		<label for="11054_2">可能会购买</label>
	</li>
	<li>
			<input group="11054" type="radio" id="11054_3" name="answers[11054].value" value="8483"  class="selection question_radio_11054"  />		<label for="11054_3">不会购买</label>
	</li>
	<li>
			<input group="11054" type="radio" id="11054_4" name="answers[11054].value" value="8484"  class="selection question_radio_11054"  />		<label for="11054_4">一定不会购买</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11054  qc_0 radio" type="radio" name="answers[11054].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2208" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你对金宝汤成品汤产品的整体看法如何？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11055].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11055].id" value="" id="answers[11055].id" />
<ul>
	<li>
			<input group="11055" type="radio" id="11055_0" name="answers[11055].value" value="8485"  class="selection question_radio_11055"  />		<label for="11055_0">非常喜欢</label>
	</li>
	<li>
			<input group="11055" type="radio" id="11055_1" name="answers[11055].value" value="8486"  class="selection question_radio_11055"  />		<label for="11055_1">比较喜欢</label>
	</li>
	<li>
			<input group="11055" type="radio" id="11055_2" name="answers[11055].value" value="8487"  class="selection question_radio_11055"  />		<label for="11055_2">一般</label>
	</li>
	<li>
			<input group="11055" type="radio" id="11055_3" name="answers[11055].value" value="8488"  class="selection question_radio_11055"  />		<label for="11055_3">不太喜欢</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11055  qc_0 radio" type="radio" name="answers[11055].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2209" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你觉得金宝汤的口味怎样？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11056].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11056].id" value="" id="answers[11056].id" />
<ul>
	<li>
			<input group="11056" type="radio" id="11056_0" name="answers[11056].value" value="8489"  class="selection question_radio_11056"  />		<label for="11056_0">很好</label>
	</li>
	<li>
			<input group="11056" type="radio" id="11056_1" name="answers[11056].value" value="8490"  class="selection question_radio_11056"  />		<label for="11056_1">不错</label>
	</li>
	<li>
			<input group="11056" type="radio" id="11056_2" name="answers[11056].value" value="8491"  class="selection question_radio_11056"  />		<label for="11056_2">一般</label>
	</li>
	<li>
			<input group="11056" type="radio" id="11056_3" name="answers[11056].value" value="8492"  class="selection question_radio_11056"  />		<label for="11056_3">不好</label>
	</li>
	<li>
			<input group="11056" type="radio" id="11056_4" name="answers[11056].value" value="8493"  class="selection question_radio_11056"  />		<label for="11056_4">很差</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11056  qc_0 radio" type="radio" name="answers[11056].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2210" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						为什么你觉得金宝汤口味不好？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11057].id" value="" id="answers[11057].id" />
<textarea name="answers[11057].value" id="question_11057" cols="40" group="11057" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[11057].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2211" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你最喜欢什么口味？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11058].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11058].id" value="" id="answers[11058].id" />
<ul>
	<li>
			<input group="11058" type="radio" id="11058_0" name="answers[11058].value" value="8494"  class="selection question_radio_11058"  />		<label for="11058_0">牛肉土豆汤</label>
	</li>
	<li>
			<input group="11058" type="radio" id="11058_1" name="answers[11058].value" value="8495"  class="selection question_radio_11058"  />		<label for="11058_1">瘦肉玉米烫</label>
	</li>
	<li>
			<input group="11058" type="radio" id="11058_2" name="answers[11058].value" value="8496"  class="selection question_radio_11058"  />		<label for="11058_2">老鸭扁尖汤</label>
	</li>
	<li>
			<input group="11058" type="radio" id="11058_3" name="answers[11058].value" value="8497"  class="selection question_radio_11058"  />		<label for="11058_3">鲜鸡菌菇汤</label>
	</li>
	<li>
			<input group="11058" type="radio" id="11058_4" name="answers[11058].value" value="8498"  class="selection question_radio_11058"  />		<label for="11058_4">云南风味</label>
	</li>
	<li>
			<input group="11058" type="radio" id="11058_5" name="answers[11058].value" value="8499"  class="selection question_radio_11058"  />		<label for="11058_5">什锦菌菇汤</label>
	</li>
	<li>
			<input group="11058" type="radio" id="11058_6" name="answers[11058].value" value="8500"  class="selection question_radio_11058"  />		<label for="11058_6">新疆风味</label>
	</li>
	<li>
			<input group="11058" type="radio" id="11058_7" name="answers[11058].value" value="8501"  class="selection question_radio_11058"  />		<label for="11058_7">羊肉汤</label>
	</li>
	<li>
			<input group="11058" type="radio" id="11058_8" name="answers[11058].value" value="8502"  class="selection question_radio_11058"  />		<label for="11058_8">杭州风味</label>
	</li>
	<li>
			<input group="11058" type="radio" id="11058_9" name="answers[11058].value" value="8503"  class="selection question_radio_11058"  />		<label for="11058_9">老鸭汤</label>
	</li>
	<li>
			<input group="11058" type="radio" id="11058_10" name="answers[11058].value" value="8504"  class="selection question_radio_11058"  />		<label for="11058_10">鸡蓉玉米汤</label>
	</li>
	<li>
			<input group="11058" type="radio" id="11058_11" name="answers[11058].value" value="8505"  class="selection question_radio_11058"  />		<label for="11058_11">奶油蘑菇汤</label>
	</li>
	<li>
			<input group="11058" type="radio" id="11058_12" name="answers[11058].value" value="8506"  class="selection question_radio_11058"  />		<label for="11058_12">蘑菇玉米汤</label>
	</li>
	<li>
			<input group="11058" type="radio" id="11058_13" name="answers[11058].value" value="8507"  class="selection question_radio_11058"  />		<label for="11058_13">奶油鸡粒蘑菇汤</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11058  qc_0 radio" type="radio" name="answers[11058].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2212" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你对金宝汤的健康程度有什么看法？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11059].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11059].id" value="" id="answers[11059].id" />
<ul>
	<li>
			<input group="11059" type="radio" id="11059_0" name="answers[11059].value" value="8508"  class="selection question_radio_11059"  />		<label for="11059_0">很健康，是家庭食谱中必备的一部分</label>
	</li>
	<li>
			<input group="11059" type="radio" id="11059_1" name="answers[11059].value" value="8509"  class="selection question_radio_11059"  />		<label for="11059_1">比较健康</label>
	</li>
	<li>
			<input group="11059" type="radio" id="11059_2" name="answers[11059].value" value="8510"  class="selection question_radio_11059"  />		<label for="11059_2">还可以</label>
	</li>
	<li>
			<input group="11059" type="radio" id="11059_3" name="answers[11059].value" value="8511"  class="selection question_radio_11059"  />		<label for="11059_3">不是很健康</label>
	</li>
	<li>
			<input group="11059" type="radio" id="11059_4" name="answers[11059].value" value="8512"  class="selection question_radio_11059"  />		<label for="11059_4">不健康</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11059  qc_0 radio" type="radio" name="answers[11059].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2213" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						为什么你觉得金宝汤不健康？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11060].id" value="" id="answers[11060].id" />
<textarea name="answers[11060].value" id="question_11060" cols="40" group="11060" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[11060].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2214" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你能承受的买每包金宝汤的最高价格是多少？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11061].id" value="" id="answers[11061].id" />
<textarea name="answers[11061].value" id="question_11061" cols="40" group="11061" rows="2" class="input-text" ></textarea>
<span class="error-content" id="err_answers[11061].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
<div class="question-even question-area" style="margin-bottom: 0px;" id="q_2214">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						请选择你对以下关于汤的选项的重视程度：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
				</td>
			</tr>
	    </tbody></table>
	  </div>

		  <div id="q_2215" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
						味道好
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11062].value" ></span>
<input type="hidden" name="answers[11062].id" value="" id="answers[11062].id" />
<table>
<tr>

<td>


	<table class="">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11062].value" value="1" id="11062_1" group="11062" class="question_radio_11062 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11062].value" value="2" id="11062_2" group="11062" class="question_radio_11062 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11062].value" value="3" id="11062_3" group="11062" class="question_radio_11062 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11062].value" value="4" id="11062_4" group="11062" class="question_radio_11062 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
		</tr>
	</table> 

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11062].value" value="" id="answers[11062].value" class="q_11062 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2218" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
						方便
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11063].value" ></span>
<input type="hidden" name="answers[11063].id" value="" id="answers[11063].id" />
<table>
<tr>

<td>


	<table class="">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11063].value" value="1" id="11063_1" group="11063" class="question_radio_11063 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11063].value" value="2" id="11063_2" group="11063" class="question_radio_11063 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11063].value" value="3" id="11063_3" group="11063" class="question_radio_11063 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11063].value" value="4" id="11063_4" group="11063" class="question_radio_11063 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
		</tr>
	</table>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11063].value" value="" id="answers[11063].value" class="q_11063 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2219" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
						价格
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11064].value" ></span>
<input type="hidden" name="answers[11064].id" value="" id="answers[11064].id" />
<table>
<tr>

<td>


	<table class="">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11064].value" value="1" id="11064_1" group="11064" class="question_radio_11064 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11064].value" value="2" id="11064_2" group="11064" class="question_radio_11064 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11064].value" value="3" id="11064_3" group="11064" class="question_radio_11064 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11064].value" value="4" id="11064_4" group="11064" class="question_radio_11064 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
		</tr>
	</table> 

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11064].value" value="" id="answers[11064].value" class="q_11064 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2220" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
						做汤所花时间
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11065].value" ></span>
<input type="hidden" name="answers[11065].id" value="" id="answers[11065].id" />
<table>
<tr>

<td>


	<table class="">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11065].value" value="1" id="11065_1" group="11065" class="question_radio_11065 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11065].value" value="2" id="11065_2" group="11065" class="question_radio_11065 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11065].value" value="3" id="11065_3" group="11065" class="question_radio_11065 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11065].value" value="4" id="11065_4" group="11065" class="question_radio_11065 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
		</tr>
	</table> 

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11065].value" value="" id="answers[11065].value" class="q_11065 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2221" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
						营养
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11066].value" ></span>
<input type="hidden" name="answers[11066].id" value="" id="answers[11066].id" />
<table>
<tr>

<td>


	<table class="">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11066].value" value="1" id="11066_1" group="11066" class="question_radio_11066 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11066].value" value="2" id="11066_2" group="11066" class="question_radio_11066 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11066].value" value="3" id="11066_3" group="11066" class="question_radio_11066 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11066].value" value="4" id="11066_4" group="11066" class="question_radio_11066 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
		</tr>
	</table> 

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11066].value" value="" id="answers[11066].value" class="q_11066 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2222" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
						多种口味
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11067].value" ></span>
<input type="hidden" name="answers[11067].id" value="" id="answers[11067].id" />
<table>
<tr>

<td>

	<table class="">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11067].value" value="1" id="11067_1" group="11067" class="question_radio_11067 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11067].value" value="2" id="11067_2" group="11067" class="question_radio_11067 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11067].value" value="3" id="11067_3" group="11067" class="question_radio_11067 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11067].value" value="4" id="11067_4" group="11067" class="question_radio_11067 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
		</tr>
	</table>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11067].value" value="" id="answers[11067].value" class="q_11067 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2223" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
						健康
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11068].value" ></span>
<input type="hidden" name="answers[11068].id" value="" id="answers[11068].id" />
<table>
<tr>

<td>

	<table class="">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11068].value" value="1" id="11068_1" group="11068" class="question_radio_11068 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11068].value" value="2" id="11068_2" group="11068" class="question_radio_11068 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11068].value" value="3" id="11068_3" group="11068" class="question_radio_11068 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11068].value" value="4" id="11068_4" group="11068" class="question_radio_11068 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
		</tr>
	</table>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11068].value" value="" id="answers[11068].value" class="q_11068 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2224" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你现在对金宝汤这个品牌的看法是什么？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11069].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11069].id" value="" id="answers[11069].id" />
<ul>
	<li>
			<input group="11069" type="radio" id="11069_0" name="answers[11069].value" value="8513"  class="selection question_radio_11069"  />		<label for="11069_0">很不喜欢</label>
	</li>
	<li>
			<input group="11069" type="radio" id="11069_1" name="answers[11069].value" value="8514"  class="selection question_radio_11069"  />		<label for="11069_1">不太喜欢</label>
	</li>
	<li>
			<input group="11069" type="radio" id="11069_2" name="answers[11069].value" value="8515"  class="selection question_radio_11069"  />		<label for="11069_2">一般</label>
	</li>
	<li>
			<input group="11069" type="radio" id="11069_3" name="answers[11069].value" value="8516"  class="selection question_radio_11069"  />		<label for="11069_3">比较喜欢</label>
	</li>
	<li>
			<input group="11069" type="radio" id="11069_4" name="answers[11069].value" value="8517"  class="selection question_radio_11069"  />		<label for="11069_4">非常喜欢</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11069  qc_0 radio" type="radio" name="answers[11069].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2225" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您每周为晚餐做几次汤(速食和非速食)？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11070].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11070].id" value="" id="answers[11070].id" />
<ul>
	<li>
			<input group="11070" type="radio" id="11070_0" name="answers[11070].value" value="8518"  class="selection question_radio_11070"  />		<label for="11070_0">少于每周一次</label>
	</li>
	<li>
			<input group="11070" type="radio" id="11070_1" name="answers[11070].value" value="8519"  class="selection question_radio_11070"  />		<label for="11070_1">每周1至2次</label>
	</li>
	<li>
			<input group="11070" type="radio" id="11070_2" name="answers[11070].value" value="8520"  class="selection question_radio_11070"  />		<label for="11070_2">每周3至5次</label>
	</li>
	<li>
			<input group="11070" type="radio" id="11070_3" name="answers[11070].value" value="8521"  class="selection question_radio_11070"  />		<label for="11070_3">每天或几乎天天</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11070  qc_0 radio" type="radio" name="answers[11070].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2226" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您每周晚餐吃几次成品汤（速食）？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11071].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11071].id" value="" id="answers[11071].id" />
<ul>
	<li>
			<input group="11071" type="radio" id="11071_0" name="answers[11071].value" value="8522"  class="selection question_radio_11071"  />		<label for="11071_0">少于每周一次</label>
	</li>
	<li>
			<input group="11071" type="radio" id="11071_1" name="answers[11071].value" value="8523"  class="selection question_radio_11071"  />		<label for="11071_1">每周1至2次</label>
	</li>
	<li>
			<input group="11071" type="radio" id="11071_2" name="answers[11071].value" value="8524"  class="selection question_radio_11071"  />		<label for="11071_2">每周3至5次</label>
	</li>
	<li>
			<input group="11071" type="radio" id="11071_3" name="answers[11071].value" value="8525"  class="selection question_radio_11071"  />		<label for="11071_3">每天或几乎天天</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11071  qc_0 radio" type="radio" name="answers[11071].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="提交" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
	        jQuery("#check-alert-dialog .content").html(html);
	        jQuery("#check-alert-dialog").dialog('open');
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '提交失败：不能提交空报告';
		    jQuery("#check-alert-dialog .content").html(html);
		    jQuery("#check-alert-dialog").dialog('open');
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[


	 Element.hide("q_2210");
	 Element.hide("q_2213");


var myrules = {
	   
	   "input#11059_0": function(el){
			el.onclick = function(){
				if ($("11059_0").checked){
						Element.hide($("q_2213"));
				}
			}
		}
	,
	   
	   "input#11056_1": function(el){
			el.onclick = function(){
				if ($("11056_1").checked){
						Element.hide($("q_2210"));
				}
			}
		}
	,
	   
	   "input#11059_2": function(el){
			el.onclick = function(){
				if ($("11059_2").checked){
						Element.hide($("q_2213"));
				}
			}
		}
	,
	   
	   "input#11056_3": function(el){
			el.onclick = function(){
				if ($("11056_3").checked){
						Element.show($("q_2210"));
				}
			}
		}
	,
	   
	   "input#11056_2": function(el){
			el.onclick = function(){
				if ($("11056_2").checked){
						Element.hide($("q_2210"));
				}
			}
		}
	,
	   
	   "input#11056_0": function(el){
			el.onclick = function(){
				if ($("11056_0").checked){
						Element.hide($("q_2210"));
				}
			}
		}
	,
	   
	   "input#11059_3": function(el){
			el.onclick = function(){
				if ($("11059_3").checked){
						Element.show($("q_2213"));
				}
			}
		}
	,
	   
	   "input#11059_1": function(el){
			el.onclick = function(){
				if ($("11059_1").checked){
						Element.hide($("q_2213"));
				}
			}
		}
	,
	   
	   "input#11059_4": function(el){
			el.onclick = function(){
				if ($("11059_4").checked){
						Element.show($("q_2213"));
				}
			}
		}
	,
	   
	   "input#11056_4": function(el){
			el.onclick = function(){
				if ($("11056_4").checked){
						Element.show($("q_2210"));
				}
			}
		}
}

Behaviour.register(myrules);

// ]]>
-->
</script>
