	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/570" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="loading();return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="RLByrGfurII6" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2246" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你在多少场合提起过金宝汤？（请填数字）
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11252].id" value="" id="answers[11252].id" />
<input type="text" name="answers[11252].value" value="" id="question_11252" group="11252" class="input-text" />

<span class="error-content" id="err_answers[11252].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2247" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你在网上发表过多少次关于金宝汤的评价（例如BBS，论坛）？（请填数字）
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11253].id" value="" id="answers[11253].id" />
<input type="text" name="answers[11253].value" value="" id="question_11253" group="11253" class="input-text" />

<span class="error-content" id="err_answers[11253].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2202" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						有多大可能性你会向其他人推荐金宝汤？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11254].value" ></span>
<input type="hidden" name="answers[11254].id" value="" id="answers[11254].id" />
<table>
<tr>

<td>

<div class="left-label">左标签</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11254].value" value="0" id="11254_0" group="11254" class="question_radio_11254 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11254].value" value="1" id="11254_1" group="11254" class="question_radio_11254 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11254].value" value="2" id="11254_2" group="11254" class="question_radio_11254 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11254].value" value="3" id="11254_3" group="11254" class="question_radio_11254 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11254].value" value="4" id="11254_4" group="11254" class="question_radio_11254 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11254].value" value="5" id="11254_5" group="11254" class="question_radio_11254 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11254].value" value="6" id="11254_6" group="11254" class="question_radio_11254 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11254].value" value="7" id="11254_7" group="11254" class="question_radio_11254 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11254].value" value="8" id="11254_8" group="11254" class="question_radio_11254 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11254].value" value="9" id="11254_9" group="11254" class="question_radio_11254 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11254].value" value="10" id="11254_10" group="11254" class="question_radio_11254 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">右标签</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11254].value" value="" id="answers[11254].value" class="q_11254 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2248" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您同意“没有汤的晚餐是不完整的”这种说法吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11255].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11255].id" value="" id="answers[11255].id" />
<ul>
	<li>
			<input group="11255" type="radio" id="11255_0" name="answers[11255].value" value="8575"  class="selection question_radio_11255"  />		<label for="11255_0">非常同意</label>
	</li>
	<li>
			<input group="11255" type="radio" id="11255_1" name="answers[11255].value" value="8576"  class="selection question_radio_11255"  />		<label for="11255_1">比较同意</label>
	</li>
	<li>
			<input group="11255" type="radio" id="11255_2" name="answers[11255].value" value="8577"  class="selection question_radio_11255"  />		<label for="11255_2">中立</label>
	</li>
	<li>
			<input group="11255" type="radio" id="11255_3" name="answers[11255].value" value="8578"  class="selection question_radio_11255"  />		<label for="11255_3">有点不认同</label>
	</li>
	<li>
			<input group="11255" type="radio" id="11255_4" name="answers[11255].value" value="8579"  class="selection question_radio_11255"  />		<label for="11255_4">非常不认同</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11255  qc_0 radio" type="radio" name="answers[11255].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2252" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在过去三个月中你有购买过金宝汤吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11256].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11256].id" value="" id="answers[11256].id" />
<ul>
	<li>
			<input group="11256" type="radio" id="11256_0" name="answers[11256].value" value="8592"  class="selection question_radio_11256"  />		<label for="11256_0">有</label>
	</li>
	<li>
			<input group="11256" type="radio" id="11256_1" name="answers[11256].value" value="8593"  class="selection question_radio_11256"  />		<label for="11256_1">没有</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11256  qc_0 radio" type="radio" name="answers[11256].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2206" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						从金宝汤活动开始到现在你买过几次金宝汤？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11257].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11257].id" value="" id="answers[11257].id" />
<ul>
	<li>
			<input group="11257" type="radio" id="11257_0" name="answers[11257].value" value="8475"  class="selection question_radio_11257"  />		<label for="11257_0">每周多于3包</label>
	</li>
	<li>
			<input group="11257" type="radio" id="11257_1" name="answers[11257].value" value="8476"  class="selection question_radio_11257"  />		<label for="11257_1">每周1至3包</label>
	</li>
	<li>
			<input group="11257" type="radio" id="11257_2" name="answers[11257].value" value="8477"  class="selection question_radio_11257"  />		<label for="11257_2">每月1至3包</label>
	</li>
	<li>
			<input group="11257" type="radio" id="11257_3" name="answers[11257].value" value="8478"  class="selection question_radio_11257"  />		<label for="11257_3">每月少于3包</label>
	</li>
	<li>
			<input group="11257" type="radio" id="11257_4" name="answers[11257].value" value="8479"  class="selection question_radio_11257"  />		<label for="11257_4">没有购买过</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11257  qc_0 radio" type="radio" name="answers[11257].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2207" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你将来有可能买金宝汤吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11258].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11258].id" value="" id="answers[11258].id" />
<ul>
	<li>
			<input group="11258" type="radio" id="11258_0" name="answers[11258].value" value="8480"  class="selection question_radio_11258"  />		<label for="11258_0">一定会购买</label>
	</li>
	<li>
			<input group="11258" type="radio" id="11258_1" name="answers[11258].value" value="8481"  class="selection question_radio_11258"  />		<label for="11258_1">会购买</label>
	</li>
	<li>
			<input group="11258" type="radio" id="11258_2" name="answers[11258].value" value="8482"  class="selection question_radio_11258"  />		<label for="11258_2">可能会购买</label>
	</li>
	<li>
			<input group="11258" type="radio" id="11258_3" name="answers[11258].value" value="8483"  class="selection question_radio_11258"  />		<label for="11258_3">不会购买</label>
	</li>
	<li>
			<input group="11258" type="radio" id="11258_4" name="answers[11258].value" value="8484"  class="selection question_radio_11258"  />		<label for="11258_4">一定不会购买</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11258  qc_0 radio" type="radio" name="answers[11258].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2203" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						为什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11259].id" value="" id="answers[11259].id" />
<textarea name="answers[11259].value" id="question_11259" cols="40" group="11259" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[11259].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2208" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你对金宝汤成品汤产品的整体看法如何？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11260].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11260].id" value="" id="answers[11260].id" />
<ul>
	<li>
			<input group="11260" type="radio" id="11260_0" name="answers[11260].value" value="8485"  class="selection question_radio_11260"  />		<label for="11260_0">非常喜欢</label>
	</li>
	<li>
			<input group="11260" type="radio" id="11260_1" name="answers[11260].value" value="8486"  class="selection question_radio_11260"  />		<label for="11260_1">比较喜欢</label>
	</li>
	<li>
			<input group="11260" type="radio" id="11260_2" name="answers[11260].value" value="8487"  class="selection question_radio_11260"  />		<label for="11260_2">一般</label>
	</li>
	<li>
			<input group="11260" type="radio" id="11260_3" name="answers[11260].value" value="8488"  class="selection question_radio_11260"  />		<label for="11260_3">不太喜欢</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11260  qc_0 radio" type="radio" name="answers[11260].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2209" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你觉得金宝汤的口味怎样？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11261].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11261].id" value="" id="answers[11261].id" />
<ul>
	<li>
			<input group="11261" type="radio" id="11261_0" name="answers[11261].value" value="8489"  class="selection question_radio_11261"  />		<label for="11261_0">很好</label>
	</li>
	<li>
			<input group="11261" type="radio" id="11261_1" name="answers[11261].value" value="8490"  class="selection question_radio_11261"  />		<label for="11261_1">不错</label>
	</li>
	<li>
			<input group="11261" type="radio" id="11261_2" name="answers[11261].value" value="8491"  class="selection question_radio_11261"  />		<label for="11261_2">一般</label>
	</li>
	<li>
			<input group="11261" type="radio" id="11261_3" name="answers[11261].value" value="8492"  class="selection question_radio_11261"  />		<label for="11261_3">不好</label>
	</li>
	<li>
			<input group="11261" type="radio" id="11261_4" name="answers[11261].value" value="8493"  class="selection question_radio_11261"  />		<label for="11261_4">很差</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11261  qc_0 radio" type="radio" name="answers[11261].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2250" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你觉得金宝汤的价格怎样？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11262].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11262].id" value="" id="answers[11262].id" />

	<select group="11262" class="selection" id="question_11262" name="answers[11262].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="8582" style=""  >很划算</option>
<option value="8583" style=""  >价格不错</option>
<option value="8584" style=""  >价格适中</option>
<option value="8585" style=""  >有点贵</option>
<option value="8586" style=""  >太贵了</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2211" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你最喜欢什么口味？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11263].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11263].id" value="" id="answers[11263].id" />
<ul>
	<li>
			<input group="11263" type="radio" id="11263_0" name="answers[11263].value" value="8494"  class="selection question_radio_11263"  />		<label for="11263_0">牛肉土豆汤</label>
	</li>
	<li>
			<input group="11263" type="radio" id="11263_1" name="answers[11263].value" value="8495"  class="selection question_radio_11263"  />		<label for="11263_1">瘦肉玉米烫</label>
	</li>
	<li>
			<input group="11263" type="radio" id="11263_2" name="answers[11263].value" value="8496"  class="selection question_radio_11263"  />		<label for="11263_2">老鸭扁尖汤</label>
	</li>
	<li>
			<input group="11263" type="radio" id="11263_3" name="answers[11263].value" value="8497"  class="selection question_radio_11263"  />		<label for="11263_3">鲜鸡菌菇汤</label>
	</li>
	<li>
			<input group="11263" type="radio" id="11263_4" name="answers[11263].value" value="8498"  class="selection question_radio_11263"  />		<label for="11263_4">云南风味</label>
	</li>
	<li>
			<input group="11263" type="radio" id="11263_5" name="answers[11263].value" value="8499"  class="selection question_radio_11263"  />		<label for="11263_5">什锦菌菇汤</label>
	</li>
	<li>
			<input group="11263" type="radio" id="11263_6" name="answers[11263].value" value="8500"  class="selection question_radio_11263"  />		<label for="11263_6">新疆风味</label>
	</li>
	<li>
			<input group="11263" type="radio" id="11263_7" name="answers[11263].value" value="8501"  class="selection question_radio_11263"  />		<label for="11263_7">羊肉汤</label>
	</li>
	<li>
			<input group="11263" type="radio" id="11263_8" name="answers[11263].value" value="8502"  class="selection question_radio_11263"  />		<label for="11263_8">杭州风味</label>
	</li>
	<li>
			<input group="11263" type="radio" id="11263_9" name="answers[11263].value" value="8503"  class="selection question_radio_11263"  />		<label for="11263_9">老鸭汤</label>
	</li>
	<li>
			<input group="11263" type="radio" id="11263_10" name="answers[11263].value" value="8504"  class="selection question_radio_11263"  />		<label for="11263_10">鸡蓉玉米汤</label>
	</li>
	<li>
			<input group="11263" type="radio" id="11263_11" name="answers[11263].value" value="8505"  class="selection question_radio_11263"  />		<label for="11263_11">奶油蘑菇汤</label>
	</li>
	<li>
			<input group="11263" type="radio" id="11263_12" name="answers[11263].value" value="8506"  class="selection question_radio_11263"  />		<label for="11263_12">蘑菇玉米汤</label>
	</li>
	<li>
			<input group="11263" type="radio" id="11263_13" name="answers[11263].value" value="8507"  class="selection question_radio_11263"  />		<label for="11263_13">奶油鸡粒蘑菇汤</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11263  qc_0 radio" type="radio" name="answers[11263].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2256" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你第二喜欢口味是什么？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11264].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11264].id" value="" id="answers[11264].id" />
<ul>
	<li>
			<input group="11264" type="radio" id="11264_0" name="answers[11264].value" value="8597"  class="selection question_radio_11264"  />		<label for="11264_0">牛肉土豆汤</label>
	</li>
	<li>
			<input group="11264" type="radio" id="11264_1" name="answers[11264].value" value="8598"  class="selection question_radio_11264"  />		<label for="11264_1">瘦肉玉米烫</label>
	</li>
	<li>
			<input group="11264" type="radio" id="11264_2" name="answers[11264].value" value="8599"  class="selection question_radio_11264"  />		<label for="11264_2">老鸭扁尖汤</label>
	</li>
	<li>
			<input group="11264" type="radio" id="11264_3" name="answers[11264].value" value="8600"  class="selection question_radio_11264"  />		<label for="11264_3">鲜鸡菌菇汤</label>
	</li>
	<li>
			<input group="11264" type="radio" id="11264_4" name="answers[11264].value" value="8601"  class="selection question_radio_11264"  />		<label for="11264_4">云南风味</label>
	</li>
	<li>
			<input group="11264" type="radio" id="11264_5" name="answers[11264].value" value="8602"  class="selection question_radio_11264"  />		<label for="11264_5">什锦菌菇汤</label>
	</li>
	<li>
			<input group="11264" type="radio" id="11264_6" name="answers[11264].value" value="8603"  class="selection question_radio_11264"  />		<label for="11264_6">新疆风味</label>
	</li>
	<li>
			<input group="11264" type="radio" id="11264_7" name="answers[11264].value" value="8604"  class="selection question_radio_11264"  />		<label for="11264_7">羊肉汤</label>
	</li>
	<li>
			<input group="11264" type="radio" id="11264_8" name="answers[11264].value" value="8605"  class="selection question_radio_11264"  />		<label for="11264_8">杭州风味</label>
	</li>
	<li>
			<input group="11264" type="radio" id="11264_9" name="answers[11264].value" value="8606"  class="selection question_radio_11264"  />		<label for="11264_9">老鸭汤</label>
	</li>
	<li>
			<input group="11264" type="radio" id="11264_10" name="answers[11264].value" value="8607"  class="selection question_radio_11264"  />		<label for="11264_10">鸡蓉玉米汤</label>
	</li>
	<li>
			<input group="11264" type="radio" id="11264_11" name="answers[11264].value" value="8608"  class="selection question_radio_11264"  />		<label for="11264_11">奶油蘑菇汤</label>
	</li>
	<li>
			<input group="11264" type="radio" id="11264_12" name="answers[11264].value" value="8609"  class="selection question_radio_11264"  />		<label for="11264_12">蘑菇玉米汤</label>
	</li>
	<li>
			<input group="11264" type="radio" id="11264_13" name="answers[11264].value" value="8610"  class="selection question_radio_11264"  />		<label for="11264_13">奶油鸡粒蘑菇汤</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11264  qc_0 radio" type="radio" name="answers[11264].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2251" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你觉得金宝汤的口味怎样？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11265].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11265].id" value="" id="answers[11265].id" />
<ul>
	<li>
			<input group="11265" type="radio" id="11265_0" name="answers[11265].value" value="8587"  class="selection question_radio_11265"  />		<label for="11265_0">很健康，是家庭食谱中必备的一部分</label>
	</li>
	<li>
			<input group="11265" type="radio" id="11265_1" name="answers[11265].value" value="8588"  class="selection question_radio_11265"  />		<label for="11265_1">比较健康</label>
	</li>
	<li>
			<input group="11265" type="radio" id="11265_2" name="answers[11265].value" value="8589"  class="selection question_radio_11265"  />		<label for="11265_2">还可以</label>
	</li>
	<li>
			<input group="11265" type="radio" id="11265_3" name="answers[11265].value" value="8590"  class="selection question_radio_11265"  />		<label for="11265_3">不是很健康</label>
	</li>
	<li>
			<input group="11265" type="radio" id="11265_4" name="answers[11265].value" value="8591"  class="selection question_radio_11265"  />		<label for="11265_4">不健康</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11265  qc_0 radio" type="radio" name="answers[11265].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2214" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你能承受的买每包金宝汤的最高价格是多少？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11266].id" value="" id="answers[11266].id" />
<textarea name="answers[11266].value" id="question_11266" cols="40" group="11266" rows="2" class="input-text" ></textarea>
<span class="error-content" id="err_answers[11266].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2215" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						味道好
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11267].value" ></span>
<input type="hidden" name="answers[11267].id" value="" id="answers[11267].id" />
<table>
<tr>

<td>

<div class="left-label">左标签</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11267].value" value="1" id="11267_1" group="11267" class="question_radio_11267 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11267].value" value="2" id="11267_2" group="11267" class="question_radio_11267 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11267].value" value="3" id="11267_3" group="11267" class="question_radio_11267 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11267].value" value="4" id="11267_4" group="11267" class="question_radio_11267 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
		</tr>
	</table> <div class="right-label">右标签</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11267].value" value="" id="answers[11267].value" class="q_11267 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2218" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						方便
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11268].value" ></span>
<input type="hidden" name="answers[11268].id" value="" id="answers[11268].id" />
<table>
<tr>

<td>

<div class="left-label">左标签</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11268].value" value="1" id="11268_1" group="11268" class="question_radio_11268 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11268].value" value="2" id="11268_2" group="11268" class="question_radio_11268 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11268].value" value="3" id="11268_3" group="11268" class="question_radio_11268 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11268].value" value="4" id="11268_4" group="11268" class="question_radio_11268 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
		</tr>
	</table> <div class="right-label">右标签</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11268].value" value="" id="answers[11268].value" class="q_11268 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2219" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						价格
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11269].value" ></span>
<input type="hidden" name="answers[11269].id" value="" id="answers[11269].id" />
<table>
<tr>

<td>

<div class="left-label">左标签</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11269].value" value="1" id="11269_1" group="11269" class="question_radio_11269 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11269].value" value="2" id="11269_2" group="11269" class="question_radio_11269 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11269].value" value="3" id="11269_3" group="11269" class="question_radio_11269 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11269].value" value="4" id="11269_4" group="11269" class="question_radio_11269 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
		</tr>
	</table> <div class="right-label">右标签</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11269].value" value="" id="answers[11269].value" class="q_11269 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2220" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						做汤所花时间
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11270].value" ></span>
<input type="hidden" name="answers[11270].id" value="" id="answers[11270].id" />
<table>
<tr>

<td>

<div class="left-label">左标签</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11270].value" value="1" id="11270_1" group="11270" class="question_radio_11270 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11270].value" value="2" id="11270_2" group="11270" class="question_radio_11270 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11270].value" value="3" id="11270_3" group="11270" class="question_radio_11270 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11270].value" value="4" id="11270_4" group="11270" class="question_radio_11270 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
		</tr>
	</table> <div class="right-label">右标签</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11270].value" value="" id="answers[11270].value" class="q_11270 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2221" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						营养
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11271].value" ></span>
<input type="hidden" name="answers[11271].id" value="" id="answers[11271].id" />
<table>
<tr>

<td>

<div class="left-label">左标签</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11271].value" value="1" id="11271_1" group="11271" class="question_radio_11271 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11271].value" value="2" id="11271_2" group="11271" class="question_radio_11271 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11271].value" value="3" id="11271_3" group="11271" class="question_radio_11271 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11271].value" value="4" id="11271_4" group="11271" class="question_radio_11271 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
		</tr>
	</table> <div class="right-label">右标签</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11271].value" value="" id="answers[11271].value" class="q_11271 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2222" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						多种口味
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11272].value" ></span>
<input type="hidden" name="answers[11272].id" value="" id="answers[11272].id" />
<table>
<tr>

<td>

<div class="left-label">左标签</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11272].value" value="1" id="11272_1" group="11272" class="question_radio_11272 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11272].value" value="2" id="11272_2" group="11272" class="question_radio_11272 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11272].value" value="3" id="11272_3" group="11272" class="question_radio_11272 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11272].value" value="4" id="11272_4" group="11272" class="question_radio_11272 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
		</tr>
	</table> <div class="right-label">右标签</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11272].value" value="" id="answers[11272].value" class="q_11272 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2223" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						健康
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11273].value" ></span>
<input type="hidden" name="answers[11273].id" value="" id="answers[11273].id" />
<table>
<tr>

<td>

<div class="left-label">左标签</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11273].value" value="1" id="11273_1" group="11273" class="question_radio_11273 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11273].value" value="2" id="11273_2" group="11273" class="question_radio_11273 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11273].value" value="3" id="11273_3" group="11273" class="question_radio_11273 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11273].value" value="4" id="11273_4" group="11273" class="question_radio_11273 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
		</tr>
	</table> <div class="right-label">右标签</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11273].value" value="" id="answers[11273].value" class="q_11273 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2224" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你现在对金宝汤这个品牌的看法是什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11274].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11274].id" value="" id="answers[11274].id" />
<ul>
	<li>
			<input group="11274" type="radio" id="11274_0" name="answers[11274].value" value="8513"  class="selection question_radio_11274"  />		<label for="11274_0">很不喜欢</label>
	</li>
	<li>
			<input group="11274" type="radio" id="11274_1" name="answers[11274].value" value="8514"  class="selection question_radio_11274"  />		<label for="11274_1">不太喜欢</label>
	</li>
	<li>
			<input group="11274" type="radio" id="11274_2" name="answers[11274].value" value="8515"  class="selection question_radio_11274"  />		<label for="11274_2">一般</label>
	</li>
	<li>
			<input group="11274" type="radio" id="11274_3" name="answers[11274].value" value="8516"  class="selection question_radio_11274"  />		<label for="11274_3">比较喜欢</label>
	</li>
	<li>
			<input group="11274" type="radio" id="11274_4" name="answers[11274].value" value="8517"  class="selection question_radio_11274"  />		<label for="11274_4">非常喜欢</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11274  qc_0 radio" type="radio" name="answers[11274].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2225" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您每周为晚餐做几次汤(速食和非速食)？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11275].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11275].id" value="" id="answers[11275].id" />
<ul>
	<li>
			<input group="11275" type="radio" id="11275_0" name="answers[11275].value" value="8518"  class="selection question_radio_11275"  />		<label for="11275_0">少于每周一次</label>
	</li>
	<li>
			<input group="11275" type="radio" id="11275_1" name="answers[11275].value" value="8519"  class="selection question_radio_11275"  />		<label for="11275_1">每周1至2次</label>
	</li>
	<li>
			<input group="11275" type="radio" id="11275_2" name="answers[11275].value" value="8520"  class="selection question_radio_11275"  />		<label for="11275_2">每周3至5次</label>
	</li>
	<li>
			<input group="11275" type="radio" id="11275_3" name="answers[11275].value" value="8521"  class="selection question_radio_11275"  />		<label for="11275_3">每天或几乎天天</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11275  qc_0 radio" type="radio" name="answers[11275].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2226" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您每周晚餐吃几次成品汤（速食）？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11276].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11276].id" value="" id="answers[11276].id" />
<ul>
	<li>
			<input group="11276" type="radio" id="11276_0" name="answers[11276].value" value="8522"  class="selection question_radio_11276"  />		<label for="11276_0">少于每周一次</label>
	</li>
	<li>
			<input group="11276" type="radio" id="11276_1" name="answers[11276].value" value="8523"  class="selection question_radio_11276"  />		<label for="11276_1">每周1至2次</label>
	</li>
	<li>
			<input group="11276" type="radio" id="11276_2" name="answers[11276].value" value="8524"  class="selection question_radio_11276"  />		<label for="11276_2">每周3至5次</label>
	</li>
	<li>
			<input group="11276" type="radio" id="11276_3" name="answers[11276].value" value="8525"  class="selection question_radio_11276"  />		<label for="11276_3">每天或几乎天天</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11276  qc_0 radio" type="radio" name="answers[11276].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="Submit" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = 'Mandatory questions must be filled out';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = 'Can not submit empty questionnaire form';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

Framework.registerAjaxSensors();
// ]]>
-->
</script>
