	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/583" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="loading();return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="j4KxEuO99uA2" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2264" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你现在对于在新加坡工作和生活的看法是？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11293].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11293].id" value="" id="answers[11293].id" />
<ul>
	<li>
			<input group="11293" type="radio" id="11293_0" name="answers[11293].value" value="8620"  class="selection question_radio_11293"  />		<label for="11293_0">很不好</label>
	</li>
	<li>
			<input group="11293" type="radio" id="11293_1" name="answers[11293].value" value="8621"  class="selection question_radio_11293"  />		<label for="11293_1">不太好</label>
	</li>
	<li>
			<input group="11293" type="radio" id="11293_2" name="answers[11293].value" value="8622"  class="selection question_radio_11293"  />		<label for="11293_2">无所谓</label>
	</li>
	<li>
			<input group="11293" type="radio" id="11293_3" name="answers[11293].value" value="8623"  class="selection question_radio_11293"  />		<label for="11293_3">还算好</label>
	</li>
	<li>
			<input group="11293" type="radio" id="11293_4" name="answers[11293].value" value="8624"  class="selection question_radio_11293"  />		<label for="11293_4">非常好</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11293  qc_0 radio" type="radio" name="answers[11293].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2265" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						有多大可能性你会推荐你的朋友去新加坡工作？
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11294].value" ></span>
<input type="hidden" name="answers[11294].id" value="" id="answers[11294].id" />
<table>
<tr>

<td>

<div class="left-label">不可能</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11294].value" value="0" id="11294_0" group="11294" class="question_radio_11294 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11294].value" value="1" id="11294_1" group="11294" class="question_radio_11294 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11294].value" value="2" id="11294_2" group="11294" class="question_radio_11294 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11294].value" value="3" id="11294_3" group="11294" class="question_radio_11294 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11294].value" value="4" id="11294_4" group="11294" class="question_radio_11294 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11294].value" value="5" id="11294_5" group="11294" class="question_radio_11294 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11294].value" value="6" id="11294_6" group="11294" class="question_radio_11294 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11294].value" value="7" id="11294_7" group="11294" class="question_radio_11294 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11294].value" value="8" id="11294_8" group="11294" class="question_radio_11294 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11294].value" value="9" id="11294_9" group="11294" class="question_radio_11294 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11294].value" value="10" id="11294_10" group="11294" class="question_radio_11294 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">一定</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11294].value" value="" id="answers[11294].value" class="q_11294 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2266" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						有多大可能性你自己会考虑去新加坡工作？
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11295].value" ></span>
<input type="hidden" name="answers[11295].id" value="" id="answers[11295].id" />
<table>
<tr>

<td>

<div class="left-label">不可能</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11295].value" value="0" id="11295_0" group="11295" class="question_radio_11295 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11295].value" value="1" id="11295_1" group="11295" class="question_radio_11295 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11295].value" value="2" id="11295_2" group="11295" class="question_radio_11295 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11295].value" value="3" id="11295_3" group="11295" class="question_radio_11295 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11295].value" value="4" id="11295_4" group="11295" class="question_radio_11295 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11295].value" value="5" id="11295_5" group="11295" class="question_radio_11295 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11295].value" value="6" id="11295_6" group="11295" class="question_radio_11295 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11295].value" value="7" id="11295_7" group="11295" class="question_radio_11295 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11295].value" value="8" id="11295_8" group="11295" class="question_radio_11295 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11295].value" value="9" id="11295_9" group="11295" class="question_radio_11295 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11295].value" value="10" id="11295_10" group="11295" class="question_radio_11295 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">一定</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11295].value" value="" id="answers[11295].value" class="q_11295 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2267" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你认为对于工程师来说新加坡的工作机会会比中国好吗?
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11296].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11296].id" value="" id="answers[11296].id" />
<ul>
	<li>
			<input group="11296" type="radio" id="11296_0" name="answers[11296].value" value="8625"  class="selection question_radio_11296"  />		<label for="11296_0">是</label>
	</li>
	<li>
			<input group="11296" type="radio" id="11296_1" name="answers[11296].value" value="8626"  class="selection question_radio_11296"  />		<label for="11296_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11296  qc_0 radio" type="radio" name="answers[11296].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2268" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你在考虑工作时技能的提升有多重要？
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11297].value" ></span>
<input type="hidden" name="answers[11297].id" value="" id="answers[11297].id" />
<table>
<tr>

<td>

<div class="left-label">不重要</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11297].value" value="1" id="11297_1" group="11297" class="question_radio_11297 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11297].value" value="2" id="11297_2" group="11297" class="question_radio_11297 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11297].value" value="3" id="11297_3" group="11297" class="question_radio_11297 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11297].value" value="4" id="11297_4" group="11297" class="question_radio_11297 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11297].value" value="5" id="11297_5" group="11297" class="question_radio_11297 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">很重要</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11297].value" value="" id="answers[11297].value" class="q_11297 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2269" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你在考虑工作时发展的机会有多重要？
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11298].value" ></span>
<input type="hidden" name="answers[11298].id" value="" id="answers[11298].id" />
<table>
<tr>

<td>

<div class="left-label">不重要</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11298].value" value="1" id="11298_1" group="11298" class="question_radio_11298 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11298].value" value="2" id="11298_2" group="11298" class="question_radio_11298 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11298].value" value="3" id="11298_3" group="11298" class="question_radio_11298 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11298].value" value="4" id="11298_4" group="11298" class="question_radio_11298 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11298].value" value="5" id="11298_5" group="11298" class="question_radio_11298 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">很重要</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11298].value" value="" id="answers[11298].value" class="q_11298 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2270" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你在考虑工作时工作和生活的平衡有多重要？
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11299].value" ></span>
<input type="hidden" name="answers[11299].id" value="" id="answers[11299].id" />
<table>
<tr>

<td>

<div class="left-label">不重要</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11299].value" value="1" id="11299_1" group="11299" class="question_radio_11299 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11299].value" value="2" id="11299_2" group="11299" class="question_radio_11299 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11299].value" value="3" id="11299_3" group="11299" class="question_radio_11299 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11299].value" value="4" id="11299_4" group="11299" class="question_radio_11299 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11299].value" value="5" id="11299_5" group="11299" class="question_radio_11299 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">很重要</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11299].value" value="" id="answers[11299].value" class="q_11299 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2271" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你在考虑工作时薪资有多重要？
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11300].value" ></span>
<input type="hidden" name="answers[11300].id" value="" id="answers[11300].id" />
<table>
<tr>

<td>

<div class="left-label">不重要</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11300].value" value="1" id="11300_1" group="11300" class="question_radio_11300 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11300].value" value="2" id="11300_2" group="11300" class="question_radio_11300 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11300].value" value="3" id="11300_3" group="11300" class="question_radio_11300 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11300].value" value="4" id="11300_4" group="11300" class="question_radio_11300 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11300].value" value="5" id="11300_5" group="11300" class="question_radio_11300 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">很重要</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11300].value" value="" id="answers[11300].value" class="q_11300 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2272" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你认为生活的质量对你选择工作地点的影响程度有多大？
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11301].value" ></span>
<input type="hidden" name="answers[11301].id" value="" id="answers[11301].id" />
<table>
<tr>

<td>

<div class="left-label">不大</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11301].value" value="1" id="11301_1" group="11301" class="question_radio_11301 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11301].value" value="2" id="11301_2" group="11301" class="question_radio_11301 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11301].value" value="3" id="11301_3" group="11301" class="question_radio_11301 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11301].value" value="4" id="11301_4" group="11301" class="question_radio_11301 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11301].value" value="5" id="11301_5" group="11301" class="question_radio_11301 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">很大</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11301].value" value="" id="answers[11301].value" class="q_11301 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2273" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你认为中文的交流社区对你选择工作地点的影响程度有多大？
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11302].value" ></span>
<input type="hidden" name="answers[11302].id" value="" id="answers[11302].id" />
<table>
<tr>

<td>

<div class="left-label">不大</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11302].value" value="1" id="11302_1" group="11302" class="question_radio_11302 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11302].value" value="2" id="11302_2" group="11302" class="question_radio_11302 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11302].value" value="3" id="11302_3" group="11302" class="question_radio_11302 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11302].value" value="4" id="11302_4" group="11302" class="question_radio_11302 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11302].value" value="5" id="11302_5" group="11302" class="question_radio_11302 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">很大</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11302].value" value="" id="answers[11302].value" class="q_11302 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2274" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你认为广阔的视野对你选择工作地点的影响程度有多大？
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11303].value" ></span>
<input type="hidden" name="answers[11303].id" value="" id="answers[11303].id" />
<table>
<tr>

<td>

<div class="left-label">不大</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11303].value" value="1" id="11303_1" group="11303" class="question_radio_11303 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11303].value" value="2" id="11303_2" group="11303" class="question_radio_11303 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11303].value" value="3" id="11303_3" group="11303" class="question_radio_11303 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11303].value" value="4" id="11303_4" group="11303" class="question_radio_11303 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11303].value" value="5" id="11303_5" group="11303" class="question_radio_11303 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">很大</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11303].value" value="" id="answers[11303].value" class="q_11303 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2275" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你认为安全的治安对你选择工作地点的影响程度有多大？
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11304].value" ></span>
<input type="hidden" name="answers[11304].id" value="" id="answers[11304].id" />
<table>
<tr>

<td>

<div class="left-label">不大</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11304].value" value="1" id="11304_1" group="11304" class="question_radio_11304 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11304].value" value="2" id="11304_2" group="11304" class="question_radio_11304 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11304].value" value="3" id="11304_3" group="11304" class="question_radio_11304 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11304].value" value="4" id="11304_4" group="11304" class="question_radio_11304 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11304].value" value="5" id="11304_5" group="11304" class="question_radio_11304 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">很大</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11304].value" value="" id="answers[11304].value" class="q_11304 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2276" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你移居新加坡的最大障碍是？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11305].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11305].id" value="" id="answers[11305].id" />




<span id="hint_11305">
</span>
<ul>
	<li>
			<input group="11305" class="question_radio_11305 selection" type="checkbox" id="11305_0" name="answers[11305].value" value="8627" 	onclick=" "/>		<label for="11305_0">不想离开父母</label>
	</li>
	<li>
			<input group="11305" class="question_radio_11305 selection" type="checkbox" id="11305_1" name="answers[11305].value" value="8628" 	onclick=" "/>		<label for="11305_1">女朋友/妻子不在一起</label>
	</li>
	<li>
			<input group="11305" class="question_radio_11305 selection" type="checkbox" id="11305_2" name="answers[11305].value" value="8629" 	onclick=" "/>		<label for="11305_2">只会说汉语</label>
	</li>
	<li>
			<input group="11305" class="question_radio_11305 selection" type="checkbox" id="11305_3" name="answers[11305].value" value="8630" 	onclick=" "/>		<label for="11305_3">舍不得孩子</label>
	</li>
	<li>
			<input group="11305" class="question_radio_11305 selection" type="checkbox" id="11305_4" name="answers[11305].value" value="8631" 	onclick=" "/>		<label for="11305_4">不想离开朋友</label>
	</li>
	<li>
			<input group="11305" class="question_radio_11305 selection" type="checkbox" id="11305_5" name="answers[11305].value" value="8632" 	onclick=" "/>		<label for="11305_5">太危险了</label>
	</li>
	<li>
			<input group="11305" class="question_radio_11305 selection" type="checkbox" id="11305_6" name="answers[11305].value" value="8633" 	onclick=" "/>		<label for="11305_6">我不知道如何申请签证和工作证</label>
	</li>
	<li>
			<input group="11305" class="question_radio_11305 selection" type="checkbox" id="11305_7" name="answers[11305].value" value="8634" 	onclick=" "/>		<label for="11305_7">我担心在新加坡找不到房子</label>
	</li>
	<li>
			<input group="11305" class="question_radio_11305 selection" type="checkbox" id="11305_8" name="answers[11305].value" value="8635" 	onclick=" "/>		<label for="11305_8">我担心新加坡的法律制度</label>
	</li>
	<li>
			<input group="11305" class="question_radio_11305 selection" type="checkbox" id="11305_9" name="answers[11305].value" value="8636" 	onclick=" "/>		<label for="11305_9">我不想失去国内的好工作机会</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2277" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请详细解释你的困难
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11306].id" value="" id="answers[11306].id" />
<textarea name="answers[11306].value" id="question_11306" cols="40" group="11306" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[11306].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="Submit" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = 'Mandatory questions must be filled out';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = 'Can not submit empty questionnaire form';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

Framework.registerAjaxSensors();
// ]]>
-->
</script>
