	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/604" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2328" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在这个活动开始前，你对“百利甜酒”这个牌子的熟悉程度？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11656].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11656].id" value="" id="answers[11656].id" />
<ul>
	<li>
			<input group="11656" type="radio" id="11656_0" name="answers[11656].value" value="8906"  class="selection question_radio_11656"  />		<label for="11656_0">从来没有听说过百利甜酒</label>
	</li>
	<li>
			<input group="11656" type="radio" id="11656_1" name="answers[11656].value" value="8907"  class="selection question_radio_11656"  />		<label for="11656_1">听说过，但没试过</label>
	</li>
	<li>
			<input group="11656" type="radio" id="11656_2" name="answers[11656].value" value="8908"  class="selection question_radio_11656"  />		<label for="11656_2">听说过，也喝过</label>
	</li>
	<li>
			<input group="11656" type="radio" id="11656_3" name="answers[11656].value" value="8909"  class="selection question_radio_11656"  />		<label for="11656_3">听说过，并规律性的饮用</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11656  qc_0 radio" type="radio" name="answers[11656].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2329" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在这个活动前，你有多大程度会向朋友推荐百利甜酒?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11657].value" ></span>
<input type="hidden" name="answers[11657].id" value="" id="answers[11657].id" />
<table>
<tr>

<td>

<div class="left-label">不会推荐</div>
<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11657].value" value="0" id="11657_0" group="11657" class="question_radio_11657 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11657].value" value="1" id="11657_1" group="11657" class="question_radio_11657 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11657].value" value="2" id="11657_2" group="11657" class="question_radio_11657 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11657].value" value="3" id="11657_3" group="11657" class="question_radio_11657 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11657].value" value="4" id="11657_4" group="11657" class="question_radio_11657 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11657].value" value="5" id="11657_5" group="11657" class="question_radio_11657 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11657].value" value="6" id="11657_6" group="11657" class="question_radio_11657 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11657].value" value="7" id="11657_7" group="11657" class="question_radio_11657 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11657].value" value="8" id="11657_8" group="11657" class="question_radio_11657 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11657].value" value="9" id="11657_9" group="11657" class="question_radio_11657 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11657].value" value="10" id="11657_10" group="11657" class="question_radio_11657 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">一定推荐</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11657].value" value="" id="answers[11657].value" class="q_11657 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2330" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						这个活动之前，你对百利甜酒的评价？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11658].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11658].id" value="" id="answers[11658].id" />
<ul>
	<li>
			<input group="11658" type="radio" id="11658_0" name="answers[11658].value" value="8910"  class="selection question_radio_11658"  />		<label for="11658_0">很负面</label>
	</li>
	<li>
			<input group="11658" type="radio" id="11658_1" name="answers[11658].value" value="8911"  class="selection question_radio_11658"  />		<label for="11658_1">负面</label>
	</li>
	<li>
			<input group="11658" type="radio" id="11658_2" name="answers[11658].value" value="8912"  class="selection question_radio_11658"  />		<label for="11658_2">中立</label>
	</li>
	<li>
			<input group="11658" type="radio" id="11658_3" name="answers[11658].value" value="8913"  class="selection question_radio_11658"  />		<label for="11658_3">正面</label>
	</li>
	<li>
			<input group="11658" type="radio" id="11658_4" name="answers[11658].value" value="8914"  class="selection question_radio_11658"  />		<label for="11658_4">非常正面</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11658  qc_0 radio" type="radio" name="answers[11658].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2331" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你有多大程度会在店里购买百利甜酒？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11659].value" ></span>
<input type="hidden" name="answers[11659].id" value="" id="answers[11659].id" />
<table>
<tr>

<td>

<div class="left-label">一定不会买</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11659].value" value="1" id="11659_1" group="11659" class="question_radio_11659 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11659].value" value="2" id="11659_2" group="11659" class="question_radio_11659 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11659].value" value="3" id="11659_3" group="11659" class="question_radio_11659 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11659].value" value="4" id="11659_4" group="11659" class="question_radio_11659 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11659].value" value="5" id="11659_5" group="11659" class="question_radio_11659 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">一定会买</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11659].value" value="" id="answers[11659].value" class="q_11659 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2332" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你有多大程度会在酒吧或KTV里购买百利甜酒？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11660].value" ></span>
<input type="hidden" name="answers[11660].id" value="" id="answers[11660].id" />
<table>
<tr>

<td>

<div class="left-label">一定不会买</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11660].value" value="1" id="11660_1" group="11660" class="question_radio_11660 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11660].value" value="2" id="11660_2" group="11660" class="question_radio_11660 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11660].value" value="3" id="11660_3" group="11660" class="question_radio_11660 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11660].value" value="4" id="11660_4" group="11660" class="question_radio_11660 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11660].value" value="5" id="11660_5" group="11660" class="question_radio_11660 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">一定会买</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11660].value" value="" id="answers[11660].value" class="q_11660 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2333" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在过去的三个月里，你有在商店里购买过百利甜酒吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11661].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11661].id" value="" id="answers[11661].id" />
<ul>
	<li>
			<input group="11661" type="radio" id="11661_0" name="answers[11661].value" value="8915"  class="selection question_radio_11661"  />		<label for="11661_0">买过</label>
	</li>
	<li>
			<input group="11661" type="radio" id="11661_1" name="answers[11661].value" value="8916"  class="selection question_radio_11661"  />		<label for="11661_1">没买过</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11661  qc_0 radio" type="radio" name="answers[11661].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2334" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在过去的三个月里，你有在酒吧或KTV里购买过百利甜酒吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11662].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11662].id" value="" id="answers[11662].id" />
<ul>
	<li>
			<input group="11662" type="radio" id="11662_0" name="answers[11662].value" value="8917"  class="selection question_radio_11662"  />		<label for="11662_0">买过</label>
	</li>
	<li>
			<input group="11662" type="radio" id="11662_1" name="answers[11662].value" value="8918"  class="selection question_radio_11662"  />		<label for="11662_1">没买过</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11662  qc_0 radio" type="radio" name="answers[11662].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2335" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你第一次喝酒是在多少年以前？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11663].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11663].id" value="" id="answers[11663].id" />
<ul>
	<li>
			<input group="11663" type="radio" id="11663_0" name="answers[11663].value" value="8919"  class="selection question_radio_11663"  />		<label for="11663_0">不到一年前</label>
	</li>
	<li>
			<input group="11663" type="radio" id="11663_1" name="answers[11663].value" value="8920"  class="selection question_radio_11663"  />		<label for="11663_1">一年或两年前</label>
	</li>
	<li>
			<input group="11663" type="radio" id="11663_2" name="answers[11663].value" value="8921"  class="selection question_radio_11663"  />		<label for="11663_2">三年或四年前</label>
	</li>
	<li>
			<input group="11663" type="radio" id="11663_3" name="answers[11663].value" value="8922"  class="selection question_radio_11663"  />		<label for="11663_3">四到六年前</label>
	</li>
	<li>
			<input group="11663" type="radio" id="11663_4" name="answers[11663].value" value="8923"  class="selection question_radio_11663"  />		<label for="11663_4">超过六年前</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11663  qc_0 radio" type="radio" name="answers[11663].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2342" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你一周平均喝酒的次数？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11664].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11664].id" value="" id="answers[11664].id" />
<ul>
	<li>
			<input group="11664" type="radio" id="11664_0" name="answers[11664].value" value="8950"  class="selection question_radio_11664"  />		<label for="11664_0">0-1</label>
	</li>
	<li>
			<input group="11664" type="radio" id="11664_1" name="answers[11664].value" value="8951"  class="selection question_radio_11664"  />		<label for="11664_1">2-4</label>
	</li>
	<li>
			<input group="11664" type="radio" id="11664_2" name="answers[11664].value" value="8952"  class="selection question_radio_11664"  />		<label for="11664_2">5-10</label>
	</li>
	<li>
			<input group="11664" type="radio" id="11664_3" name="answers[11664].value" value="8953"  class="selection question_radio_11664"  />		<label for="11664_3">11-20</label>
	</li>
	<li>
			<input group="11664" type="radio" id="11664_4" name="answers[11664].value" value="8954"  class="selection question_radio_11664"  />		<label for="11664_4">&gt;20</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11664  qc_0 radio" type="radio" name="answers[11664].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2343" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请你选出与朋友们饮酒时考虑的三个最重要的因素
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11665].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11665].id" value="" id="answers[11665].id" />




<span id="hint_11665">
</span>
<ul>
	<li>
			<input group="11665" class="question_radio_11665 selection" type="checkbox" id="11665_0" name="answers[11665].value" value="8955" 	onclick=" "/>		<label for="11665_0">相聚</label>
	</li>
	<li>
			<input group="11665" class="question_radio_11665 selection" type="checkbox" id="11665_1" name="answers[11665].value" value="8956" 	onclick=" "/>		<label for="11665_1">放松</label>
	</li>
	<li>
			<input group="11665" class="question_radio_11665 selection" type="checkbox" id="11665_2" name="answers[11665].value" value="8957" 	onclick=" "/>		<label for="11665_2">烈酒</label>
	</li>
	<li>
			<input group="11665" class="question_radio_11665 selection" type="checkbox" id="11665_3" name="answers[11665].value" value="8958" 	onclick=" "/>		<label for="11665_3">价格</label>
	</li>
	<li>
			<input group="11665" class="question_radio_11665 selection" type="checkbox" id="11665_4" name="answers[11665].value" value="8959" 	onclick=" "/>		<label for="11665_4">发胖</label>
	</li>
	<li>
			<input group="11665" class="question_radio_11665 selection" type="checkbox" id="11665_5" name="answers[11665].value" value="8960" 	onclick=" "/>		<label for="11665_5">味道</label>
	</li>
	<li>
			<input group="11665" class="question_radio_11665 selection" type="checkbox" id="11665_6" name="answers[11665].value" value="8961" 	onclick=" "/>		<label for="11665_6">温暖</label>
	</li>
	<li>
			<input group="11665" class="question_radio_11665 selection" type="checkbox" id="11665_7" name="answers[11665].value" value="8962" 	onclick=" "/>		<label for="11665_7">进口</label>
	</li>
	<li>
			<input group="11665" class="question_radio_11665 selection" type="checkbox" id="11665_8" name="answers[11665].value" value="8963" 	onclick=" "/>		<label for="11665_8">保持控制</label>
	</li>
	<li>
			<input group="11665" class="question_radio_11665 selection" type="checkbox" id="11665_9" name="answers[11665].value" value="8964" 	onclick=" "/>		<label for="11665_9">外出</label>
	</li>
	<li>
			<input group="11665" class="question_radio_11665 selection" type="checkbox" id="11665_10" name="answers[11665].value" value="8965" 	onclick=" "/>		<label for="11665_10">酒的本身</label>
	</li>
	<li>
			<input group="11665" class="question_radio_11665 selection" type="checkbox" id="11665_11" name="answers[11665].value" value="8966" 	onclick=" "/>		<label for="11665_11">酒的品牌</label>
	</li>
	<li>
			<input group="11665" class="question_radio_11665 selection" type="checkbox" id="11665_12" name="answers[11665].value" value="8967" 	onclick=" "/>		<label for="11665_12">包装</label>
	</li>
	<li>
			<input group="11665" class="question_radio_11665 selection" type="checkbox" id="11665_13" name="answers[11665].value" value="8968" 	onclick=" "/>		<label for="11665_13">广告</label>
	</li>
	<li>
			<input group="11665" class="question_radio_11665 selection" type="checkbox" id="11665_14" name="answers[11665].value" value="8969" 	onclick=" "/>		<label for="11665_14">朋友推荐</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2338" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						当你想到百利甜酒时，你会想到什么词描述它？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11666].id" value="" id="answers[11666].id" />
<input type="text" name="answers[11666].value" value="" id="question_11666" group="11666" class="input-text" />

<span class="error-content" id="err_answers[11666].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2339" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你平时经常喝的酒？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11667].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11667].id" value="" id="answers[11667].id" />
<ul>
	<li>
			<input group="11667" type="radio" id="11667_0" name="answers[11667].value" value="8939"  class="selection question_radio_11667" onclick="showOtherValueInputInRadio(this)" />		<label for="11667_0">软性的（例如啤酒）</label>
	</li>
	<li>
			<input group="11667" type="radio" id="11667_1" name="answers[11667].value" value="8940"  class="selection question_radio_11667" onclick="showOtherValueInputInRadio(this)" />		<label for="11667_1">中性的 (例如葡萄酒，鸡尾酒）</label>
	</li>
	<li>
			<input group="11667" type="radio" id="11667_2" name="answers[11667].value" value="8941"  class="selection question_radio_11667" onclick="showOtherValueInputInRadio(this)" />		<label for="11667_2">烈酒（不混合的）</label>
	</li>
		<li>
			<input type="radio" id="11667_other" name="answers[11667].value" value="0" class="question_radio_11667" onclick="showOtherValueInputInRadio(this)" />			<label for="11667_other">其他</label>
			<input id="11667_other_input" type="text" name="answers[11667].otherValue" value=""  style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11667  qc_0 radio" type="radio" name="answers[11667].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2340" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你一般在什么时候喝酒？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11668].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11668].id" value="" id="answers[11668].id" />
<ul>
	<li>
			<input group="11668" type="radio" id="11668_0" name="answers[11668].value" value="8942"  class="selection question_radio_11668" onclick="showOtherValueInputInRadio(this)" />		<label for="11668_0">当亲戚或朋友作客的时候</label>
	</li>
	<li>
			<input group="11668" type="radio" id="11668_1" name="answers[11668].value" value="8943"  class="selection question_radio_11668" onclick="showOtherValueInputInRadio(this)" />		<label for="11668_1">和朋友在外的时候</label>
	</li>
	<li>
			<input group="11668" type="radio" id="11668_2" name="answers[11668].value" value="8944"  class="selection question_radio_11668" onclick="showOtherValueInputInRadio(this)" />		<label for="11668_2">想放松的时候</label>
	</li>
		<li>
			<input type="radio" id="11668_other" name="answers[11668].value" value="0" class="question_radio_11668" onclick="showOtherValueInputInRadio(this)" />			<label for="11668_other">其他</label>
			<input id="11668_other_input" type="text" name="answers[11668].otherValue" value=""  style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11668  qc_0 radio" type="radio" name="answers[11668].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2344" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你在什么地方喝酒？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11669].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11669].id" value="" id="answers[11669].id" />
<ul>
	<li>
			<input group="11669" type="radio" id="11669_0" name="answers[11669].value" value="8970"  class="selection question_radio_11669" onclick="showOtherValueInputInRadio(this)" />		<label for="11669_0">家</label>
	</li>
	<li>
			<input group="11669" type="radio" id="11669_1" name="answers[11669].value" value="8971"  class="selection question_radio_11669" onclick="showOtherValueInputInRadio(this)" />		<label for="11669_1">酒吧</label>
	</li>
	<li>
			<input group="11669" type="radio" id="11669_2" name="answers[11669].value" value="8972"  class="selection question_radio_11669" onclick="showOtherValueInputInRadio(this)" />		<label for="11669_2">KTV</label>
	</li>
	<li>
			<input group="11669" type="radio" id="11669_3" name="answers[11669].value" value="8973"  class="selection question_radio_11669" onclick="showOtherValueInputInRadio(this)" />		<label for="11669_3">饭店</label>
	</li>
	<li>
			<input group="11669" type="radio" id="11669_4" name="answers[11669].value" value="8974"  class="selection question_radio_11669" onclick="showOtherValueInputInRadio(this)" />		<label for="11669_4">夜总会</label>
	</li>
		<li>
			<input type="radio" id="11669_other" name="answers[11669].value" value="0" class="question_radio_11669" onclick="showOtherValueInputInRadio(this)" />			<label for="11669_other">其他</label>
			<input id="11669_other_input" type="text" name="answers[11669].otherValue" value=""  style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11669  qc_0 radio" type="radio" name="answers[11669].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="提交" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
			jQuery("#check-alert-dialog .content").html(html);
    			jQuery("#check-alert-dialog").dialog('open');
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '提交失败：不能提交空报告';
			jQuery("#check-alert-dialog .content").html(html);
    			jQuery("#check-alert-dialog").dialog('open');
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

// ]]>
-->
</script>
