	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/606" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="loading();return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="YyUZhVR7o22E" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2345" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						总体来说, 你对这次星星火社区力士体验分享活动满意吗?
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11670].value" ></span>
<input type="hidden" name="answers[11670].id" value="" id="answers[11670].id" />
<table>
<tr>

<td>

<div class="left-label">非常不满意</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11670].value" value="0" id="11670_0" group="11670" class="question_radio_11670 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11670].value" value="1" id="11670_1" group="11670" class="question_radio_11670 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11670].value" value="2" id="11670_2" group="11670" class="question_radio_11670 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11670].value" value="3" id="11670_3" group="11670" class="question_radio_11670 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11670].value" value="4" id="11670_4" group="11670" class="question_radio_11670 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11670].value" value="5" id="11670_5" group="11670" class="question_radio_11670 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11670].value" value="6" id="11670_6" group="11670" class="question_radio_11670 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11670].value" value="7" id="11670_7" group="11670" class="question_radio_11670 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11670].value" value="8" id="11670_8" group="11670" class="question_radio_11670 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11670].value" value="9" id="11670_9" group="11670" class="question_radio_11670 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11670].value" value="10" id="11670_10" group="11670" class="question_radio_11670 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">非常满意</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11670].value" value="" id="answers[11670].value" class="q_11670 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2346" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请你提供一些建议给我们: 在哪些方面我们还可以做得更好？
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11671].id" value="" id="answers[11671].id" />
<textarea name="answers[11671].value" id="question_11671" cols="40" group="11671" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[11671].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2347" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						过去三个月中,你在多少个场合提到过力士？
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11672].id" value="" id="answers[11672].id" />
<textarea name="answers[11672].value" id="question_11672" cols="40" group="11672" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[11672].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2348" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你有在网上发表过有关力士的帖子或评论吗？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11673].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11673].id" value="" id="answers[11673].id" />
<ul>
	<li>
			<input group="11673" type="radio" id="11673_0" name="answers[11673].value" value="8975"  class="selection question_radio_11673"  />		<label for="11673_0">是</label>
	</li>
	<li>
			<input group="11673" type="radio" id="11673_1" name="answers[11673].value" value="8976"  class="selection question_radio_11673"  />		<label for="11673_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11673  qc_0 radio" type="radio" name="answers[11673].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2349" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						如果有,请将网页地址链接贴在下面的输入框里
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11674].id" value="" id="answers[11674].id" />
<textarea name="answers[11674].value" id="question_11674" cols="40" group="11674" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[11674].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2350" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						如果你已经找不到那些帖子的链接，请问你发表评论的次数？（当4b问题答案为空）
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11675].id" value="" id="answers[11675].id" />
<textarea name="answers[11675].value" id="question_11675" cols="40" group="11675" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[11675].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2351" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你有多大可能会向别人推荐力士？
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11676].value" ></span>
<input type="hidden" name="answers[11676].id" value="" id="answers[11676].id" />
<table>
<tr>

<td>

<div class="left-label">一定不会推荐</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11676].value" value="0" id="11676_0" group="11676" class="question_radio_11676 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11676].value" value="1" id="11676_1" group="11676" class="question_radio_11676 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11676].value" value="2" id="11676_2" group="11676" class="question_radio_11676 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11676].value" value="3" id="11676_3" group="11676" class="question_radio_11676 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11676].value" value="4" id="11676_4" group="11676" class="question_radio_11676 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11676].value" value="5" id="11676_5" group="11676" class="question_radio_11676 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11676].value" value="6" id="11676_6" group="11676" class="question_radio_11676 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11676].value" value="7" id="11676_7" group="11676" class="question_radio_11676 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11676].value" value="8" id="11676_8" group="11676" class="question_radio_11676 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11676].value" value="9" id="11676_9" group="11676" class="question_radio_11676 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11676].value" value="10" id="11676_10" group="11676" class="question_radio_11676 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">一定会推荐</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11676].value" value="" id="answers[11676].value" class="q_11676 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2352" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						为什么?
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11677].id" value="" id="answers[11677].id" />
<textarea name="answers[11677].value" id="question_11677" cols="40" group="11677" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[11677].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2353" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你目前对力士的评价是...？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11678].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11678].id" value="" id="answers[11678].id" />
<ul>
	<li>
			<input group="11678" type="radio" id="11678_0" name="answers[11678].value" value="8977"  class="selection question_radio_11678"  />		<label for="11678_0">非常负面</label>
	</li>
	<li>
			<input group="11678" type="radio" id="11678_1" name="answers[11678].value" value="8978"  class="selection question_radio_11678"  />		<label for="11678_1">有点负面</label>
	</li>
	<li>
			<input group="11678" type="radio" id="11678_2" name="answers[11678].value" value="8979"  class="selection question_radio_11678"  />		<label for="11678_2">中立</label>
	</li>
	<li>
			<input group="11678" type="radio" id="11678_3" name="answers[11678].value" value="8980"  class="selection question_radio_11678"  />		<label for="11678_3">有点正面</label>
	</li>
	<li>
			<input group="11678" type="radio" id="11678_4" name="answers[11678].value" value="8981"  class="selection question_radio_11678"  />		<label for="11678_4">非常正面</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11678  qc_0 radio" type="radio" name="answers[11678].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2354" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在过去三个月,你有购买力士的产品吗？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11679].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11679].id" value="" id="answers[11679].id" />
<ul>
	<li>
			<input group="11679" type="radio" id="11679_0" name="answers[11679].value" value="8982"  class="selection question_radio_11679"  />		<label for="11679_0">有</label>
	</li>
	<li>
			<input group="11679" type="radio" id="11679_1" name="answers[11679].value" value="8983"  class="selection question_radio_11679"  />		<label for="11679_1">没有</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11679  qc_0 radio" type="radio" name="answers[11679].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2355" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在过去三个月,你购买的力士产品数量是...？（如果7a的答案是“没有”可不做回答）
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11680].id" value="" id="answers[11680].id" />
<input type="text" name="answers[11680].value" value="" id="question_11680" group="11680" class="input-text" />

<span class="error-content" id="err_answers[11680].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2356" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你有多大可能会在将来购买力士的洗护产品？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11681].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11681].id" value="" id="answers[11681].id" />
<ul>
	<li>
			<input group="11681" type="radio" id="11681_0" name="answers[11681].value" value="8984"  class="selection question_radio_11681"  />		<label for="11681_0">一定不会买</label>
	</li>
	<li>
			<input group="11681" type="radio" id="11681_1" name="answers[11681].value" value="8985"  class="selection question_radio_11681"  />		<label for="11681_1">也许会买</label>
	</li>
	<li>
			<input group="11681" type="radio" id="11681_2" name="answers[11681].value" value="8986"  class="selection question_radio_11681"  />		<label for="11681_2">不一定会买</label>
	</li>
	<li>
			<input group="11681" type="radio" id="11681_3" name="answers[11681].value" value="8987"  class="selection question_radio_11681"  />		<label for="11681_3">应该会买</label>
	</li>
	<li>
			<input group="11681" type="radio" id="11681_4" name="answers[11681].value" value="8988"  class="selection question_radio_11681"  />		<label for="11681_4">一定会买</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11681  qc_0 radio" type="radio" name="answers[11681].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2357" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						10个样品中，你与朋友们分享了几个？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11682].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11682].id" value="" id="answers[11682].id" />
<ul>
	<li>
			<input group="11682" type="radio" id="11682_0" name="answers[11682].value" value="8989"  class="selection question_radio_11682"  />		<label for="11682_0">没有</label>
	</li>
	<li>
			<input group="11682" type="radio" id="11682_1" name="answers[11682].value" value="8990"  class="selection question_radio_11682"  />		<label for="11682_1">1</label>
	</li>
	<li>
			<input group="11682" type="radio" id="11682_2" name="answers[11682].value" value="8991"  class="selection question_radio_11682"  />		<label for="11682_2">2</label>
	</li>
	<li>
			<input group="11682" type="radio" id="11682_3" name="answers[11682].value" value="8992"  class="selection question_radio_11682"  />		<label for="11682_3">3</label>
	</li>
	<li>
			<input group="11682" type="radio" id="11682_4" name="answers[11682].value" value="8993"  class="selection question_radio_11682"  />		<label for="11682_4">4</label>
	</li>
	<li>
			<input group="11682" type="radio" id="11682_5" name="answers[11682].value" value="8994"  class="selection question_radio_11682"  />		<label for="11682_5">5</label>
	</li>
	<li>
			<input group="11682" type="radio" id="11682_6" name="answers[11682].value" value="8995"  class="selection question_radio_11682"  />		<label for="11682_6">6</label>
	</li>
	<li>
			<input group="11682" type="radio" id="11682_7" name="answers[11682].value" value="8996"  class="selection question_radio_11682"  />		<label for="11682_7">7</label>
	</li>
	<li>
			<input group="11682" type="radio" id="11682_8" name="answers[11682].value" value="8997"  class="selection question_radio_11682"  />		<label for="11682_8">8</label>
	</li>
	<li>
			<input group="11682" type="radio" id="11682_9" name="answers[11682].value" value="8998"  class="selection question_radio_11682"  />		<label for="11682_9">9</label>
	</li>
	<li>
			<input group="11682" type="radio" id="11682_10" name="answers[11682].value" value="8999"  class="selection question_radio_11682"  />		<label for="11682_10">全部</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11682  qc_0 radio" type="radio" name="answers[11682].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2358" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						力士是一个专业的品牌
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11683].value" ></span>
<input type="hidden" name="answers[11683].id" value="" id="answers[11683].id" />
<table>
<tr>

<td>

<div class="left-label">非常不同意</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11683].value" value="1" id="11683_1" group="11683" class="question_radio_11683 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11683].value" value="2" id="11683_2" group="11683" class="question_radio_11683 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11683].value" value="3" id="11683_3" group="11683" class="question_radio_11683 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11683].value" value="4" id="11683_4" group="11683" class="question_radio_11683 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11683].value" value="5" id="11683_5" group="11683" class="question_radio_11683 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">非常同意</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11683].value" value="" id="answers[11683].value" class="q_11683 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2359" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						力士是一个好的洗发水及洗护组合
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11684].value" ></span>
<input type="hidden" name="answers[11684].id" value="" id="answers[11684].id" />
<table>
<tr>

<td>

<div class="left-label">非常不同意</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11684].value" value="1" id="11684_1" group="11684" class="question_radio_11684 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11684].value" value="2" id="11684_2" group="11684" class="question_radio_11684 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11684].value" value="3" id="11684_3" group="11684" class="question_radio_11684 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11684].value" value="4" id="11684_4" group="11684" class="question_radio_11684 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11684].value" value="5" id="11684_5" group="11684" class="question_radio_11684 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">非常同意</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11684].value" value="" id="answers[11684].value" class="q_11684 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2360" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						力士让我的头发亮泽
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11685].value" ></span>
<input type="hidden" name="answers[11685].id" value="" id="answers[11685].id" />
<table>
<tr>

<td>

<div class="left-label">非常不同意</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11685].value" value="1" id="11685_1" group="11685" class="question_radio_11685 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11685].value" value="2" id="11685_2" group="11685" class="question_radio_11685 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11685].value" value="3" id="11685_3" group="11685" class="question_radio_11685 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11685].value" value="4" id="11685_4" group="11685" class="question_radio_11685 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11685].value" value="5" id="11685_5" group="11685" class="question_radio_11685 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">非常同意</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11685].value" value="" id="answers[11685].value" class="q_11685 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2361" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						力士修复了我受损的头发
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11686].value" ></span>
<input type="hidden" name="answers[11686].id" value="" id="answers[11686].id" />
<table>
<tr>

<td>

<div class="left-label">非常不同意</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11686].value" value="1" id="11686_1" group="11686" class="question_radio_11686 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11686].value" value="2" id="11686_2" group="11686" class="question_radio_11686 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11686].value" value="3" id="11686_3" group="11686" class="question_radio_11686 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11686].value" value="4" id="11686_4" group="11686" class="question_radio_11686 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11686].value" value="5" id="11686_5" group="11686" class="question_radio_11686 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">非常同意</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11686].value" value="" id="answers[11686].value" class="q_11686 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2362" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						力士让我变得更有吸引力
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11687].value" ></span>
<input type="hidden" name="answers[11687].id" value="" id="answers[11687].id" />
<table>
<tr>

<td>

<div class="left-label">非常不同意</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11687].value" value="1" id="11687_1" group="11687" class="question_radio_11687 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11687].value" value="2" id="11687_2" group="11687" class="question_radio_11687 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11687].value" value="3" id="11687_3" group="11687" class="question_radio_11687 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11687].value" value="4" id="11687_4" group="11687" class="question_radio_11687 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11687].value" value="5" id="11687_5" group="11687" class="question_radio_11687 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">非常同意</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11687].value" value="" id="answers[11687].value" class="q_11687 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2363" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在你收到样品后，你有向认识的人推荐力士吗？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11688].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11688].id" value="" id="answers[11688].id" />
<ul>
	<li>
			<input group="11688" type="radio" id="11688_0" name="answers[11688].value" value="9000"  class="selection question_radio_11688"  />		<label for="11688_0">有</label>
	</li>
	<li>
			<input group="11688" type="radio" id="11688_1" name="answers[11688].value" value="9001"  class="selection question_radio_11688"  />		<label for="11688_1">没有</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11688  qc_0 radio" type="radio" name="answers[11688].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2364" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你比较常用的头发洗护品牌是?
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11689].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11689].id" value="" id="answers[11689].id" />
<ul>
	<li>
			<input group="11689" type="radio" id="11689_0" name="answers[11689].value" value="9002"  class="selection question_radio_11689"  />		<label for="11689_0">力士</label>
	</li>
	<li>
			<input group="11689" type="radio" id="11689_1" name="answers[11689].value" value="9003"  class="selection question_radio_11689"  />		<label for="11689_1">潘婷</label>
	</li>
	<li>
			<input group="11689" type="radio" id="11689_2" name="answers[11689].value" value="9004"  class="selection question_radio_11689"  />		<label for="11689_2">飘柔</label>
	</li>
	<li>
			<input group="11689" type="radio" id="11689_3" name="answers[11689].value" value="9005"  class="selection question_radio_11689"  />		<label for="11689_3">欧莱雅</label>
	</li>
	<li>
			<input group="11689" type="radio" id="11689_4" name="answers[11689].value" value="9006"  class="selection question_radio_11689"  />		<label for="11689_4">海飞丝</label>
	</li>
	<li>
			<input group="11689" type="radio" id="11689_5" name="answers[11689].value" value="9007"  class="selection question_radio_11689"  />		<label for="11689_5">多芬</label>
	</li>
	<li>
			<input group="11689" type="radio" id="11689_6" name="answers[11689].value" value="9008"  class="selection question_radio_11689"  />		<label for="11689_6">夏士莲</label>
	</li>
	<li>
			<input group="11689" type="radio" id="11689_7" name="answers[11689].value" value="9009"  class="selection question_radio_11689"  />		<label for="11689_7">清扬</label>
	</li>
	<li>
			<input group="11689" type="radio" id="11689_8" name="answers[11689].value" value="9010"  class="selection question_radio_11689"  />		<label for="11689_8">霸王</label>
	</li>
	<li>
			<input group="11689" type="radio" id="11689_9" name="answers[11689].value" value="9011"  class="selection question_radio_11689"  />		<label for="11689_9">追风</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11689  qc_0 radio" type="radio" name="answers[11689].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2365" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						下面哪种选择你会在将来尝试购买？（如果第8题答案为“一定不会买”可不做回答）
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11690].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11690].id" value="" id="answers[11690].id" />
<ul>
	<li>
			<input group="11690" type="radio" id="11690_0" name="answers[11690].value" value="9012"  class="selection question_radio_11690"  />		<label for="11690_0">价值8.3元的200毫升力士洗护产品</label>
	</li>
	<li>
			<input group="11690" type="radio" id="11690_1" name="answers[11690].value" value="9013"  class="selection question_radio_11690"  />		<label for="11690_1">价值22.9元的350毫升力士洗护产品</label>
	</li>
	<li>
			<input group="11690" type="radio" id="11690_2" name="answers[11690].value" value="9014"  class="selection question_radio_11690"  />		<label for="11690_2">价值51元的650毫升力士洗护产品</label>
	</li>
	<li>
			<input group="11690" type="radio" id="11690_3" name="answers[11690].value" value="9015"  class="selection question_radio_11690"  />		<label for="11690_3">不清楚会买哪种</label>
	</li>
	<li>
			<input group="11690" type="radio" id="11690_4" name="answers[11690].value" value="9016"  class="selection question_radio_11690"  />		<label for="11690_4">都不会买</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11690  qc_0 radio" type="radio" name="answers[11690].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="Submit" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = 'Mandatory questions must be filled out';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = 'Can not submit empty questionnaire form';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[




var myrules = {
	   
	   "input#11681_1": function(el){
			el.onclick = function(){
				if ($("11681_1").checked){
						Element.show($("q_2365"));
				}
			}
		}
	,
	   
	   "input#11681_2": function(el){
			el.onclick = function(){
				if ($("11681_2").checked){
						Element.show($("q_2365"));
				}
			}
		}
	,
	   
	   "input#11681_0": function(el){
			el.onclick = function(){
				if ($("11681_0").checked){
						Element.hide($("q_2365"));
				}
			}
		}
	,
	   
	   "input#11681_4": function(el){
			el.onclick = function(){
				if ($("11681_4").checked){
						Element.show($("q_2365"));
				}
			}
		}
	,
	   
	   "input#11681_3": function(el){
			el.onclick = function(){
				if ($("11681_3").checked){
						Element.show($("q_2365"));
				}
			}
		}
}

Behaviour.register(myrules);

Framework.registerAjaxSensors();
// ]]>
-->
</script>
