	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/612" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2417" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你如何评价此次产品体验分享活动?你的评分是?
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11858].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11858].id" value="" id="answers[11858].id" />
<ul>
	<li>
			<input group="11858" type="radio" id="11858_0" name="answers[11858].value" value="9183"  class="selection question_radio_11858"  />		<label for="11858_0">0</label>
	</li>
	<li>
			<input group="11858" type="radio" id="11858_1" name="answers[11858].value" value="9184"  class="selection question_radio_11858"  />		<label for="11858_1">1</label>
	</li>
	<li>
			<input group="11858" type="radio" id="11858_2" name="answers[11858].value" value="9185"  class="selection question_radio_11858"  />		<label for="11858_2">2</label>
	</li>
	<li>
			<input group="11858" type="radio" id="11858_3" name="answers[11858].value" value="9186"  class="selection question_radio_11858"  />		<label for="11858_3">3</label>
	</li>
	<li>
			<input group="11858" type="radio" id="11858_4" name="answers[11858].value" value="9187"  class="selection question_radio_11858"  />		<label for="11858_4">4</label>
	</li>
	<li>
			<input group="11858" type="radio" id="11858_5" name="answers[11858].value" value="9188"  class="selection question_radio_11858"  />		<label for="11858_5">5</label>
	</li>
	<li>
			<input group="11858" type="radio" id="11858_6" name="answers[11858].value" value="9189"  class="selection question_radio_11858"  />		<label for="11858_6">6</label>
	</li>
	<li>
			<input group="11858" type="radio" id="11858_7" name="answers[11858].value" value="9190"  class="selection question_radio_11858"  />		<label for="11858_7">7</label>
	</li>
	<li>
			<input group="11858" type="radio" id="11858_8" name="answers[11858].value" value="9191"  class="selection question_radio_11858"  />		<label for="11858_8">8</label>
	</li>
	<li>
			<input group="11858" type="radio" id="11858_9" name="answers[11858].value" value="9192"  class="selection question_radio_11858"  />		<label for="11858_9">9</label>
	</li>
	<li>
			<input group="11858" type="radio" id="11858_10" name="answers[11858].value" value="9193"  class="selection question_radio_11858"  />		<label for="11858_10">10</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11858  qc_0 radio" type="radio" name="answers[11858].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2418" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问此次产品体验分享活动那部分是你喜欢的?哪些部分是我们需要改善的?
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11859].id" value="" id="answers[11859].id" />
<textarea name="answers[11859].value" id="question_11859" cols="40" group="11859" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[11859].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2419" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						过去的三个月里，你是否还记得有多少次你有跟别人谈起过舒耐？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11860].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11860].id" value="" id="answers[11860].id" />
<ul>
	<li>
			<input group="11860" type="radio" id="11860_0" name="answers[11860].value" value="9194"  class="selection question_radio_11860"  />		<label for="11860_0">0</label>
	</li>
	<li>
			<input group="11860" type="radio" id="11860_1" name="answers[11860].value" value="9195"  class="selection question_radio_11860"  />		<label for="11860_1">1</label>
	</li>
	<li>
			<input group="11860" type="radio" id="11860_2" name="answers[11860].value" value="9196"  class="selection question_radio_11860"  />		<label for="11860_2">2</label>
	</li>
	<li>
			<input group="11860" type="radio" id="11860_3" name="answers[11860].value" value="9197"  class="selection question_radio_11860"  />		<label for="11860_3">3</label>
	</li>
	<li>
			<input group="11860" type="radio" id="11860_4" name="answers[11860].value" value="9198"  class="selection question_radio_11860"  />		<label for="11860_4">4</label>
	</li>
	<li>
			<input group="11860" type="radio" id="11860_5" name="answers[11860].value" value="9199"  class="selection question_radio_11860"  />		<label for="11860_5">5</label>
	</li>
	<li>
			<input group="11860" type="radio" id="11860_6" name="answers[11860].value" value="9200"  class="selection question_radio_11860"  />		<label for="11860_6">6</label>
	</li>
	<li>
			<input group="11860" type="radio" id="11860_7" name="answers[11860].value" value="9201"  class="selection question_radio_11860"  />		<label for="11860_7">7</label>
	</li>
	<li>
			<input group="11860" type="radio" id="11860_8" name="answers[11860].value" value="9202"  class="selection question_radio_11860"  />		<label for="11860_8">8</label>
	</li>
	<li>
			<input group="11860" type="radio" id="11860_9" name="answers[11860].value" value="9203"  class="selection question_radio_11860"  />		<label for="11860_9">9</label>
	</li>
	<li>
			<input group="11860" type="radio" id="11860_10" name="answers[11860].value" value="9204"  class="selection question_radio_11860"  />		<label for="11860_10">10</label>
	</li>
	<li>
			<input group="11860" type="radio" id="11860_11" name="answers[11860].value" value="9205"  class="selection question_radio_11860"  />		<label for="11860_11">&gt;10</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11860  qc_0 radio" type="radio" name="answers[11860].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2420" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你有多少次将这些谈话发表到网站上去?（如：BBS、论坛）
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11861].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11861].id" value="" id="answers[11861].id" />

	<select group="11861" class="selection" id="question_11861" name="answers[11861].value" title="title"  size = "1" >
	<option selected="selected" value="0">请选择</option>
<option value="9206" style=""  >0</option>
<option value="9207" style=""  >1</option>
<option value="9208" style=""  >2</option>
<option value="9209" style=""  >3</option>
<option value="9210" style=""  >4</option>
<option value="9211" style=""  >5</option>
<option value="9212" style=""  >6</option>
<option value="9213" style=""  >7</option>
<option value="9214" style=""  >8</option>
<option value="9215" style=""  >9</option>
<option value="9216" style=""  >10</option>
<option value="9217" style=""  >&gt;10</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2421" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你是否愿意向你的朋友推荐舒耐的产品？
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11862].value" ></span>
<input type="hidden" name="answers[11862].id" value="" id="answers[11862].id" />
<table>
<tr>

<td>

<div class="left-label">绝对不会</div>
	<table class="rating-table" style="width:50%">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11862].value" value="0" id="11862_0" group="11862" class="question_radio_11862 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11862].value" value="1" id="11862_1" group="11862" class="question_radio_11862 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11862].value" value="2" id="11862_2" group="11862" class="question_radio_11862 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11862].value" value="3" id="11862_3" group="11862" class="question_radio_11862 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11862].value" value="4" id="11862_4" group="11862" class="question_radio_11862 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11862].value" value="5" id="11862_5" group="11862" class="question_radio_11862 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11862].value" value="6" id="11862_6" group="11862" class="question_radio_11862 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11862].value" value="7" id="11862_7" group="11862" class="question_radio_11862 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11862].value" value="8" id="11862_8" group="11862" class="question_radio_11862 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11862].value" value="9" id="11862_9" group="11862" class="question_radio_11862 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11862].value" value="10" id="11862_10" group="11862" class="question_radio_11862 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">肯定会</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11862].value" value="" id="answers[11862].value" class="q_11862 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2203" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						为什么？
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[11863].id" value="" id="answers[11863].id" />
<textarea name="answers[11863].value" id="question_11863" cols="40" group="11863" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[11863].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2422" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						如果你参加了腋下测试并收到了包含10瓶舒耐的礼盒，你与朋友们分享了其中的几瓶？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11864].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11864].id" value="" id="answers[11864].id" />
<ul>
	<li>
			<input group="11864" type="radio" id="11864_0" name="answers[11864].value" value="9218"  class="selection question_radio_11864"  />		<label for="11864_0">没有收到第二个礼盒</label>
	</li>
	<li>
			<input group="11864" type="radio" id="11864_1" name="answers[11864].value" value="9219"  class="selection question_radio_11864"  />		<label for="11864_1">一个也没分享</label>
	</li>
	<li>
			<input group="11864" type="radio" id="11864_2" name="answers[11864].value" value="9220"  class="selection question_radio_11864"  />		<label for="11864_2">1</label>
	</li>
	<li>
			<input group="11864" type="radio" id="11864_3" name="answers[11864].value" value="9221"  class="selection question_radio_11864"  />		<label for="11864_3">2</label>
	</li>
	<li>
			<input group="11864" type="radio" id="11864_4" name="answers[11864].value" value="9222"  class="selection question_radio_11864"  />		<label for="11864_4">3</label>
	</li>
	<li>
			<input group="11864" type="radio" id="11864_5" name="answers[11864].value" value="9223"  class="selection question_radio_11864"  />		<label for="11864_5">4</label>
	</li>
	<li>
			<input group="11864" type="radio" id="11864_6" name="answers[11864].value" value="9224"  class="selection question_radio_11864"  />		<label for="11864_6">5</label>
	</li>
	<li>
			<input group="11864" type="radio" id="11864_7" name="answers[11864].value" value="9225"  class="selection question_radio_11864"  />		<label for="11864_7">6</label>
	</li>
	<li>
			<input group="11864" type="radio" id="11864_8" name="answers[11864].value" value="9226"  class="selection question_radio_11864"  />		<label for="11864_8">7</label>
	</li>
	<li>
			<input group="11864" type="radio" id="11864_9" name="answers[11864].value" value="9227"  class="selection question_radio_11864"  />		<label for="11864_9">8</label>
	</li>
	<li>
			<input group="11864" type="radio" id="11864_10" name="answers[11864].value" value="9228"  class="selection question_radio_11864"  />		<label for="11864_10">9</label>
	</li>
	<li>
			<input group="11864" type="radio" id="11864_11" name="answers[11864].value" value="9229"  class="selection question_radio_11864"  />		<label for="11864_11">分享了全部</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11864  qc_0 radio" type="radio" name="answers[11864].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2171" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						目前你对舒耐的看法是什么？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11865].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11865].id" value="" id="answers[11865].id" />
<ul>
	<li>
			<input group="11865" type="radio" id="11865_0" name="answers[11865].value" value="8422"  class="selection question_radio_11865"  />		<label for="11865_0">很负面</label>
	</li>
	<li>
			<input group="11865" type="radio" id="11865_1" name="answers[11865].value" value="8423"  class="selection question_radio_11865"  />		<label for="11865_1">有点负面</label>
	</li>
	<li>
			<input group="11865" type="radio" id="11865_2" name="answers[11865].value" value="8424"  class="selection question_radio_11865"  />		<label for="11865_2">中立</label>
	</li>
	<li>
			<input group="11865" type="radio" id="11865_3" name="answers[11865].value" value="8425"  class="selection question_radio_11865"  />		<label for="11865_3">有点正面</label>
	</li>
	<li>
			<input group="11865" type="radio" id="11865_4" name="answers[11865].value" value="8426"  class="selection question_radio_11865"  />		<label for="11865_4">很正面</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11865  qc_0 radio" type="radio" name="answers[11865].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2423" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在过去的三个月内，你有购买过舒耐吗？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11866].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11866].id" value="" id="answers[11866].id" />
<ul>
	<li>
			<input group="11866" type="radio" id="11866_0" name="answers[11866].value" value="9230"  class="selection question_radio_11866"  />		<label for="11866_0">有</label>
	</li>
	<li>
			<input group="11866" type="radio" id="11866_1" name="answers[11866].value" value="9231"  class="selection question_radio_11866"  />		<label for="11866_1">没有</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11866  qc_0 radio" type="radio" name="answers[11866].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2424" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在过去3个月，你总共买过多少瓶舒耐?
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11867].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11867].id" value="" id="answers[11867].id" />
<ul>
	<li>
			<input group="11867" type="radio" id="11867_0" name="answers[11867].value" value="9232"  class="selection question_radio_11867"  />		<label for="11867_0">&gt;3</label>
	</li>
	<li>
			<input group="11867" type="radio" id="11867_1" name="answers[11867].value" value="9233"  class="selection question_radio_11867"  />		<label for="11867_1">3</label>
	</li>
	<li>
			<input group="11867" type="radio" id="11867_2" name="answers[11867].value" value="9234"  class="selection question_radio_11867"  />		<label for="11867_2">2</label>
	</li>
	<li>
			<input group="11867" type="radio" id="11867_3" name="answers[11867].value" value="9235"  class="selection question_radio_11867"  />		<label for="11867_3">1</label>
	</li>
	<li>
			<input group="11867" type="radio" id="11867_4" name="answers[11867].value" value="9236"  class="selection question_radio_11867"  />		<label for="11867_4">0</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11867  qc_0 radio" type="radio" name="answers[11867].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2425" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						将来你会购买舒耐吗？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11868].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11868].id" value="" id="answers[11868].id" />
<ul>
	<li>
			<input group="11868" type="radio" id="11868_0" name="answers[11868].value" value="9237"  class="selection question_radio_11868"  />		<label for="11868_0">不可能</label>
	</li>
	<li>
			<input group="11868" type="radio" id="11868_1" name="answers[11868].value" value="9238"  class="selection question_radio_11868"  />		<label for="11868_1">有点不可能</label>
	</li>
	<li>
			<input group="11868" type="radio" id="11868_2" name="answers[11868].value" value="9239"  class="selection question_radio_11868"  />		<label for="11868_2">中立</label>
	</li>
	<li>
			<input group="11868" type="radio" id="11868_3" name="answers[11868].value" value="9240"  class="selection question_radio_11868"  />		<label for="11868_3">可能</label>
	</li>
	<li>
			<input group="11868" type="radio" id="11868_4" name="answers[11868].value" value="9241"  class="selection question_radio_11868"  />		<label for="11868_4">很可能</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11868  qc_0 radio" type="radio" name="answers[11868].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
 <div id="q_2434" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问针对下述品牌/产品特征,你将如何评价?(1= 非常差 - 5=非常好）
					</div>
				</td>
</tr>
<tr>
		  <div id="q_2426" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table" style="margin-left:50px;">
			<tr>
				<td width=50% valign="top">
					<div class="">
						芬芳的味道
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11869].value" ></span>
<input type="hidden" name="answers[11869].id" value="" id="answers[11869].id" />
<table>
<tr>

<td>

<div class="left-label"></div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11869].value" value="1" id="11869_1" group="11869" class="question_radio_11869 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11869].value" value="2" id="11869_2" group="11869" class="question_radio_11869 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11869].value" value="3" id="11869_3" group="11869" class="question_radio_11869 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11869].value" value="4" id="11869_4" group="11869" class="question_radio_11869 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11869].value" value="5" id="11869_5" group="11869" class="question_radio_11869 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label"></div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11869].value" value="" id="answers[11869].value" class="q_11869 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2427" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table" style="margin-left:50px;">
			<tr>
				<td width=50% valign="top">
					<div class="">
						负担得起的价格
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11870].value" ></span>
<input type="hidden" name="answers[11870].id" value="" id="answers[11870].id" />
<table>
<tr>

<td>

<div class="left-label"></div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11870].value" value="1" id="11870_1" group="11870" class="question_radio_11870 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11870].value" value="2" id="11870_2" group="11870" class="question_radio_11870 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11870].value" value="3" id="11870_3" group="11870" class="question_radio_11870 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11870].value" value="4" id="11870_4" group="11870" class="question_radio_11870 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11870].value" value="5" id="11870_5" group="11870" class="question_radio_11870 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label"></div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11870].value" value="" id="answers[11870].value" class="q_11870 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2428" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table" style="margin-left:50px;">
			<tr>
				<td width=50% valign="top">
					<div class="">
						效力
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11871].value" ></span>
<input type="hidden" name="answers[11871].id" value="" id="answers[11871].id" />
<table>
<tr>

<td>

<div class="left-label"></div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11871].value" value="1" id="11871_1" group="11871" class="question_radio_11871 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11871].value" value="2" id="11871_2" group="11871" class="question_radio_11871 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11871].value" value="3" id="11871_3" group="11871" class="question_radio_11871 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11871].value" value="4" id="11871_4" group="11871" class="question_radio_11871 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11871].value" value="5" id="11871_5" group="11871" class="question_radio_11871 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label"></div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11871].value" value="" id="answers[11871].value" class="q_11871 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2429" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table" style="margin-left:50px;">
			<tr>
				<td width=50% valign="top">
					<div class="">
						使我感到清新
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11872].value" ></span>
<input type="hidden" name="answers[11872].id" value="" id="answers[11872].id" />
<table>
<tr>

<td>

<div class="left-label"></div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11872].value" value="1" id="11872_1" group="11872" class="question_radio_11872 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11872].value" value="2" id="11872_2" group="11872" class="question_radio_11872 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11872].value" value="3" id="11872_3" group="11872" class="question_radio_11872 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11872].value" value="4" id="11872_4" group="11872" class="question_radio_11872 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11872].value" value="5" id="11872_5" group="11872" class="question_radio_11872 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label"></div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11872].value" value="" id="answers[11872].value" class="q_11872 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2430" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table" style="margin-left:50px;">
			<tr>
				<td width=50% valign="top">
					<div class="">
						著名品牌
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11873].value" ></span>
<input type="hidden" name="answers[11873].id" value="" id="answers[11873].id" />
<table>
<tr>

<td>

<div class="left-label"></div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11873].value" value="1" id="11873_1" group="11873" class="question_radio_11873 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11873].value" value="2" id="11873_2" group="11873" class="question_radio_11873 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11873].value" value="3" id="11873_3" group="11873" class="question_radio_11873 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11873].value" value="4" id="11873_4" group="11873" class="question_radio_11873 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11873].value" value="5" id="11873_5" group="11873" class="question_radio_11873 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label"></div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11873].value" value="" id="answers[11873].value" class="q_11873 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2431" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table" style="margin-left:50px;">
			<tr>
				<td width=50% valign="top">
					<div class="">
						使我有自信
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[11874].value" ></span>
<input type="hidden" name="answers[11874].id" value="" id="answers[11874].id" />
<table>
<tr>

<td>

<div class="left-label"></div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[11874].value" value="1" id="11874_1" group="11874" class="question_radio_11874 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11874].value" value="2" id="11874_2" group="11874" class="question_radio_11874 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11874].value" value="3" id="11874_3" group="11874" class="question_radio_11874 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[11874].value" value="4" id="11874_4" group="11874" class="question_radio_11874 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[11874].value" value="5" id="11874_5" group="11874" class="question_radio_11874 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label"></div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[11874].value" value="" id="answers[11874].value" class="q_11874 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2432" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在收到舒耐礼盒后，你使用香体抑汗产品的频率？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11875].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11875].id" value="" id="answers[11875].id" />
<ul>
	<li>
			<input group="11875" type="radio" id="11875_0" name="answers[11875].value" value="9242"  class="selection question_radio_11875"  />		<label for="11875_0">从来没用过</label>
	</li>
	<li>
			<input group="11875" type="radio" id="11875_1" name="answers[11875].value" value="9243"  class="selection question_radio_11875"  />		<label for="11875_1">一周1至2次</label>
	</li>
	<li>
			<input group="11875" type="radio" id="11875_2" name="answers[11875].value" value="9244"  class="selection question_radio_11875"  />		<label for="11875_2">一周3至5次</label>
	</li>
	<li>
			<input group="11875" type="radio" id="11875_3" name="answers[11875].value" value="9245"  class="selection question_radio_11875"  />		<label for="11875_3">每天</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11875  qc_0 radio" type="radio" name="answers[11875].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2433" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你最近使用香体抑汗产品的频率？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[11876].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[11876].id" value="" id="answers[11876].id" />
<ul>
	<li>
			<input group="11876" type="radio" id="11876_0" name="answers[11876].value" value="9246"  class="selection question_radio_11876"  />		<label for="11876_0">从来没用过</label>
	</li>
	<li>
			<input group="11876" type="radio" id="11876_1" name="answers[11876].value" value="9247"  class="selection question_radio_11876"  />		<label for="11876_1">一周1至2次</label>
	</li>
	<li>
			<input group="11876" type="radio" id="11876_2" name="answers[11876].value" value="9248"  class="selection question_radio_11876"  />		<label for="11876_2">一周3至5次</label>
	</li>
	<li>
			<input group="11876" type="radio" id="11876_3" name="answers[11876].value" value="9249"  class="selection question_radio_11876"  />		<label for="11876_3">每天</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_11876  qc_0 radio" type="radio" name="answers[11876].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="提交" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
	    	jQuery("#check-alert-dialog .content").html(html);
	        jQuery("#check-alert-dialog").dialog('open');
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '提交失败：不能提交空报告';
			 jQuery("#check-alert-dialog .content").html(html);
		     jQuery("#check-alert-dialog").dialog('open');
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

// ]]>
-->
</script>
