	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/629" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />
<input type="hidden" name="surveyId" value="OgTm8t7eUn8F"/>

<div class="mandatory"><span style="color: red;">* </span>- It is mandatory</div>
<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2560" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你有孩子吗？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12170].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12170].id" value="" id="answers[12170].id" />
<ul>
	<li>
			<input group="12170" type="radio" id="12170_0" name="answers[12170].value" value="9740"  class="selection question_radio_12170"  onclick="isOrNo(this.value)"/>		<label for="12170_0">是</label>
	</li>
	<li>
			<input group="12170" type="radio" id="12170_1" name="answers[12170].value" value="9741"  class="selection question_radio_12170"  onclick="isOrNo(this.value)"/>		<label for="12170_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12170  qc_0 radio" type="radio" name="answers[12170].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
	function isOrNo(val){
		if(val==9740){
			document.getElementById("all_div").style.display="";
			document.getElementById("text_div").style.display="none";
			
		}else{
			
			document.getElementById("all_div").style.display="none";
			document.getElementById("text_div").style.display="";
			document.getElementById("question_12185").value = 'none';
			document.getElementById("question_12186").value = 'none';
			document.getElementById("question_12187").value = 'none';
		}
	}
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
<div id="text_div" style="display:none"><span style="color:red">很遗憾，这个调查是针对已经有孩子的父母,感谢你对星星火的支持，点击提交您同样可以获得100积分！</span></div>
<div id="all_div" style="display:none">
		  <div id="q_2561" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的孩子多大了？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12171].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12171].id" value="" id="answers[12171].id" />
<ul>
	<li>
			<input group="12171" type="radio" id="12171_0" name="answers[12171].value" value="9742"  class="selection question_radio_12171"  />		<label for="12171_0">3岁以下</label>
	</li>
	<li>
			<input group="12171" type="radio" id="12171_1" name="answers[12171].value" value="9743"  class="selection question_radio_12171"  />		<label for="12171_1">3-6岁</label>
	</li>
	<li>
			<input group="12171" type="radio" id="12171_2" name="answers[12171].value" value="9744"  class="selection question_radio_12171"  />		<label for="12171_2">7-10岁</label>
	</li>
	<li>
			<input group="12171" type="radio" id="12171_3" name="answers[12171].value" value="9745"  class="selection question_radio_12171"  />		<label for="12171_3">11-14岁</label>
	</li>
	<li>
			<input group="12171" type="radio" id="12171_4" name="answers[12171].value" value="9746"  class="selection question_radio_12171"  />		<label for="12171_4">大于14岁</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12171  qc_0 radio" type="radio" name="answers[12171].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2562" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你觉得孩子在同龄人中是佼佼者有多重要?
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[12172].value" ></span>
<input type="hidden" name="answers[12172].id" value="" id="answers[12172].id" />
<table>
<tr>

<td>

<div class="left-label">不重要</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[12172].value" value="1" id="12172_1" group="12172" class="question_radio_12172 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12172].value" value="2" id="12172_2" group="12172" class="question_radio_12172 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12172].value" value="3" id="12172_3" group="12172" class="question_radio_12172 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12172].value" value="4" id="12172_4" group="12172" class="question_radio_12172 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[12172].value" value="5" id="12172_5" group="12172" class="question_radio_12172 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">很重要</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[12172].value" value="" id="answers[12172].value" class="q_12172 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2563" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你觉得以下哪些是孩子比同龄人出色的必备技能?(多选)
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12173].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12173].id" value="" id="answers[12173].id" />




<span id="hint_12173">
</span>
<ul>
	<li>
			<input group="12173" class="question_radio_12173 selection" type="checkbox" id="12173_0" name="answers[12173].value" value="9747" 	onclick=" "/>		<label for="12173_0">电脑技能</label>
	</li>
	<li>
			<input group="12173" class="question_radio_12173 selection" type="checkbox" id="12173_1" name="answers[12173].value" value="9748" 	onclick=" "/>		<label for="12173_1">社交能力</label>
	</li>
	<li>
			<input group="12173" class="question_radio_12173 selection" type="checkbox" id="12173_2" name="answers[12173].value" value="9749" 	onclick=" "/>		<label for="12173_2">语言能力</label>
	</li>
	<li>
			<input group="12173" class="question_radio_12173 selection" type="checkbox" id="12173_3" name="answers[12173].value" value="9750" 	onclick=" "/>		<label for="12173_3">数学能力</label>
	</li>
	<li>
			<input group="12173" class="question_radio_12173 selection" type="checkbox" id="12173_4" name="answers[12173].value" value="9751" 	onclick=" "/>		<label for="12173_4">音乐才能</label>
	</li>
	<li>
			<input group="12173" class="question_radio_12173 selection" type="checkbox" id="12173_5" name="answers[12173].value" value="9752" 	onclick=" "/>		<label for="12173_5">开放的思维</label>
	</li>
		<li>
			<input class="question_radio_12173" type="checkbox" id="12173_other"   value="0" onclick="showOtherValueInputInCheckBox(this)" />			<label for="12173_other">其他</label>
			<input id="12173_other_input" type="text" name="answers[12173].otherValue" value="" style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2564" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的孩子在周末参加的课程或活动有哪些?(多选)
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12174].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12174].id" value="" id="answers[12174].id" />




<span id="hint_12174">
</span>
<ul>
	<li>
			<input group="12174" class="question_radio_12174 selection" type="checkbox" id="12174_0" name="answers[12174].value" value="9753" 	onclick=" "/>		<label for="12174_0">音乐课程</label>
	</li>
	<li>
			<input group="12174" class="question_radio_12174 selection" type="checkbox" id="12174_1" name="answers[12174].value" value="9754" 	onclick=" "/>		<label for="12174_1">周日去学校补课</label>
	</li>
	<li>
			<input group="12174" class="question_radio_12174 selection" type="checkbox" id="12174_2" name="answers[12174].value" value="9755" 	onclick=" "/>		<label for="12174_2">舞蹈课</label>
	</li>
	<li>
			<input group="12174" class="question_radio_12174 selection" type="checkbox" id="12174_3" name="answers[12174].value" value="9756" 	onclick=" "/>		<label for="12174_3">读很多的书</label>
	</li>
	<li>
			<input group="12174" class="question_radio_12174 selection" type="checkbox" id="12174_4" name="answers[12174].value" value="9757" 	onclick=" "/>		<label for="12174_4">旅游</label>
	</li>
		<li>
			<input class="question_radio_12174" type="checkbox" id="12174_other"   value="0" onclick="showOtherValueInputInCheckBox(this)" />			<label for="12174_other">其他</label>
			<input id="12174_other_input" type="text" name="answers[12174].otherValue" value="" style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2565" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的孩子平均每天花在课后家庭作业上的时间是多少?
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12175].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12175].id" value="" id="answers[12175].id" />
<ul>
	<li>
			<input group="12175" type="radio" id="12175_0" name="answers[12175].value" value="9758"  class="selection question_radio_12175"  />		<label for="12175_0">少于30分钟</label>
	</li>
	<li>
			<input group="12175" type="radio" id="12175_1" name="answers[12175].value" value="9759"  class="selection question_radio_12175"  />		<label for="12175_1">30-60分钟</label>
	</li>
	<li>
			<input group="12175" type="radio" id="12175_2" name="answers[12175].value" value="9760"  class="selection question_radio_12175"  />		<label for="12175_2">60-90分钟</label>
	</li>
	<li>
			<input group="12175" type="radio" id="12175_3" name="answers[12175].value" value="9761"  class="selection question_radio_12175"  />		<label for="12175_3">90-120分钟</label>
	</li>
	<li>
			<input group="12175" type="radio" id="12175_4" name="answers[12175].value" value="9762"  class="selection question_radio_12175"  />		<label for="12175_4">2-3小时</label>
	</li>
	<li>
			<input group="12175" type="radio" id="12175_5" name="answers[12175].value" value="9763"  class="selection question_radio_12175"  />		<label for="12175_5">多于3小时</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12175  qc_0 radio" type="radio" name="answers[12175].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2566" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你觉得孩子可以说一口流利的英语有多重要？
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[12176].value" ></span>
<input type="hidden" name="answers[12176].id" value="" id="answers[12176].id" />
<table>
<tr>

<td>

<div class="left-label">不重要</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[12176].value" value="1" id="12176_1" group="12176" class="question_radio_12176 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12176].value" value="2" id="12176_2" group="12176" class="question_radio_12176 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12176].value" value="3" id="12176_3" group="12176" class="question_radio_12176 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12176].value" value="4" id="12176_4" group="12176" class="question_radio_12176 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12176].value" value="5" id="12176_5" group="12176" class="question_radio_12176 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12176].value" value="6" id="12176_6" group="12176" class="question_radio_12176 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12176].value" value="7" id="12176_7" group="12176" class="question_radio_12176 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12176].value" value="8" id="12176_8" group="12176" class="question_radio_12176 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12176].value" value="9" id="12176_9" group="12176" class="question_radio_12176 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[12176].value" value="10" id="12176_10" group="12176" class="question_radio_12176 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">很重要</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[12176].value" value="" id="answers[12176].value" class="q_12176 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2567" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请解释你觉得重要或不重要的原因?
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[12177].id" value="" id="answers[12177].id" />
<textarea name="answers[12177].value" id="question_12177" cols="40" group="12177" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[12177].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2568" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你准备要送你的孩子去参与一些英语课程吗？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12178].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12178].id" value="" id="answers[12178].id" />
<ul>
	<li>
			<input group="12178" type="radio" id="12178_0" name="answers[12178].value" value="9764"  class="selection question_radio_12178" onclick="showOrHide(this.value)" />		<label for="12178_0">是，三个月之内</label>
	</li>
	<li>
			<input group="12178" type="radio" id="12178_1" name="answers[12178].value" value="9765"  class="selection question_radio_12178"  onclick="showOrHide(this.value)" />		<label for="12178_1">是，半年之内</label>
	</li>
	<li>
			<input group="12178" type="radio" id="12178_2" name="answers[12178].value" value="9766"  class="selection question_radio_12178"  onclick="showOrHide(this.value)" />		<label for="12178_2">是，九个月之内</label>
	</li>
	<li>
			<input group="12178" type="radio" id="12178_3" name="answers[12178].value" value="9767"  class="selection question_radio_12178"  onclick="showOrHide(this.value)" />		<label for="12178_3">是，一年之内</label>
	</li>
	<li>
			<input group="12178" type="radio" id="12178_3" name="answers[12178].value" value="9793"  class="selection question_radio_12178"  onclick="showOrHide(this.value)" />		<label for="12178_4">是，但要到明年之后</label>
	</li>
	<li>
			<input group="12178" type="radio" id="12178_3" name="answers[12178].value" value="9796"  class="selection question_radio_12178"  onclick="showOrHide(this.value)" />		<label for="12178_5">我的孩子已经在上英语课了</label>
	</li>
	<li>
			<input group="12178" type="radio" id="12178_5" name="answers[12178].value" value="9797"  class="selection question_radio_12178"  onclick="showOrHide(this.value)" />		<label for="12178_6">我还没有这个计划</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12178  qc_0 radio" type="radio" name="answers[12178].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide(val){
	if(val==9797){
		document.getElementById("q_2569").style.display="none";
	}else{
		document.getElementById("q_2569").style.display="";
	}
}
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2569" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你打算送孩子去参与英语课程最重要的原因是什么？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12179].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12179].id" value="" id="answers[12179].id" />
<ul>
	<li>
			<input group="12179" type="radio" id="12179_0" name="answers[12179].value" value="9768"  class="selection question_radio_12179" onclick="showOtherValueInputInRadio(this)" />		<label for="12179_0">职业发展机会</label>
	</li>
	<li>
			<input group="12179" type="radio" id="12179_1" name="answers[12179].value" value="9769"  class="selection question_radio_12179" onclick="showOtherValueInputInRadio(this)" />		<label for="12179_1">更好的了解世界</label>
	</li>
	<li>
			<input group="12179" type="radio" id="12179_2" name="answers[12179].value" value="9770"  class="selection question_radio_12179" onclick="showOtherValueInputInRadio(this)" />		<label for="12179_2">沟通能力的提升</label>
	</li>
	<li>
			<input group="12179" type="radio" id="12179_3" name="answers[12179].value" value="9771"  class="selection question_radio_12179" onclick="showOtherValueInputInRadio(this)" />		<label for="12179_3">领先于同龄人</label>
	</li>
		<li>
			<input type="radio" id="12179_other" name="answers[12179].value" value="0" class="question_radio_12179" onclick="showOtherValueInputInRadio(this)" />			<label for="12179_other">其他</label>
			<input id="12179_other_input" type="text" name="answers[12179].otherValue" value=""  style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12179  qc_0 radio" type="radio" name="answers[12179].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2570" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你有听过以下哪些英语培训学校？(多选)
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12180].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12180].id" value="" id="answers[12180].id" />




<span id="hint_12180">
</span>
<ul>
	<li>
			<input group="12180" class="question_radio_12180 selection" type="checkbox" id="12180_0" name="answers[12180].value" value="9772" 	onclick=" "/>		<label for="12180_0">迪士尼英语</label>
	</li>
	<li>
			<input group="12180" class="question_radio_12180 selection" type="checkbox" id="12180_1" name="answers[12180].value" value="9773" 	onclick=" "/>		<label for="12180_1">韦博英语</label>
	</li>
	<li>
			<input group="12180" class="question_radio_12180 selection" type="checkbox" id="12180_2" name="answers[12180].value" value="9774" 	onclick=" "/>		<label for="12180_2">新东方</label>
	</li>
	<li>
			<input group="12180" class="question_radio_12180 selection" type="checkbox" id="12180_3" name="answers[12180].value" value="9775" 	onclick=" "/>		<label for="12180_3">英孚</label>
	</li>
	<li>
			<input group="12180" class="question_radio_12180 selection" type="checkbox" id="12180_4" name="answers[12180].value" value="9776" 	onclick=" "/>		<label for="12180_4">德高教育</label>
	</li>
		<li>
			<input class="question_radio_12180" type="checkbox" id="12180_other"   value="0" onclick="showOtherValueInputInCheckBox(this)" />			<label for="12180_other">其他</label>
			<input id="12180_other_input" type="text" name="answers[12180].otherValue" value="" style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2571" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你觉得下列学校哪个是英语培训中最好的？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12181].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12181].id" value="" id="answers[12181].id" />




<span id="hint_12181">
</span>
<ul>
	<li>
			<input group="12181" class="question_radio_12181 selection" type="radio" id="12181_0" name="answers[12181].value" value="9777" 	onclick="showOtherValueInputInRadio(this) "/>		<label for="12181_0">迪士尼英语</label>
	</li>
	<li>
			<input group="12181" class="question_radio_12181 selection" type="radio" id="12181_1" name="answers[12181].value" value="9778" 	onclick="showOtherValueInputInRadio(this) "/>		<label for="12181_1">韦博英语</label>
	</li>
	<li>
			<input group="12181" class="question_radio_12181 selection" type="radio" id="12181_2" name="answers[12181].value" value="9779" 	onclick="showOtherValueInputInRadio(this)"/>		<label for="12181_2">新东方</label>
	</li>
	<li>
			<input group="12181" class="question_radio_12181 selection" type="radio" id="12181_3" name="answers[12181].value" value="9780" 	onclick="showOtherValueInputInRadio(this)"/>		<label for="12181_3">英孚</label>
	</li>
	<li>
			<input group="12181" class="question_radio_12181 selection" type="radio" id="12181_4" name="answers[12181].value" value="9781" 	onclick="showOtherValueInputInRadio(this)"/>		<label for="12181_4">德高教育</label>
	</li>
		<li>
			<input class="question_radio_12181" type="radio" id="12181_other"   value="0" onclick="showOtherValueInputInRadio(this)" name="answers[12181].value" />			<label for="12181_other">其他</label>
			<input id="12181_other_input" type="text" name="answers[12181].otherValue" value="" style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2572" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的家庭月收入是多少？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12182].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12182].id" value="" id="answers[12182].id" />
<ul>
	<li>
			<input group="12182" type="radio" id="12182_0" name="answers[12182].value" value="9782"  class="selection question_radio_12182"  />		<label for="12182_0">少于￥3,000/月</label>
	</li>
	<li>
			<input group="12182" type="radio" id="12182_1" name="answers[12182].value" value="9783"  class="selection question_radio_12182"  />		<label for="12182_1">￥3,000～5,000/月</label>
	</li>
	<li>
			<input group="12182" type="radio" id="12182_2" name="answers[12182].value" value="9784"  class="selection question_radio_12182"  />		<label for="12182_2">￥5,000～7,000/月</label>
	</li>
	<li>
			<input group="12182" type="radio" id="12182_3" name="answers[12182].value" value="9785"  class="selection question_radio_12182"  />		<label for="12182_3">￥7,000～10,000/月</label>
	</li>
	<li>
			<input group="12182" type="radio" id="12182_4" name="answers[12182].value" value="9786"  class="selection question_radio_12182"  />		<label for="12182_4">￥10,000～15,000/月</label>
	</li>
	<li>
			<input group="12182" type="radio" id="12182_5" name="answers[12182].value" value="9787"  class="selection question_radio_12182"  />		<label for="12182_5">￥15,000～20,000/月</label>
	</li>
	<li>
			<input group="12182" type="radio" id="12182_6" name="answers[12182].value" value="9788"  class="selection question_radio_12182"  />		<label for="12182_6">多于20,000/月</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12182  qc_0 radio" type="radio" name="answers[12182].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2573" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你在在哪个城市居住？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12183].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12183].id" value="" id="answers[12183].id" />

	<select group="12183" class="selection" id="question_12183" name="answers[12183].value" title="title"  size = "1" onchange="createElementOptions(this.value,this)">
	<option selected="selected" value="0">请选择</option>
<option value="9789" style="" >上海</option>
<option value="9790" style="" >北京</option>
<option value="9791" style="" >广州</option>
<option value="9792" style="" >深圳</option>
		<option id="12183_other" value="10" onclick="createElementOptions(this.value)" >其他</option>
	</select> 
	
	<select id="region_shanghai" class="selection" style="display:none" onchange="fillValueToText(this.value)" >
		<option selected="selected" value="0">请选择</option>
		<option value="黄浦区" >黄浦区</option>
		<option value="卢湾区" >卢湾区</option>
		<option value="徐汇区" >徐汇区</option>
		<option value="长宁区" >长宁区</option>
		<option value="静安区" >静安区</option>
		<option value="普陀区" >普陀区</option>
		<option value="闸北区" >闸北区</option>
		<option value="虹口区" >虹口区</option>
		<option value="杨浦区" >杨浦区</option>
		<option value="浦东新区" >浦东新区</option>
		<option value="宝山区" >宝山区</option>
		<option value="闵行区" >闵行区</option>
		<option value="嘉定区" >嘉定区</option>
		<option value="金山区" >金山区</option>
		<option value="松江区" >松江区</option>
		<option value="青浦区" >青浦区</option>
		<option value="奉贤区" >奉贤区</option>
		<option value="南汇区" >南汇区</option>
		<option value="崇明" >崇明</option>
	</select>
	<select id="region_beijing" class="selection" style="display:none" onchange="fillValueToText(this.value)">
		<option selected="selected" value="0">请选择</option>
		<option value="东城区" onclick="">东城区</option>
		<option value="西城区" >西城区</option>
		<option value="崇文区" >崇文区</option>
		<option value="宣武区" >宣武区</option>
		<option value="朝阳区" >朝阳区</option>
		<option value="海淀区" >海淀区</option>
		<option value="丰台区" >丰台区</option>
		<option value="石景山区" >石景山区</option>
		<option value="房山区" >房山区</option>
		<option value="通州区" >通州区</option>
		<option value="顺义区" >顺义区</option>
		<option value="大兴区" >大兴区</option>
		<option value="昌平区" >昌平区</option>
		<option value="平谷区" >平谷区</option>
		<option value="怀柔区" >怀柔区</option>
		<option value="门头沟区" >门头沟区</option>
		<option value="密云县" >密云县</option>
		<option value="延庆县" >延庆县</option>
	</select>
	<select id="region_guangzhou" class="selection" style="display:none" onchange="fillValueToText(this.value)" >
		<option selected="selected" value="0">请选择</option>
		<option value="越秀区" >越秀区</option>
		<option value="海珠区" >海珠区</option>
		<option value="荔湾区" >荔湾区</option>
		<option value="天河区" >天河区</option>
		<option value="白云区" >白云区</option>
		<option value="黄埔区" >黄埔区</option>
		<option value="花都区" >花都区</option>
		<option value="番禺区" >番禺区</option>
		<option value="萝岗区" >萝岗区</option>
		<option value="南沙区" >南沙区</option>
		<option value="从化市" >从化市</option>
		<option value="增城市" >增城市</option>
	</select>
	<select id="region_shenzhen" class="selection" style="display:none"  onchange="fillValueToText(this.value)">
		<option selected="selected" value="0">请选择</option>
		<option value="福田区 " >福田区 </option>
		<option value="罗湖区 " >罗湖区 </option>
		<option value="南山区  " >南山区  </option>
		<option value="盐田区  " >盐田区  </option>
		<option value="宝安区  " >宝安区  </option>
		<option value="龙岗区  " >龙岗区  </option>
	</select>
	
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>
<tr>
	<td><input id="question_12183_other" style="display:none;" type="text" name="answers[12183].otherValue" value=""/></td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function createElementOptions(val,obj){
	if(val==9789){
		document.getElementById("region_shanghai").style.display="";
		document.getElementById("region_beijing").style.display="none";
		document.getElementById("region_guangzhou").style.display="none";
		document.getElementById("region_shenzhen").style.display="none";
		showOtherValueInputInSelect(obj);
	}else if(val==9790){
		document.getElementById("region_shanghai").style.display="none";
		document.getElementById("region_beijing").style.display="";
		document.getElementById("region_guangzhou").style.display="none";
		document.getElementById("region_shenzhen").style.display="none";
		showOtherValueInputInSelect(obj);
	}else if(val==9791){
		document.getElementById("region_shanghai").style.display="none";
		document.getElementById("region_beijing").style.display="none";
		document.getElementById("region_guangzhou").style.display="";
		document.getElementById("region_shenzhen").style.display="none";
		showOtherValueInputInSelect(obj);
	}else if(val==9792){
		document.getElementById("region_shanghai").style.display="none";
		document.getElementById("region_beijing").style.display="none";
		document.getElementById("region_guangzhou").style.display="none";
		document.getElementById("region_shenzhen").style.display="";
		showOtherValueInputInSelect(obj);
	}else{
		document.getElementById("region_shanghai").style.display="none";
		document.getElementById("region_beijing").style.display="none";
		document.getElementById("region_guangzhou").style.display="none";
		document.getElementById("region_shenzhen").style.display="none";
		document.getElementById("question_12184").value="";
		showOtherValueInputInSelect(obj);
	}
}
function fillValueToText(val){
	document.getElementById("question_12184").value=val;
}
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2574" style="margin-bottom:0px; display:none" class="question-even question-area" >
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						哪个区?
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[12184].id" value="" id="answers[12184].id" />
<input type="text" name="answers[12184].value" value="" id="question_12184" group="12184" class="input-text" />

<span class="error-content" id="err_answers[12184].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("12185");
// ]]>
-->
</script>
		  <div id="q_1969" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						姓名
							<span style="color:red">*</span>
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[12185].id" value="" id="answers[12185].id" />
<input type="text" name="answers[12185].value" value="" id="question_12185" group="12185" class="input-text" />

<span class="error-content" id="err_answers[12185].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("12186");
// ]]>
-->
</script>
		  <div id="q_2095" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						邮箱
							<span style="color:red">*</span>
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[12186].id" value="" id="answers[12186].id" />
<input type="text" name="answers[12186].value" value="" id="question_12186" group="12186" class="input-text" />

<span class="error-content" id="err_answers[12186].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("12187");
// ]]>
-->
</script>
		  <div id="q_612" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						电话
							<span style="color:red">*</span>
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[12187].id" value="" id="answers[12187].id" />
<input type="text" name="answers[12187].value" value="" id="question_12187" group="12187" class="input-text" />

<span class="error-content" id="err_answers[12187].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

</div>

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="提交" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
	        jQuery("#check-alert-dialog .content").html(html);
	        jQuery("#check-alert-dialog").dialog('open');
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '提交失败：不能提交空报告';
		    jQuery("#check-alert-dialog .content").html(html);
		    jQuery("#check-alert-dialog").dialog('open');
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

// ]]>
-->
</script>
