	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/661" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2637" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在过去的两个月里， 你能回想起在多少个场合提到过百利甜酒？请真实回答
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[12560].id" value="" id="answers[12560].id" />
<input type="text" name="answers[12560].value" value="" id="question_12560" group="12560" class="input-text" />

<span class="error-content" id="err_answers[12560].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2623" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你有多大程度会向朋友推荐百利甜酒？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[12561].value" ></span>
<input type="hidden" name="answers[12561].id" value="" id="answers[12561].id" />
<table>
<tr>

<td>

<div class="left-label">不会推荐</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[12561].value" value="1" id="12561_1" group="12561" class="question_radio_12561 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12561].value" value="2" id="12561_2" group="12561" class="question_radio_12561 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12561].value" value="3" id="12561_3" group="12561" class="question_radio_12561 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12561].value" value="4" id="12561_4" group="12561" class="question_radio_12561 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12561].value" value="5" id="12561_5" group="12561" class="question_radio_12561 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12561].value" value="6" id="12561_6" group="12561" class="question_radio_12561 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12561].value" value="7" id="12561_7" group="12561" class="question_radio_12561 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12561].value" value="8" id="12561_8" group="12561" class="question_radio_12561 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12561].value" value="9" id="12561_9" group="12561" class="question_radio_12561 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[12561].value" value="10" id="12561_10" group="12561" class="question_radio_12561 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">一定推荐</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[12561].value" value="" id="answers[12561].value" class="q_12561 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2624" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你对百利甜酒的整体印象是什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12562].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12562].id" value="" id="answers[12562].id" />
<ul>
	<li>
			<input group="12562" type="radio" id="12562_0" name="answers[12562].value" value="10163"  class="selection question_radio_12562"  />		<label for="12562_0">非常负面</label>
	</li>
	<li>
			<input group="12562" type="radio" id="12562_1" name="answers[12562].value" value="10164"  class="selection question_radio_12562"  />		<label for="12562_1">负面</label>
	</li>
	<li>
			<input group="12562" type="radio" id="12562_2" name="answers[12562].value" value="10165"  class="selection question_radio_12562"  />		<label for="12562_2">中立</label>
	</li>
	<li>
			<input group="12562" type="radio" id="12562_3" name="answers[12562].value" value="10166"  class="selection question_radio_12562"  />		<label for="12562_3">正面</label>
	</li>
	<li>
			<input group="12562" type="radio" id="12562_4" name="answers[12562].value" value="10167"  class="selection question_radio_12562"  />		<label for="12562_4">非常正面</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12562  qc_0 radio" type="radio" name="answers[12562].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2625" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						如果百利甜酒在您常去的商店里出售，请问哪一项最能描述您购买的可能性？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[12563].value" ></span>
<input type="hidden" name="answers[12563].id" value="" id="answers[12563].id" />
<table>
<tr>

<td>

<div class="left-label">一定不会买</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[12563].value" value="1" id="12563_1" group="12563" class="question_radio_12563 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12563].value" value="2" id="12563_2" group="12563" class="question_radio_12563 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12563].value" value="3" id="12563_3" group="12563" class="question_radio_12563 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12563].value" value="4" id="12563_4" group="12563" class="question_radio_12563 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[12563].value" value="5" id="12563_5" group="12563" class="question_radio_12563 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">一定会买</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[12563].value" value="" id="answers[12563].value" class="q_12563 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2626" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你有多大程度将来在酒吧或KTV里够买百利甜酒？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[12564].value" ></span>
<input type="hidden" name="answers[12564].id" value="" id="answers[12564].id" />
<table>
<tr>

<td>

<div class="left-label">一定不会买</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[12564].value" value="1" id="12564_1" group="12564" class="question_radio_12564 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12564].value" value="2" id="12564_2" group="12564" class="question_radio_12564 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12564].value" value="3" id="12564_3" group="12564" class="question_radio_12564 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12564].value" value="4" id="12564_4" group="12564" class="question_radio_12564 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[12564].value" value="5" id="12564_5" group="12564" class="question_radio_12564 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">一定会买</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[12564].value" value="" id="answers[12564].value" class="q_12564 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2627" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在过去的三个月里，你有购买过百利甜酒吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12565].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12565].id" value="" id="answers[12565].id" />
<ul>
	<li>
			<input group="12565" type="radio" id="12565_0" name="answers[12565].value" value="10168"  class="selection question_radio_12565" onclick="showOrHidden(this.value)" />		<label for="12565_0">有</label>
	</li>
	<li>
			<input group="12565" type="radio" id="12565_1" name="answers[12565].value" value="10169"  class="selection question_radio_12565" onclick="showOrHidden(this.value)" />		<label for="12565_1">没有</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12565  qc_0 radio" type="radio" name="answers[12565].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2639" style="margin-bottom:0px;display:none" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你是在哪里购买的？(多选)
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12566].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12566].id" value="" id="answers[12566].id" />




<span id="hint_12566">
</span>
<ul>
	<li>
			<input group="12566" class="question_radio_12566 selection" type="checkbox" id="12566_0" name="answers[12566].value" value="10211" 	onclick=" "/>		<label for="12566_0">全家</label>
	</li>
	<li>
			<input group="12566" class="question_radio_12566 selection" type="checkbox" id="12566_1" name="answers[12566].value" value="10212" 	onclick=" "/>		<label for="12566_1">东方CJ</label>
	</li>
	<li>
			<input group="12566" class="question_radio_12566 selection" type="checkbox" id="12566_2" name="answers[12566].value" value="10213" 	onclick=" "/>		<label for="12566_2">家乐福</label>
	</li>
	<li>
			<input group="12566" class="question_radio_12566 selection" type="checkbox" id="12566_3" name="answers[12566].value" value="10214" 	onclick=" "/>		<label for="12566_3">沃尔玛</label>
	</li>
	<li>
			<input group="12566" class="question_radio_12566 selection" type="checkbox" id="12566_4" name="answers[12566].value" value="10215" 	onclick=" "/>		<label for="12566_4">麦德龙</label>
	</li>
	<li>
			<input group="12566" class="question_radio_12566 selection" type="checkbox" id="12566_5" name="answers[12566].value" value="10216" 	onclick=" "/>		<label for="12566_5">捷强</label>
	</li>
	<li>
			<input group="12566" class="question_radio_12566 selection" type="checkbox" id="12566_6" name="answers[12566].value" value="10217" 	onclick=" "/>		<label for="12566_6">山姆</label>
	</li>
	<li>
			<input group="12566" class="question_radio_12566 selection" type="checkbox" id="12566_7" name="answers[12566].value" value="10218" 	onclick=" "/>		<label for="12566_7">好乐迪</label>
	</li>
	<li>
			<input group="12566" class="question_radio_12566 selection" type="checkbox" id="12566_8" name="answers[12566].value" value="10219" 	onclick=" showOtherInput(this.value) "/>		<label for="12566_8">其他</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>
<tr>

<td>
	<div id="123456" style="display:none">
		<input type="hidden" name="answers[12567].id" value="" id="answers[12567].id" />
		<input type="text" name="answers[12567].value" value="" id="question_12567" group="12567" class="input-text" />
		<span class="error-content" id="err_answers[12567].value"  class="redFieldError"></span>
	</div>
</td>
<td valign="top" class="noanswer-td"></td>
</tr>
  </table>
<script language="JavaScript" type="text/javascript">


<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
function showOrHidden(val){
	if(val=="10168"){
		document.getElementById("q_2639").style.display="";
	}else{
		document.getElementById("q_2639").style.display="none";
	}
}

function showOtherInput(val){
    if(val=="10219"){
		if(jQuery("#12566_8").attr('checked')){
			document.getElementById("123456").style.display="";
		}else{
			document.getElementById("123456").style.display="none";
		}
	}
}
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2640" style="margin-bottom:0px; display:none" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="">
						其他
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2629" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在过去的三个月里，你有在酒吧或KTV购买过百利甜酒吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12568].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12568].id" value="" id="answers[12568].id" />
<ul>
	<li>
			<input group="12568" type="radio" id="12568_0" name="answers[12568].value" value="10178"  class="selection question_radio_12568" onclick="showOrHidden2(this.value)"  />		<label for="12568_0">有</label>
	</li>
	<li>
			<input group="12568" type="radio" id="12568_1" name="answers[12568].value" value="10179"  class="selection question_radio_12568" onclick="showOrHidden2(this.value)"  />		<label for="12568_1">没有</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12568  qc_0 radio" type="radio" name="answers[12568].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHidden2(val){
	if(val=="10178"){
		document.getElementById("q_2638").style.display="";
	}else{
		document.getElementById("q_2638").style.display="none";
	}
}
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2638" style="margin-bottom:0px; display:none" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						具体是哪个酒吧或KTV？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[12569].id" value="" id="answers[12569].id" />
<input type="text" name="answers[12569].value" value="" id="question_12569" group="12569" class="input-text" />

<span class="error-content" id="err_answers[12569].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2631" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你一周平均喝酒的次数是多少？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12570].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12570].id" value="" id="answers[12570].id" />
<ul>
	<li>
			<input group="12570" type="radio" id="12570_0" name="answers[12570].value" value="10180"  class="selection question_radio_12570"  />		<label for="12570_0">0-1</label>
	</li>
	<li>
			<input group="12570" type="radio" id="12570_1" name="answers[12570].value" value="10181"  class="selection question_radio_12570"  />		<label for="12570_1">2-4</label>
	</li>
	<li>
			<input group="12570" type="radio" id="12570_2" name="answers[12570].value" value="10182"  class="selection question_radio_12570"  />		<label for="12570_2">5-10</label>
	</li>
	<li>
			<input group="12570" type="radio" id="12570_3" name="answers[12570].value" value="10183"  class="selection question_radio_12570"  />		<label for="12570_3">11-20</label>
	</li>
	<li>
			<input group="12570" type="radio" id="12570_4" name="answers[12570].value" value="10184"  class="selection question_radio_12570"  />		<label for="12570_4">&gt;20</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12570  qc_0 radio" type="radio" name="answers[12570].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2632" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请你选择在与朋友饮酒时考虑的三个最重要的因素?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12571].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12571].id" value="" id="answers[12571].id" />




<span id="hint_12571">
      请选择三个因素<br>
</span>
<ul>
	<li>
			<input group="12571" class="question_radio_12571 selection" type="checkbox" id="12571_0" name="answers[12571].value" value="10185" 	onclick="checkChanged('12571_0',3,3);  "/>		<label for="12571_0">欢聚</label>
	</li>
	<li>
			<input group="12571" class="question_radio_12571 selection" type="checkbox" id="12571_1" name="answers[12571].value" value="10186" 	onclick="checkChanged('12571_1',3,3);  "/>		<label for="12571_1">放松</label>
	</li>
	<li>
			<input group="12571" class="question_radio_12571 selection" type="checkbox" id="12571_2" name="answers[12571].value" value="10187" 	onclick="checkChanged('12571_2',3,3);  "/>		<label for="12571_2">烈酒</label>
	</li>
	<li>
			<input group="12571" class="question_radio_12571 selection" type="checkbox" id="12571_3" name="answers[12571].value" value="10188" 	onclick="checkChanged('12571_3',3,3);  "/>		<label for="12571_3">价格</label>
	</li>
	<li>
			<input group="12571" class="question_radio_12571 selection" type="checkbox" id="12571_4" name="answers[12571].value" value="10189" 	onclick="checkChanged('12571_4',3,3);  "/>		<label for="12571_4">易胖</label>
	</li>
	<li>
			<input group="12571" class="question_radio_12571 selection" type="checkbox" id="12571_5" name="answers[12571].value" value="10190" 	onclick="checkChanged('12571_5',3,3);  "/>		<label for="12571_5">味道</label>
	</li>
	<li>
			<input group="12571" class="question_radio_12571 selection" type="checkbox" id="12571_6" name="answers[12571].value" value="10191" 	onclick="checkChanged('12571_6',3,3);  "/>		<label for="12571_6">气氛温馨</label>
	</li>
	<li>
			<input group="12571" class="question_radio_12571 selection" type="checkbox" id="12571_7" name="answers[12571].value" value="10192" 	onclick="checkChanged('12571_7',3,3);  "/>		<label for="12571_7">进口</label>
	</li>
	<li>
			<input group="12571" class="question_radio_12571 selection" type="checkbox" id="12571_8" name="answers[12571].value" value="10193" 	onclick="checkChanged('12571_8',3,3);  "/>		<label for="12571_8">保持控制</label>
	</li>
	<li>
			<input group="12571" class="question_radio_12571 selection" type="checkbox" id="12571_9" name="answers[12571].value" value="10194" 	onclick="checkChanged('12571_9',3,3);  "/>		<label for="12571_9">外出相聚</label>
	</li>
	<li>
			<input group="12571" class="question_radio_12571 selection" type="checkbox" id="12571_10" name="answers[12571].value" value="10195" 	onclick="checkChanged('12571_10',3,3);  "/>		<label for="12571_10">酒精含量</label>
	</li>
	<li>
			<input group="12571" class="question_radio_12571 selection" type="checkbox" id="12571_11" name="answers[12571].value" value="10196" 	onclick="checkChanged('12571_11',3,3);  "/>		<label for="12571_11">品牌知名度</label>
	</li>
	<li>
			<input group="12571" class="question_radio_12571 selection" type="checkbox" id="12571_12" name="answers[12571].value" value="10197" 	onclick="checkChanged('12571_12',3,3);  "/>		<label for="12571_12">包装</label>
	</li>
	<li>
			<input group="12571" class="question_radio_12571 selection" type="checkbox" id="12571_13" name="answers[12571].value" value="10198" 	onclick="checkChanged('12571_13',3,3);  "/>		<label for="12571_13">好的宣传及广告</label>
	</li>
	<li>
			<input group="12571" class="question_radio_12571 selection" type="checkbox" id="12571_14" name="answers[12571].value" value="10199" 	onclick="checkChanged('12571_14',3,3);  "/>		<label for="12571_14">朋友推荐</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

	
		if(typeof previouslySelectedOptions == "undefined") {
				var previouslySelectedOptions = new Array();
		}
				
		if(typeof previouslySelectedOptions[12571]=="undefined") {		
			 previouslySelectedOptions[12571] = new Array();
						
		}

		if(typeof checkChanged=="undefined") {
			checkChanged = function(id, max, min) {
				var elementId = id.split("_")[0];
				if($(id).checked == true) {				
					previouslySelectedOptions[elementId].push(id);
					// if there are now more elements in the array than allowed, delete the first one
					if (previouslySelectedOptions[elementId].length > max && max != 0){
						$(previouslySelectedOptions[elementId][0]).checked=false;
						previouslySelectedOptions[elementId].shift();					
					}	
				} else {
				   var newArray = new Array();
				    // delete the now unselected checkbox from the array
					for (var i = 0; i < previouslySelectedOptions[elementId].length; i++) {
						if (previouslySelectedOptions[elementId][i] != id) {
							newArray.push(previouslySelectedOptions[elementId][i]);
						}
					}
					previouslySelectedOptions[elementId] = newArray;
				}
				if (previouslySelectedOptions[elementId].length < min  && min != 0) {
					new Effect.Pulsate("hint_12571", {pulses:1, from:0.4});
				}		
			}
		}
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2633" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						当你想到百利甜酒时，你会想到什么词描述它？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[12572].id" value="" id="answers[12572].id" />
<textarea name="answers[12572].value" id="question_12572" cols="40" group="12572" rows="2" class="input-text" ></textarea>
<span class="error-content" id="err_answers[12572].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2634" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你平时主要喝哪种酒？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12573].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12573].id" value="" id="answers[12573].id" />
<ul>
	<li>
			<input group="12573" type="radio" id="12573_0" name="answers[12573].value" value="10200"  class="selection question_radio_12573" onclick="showOtherValueInputInRadio(this)" />		<label for="12573_0">软性的（例如啤酒）</label>
	</li>
	<li>
			<input group="12573" type="radio" id="12573_1" name="answers[12573].value" value="10201"  class="selection question_radio_12573" onclick="showOtherValueInputInRadio(this)" />		<label for="12573_1">中等类的 (例如：红酒，鸡尾酒）</label>
	</li>
	<li>
			<input group="12573" type="radio" id="12573_2" name="answers[12573].value" value="10202"  class="selection question_radio_12573" onclick="showOtherValueInputInRadio(this)" />		<label for="12573_2">烈酒类的，纯的</label>
	</li>
		<li>
			<input type="radio" id="12573_other" name="answers[12573].value" value="0" class="question_radio_12573" onclick="showOtherValueInputInRadio(this)" />			<label for="12573_other">其他</label>
			<input id="12573_other_input" type="text" name="answers[12573].otherValue" value=""  style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12573  qc_0 radio" type="radio" name="answers[12573].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2635" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你一般在什么场合饮酒？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12574].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12574].id" value="" id="answers[12574].id" />
<ul>
	<li>
			<input group="12574" type="radio" id="12574_0" name="answers[12574].value" value="10203"  class="selection question_radio_12574" onclick="showOtherValueInputInRadio(this)" />		<label for="12574_0">朋友家人作客的时候</label>
	</li>
	<li>
			<input group="12574" type="radio" id="12574_1" name="answers[12574].value" value="10204"  class="selection question_radio_12574" onclick="showOtherValueInputInRadio(this)" />		<label for="12574_1">和朋友出去的时候</label>
	</li>
	<li>
			<input group="12574" type="radio" id="12574_2" name="answers[12574].value" value="10205"  class="selection question_radio_12574" onclick="showOtherValueInputInRadio(this)" />		<label for="12574_2">自己想放松的时候</label>
	</li>
		<li>
			<input type="radio" id="12574_other" name="answers[12574].value" value="0" class="question_radio_12574" onclick="showOtherValueInputInRadio(this)" />			<label for="12574_other">其他</label>
			<input id="12574_other_input" type="text" name="answers[12574].otherValue" value=""  style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12574  qc_0 radio" type="radio" name="answers[12574].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2636" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你一般在什么地方饮酒？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12575].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12575].id" value="" id="answers[12575].id" />
<ul>
	<li>
			<input group="12575" type="radio" id="12575_0" name="answers[12575].value" value="10206"  class="selection question_radio_12575" onclick="showOtherValueInputInRadio(this)" />		<label for="12575_0">家</label>
	</li>
	<li>
			<input group="12575" type="radio" id="12575_1" name="answers[12575].value" value="10207"  class="selection question_radio_12575" onclick="showOtherValueInputInRadio(this)" />		<label for="12575_1">酒吧</label>
	</li>
	<li>
			<input group="12575" type="radio" id="12575_2" name="answers[12575].value" value="10208"  class="selection question_radio_12575" onclick="showOtherValueInputInRadio(this)" />		<label for="12575_2">KTV</label>
	</li>
	<li>
			<input group="12575" type="radio" id="12575_3" name="answers[12575].value" value="10209"  class="selection question_radio_12575" onclick="showOtherValueInputInRadio(this)" />		<label for="12575_3">饭店</label>
	</li>
	<li>
			<input group="12575" type="radio" id="12575_4" name="answers[12575].value" value="10210"  class="selection question_radio_12575" onclick="showOtherValueInputInRadio(this)" />		<label for="12575_4">迪厅</label>
	</li>
		<li>
			<input type="radio" id="12575_other" name="answers[12575].value" value="0" class="question_radio_12575" onclick="showOtherValueInputInRadio(this)" />			<label for="12575_other">其他</label>
			<input id="12575_other_input" type="text" name="answers[12575].otherValue" value=""  style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12575  qc_0 radio" type="radio" name="answers[12575].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="提交" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
	        jQuery("#check-alert-dialog .content").html(html);
	        jQuery("#check-alert-dialog").dialog('open');
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '提交失败：不能提交空报告';
		    jQuery("#check-alert-dialog .content").html(html);
		    jQuery("#check-alert-dialog").dialog('open');
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

// ]]>
-->
</script>
