	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/673" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="nY2P9RfmdlFa" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />
<input type="hidden" name="surveyId" value="nY2P9RfmdlFa"/>

<div class="mandatory"><span style="color: red;">* </span>- It is mandatory</div>
<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2666" style="margin-bottom:0px;" class="question-even question-area">
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						下面哪一项能够准确描述你目前的工作状态？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12751].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12751].id" value="" id="answers[12751].id" />
<ul>
	<li>
			<input group="12751" type="radio" id="12751_0" name="answers[12751].value" value="10313"  class="selection question_radio_12751" onclick="showOtherValueInputInRadio(this)" />		<label for="12751_0">自由职业者/个体户/私营企业老板</label>
	</li>
	<li>
			<input group="12751" type="radio" id="12751_1" name="answers[12751].value" value="10315"  class="selection question_radio_12751" onclick="showOtherValueInputInRadio(this)" />		<label for="12751_1">专业人士（如医生/律师/会计/建筑师等）</label>
	</li>
	<li>
			<input group="12751" type="radio" id="12751_2" name="answers[12751].value" value="10316"  class="selection question_radio_12751" onclick="showOtherValueInputInRadio(this)" />		<label for="12751_2">高层管理（如执行董事、总经理等）</label>
	</li>
	<li>
			<input group="12751" type="radio" id="12751_3" name="answers[12751].value" value="10317"  class="selection question_radio_12751" onclick="showOtherValueInputInRadio(this)" />		<label for="12751_3">中层管理（如部门经理/品牌经理等）</label>
	</li>
	<li>
			<input group="12751" type="radio" id="12751_4" name="answers[12751].value" value="10318"  class="selection question_radio_12751" onclick="showOtherValueInputInRadio(this)" />		<label for="12751_4">基层经理</label>
	</li>
	<li>
			<input group="12751" type="radio" id="12751_5" name="answers[12751].value" value="10319"  class="selection question_radio_12751" onclick="showOtherValueInputInRadio(this)" />		<label for="12751_5">其它办公室职员（如公司一般职员、文员、销售等）</label>
	</li>
	<li>
			<input group="12751" type="radio" id="12751_6" name="answers[12751].value" value="10320"  class="selection question_radio_12751" onclick="showOtherValueInputInRadio(this)" />		<label for="12751_6">技术类手工劳动者、领班或主管等</label>
	</li>
	<li>
			<input group="12751" type="radio" id="12751_7" name="answers[12751].value" value="10321"  class="selection question_radio_12751" onclick="showOtherValueInputInRadio(this)" />		<label for="12751_7">非技术类手工劳动者</label>
	</li>
	<li>
			<input group="12751" type="radio" id="12751_8" name="answers[12751].value" value="10322"  class="selection question_radio_12751" onclick="showOtherValueInputInRadio(this)" />		<label for="12751_8">服务性行业职员（服务员，店员，司机等）</label>
	</li>
	<li>
			<input group="12751" type="radio" id="12751_9" name="answers[12751].value" value="10323"  class="selection question_radio_12751" onclick="showOtherValueInputInRadio(this)" />		<label for="12751_9">教师</label>
	</li>
	<li>
			<input group="12751" type="radio" id="12751_10" name="answers[12751].value" value="10324"  class="selection question_radio_12751" onclick="showOtherValueInputInRadio(this)" />		<label for="12751_10">护士</label>
	</li>
	<li>
			<input group="12751" type="radio" id="12751_11" name="answers[12751].value" value="10325"  class="selection question_radio_12751" onclick="showOtherValueInputInRadio(this)" />		<label for="12751_11">政府机关干部</label>
	</li>
	<li>
			<input group="12751" type="radio" id="12751_12" name="answers[12751].value" value="10326"  class="selection question_radio_12751" onclick="showOtherValueInputInRadio(this)" />		<label for="12751_12">政府机关普通公务员</label>
	</li>
	<li>
			<input group="12751" type="radio" id="12751_13" name="answers[12751].value" value="10327"  class="selection question_radio_12751" onclick="showOtherValueInputInRadio(this)" />		<label for="12751_13">学生</label>
	</li>
	<li>
			<input group="12751" type="radio" id="12751_14" name="answers[12751].value" value="10328"  class="selection question_radio_12751" onclick="showOtherValueInputInRadio(this)" />		<label for="12751_14">全职家庭主妇</label>
	</li>
	<li>
			<input group="12751" type="radio" id="12751_15" name="answers[12751].value" value="10329"  class="selection question_radio_12751" onclick="showOtherValueInputInRadio(this)" />		<label for="12751_15">离/退休</label>
	</li>
		<li>
			<input type="radio" id="12751_other" name="answers[12751].value" value="0" class="question_radio_12751" onclick="showOtherValueInputInRadio(this)" />			<label for="12751_other">其他</label>
			<input id="12751_other_input" type="text" name="answers[12751].otherValue" value=""  style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12751  qc_0 radio" type="radio" name="answers[12751].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2667" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你目前的月家庭收入是多少？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12752].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12752].id" value="" id="answers[12752].id" />
<ul>
	<li>
			<input group="12752" type="radio" id="12752_0" name="answers[12752].value" value="10330"  class="selection question_radio_12752"  />		<label for="12752_0">不方便说</label>
	</li>
	<li>
			<input group="12752" type="radio" id="12752_1" name="answers[12752].value" value="10331"  class="selection question_radio_12752"  />		<label for="12752_1">&lt;8 K/mo</label>
	</li>
	<li>
			<input group="12752" type="radio" id="12752_2" name="answers[12752].value" value="10332"  class="selection question_radio_12752"  />		<label for="12752_2">8-10K/mo</label>
	</li>
	<li>
			<input group="12752" type="radio" id="12752_3" name="answers[12752].value" value="10333"  class="selection question_radio_12752"  />		<label for="12752_3">10-12K/mo</label>
	</li>
	<li>
			<input group="12752" type="radio" id="12752_4" name="answers[12752].value" value="10334"  class="selection question_radio_12752"  />		<label for="12752_4">12-15K/mo</label>
	</li>
	<li>
			<input group="12752" type="radio" id="12752_5" name="answers[12752].value" value="10335"  class="selection question_radio_12752"  />		<label for="12752_5">&gt;15K/mo</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12752  qc_0 radio" type="radio" name="answers[12752].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2668" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你使用家用汽车的频率是多少？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12753].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12753].id" value="" id="answers[12753].id" />
<ul>
	<li>
			<input group="12753" type="radio" id="12753_0" name="answers[12753].value" value="10336"  class="selection question_radio_12753"  />		<label for="12753_0">我们家还没有购买汽车</label>
	</li>
	<li>
			<input group="12753" type="radio" id="12753_1" name="answers[12753].value" value="10337"  class="selection question_radio_12753"  />		<label for="12753_1">少于一次一周</label>
	</li>
	<li>
			<input group="12753" type="radio" id="12753_2" name="answers[12753].value" value="10338"  class="selection question_radio_12753"  />		<label for="12753_2">一周多次</label>
	</li>
	<li>
			<input group="12753" type="radio" id="12753_3" name="answers[12753].value" value="10339"  class="selection question_radio_12753"  />		<label for="12753_3">每天</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12753  qc_0 radio" type="radio" name="answers[12753].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2669" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请选择你目前的居住状态？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12754].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12754].id" value="" id="answers[12754].id" />
<ul>
	<li>
			<input group="12754" type="radio" id="12754_0" name="answers[12754].value" value="10340"  class="selection question_radio_12754"  />		<label for="12754_0">我和我父母居住</label>
	</li>
	<li>
			<input group="12754" type="radio" id="12754_1" name="answers[12754].value" value="10341"  class="selection question_radio_12754"  />		<label for="12754_1">我自己一个人租房子住</label>
	</li>
	<li>
			<input group="12754" type="radio" id="12754_2" name="answers[12754].value" value="10342"  class="selection question_radio_12754"  />		<label for="12754_2">我和别人合租</label>
	</li>
	<li>
			<input group="12754" type="radio" id="12754_3" name="answers[12754].value" value="10343"  class="selection question_radio_12754"  />		<label for="12754_3">我和我爱人租房子住</label>
	</li>
	<li>
			<input group="12754" type="radio" id="12754_4" name="answers[12754].value" value="10344"  class="selection question_radio_12754"  />		<label for="12754_4">我一个人住在自己的房子里</label>
	</li>
	<li>
			<input group="12754" type="radio" id="12754_5" name="answers[12754].value" value="10345"  class="selection question_radio_12754"  />		<label for="12754_5">我和我爱人住在我们自己的房子里</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12754  qc_0 radio" type="radio" name="answers[12754].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2670" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的年龄是多少？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[12755].id" value="" id="answers[12755].id" />
<input type="text" name="answers[12755].value" value="" id="question_12755" group="12755" class="input-text" />

<span class="error-content" id="err_answers[12755].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2671" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你经常购买有机食品吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12756].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12756].id" value="" id="answers[12756].id" />
<ul>
	<li>
			<input group="12756" type="radio" id="12756_0" name="answers[12756].value" value="10346"  class="selection question_radio_12756"  />		<label for="12756_0">不，我觉得太贵了</label>
	</li>
	<li>
			<input group="12756" type="radio" id="12756_1" name="answers[12756].value" value="10347"  class="selection question_radio_12756"  />		<label for="12756_1">不，我不认为那些是真的有机食品</label>
	</li>
	<li>
			<input group="12756" type="radio" id="12756_2" name="answers[12756].value" value="10348"  class="selection question_radio_12756"  />		<label for="12756_2">是，我比较担心食物里的有害物质</label>
	</li>
	<li>
			<input group="12756" type="radio" id="12756_3" name="answers[12756].value" value="10349"  class="selection question_radio_12756"  />		<label for="12756_3">是，我觉得对环境比较好</label>
	</li>
	<li>
			<input group="12756" type="radio" id="12756_4" name="answers[12756].value" value="10350"  class="selection question_radio_12756"  />		<label for="12756_4">是，我愿意为质量好的及更安全的</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12756  qc_0 radio" type="radio" name="answers[12756].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2672" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你觉得有一个体面的外表及保持时尚度对你有多重要？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[12757].value" ></span>
<input type="hidden" name="answers[12757].id" value="" id="answers[12757].id" />
<table>
<tr>

<td>

<div class="left-label">非常不重要</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[12757].value" value="0" id="12757_0" group="12757" class="question_radio_12757 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12757].value" value="1" id="12757_1" group="12757" class="question_radio_12757 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12757].value" value="2" id="12757_2" group="12757" class="question_radio_12757 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12757].value" value="3" id="12757_3" group="12757" class="question_radio_12757 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12757].value" value="4" id="12757_4" group="12757" class="question_radio_12757 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12757].value" value="5" id="12757_5" group="12757" class="question_radio_12757 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12757].value" value="6" id="12757_6" group="12757" class="question_radio_12757 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12757].value" value="7" id="12757_7" group="12757" class="question_radio_12757 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12757].value" value="8" id="12757_8" group="12757" class="question_radio_12757 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[12757].value" value="9" id="12757_9" group="12757" class="question_radio_12757 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[12757].value" value="10" id="12757_10" group="12757" class="question_radio_12757 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">非常重要</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[12757].value" value="" id="answers[12757].value" class="q_12757 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2687" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你现在的状态是：
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12758].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12758].id" value="" id="answers[12758].id" />
<ul>
	<li>
			<input group="12758" type="radio" id="12758_0" name="answers[12758].value" value="10468"  class="selection question_radio_12758"  />		<label for="12758_0">怀孕的母亲</label>
	</li>
	<li>
			<input group="12758" type="radio" id="12758_1" name="answers[12758].value" value="10469"  class="selection question_radio_12758"  />		<label for="12758_1">孩子1-5个月大</label>
	</li>
	<li>
			<input group="12758" type="radio" id="12758_2" name="answers[12758].value" value="10470"  class="selection question_radio_12758"  />		<label for="12758_2">孩子5-8个月大，出现过便秘</label>
	</li>
	<li>
			<input group="12758" type="radio" id="12758_3" name="answers[12758].value" value="10471"  class="selection question_radio_12758"  />		<label for="12758_3">孩子一周岁或以上</label>
	</li>
	<li>
			<input group="12758" type="radio" id="12758_4" name="answers[12758].value" value="10472"  class="selection question_radio_12758"  />		<label for="12758_4">以上都不是</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12758  qc_0 radio" type="radio" name="answers[12758].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2673" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在选择奶粉的时候，下面哪句话能描述你的想法？（多项选择）
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12759].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12759].id" value="" id="answers[12759].id" />




<span id="hint_12759">
</span>
<ul>
	<li>
			<input group="12759" class="question_radio_12759 selection" type="checkbox" id="12759_0" name="answers[12759].value" value="10351" 	onclick=" "/>		<label for="12759_0">市场上最受欢迎的奶粉就是最适合我的孩子的</label>
	</li>
	<li>
			<input group="12759" class="question_radio_12759 selection" type="checkbox" id="12759_1" name="answers[12759].value" value="10352" 	onclick=" "/>		<label for="12759_1">价格适中的奶粉是比较合适的选择</label>
	</li>
	<li>
			<input group="12759" class="question_radio_12759 selection" type="checkbox" id="12759_2" name="answers[12759].value" value="10353" 	onclick=" "/>		<label for="12759_2">我只相信进口奶粉，不相信国产的</label>
	</li>
	<li>
			<input group="12759" class="question_radio_12759 selection" type="checkbox" id="12759_3" name="answers[12759].value" value="10354" 	onclick=" "/>		<label for="12759_3">我只相信我朋友的推荐</label>
	</li>
	<li>
			<input group="12759" class="question_radio_12759 selection" type="checkbox" id="12759_4" name="answers[12759].value" value="10355" 	onclick=" "/>		<label for="12759_4">我只在乎对我孩子最好的，无所谓价格高低</label>
	</li>
	<li>
			<input group="12759" class="question_radio_12759 selection" type="checkbox" id="12759_5" name="answers[12759].value" value="10356" 	onclick=" "/>		<label for="12759_5">奶粉的品牌一定是有机的产品</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2684" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你孩子的预产期是什么时候？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[12760].id" value="" id="answers[12760].id" />
<input type="text" name="answers[12760].value" value="" id="question_12760" group="12760" class="input-text" />

<span class="error-content" id="err_answers[12760].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2675" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你听过以下哪些奶粉品牌？（多项选择）
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12761].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12761].id" value="" id="answers[12761].id" />




<span id="hint_12761">
</span>
<ul>
	<li>
			<input group="12761" class="question_radio_12761 selection" type="checkbox" id="12761_0" name="answers[12761].value" value="10361" 	onclick=" "/>		<label for="12761_0">雅培</label>
	</li>
	<li>
			<input group="12761" class="question_radio_12761 selection" type="checkbox" id="12761_1" name="answers[12761].value" value="10362" 	onclick=" "/>		<label for="12761_1">惠氏</label>
	</li>
	<li>
			<input group="12761" class="question_radio_12761 selection" type="checkbox" id="12761_2" name="answers[12761].value" value="10363" 	onclick=" "/>		<label for="12761_2">美赞臣</label>
	</li>
	<li>
			<input group="12761" class="question_radio_12761 selection" type="checkbox" id="12761_3" name="answers[12761].value" value="10364" 	onclick=" "/>		<label for="12761_3">美素佳儿</label>
	</li>
	<li>
			<input group="12761" class="question_radio_12761 selection" type="checkbox" id="12761_4" name="answers[12761].value" value="10365" 	onclick=" "/>		<label for="12761_4">多美滋</label>
	</li>
	<li>
			<input group="12761" class="question_radio_12761 selection" type="checkbox" id="12761_5" name="answers[12761].value" value="10366" 	onclick=" "/>		<label for="12761_5">伊利</label>
	</li>
	<li>
			<input group="12761" class="question_radio_12761 selection" type="checkbox" id="12761_6" name="answers[12761].value" value="10367" 	onclick=" "/>		<label for="12761_6">圣元</label>
	</li>
	<li>
			<input group="12761" class="question_radio_12761 selection" type="checkbox" id="12761_7" name="answers[12761].value" value="10368" 	onclick=" "/>		<label for="12761_7">飞鹤</label>
	</li>
	<li>
			<input group="12761" class="question_radio_12761 selection" type="checkbox" id="12761_8" name="answers[12761].value" value="10369" 	onclick=" "/>		<label for="12761_8">培芝</label>
	</li>
	<li>
			<input group="12761" class="question_radio_12761 selection" type="checkbox" id="12761_9" name="answers[12761].value" value="10370" 	onclick=" "/>		<label for="12761_9">贝因美</label>
	</li>
	<li>
			<input group="12761" class="question_radio_12761 selection" type="checkbox" id="12761_10" name="answers[12761].value" value="10371" 	onclick=" "/>		<label for="12761_10">明冶</label>
	</li>
	<li>
			<input group="12761" class="question_radio_12761 selection" type="checkbox" id="12761_11" name="answers[12761].value" value="10372" 	onclick=" "/>		<label for="12761_11">Karicare</label>
	</li>
	<li>
			<input group="12761" class="question_radio_12761 selection" type="checkbox" id="12761_12" name="answers[12761].value" value="10373" 	onclick=" "/>		<label for="12761_12">明一</label>
	</li>
	<li>
			<input group="12761" class="question_radio_12761 selection" type="checkbox" id="12761_13" name="answers[12761].value" value="10374" 	onclick=" "/>		<label for="12761_13">施恩</label>
	</li>
	<li>
			<input group="12761" class="question_radio_12761 selection" type="checkbox" id="12761_14" name="answers[12761].value" value="10375" 	onclick=" "/>		<label for="12761_14">雅士利</label>
	</li>
	<li>
			<input group="12761" class="question_radio_12761 selection" type="checkbox" id="12761_15" name="answers[12761].value" value="10376" 	onclick=" "/>		<label for="12761_15">味全</label>
	</li>
	<li>
			<input group="12761" class="question_radio_12761 selection" type="checkbox" id="12761_16" name="answers[12761].value" value="10377" 	onclick=" "/>		<label for="12761_16">雀巢</label>
	</li>
		<li>
			<input class="question_radio_12761" type="checkbox" id="12761_other"   value="0" onclick="showOtherValueInputInCheckBox(this)" />			<label for="12761_other">其他</label>
			<input id="12761_other_input" type="text" name="answers[12761].otherValue" value="" style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2676" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你最有可能为你孩子购买的奶粉品牌是什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12762].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12762].id" value="" id="answers[12762].id" />
<ul>
	<li>
			<input group="12762" type="radio" id="12762_0" name="answers[12762].value" value="10378"  class="selection question_radio_12762" onclick="showOtherValueInputInRadio(this)" />		<label for="12762_0">雅培</label>
	</li>
	<li>
			<input group="12762" type="radio" id="12762_1" name="answers[12762].value" value="10379"  class="selection question_radio_12762" onclick="showOtherValueInputInRadio(this)" />		<label for="12762_1">惠氏</label>
	</li>
	<li>
			<input group="12762" type="radio" id="12762_2" name="answers[12762].value" value="10380"  class="selection question_radio_12762" onclick="showOtherValueInputInRadio(this)" />		<label for="12762_2">美赞臣</label>
	</li>
	<li>
			<input group="12762" type="radio" id="12762_3" name="answers[12762].value" value="10381"  class="selection question_radio_12762" onclick="showOtherValueInputInRadio(this)" />		<label for="12762_3">美素佳儿</label>
	</li>
	<li>
			<input group="12762" type="radio" id="12762_4" name="answers[12762].value" value="10382"  class="selection question_radio_12762" onclick="showOtherValueInputInRadio(this)" />		<label for="12762_4">多美滋</label>
	</li>
	<li>
			<input group="12762" type="radio" id="12762_5" name="answers[12762].value" value="10383"  class="selection question_radio_12762" onclick="showOtherValueInputInRadio(this)" />		<label for="12762_5">伊利</label>
	</li>
	<li>
			<input group="12762" type="radio" id="12762_6" name="answers[12762].value" value="10384"  class="selection question_radio_12762" onclick="showOtherValueInputInRadio(this)" />		<label for="12762_6">圣元</label>
	</li>
	<li>
			<input group="12762" type="radio" id="12762_7" name="answers[12762].value" value="10385"  class="selection question_radio_12762" onclick="showOtherValueInputInRadio(this)" />		<label for="12762_7">飞鹤</label>
	</li>
	<li>
			<input group="12762" type="radio" id="12762_8" name="answers[12762].value" value="10386"  class="selection question_radio_12762" onclick="showOtherValueInputInRadio(this)" />		<label for="12762_8">培芝</label>
	</li>
	<li>
			<input group="12762" type="radio" id="12762_9" name="answers[12762].value" value="10387"  class="selection question_radio_12762" onclick="showOtherValueInputInRadio(this)" />		<label for="12762_9">贝因美</label>
	</li>
	<li>
			<input group="12762" type="radio" id="12762_10" name="answers[12762].value" value="10388"  class="selection question_radio_12762" onclick="showOtherValueInputInRadio(this)" />		<label for="12762_10">明冶</label>
	</li>
	<li>
			<input group="12762" type="radio" id="12762_11" name="answers[12762].value" value="10389"  class="selection question_radio_12762" onclick="showOtherValueInputInRadio(this)" />		<label for="12762_11">Karicare</label>
	</li>
	<li>
			<input group="12762" type="radio" id="12762_12" name="answers[12762].value" value="10390"  class="selection question_radio_12762" onclick="showOtherValueInputInRadio(this)" />		<label for="12762_12">明一</label>
	</li>
	<li>
			<input group="12762" type="radio" id="12762_13" name="answers[12762].value" value="10391"  class="selection question_radio_12762" onclick="showOtherValueInputInRadio(this)" />		<label for="12762_13">施恩</label>
	</li>
	<li>
			<input group="12762" type="radio" id="12762_14" name="answers[12762].value" value="10392"  class="selection question_radio_12762" onclick="showOtherValueInputInRadio(this)" />		<label for="12762_14">雅士利</label>
	</li>
	<li>
			<input group="12762" type="radio" id="12762_15" name="answers[12762].value" value="10393"  class="selection question_radio_12762" onclick="showOtherValueInputInRadio(this)" />		<label for="12762_15">味全</label>
	</li>
	<li>
			<input group="12762" type="radio" id="12762_16" name="answers[12762].value" value="10394"  class="selection question_radio_12762" onclick="showOtherValueInputInRadio(this)" />		<label for="12762_16">雀巢</label>
	</li>
	<li>
			<input group="12762" type="radio" id="12762_17" name="answers[12762].value" value="10395"  class="selection question_radio_12762" onclick="showOtherValueInputInRadio(this)" />		<label for="12762_17">Meiji</label>
	</li>
		<li>
			<input type="radio" id="12762_other" name="answers[12762].value" value="0" class="question_radio_12762" onclick="showOtherValueInputInRadio(this)" />			<label for="12762_other">其他</label>
			<input id="12762_other_input" type="text" name="answers[12762].otherValue" value=""  style="display:none;"/>
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12762  qc_0 radio" type="radio" name="answers[12762].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2677" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的孩子多大了？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12763].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12763].id" value="" id="answers[12763].id" />
<ul>
	<li>
			<input group="12763" type="radio" id="12763_0" name="answers[12763].value" value="10396"  class="selection question_radio_12763"  />		<label for="12763_0">&lt;1 month</label>
	</li>
	<li>
			<input group="12763" type="radio" id="12763_1" name="answers[12763].value" value="10397"  class="selection question_radio_12763"  />		<label for="12763_1">1 month</label>
	</li>
	<li>
			<input group="12763" type="radio" id="12763_2" name="answers[12763].value" value="10398"  class="selection question_radio_12763"  />		<label for="12763_2">2 months</label>
	</li>
	<li>
			<input group="12763" type="radio" id="12763_3" name="answers[12763].value" value="10399"  class="selection question_radio_12763"  />		<label for="12763_3">3 months</label>
	</li>
	<li>
			<input group="12763" type="radio" id="12763_4" name="answers[12763].value" value="10400"  class="selection question_radio_12763"  />		<label for="12763_4">4 months</label>
	</li>
	<li>
			<input group="12763" type="radio" id="12763_5" name="answers[12763].value" value="10401"  class="selection question_radio_12763"  />		<label for="12763_5">5 months</label>
	</li>
	<li>
			<input group="12763" type="radio" id="12763_6" name="answers[12763].value" value="10402"  class="selection question_radio_12763"  />		<label for="12763_6">6 months</label>
	</li>
	<li>
			<input group="12763" type="radio" id="12763_7" name="answers[12763].value" value="10403"  class="selection question_radio_12763"  />		<label for="12763_7">7 months</label>
	</li>
	<li>
			<input group="12763" type="radio" id="12763_8" name="answers[12763].value" value="10404"  class="selection question_radio_12763"  />		<label for="12763_8">8 months</label>
	</li>
	<li>
			<input group="12763" type="radio" id="12763_9" name="answers[12763].value" value="10405"  class="selection question_radio_12763"  />		<label for="12763_9">9 months</label>
	</li>
	<li>
			<input group="12763" type="radio" id="12763_10" name="answers[12763].value" value="10406"  class="selection question_radio_12763"  />		<label for="12763_10">10 months</label>
	</li>
	<li>
			<input group="12763" type="radio" id="12763_11" name="answers[12763].value" value="10407"  class="selection question_radio_12763"  />		<label for="12763_11">11 months</label>
	</li>
	<li>
			<input group="12763" type="radio" id="12763_12" name="answers[12763].value" value="10408"  class="selection question_radio_12763"  />		<label for="12763_12">12 months</label>
	</li>
	<li>
			<input group="12763" type="radio" id="12763_13" name="answers[12763].value" value="10409"  class="selection question_radio_12763"  />		<label for="12763_13">&gt;12 months</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12763  qc_0 radio" type="radio" name="answers[12763].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2678" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你觉得母乳已经足够为孩子补充营养吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12764].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12764].id" value="" id="answers[12764].id" />
<ul>
	<li>
			<input group="12764" type="radio" id="12764_0" name="answers[12764].value" value="10410"  class="selection question_radio_12764"  />		<label for="12764_0">母乳已经足够了</label>
	</li>
	<li>
			<input group="12764" type="radio" id="12764_1" name="answers[12764].value" value="10411"  class="selection question_radio_12764"  />		<label for="12764_1">需要奶粉</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12764  qc_0 radio" type="radio" name="answers[12764].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2680" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你现在使用的奶粉品牌是什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12765].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12765].id" value="" id="answers[12765].id" />
<ul>
	<li>
			<input group="12765" type="radio" id="12765_0" name="answers[12765].value" value="10429"  class="selection question_radio_12765"  />		<label for="12765_0">雅培</label>
	</li>
	<li>
			<input group="12765" type="radio" id="12765_1" name="answers[12765].value" value="10430"  class="selection question_radio_12765"  />		<label for="12765_1">惠氏</label>
	</li>
	<li>
			<input group="12765" type="radio" id="12765_2" name="answers[12765].value" value="10431"  class="selection question_radio_12765"  />		<label for="12765_2">美赞臣</label>
	</li>
	<li>
			<input group="12765" type="radio" id="12765_3" name="answers[12765].value" value="10432"  class="selection question_radio_12765"  />		<label for="12765_3">美素佳儿</label>
	</li>
	<li>
			<input group="12765" type="radio" id="12765_4" name="answers[12765].value" value="10433"  class="selection question_radio_12765"  />		<label for="12765_4">多美滋</label>
	</li>
	<li>
			<input group="12765" type="radio" id="12765_5" name="answers[12765].value" value="10434"  class="selection question_radio_12765"  />		<label for="12765_5">伊利</label>
	</li>
	<li>
			<input group="12765" type="radio" id="12765_6" name="answers[12765].value" value="10435"  class="selection question_radio_12765"  />		<label for="12765_6">圣元</label>
	</li>
	<li>
			<input group="12765" type="radio" id="12765_7" name="answers[12765].value" value="10436"  class="selection question_radio_12765"  />		<label for="12765_7">飞鹤</label>
	</li>
	<li>
			<input group="12765" type="radio" id="12765_8" name="answers[12765].value" value="10437"  class="selection question_radio_12765"  />		<label for="12765_8">培芝</label>
	</li>
	<li>
			<input group="12765" type="radio" id="12765_9" name="answers[12765].value" value="10438"  class="selection question_radio_12765"  />		<label for="12765_9">贝因美</label>
	</li>
	<li>
			<input group="12765" type="radio" id="12765_10" name="answers[12765].value" value="10439"  class="selection question_radio_12765"  />		<label for="12765_10">明冶</label>
	</li>
	<li>
			<input group="12765" type="radio" id="12765_11" name="answers[12765].value" value="10440"  class="selection question_radio_12765"  />		<label for="12765_11">Karicare</label>
	</li>
	<li>
			<input group="12765" type="radio" id="12765_12" name="answers[12765].value" value="10441"  class="selection question_radio_12765"  />		<label for="12765_12">明一</label>
	</li>
	<li>
			<input group="12765" type="radio" id="12765_13" name="answers[12765].value" value="10442"  class="selection question_radio_12765"  />		<label for="12765_13">施恩</label>
	</li>
	<li>
			<input group="12765" type="radio" id="12765_14" name="answers[12765].value" value="10443"  class="selection question_radio_12765"  />		<label for="12765_14">雅士利</label>
	</li>
	<li>
			<input group="12765" type="radio" id="12765_15" name="answers[12765].value" value="10444"  class="selection question_radio_12765"  />		<label for="12765_15">味全</label>
	</li>
	<li>
			<input group="12765" type="radio" id="12765_16" name="answers[12765].value" value="10445"  class="selection question_radio_12765"  />		<label for="12765_16">雀巢</label>
	</li>
	<li>
			<input group="12765" type="radio" id="12765_17" name="answers[12765].value" value="10446"  class="selection question_radio_12765"  />		<label for="12765_17">我没有用奶粉</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12765  qc_0 radio" type="radio" name="answers[12765].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2685" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的孩子遇到过便秘的情况吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12766].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12766].id" value="" id="answers[12766].id" />
<ul>
	<li>
			<input group="12766" type="radio" id="12766_0" name="answers[12766].value" value="10466"  class="selection question_radio_12766"  />		<label for="12766_0">是</label>
	</li>
	<li>
			<input group="12766" type="radio" id="12766_1" name="answers[12766].value" value="10467"  class="selection question_radio_12766"  />		<label for="12766_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12766  qc_0 radio" type="radio" name="answers[12766].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2681" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你准备更换奶粉品牌吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12767].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12767].id" value="" id="answers[12767].id" />
<ul>
	<li>
			<input group="12767" type="radio" id="12767_0" name="answers[12767].value" value="10447"  class="selection question_radio_12767"  />		<label for="12767_0">是</label>
	</li>
	<li>
			<input group="12767" type="radio" id="12767_1" name="answers[12767].value" value="10448"  class="selection question_radio_12767"  />		<label for="12767_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12767  qc_0 radio" type="radio" name="answers[12767].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2682" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你希望换成哪一个牌子的奶粉？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12768].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12768].id" value="" id="answers[12768].id" />
<ul>
	<li>
			<input group="12768" type="radio" id="12768_0" name="answers[12768].value" value="10449"  class="selection question_radio_12768"  />		<label for="12768_0">雅培</label>
	</li>
	<li>
			<input group="12768" type="radio" id="12768_1" name="answers[12768].value" value="10450"  class="selection question_radio_12768"  />		<label for="12768_1">惠氏</label>
	</li>
	<li>
			<input group="12768" type="radio" id="12768_2" name="answers[12768].value" value="10451"  class="selection question_radio_12768"  />		<label for="12768_2">美赞臣</label>
	</li>
	<li>
			<input group="12768" type="radio" id="12768_3" name="answers[12768].value" value="10452"  class="selection question_radio_12768"  />		<label for="12768_3">美素佳儿</label>
	</li>
	<li>
			<input group="12768" type="radio" id="12768_4" name="answers[12768].value" value="10453"  class="selection question_radio_12768"  />		<label for="12768_4">多美滋</label>
	</li>
	<li>
			<input group="12768" type="radio" id="12768_5" name="answers[12768].value" value="10454"  class="selection question_radio_12768"  />		<label for="12768_5">伊利</label>
	</li>
	<li>
			<input group="12768" type="radio" id="12768_6" name="answers[12768].value" value="10455"  class="selection question_radio_12768"  />		<label for="12768_6">圣元</label>
	</li>
	<li>
			<input group="12768" type="radio" id="12768_7" name="answers[12768].value" value="10456"  class="selection question_radio_12768"  />		<label for="12768_7">飞鹤</label>
	</li>
	<li>
			<input group="12768" type="radio" id="12768_8" name="answers[12768].value" value="10457"  class="selection question_radio_12768"  />		<label for="12768_8">培芝</label>
	</li>
	<li>
			<input group="12768" type="radio" id="12768_9" name="answers[12768].value" value="10458"  class="selection question_radio_12768"  />		<label for="12768_9">贝因美</label>
	</li>
	<li>
			<input group="12768" type="radio" id="12768_10" name="answers[12768].value" value="10459"  class="selection question_radio_12768"  />		<label for="12768_10">明冶</label>
	</li>
	<li>
			<input group="12768" type="radio" id="12768_11" name="answers[12768].value" value="10460"  class="selection question_radio_12768"  />		<label for="12768_11">Karicare</label>
	</li>
	<li>
			<input group="12768" type="radio" id="12768_12" name="answers[12768].value" value="10461"  class="selection question_radio_12768"  />		<label for="12768_12">明一</label>
	</li>
	<li>
			<input group="12768" type="radio" id="12768_13" name="answers[12768].value" value="10462"  class="selection question_radio_12768"  />		<label for="12768_13">施恩</label>
	</li>
	<li>
			<input group="12768" type="radio" id="12768_14" name="answers[12768].value" value="10463"  class="selection question_radio_12768"  />		<label for="12768_14">雅士利</label>
	</li>
	<li>
			<input group="12768" type="radio" id="12768_15" name="answers[12768].value" value="10464"  class="selection question_radio_12768"  />		<label for="12768_15">味全</label>
	</li>
	<li>
			<input group="12768" type="radio" id="12768_16" name="answers[12768].value" value="10465"  class="selection question_radio_12768"  />		<label for="12768_16">雀巢</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_12768  qc_0 radio" type="radio" name="answers[12768].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2683" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你更换奶粉品牌最重要的因素是什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[12769].id" value="" id="answers[12769].id" />
<textarea name="answers[12769].value" id="question_12769" cols="40" group="12769" rows="2" class="input-text" ></textarea>
<span class="error-content" id="err_answers[12769].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("12773");
// ]]>
-->
</script>
		  <div id="q_2688" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						城市
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[12773].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[12773].id" value="" id="answers[12773].id" />

	<select group="12773" class="selection" id="question_12773" name="answers[12773].value" title="title"  size = "1" >
	<option selected="selected" value="0">请选择</option>
<option value="10473" style=""  >北京</option>
<option value="10474" style=""  >上海</option>
<option value="10475" style=""  >南京</option>
<option value="10476" style=""  >广州</option>
<option value="10477" style=""  >深圳</option>
<option value="10478" style=""  >成都</option>
<option value="10479" style=""  >其他</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("12770");
// ]]>
-->
</script>
		  <div id="q_2088" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						姓名:
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[12770].id" value="" id="answers[12770].id" />
<input type="text" name="answers[12770].value" value="" id="question_12770" group="12770" class="input-text" />

<span class="error-content" id="err_answers[12770].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("12771");
// ]]>
-->
</script>
		  <div id="q_2686" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						手机号码
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[12771].id" value="" id="answers[12771].id" />
<input type="text" name="answers[12771].value" value="" id="question_12771" group="12771" class="input-text" />

<span class="error-content" id="err_answers[12771].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("12772");
// ]]>
-->
</script>
		  <div id="q_2661" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						邮箱:
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[12772].id" value="" id="answers[12772].id" />
<input type="text" name="answers[12772].value" value="" id="question_12772" group="12772" class="input-text" />

<span class="error-content" id="err_answers[12772].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="提交" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
	        jQuery("#check-alert-dialog .content").html(html);
	        jQuery("#check-alert-dialog").dialog('open');	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '提交失败：不能提交空报告';
		    jQuery("#check-alert-dialog .content").html(html);
		    jQuery("#check-alert-dialog").dialog('open');			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[


	 Element.hide("q_2673");
	 Element.hide("q_2684");
	 Element.hide("q_2675");
	 Element.hide("q_2676");
	 Element.hide("q_2677");
	 Element.hide("q_2678");
	 Element.hide("q_2680");
	 Element.hide("q_2685");
	 Element.hide("q_2681");
	 Element.hide("q_2682");
	 Element.hide("q_2683");


var myrules = {
	   
	   "input#12758_1": function(el){
			el.onclick = function(){
				if ($("12758_1").checked){
						Element.hide($("q_2684"));
						Element.show($("q_2675"));
						Element.hide($("q_2676"));
						Element.show($("q_2677"));
						Element.show($("q_2678"));
						Element.show($("q_2680"));
						Element.hide($("q_2681"));
						Element.hide($("q_2682"));
						Element.hide($("q_2683"));
						Element.hide($("q_2685"));
						Element.show($("q_2673"));
				}
			}
		}
	,
	   
	   "input#12758_3": function(el){
			el.onclick = function(){
				if ($("12758_3").checked){
						Element.hide($("q_2684"));
						Element.hide($("q_2675"));
						Element.hide($("q_2676"));
						Element.hide($("q_2677"));
						Element.hide($("q_2678"));
						Element.show($("q_2680"));
						Element.show($("q_2681"));
						Element.show($("q_2682"));
						Element.show($("q_2683"));
						Element.hide($("q_2685"));
						Element.show($("q_2673"));
				}
			}
		}
	,
	   
	   "input#12767_1": function(el){
			el.onclick = function(){
				if ($("12767_1").checked){
						Element.hide($("q_2682"));
				}
			}
		}
	,
	   
	   "input#12758_4": function(el){
			el.onclick = function(){
				if ($("12758_4").checked){
						Element.hide($("q_2684"));
						Element.hide($("q_2675"));
						Element.hide($("q_2676"));
						Element.hide($("q_2677"));
						Element.hide($("q_2678"));
						Element.hide($("q_2680"));
						Element.hide($("q_2681"));
						Element.hide($("q_2682"));
						Element.hide($("q_2683"));
						Element.hide($("q_2685"));
						Element.hide($("q_2673"));
				}
			}
		}
	,
	   
	   "input#12758_2": function(el){
			el.onclick = function(){
				if ($("12758_2").checked){
						Element.hide($("q_2684"));
						Element.hide($("q_2675"));
						Element.hide($("q_2676"));
						Element.show($("q_2677"));
						Element.hide($("q_2678"));
						Element.show($("q_2680"));
						Element.show($("q_2681"));
						Element.show($("q_2682"));
						Element.hide($("q_2683"));
						Element.show($("q_2685"));
						Element.show($("q_2673"));
				}
			}
		}
	,
	   
	   "input#12764_1": function(el){
			el.onclick = function(){
				if ($("12764_1").checked){
						Element.show($("q_2680"));
				}
			}
		}
	,
	   
	   "input#12758_0": function(el){
			el.onclick = function(){
				if ($("12758_0").checked){
						Element.show($("q_2684"));
						Element.show($("q_2675"));
						Element.show($("q_2676"));
						Element.hide($("q_2677"));
						Element.hide($("q_2678"));
						Element.hide($("q_2680"));
						Element.hide($("q_2681"));
						Element.hide($("q_2682"));
						Element.hide($("q_2683"));
						Element.hide($("q_2685"));
						Element.show($("q_2673"));
				}
			}
		}
	,
	   
	   "input#12764_0": function(el){
			el.onclick = function(){
				if ($("12764_0").checked){
						Element.hide($("q_2680"));
				}
			}
		}
	,
	   
	   "input#12767_0": function(el){
			el.onclick = function(){
				if ($("12767_0").checked){
						Element.show($("q_2682"));
				}
			}
		}
}

Behaviour.register(myrules);

// ]]>
-->
</script>
