	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/683" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="loading();return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="KUaGt73ULoL5" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />
<input type="hidden" name="surveyId" value="KUaGt73ULoL5"/>

<div class="mandatory"><span style="color: red;">* </span>- It is mandatory</div>
<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2647" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的孩子多大了？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13026].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13026].id" value="" id="answers[13026].id" />
<ul>
	<li>
			<input group="13026" type="radio" id="13026_0" name="answers[13026].value" value="10234"  class="selection question_radio_13026"  />		<label for="13026_0">3岁以下</label>
	</li>
	<li>
			<input group="13026" type="radio" id="13026_1" name="answers[13026].value" value="10235"  class="selection question_radio_13026"  />		<label for="13026_1">3-6岁</label>
	</li>
	<li>
			<input group="13026" type="radio" id="13026_2" name="answers[13026].value" value="10236"  class="selection question_radio_13026"  />		<label for="13026_2">7-10岁</label>
	</li>
	<li>
			<input group="13026" type="radio" id="13026_3" name="answers[13026].value" value="10237"  class="selection question_radio_13026"  />		<label for="13026_3">11-14岁</label>
	</li>
	<li>
			<input group="13026" type="radio" id="13026_4" name="answers[13026].value" value="10238"  class="selection question_radio_13026"  />		<label for="13026_4">大于14岁</label>
	</li>
	<li>
			<input group="13026" type="radio" id="13026_5" name="answers[13026].value" value="10239"  class="selection question_radio_13026"  />		<label for="13026_5">我没有孩子</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13026  qc_0 radio" type="radio" name="answers[13026].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2648" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你觉得孩子在同龄人中是佼佼者有多重要?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[13027].value" ></span>
<input type="hidden" name="answers[13027].id" value="" id="answers[13027].id" />
<table>
<tr>

<td>

<div class="left-label">不重要</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[13027].value" value="1" id="13027_1" group="13027" class="question_radio_13027 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13027].value" value="2" id="13027_2" group="13027" class="question_radio_13027 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13027].value" value="3" id="13027_3" group="13027" class="question_radio_13027 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13027].value" value="4" id="13027_4" group="13027" class="question_radio_13027 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13027].value" value="5" id="13027_5" group="13027" class="question_radio_13027 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13027].value" value="6" id="13027_6" group="13027" class="question_radio_13027 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13027].value" value="7" id="13027_7" group="13027" class="question_radio_13027 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13027].value" value="8" id="13027_8" group="13027" class="question_radio_13027 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13027].value" value="9" id="13027_9" group="13027" class="question_radio_13027 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[13027].value" value="10" id="13027_10" group="13027" class="question_radio_13027 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">很重要</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[13027].value" value="" id="answers[13027].value" class="q_13027 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2566" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你觉得孩子可以说一口流利的英语有多重要？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[13028].value" ></span>
<input type="hidden" name="answers[13028].id" value="" id="answers[13028].id" />
<table>
<tr>

<td>

<div class="left-label">不重要</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[13028].value" value="1" id="13028_1" group="13028" class="question_radio_13028 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13028].value" value="2" id="13028_2" group="13028" class="question_radio_13028 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13028].value" value="3" id="13028_3" group="13028" class="question_radio_13028 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13028].value" value="4" id="13028_4" group="13028" class="question_radio_13028 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13028].value" value="5" id="13028_5" group="13028" class="question_radio_13028 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13028].value" value="6" id="13028_6" group="13028" class="question_radio_13028 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13028].value" value="7" id="13028_7" group="13028" class="question_radio_13028 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13028].value" value="8" id="13028_8" group="13028" class="question_radio_13028 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13028].value" value="9" id="13028_9" group="13028" class="question_radio_13028 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[13028].value" value="10" id="13028_10" group="13028" class="question_radio_13028 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">很重要</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[13028].value" value="" id="answers[13028].value" class="q_13028 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2565" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的孩子平均每天花在课后家庭作业上的时间是多少?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13029].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13029].id" value="" id="answers[13029].id" />
<ul>
	<li>
			<input group="13029" type="radio" id="13029_0" name="answers[13029].value" value="9758"  class="selection question_radio_13029"  />		<label for="13029_0">少于30分钟</label>
	</li>
	<li>
			<input group="13029" type="radio" id="13029_1" name="answers[13029].value" value="9759"  class="selection question_radio_13029"  />		<label for="13029_1">30-60分钟</label>
	</li>
	<li>
			<input group="13029" type="radio" id="13029_2" name="answers[13029].value" value="9760"  class="selection question_radio_13029"  />		<label for="13029_2">60-90分钟</label>
	</li>
	<li>
			<input group="13029" type="radio" id="13029_3" name="answers[13029].value" value="9761"  class="selection question_radio_13029"  />		<label for="13029_3">90-120分钟</label>
	</li>
	<li>
			<input group="13029" type="radio" id="13029_4" name="answers[13029].value" value="9762"  class="selection question_radio_13029"  />		<label for="13029_4">2-3小时</label>
	</li>
	<li>
			<input group="13029" type="radio" id="13029_5" name="answers[13029].value" value="9763"  class="selection question_radio_13029"  />		<label for="13029_5">多于3小时</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13029  qc_0 radio" type="radio" name="answers[13029].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2649" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你准备要送你的孩子去参与一些英语课程吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13030].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13030].id" value="" id="answers[13030].id" />
<ul>
	<li>
			<input group="13030" type="radio" id="13030_0" name="answers[13030].value" value="10240"  class="selection question_radio_13030"  />		<label for="13030_0">是，半年之内</label>
	</li>
	<li>
			<input group="13030" type="radio" id="13030_1" name="answers[13030].value" value="10241"  class="selection question_radio_13030"  />		<label for="13030_1">是，一年之内</label>
	</li>
	<li>
			<input group="13030" type="radio" id="13030_2" name="answers[13030].value" value="10242"  class="selection question_radio_13030"  />		<label for="13030_2">是，但要到明年之后</label>
	</li>
	<li>
			<input group="13030" type="radio" id="13030_3" name="answers[13030].value" value="10243"  class="selection question_radio_13030"  />		<label for="13030_3">我的孩子已经在上英语课了</label>
	</li>
	<li>
			<input group="13030" type="radio" id="13030_4" name="answers[13030].value" value="10244"  class="selection question_radio_13030"  />		<label for="13030_4">我没有这个计划</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13030  qc_0 radio" type="radio" name="answers[13030].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2650" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你打算送孩子去参与英语课程最重要的原因是什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13031].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13031].id" value="" id="answers[13031].id" />
<ul>
	<li>
			<input group="13031" type="radio" id="13031_0" name="answers[13031].value" value="10245"  class="selection question_radio_13031"  />		<label for="13031_0">职业发展机会</label>
	</li>
	<li>
			<input group="13031" type="radio" id="13031_1" name="answers[13031].value" value="10246"  class="selection question_radio_13031"  />		<label for="13031_1">更好的了解世界</label>
	</li>
	<li>
			<input group="13031" type="radio" id="13031_2" name="answers[13031].value" value="10247"  class="selection question_radio_13031"  />		<label for="13031_2">沟通能力的提升</label>
	</li>
	<li>
			<input group="13031" type="radio" id="13031_3" name="answers[13031].value" value="10248"  class="selection question_radio_13031"  />		<label for="13031_3">领先于同龄人</label>
	</li>
	<li>
			<input group="13031" type="radio" id="13031_4" name="answers[13031].value" value="10249"  class="selection question_radio_13031"  />		<label for="13031_4">其他(请填写)</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13031  qc_0 radio" type="radio" name="answers[13031].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2640" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13032].id" value="" id="answers[13032].id" />
<input type="text" name="answers[13032].value" value="" id="question_13032" group="13032" class="input-text" />

<span class="error-content" id="err_answers[13032].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2747" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你听说过以下哪个英语培训机构？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13033].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13033].id" value="" id="answers[13033].id" />




<span id="hint_13033">
</span>
<ul>
	<li>
			<input group="13033" class="question_radio_13033 selection" type="checkbox" id="13033_0" name="answers[13033].value" value="10683" 	onclick=" "/>		<label for="13033_0">迪士尼英语</label>
	</li>
	<li>
			<input group="13033" class="question_radio_13033 selection" type="checkbox" id="13033_1" name="answers[13033].value" value="10684" 	onclick=" "/>		<label for="13033_1">小小地球</label>
	</li>
	<li>
			<input group="13033" class="question_radio_13033 selection" type="checkbox" id="13033_2" name="answers[13033].value" value="10685" 	onclick=" "/>		<label for="13033_2">乐宁</label>
	</li>
	<li>
			<input group="13033" class="question_radio_13033 selection" type="checkbox" id="13033_3" name="answers[13033].value" value="10686" 	onclick=" "/>		<label for="13033_3">长颈鹿</label>
	</li>
	<li>
			<input group="13033" class="question_radio_13033 selection" type="checkbox" id="13033_4" name="answers[13033].value" value="10687" 	onclick=" "/>		<label for="13033_4">瑞思</label>
	</li>
	<li>
			<input group="13033" class="question_radio_13033 selection" type="checkbox" id="13033_5" name="answers[13033].value" value="10688" 	onclick=" "/>		<label for="13033_5">学乐</label>
	</li>
	<li>
			<input group="13033" class="question_radio_13033 selection" type="checkbox" id="13033_6" name="answers[13033].value" value="10689" 	onclick=" "/>		<label for="13033_6">新东方</label>
	</li>
	<li>
			<input group="13033" class="question_radio_13033 selection" type="checkbox" id="13033_7" name="answers[13033].value" value="10690" 	onclick=" "/>		<label for="13033_7">其他(请填写)</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2748" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他机构
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13034].id" value="" id="answers[13034].id" />
<input type="text" name="answers[13034].value" value="" id="question_13034" group="13034" class="input-text" />

<span class="error-content" id="err_answers[13034].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2749" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你觉得下列学校哪个是英语培训中最好的？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13035].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13035].id" value="" id="answers[13035].id" />
<ul>
	<li>
			<input group="13035" type="radio" id="13035_0" name="answers[13035].value" value="10691"  class="selection question_radio_13035"  />		<label for="13035_0">迪士尼英语</label>
	</li>
	<li>
			<input group="13035" type="radio" id="13035_1" name="answers[13035].value" value="10692"  class="selection question_radio_13035"  />		<label for="13035_1">小小地球</label>
	</li>
	<li>
			<input group="13035" type="radio" id="13035_2" name="answers[13035].value" value="10693"  class="selection question_radio_13035"  />		<label for="13035_2">乐宁</label>
	</li>
	<li>
			<input group="13035" type="radio" id="13035_3" name="answers[13035].value" value="10694"  class="selection question_radio_13035"  />		<label for="13035_3">长颈鹿</label>
	</li>
	<li>
			<input group="13035" type="radio" id="13035_4" name="answers[13035].value" value="10695"  class="selection question_radio_13035"  />		<label for="13035_4">瑞思</label>
	</li>
	<li>
			<input group="13035" type="radio" id="13035_5" name="answers[13035].value" value="10696"  class="selection question_radio_13035"  />		<label for="13035_5">学乐</label>
	</li>
	<li>
			<input group="13035" type="radio" id="13035_6" name="answers[13035].value" value="10697"  class="selection question_radio_13035"  />		<label for="13035_6">新东方</label>
	</li>
	<li>
			<input group="13035" type="radio" id="13035_7" name="answers[13035].value" value="10698"  class="selection question_radio_13035"  />		<label for="13035_7">其他(请填写)</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13035  qc_0 radio" type="radio" name="answers[13035].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2653" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他学校
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13036].id" value="" id="answers[13036].id" />
<input type="text" name="answers[13036].value" value="" id="question_13036" group="13036" class="input-text" />

<span class="error-content" id="err_answers[13036].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2654" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你听说过英孚教育的什么课程？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13037].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13037].id" value="" id="answers[13037].id" />




<span id="hint_13037">
</span>
<ul>
	<li>
			<input group="13037" class="question_radio_13037 selection" type="checkbox" id="13037_0" name="answers[13037].value" value="10264" 	onclick=" "/>		<label for="13037_0">成人及职场英语</label>
	</li>
	<li>
			<input group="13037" class="question_radio_13037 selection" type="checkbox" id="13037_1" name="answers[13037].value" value="10265" 	onclick=" "/>		<label for="13037_1">青少儿英语</label>
	</li>
	<li>
			<input group="13037" class="question_radio_13037 selection" type="checkbox" id="13037_2" name="answers[13037].value" value="10266" 	onclick=" "/>		<label for="13037_2">以上都听说过</label>
	</li>
	<li>
			<input group="13037" class="question_radio_13037 selection" type="checkbox" id="13037_3" name="answers[13037].value" value="10267" 	onclick=" "/>		<label for="13037_3">其他课程(请填写)</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2655" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他课程
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13038].id" value="" id="answers[13038].id" />
<input type="text" name="answers[13038].value" value="" id="question_13038" group="13038" class="input-text" />

<span class="error-content" id="err_answers[13038].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2665" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你曾和英孚教育联系过吗?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13039].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13039].id" value="" id="answers[13039].id" />
<ul>
	<li>
			<input group="13039" type="radio" id="13039_0" name="answers[13039].value" value="10311"  class="selection question_radio_13039"  />		<label for="13039_0">是</label>
	</li>
	<li>
			<input group="13039" type="radio" id="13039_1" name="answers[13039].value" value="10312"  class="selection question_radio_13039"  />		<label for="13039_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13039  qc_0 radio" type="radio" name="answers[13039].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2656" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你的孩子已经是英孚课程的学生了吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13040].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13040].id" value="" id="answers[13040].id" />
<ul>
	<li>
			<input group="13040" type="radio" id="13040_0" name="answers[13040].value" value="10268"  class="selection question_radio_13040"  />		<label for="13040_0">是</label>
	</li>
	<li>
			<input group="13040" type="radio" id="13040_1" name="answers[13040].value" value="10269"  class="selection question_radio_13040"  />		<label for="13040_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13040  qc_0 radio" type="radio" name="answers[13040].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2657" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你多久和朋友聚会一次？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13041].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13041].id" value="" id="answers[13041].id" />
<ul>
	<li>
			<input group="13041" type="radio" id="13041_0" name="answers[13041].value" value="10270"  class="selection question_radio_13041"  />		<label for="13041_0">从不</label>
	</li>
	<li>
			<input group="13041" type="radio" id="13041_1" name="answers[13041].value" value="10271"  class="selection question_radio_13041"  />		<label for="13041_1">只有特殊场合</label>
	</li>
	<li>
			<input group="13041" type="radio" id="13041_2" name="answers[13041].value" value="10272"  class="selection question_radio_13041"  />		<label for="13041_2">一个月两三次</label>
	</li>
	<li>
			<input group="13041" type="radio" id="13041_3" name="answers[13041].value" value="10273"  class="selection question_radio_13041"  />		<label for="13041_3">每周一次</label>
	</li>
	<li>
			<input group="13041" type="radio" id="13041_4" name="answers[13041].value" value="10274"  class="selection question_radio_13041"  />		<label for="13041_4">一周几次</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13041  qc_0 radio" type="radio" name="answers[13041].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2658" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你的好友中，有多少已经为人父母？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13042].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13042].id" value="" id="answers[13042].id" />
<ul>
	<li>
			<input group="13042" type="radio" id="13042_0" name="answers[13042].value" value="10275"  class="selection question_radio_13042"  />		<label for="13042_0">多于30位</label>
	</li>
	<li>
			<input group="13042" type="radio" id="13042_1" name="answers[13042].value" value="10276"  class="selection question_radio_13042"  />		<label for="13042_1">20~30位</label>
	</li>
	<li>
			<input group="13042" type="radio" id="13042_2" name="answers[13042].value" value="10277"  class="selection question_radio_13042"  />		<label for="13042_2">10~20位</label>
	</li>
	<li>
			<input group="13042" type="radio" id="13042_3" name="answers[13042].value" value="10278"  class="selection question_radio_13042"  />		<label for="13042_3">5~10位</label>
	</li>
	<li>
			<input group="13042" type="radio" id="13042_4" name="answers[13042].value" value="10279"  class="selection question_radio_13042"  />		<label for="13042_4">5位以下</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13042  qc_0 radio" type="radio" name="answers[13042].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2659" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您家庭每个月收入水平？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13043].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13043].id" value="" id="answers[13043].id" />
<ul>
	<li>
			<input group="13043" type="radio" id="13043_0" name="answers[13043].value" value="10280"  class="selection question_radio_13043"  />		<label for="13043_0">￥5,000以下</label>
	</li>
	<li>
			<input group="13043" type="radio" id="13043_1" name="answers[13043].value" value="10281"  class="selection question_radio_13043"  />		<label for="13043_1">￥5,000～10,000</label>
	</li>
	<li>
			<input group="13043" type="radio" id="13043_2" name="answers[13043].value" value="10282"  class="selection question_radio_13043"  />		<label for="13043_2">￥10,000～15,000</label>
	</li>
	<li>
			<input group="13043" type="radio" id="13043_3" name="answers[13043].value" value="10283"  class="selection question_radio_13043"  />		<label for="13043_3">￥15,000～20,000</label>
	</li>
	<li>
			<input group="13043" type="radio" id="13043_4" name="answers[13043].value" value="10284"  class="selection question_radio_13043"  />		<label for="13043_4">￥20,000～25,000</label>
	</li>
	<li>
			<input group="13043" type="radio" id="13043_5" name="answers[13043].value" value="10285"  class="selection question_radio_13043"  />		<label for="13043_5">￥25,000以上</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13043  qc_0 radio" type="radio" name="answers[13043].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2750" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						如果你的子女有机会参加英孚的课程，以下哪个校区比较方便？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13044].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13044].id" value="" id="answers[13044].id" />
<ul>
	<li>
			<input group="13044" type="radio" id="13044_0" name="answers[13044].value" value="10699"  class="selection question_radio_13044"  />		<label for="13044_0">徐汇太原路  上海徐汇区太原路167号</label>
	</li>
	<li>
			<input group="13044" type="radio" id="13044_1" name="answers[13044].value" value="10700"  class="selection question_radio_13044"  />		<label for="13044_1">华润时代广场  上海浦东张扬路500号华润时代广场613室</label>
	</li>
	<li>
			<input group="13044" type="radio" id="13044_2" name="answers[13044].value" value="10701"  class="selection question_radio_13044"  />		<label for="13044_2">莘庄仲盛   都市路5001号仲盛世界商城5楼</label>
	</li>
	<li>
			<input group="13044" type="radio" id="13044_3" name="answers[13044].value" value="10702"  class="selection question_radio_13044"  />		<label for="13044_3">闵行顾戴路  上海市闵行区顾戴路(近龙茗路)1178弄58-60号</label>
	</li>
	<li>
			<input group="13044" type="radio" id="13044_4" name="answers[13044].value" value="10703"  class="selection question_radio_13044"  />		<label for="13044_4">普陀中远两湾城  上海普陀区中潭路91弄19号（小区内）临近中山北路</label>
	</li>
	<li>
			<input group="13044" type="radio" id="13044_5" name="answers[13044].value" value="10704"  class="selection question_radio_13044"  />		<label for="13044_5">徐汇宜山路  上海徐汇区宜山路675号</label>
	</li>
	<li>
			<input group="13044" type="radio" id="13044_6" name="answers[13044].value" value="10705"  class="selection question_radio_13044"  />		<label for="13044_6">杨浦五角场  上海市杨浦区四平路2162号3楼</label>
	</li>
	<li>
			<input group="13044" type="radio" id="13044_7" name="answers[13044].value" value="10706"  class="selection question_radio_13044"  />		<label for="13044_7">长宁西郊百联  上海长宁区仙霞西路88号百联西郊购物中心一楼1315室</label>
	</li>
	<li>
			<input group="13044" type="radio" id="13044_8" name="answers[13044].value" value="10707"  class="selection question_radio_13044"  />		<label for="13044_8">黄浦西藏南路  上海市黄浦区瞿溪路405号（西藏南路口）</label>
	</li>
	<li>
			<input group="13044" type="radio" id="13044_9" name="answers[13044].value" value="10708"  class="selection question_radio_13044"  />		<label for="13044_9">浦东金桥枣庄路  上海浦东博山东路560弄12号（近枣庄路）</label>
	</li>
	<li>
			<input group="13044" type="radio" id="13044_10" name="answers[13044].value" value="10709"  class="selection question_radio_13044"  />		<label for="13044_10">长宁中山公园  上海长宁路1158号贝多芬广场4楼</label>
	</li>
	<li>
			<input group="13044" type="radio" id="13044_11" name="answers[13044].value" value="10710"  class="selection question_radio_13044"  />		<label for="13044_11">越秀环市东  水荫路2号华信大厦东座3楼</label>
	</li>
	<li>
			<input group="13044" type="radio" id="13044_12" name="answers[13044].value" value="10711"  class="selection question_radio_13044"  />		<label for="13044_12">其他(请填写)</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13044  qc_0 radio" type="radio" name="answers[13044].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2751" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他校区
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13045].id" value="" id="answers[13045].id" />
<input type="text" name="answers[13045].value" value="" id="question_13045" group="13045" class="input-text" />

<span class="error-content" id="err_answers[13045].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("13046");
// ]]>
-->
</script>
		  <div id="q_2088" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						姓名:
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13046].id" value="" id="answers[13046].id" />
<input type="text" name="answers[13046].value" value="" id="question_13046" group="13046" class="input-text" />

<span class="error-content" id="err_answers[13046].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("13047");
// ]]>
-->
</script>
		  <div id="q_2663" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						邮箱(我们会通过邮件和短信通知入选活动者):
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13047].id" value="" id="answers[13047].id" />
<input type="text" name="answers[13047].value" value="" id="question_13047" group="13047" class="input-text" />

<span class="error-content" id="err_answers[13047].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("13048");
// ]]>
-->
</script>
		  <div id="q_2664" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						手机:
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13048].id" value="" id="answers[13048].id" />
<input type="text" name="answers[13048].value" value="" id="question_13048" group="13048" class="input-text" />

<span class="error-content" id="err_answers[13048].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="Submit" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = 'Mandatory questions must be filled out';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = 'Can not submit empty questionnaire form';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[


	 Element.hide("q_2640");
	 Element.hide("q_2748");
	 Element.hide("q_2653");
	 Element.hide("q_2655");
	 Element.hide("q_2751");


var myrules = {
	   
	   "input#13044_10": function(el){
			el.onclick = function(){
				if ($("13044_10").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13031_2": function(el){
			el.onclick = function(){
				if ($("13031_2").checked){
						Element.hide($("q_2640"));
				}
			}
		}
	,
	   
	   "input#13035_4": function(el){
			el.onclick = function(){
				if ($("13035_4").checked){
						Element.hide($("q_2653"));
				}
			}
		}
	,
	   
	   "input#13044_3": function(el){
			el.onclick = function(){
				if ($("13044_3").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13044_6": function(el){
			el.onclick = function(){
				if ($("13044_6").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13035_5": function(el){
			el.onclick = function(){
				if ($("13035_5").checked){
						Element.hide($("q_2653"));
				}
			}
		}
	,
	   
	   "input#13044_12": function(el){
			el.onclick = function(){
				if ($("13044_12").checked){
						Element.show($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13031_3": function(el){
			el.onclick = function(){
				if ($("13031_3").checked){
						Element.hide($("q_2640"));
				}
			}
		}
	,
	   
	   "input#13037_3": function(el){
			el.onclick = function(){
				if ($("13037_3").checked){
						Element.show($("q_2655"));
				}
			}
		}
	,
	   
	   "input#13044_4": function(el){
			el.onclick = function(){
				if ($("13044_4").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13044_7": function(el){
			el.onclick = function(){
				if ($("13044_7").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13035_2": function(el){
			el.onclick = function(){
				if ($("13035_2").checked){
						Element.hide($("q_2653"));
				}
			}
		}
	,
	   
	   "input#13044_11": function(el){
			el.onclick = function(){
				if ($("13044_11").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13044_1": function(el){
			el.onclick = function(){
				if ($("13044_1").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13031_1": function(el){
			el.onclick = function(){
				if ($("13031_1").checked){
						Element.hide($("q_2640"));
				}
			}
		}
	,
	   
	   "input#13044_5": function(el){
			el.onclick = function(){
				if ($("13044_5").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13035_7": function(el){
			el.onclick = function(){
				if ($("13035_7").checked){
						Element.show($("q_2653"));
				}
			}
		}
	,
	   
	   "input#13044_2": function(el){
			el.onclick = function(){
				if ($("13044_2").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13044_9": function(el){
			el.onclick = function(){
				if ($("13044_9").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13044_0": function(el){
			el.onclick = function(){
				if ($("13044_0").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13035_0": function(el){
			el.onclick = function(){
				if ($("13035_0").checked){
						Element.hide($("q_2653"));
				}
			}
		}
	,
	   
	   "input#13031_4": function(el){
			el.onclick = function(){
				if ($("13031_4").checked){
						Element.show($("q_2640"));
				}
			}
		}
	,
	   
	   "input#13033_7": function(el){
			el.onclick = function(){
				if ($("13033_7").checked){
						Element.show($("q_2748"));
				}
			}
		}
	,
	   
	   "input#13035_1": function(el){
			el.onclick = function(){
				if ($("13035_1").checked){
						Element.hide($("q_2653"));
				}
			}
		}
	,
	   
	   "input#13031_0": function(el){
			el.onclick = function(){
				if ($("13031_0").checked){
						Element.hide($("q_2640"));
				}
			}
		}
	,
	   
	   "input#13035_6": function(el){
			el.onclick = function(){
				if ($("13035_6").checked){
						Element.hide($("q_2653"));
				}
			}
		}
	,
	   
	   "input#13044_8": function(el){
			el.onclick = function(){
				if ($("13044_8").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13035_3": function(el){
			el.onclick = function(){
				if ($("13035_3").checked){
						Element.hide($("q_2653"));
				}
			}
		}
}

Behaviour.register(myrules);

Framework.registerAjaxSensors();
// ]]>
-->
</script>
