	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/691" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />
<input type="hidden" name="surveyId" value="3NQKBi3P49S8"/>

<div class="mandatory"><span style="color: red;">* </span>- It is mandatory</div>
<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2722" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请描述一下你现在的生活状态
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13089].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13089].id" value="" id="answers[13089].id" />
<ul>
	<li>
			<input group="13089" type="radio" id="13089_0" name="answers[13089].value" value="10565"  class="selection question_radio_13089"  />		<label for="13089_0">我是女性，没有结婚</label>
	</li>
	<li>
			<input group="13089" type="radio" id="13089_1" name="answers[13089].value" value="10566"  class="selection question_radio_13089"  />		<label for="13089_1">我是女性，已婚</label>
	</li>
	<li>
			<input group="13089" type="radio" id="13089_2" name="answers[13089].value" value="10567"  class="selection question_radio_13089"  />		<label for="13089_2">我是男性，没有结婚</label>
	</li>
	<li>
			<input group="13089" type="radio" id="13089_3" name="answers[13089].value" value="10568"  class="selection question_radio_13089"  />		<label for="13089_3">我是男性，已婚</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13089  qc_0 radio" type="radio" name="answers[13089].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2723" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你有孩子吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13090].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13090].id" value="" id="answers[13090].id" />
<ul>
	<li>
			<input group="13090" type="radio" id="13090_0" name="answers[13090].value" value="10569"  class="selection question_radio_13090"  />		<label for="13090_0">没有</label>
	</li>
	<li>
			<input group="13090" type="radio" id="13090_1" name="answers[13090].value" value="10570"  class="selection question_radio_13090"  />		<label for="13090_1">是的，我有一个孩子</label>
	</li>
	<li>
			<input group="13090" type="radio" id="13090_2" name="answers[13090].value" value="10571"  class="selection question_radio_13090"  />		<label for="13090_2">是的，我有超过一个孩子</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13090  qc_0 radio" type="radio" name="answers[13090].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2724" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你的孩子多大了？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13091].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13091].id" value="" id="answers[13091].id" />
<ul>
	<li>
			<input group="13091" type="radio" id="13091_0" name="answers[13091].value" value="10572"  class="selection question_radio_13091"  />		<label for="13091_0">0-2岁</label>
	</li>
	<li>
			<input group="13091" type="radio" id="13091_1" name="answers[13091].value" value="10573"  class="selection question_radio_13091"  />		<label for="13091_1">3-5岁</label>
	</li>
	<li>
			<input group="13091" type="radio" id="13091_2" name="answers[13091].value" value="10574"  class="selection question_radio_13091"  />		<label for="13091_2">6-9岁</label>
	</li>
	<li>
			<input group="13091" type="radio" id="13091_3" name="answers[13091].value" value="10575"  class="selection question_radio_13091"  />		<label for="13091_3">10-12岁</label>
	</li>
	<li>
			<input group="13091" type="radio" id="13091_4" name="answers[13091].value" value="10576"  class="selection question_radio_13091"  />		<label for="13091_4">&gt;12岁</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13091  qc_0 radio" type="radio" name="answers[13091].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2725" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你孩子的性别是？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13092].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13092].id" value="" id="answers[13092].id" />
<ul>
	<li>
			<input group="13092" type="radio" id="13092_0" name="answers[13092].value" value="10577"  class="selection question_radio_13092"  />		<label for="13092_0">女孩</label>
	</li>
	<li>
			<input group="13092" type="radio" id="13092_1" name="answers[13092].value" value="10578"  class="selection question_radio_13092"  />		<label for="13092_1">男孩</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13092  qc_0 radio" type="radio" name="answers[13092].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2726" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你的孩子吃零食吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13093].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13093].id" value="" id="answers[13093].id" />
<ul>
	<li>
			<input group="13093" type="radio" id="13093_0" name="answers[13093].value" value="10579"  class="selection question_radio_13093"  />		<label for="13093_0">从来不吃</label>
	</li>
	<li>
			<input group="13093" type="radio" id="13093_1" name="answers[13093].value" value="10580"  class="selection question_radio_13093"  />		<label for="13093_1">吃，每周少于一到两次</label>
	</li>
	<li>
			<input group="13093" type="radio" id="13093_2" name="answers[13093].value" value="10581"  class="selection question_radio_13093"  />		<label for="13093_2">吃，每周多于两次</label>
	</li>
	<li>
			<input group="13093" type="radio" id="13093_3" name="answers[13093].value" value="10582"  class="selection question_radio_13093"  />		<label for="13093_3">每天都吃</label>
	</li>
	<li>
			<input group="13093" type="radio" id="13093_4" name="answers[13093].value" value="10583"  class="selection question_radio_13093"  />		<label for="13093_4">一天吃很多次</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13093  qc_0 radio" type="radio" name="answers[13093].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2727" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问在您家里，在决定购买给孩子吃的各类零食的时候，以下哪句话最适合描述您的情况？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13094].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13094].id" value="" id="answers[13094].id" />
<ul>
	<li>
			<input group="13094" type="radio" id="13094_0" name="answers[13094].value" value="10584"  class="selection question_radio_13094"  />		<label for="13094_0">完全由我自己决定</label>
	</li>
	<li>
			<input group="13094" type="radio" id="13094_1" name="answers[13094].value" value="10585"  class="selection question_radio_13094"  />		<label for="13094_1">大多数由我自己決定，偶尔由家庭中的其他人决定</label>
	</li>
	<li>
			<input group="13094" type="radio" id="13094_2" name="answers[13094].value" value="10586"  class="selection question_radio_13094"  />		<label for="13094_2">有時候由我决定，有時候由家庭中的其他人决定</label>
	</li>
	<li>
			<input group="13094" type="radio" id="13094_3" name="answers[13094].value" value="10587"  class="selection question_radio_13094"  />		<label for="13094_3">大多数由家庭中的其他人决定</label>
	</li>
	<li>
			<input group="13094" type="radio" id="13094_4" name="answers[13094].value" value="10588"  class="selection question_radio_13094"  />		<label for="13094_4">完全由家庭中的其他人决定</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13094  qc_0 radio" type="radio" name="answers[13094].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2728" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问以下那句话最适合用来形容你平时给孩子购买各类食品和饮料时的情况？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13095].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13095].id" value="" id="answers[13095].id" />
<ul>
	<li>
			<input group="13095" type="radio" id="13095_0" name="answers[13095].value" value="10589"  class="selection question_radio_13095"  />		<label for="13095_0">我决定买什么，并且由我来购买</label>
	</li>
	<li>
			<input group="13095" type="radio" id="13095_1" name="answers[13095].value" value="10590"  class="selection question_radio_13095"  />		<label for="13095_1">我和孩子共同决定买什么，并且由我来购买</label>
	</li>
	<li>
			<input group="13095" type="radio" id="13095_2" name="answers[13095].value" value="10591"  class="selection question_radio_13095"  />		<label for="13095_2">孩子自己决定买什么，并且由我来购买，我一般知道他为什么要买这个产品</label>
	</li>
	<li>
			<input group="13095" type="radio" id="13095_3" name="answers[13095].value" value="10592"  class="selection question_radio_13095"  />		<label for="13095_3">孩子自己决定买什么，产品由我来购买，但我一般不了解他为什么要买这个产品</label>
	</li>
	<li>
			<input group="13095" type="radio" id="13095_4" name="answers[13095].value" value="10593"  class="selection question_radio_13095"  />		<label for="13095_4">孩子自己决定买什么，并且由他自己购买</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13095  qc_0 radio" type="radio" name="answers[13095].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2729" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你的孩子一般吃什么种类的零食？(多选)
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13096].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13096].id" value="" id="answers[13096].id" />




<span id="hint_13096">
</span>
<ul>
	<li>
			<input group="13096" class="question_radio_13096 selection" type="checkbox" id="13096_0" name="answers[13096].value" value="10594" 	onclick=" "/>		<label for="13096_0">巧克力</label>
	</li>
	<li>
			<input group="13096" class="question_radio_13096 selection" type="checkbox" id="13096_1" name="answers[13096].value" value="10595" 	onclick=" "/>		<label for="13096_1">饼干</label>
	</li>
	<li>
			<input group="13096" class="question_radio_13096 selection" type="checkbox" id="13096_2" name="answers[13096].value" value="10596" 	onclick=" "/>		<label for="13096_2">面包，蛋糕，派，馅饼</label>
	</li>
	<li>
			<input group="13096" class="question_radio_13096 selection" type="checkbox" id="13096_3" name="answers[13096].value" value="10597" 	onclick=" "/>		<label for="13096_3">糖果</label>
	</li>
	<li>
			<input group="13096" class="question_radio_13096 selection" type="checkbox" id="13096_4" name="answers[13096].value" value="10598" 	onclick=" "/>		<label for="13096_4">奶制品</label>
	</li>
	<li>
			<input group="13096" class="question_radio_13096 selection" type="checkbox" id="13096_5" name="answers[13096].value" value="10599" 	onclick=" "/>		<label for="13096_5">薯片，爆米花</label>
	</li>
	<li>
			<input group="13096" class="question_radio_13096 selection" type="checkbox" id="13096_6" name="answers[13096].value" value="10600" 	onclick=" "/>		<label for="13096_6">坚果，瓜子，干果</label>
	</li>
	<li>
			<input group="13096" class="question_radio_13096 selection" type="checkbox" id="13096_7" name="answers[13096].value" value="10601" 	onclick=" "/>		<label for="13096_7">肉类休闲食品</label>
	</li>
	<li>
			<input group="13096" class="question_radio_13096 selection" type="checkbox" id="13096_8" name="answers[13096].value" value="10602" 	onclick=" "/>		<label for="13096_8">其他</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2730" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他种类
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13097].id" value="" id="answers[13097].id" />
<input type="text" name="answers[13097].value" value="" id="question_13097" group="13097" class="input-text" />

<span class="error-content" id="err_answers[13097].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2731" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在过去的三个月里，你为你的孩子买的零食有哪些？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13098].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13098].id" value="" id="answers[13098].id" />




<span id="hint_13098">
</span>
<ul>
	<li>
			<input group="13098" class="question_radio_13098 selection" type="checkbox" id="13098_0" name="answers[13098].value" value="10603" 	onclick=" "/>		<label for="13098_0">好丽友好多鱼</label>
	</li>
	<li>
			<input group="13098" class="question_radio_13098 selection" type="checkbox" id="13098_1" name="answers[13098].value" value="10604" 	onclick=" "/>		<label for="13098_1">格力高百奇</label>
	</li>
	<li>
			<input group="13098" class="question_radio_13098 selection" type="checkbox" id="13098_2" name="answers[13098].value" value="10605" 	onclick=" "/>		<label for="13098_2">好丽友蘑菇力</label>
	</li>
	<li>
			<input group="13098" class="question_radio_13098 selection" type="checkbox" id="13098_3" name="answers[13098].value" value="10606" 	onclick=" "/>		<label for="13098_3">格力高百醇</label>
	</li>
	<li>
			<input group="13098" class="question_radio_13098 selection" type="checkbox" id="13098_4" name="answers[13098].value" value="10607" 	onclick=" "/>		<label for="13098_4">乐天小熊</label>
	</li>
	<li>
			<input group="13098" class="question_radio_13098 selection" type="checkbox" id="13098_5" name="answers[13098].value" value="10608" 	onclick=" "/>		<label for="13098_5">奥利奥</label>
	</li>
	<li>
			<input group="13098" class="question_radio_13098 selection" type="checkbox" id="13098_6" name="answers[13098].value" value="10609" 	onclick=" "/>		<label for="13098_6">百力滋</label>
	</li>
	<li>
			<input group="13098" class="question_radio_13098 selection" type="checkbox" id="13098_7" name="answers[13098].value" value="10610" 	onclick=" "/>		<label for="13098_7">泡吧小脆</label>
	</li>
	<li>
			<input group="13098" class="question_radio_13098 selection" type="checkbox" id="13098_8" name="answers[13098].value" value="10611" 	onclick=" "/>		<label for="13098_8">菜园小饼</label>
	</li>
	<li>
			<input group="13098" class="question_radio_13098 selection" type="checkbox" id="13098_9" name="answers[13098].value" value="10612" 	onclick=" "/>		<label for="13098_9">旺旺系列食品</label>
	</li>
	<li>
			<input group="13098" class="question_radio_13098 selection" type="checkbox" id="13098_10" name="answers[13098].value" value="10613" 	onclick=" "/>		<label for="13098_10">优冠早餐馅饼</label>
	</li>
	<li>
			<input group="13098" class="question_radio_13098 selection" type="checkbox" id="13098_11" name="answers[13098].value" value="10614" 	onclick=" "/>		<label for="13098_11">卡夫小王子</label>
	</li>
	<li>
			<input group="13098" class="question_radio_13098 selection" type="checkbox" id="13098_12" name="answers[13098].value" value="10615" 	onclick=" "/>		<label for="13098_12">正航熊仔饼</label>
	</li>
	<li>
			<input group="13098" class="question_radio_13098 selection" type="checkbox" id="13098_13" name="answers[13098].value" value="10616" 	onclick=" "/>		<label for="13098_13">其他</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2732" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他零食
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13099].id" value="" id="answers[13099].id" />
<input type="text" name="answers[13099].value" value="" id="question_13099" group="13099" class="input-text" />

<span class="error-content" id="err_answers[13099].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2733" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你为孩子最经常购买的零食是什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13100].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13100].id" value="" id="answers[13100].id" />
<ul>
	<li>
			<input group="13100" type="radio" id="13100_0" name="answers[13100].value" value="10617"  class="selection question_radio_13100"  />		<label for="13100_0">好丽友好多鱼</label>
	</li>
	<li>
			<input group="13100" type="radio" id="13100_1" name="answers[13100].value" value="10618"  class="selection question_radio_13100"  />		<label for="13100_1">格力高百奇</label>
	</li>
	<li>
			<input group="13100" type="radio" id="13100_2" name="answers[13100].value" value="10619"  class="selection question_radio_13100"  />		<label for="13100_2">好丽友蘑菇力</label>
	</li>
	<li>
			<input group="13100" type="radio" id="13100_3" name="answers[13100].value" value="10620"  class="selection question_radio_13100"  />		<label for="13100_3">格力高百醇</label>
	</li>
	<li>
			<input group="13100" type="radio" id="13100_4" name="answers[13100].value" value="10621"  class="selection question_radio_13100"  />		<label for="13100_4">乐天小熊</label>
	</li>
	<li>
			<input group="13100" type="radio" id="13100_5" name="answers[13100].value" value="10622"  class="selection question_radio_13100"  />		<label for="13100_5">奥利奥</label>
	</li>
	<li>
			<input group="13100" type="radio" id="13100_6" name="answers[13100].value" value="10623"  class="selection question_radio_13100"  />		<label for="13100_6">百力滋</label>
	</li>
	<li>
			<input group="13100" type="radio" id="13100_7" name="answers[13100].value" value="10624"  class="selection question_radio_13100"  />		<label for="13100_7">泡吧小脆</label>
	</li>
	<li>
			<input group="13100" type="radio" id="13100_8" name="answers[13100].value" value="10625"  class="selection question_radio_13100"  />		<label for="13100_8">菜园小饼</label>
	</li>
	<li>
			<input group="13100" type="radio" id="13100_9" name="answers[13100].value" value="10626"  class="selection question_radio_13100"  />		<label for="13100_9">旺旺系列食品</label>
	</li>
	<li>
			<input group="13100" type="radio" id="13100_10" name="answers[13100].value" value="10627"  class="selection question_radio_13100"  />		<label for="13100_10">优冠早餐馅饼</label>
	</li>
	<li>
			<input group="13100" type="radio" id="13100_11" name="answers[13100].value" value="10628"  class="selection question_radio_13100"  />		<label for="13100_11">卡夫小王子</label>
	</li>
	<li>
			<input group="13100" type="radio" id="13100_12" name="answers[13100].value" value="10629"  class="selection question_radio_13100"  />		<label for="13100_12">正航熊仔饼</label>
	</li>
	<li>
			<input group="13100" type="radio" id="13100_13" name="answers[13100].value" value="10630"  class="selection question_radio_13100"  />		<label for="13100_13">其他</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13100  qc_0 radio" type="radio" name="answers[13100].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2734" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他零食(最经常买的)
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13101].id" value="" id="answers[13101].id" />
<input type="text" name="answers[13101].value" value="" id="question_13101" group="13101" class="input-text" />

<span class="error-content" id="err_answers[13101].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2735" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问在过去的三个月里你的孩子吃过一下哪些食品？(多选)
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13102].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13102].id" value="" id="answers[13102].id" />




<span id="hint_13102">
</span>
<ul>
	<li>
			<input group="13102" class="question_radio_13102 selection" type="checkbox" id="13102_0" name="answers[13102].value" value="10631" 	onclick=" "/>		<label for="13102_0">好丽友好多鱼</label>
	</li>
	<li>
			<input group="13102" class="question_radio_13102 selection" type="checkbox" id="13102_1" name="answers[13102].value" value="10632" 	onclick=" "/>		<label for="13102_1">格力高百奇</label>
	</li>
	<li>
			<input group="13102" class="question_radio_13102 selection" type="checkbox" id="13102_2" name="answers[13102].value" value="10633" 	onclick=" "/>		<label for="13102_2">好丽友蘑菇力</label>
	</li>
	<li>
			<input group="13102" class="question_radio_13102 selection" type="checkbox" id="13102_3" name="answers[13102].value" value="10634" 	onclick=" "/>		<label for="13102_3">格力高百醇</label>
	</li>
	<li>
			<input group="13102" class="question_radio_13102 selection" type="checkbox" id="13102_4" name="answers[13102].value" value="10635" 	onclick=" "/>		<label for="13102_4">乐天小熊</label>
	</li>
	<li>
			<input group="13102" class="question_radio_13102 selection" type="checkbox" id="13102_5" name="answers[13102].value" value="10636" 	onclick=" "/>		<label for="13102_5">奥利奥</label>
	</li>
	<li>
			<input group="13102" class="question_radio_13102 selection" type="checkbox" id="13102_6" name="answers[13102].value" value="10637" 	onclick=" "/>		<label for="13102_6">百力滋</label>
	</li>
	<li>
			<input group="13102" class="question_radio_13102 selection" type="checkbox" id="13102_7" name="answers[13102].value" value="10638" 	onclick=" "/>		<label for="13102_7">泡吧小脆</label>
	</li>
	<li>
			<input group="13102" class="question_radio_13102 selection" type="checkbox" id="13102_8" name="answers[13102].value" value="10639" 	onclick=" "/>		<label for="13102_8">菜园小饼</label>
	</li>
	<li>
			<input group="13102" class="question_radio_13102 selection" type="checkbox" id="13102_9" name="answers[13102].value" value="10640" 	onclick=" "/>		<label for="13102_9">旺旺系列食品</label>
	</li>
	<li>
			<input group="13102" class="question_radio_13102 selection" type="checkbox" id="13102_10" name="answers[13102].value" value="10641" 	onclick=" "/>		<label for="13102_10">优冠早餐馅饼</label>
	</li>
	<li>
			<input group="13102" class="question_radio_13102 selection" type="checkbox" id="13102_11" name="answers[13102].value" value="10642" 	onclick=" "/>		<label for="13102_11">卡夫小王子</label>
	</li>
	<li>
			<input group="13102" class="question_radio_13102 selection" type="checkbox" id="13102_12" name="answers[13102].value" value="10643" 	onclick=" "/>		<label for="13102_12">正航熊仔饼</label>
	</li>
	<li>
			<input group="13102" class="question_radio_13102 selection" type="checkbox" id="13102_13" name="answers[13102].value" value="10644" 	onclick=" "/>		<label for="13102_13">其他</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2736" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他零食(吃过的)
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13103].id" value="" id="answers[13103].id" />
<input type="text" name="answers[13103].value" value="" id="question_13103" group="13103" class="input-text" />

<span class="error-content" id="err_answers[13103].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2737" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你的孩子最经常吃的零食是什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13104].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13104].id" value="" id="answers[13104].id" />
<ul>
	<li>
			<input group="13104" type="radio" id="13104_0" name="answers[13104].value" value="10645"  class="selection question_radio_13104"  />		<label for="13104_0">好丽友好多鱼</label>
	</li>
	<li>
			<input group="13104" type="radio" id="13104_1" name="answers[13104].value" value="10646"  class="selection question_radio_13104"  />		<label for="13104_1">格力高百奇</label>
	</li>
	<li>
			<input group="13104" type="radio" id="13104_2" name="answers[13104].value" value="10647"  class="selection question_radio_13104"  />		<label for="13104_2">好丽友蘑菇力</label>
	</li>
	<li>
			<input group="13104" type="radio" id="13104_3" name="answers[13104].value" value="10648"  class="selection question_radio_13104"  />		<label for="13104_3">格力高百醇</label>
	</li>
	<li>
			<input group="13104" type="radio" id="13104_4" name="answers[13104].value" value="10649"  class="selection question_radio_13104"  />		<label for="13104_4">乐天小熊</label>
	</li>
	<li>
			<input group="13104" type="radio" id="13104_5" name="answers[13104].value" value="10650"  class="selection question_radio_13104"  />		<label for="13104_5">奥利奥</label>
	</li>
	<li>
			<input group="13104" type="radio" id="13104_6" name="answers[13104].value" value="10651"  class="selection question_radio_13104"  />		<label for="13104_6">百力滋</label>
	</li>
	<li>
			<input group="13104" type="radio" id="13104_7" name="answers[13104].value" value="10652"  class="selection question_radio_13104"  />		<label for="13104_7">泡吧小脆</label>
	</li>
	<li>
			<input group="13104" type="radio" id="13104_8" name="answers[13104].value" value="10653"  class="selection question_radio_13104"  />		<label for="13104_8">菜园小饼</label>
	</li>
	<li>
			<input group="13104" type="radio" id="13104_9" name="answers[13104].value" value="10654"  class="selection question_radio_13104"  />		<label for="13104_9">旺旺系列食品</label>
	</li>
	<li>
			<input group="13104" type="radio" id="13104_10" name="answers[13104].value" value="10655"  class="selection question_radio_13104"  />		<label for="13104_10">优冠早餐馅饼</label>
	</li>
	<li>
			<input group="13104" type="radio" id="13104_11" name="answers[13104].value" value="10656"  class="selection question_radio_13104"  />		<label for="13104_11">卡夫小王子</label>
	</li>
	<li>
			<input group="13104" type="radio" id="13104_12" name="answers[13104].value" value="10657"  class="selection question_radio_13104"  />		<label for="13104_12">正航熊仔饼</label>
	</li>
	<li>
			<input group="13104" type="radio" id="13104_13" name="answers[13104].value" value="10658"  class="selection question_radio_13104"  />		<label for="13104_13">其他</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13104  qc_0 radio" type="radio" name="answers[13104].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2738" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他零食(最经常吃的)
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13105].id" value="" id="answers[13105].id" />
<input type="text" name="answers[13105].value" value="" id="question_13105" group="13105" class="input-text" />

<span class="error-content" id="err_answers[13105].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2739" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						一般来说，谁给你的孩子零食？(多选)
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13106].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13106].id" value="" id="answers[13106].id" />




<span id="hint_13106">
</span>
<ul>
	<li>
			<input group="13106" class="question_radio_13106 selection" type="checkbox" id="13106_0" name="answers[13106].value" value="10659" 	onclick=" "/>		<label for="13106_0">我给她/他</label>
	</li>
	<li>
			<input group="13106" class="question_radio_13106 selection" type="checkbox" id="13106_1" name="answers[13106].value" value="10660" 	onclick=" "/>		<label for="13106_1">她/他自己买</label>
	</li>
	<li>
			<input group="13106" class="question_radio_13106 selection" type="checkbox" id="13106_2" name="answers[13106].value" value="10661" 	onclick=" "/>		<label for="13106_2">同学或玩伴给她/他</label>
	</li>
	<li>
			<input group="13106" class="question_radio_13106 selection" type="checkbox" id="13106_3" name="answers[13106].value" value="10662" 	onclick=" "/>		<label for="13106_3">家人给她/他</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2740" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你有多少朋友的孩子和你的孩子年纪相仿？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13107].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13107].id" value="" id="answers[13107].id" />
<ul>
	<li>
			<input group="13107" type="radio" id="13107_0" name="answers[13107].value" value="10663"  class="selection question_radio_13107"  />		<label for="13107_0">无</label>
	</li>
	<li>
			<input group="13107" type="radio" id="13107_1" name="answers[13107].value" value="10664"  class="selection question_radio_13107"  />		<label for="13107_1">1或2个</label>
	</li>
	<li>
			<input group="13107" type="radio" id="13107_2" name="answers[13107].value" value="10665"  class="selection question_radio_13107"  />		<label for="13107_2">3或4个</label>
	</li>
	<li>
			<input group="13107" type="radio" id="13107_3" name="answers[13107].value" value="10666"  class="selection question_radio_13107"  />		<label for="13107_3">5或6个</label>
	</li>
	<li>
			<input group="13107" type="radio" id="13107_4" name="answers[13107].value" value="10667"  class="selection question_radio_13107"  />		<label for="13107_4">&gt;6</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13107  qc_0 radio" type="radio" name="answers[13107].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2741" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你愿意与我们分享一些你的孩子对于零食的意见吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13108].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13108].id" value="" id="answers[13108].id" />
<ul>
	<li>
			<input group="13108" type="radio" id="13108_0" name="answers[13108].value" value="10668"  class="selection question_radio_13108"  />		<label for="13108_0">是</label>
	</li>
	<li>
			<input group="13108" type="radio" id="13108_1" name="answers[13108].value" value="10669"  class="selection question_radio_13108"  />		<label for="13108_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13108  qc_0 radio" type="radio" name="answers[13108].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2742" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你和你的朋友平时是否会讨论孩子所吃的零食吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13109].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13109].id" value="" id="answers[13109].id" />
<ul>
	<li>
			<input group="13109" type="radio" id="13109_0" name="answers[13109].value" value="10670"  class="selection question_radio_13109"  />		<label for="13109_0">是的，非常频繁</label>
	</li>
	<li>
			<input group="13109" type="radio" id="13109_1" name="answers[13109].value" value="10671"  class="selection question_radio_13109"  />		<label for="13109_1">是的，经常</label>
	</li>
	<li>
			<input group="13109" type="radio" id="13109_2" name="answers[13109].value" value="10672"  class="selection question_radio_13109"  />		<label for="13109_2">是的，有时候</label>
	</li>
	<li>
			<input group="13109" type="radio" id="13109_3" name="answers[13109].value" value="10673"  class="selection question_radio_13109"  />		<label for="13109_3">是的，很少</label>
	</li>
	<li>
			<input group="13109" type="radio" id="13109_4" name="answers[13109].value" value="10674"  class="selection question_radio_13109"  />		<label for="13109_4">从来不</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13109  qc_0 radio" type="radio" name="answers[13109].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("13110");
// ]]>
-->
</script>
		  <div id="q_2743" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的年龄
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13110].id" value="" id="answers[13110].id" />
<input type="text" name="answers[13110].value" value="" id="question_13110" group="13110" class="input-text" />

<span class="error-content" id="err_answers[13110].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("13111");
// ]]>
-->
</script>
		  <div id="q_2744" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的姓名
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13111].id" value="" id="answers[13111].id" />
<input type="text" name="answers[13111].value" value="" id="question_13111" group="13111" class="input-text" />

<span class="error-content" id="err_answers[13111].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("13112");
// ]]>
-->
</script>
		  <div id="q_2533" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的邮箱地址
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13112].id" value="" id="answers[13112].id" />
<input type="text" name="answers[13112].value" value="" id="question_13112" group="13112" class="input-text" />

<span class="error-content" id="err_answers[13112].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2534" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的手机号码
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13113].id" value="" id="answers[13113].id" />
<input type="text" name="answers[13113].value" value="" id="question_13113" group="13113" class="input-text" />

<span class="error-content" id="err_answers[13113].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2745" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的家庭年收入
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13114].id" value="" id="answers[13114].id" />
<input type="text" name="answers[13114].value" value="" id="question_13114" group="13114" class="input-text" />

<span class="error-content" id="err_answers[13114].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("13115");
// ]]>
-->
</script>
		  <div id="q_2158" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						城市
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13115].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13115].id" value="" id="answers[13115].id" />

	<select group="13115" class="selection" id="question_13115" name="answers[13115].value" title="title"  size = "1" >
	<option selected="selected" value="0">请选择</option>
<option value="8315" style=""  >鞍山市</option>
<option value="8316" style=""  >蚌埠市</option>
<option value="8317" style=""  >包头市</option>
<option value="8318" style=""  >宝鸡市</option>
<option value="8319" style=""  >保定市</option>
<option value="8320" style=""  >北京市</option>
<option value="8321" style=""  >沧州市</option>
<option value="8322" style=""  >长春市</option>
<option value="8323" style=""  >长沙市</option>
<option value="8324" style=""  >常州市</option>
<option value="8325" style=""  >郴州市</option>
<option value="8326" style=""  >成都市</option>
<option value="8327" style=""  >大理市</option>
<option value="8328" style=""  >大连市</option>
<option value="8329" style=""  >大庆市</option>
<option value="8330" style=""  >大同市</option>
<option value="8331" style=""  >东莞市</option>
<option value="8332" style=""  >佛山市</option>
<option value="8333" style=""  >福州市</option>
<option value="8334" style=""  >抚顺市</option>
<option value="8335" style=""  >广州市</option>
<option value="8336" style=""  >贵阳市</option>
<option value="8337" style=""  >桂林市</option>
<option value="8338" style=""  >哈尔滨市</option>
<option value="8339" style=""  >海口市</option>
<option value="8340" style=""  >杭州市</option>
<option value="8341" style=""  >合肥市</option>
<option value="8342" style=""  >衡阳市</option>
<option value="8343" style=""  >呼和浩特市</option>
<option value="8344" style=""  >惠州市</option>
<option value="8345" style=""  >吉林市</option>
<option value="8346" style=""  >济南市</option>
<option value="8347" style=""  >嘉兴市</option>
<option value="8348" style=""  >江门市</option>
<option value="8349" style=""  >九江市</option>
<option value="8350" style=""  >开封市</option>
<option value="8351" style=""  >昆明市</option>
<option value="8352" style=""  >兰州市</option>
<option value="8353" style=""  >廊坊市</option>
<option value="8354" style=""  >连云港市</option>
<option value="8355" style=""  >洛阳市</option>
<option value="8356" style=""  >马安山市</option>
<option value="8357" style=""  >牡丹江市</option>
<option value="8358" style=""  >南昌市</option>
<option value="8359" style=""  >南京市</option>
<option value="8360" style=""  >南宁市</option>
<option value="8361" style=""  >南通市</option>
<option value="8362" style=""  >宁波市</option>
<option value="8363" style=""  >攀枝花市</option>
<option value="8364" style=""  >平顶山市</option>
<option value="8365" style=""  >齐齐哈尔</option>
<option value="8366" style=""  >秦皇岛市</option>
<option value="8367" style=""  >青岛市</option>
<option value="8368" style=""  >泉州市</option>
<option value="8369" style=""  >汕头市</option>
<option value="8370" style=""  >上海市</option>
<option value="8371" style=""  >绍兴市</option>
<option value="8372" style=""  >深圳市</option>
<option value="8373" style=""  >沈阳市</option>
<option value="8374" style=""  >石家庄市</option>
<option value="8375" style=""  >苏州市</option>
<option value="8376" style=""  >太原市</option>
<option value="8377" style=""  >泰州市</option>
<option value="8378" style=""  >唐山市</option>
<option value="8379" style=""  >天津市</option>
<option value="8380" style=""  >威海市</option>
<option value="8381" style=""  >潍坊市</option>
<option value="8382" style=""  >温州市</option>
<option value="8383" style=""  >乌鲁木齐市</option>
<option value="8384" style=""  >无锡市</option>
<option value="8385" style=""  >芜湖市</option>
<option value="8386" style=""  >武汉市</option>
<option value="8387" style=""  >西安市</option>
<option value="8388" style=""  >西宁市</option>
<option value="8389" style=""  >厦门市</option>
<option value="8390" style=""  >新乡市</option>
<option value="8391" style=""  >徐州市</option>
<option value="8392" style=""  >烟台市</option>
<option value="8393" style=""  >延安市</option>
<option value="8394" style=""  >扬州市</option>
<option value="8395" style=""  >宜宾市</option>
<option value="8396" style=""  >银川市</option>
<option value="8397" style=""  >玉林市</option>
<option value="8398" style=""  >玉溪市</option>
<option value="8399" style=""  >湛江市</option>
<option value="8400" style=""  >漳州市</option>
<option value="8401" style=""  >镇江市</option>
<option value="8402" style=""  >郑州市</option>
<option value="8403" style=""  >中山市</option>
<option value="8404" style=""  >重庆市</option>
<option value="8405" style=""  >珠海市</option>
<option value="8406" style=""  >淄博市</option>
<option value="8407" style=""  >自贡市</option>
<option value="8408" style=""  >遵义市</option>
<option value="8409" style=""  >其他</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2717" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他城市
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13116].id" value="" id="answers[13116].id" />
<input type="text" name="answers[13116].value" value="" id="question_13116" group="13116" class="input-text" />

<span class="error-content" id="err_answers[13116].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="提交" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
	        jQuery("#check-alert-dialog .content").html(html);
	        jQuery("#check-alert-dialog").dialog('open');
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '提交失败：不能提交空报告';
		    jQuery("#check-alert-dialog .content").html(html);
		    jQuery("#check-alert-dialog").dialog('open');
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[


	 Element.hide("q_2730");
	 Element.hide("q_2732");
	 Element.hide("q_2734");
	 Element.hide("q_2736");
	 Element.hide("q_2738");
	 Element.hide("q_2717");


var myrules = {
	   
	   "input#13100_12": function(el){
			el.onclick = function(){
				if ($("13100_12").checked){
						Element.hide($("q_2734"));
				}
			}
		}
	,
	   
	   "input#13100_7": function(el){
			el.onclick = function(){
				if ($("13100_7").checked){
						Element.hide($("q_2734"));
				}
			}
		}
	,
	   
	   "input#13104_11": function(el){
			el.onclick = function(){
				if ($("13104_11").checked){
						Element.hide($("q_2738"));
				}
			}
		}
	,
	   
	   "input#13100_10": function(el){
			el.onclick = function(){
				if ($("13100_10").checked){
						Element.hide($("q_2734"));
				}
			}
		}
	,
	   
	   "input#13104_9": function(el){
			el.onclick = function(){
				if ($("13104_9").checked){
						Element.hide($("q_2738"));
				}
			}
		}
	,
	   
	   "input#13104_4": function(el){
			el.onclick = function(){
				if ($("13104_4").checked){
						Element.hide($("q_2738"));
				}
			}
		}
	,
	   
	   "input#13100_4": function(el){
			el.onclick = function(){
				if ($("13100_4").checked){
						Element.hide($("q_2734"));
				}
			}
		}
	,
	   
	   "input#13104_3": function(el){
			el.onclick = function(){
				if ($("13104_3").checked){
						Element.hide($("q_2738"));
				}
			}
		}
	,
	   
	   "input#13100_5": function(el){
			el.onclick = function(){
				if ($("13100_5").checked){
						Element.hide($("q_2734"));
				}
			}
		}
	,
	   
	   "input#13104_6": function(el){
			el.onclick = function(){
				if ($("13104_6").checked){
						Element.hide($("q_2738"));
				}
			}
		}
	,
	   
	   "input#13104_12": function(el){
			el.onclick = function(){
				if ($("13104_12").checked){
						Element.hide($("q_2738"));
				}
			}
		}
	,
	   
	   "input#13100_9": function(el){
			el.onclick = function(){
				if ($("13100_9").checked){
						Element.hide($("q_2734"));
				}
			}
		}
	,
	   
	   "input#13104_13": function(el){
			el.onclick = function(){
				if ($("13104_13").checked){
						Element.show($("q_2738"));
				}
			}
		}
	,
	   
	   "input#13100_13": function(el){
			el.onclick = function(){
				if ($("13100_13").checked){
						Element.show($("q_2734"));
				}
			}
		}
	,
	   
	   "input#13100_6": function(el){
			el.onclick = function(){
				if ($("13100_6").checked){
						Element.hide($("q_2734"));
				}
			}
		}
	,
	   
	   "input#13104_1": function(el){
			el.onclick = function(){
				if ($("13104_1").checked){
						Element.hide($("q_2738"));
				}
			}
		}
	,
	   
	   "input#13104_7": function(el){
			el.onclick = function(){
				if ($("13104_7").checked){
						Element.hide($("q_2738"));
				}
			}
		}
	,
	   
	   "input#13104_10": function(el){
			el.onclick = function(){
				if ($("13104_10").checked){
						Element.hide($("q_2738"));
				}
			}
		}
	,
	   
	   "input#13104_0": function(el){
			el.onclick = function(){
				if ($("13104_0").checked){
						Element.hide($("q_2738"));
				}
			}
		}
	,
	   
	   "input#13104_8": function(el){
			el.onclick = function(){
				if ($("13104_8").checked){
						Element.hide($("q_2738"));
				}
			}
		}
	,
	   
	   "input#13100_3": function(el){
			el.onclick = function(){
				if ($("13100_3").checked){
						Element.hide($("q_2734"));
				}
			}
		}
	,
	   
	   "input#13096_8": function(el){
			el.onclick = function(){
				if ($("13096_8").checked){
						Element.show($("q_2730"));
				}
			}
		}
	,
	   
	   "input#13104_5": function(el){
			el.onclick = function(){
				if ($("13104_5").checked){
						Element.hide($("q_2738"));
				}
			}
		}
	,
	   
	   "input#13100_8": function(el){
			el.onclick = function(){
				if ($("13100_8").checked){
						Element.hide($("q_2734"));
				}
			}
		}
	,
	   
	   "input#13100_0": function(el){
			el.onclick = function(){
				if ($("13100_0").checked){
						Element.hide($("q_2734"));
				}
			}
		}
	,
	   
	   "input#13100_11": function(el){
			el.onclick = function(){
				if ($("13100_11").checked){
						Element.hide($("q_2734"));
				}
			}
		}
	,
	   
	   "input#13098_13": function(el){
			el.onclick = function(){
				if ($("13098_13").checked){
						Element.show($("q_2732"));
				}
			}
		}
	,
	   
	   "input#13100_1": function(el){
			el.onclick = function(){
				if ($("13100_1").checked){
						Element.hide($("q_2734"));
				}
			}
		}
	,
	   
	   "input#13102_13": function(el){
			el.onclick = function(){
				if ($("13102_13").checked){
						Element.show($("q_2736"));
				}
			}
		}
	,
	   
	   "input#13104_2": function(el){
			el.onclick = function(){
				if ($("13104_2").checked){
						Element.hide($("q_2738"));
				}
			}
		}
	,
	   
	   "input#13100_2": function(el){
			el.onclick = function(){
				if ($("13100_2").checked){
						Element.hide($("q_2734"));
				}
			}
		}
}

Behaviour.register(myrules);

// ]]>
-->
</script>
