	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/696" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="loading();return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="UZsrHu20j21X" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />
<input type="hidden" name="surveyId" value="UZsrHu20j21X"/>

<div class="mandatory"><span style="color: red;">* </span>- It is mandatory</div>
<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2647" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的孩子多大了？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13146].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13146].id" value="" id="answers[13146].id" />
<ul>
	<li>
			<input group="13146" type="radio" id="13146_0" name="answers[13146].value" value="10234"  class="selection question_radio_13146"  />		<label for="13146_0">3岁以下</label>
	</li>
	<li>
			<input group="13146" type="radio" id="13146_1" name="answers[13146].value" value="10235"  class="selection question_radio_13146"  />		<label for="13146_1">3-6岁</label>
	</li>
	<li>
			<input group="13146" type="radio" id="13146_2" name="answers[13146].value" value="10236"  class="selection question_radio_13146"  />		<label for="13146_2">7-10岁</label>
	</li>
	<li>
			<input group="13146" type="radio" id="13146_3" name="answers[13146].value" value="10237"  class="selection question_radio_13146"  />		<label for="13146_3">11-14岁</label>
	</li>
	<li>
			<input group="13146" type="radio" id="13146_4" name="answers[13146].value" value="10238"  class="selection question_radio_13146"  />		<label for="13146_4">大于14岁</label>
	</li>
	<li>
			<input group="13146" type="radio" id="13146_5" name="answers[13146].value" value="10239"  class="selection question_radio_13146"  />		<label for="13146_5">我没有孩子</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13146  qc_0 radio" type="radio" name="answers[13146].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2770" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你孩子的性别?
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13147].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13147].id" value="" id="answers[13147].id" />
<ul>
	<li>
			<input group="13147" type="radio" id="13147_0" name="answers[13147].value" value="10741"  class="selection question_radio_13147"  />		<label for="13147_0">男孩</label>
	</li>
	<li>
			<input group="13147" type="radio" id="13147_1" name="answers[13147].value" value="10742"  class="selection question_radio_13147"  />		<label for="13147_1">女孩</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13147  qc_0 radio" type="radio" name="answers[13147].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2648" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你觉得孩子在同龄人中是佼佼者有多重要?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[13148].value" ></span>
<input type="hidden" name="answers[13148].id" value="" id="answers[13148].id" />
<table>
<tr>

<td>

<div class="left-label">不重要</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[13148].value" value="1" id="13148_1" group="13148" class="question_radio_13148 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13148].value" value="2" id="13148_2" group="13148" class="question_radio_13148 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13148].value" value="3" id="13148_3" group="13148" class="question_radio_13148 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13148].value" value="4" id="13148_4" group="13148" class="question_radio_13148 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13148].value" value="5" id="13148_5" group="13148" class="question_radio_13148 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13148].value" value="6" id="13148_6" group="13148" class="question_radio_13148 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13148].value" value="7" id="13148_7" group="13148" class="question_radio_13148 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13148].value" value="8" id="13148_8" group="13148" class="question_radio_13148 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13148].value" value="9" id="13148_9" group="13148" class="question_radio_13148 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[13148].value" value="10" id="13148_10" group="13148" class="question_radio_13148 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">很重要</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[13148].value" value="" id="answers[13148].value" class="q_13148 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2566" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你觉得孩子可以说一口流利的英语有多重要？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[13149].value" ></span>
<input type="hidden" name="answers[13149].id" value="" id="answers[13149].id" />
<table>
<tr>

<td>

<div class="left-label">不重要</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[13149].value" value="1" id="13149_1" group="13149" class="question_radio_13149 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13149].value" value="2" id="13149_2" group="13149" class="question_radio_13149 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13149].value" value="3" id="13149_3" group="13149" class="question_radio_13149 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13149].value" value="4" id="13149_4" group="13149" class="question_radio_13149 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13149].value" value="5" id="13149_5" group="13149" class="question_radio_13149 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13149].value" value="6" id="13149_6" group="13149" class="question_radio_13149 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13149].value" value="7" id="13149_7" group="13149" class="question_radio_13149 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13149].value" value="8" id="13149_8" group="13149" class="question_radio_13149 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13149].value" value="9" id="13149_9" group="13149" class="question_radio_13149 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[13149].value" value="10" id="13149_10" group="13149" class="question_radio_13149 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">很重要</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[13149].value" value="" id="answers[13149].value" class="q_13149 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2565" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的孩子平均每天花在课后家庭作业上的时间是多少?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13150].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13150].id" value="" id="answers[13150].id" />
<ul>
	<li>
			<input group="13150" type="radio" id="13150_0" name="answers[13150].value" value="9758"  class="selection question_radio_13150"  />		<label for="13150_0">少于30分钟</label>
	</li>
	<li>
			<input group="13150" type="radio" id="13150_1" name="answers[13150].value" value="9759"  class="selection question_radio_13150"  />		<label for="13150_1">30-60分钟</label>
	</li>
	<li>
			<input group="13150" type="radio" id="13150_2" name="answers[13150].value" value="9760"  class="selection question_radio_13150"  />		<label for="13150_2">60-90分钟</label>
	</li>
	<li>
			<input group="13150" type="radio" id="13150_3" name="answers[13150].value" value="9761"  class="selection question_radio_13150"  />		<label for="13150_3">90-120分钟</label>
	</li>
	<li>
			<input group="13150" type="radio" id="13150_4" name="answers[13150].value" value="9762"  class="selection question_radio_13150"  />		<label for="13150_4">2-3小时</label>
	</li>
	<li>
			<input group="13150" type="radio" id="13150_5" name="answers[13150].value" value="9763"  class="selection question_radio_13150"  />		<label for="13150_5">多于3小时</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13150  qc_0 radio" type="radio" name="answers[13150].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2649" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你准备要送你的孩子去参与一些英语课程吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13151].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13151].id" value="" id="answers[13151].id" />
<ul>
	<li>
			<input group="13151" type="radio" id="13151_0" name="answers[13151].value" value="10240"  class="selection question_radio_13151"  />		<label for="13151_0">是，半年之内</label>
	</li>
	<li>
			<input group="13151" type="radio" id="13151_1" name="answers[13151].value" value="10241"  class="selection question_radio_13151"  />		<label for="13151_1">是，一年之内</label>
	</li>
	<li>
			<input group="13151" type="radio" id="13151_2" name="answers[13151].value" value="10242"  class="selection question_radio_13151"  />		<label for="13151_2">是，但要到明年之后</label>
	</li>
	<li>
			<input group="13151" type="radio" id="13151_3" name="answers[13151].value" value="10243"  class="selection question_radio_13151"  />		<label for="13151_3">我的孩子已经在上英语课了</label>
	</li>
	<li>
			<input group="13151" type="radio" id="13151_4" name="answers[13151].value" value="10244"  class="selection question_radio_13151"  />		<label for="13151_4">我没有这个计划</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13151  qc_0 radio" type="radio" name="answers[13151].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2771" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的孩子现在在哪里上英语课？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13152].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13152].id" value="" id="answers[13152].id" />
<ul>
	<li>
			<input group="13152" type="radio" id="13152_0" name="answers[13152].value" value="10743"  class="selection question_radio_13152"  />		<label for="13152_0">迪士尼英语</label>
	</li>
	<li>
			<input group="13152" type="radio" id="13152_1" name="answers[13152].value" value="10744"  class="selection question_radio_13152"  />		<label for="13152_1">小小地球</label>
	</li>
	<li>
			<input group="13152" type="radio" id="13152_2" name="answers[13152].value" value="10745"  class="selection question_radio_13152"  />		<label for="13152_2">乐宁</label>
	</li>
	<li>
			<input group="13152" type="radio" id="13152_3" name="answers[13152].value" value="10746"  class="selection question_radio_13152"  />		<label for="13152_3">英孚</label>
	</li>
	<li>
			<input group="13152" type="radio" id="13152_4" name="answers[13152].value" value="10747"  class="selection question_radio_13152"  />		<label for="13152_4">瑞思</label>
	</li>
	<li>
			<input group="13152" type="radio" id="13152_5" name="answers[13152].value" value="10748"  class="selection question_radio_13152"  />		<label for="13152_5">学乐</label>
	</li>
	<li>
			<input group="13152" type="radio" id="13152_6" name="answers[13152].value" value="10749"  class="selection question_radio_13152"  />		<label for="13152_6">新东方</label>
	</li>
	<li>
			<input group="13152" type="radio" id="13152_7" name="answers[13152].value" value="10750"  class="selection question_radio_13152"  />		<label for="13152_7">长颈鹿</label>
	</li>
	<li>
			<input group="13152" type="radio" id="13152_8" name="answers[13152].value" value="10751"  class="selection question_radio_13152"  />		<label for="13152_8">其他(请填写)</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13152  qc_0 radio" type="radio" name="answers[13152].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2772" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其 他
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13153].id" value="" id="answers[13153].id" />
<input type="text" name="answers[13153].value" value="" id="question_13153" group="13153" class="input-text" />

<span class="error-content" id="err_answers[13153].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2773" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你打算送孩子去参与英语课程最重要的原因是什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13154].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13154].id" value="" id="answers[13154].id" />
<ul>
	<li>
			<input group="13154" type="radio" id="13154_0" name="answers[13154].value" value="10752"  class="selection question_radio_13154"  />		<label for="13154_0">更好的了解世界</label>
	</li>
	<li>
			<input group="13154" type="radio" id="13154_1" name="answers[13154].value" value="10753"  class="selection question_radio_13154"  />		<label for="13154_1">沟通能力的提升</label>
	</li>
	<li>
			<input group="13154" type="radio" id="13154_2" name="answers[13154].value" value="10754"  class="selection question_radio_13154"  />		<label for="13154_2">领先于同龄人</label>
	</li>
	<li>
			<input group="13154" type="radio" id="13154_3" name="answers[13154].value" value="10755"  class="selection question_radio_13154"  />		<label for="13154_3">提前适应课堂</label>
	</li>
	<li>
			<input group="13154" type="radio" id="13154_4" name="answers[13154].value" value="10756"  class="selection question_radio_13154"  />		<label for="13154_4">尽早接触英语</label>
	</li>
	<li>
			<input group="13154" type="radio" id="13154_5" name="answers[13154].value" value="10757"  class="selection question_radio_13154"  />		<label for="13154_5">听说读写能力的提高</label>
	</li>
	<li>
			<input group="13154" type="radio" id="13154_6" name="answers[13154].value" value="10758"  class="selection question_radio_13154"  />		<label for="13154_6">英语成绩的提高</label>
	</li>
	<li>
			<input group="13154" type="radio" id="13154_7" name="answers[13154].value" value="10759"  class="selection question_radio_13154"  />		<label for="13154_7">其他(请填写)</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13154  qc_0 radio" type="radio" name="answers[13154].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2640" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13155].id" value="" id="answers[13155].id" />
<input type="text" name="answers[13155].value" value="" id="question_13155" group="13155" class="input-text" />

<span class="error-content" id="err_answers[13155].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2774" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你听说过以下哪个英语培训机构？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13156].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13156].id" value="" id="answers[13156].id" />




<span id="hint_13156">
</span>
<ul>
	<li>
			<input group="13156" class="question_radio_13156 selection" type="checkbox" id="13156_0" name="answers[13156].value" value="10760" 	onclick=" "/>		<label for="13156_0">迪士尼英语</label>
	</li>
	<li>
			<input group="13156" class="question_radio_13156 selection" type="checkbox" id="13156_1" name="answers[13156].value" value="10761" 	onclick=" "/>		<label for="13156_1">小小地球</label>
	</li>
	<li>
			<input group="13156" class="question_radio_13156 selection" type="checkbox" id="13156_2" name="answers[13156].value" value="10762" 	onclick=" "/>		<label for="13156_2">乐宁</label>
	</li>
	<li>
			<input group="13156" class="question_radio_13156 selection" type="checkbox" id="13156_3" name="answers[13156].value" value="10763" 	onclick=" "/>		<label for="13156_3">英孚</label>
	</li>
	<li>
			<input group="13156" class="question_radio_13156 selection" type="checkbox" id="13156_4" name="answers[13156].value" value="10764" 	onclick=" "/>		<label for="13156_4">长颈鹿</label>
	</li>
	<li>
			<input group="13156" class="question_radio_13156 selection" type="checkbox" id="13156_5" name="answers[13156].value" value="10765" 	onclick=" "/>		<label for="13156_5">瑞思</label>
	</li>
	<li>
			<input group="13156" class="question_radio_13156 selection" type="checkbox" id="13156_6" name="answers[13156].value" value="10766" 	onclick=" "/>		<label for="13156_6">学乐</label>
	</li>
	<li>
			<input group="13156" class="question_radio_13156 selection" type="checkbox" id="13156_7" name="answers[13156].value" value="10767" 	onclick=" "/>		<label for="13156_7">新东方</label>
	</li>
	<li>
			<input group="13156" class="question_radio_13156 selection" type="checkbox" id="13156_8" name="answers[13156].value" value="10768" 	onclick=" "/>		<label for="13156_8">其他(请填写)</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2748" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他机构
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13157].id" value="" id="answers[13157].id" />
<input type="text" name="answers[13157].value" value="" id="question_13157" group="13157" class="input-text" />

<span class="error-content" id="err_answers[13157].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2775" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你一般通过什么途径了解英语培训的相关消息？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13158].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13158].id" value="" id="answers[13158].id" />




<span id="hint_13158">
</span>
<ul>
	<li>
			<input group="13158" class="question_radio_13158 selection" type="checkbox" id="13158_0" name="answers[13158].value" value="10769" 	onclick=" "/>		<label for="13158_0">朋友推荐</label>
	</li>
	<li>
			<input group="13158" class="question_radio_13158 selection" type="checkbox" id="13158_1" name="answers[13158].value" value="10770" 	onclick=" "/>		<label for="13158_1">杂志广告</label>
	</li>
	<li>
			<input group="13158" class="question_radio_13158 selection" type="checkbox" id="13158_2" name="answers[13158].value" value="10771" 	onclick=" "/>		<label for="13158_2">户外广告</label>
	</li>
	<li>
			<input group="13158" class="question_radio_13158 selection" type="checkbox" id="13158_3" name="answers[13158].value" value="10772" 	onclick=" "/>		<label for="13158_3">电视广告</label>
	</li>
	<li>
			<input group="13158" class="question_radio_13158 selection" type="checkbox" id="13158_4" name="answers[13158].value" value="10773" 	onclick=" "/>		<label for="13158_4">网上广告</label>
	</li>
	<li>
			<input group="13158" class="question_radio_13158 selection" type="checkbox" id="13158_5" name="answers[13158].value" value="10774" 	onclick=" "/>		<label for="13158_5">广播</label>
	</li>
	<li>
			<input group="13158" class="question_radio_13158 selection" type="checkbox" id="13158_6" name="answers[13158].value" value="10775" 	onclick=" "/>		<label for="13158_6">其他(请填写)</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2776" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他途径
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13159].id" value="" id="answers[13159].id" />
<input type="text" name="answers[13159].value" value="" id="question_13159" group="13159" class="input-text" />

<span class="error-content" id="err_answers[13159].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2777" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你觉得下列学校哪个是英语培训中最好的？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13160].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13160].id" value="" id="answers[13160].id" />
<ul>
	<li>
			<input group="13160" type="radio" id="13160_0" name="answers[13160].value" value="10776"  class="selection question_radio_13160"  />		<label for="13160_0">迪士尼英语</label>
	</li>
	<li>
			<input group="13160" type="radio" id="13160_1" name="answers[13160].value" value="10777"  class="selection question_radio_13160"  />		<label for="13160_1">小小地球</label>
	</li>
	<li>
			<input group="13160" type="radio" id="13160_2" name="answers[13160].value" value="10778"  class="selection question_radio_13160"  />		<label for="13160_2">乐宁</label>
	</li>
	<li>
			<input group="13160" type="radio" id="13160_3" name="answers[13160].value" value="10779"  class="selection question_radio_13160"  />		<label for="13160_3">英孚</label>
	</li>
	<li>
			<input group="13160" type="radio" id="13160_4" name="answers[13160].value" value="10780"  class="selection question_radio_13160"  />		<label for="13160_4">长颈鹿</label>
	</li>
	<li>
			<input group="13160" type="radio" id="13160_5" name="answers[13160].value" value="10781"  class="selection question_radio_13160"  />		<label for="13160_5">瑞思</label>
	</li>
	<li>
			<input group="13160" type="radio" id="13160_6" name="answers[13160].value" value="10782"  class="selection question_radio_13160"  />		<label for="13160_6">学乐</label>
	</li>
	<li>
			<input group="13160" type="radio" id="13160_7" name="answers[13160].value" value="10783"  class="selection question_radio_13160"  />		<label for="13160_7">新东方</label>
	</li>
	<li>
			<input group="13160" type="radio" id="13160_8" name="answers[13160].value" value="10784"  class="selection question_radio_13160"  />		<label for="13160_8">其他(请填写)</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13160  qc_0 radio" type="radio" name="answers[13160].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2653" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他学校
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13161].id" value="" id="answers[13161].id" />
<input type="text" name="answers[13161].value" value="" id="question_13161" group="13161" class="input-text" />

<span class="error-content" id="err_answers[13161].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2654" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你听说过英孚教育的什么课程？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13162].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13162].id" value="" id="answers[13162].id" />




<span id="hint_13162">
</span>
<ul>
	<li>
			<input group="13162" class="question_radio_13162 selection" type="checkbox" id="13162_0" name="answers[13162].value" value="10264" 	onclick=" "/>		<label for="13162_0">成人及职场英语</label>
	</li>
	<li>
			<input group="13162" class="question_radio_13162 selection" type="checkbox" id="13162_1" name="answers[13162].value" value="10265" 	onclick=" "/>		<label for="13162_1">青少儿英语</label>
	</li>
	<li>
			<input group="13162" class="question_radio_13162 selection" type="checkbox" id="13162_2" name="answers[13162].value" value="10266" 	onclick=" "/>		<label for="13162_2">以上都听说过</label>
	</li>
	<li>
			<input group="13162" class="question_radio_13162 selection" type="checkbox" id="13162_3" name="answers[13162].value" value="10267" 	onclick=" "/>		<label for="13162_3">其他课程(请填写)</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2655" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他课程
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13163].id" value="" id="answers[13163].id" />
<input type="text" name="answers[13163].value" value="" id="question_13163" group="13163" class="input-text" />

<span class="error-content" id="err_answers[13163].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2665" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你曾和英孚教育联系过吗?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13164].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13164].id" value="" id="answers[13164].id" />
<ul>
	<li>
			<input group="13164" type="radio" id="13164_0" name="answers[13164].value" value="10311"  class="selection question_radio_13164"  />		<label for="13164_0">是</label>
	</li>
	<li>
			<input group="13164" type="radio" id="13164_1" name="answers[13164].value" value="10312"  class="selection question_radio_13164"  />		<label for="13164_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13164  qc_0 radio" type="radio" name="answers[13164].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2656" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你的孩子已经是英孚课程的学生了吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13165].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13165].id" value="" id="answers[13165].id" />
<ul>
	<li>
			<input group="13165" type="radio" id="13165_0" name="answers[13165].value" value="10268"  class="selection question_radio_13165"  />		<label for="13165_0">是</label>
	</li>
	<li>
			<input group="13165" type="radio" id="13165_1" name="answers[13165].value" value="10269"  class="selection question_radio_13165"  />		<label for="13165_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13165  qc_0 radio" type="radio" name="answers[13165].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2657" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你多久和朋友聚会一次？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13166].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13166].id" value="" id="answers[13166].id" />
<ul>
	<li>
			<input group="13166" type="radio" id="13166_0" name="answers[13166].value" value="10270"  class="selection question_radio_13166"  />		<label for="13166_0">从不</label>
	</li>
	<li>
			<input group="13166" type="radio" id="13166_1" name="answers[13166].value" value="10271"  class="selection question_radio_13166"  />		<label for="13166_1">只有特殊场合</label>
	</li>
	<li>
			<input group="13166" type="radio" id="13166_2" name="answers[13166].value" value="10272"  class="selection question_radio_13166"  />		<label for="13166_2">一个月两三次</label>
	</li>
	<li>
			<input group="13166" type="radio" id="13166_3" name="answers[13166].value" value="10273"  class="selection question_radio_13166"  />		<label for="13166_3">每周一次</label>
	</li>
	<li>
			<input group="13166" type="radio" id="13166_4" name="answers[13166].value" value="10274"  class="selection question_radio_13166"  />		<label for="13166_4">一周几次</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13166  qc_0 radio" type="radio" name="answers[13166].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2658" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你的好友中，有多少已经为人父母？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13167].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13167].id" value="" id="answers[13167].id" />
<ul>
	<li>
			<input group="13167" type="radio" id="13167_0" name="answers[13167].value" value="10275"  class="selection question_radio_13167"  />		<label for="13167_0">多于30位</label>
	</li>
	<li>
			<input group="13167" type="radio" id="13167_1" name="answers[13167].value" value="10276"  class="selection question_radio_13167"  />		<label for="13167_1">20~30位</label>
	</li>
	<li>
			<input group="13167" type="radio" id="13167_2" name="answers[13167].value" value="10277"  class="selection question_radio_13167"  />		<label for="13167_2">10~20位</label>
	</li>
	<li>
			<input group="13167" type="radio" id="13167_3" name="answers[13167].value" value="10278"  class="selection question_radio_13167"  />		<label for="13167_3">5~10位</label>
	</li>
	<li>
			<input group="13167" type="radio" id="13167_4" name="answers[13167].value" value="10279"  class="selection question_radio_13167"  />		<label for="13167_4">5位以下</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13167  qc_0 radio" type="radio" name="answers[13167].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2659" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						您家庭每个月收入水平？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13168].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13168].id" value="" id="answers[13168].id" />
<ul>
	<li>
			<input group="13168" type="radio" id="13168_0" name="answers[13168].value" value="10280"  class="selection question_radio_13168"  />		<label for="13168_0">￥5,000以下</label>
	</li>
	<li>
			<input group="13168" type="radio" id="13168_1" name="answers[13168].value" value="10281"  class="selection question_radio_13168"  />		<label for="13168_1">￥5,000～10,000</label>
	</li>
	<li>
			<input group="13168" type="radio" id="13168_2" name="answers[13168].value" value="10282"  class="selection question_radio_13168"  />		<label for="13168_2">￥10,000～15,000</label>
	</li>
	<li>
			<input group="13168" type="radio" id="13168_3" name="answers[13168].value" value="10283"  class="selection question_radio_13168"  />		<label for="13168_3">￥15,000～20,000</label>
	</li>
	<li>
			<input group="13168" type="radio" id="13168_4" name="answers[13168].value" value="10284"  class="selection question_radio_13168"  />		<label for="13168_4">￥20,000～25,000</label>
	</li>
	<li>
			<input group="13168" type="radio" id="13168_5" name="answers[13168].value" value="10285"  class="selection question_radio_13168"  />		<label for="13168_5">￥25,000以上</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13168  qc_0 radio" type="radio" name="answers[13168].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2778" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						如果你的子女有机会参加英孚的课程，以下哪个校区比较方便？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13169].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13169].id" value="" id="answers[13169].id" />
<ul>
	<li>
			<input group="13169" type="radio" id="13169_0" name="answers[13169].value" value="10785"  class="selection question_radio_13169"  />		<label for="13169_0">徐汇太原路 上海徐汇区太原路167号</label>
	</li>
	<li>
			<input group="13169" type="radio" id="13169_1" name="answers[13169].value" value="10786"  class="selection question_radio_13169"  />		<label for="13169_1">华润时代广场 上海浦东张扬路500号华润时代广场613室</label>
	</li>
	<li>
			<input group="13169" type="radio" id="13169_2" name="answers[13169].value" value="10787"  class="selection question_radio_13169"  />		<label for="13169_2">莘庄仲盛 都市路5001号仲盛世界商城5楼</label>
	</li>
	<li>
			<input group="13169" type="radio" id="13169_3" name="answers[13169].value" value="10788"  class="selection question_radio_13169"  />		<label for="13169_3">闵行顾戴路 上海市闵行区顾戴路(近龙茗路)1178弄58-60号</label>
	</li>
	<li>
			<input group="13169" type="radio" id="13169_4" name="answers[13169].value" value="10789"  class="selection question_radio_13169"  />		<label for="13169_4">普陀中远两湾城 上海普陀区中潭路91弄19号（小区内）临近中山北路</label>
	</li>
	<li>
			<input group="13169" type="radio" id="13169_5" name="answers[13169].value" value="10790"  class="selection question_radio_13169"  />		<label for="13169_5">徐汇宜山路 上海徐汇区宜山路675号</label>
	</li>
	<li>
			<input group="13169" type="radio" id="13169_6" name="answers[13169].value" value="10791"  class="selection question_radio_13169"  />		<label for="13169_6">杨浦五角场 上海市杨浦区四平路2162号3楼</label>
	</li>
	<li>
			<input group="13169" type="radio" id="13169_7" name="answers[13169].value" value="10792"  class="selection question_radio_13169"  />		<label for="13169_7">长宁西郊百联 上海长宁区仙霞西路88号百联西郊购物中心一楼1315室</label>
	</li>
	<li>
			<input group="13169" type="radio" id="13169_8" name="answers[13169].value" value="10793"  class="selection question_radio_13169"  />		<label for="13169_8">黄浦西藏南路 上海市黄浦区瞿溪路405号（西藏南路口）</label>
	</li>
	<li>
			<input group="13169" type="radio" id="13169_9" name="answers[13169].value" value="10794"  class="selection question_radio_13169"  />		<label for="13169_9">浦东金桥枣庄路 上海浦东博山东路560弄12号（近枣庄路）</label>
	</li>
	<li>
			<input group="13169" type="radio" id="13169_10" name="answers[13169].value" value="10795"  class="selection question_radio_13169"  />		<label for="13169_10">长宁中山公园 上海长宁路1158号贝多芬广场4楼</label>
	</li>
	<li>
			<input group="13169" type="radio" id="13169_11" name="answers[13169].value" value="10796"  class="selection question_radio_13169"  />		<label for="13169_11">越秀环市东 水荫路2号华信大厦东座3楼</label>
	</li>
	<li>
			<input group="13169" type="radio" id="13169_12" name="answers[13169].value" value="10797"  class="selection question_radio_13169"  />		<label for="13169_12">其他(请填写)</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13169  qc_0 radio" type="radio" name="answers[13169].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2751" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他校区
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13170].id" value="" id="answers[13170].id" />
<input type="text" name="answers[13170].value" value="" id="question_13170" group="13170" class="input-text" />

<span class="error-content" id="err_answers[13170].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("13171");
// ]]>
-->
</script>
		  <div id="q_2088" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						姓名:
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13171].id" value="" id="answers[13171].id" />
<input type="text" name="answers[13171].value" value="" id="question_13171" group="13171" class="input-text" />

<span class="error-content" id="err_answers[13171].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("13172");
// ]]>
-->
</script>
		  <div id="q_2663" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						邮箱(我们会通过邮件和短信通知入选活动者):
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13172].id" value="" id="answers[13172].id" />
<input type="text" name="answers[13172].value" value="" id="question_13172" group="13172" class="input-text" />

<span class="error-content" id="err_answers[13172].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2664" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						手机:
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13173].id" value="" id="answers[13173].id" />
<input type="text" name="answers[13173].value" value="" id="question_13173" group="13173" class="input-text" />

<span class="error-content" id="err_answers[13173].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="Submit" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = 'Mandatory questions must be filled out';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = 'Can not submit empty questionnaire form';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[


	 Element.hide("q_2772");
	 Element.hide("q_2640");
	 Element.hide("q_2748");
	 Element.hide("q_2776");
	 Element.hide("q_2653");
	 Element.hide("q_2655");
	 Element.hide("q_2751");


var myrules = {
	   
	   "input#13156_8": function(el){
			el.onclick = function(){
				if ($("13156_8").checked){
						Element.show($("q_2748"));
				}
			}
		}
	,
	   
	   "input#13151_1": function(el){
			el.onclick = function(){
				if ($("13151_1").checked){
						Element.hide($("q_2771"));
				}
			}
		}
	,
	   
	   "input#13154_5": function(el){
			el.onclick = function(){
				if ($("13154_5").checked){
						Element.hide($("q_2640"));
				}
			}
		}
	,
	   
	   "input#13169_7": function(el){
			el.onclick = function(){
				if ($("13169_7").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13169_2": function(el){
			el.onclick = function(){
				if ($("13169_2").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13160_5": function(el){
			el.onclick = function(){
				if ($("13160_5").checked){
						Element.hide($("q_2653"));
				}
			}
		}
	,
	   
	   "input#13169_8": function(el){
			el.onclick = function(){
				if ($("13169_8").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13154_4": function(el){
			el.onclick = function(){
				if ($("13154_4").checked){
						Element.hide($("q_2640"));
				}
			}
		}
	,
	   
	   "input#13151_0": function(el){
			el.onclick = function(){
				if ($("13151_0").checked){
						Element.hide($("q_2771"));
				}
			}
		}
	,
	   
	   "input#13160_0": function(el){
			el.onclick = function(){
				if ($("13160_0").checked){
						Element.hide($("q_2653"));
				}
			}
		}
	,
	   
	   "input#13169_11": function(el){
			el.onclick = function(){
				if ($("13169_11").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13151_4": function(el){
			el.onclick = function(){
				if ($("13151_4").checked){
						Element.hide($("q_2771"));
				}
			}
		}
	,
	   
	   "input#13152_1": function(el){
			el.onclick = function(){
				if ($("13152_1").checked){
						Element.hide($("q_2772"));
				}
			}
		}
	,
	   
	   "input#13169_0": function(el){
			el.onclick = function(){
				if ($("13169_0").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13160_3": function(el){
			el.onclick = function(){
				if ($("13160_3").checked){
						Element.hide($("q_2653"));
				}
			}
		}
	,
	   
	   "input#13154_7": function(el){
			el.onclick = function(){
				if ($("13154_7").checked){
						Element.show($("q_2640"));
				}
			}
		}
	,
	   
	   "input#13152_5": function(el){
			el.onclick = function(){
				if ($("13152_5").checked){
						Element.hide($("q_2772"));
				}
			}
		}
	,
	   
	   "input#13169_12": function(el){
			el.onclick = function(){
				if ($("13169_12").checked){
						Element.show($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13152_8": function(el){
			el.onclick = function(){
				if ($("13152_8").checked){
						Element.show($("q_2772"));
				}
			}
		}
	,
	   
	   "input#13169_1": function(el){
			el.onclick = function(){
				if ($("13169_1").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13152_3": function(el){
			el.onclick = function(){
				if ($("13152_3").checked){
						Element.hide($("q_2772"));
				}
			}
		}
	,
	   
	   "input#13160_2": function(el){
			el.onclick = function(){
				if ($("13160_2").checked){
						Element.hide($("q_2653"));
				}
			}
		}
	,
	   
	   "input#13151_2": function(el){
			el.onclick = function(){
				if ($("13151_2").checked){
						Element.hide($("q_2771"));
				}
			}
		}
	,
	   
	   "input#13154_0": function(el){
			el.onclick = function(){
				if ($("13154_0").checked){
						Element.hide($("q_2640"));
				}
			}
		}
	,
	   
	   "input#13154_2": function(el){
			el.onclick = function(){
				if ($("13154_2").checked){
						Element.hide($("q_2640"));
				}
			}
		}
	,
	   
	   "input#13169_9": function(el){
			el.onclick = function(){
				if ($("13169_9").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13152_7": function(el){
			el.onclick = function(){
				if ($("13152_7").checked){
						Element.hide($("q_2772"));
				}
			}
		}
	,
	   
	   "input#13160_1": function(el){
			el.onclick = function(){
				if ($("13160_1").checked){
						Element.hide($("q_2653"));
				}
			}
		}
	,
	   
	   "input#13154_1": function(el){
			el.onclick = function(){
				if ($("13154_1").checked){
						Element.hide($("q_2640"));
				}
			}
		}
	,
	   
	   "input#13169_6": function(el){
			el.onclick = function(){
				if ($("13169_6").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13162_3": function(el){
			el.onclick = function(){
				if ($("13162_3").checked){
						Element.show($("q_2655"));
				}
			}
		}
	,
	   
	   "input#13160_4": function(el){
			el.onclick = function(){
				if ($("13160_4").checked){
						Element.hide($("q_2653"));
				}
			}
		}
	,
	   
	   "input#13152_6": function(el){
			el.onclick = function(){
				if ($("13152_6").checked){
						Element.hide($("q_2772"));
				}
			}
		}
	,
	   
	   "input#13152_0": function(el){
			el.onclick = function(){
				if ($("13152_0").checked){
						Element.hide($("q_2772"));
				}
			}
		}
	,
	   
	   "input#13169_3": function(el){
			el.onclick = function(){
				if ($("13169_3").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13169_10": function(el){
			el.onclick = function(){
				if ($("13169_10").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13160_7": function(el){
			el.onclick = function(){
				if ($("13160_7").checked){
						Element.hide($("q_2653"));
				}
			}
		}
	,
	   
	   "input#13152_2": function(el){
			el.onclick = function(){
				if ($("13152_2").checked){
						Element.hide($("q_2772"));
				}
			}
		}
	,
	   
	   "input#13154_3": function(el){
			el.onclick = function(){
				if ($("13154_3").checked){
						Element.hide($("q_2640"));
				}
			}
		}
	,
	   
	   "input#13158_6": function(el){
			el.onclick = function(){
				if ($("13158_6").checked){
						Element.show($("q_2776"));
				}
			}
		}
	,
	   
	   "input#13169_4": function(el){
			el.onclick = function(){
				if ($("13169_4").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13160_8": function(el){
			el.onclick = function(){
				if ($("13160_8").checked){
						Element.show($("q_2653"));
				}
			}
		}
	,
	   
	   "input#13151_3": function(el){
			el.onclick = function(){
				if ($("13151_3").checked){
						Element.show($("q_2771"));
				}
			}
		}
	,
	   
	   "input#13160_6": function(el){
			el.onclick = function(){
				if ($("13160_6").checked){
						Element.hide($("q_2653"));
				}
			}
		}
	,
	   
	   "input#13169_5": function(el){
			el.onclick = function(){
				if ($("13169_5").checked){
						Element.hide($("q_2751"));
				}
			}
		}
	,
	   
	   "input#13152_4": function(el){
			el.onclick = function(){
				if ($("13152_4").checked){
						Element.hide($("q_2772"));
				}
			}
		}
	,
	   
	   "input#13154_6": function(el){
			el.onclick = function(){
				if ($("13154_6").checked){
						Element.hide($("q_2640"));
				}
			}
		}
}

Behaviour.register(myrules);

Framework.registerAjaxSensors();
// ]]>
-->
</script>
