	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/711" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="loading();return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="JMXGEeulOpiA" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2895" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你听说过卡夫王子脆脆多吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13402].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13402].id" value="" id="answers[13402].id" />
<ul>
	<li>
			<input group="13402" type="radio" id="13402_0" name="answers[13402].value" value="11150"  class="selection question_radio_13402"  />		<label for="13402_0">是</label>
	</li>
	<li>
			<input group="13402" type="radio" id="13402_1" name="answers[13402].value" value="11151"  class="selection question_radio_13402"  />		<label for="13402_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13402  qc_0 radio" type="radio" name="answers[13402].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2896" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你在最近三个月中购买脆脆多的次数是多少？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13403].id" value="" id="answers[13403].id" />
<input type="text" name="answers[13403].value" value="" id="question_13403" group="13403" class="input-text" />

<span class="error-content" id="err_answers[13403].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2897" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你有多大程度会向别人推荐脆脆多?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[13404].value" ></span>
<input type="hidden" name="answers[13404].id" value="" id="answers[13404].id" />
<table>
<tr>

<td>

<div class="left-label">不会</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[13404].value" value="0" id="13404_0" group="13404" class="question_radio_13404 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13404].value" value="1" id="13404_1" group="13404" class="question_radio_13404 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13404].value" value="2" id="13404_2" group="13404" class="question_radio_13404 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13404].value" value="3" id="13404_3" group="13404" class="question_radio_13404 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13404].value" value="4" id="13404_4" group="13404" class="question_radio_13404 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13404].value" value="5" id="13404_5" group="13404" class="question_radio_13404 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13404].value" value="6" id="13404_6" group="13404" class="question_radio_13404 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13404].value" value="7" id="13404_7" group="13404" class="question_radio_13404 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13404].value" value="8" id="13404_8" group="13404" class="question_radio_13404 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13404].value" value="9" id="13404_9" group="13404" class="question_radio_13404 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[13404].value" value="10" id="13404_10" group="13404" class="question_radio_13404 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">会</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[13404].value" value="" id="answers[13404].value" class="q_13404 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2898" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你有多大程度会在未来的三个月里购买脆脆多？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[13405].value" ></span>
<input type="hidden" name="answers[13405].id" value="" id="answers[13405].id" />
<table>
<tr>

<td>

<div class="left-label">不会</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[13405].value" value="0" id="13405_0" group="13405" class="question_radio_13405 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13405].value" value="1" id="13405_1" group="13405" class="question_radio_13405 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13405].value" value="2" id="13405_2" group="13405" class="question_radio_13405 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13405].value" value="3" id="13405_3" group="13405" class="question_radio_13405 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13405].value" value="4" id="13405_4" group="13405" class="question_radio_13405 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[13405].value" value="5" id="13405_5" group="13405" class="question_radio_13405 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">会</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[13405].value" value="" id="answers[13405].value" class="q_13405 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2899" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你听说过好丽友好多鱼吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13406].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13406].id" value="" id="answers[13406].id" />
<ul>
	<li>
			<input group="13406" type="radio" id="13406_0" name="answers[13406].value" value="11152"  class="selection question_radio_13406"  />		<label for="13406_0">是</label>
	</li>
	<li>
			<input group="13406" type="radio" id="13406_1" name="answers[13406].value" value="11153"  class="selection question_radio_13406"  />		<label for="13406_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13406  qc_0 radio" type="radio" name="answers[13406].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2900" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你在最近三个月中购买好丽友好多鱼的次数是多少？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13407].id" value="" id="answers[13407].id" />
<input type="text" name="answers[13407].value" value="" id="question_13407" group="13407" class="input-text" />

<span class="error-content" id="err_answers[13407].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2901" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你有多大程度会向别人推荐好丽友好多鱼?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[13408].value" ></span>
<input type="hidden" name="answers[13408].id" value="" id="answers[13408].id" />
<table>
<tr>

<td>

<div class="left-label">不会</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[13408].value" value="0" id="13408_0" group="13408" class="question_radio_13408 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13408].value" value="1" id="13408_1" group="13408" class="question_radio_13408 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13408].value" value="2" id="13408_2" group="13408" class="question_radio_13408 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13408].value" value="3" id="13408_3" group="13408" class="question_radio_13408 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13408].value" value="4" id="13408_4" group="13408" class="question_radio_13408 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13408].value" value="5" id="13408_5" group="13408" class="question_radio_13408 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13408].value" value="6" id="13408_6" group="13408" class="question_radio_13408 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13408].value" value="7" id="13408_7" group="13408" class="question_radio_13408 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13408].value" value="8" id="13408_8" group="13408" class="question_radio_13408 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13408].value" value="9" id="13408_9" group="13408" class="question_radio_13408 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[13408].value" value="10" id="13408_10" group="13408" class="question_radio_13408 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">会</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[13408].value" value="" id="answers[13408].value" class="q_13408 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2902" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你有多大程度会在未来的三个月里购买好丽友好多鱼？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[13409].value" ></span>
<input type="hidden" name="answers[13409].id" value="" id="answers[13409].id" />
<table>
<tr>

<td>

<div class="left-label">不会</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[13409].value" value="0" id="13409_0" group="13409" class="question_radio_13409 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13409].value" value="1" id="13409_1" group="13409" class="question_radio_13409 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13409].value" value="2" id="13409_2" group="13409" class="question_radio_13409 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13409].value" value="3" id="13409_3" group="13409" class="question_radio_13409 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13409].value" value="4" id="13409_4" group="13409" class="question_radio_13409 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[13409].value" value="5" id="13409_5" group="13409" class="question_radio_13409 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">会</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[13409].value" value="" id="answers[13409].value" class="q_13409 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2907" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你听说过好丽友蘑菇力吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13410].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13410].id" value="" id="answers[13410].id" />
<ul>
	<li>
			<input group="13410" type="radio" id="13410_0" name="answers[13410].value" value="11156"  class="selection question_radio_13410"  />		<label for="13410_0">是</label>
	</li>
	<li>
			<input group="13410" type="radio" id="13410_1" name="answers[13410].value" value="11157"  class="selection question_radio_13410"  />		<label for="13410_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13410  qc_0 radio" type="radio" name="answers[13410].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2904" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你在最近三个月中购买好丽友蘑菇力的次数是多少？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13411].id" value="" id="answers[13411].id" />
<input type="text" name="answers[13411].value" value="" id="question_13411" group="13411" class="input-text" />

<span class="error-content" id="err_answers[13411].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2905" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你有多大程度会向别人推荐好丽友蘑菇力?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[13412].value" ></span>
<input type="hidden" name="answers[13412].id" value="" id="answers[13412].id" />
<table>
<tr>

<td>

<div class="left-label">不会</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[13412].value" value="0" id="13412_0" group="13412" class="question_radio_13412 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13412].value" value="1" id="13412_1" group="13412" class="question_radio_13412 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13412].value" value="2" id="13412_2" group="13412" class="question_radio_13412 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13412].value" value="3" id="13412_3" group="13412" class="question_radio_13412 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13412].value" value="4" id="13412_4" group="13412" class="question_radio_13412 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13412].value" value="5" id="13412_5" group="13412" class="question_radio_13412 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13412].value" value="6" id="13412_6" group="13412" class="question_radio_13412 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13412].value" value="7" id="13412_7" group="13412" class="question_radio_13412 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13412].value" value="8" id="13412_8" group="13412" class="question_radio_13412 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13412].value" value="9" id="13412_9" group="13412" class="question_radio_13412 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[13412].value" value="10" id="13412_10" group="13412" class="question_radio_13412 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">会</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[13412].value" value="" id="answers[13412].value" class="q_13412 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2906" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你有多大程度会在未来的三个月里购买好丽友蘑菇力？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[13413].value" ></span>
<input type="hidden" name="answers[13413].id" value="" id="answers[13413].id" />
<table>
<tr>

<td>

<div class="left-label">不会</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[13413].value" value="0" id="13413_0" group="13413" class="question_radio_13413 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13413].value" value="1" id="13413_1" group="13413" class="question_radio_13413 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13413].value" value="2" id="13413_2" group="13413" class="question_radio_13413 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13413].value" value="3" id="13413_3" group="13413" class="question_radio_13413 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13413].value" value="4" id="13413_4" group="13413" class="question_radio_13413 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[13413].value" value="5" id="13413_5" group="13413" class="question_radio_13413 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">会</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[13413].value" value="" id="answers[13413].value" class="q_13413 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2884" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你觉得你了解孩子在零食方面的选择及偏爱吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13414].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13414].id" value="" id="answers[13414].id" />
<ul>
	<li>
			<input group="13414" type="radio" id="13414_0" name="answers[13414].value" value="11072"  class="selection question_radio_13414"  />		<label for="13414_0">是</label>
	</li>
	<li>
			<input group="13414" type="radio" id="13414_1" name="answers[13414].value" value="11073"  class="selection question_radio_13414"  />		<label for="13414_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13414  qc_0 radio" type="radio" name="answers[13414].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2885" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请详细解释一下
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13415].id" value="" id="answers[13415].id" />
<input type="text" name="answers[13415].value" value="" id="question_13415" group="13415" class="input-text" />

<span class="error-content" id="err_answers[13415].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2886" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在考虑购买哪种零食时，谁是你家庭中的最终决定者？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13416].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13416].id" value="" id="answers[13416].id" />
<ul>
	<li>
			<input group="13416" type="radio" id="13416_0" name="answers[13416].value" value="11074"  class="selection question_radio_13416"  />		<label for="13416_0">我</label>
	</li>
	<li>
			<input group="13416" type="radio" id="13416_1" name="answers[13416].value" value="11075"  class="selection question_radio_13416"  />		<label for="13416_1">我的丈夫</label>
	</li>
	<li>
			<input group="13416" type="radio" id="13416_2" name="answers[13416].value" value="11076"  class="selection question_radio_13416"  />		<label for="13416_2">我的孩子</label>
	</li>
	<li>
			<input group="13416" type="radio" id="13416_3" name="answers[13416].value" value="11077"  class="selection question_radio_13416"  />		<label for="13416_3">我们全家一起决定</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13416  qc_0 radio" type="radio" name="answers[13416].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2887" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在为孩子购买零食时，你最注重的方面是什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13417].id" value="" id="answers[13417].id" />
<input type="text" name="answers[13417].value" value="" id="question_13417" group="13417" class="input-text" />

<span class="error-content" id="err_answers[13417].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2888" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的孩子自己在选零食时最注重的方面是什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13418].id" value="" id="answers[13418].id" />
<input type="text" name="answers[13418].value" value="" id="question_13418" group="13418" class="input-text" />

<span class="error-content" id="err_answers[13418].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2892" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在你即将收到的零食礼包里，你希望收到哪种口味的好丽友蘑菇力？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13419].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13419].id" value="" id="answers[13419].id" />

	<select group="13419" class="selection" id="question_13419" name="answers[13419].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="11143" style=""  >好丽友蘑菇力红豆巧克力味</option>
<option value="11144" style=""  >好丽友蘑菇力巧克力味</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2893" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在你即将收到的零食礼包里，你希望收到哪种口味的卡夫王子脆脆多？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13420].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13420].id" value="" id="answers[13420].id" />

	<select group="13420" class="selection" id="question_13420" name="answers[13420].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="11145" style=""  >王子脆脆多巧克力味</option>
<option value="11146" style=""  >王子脆脆多甜橙味</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2894" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在你即将收到的零食礼包里，你希望收到哪种口味的好丽友好多鱼？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13421].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13421].id" value="" id="answers[13421].id" />

	<select group="13421" class="selection" id="question_13421" name="answers[13421].value" title="title"  size = "1" >
	<option selected="selected" value="0">Please choose</option>
<option value="11147" style=""  >好丽友好多鱼浓香茄汁味</option>
<option value="11148" style=""  >好丽友好多鱼脆香烧烤味</option>
<option value="11149" style=""  >好丽友好多鱼鲜香海苔味</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="Submit" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = 'Mandatory questions must be filled out';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = 'Can not submit empty questionnaire form';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

Framework.registerAjaxSensors();
// ]]>
-->
</script>
