	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/716" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />
<input type="hidden" name="surveyId" value="5BJGWVUw6Iv5"/>

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2946" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你对自己的体重满意吗？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13503].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13503].id" value="" id="answers[13503].id" />
<ul>
	<li>
			<input group="13503" type="radio" id="13503_0" name="answers[13503].value" value="11207"  class="selection question_radio_13503"  />		<label for="13503_0">我觉得自己过瘦</label>
	</li>
	<li>
			<input group="13503" type="radio" id="13503_1" name="answers[13503].value" value="11208"  class="selection question_radio_13503"  />		<label for="13503_1">我非常满意现在的身材</label>
	</li>
	<li>
			<input group="13503" type="radio" id="13503_2" name="answers[13503].value" value="11209"  class="selection question_radio_13503"  />		<label for="13503_2">感觉还行，最好再瘦点</label>
	</li>
	<li>
			<input group="13503" type="radio" id="13503_3" name="answers[13503].value" value="11210"  class="selection question_radio_13503"  />		<label for="13503_3">我有点胖，在考虑瘦身</label>
	</li>
	<li>
			<input group="13503" type="radio" id="13503_4" name="answers[13503].value" value="11211"  class="selection question_radio_13503"  />		<label for="13503_4">我很胖，一定要减肥</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13503  qc_0 radio" type="radio" name="answers[13503].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2947" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你之前曾减过肥吗？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13504].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13504].id" value="" id="answers[13504].id" />
<ul>
	<li>
			<input group="13504" type="radio" id="13504_0" name="answers[13504].value" value="11212"  class="selection question_radio_13504"  />		<label for="13504_0">是的，很多次</label>
	</li>
	<li>
			<input group="13504" type="radio" id="13504_1" name="answers[13504].value" value="11213"  class="selection question_radio_13504"  />		<label for="13504_1">是的，一两次</label>
	</li>
	<li>
			<input group="13504" type="radio" id="13504_2" name="answers[13504].value" value="11214"  class="selection question_radio_13504"  />		<label for="13504_2">没有</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13504  qc_0 radio" type="radio" name="answers[13504].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2948" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						为了减轻体重，你做过哪些努力呢？
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13505].id" value="" id="answers[13505].id" />
<textarea name="answers[13505].value" id="question_13505" cols="40" group="13505" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[13505].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2949" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你理想的减肥方式是什么样，请描述一下吧
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13506].id" value="" id="answers[13506].id" />
<textarea name="answers[13506].value" id="question_13506" cols="40" group="13506" rows="5" class="input-text" ></textarea>
<span class="error-content" id="err_answers[13506].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2950" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你减肥的主要动力是什么呢？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13507].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13507].id" value="" id="answers[13507].id" />
<ul>
	<li>
			<input group="13507" type="radio" id="13507_0" name="answers[13507].value" value="11215"  class="selection question_radio_13507"  />		<label for="13507_0">让自己更强健有力</label>
	</li>
	<li>
			<input group="13507" type="radio" id="13507_1" name="answers[13507].value" value="11216"  class="selection question_radio_13507"  />		<label for="13507_1">降低心血管疾病等的风险</label>
	</li>
	<li>
			<input group="13507" type="radio" id="13507_2" name="answers[13507].value" value="11217"  class="selection question_radio_13507"  />		<label for="13507_2">产后恢复体重</label>
	</li>
	<li>
			<input group="13507" type="radio" id="13507_3" name="answers[13507].value" value="11218"  class="selection question_radio_13507"  />		<label for="13507_3">有更多合身的衣服可穿</label>
	</li>
	<li>
			<input group="13507" type="radio" id="13507_4" name="answers[13507].value" value="11219"  class="selection question_radio_13507"  />		<label for="13507_4">其他（请填写）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13507  qc_0 radio" type="radio" name="answers[13507].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2951" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他动力
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13508].id" value="" id="answers[13508].id" />
<input type="text" name="answers[13508].value" value="" id="question_13508" group="13508" class="input-text" />

<span class="error-content" id="err_answers[13508].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2952" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你的身高？（单位：cm）如填写 165，178
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13509].id" value="" id="answers[13509].id" />
<input type="text" name="answers[13509].value" value="" id="question_13509" group="13509" class="input-text" />

<span class="error-content" id="err_answers[13509].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2953" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你的体重？（单位：kg）如填写 55，70
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13510].id" value="" id="answers[13510].id" />
<input type="text" name="answers[13510].value" value="" id="question_13510" group="13510" class="input-text" />

<span class="error-content" id="err_answers[13510].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2954" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你的理想体重？（单位：kg）如填写 50，65
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13511].id" value="" id="answers[13511].id" />
<input type="text" name="answers[13511].value" value="" id="question_13511" group="13511" class="input-text" />

<span class="error-content" id="err_answers[13511].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2955" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你觉得完全靠自己而瘦身成功的难度如何？
					</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[13512].value" ></span>
<input type="hidden" name="answers[13512].id" value="" id="answers[13512].id" />
<table>
<tr>

<td>

<div class="left-label">非常简单</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[13512].value" value="1" id="13512_1" group="13512" class="question_radio_13512 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13512].value" value="2" id="13512_2" group="13512" class="question_radio_13512 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13512].value" value="3" id="13512_3" group="13512" class="question_radio_13512 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13512].value" value="4" id="13512_4" group="13512" class="question_radio_13512 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13512].value" value="5" id="13512_5" group="13512" class="question_radio_13512 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13512].value" value="6" id="13512_6" group="13512" class="question_radio_13512 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13512].value" value="7" id="13512_7" group="13512" class="question_radio_13512 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13512].value" value="8" id="13512_8" group="13512" class="question_radio_13512 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13512].value" value="9" id="13512_9" group="13512" class="question_radio_13512 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[13512].value" value="10" id="13512_10" group="13512" class="question_radio_13512 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</table> <div class="right-label">非常困难</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[13512].value" value="" id="answers[13512].value" class="q_13512 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2956" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你的性别？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13513].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13513].id" value="" id="answers[13513].id" />
<ul>
	<li>
			<input group="13513" type="radio" id="13513_0" name="answers[13513].value" value="11220"  class="selection question_radio_13513"  />		<label for="13513_0">男</label>
	</li>
	<li>
			<input group="13513" type="radio" id="13513_1" name="answers[13513].value" value="11221"  class="selection question_radio_13513"  />		<label for="13513_1">女</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13513  qc_0 radio" type="radio" name="answers[13513].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2957" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你的出生年份?
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13514].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13514].id" value="" id="answers[13514].id" />

	<select group="13514" class="selection" id="question_13514" name="answers[13514].value" title="title"  size = "1" >
	<option selected="selected" value="0">请选择</option>
<option value="11222" style=""  >1960以前</option>
<option value="11223" style=""  >1961</option>
<option value="11224" style=""  >1962</option>
<option value="11225" style=""  >1963</option>
<option value="11226" style=""  >1964</option>
<option value="11227" style=""  >1965</option>
<option value="11228" style=""  >1966</option>
<option value="11229" style=""  >1967</option>
<option value="11230" style=""  >1968</option>
<option value="11231" style=""  >1969</option>
<option value="11232" style=""  >1970</option>
<option value="11233" style=""  >1971</option>
<option value="11234" style=""  >1972</option>
<option value="11235" style=""  >1973</option>
<option value="11236" style=""  >1974</option>
<option value="11237" style=""  >1975</option>
<option value="11238" style=""  >1976</option>
<option value="11239" style=""  >1977</option>
<option value="11240" style=""  >1978</option>
<option value="11241" style=""  >1979</option>
<option value="11242" style=""  >1980</option>
<option value="11243" style=""  >1981</option>
<option value="11244" style=""  >1982</option>
<option value="11245" style=""  >1983</option>
<option value="11246" style=""  >1984</option>
<option value="11247" style=""  >1985</option>
<option value="11248" style=""  >1986</option>
<option value="11249" style=""  >1987</option>
<option value="11250" style=""  >1988</option>
<option value="11251" style=""  >1989</option>
<option value="11252" style=""  >1990</option>
<option value="11253" style=""  >1991</option>
<option value="11254" style=""  >1992</option>
<option value="11255" style=""  >1993</option>
<option value="11256" style=""  >1994</option>
<option value="11257" style=""  >1995</option>
<option value="11258" style=""  >1995以后</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2958" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你的居住城市?
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13515].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13515].id" value="" id="answers[13515].id" />

	<select group="13515" class="selection" id="question_13515" name="answers[13515].value" title="title"  size = "1" >
	<option selected="selected" value="0">请选择</option>
<option value="11259" style=""  >鞍山市</option>
<option value="11260" style=""  >蚌埠市</option>
<option value="11261" style=""  >包头市</option>
<option value="11262" style=""  >宝鸡市</option>
<option value="11263" style=""  >保定市</option>
<option value="11264" style=""  >北京市</option>
<option value="11265" style=""  >沧州市</option>
<option value="11266" style=""  >长春市</option>
<option value="11267" style=""  >长沙市</option>
<option value="11268" style=""  >常州市</option>
<option value="11269" style=""  >郴州市</option>
<option value="11270" style=""  >成都市</option>
<option value="11271" style=""  >大理市</option>
<option value="11272" style=""  >大连市</option>
<option value="11273" style=""  >大庆市</option>
<option value="11274" style=""  >大同市</option>
<option value="11275" style=""  >东莞市</option>
<option value="11276" style=""  >佛山市</option>
<option value="11277" style=""  >福州市</option>
<option value="11278" style=""  >抚顺市</option>
<option value="11279" style=""  >广州市</option>
<option value="11280" style=""  >贵阳市</option>
<option value="11281" style=""  >桂林市</option>
<option value="11282" style=""  >哈尔滨市</option>
<option value="11283" style=""  >海口市</option>
<option value="11284" style=""  >杭州市</option>
<option value="11285" style=""  >合肥市</option>
<option value="11286" style=""  >衡阳市</option>
<option value="11287" style=""  >呼和浩特市</option>
<option value="11288" style=""  >惠州市</option>
<option value="11289" style=""  >吉林市</option>
<option value="11290" style=""  >济南市</option>
<option value="11291" style=""  >嘉兴市</option>
<option value="11292" style=""  >江门市</option>
<option value="11293" style=""  >九江市</option>
<option value="11294" style=""  >开封市</option>
<option value="11295" style=""  >昆明市</option>
<option value="11296" style=""  >兰州市</option>
<option value="11297" style=""  >廊坊市</option>
<option value="11298" style=""  >连云港市</option>
<option value="11299" style=""  >洛阳市</option>
<option value="11300" style=""  >马安山市</option>
<option value="11301" style=""  >牡丹江市</option>
<option value="11302" style=""  >南昌市</option>
<option value="11303" style=""  >南京市</option>
<option value="11304" style=""  >南宁市</option>
<option value="11305" style=""  >南通市</option>
<option value="11306" style=""  >宁波市</option>
<option value="11307" style=""  >攀枝花市</option>
<option value="11308" style=""  >平顶山市</option>
<option value="11309" style=""  >齐齐哈尔</option>
<option value="11310" style=""  >秦皇岛市</option>
<option value="11311" style=""  >青岛市</option>
<option value="11312" style=""  >泉州市</option>
<option value="11313" style=""  >汕头市</option>
<option value="11314" style=""  >上海市</option>
<option value="11315" style=""  >绍兴市</option>
<option value="11316" style=""  >深圳市</option>
<option value="11317" style=""  >沈阳市</option>
<option value="11318" style=""  >石家庄市</option>
<option value="11319" style=""  >苏州市</option>
<option value="11320" style=""  >太原市</option>
<option value="11321" style=""  >泰州市</option>
<option value="11322" style=""  >唐山市</option>
<option value="11323" style=""  >天津市</option>
<option value="11324" style=""  >威海市</option>
<option value="11325" style=""  >潍坊市</option>
<option value="11326" style=""  >温州市</option>
<option value="11327" style=""  >乌鲁木齐市</option>
<option value="11328" style=""  >无锡市</option>
<option value="11329" style=""  >芜湖市</option>
<option value="11330" style=""  >武汉市</option>
<option value="11331" style=""  >西安市</option>
<option value="11332" style=""  >西宁市</option>
<option value="11333" style=""  >厦门市</option>
<option value="11334" style=""  >新乡市</option>
<option value="11335" style=""  >徐州市</option>
<option value="11336" style=""  >烟台市</option>
<option value="11337" style=""  >延安市</option>
<option value="11338" style=""  >扬州市</option>
<option value="11339" style=""  >宜宾市</option>
<option value="11340" style=""  >银川市</option>
<option value="11341" style=""  >玉林市</option>
<option value="11342" style=""  >玉溪市</option>
<option value="11343" style=""  >湛江市</option>
<option value="11344" style=""  >漳州市</option>
<option value="11345" style=""  >镇江市</option>
<option value="11346" style=""  >郑州市</option>
<option value="11347" style=""  >中山市</option>
<option value="11348" style=""  >重庆市</option>
<option value="11349" style=""  >珠海市</option>
<option value="11350" style=""  >淄博市</option>
<option value="11351" style=""  >自贡市</option>
<option value="11352" style=""  >遵义市</option>
<option value="11353" style=""  >其他</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2572" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的家庭月收入是多少？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13516].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13516].id" value="" id="answers[13516].id" />
<ul>
	<li>
			<input group="13516" type="radio" id="13516_0" name="answers[13516].value" value="9782"  class="selection question_radio_13516"  />		<label for="13516_0">少于￥3,000/月</label>
	</li>
	<li>
			<input group="13516" type="radio" id="13516_1" name="answers[13516].value" value="9783"  class="selection question_radio_13516"  />		<label for="13516_1">￥3,000～5,000/月</label>
	</li>
	<li>
			<input group="13516" type="radio" id="13516_2" name="answers[13516].value" value="9784"  class="selection question_radio_13516"  />		<label for="13516_2">￥5,000～7,000/月</label>
	</li>
	<li>
			<input group="13516" type="radio" id="13516_3" name="answers[13516].value" value="9785"  class="selection question_radio_13516"  />		<label for="13516_3">￥7,000～10,000/月</label>
	</li>
	<li>
			<input group="13516" type="radio" id="13516_4" name="answers[13516].value" value="9786"  class="selection question_radio_13516"  />		<label for="13516_4">￥10,000～15,000/月</label>
	</li>
	<li>
			<input group="13516" type="radio" id="13516_5" name="answers[13516].value" value="9787"  class="selection question_radio_13516"  />		<label for="13516_5">￥15,000～20,000/月</label>
	</li>
	<li>
			<input group="13516" type="radio" id="13516_6" name="answers[13516].value" value="9788"  class="selection question_radio_13516"  />		<label for="13516_6">多于￥20,000/月</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13516  qc_0 radio" type="radio" name="answers[13516].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2088" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						姓名:
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13517].id" value="" id="answers[13517].id" />
<input type="text" name="answers[13517].value" value="" id="question_13517" group="13517" class="input-text" />

<span class="error-content" id="err_answers[13517].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2089" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						电话:
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13518].id" value="" id="answers[13518].id" />
<input type="text" name="answers[13518].value" value="" id="question_13518" group="13518" class="input-text" />

<span class="error-content" id="err_answers[13518].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2661" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						邮箱:
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13519].id" value="" id="answers[13519].id" />
<input type="text" name="answers[13519].value" value="" id="question_13519" group="13519" class="input-text" />

<span class="error-content" id="err_answers[13519].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="提交" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
	        jQuery("#check-alert-dialog .content").html(html);
	        jQuery("#check-alert-dialog").dialog('open');
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '提交失败：不能提交空报告';
		    jQuery("#check-alert-dialog .content").html(html);
		    jQuery("#check-alert-dialog").dialog('open');
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[


	 Element.hide("q_2948");
	 Element.hide("q_2951");


var myrules = {
	   
	   "input#13504_1": function(el){
			el.onclick = function(){
				if ($("13504_1").checked){
						Element.show($("q_2948"));
				}
			}
		}
	,
	   
	   "input#13507_0": function(el){
			el.onclick = function(){
				if ($("13507_0").checked){
						Element.hide($("q_2951"));
				}
			}
		}
	,
	   
	   "input#13507_3": function(el){
			el.onclick = function(){
				if ($("13507_3").checked){
						Element.hide($("q_2951"));
				}
			}
		}
	,
	   
	   "input#13504_0": function(el){
			el.onclick = function(){
				if ($("13504_0").checked){
						Element.show($("q_2948"));
				}
			}
		}
	,
	   
	   "input#13507_4": function(el){
			el.onclick = function(){
				if ($("13507_4").checked){
						Element.show($("q_2951"));
				}
			}
		}
	,
	   
	   "input#13507_1": function(el){
			el.onclick = function(){
				if ($("13507_1").checked){
						Element.hide($("q_2951"));
				}
			}
		}
	,
	   
	   "input#13504_2": function(el){
			el.onclick = function(){
				if ($("13504_2").checked){
						Element.hide($("q_2948"));
				}
			}
		}
	,
	   
	   "input#13507_2": function(el){
			el.onclick = function(){
				if ($("13507_2").checked){
						Element.hide($("q_2951"));
				}
			}
		}
}

Behaviour.register(myrules);

// ]]>
-->
</script>
