	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/730" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />
<input type="hidden" name="surveyId" value="6yemraAnbJyC"/>

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2984" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你喝葡萄酒吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13651].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13651].id" value="" id="answers[13651].id" />
<ul>
	<li>
			<input group="13651" type="radio" id="13651_0" name="answers[13651].value" value="11414"  class="selection question_radio_13651" onclick="showOrHide1()" />		<label for="13651_0">是的，一个月超过两次</label>
	</li>
	<li>
			<input group="13651" type="radio" id="13651_1" name="answers[13651].value" value="11415"  class="selection question_radio_13651" onclick="showOrHide1()" />		<label for="13651_1">是的，大概半个月喝一次</label>
	</li>
	<li>
			<input group="13651" type="radio" id="13651_2" name="answers[13651].value" value="11416"  class="selection question_radio_13651" onclick="showOrHide1()" />		<label for="13651_2">是的，一个月一次</label>
	</li>
	<li>
			<input group="13651" type="radio" id="13651_3" name="answers[13651].value" value="11417"  class="selection question_radio_13651" onclick="showOrHide1()" />		<label for="13651_3">是的，但是少于每月一次</label>
	</li>
	<li>
			<input group="13651" type="radio" id="13651_4" name="answers[13651].value" value="11418"  class="selection question_radio_13651" onclick="showOrHide1()" />		<label for="13651_4">没喝过，但是我想尝试一下</label>
	</li>
	<li>
			<input group="13651" type="radio" id="13651_5" name="answers[13651].value" value="11419"  class="selection question_radio_13651" onclick="showOrHide1()"  />		<label for="13651_5">没喝过，我不喜欢葡萄酒</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13651  qc_0 radio" type="radio" name="answers[13651].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide1(){
	if(document.getElementById("13651_0").checked||document.getElementById("13651_1").checked||document.getElementById("13651_2").checked||document.getElementById("13651_3").checked){
		document.getElementById("q_2987").style.display="";
	}else{
		document.getElementById("q_2987").style.display="none";
	}
}
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2985" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你身边的朋友或家人喝葡萄酒吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13652].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13652].id" value="" id="answers[13652].id" />
<ul>
	<li>
			<input group="13652" type="radio" id="13652_0" name="answers[13652].value" value="11420"  class="selection question_radio_13652"  />		<label for="13652_0">是的，一个月超过两次</label>
	</li>
	<li>
			<input group="13652" type="radio" id="13652_1" name="answers[13652].value" value="11421"  class="selection question_radio_13652"  />		<label for="13652_1">是的，大概半个月喝一次</label>
	</li>
	<li>
			<input group="13652" type="radio" id="13652_2" name="answers[13652].value" value="11422"  class="selection question_radio_13652"  />		<label for="13652_2">是的，一个月一次</label>
	</li>
	<li>
			<input group="13652" type="radio" id="13652_3" name="answers[13652].value" value="11423"  class="selection question_radio_13652"  />		<label for="13652_3">是的，但是少于每月一次</label>
	</li>
	<li>
			<input group="13652" type="radio" id="13652_4" name="answers[13652].value" value="11424"  class="selection question_radio_13652"  />		<label for="13652_4">没喝过，但是他们想尝试一下</label>
	</li>
	<li>
			<input group="13652" type="radio" id="13652_5" name="answers[13652].value" value="11425"  class="selection question_radio_13652"  />		<label for="13652_5">没喝过，他们不喜欢葡萄酒</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13652  qc_0 radio" type="radio" name="answers[13652].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2986" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						除了葡萄酒以外，你经常喝哪些酒？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13653].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13653].id" value="" id="answers[13653].id" />
<ul>
	<li>
			<input group="13653" type="radio" id="13653_0" name="answers[13653].value" value="11426"  class="selection question_radio_13653" onclick="showOrHide2()" />		<label for="13653_0">啤酒</label>
	</li>
	<li>
			<input group="13653" type="radio" id="13653_1" name="answers[13653].value" value="11427"  class="selection question_radio_13653" onclick="showOrHide2()" />		<label for="13653_1">白酒</label>
	</li>
	<li>
			<input group="13653" type="radio" id="13653_2" name="answers[13653].value" value="11428"  class="selection question_radio_13653" onclick="showOrHide2()" />		<label for="13653_2">其他中国的酒（如黄酒等）</label>
	</li>
	<li>
			<input group="13653" type="radio" id="13653_3" name="answers[13653].value" value="11429"  class="selection question_radio_13653" onclick="showOrHide2()" />		<label for="13653_3">威士忌</label>
	</li>
	<li>
			<input group="13653" type="radio" id="13653_4" name="answers[13653].value" value="11430"  class="selection question_radio_13653" onclick="showOrHide2()" />		<label for="13653_4">伏特加</label>
	</li>
	<li>
			<input group="13653" type="radio" id="13653_5" name="answers[13653].value" value="11431"  class="selection question_radio_13653"  onclick="showOrHide2()" />		<label for="13653_5">其他（请详述）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13653  qc_0 radio" type="radio" name="answers[13653].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide2(){
	if(document.getElementById("13653_5").checked){
		document.getElementById("q_2644").style.display="";
	}else{
		document.getElementById("q_2644").style.display="none";
	}
}
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2644" style="margin-bottom:0px; display:none" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他酒
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13654].id" value="" id="answers[13654].id" />
<input type="text" name="answers[13654].value" value="" id="question_13654" group="13654" class="input-text" />

<span class="error-content" id="err_answers[13654].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2987" style="margin-bottom:0px; display:none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你之前喝过以下哪些葡萄酒？（多选）
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13655].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13655].id" value="" id="answers[13655].id" />




<span id="hint_13655">
</span>
<ul>
	<li>
			<input group="13655" class="question_radio_13655 selection" type="checkbox" id="13655_0" name="answers[13655].value" value="11432" 	onclick=" "/>		<label for="13655_0">中国葡萄酒</label>
	</li>
	<li>
			<input group="13655" class="question_radio_13655 selection" type="checkbox" id="13655_1" name="answers[13655].value" value="11433" 	onclick=" "/>		<label for="13655_1">澳大利亚葡萄酒</label>
	</li>
	<li>
			<input group="13655" class="question_radio_13655 selection" type="checkbox" id="13655_2" name="answers[13655].value" value="11434" 	onclick=" "/>		<label for="13655_2">西班牙葡萄酒</label>
	</li>
	<li>
			<input group="13655" class="question_radio_13655 selection" type="checkbox" id="13655_3" name="answers[13655].value" value="11435" 	onclick=" "/>		<label for="13655_3">意大利葡萄酒</label>
	</li>
	<li>
			<input group="13655" class="question_radio_13655 selection" type="checkbox" id="13655_4" name="answers[13655].value" value="11436" 	onclick=" "/>		<label for="13655_4">法国葡萄酒</label>
	</li>
	<li>
			<input group="13655" class="question_radio_13655 selection" type="checkbox" id="13655_5" name="answers[13655].value" value="11437" 	onclick=" "/>		<label for="13655_5">南美葡萄酒 (智利， 阿根廷...)</label>
	</li>
	<li>
			<input group="13655" class="question_radio_13655 selection" type="checkbox" id="13655_6" name="answers[13655].value" value="11438" 	onclick=" "/>		<label for="13655_6">南非葡萄酒</label>
	</li>
	<li>
			<input group="13655" class="question_radio_13655 selection" type="checkbox" id="13655_7" name="answers[13655].value" value="11439" 	onclick=" "/>		<label for="13655_7">我不记得了</label>
	</li>
	<li>
			<input group="13655" class="question_radio_13655 selection" type="checkbox" id="13655_8" name="answers[13655].value" value="11440" 	onclick="showOrHide3() "/>		<label for="13655_8">其他（请详述）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide3(){
	if(document.getElementById("13655_8").checked){
		document.getElementById("q_3003").style.display="";
	}else if(!document.getElementById("13655_8").checked){
		document.getElementById("q_3003").style.display="none";
	}
}
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3003" style="margin-bottom:0px; display:none" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他葡萄酒
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13656].id" value="" id="answers[13656].id" />
<input type="text" name="answers[13656].value" value="" id="question_13656" group="13656" class="input-text" />

<span class="error-content" id="err_answers[13656].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2988" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你最后一次喝葡萄酒是在什么情况下？（多选）
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13657].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13657].id" value="" id="answers[13657].id" />




<span id="hint_13657">
</span>
<ul>
	<li>
			<input group="13657" class="question_radio_13657 selection" type="checkbox" id="13657_0" name="answers[13657].value" value="11441" 	onclick=" "/>		<label for="13657_0">过年的时候</label>
	</li>
	<li>
			<input group="13657" class="question_radio_13657 selection" type="checkbox" id="13657_1" name="answers[13657].value" value="11442" 	onclick=" "/>		<label for="13657_1">品尝新款葡萄酒</label>
	</li>
	<li>
			<input group="13657" class="question_radio_13657 selection" type="checkbox" id="13657_2" name="answers[13657].value" value="11443" 	onclick=" "/>		<label for="13657_2">在饭店里</label>
	</li>
	<li>
			<input group="13657" class="question_radio_13657 selection" type="checkbox" id="13657_3" name="answers[13657].value" value="11444" 	onclick=" "/>		<label for="13657_3">在酒吧里</label>
	</li>
	<li>
			<input group="13657" class="question_radio_13657 selection" type="checkbox" id="13657_4" name="answers[13657].value" value="11445" 	onclick=" "/>		<label for="13657_4">在家里</label>
	</li>
	<li>
			<input group="13657" class="question_radio_13657 selection" type="checkbox" id="13657_5" name="answers[13657].value" value="11446" 	onclick=" "/>		<label for="13657_5">独自一人</label>
	</li>
	<li>
			<input group="13657" class="question_radio_13657 selection" type="checkbox" id="13657_6" name="answers[13657].value" value="11447" 	onclick=" "/>		<label for="13657_6">与朋友一起</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2989" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你喜欢以下哪种葡萄酒？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13658].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13658].id" value="" id="answers[13658].id" />
<ul>
	<li>
			<input group="13658" type="radio" id="13658_0" name="answers[13658].value" value="11448"  class="selection question_radio_13658"onclick="showOrHide4()"  />		<label for="13658_0">中国葡萄酒</label>
	</li>
	<li>
			<input group="13658" type="radio" id="13658_1" name="answers[13658].value" value="11449"  class="selection question_radio_13658" onclick="showOrHide4()" />		<label for="13658_1">澳大利亚葡萄酒</label>
	</li>
	<li>
			<input group="13658" type="radio" id="13658_2" name="answers[13658].value" value="11450"  class="selection question_radio_13658" onclick="showOrHide4()" />		<label for="13658_2">西班牙葡萄酒</label>
	</li>
	<li>
			<input group="13658" type="radio" id="13658_3" name="answers[13658].value" value="11451"  class="selection question_radio_13658" onclick="showOrHide4()" />		<label for="13658_3">意大利葡萄酒</label>
	</li>
	<li>
			<input group="13658" type="radio" id="13658_4" name="answers[13658].value" value="11452"  class="selection question_radio_13658"onclick="showOrHide4()"  />		<label for="13658_4">法国葡萄酒</label>
	</li>
	<li>
			<input group="13658" type="radio" id="13658_5" name="answers[13658].value" value="11453"  class="selection question_radio_13658" onclick="showOrHide4()" />		<label for="13658_5">南美葡萄酒 (智利， 阿根廷...)</label>
	</li>
	<li>
			<input group="13658" type="radio" id="13658_6" name="answers[13658].value" value="11454"  class="selection question_radio_13658" onclick="showOrHide4()" />		<label for="13658_6">南非葡萄酒</label>
	</li>
	<li>
			<input group="13658" type="radio" id="13658_7" name="answers[13658].value" value="11455"  class="selection question_radio_13658" onclick="showOrHide4()" />		<label for="13658_7">我不太清楚</label>
	</li>
	<li>
			<input group="13658" type="radio" id="13658_8" name="answers[13658].value" value="11456"  class="selection question_radio_13658"  onclick="showOrHide4()" />		<label for="13658_8">其他（请详述）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13658  qc_0 radio" type="radio" name="answers[13658].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide4(){
	if(document.getElementById("13658_8").checked){
		document.getElementById("q_3004").style.display="";
	}else{
		document.getElementById("q_3004").style.display="none";
	}
}
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3004" style="margin-bottom:0px; display:none" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他喜欢的葡萄酒
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13659].id" value="" id="answers[13659].id" />
<input type="text" name="answers[13659].value" value="" id="question_13659" group="13659" class="input-text" />

<span class="error-content" id="err_answers[13659].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3008" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你喜欢这种葡萄酒的原因是什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13660].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13660].id" value="" id="answers[13660].id" />
<ul>
	<li>
			<input group="13660" type="radio" id="13660_0" name="answers[13660].value" value="11520"  class="selection question_radio_13660" onclick="showOrHide5()" />		<label for="13660_0">有名的品牌</label>
	</li>
	<li>
			<input group="13660" type="radio" id="13660_1" name="answers[13660].value" value="11521"  class="selection question_radio_13660" onclick="showOrHide5()" />		<label for="13660_1">价格合适</label>
	</li>
	<li>
			<input group="13660" type="radio" id="13660_2" name="answers[13660].value" value="11522"  class="selection question_radio_13660" onclick="showOrHide5()" />		<label for="13660_2">朋友及家人的推荐</label>
	</li>
	<li>
			<input group="13660" type="radio" id="13660_3" name="answers[13660].value" value="11523"  class="selection question_radio_13660" onclick="showOrHide5()" />		<label for="13660_3">广告及品牌形象</label>
	</li>
	<li>
			<input group="13660" type="radio" id="13660_4" name="answers[13660].value" value="11524"  class="selection question_radio_13660" onclick="showOrHide5()" />		<label for="13660_4">味道不错</label>
	</li>
	<li>
			<input group="13660" type="radio" id="13660_5" name="answers[13660].value" value="11525"  class="selection question_radio_13660"  onclick="showOrHide5()" />		<label for="13660_5">其他（请详述）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13660  qc_0 radio" type="radio" name="answers[13660].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide5(){
	if(document.getElementById("13660_5").checked){
		document.getElementById("q_2832").style.display="";
	}else{
		document.getElementById("q_2832").style.display="none";
	}
}
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2832" style="margin-bottom:0px; display:none" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他原因
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13661].id" value="" id="answers[13661].id" />
<input type="text" name="answers[13661].value" value="" id="question_13661" group="13661" class="input-text" />

<span class="error-content" id="err_answers[13661].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2991" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						当提到法国葡萄酒的时候，你会觉得：
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13662].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13662].id" value="" id="answers[13662].id" />
<ul>
	<li>
			<input group="13662" type="radio" id="13662_0" name="answers[13662].value" value="11463"  class="selection question_radio_13662"  />		<label for="13662_0">非常正面</label>
	</li>
	<li>
			<input group="13662" type="radio" id="13662_1" name="answers[13662].value" value="11464"  class="selection question_radio_13662"  />		<label for="13662_1">有点正面</label>
	</li>
	<li>
			<input group="13662" type="radio" id="13662_2" name="answers[13662].value" value="11465"  class="selection question_radio_13662"  />		<label for="13662_2">一般</label>
	</li>
	<li>
			<input group="13662" type="radio" id="13662_3" name="answers[13662].value" value="11466"  class="selection question_radio_13662"  />		<label for="13662_3">有点负面</label>
	</li>
	<li>
			<input group="13662" type="radio" id="13662_4" name="answers[13662].value" value="11467"  class="selection question_radio_13662"  />		<label for="13662_4">非常负面</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13662  qc_0 radio" type="radio" name="answers[13662].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3009" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请用一句简短的话解释你的选择：
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13663].id" value="" id="answers[13663].id" />
<textarea name="answers[13663].value" id="question_13663" cols="40" group="13663" rows="2" class="input-text" ></textarea>
<span class="error-content" id="err_answers[13663].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2993" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你听说过下列那些法国葡萄酒产地？(多选)
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13664].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13664].id" value="" id="answers[13664].id" />




<span id="hint_13664">
</span>
<ul>
	<li>
			<input group="13664" class="question_radio_13664 selection" type="checkbox" id="13664_0" name="answers[13664].value" value="11468" 	onclick=" "/>		<label for="13664_0">阿尔萨斯</label>
	</li>
	<li>
			<input group="13664" class="question_radio_13664 selection" type="checkbox" id="13664_1" name="answers[13664].value" value="11469" 	onclick=" "/>		<label for="13664_1">波尔多</label>
	</li>
	<li>
			<input group="13664" class="question_radio_13664 selection" type="checkbox" id="13664_2" name="answers[13664].value" value="11470" 	onclick=" "/>		<label for="13664_2">勃艮第</label>
	</li>
	<li>
			<input group="13664" class="question_radio_13664 selection" type="checkbox" id="13664_3" name="answers[13664].value" value="11471" 	onclick=" "/>		<label for="13664_3">香槟</label>
	</li>
	<li>
			<input group="13664" class="question_radio_13664 selection" type="checkbox" id="13664_4" name="answers[13664].value" value="11472" 	onclick=" "/>		<label for="13664_4">郎格多克</label>
	</li>
	<li>
			<input group="13664" class="question_radio_13664 selection" type="checkbox" id="13664_5" name="answers[13664].value" value="11473" 	onclick=" "/>		<label for="13664_5">卢瓦尔河</label>
	</li>
	<li>
			<input group="13664" class="question_radio_13664 selection" type="checkbox" id="13664_6" name="answers[13664].value" value="11474" 	onclick="showOrHide6() "/>		<label for="13664_6">其他（请详述）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide6(){
	if(document.getElementById("13664_6").checked){
		document.getElementById("q_3005").style.display="";
	}else if(!document.getElementById("13664_6").checked){
		document.getElementById("q_3005").style.display="none";
	}
}
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3005" style="margin-bottom:0px; display:none" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他产地
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13665].id" value="" id="answers[13665].id" />
<input type="text" name="answers[13665].value" value="" id="question_13665" group="13665" class="input-text" />

<span class="error-content" id="err_answers[13665].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2994" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你一般通过下列哪些渠道了解法国葡萄酒？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13666].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13666].id" value="" id="answers[13666].id" />
<ul>
	<li>
			<input group="13666" type="radio" id="13666_0" name="answers[13666].value" value="11475"  class="selection question_radio_13666"  />		<label for="13666_0">电视</label>
	</li>
	<li>
			<input group="13666" type="radio" id="13666_1" name="answers[13666].value" value="11476"  class="selection question_radio_13666"  />		<label for="13666_1">印刷材料</label>
	</li>
	<li>
			<input group="13666" type="radio" id="13666_2" name="answers[13666].value" value="11477"  class="selection question_radio_13666"  />		<label for="13666_2">户外广告</label>
	</li>
	<li>
			<input group="13666" type="radio" id="13666_3" name="answers[13666].value" value="11478"  class="selection question_radio_13666"  />		<label for="13666_3">网上</label>
	</li>
	<li>
			<input group="13666" type="radio" id="13666_4" name="answers[13666].value" value="11479"  class="selection question_radio_13666"  />		<label for="13666_4">电台</label>
	</li>
	<li>
			<input group="13666" type="radio" id="13666_5" name="answers[13666].value" value="11480"  class="selection question_radio_13666"  onclick="showOrHide7" />		<label for="13666_5">其他</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13666  qc_0 radio" type="radio" name="answers[13666].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide7(){
	if(document.getElementById("13666_5").checked){
		document.getElementById("q_3006").style.display="";
	}else{
		document.getElementById("q_3006").style.display="none";
	}
}

</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3006" style="margin-bottom:0px; display:none" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他渠道
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13667].id" value="" id="answers[13667].id" />
<input type="text" name="answers[13667].value" value="" id="question_13667" group="13667" class="input-text" />

<span class="error-content" id="err_answers[13667].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2995" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你自己购买葡萄酒吗？(多选)
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13668].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13668].id" value="" id="answers[13668].id" />




<span id="hint_13668">
</span>
<ul>
	<li>
			<input group="13668" class="question_radio_13668 selection" type="checkbox" id="13668_0" name="answers[13668].value" value="11481" 	onclick=" "/>		<label for="13668_0">不</label>
	</li>
	<li>
			<input group="13668" class="question_radio_13668 selection" type="checkbox" id="13668_1" name="answers[13668].value" value="11482" 	onclick=" "/>		<label for="13668_1">是的，在店里</label>
	</li>
	<li>
			<input group="13668" class="question_radio_13668 selection" type="checkbox" id="13668_2" name="answers[13668].value" value="11483" 	onclick=" "/>		<label for="13668_2">是的，在网上</label>
	</li>
	<li>
			<input group="13668" class="question_radio_13668 selection" type="checkbox" id="13668_3" name="answers[13668].value" value="11484" 	onclick=" "/>		<label for="13668_3">是的，在饭店，酒吧或迪厅里</label>
	</li>
	<li>
			<input group="13668" class="question_radio_13668 selection" type="checkbox" id="13668_4" name="answers[13668].value" value="11485" 	onclick="showOrHide8() "/>		<label for="13668_4">是的，在其他地方（请详述）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide8(){
	if(document.getElementById("13668_4").checked){
		document.getElementById("q_2646").style.display="";
	}else if(!document.getElementById("13668_4").checked){
		document.getElementById("q_2646").style.display="none";
	}
}
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2646" style="margin-bottom:0px; display:none" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他地方
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13669].id" value="" id="answers[13669].id" />
<input type="text" name="answers[13669].value" value="" id="question_13669" group="13669" class="input-text" />

<span class="error-content" id="err_answers[13669].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2996" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你在购买法国葡萄酒时遇到的最大的困难是什么？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13670].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13670].id" value="" id="answers[13670].id" />
<ul>
	<li>
			<input group="13670" type="radio" id="13670_0" name="answers[13670].value" value="11486"  class="selection question_radio_13670"  />		<label for="13670_0">我不清楚怎样挑选葡萄酒</label>
	</li>
	<li>
			<input group="13670" type="radio" id="13670_1" name="answers[13670].value" value="11487"  class="selection question_radio_13670"  />		<label for="13670_1">我不确定葡萄酒的品质</label>
	</li>
	<li>
			<input group="13670" type="radio" id="13670_2" name="answers[13670].value" value="11488"  class="selection question_radio_13670"  />		<label for="13670_2">担心被骗</label>
	</li>
	<li>
			<input group="13670" type="radio" id="13670_3" name="answers[13670].value" value="11489"  class="selection question_radio_13670"  />		<label for="13670_3">价格太贵</label>
	</li>
	<li>
			<input group="13670" type="radio" id="13670_4" name="answers[13670].value" value="11490"  class="selection question_radio_13670"  />		<label for="13670_4">我不了解各种葡萄的品种</label>
	</li>
	<li>
			<input group="13670" type="radio" id="13670_5" name="answers[13670].value" value="11491"  class="selection question_radio_13670"  />		<label for="13670_5">我不清楚葡萄酒与每餐的搭配（正确的饮用搭配）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13670  qc_0 radio" type="radio" name="answers[13670].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2997" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						当你最终决定买某个牌子的葡萄酒时，影响你做决定的因素是：
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13671].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13671].id" value="" id="answers[13671].id" />
<ul>
	<li>
			<input group="13671" type="radio" id="13671_0" name="answers[13671].value" value="11492"  class="selection question_radio_13671"  />		<label for="13671_0">价格</label>
	</li>
	<li>
			<input group="13671" type="radio" id="13671_1" name="answers[13671].value" value="11493"  class="selection question_radio_13671"  />		<label for="13671_1">葡萄酒产地</label>
	</li>
	<li>
			<input group="13671" type="radio" id="13671_2" name="answers[13671].value" value="11494"  class="selection question_radio_13671"  />		<label for="13671_2">葡萄酒质量</label>
	</li>
	<li>
			<input group="13671" type="radio" id="13671_3" name="answers[13671].value" value="11495"  class="selection question_radio_13671"  />		<label for="13671_3">年份</label>
	</li>
	<li>
			<input group="13671" type="radio" id="13671_4" name="answers[13671].value" value="11496"  class="selection question_radio_13671"  />		<label for="13671_4">我不太挑剔，基本上是随便选择</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13671  qc_0 radio" type="radio" name="answers[13671].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2998" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你了解AOC，IGP和VDP的意思吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13672].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13672].id" value="" id="answers[13672].id" />
<ul>
	<li>
			<input group="13672" type="radio" id="13672_0" name="answers[13672].value" value="11497"  class="selection question_radio_13672"  />		<label for="13672_0">不知道</label>
	</li>
	<li>
			<input group="13672" type="radio" id="13672_1" name="answers[13672].value" value="11498"  class="selection question_radio_13672"  />		<label for="13672_1">我只知道其中的一个</label>
	</li>
	<li>
			<input group="13672" type="radio" id="13672_2" name="answers[13672].value" value="11499"  class="selection question_radio_13672"  />		<label for="13672_2">我知道两个</label>
	</li>
	<li>
			<input group="13672" type="radio" id="13672_3" name="answers[13672].value" value="11500"  class="selection question_radio_13672"  />		<label for="13672_3">我全部都知道</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13672  qc_0 radio" type="radio" name="answers[13672].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2999" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						作为星星火的会员，你愿意了解并尝试更多的法国葡萄酒吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13673].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13673].id" value="" id="answers[13673].id" />
<ul>
	<li>
			<input group="13673" type="radio" id="13673_0" name="answers[13673].value" value="11501"  class="selection question_radio_13673"  onclick="showOrHide9()"/>		<label for="13673_0">是的，我愿意</label>
	</li>
	<li>
			<input group="13673" type="radio" id="13673_1" name="answers[13673].value" value="11502"  class="selection question_radio_13673"  onclick="showOrHide9()" />		<label for="13673_1">是的，我愿意，我还想了解其他酒类（请详述）</label>
	</li>
	<li>
			<input group="13673" type="radio" id="13673_2" name="answers[13673].value" value="11503"  class="selection question_radio_13673" onclick="showOrHide9()" />		<label for="13673_2">不，谢谢</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13673  qc_0 radio" type="radio" name="answers[13673].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide9(){
	if(document.getElementById("13673_1").checked){
		document.getElementById("q_3010").style.display="";
	}else{
		document.getElementById("q_3010").style.display="none";
	}
}
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3010" style="margin-bottom:0px; display:none" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他酒类
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13674].id" value="" id="answers[13674].id" />
<input type="text" name="answers[13674].value" value="" id="question_13674" group="13674" class="input-text" />

<span class="error-content" id="err_answers[13674].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3011" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的年龄
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13675].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13675].id" value="" id="answers[13675].id" />
<ul>
	<li>
			<input group="13675" type="radio" id="13675_0" name="answers[13675].value" value="11526"  class="selection question_radio_13675"  />		<label for="13675_0">&lt;25岁</label>
	</li>
	<li>
			<input group="13675" type="radio" id="13675_1" name="answers[13675].value" value="11527"  class="selection question_radio_13675"  />		<label for="13675_1">25-34岁</label>
	</li>
	<li>
			<input group="13675" type="radio" id="13675_2" name="answers[13675].value" value="11528"  class="selection question_radio_13675"  />		<label for="13675_2">35-44岁</label>
	</li>
	<li>
			<input group="13675" type="radio" id="13675_3" name="answers[13675].value" value="11529"  class="selection question_radio_13675"  />		<label for="13675_3">45-54岁</label>
	</li>
	<li>
			<input group="13675" type="radio" id="13675_4" name="answers[13675].value" value="11530"  class="selection question_radio_13675"  />		<label for="13675_4">&gt;54岁</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13675  qc_0 radio" type="radio" name="answers[13675].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3001" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的性别
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13676].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13676].id" value="" id="answers[13676].id" />
<ul>
	<li>
			<input group="13676" type="radio" id="13676_0" name="answers[13676].value" value="11509"  class="selection question_radio_13676"  />		<label for="13676_0">女性</label>
	</li>
	<li>
			<input group="13676" type="radio" id="13676_1" name="answers[13676].value" value="11510"  class="selection question_radio_13676"  />		<label for="13676_1">男性</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13676  qc_0 radio" type="radio" name="answers[13676].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3012" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的婚姻状况
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13677].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13677].id" value="" id="answers[13677].id" />
<ul>
	<li>
			<input group="13677" type="radio" id="13677_0" name="answers[13677].value" value="11531"  class="selection question_radio_13677"  />		<label for="13677_0">单身</label>
	</li>
	<li>
			<input group="13677" type="radio" id="13677_1" name="answers[13677].value" value="11532"  class="selection question_radio_13677"  />		<label for="13677_1">结婚了，但还没有孩子</label>
	</li>
	<li>
			<input group="13677" type="radio" id="13677_2" name="answers[13677].value" value="11533"  class="selection question_radio_13677"  />		<label for="13677_2">结婚了，有孩子了</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13677  qc_0 radio" type="radio" name="answers[13677].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3007" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的家庭月收入是多少
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13678].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13678].id" value="" id="answers[13678].id" />
<ul>
	<li>
			<input group="13678" type="radio" id="13678_0" name="answers[13678].value" value="11514"  class="selection question_radio_13678"  />		<label for="13678_0">&lt; 5,000/月</label>
	</li>
	<li>
			<input group="13678" type="radio" id="13678_1" name="answers[13678].value" value="11515"  class="selection question_radio_13678"  />		<label for="13678_1">￥5,000～10,000/月</label>
	</li>
	<li>
			<input group="13678" type="radio" id="13678_2" name="answers[13678].value" value="11516"  class="selection question_radio_13678"  />		<label for="13678_2">￥10,000～15,000/月</label>
	</li>
	<li>
			<input group="13678" type="radio" id="13678_3" name="answers[13678].value" value="11517"  class="selection question_radio_13678"  />		<label for="13678_3">￥15,000～20,000/月</label>
	</li>
	<li>
			<input group="13678" type="radio" id="13678_4" name="answers[13678].value" value="11518"  class="selection question_radio_13678"  />		<label for="13678_4">￥20,000～25,000/月</label>
	</li>
	<li>
			<input group="13678" type="radio" id="13678_5" name="answers[13678].value" value="11519"  class="selection question_radio_13678"  />		<label for="13678_5">&gt;25,000/月</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13678  qc_0 radio" type="radio" name="answers[13678].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="提交" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
	        jQuery("#check-alert-dialog .content").html(html);
	        jQuery("#check-alert-dialog").dialog('open');
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '提交失败：不能提交空报告';
		    jQuery("#check-alert-dialog .content").html(html);
		    jQuery("#check-alert-dialog").dialog('open');
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

// ]]>
-->
</script>
