	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/732" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />
<input type="hidden" name="surveyId" value="dPKTUD99lXS5"/>

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3013" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你平时化妆需要多长时间？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13722].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13722].id" value="" id="answers[13722].id" />
<ul>
	<li>
			<input group="13722" type="radio" id="13722_0" name="answers[13722].value" value="11535"  class="selection question_radio_13722"  />		<label for="13722_0">我很少化妆</label>
	</li>
	<li>
			<input group="13722" type="radio" id="13722_1" name="answers[13722].value" value="11536"  class="selection question_radio_13722"  />		<label for="13722_1">少于5分钟</label>
	</li>
	<li>
			<input group="13722" type="radio" id="13722_2" name="answers[13722].value" value="11537"  class="selection question_radio_13722"  />		<label for="13722_2">5到15分钟</label>
	</li>
	<li>
			<input group="13722" type="radio" id="13722_3" name="answers[13722].value" value="11538"  class="selection question_radio_13722"  />		<label for="13722_3">15到30分钟</label>
	</li>
	<li>
			<input group="13722" type="radio" id="13722_4" name="answers[13722].value" value="11539"  class="selection question_radio_13722"  />		<label for="13722_4">超过30分钟</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13722  qc_0 radio" type="radio" name="answers[13722].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3016" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你最喜欢哪些化妆品品牌？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13723].id" value="" id="answers[13723].id" />
<input type="text" name="answers[13723].value" value="" id="question_13723" group="13723" class="input-text" />

<span class="error-content" id="err_answers[13723].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3017" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你会经常和朋友一起去做指甲、做头发、去美容店吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13724].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13724].id" value="" id="answers[13724].id" />
<ul>
	<li>
			<input group="13724" type="radio" id="13724_0" name="answers[13724].value" value="11548"  class="selection question_radio_13724"  />		<label for="13724_0">从来不去</label>
	</li>
	<li>
			<input group="13724" type="radio" id="13724_1" name="answers[13724].value" value="11549"  class="selection question_radio_13724"  />		<label for="13724_1">一年三四次</label>
	</li>
	<li>
			<input group="13724" type="radio" id="13724_2" name="answers[13724].value" value="11550"  class="selection question_radio_13724"  />		<label for="13724_2">每二个月一次</label>
	</li>
	<li>
			<input group="13724" type="radio" id="13724_3" name="answers[13724].value" value="11551"  class="selection question_radio_13724"  />		<label for="13724_3">每月一次</label>
	</li>
	<li>
			<input group="13724" type="radio" id="13724_4" name="answers[13724].value" value="11552"  class="selection question_radio_13724"  />		<label for="13724_4">每月好几次</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13724  qc_0 radio" type="radio" name="answers[13724].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3018" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的朋友们和你一样都很关注美容吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13725].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13725].id" value="" id="answers[13725].id" />
<ul>
	<li>
			<input group="13725" type="radio" id="13725_0" name="answers[13725].value" value="11553"  class="selection question_radio_13725"  />		<label for="13725_0">我更关注些</label>
	</li>
	<li>
			<input group="13725" type="radio" id="13725_1" name="answers[13725].value" value="11554"  class="selection question_radio_13725"  />		<label for="13725_1">我们关注的程度一样</label>
	</li>
	<li>
			<input group="13725" type="radio" id="13725_2" name="answers[13725].value" value="11555"  class="selection question_radio_13725"  />		<label for="13725_2">我们都很关注，她/他们把我视作达人</label>
	</li>
	<li>
			<input group="13725" type="radio" id="13725_3" name="answers[13725].value" value="11556"  class="selection question_radio_13725"  />		<label for="13725_3">我们都很关注，我把她/他们视作达人</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13725  qc_0 radio" type="radio" name="answers[13725].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3019" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你每月花多少钱在化妆品或头发护理上？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13726].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13726].id" value="" id="answers[13726].id" />
<ul>
	<li>
			<input group="13726" type="radio" id="13726_0" name="answers[13726].value" value="11557"  class="selection question_radio_13726"  />		<label for="13726_0">低于200元</label>
	</li>
	<li>
			<input group="13726" type="radio" id="13726_1" name="answers[13726].value" value="11558"  class="selection question_radio_13726"  />		<label for="13726_1">200-400元</label>
	</li>
	<li>
			<input group="13726" type="radio" id="13726_2" name="answers[13726].value" value="11559"  class="selection question_radio_13726"  />		<label for="13726_2">400-800元</label>
	</li>
	<li>
			<input group="13726" type="radio" id="13726_3" name="answers[13726].value" value="11560"  class="selection question_radio_13726"  />		<label for="13726_3">800-1500元</label>
	</li>
	<li>
			<input group="13726" type="radio" id="13726_4" name="answers[13726].value" value="11561"  class="selection question_radio_13726"  />		<label for="13726_4">1500-2500元</label>
	</li>
	<li>
			<input group="13726" type="radio" id="13726_5" name="answers[13726].value" value="11562"  class="selection question_radio_13726"  />		<label for="13726_5">高于2500元</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13726  qc_0 radio" type="radio" name="answers[13726].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3030" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						常购买选择下面哪一类化妆品？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13727].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13727].id" value="" id="answers[13727].id" />




<span id="hint_13727">
    Please select at most  3 values.<br>
</span>
<ul>
	<li>
			<input group="13727" class="question_radio_13727 selection" type="checkbox" id="13727_0" name="answers[13727].value" value="11686" 	onclick="checkChanged('13727_0',3,0);  "/>		<label for="13727_0">大众化妆品（如巴黎欧莱雅、玉兰油）</label>
	</li>
	<li>
			<input group="13727" class="question_radio_13727 selection" type="checkbox" id="13727_1" name="answers[13727].value" value="11687" 	onclick="checkChanged('13727_1',3,0);  "/>		<label for="13727_1">高级化妆品（如香奈尔、迪奥）</label>
	</li>
	<li>
			<input group="13727" class="question_radio_13727 selection" type="checkbox" id="13727_2" name="answers[13727].value" value="11688" 	onclick="checkChanged('13727_2',3,0);  "/>		<label for="13727_2">纯天然/有机产品（如悦木之源、欧舒丹）</label>
	</li>
	<li>
			<input group="13727" class="question_radio_13727 selection" type="checkbox" id="13727_3" name="answers[13727].value" value="11689" 	onclick="checkChanged('13727_3',3,0);  "/>		<label for="13727_3">药妆产品（如雅漾、薇姿）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

	
		if(typeof previouslySelectedOptions == "undefined") {
				var previouslySelectedOptions = new Array();
		}
				
		if(typeof previouslySelectedOptions[13727]=="undefined") {		
			 previouslySelectedOptions[13727] = new Array();
						
		}

		if(typeof checkChanged=="undefined") {
			checkChanged = function(id, max, min) {
				var elementId = id.split("_")[0];
				if($(id).checked == true) {				
					previouslySelectedOptions[elementId].push(id);
					// if there are now more elements in the array than allowed, delete the first one
					if (previouslySelectedOptions[elementId].length > max && max != 0){
						$(previouslySelectedOptions[elementId][0]).checked=false;
						previouslySelectedOptions[elementId].shift();					
					}	
				} else {
				   var newArray = new Array();
				    // delete the now unselected checkbox from the array
					for (var i = 0; i < previouslySelectedOptions[elementId].length; i++) {
						if (previouslySelectedOptions[elementId][i] != id) {
							newArray.push(previouslySelectedOptions[elementId][i]);
						}
					}
					previouslySelectedOptions[elementId] = newArray;
				}
				if (previouslySelectedOptions[elementId].length < min  && min != 0) {
					new Effect.Pulsate("hint_13727", {pulses:1, from:0.4});
				}		
			}
		}
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3031" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						平时通过哪种渠道购买美容产品？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13728].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13728].id" value="" id="answers[13728].id" />




<span id="hint_13728">
    Please select at most  3 values.<br>
</span>
<ul>
	<li>
			<input group="13728" class="question_radio_13728 selection" type="checkbox" id="13728_0" name="answers[13728].value" value="11690" 	onclick="checkChanged('13728_0',3,0);  "/>		<label for="13728_0">化妆品专卖店（丝芙兰，SASA等）</label>
	</li>
	<li>
			<input group="13728" class="question_radio_13728 selection" type="checkbox" id="13728_1" name="answers[13728].value" value="11691" 	onclick="checkChanged('13728_1',3,0);  "/>		<label for="13728_1">药房/超市</label>
	</li>
	<li>
			<input group="13728" class="question_radio_13728 selection" type="checkbox" id="13728_2" name="answers[13728].value" value="11692" 	onclick="checkChanged('13728_2',3,0);  "/>		<label for="13728_2">品牌专柜</label>
	</li>
	<li>
			<input group="13728" class="question_radio_13728 selection" type="checkbox" id="13728_3" name="answers[13728].value" value="11693" 	onclick="checkChanged('13728_3',3,0);  "/>		<label for="13728_3">在线商城/品牌官网</label>
	</li>
	<li>
			<input group="13728" class="question_radio_13728 selection" type="checkbox" id="13728_4" name="answers[13728].value" value="11694" 	onclick="checkChanged('13728_4',3,0);  "/>		<label for="13728_4">沙龙/美容院/SPA</label>
	</li>
	<li>
			<input group="13728" class="question_radio_13728 selection" type="checkbox" id="13728_5" name="answers[13728].value" value="11695" 	onclick="checkChanged('13728_5',3,0);  "/>		<label for="13728_5">免税店</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

	
		if(typeof previouslySelectedOptions == "undefined") {
				var previouslySelectedOptions = new Array();
		}
				
		if(typeof previouslySelectedOptions[13728]=="undefined") {		
			 previouslySelectedOptions[13728] = new Array();
						
		}

		if(typeof checkChanged=="undefined") {
			checkChanged = function(id, max, min) {
				var elementId = id.split("_")[0];
				if($(id).checked == true) {				
					previouslySelectedOptions[elementId].push(id);
					// if there are now more elements in the array than allowed, delete the first one
					if (previouslySelectedOptions[elementId].length > max && max != 0){
						$(previouslySelectedOptions[elementId][0]).checked=false;
						previouslySelectedOptions[elementId].shift();					
					}	
				} else {
				   var newArray = new Array();
				    // delete the now unselected checkbox from the array
					for (var i = 0; i < previouslySelectedOptions[elementId].length; i++) {
						if (previouslySelectedOptions[elementId][i] != id) {
							newArray.push(previouslySelectedOptions[elementId][i]);
						}
					}
					previouslySelectedOptions[elementId] = newArray;
				}
				if (previouslySelectedOptions[elementId].length < min  && min != 0) {
					new Effect.Pulsate("hint_13728", {pulses:1, from:0.4});
				}		
			}
		}
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3032" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						平时通过哪种渠道获得化妆品或美容信息？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13729].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13729].id" value="" id="answers[13729].id" />




<span id="hint_13729">
</span>
<ul>
	<li>
			<input group="13729" class="question_radio_13729 selection" type="checkbox" id="13729_0" name="answers[13729].value" value="11696" 	onclick=" "/>		<label for="13729_0">电视, 杂志, 报纸</label>
	</li>
	<li>
			<input group="13729" class="question_radio_13729 selection" type="checkbox" id="13729_1" name="answers[13729].value" value="11697" 	onclick=" "/>		<label for="13729_1">百货店, 卖场</label>
	</li>
	<li>
			<input group="13729" class="question_radio_13729 selection" type="checkbox" id="13729_2" name="answers[13729].value" value="11698" 	onclick=" "/>		<label for="13729_2">博客, Newsletter</label>
	</li>
	<li>
			<input group="13729" class="question_radio_13729 selection" type="checkbox" id="13729_3" name="answers[13729].value" value="11699" 	onclick=" "/>		<label for="13729_3">BBS及产品使用评论</label>
	</li>
	<li>
			<input group="13729" class="question_radio_13729 selection" type="checkbox" id="13729_4" name="answers[13729].value" value="11700" 	onclick=" "/>		<label for="13729_4">家人或朋友</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3020" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在过去2年里，你用过多少个化妆品品牌？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13730].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13730].id" value="" id="answers[13730].id" />
<ul>
	<li>
			<input group="13730" type="radio" id="13730_0" name="answers[13730].value" value="11563"  class="selection question_radio_13730"  />		<label for="13730_0">1个</label>
	</li>
	<li>
			<input group="13730" type="radio" id="13730_1" name="answers[13730].value" value="11564"  class="selection question_radio_13730"  />		<label for="13730_1">2-3个</label>
	</li>
	<li>
			<input group="13730" type="radio" id="13730_2" name="answers[13730].value" value="11565"  class="selection question_radio_13730"  />		<label for="13730_2">3-5个</label>
	</li>
	<li>
			<input group="13730" type="radio" id="13730_3" name="answers[13730].value" value="11566"  class="selection question_radio_13730"  />		<label for="13730_3">5-10个</label>
	</li>
	<li>
			<input group="13730" type="radio" id="13730_4" name="answers[13730].value" value="11567"  class="selection question_radio_13730"  />		<label for="13730_4">多于10个</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13730  qc_0 radio" type="radio" name="answers[13730].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3021" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						“当我在决定买哪个化妆品品牌时，价格对我来说很重要。” 你同意这种说法吗？请打分。
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<span class="error-content" id="err_answers[13731].value" ></span>
<input type="hidden" name="answers[13731].id" value="" id="answers[13731].id" />
<table>
<tr>

<td>

<div class="left-label">不同意</div>
	<table class="rating-table">
		<tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[13731].value" value="1" id="13731_1" group="13731" class="question_radio_13731 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13731].value" value="2" id="13731_2" group="13731" class="question_radio_13731 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13731].value" value="3" id="13731_3" group="13731" class="question_radio_13731 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" >
<input type="radio" name="answers[13731].value" value="4" id="13731_4" group="13731" class="question_radio_13731 rating" style="background-color: #ffffff" />
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[13731].value" value="5" id="13731_5" group="13731" class="question_radio_13731 rating" style="background-color: #ffffff" />
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</table> <div class="right-label">很同意</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[13731].value" value="" id="answers[13731].value" class="q_13731 qc_0 radio" />
</td>
</tr>
</table>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3033" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						上个月，你在美容/护发/护肤论坛或博客上发了多少贴？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13732].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13732].id" value="" id="answers[13732].id" />
<ul>
	<li>
			<input group="13732" type="radio" id="13732_0" name="answers[13732].value" value="11701"  class="selection question_radio_13732"  />		<label for="13732_0">0</label>
	</li>
	<li>
			<input group="13732" type="radio" id="13732_1" name="answers[13732].value" value="11702"  class="selection question_radio_13732"  />		<label for="13732_1">1~10</label>
	</li>
	<li>
			<input group="13732" type="radio" id="13732_2" name="answers[13732].value" value="11703"  class="selection question_radio_13732"  />		<label for="13732_2">11~15</label>
	</li>
	<li>
			<input group="13732" type="radio" id="13732_3" name="answers[13732].value" value="11704"  class="selection question_radio_13732"  />		<label for="13732_3">16~20</label>
	</li>
	<li>
			<input group="13732" type="radio" id="13732_4" name="answers[13732].value" value="11705"  class="selection question_radio_13732"  />		<label for="13732_4">20~30</label>
	</li>
	<li>
			<input group="13732" type="radio" id="13732_5" name="answers[13732].value" value="11706"  class="selection question_radio_13732"  />		<label for="13732_5">30+</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13732  qc_0 radio" type="radio" name="answers[13732].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3024" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你经常逛哪些美容/护发/护肤论坛或博客？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13733].id" value="" id="answers[13733].id" />
<input type="text" name="answers[13733].value" value="" id="question_13733" group="13733" class="input-text" />

<span class="error-content" id="err_answers[13733].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3025" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你用微博吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13734].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13734].id" value="" id="answers[13734].id" />
<ul>
	<li>
			<input group="13734" type="radio" id="13734_0" name="answers[13734].value" value="11580"  class="selection question_radio_13734"  />		<label for="13734_0">我不用</label>
	</li>
	<li>
			<input group="13734" type="radio" id="13734_1" name="answers[13734].value" value="11581"  class="selection question_radio_13734"  />		<label for="13734_1">用，但我不想公开域名</label>
	</li>
	<li>
			<input group="13734" type="radio" id="13734_2" name="answers[13734].value" value="11582"  class="selection question_radio_13734"  />		<label for="13734_2">用，我的微博域名是：</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13734  qc_0 radio" type="radio" name="answers[13734].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3026" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						微博地址：
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13735].id" value="" id="answers[13735].id" />
<input type="text" name="answers[13735].value" value="" id="question_13735" group="13735" class="input-text" />

<span class="error-content" id="err_answers[13735].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3027" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的月收入
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13736].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13736].id" value="" id="answers[13736].id" />
<ul>
	<li>
			<input group="13736" type="radio" id="13736_0" name="answers[13736].value" value="11583"  class="selection question_radio_13736"  />		<label for="13736_0">低于3,000元/月</label>
	</li>
	<li>
			<input group="13736" type="radio" id="13736_1" name="answers[13736].value" value="11584"  class="selection question_radio_13736"  />		<label for="13736_1">￥3,000～5,000元/月</label>
	</li>
	<li>
			<input group="13736" type="radio" id="13736_2" name="answers[13736].value" value="11585"  class="selection question_radio_13736"  />		<label for="13736_2">￥5,000～7,000元/月</label>
	</li>
	<li>
			<input group="13736" type="radio" id="13736_3" name="answers[13736].value" value="11586"  class="selection question_radio_13736"  />		<label for="13736_3">￥7,000～10,000元/月</label>
	</li>
	<li>
			<input group="13736" type="radio" id="13736_4" name="answers[13736].value" value="11587"  class="selection question_radio_13736"  />		<label for="13736_4">￥10,000～15,000元/月</label>
	</li>
	<li>
			<input group="13736" type="radio" id="13736_5" name="answers[13736].value" value="11588"  class="selection question_radio_13736"  />		<label for="13736_5">高于￥15,000元/月</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13736  qc_0 radio" type="radio" name="answers[13736].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3034" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的最高学历:
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13737].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13737].id" value="" id="answers[13737].id" />

	<select group="13737" class="selection" id="question_13737" name="answers[13737].value" title="title"  size = "1" >
	<option selected="selected" value="0">请选择</option>
<option value="11707" style=""  >博士</option>
<option value="11708" style=""  >研究生</option>
<option value="11709" style=""  >本科</option>
<option value="11710" style=""  >专科</option>
<option value="11711" style=""  >高中</option>
<option value="11712" style=""  >初中</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3028" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的性别：
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13738].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13738].id" value="" id="answers[13738].id" />
<ul>
	<li>
			<input group="13738" type="radio" id="13738_0" name="answers[13738].value" value="11589"  class="selection question_radio_13738"  />		<label for="13738_0">男性</label>
	</li>
	<li>
			<input group="13738" type="radio" id="13738_1" name="answers[13738].value" value="11590"  class="selection question_radio_13738"  />		<label for="13738_1">女性</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_13738  qc_0 radio" type="radio" name="answers[13738].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3029" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你目前的居住地：
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13739].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13739].id" value="" id="answers[13739].id" />

	<select group="13739" class="selection" id="question_13739" name="answers[13739].value" title="title"  size = "1" >
	<option selected="selected" value="0">请选择</option>
<option value="11597" style=""  >北京市</option>
<option value="11647" style=""  >上海市</option>
<option value="11612" style=""  >广州市</option>
<option value="11594" style=""  >包头市</option>
<option value="11595" style=""  >宝鸡市</option>
<option value="11596" style=""  >保定市</option>
<option value="11591" style=""  >武汉市</option>
<option value="11598" style=""  >沧州市</option>
<option value="11599" style=""  >长春市</option>
<option value="11600" style=""  >长沙市</option>
<option value="11601" style=""  >常州市</option>
<option value="11602" style=""  >郴州市</option>
<option value="11603" style=""  >成都市</option>
<option value="11604" style=""  >大理市</option>
<option value="11605" style=""  >大连市</option>
<option value="11606" style=""  >大庆市</option>
<option value="11607" style=""  >大同市</option>
<option value="11608" style=""  >东莞市</option>
<option value="11609" style=""  >佛山市</option>
<option value="11610" style=""  >福州市</option>
<option value="11611" style=""  >抚顺市</option>
<option value="11593" style=""  >蚌埠市</option>
<option value="11613" style=""  >贵阳市</option>
<option value="11614" style=""  >桂林市</option>
<option value="11615" style=""  >哈尔滨市</option>
<option value="11616" style=""  >海口市</option>
<option value="11617" style=""  >杭州市</option>
<option value="11618" style=""  >合肥市</option>
<option value="11619" style=""  >衡阳市</option>
<option value="11620" style=""  >呼和浩特市</option>
<option value="11621" style=""  >惠州市</option>
<option value="11622" style=""  >吉林市</option>
<option value="11623" style=""  >济南市</option>
<option value="11624" style=""  >嘉兴市</option>
<option value="11625" style=""  >江门市</option>
<option value="11626" style=""  >九江市</option>
<option value="11627" style=""  >开封市</option>
<option value="11628" style=""  >昆明市</option>
<option value="11629" style=""  >兰州市</option>
<option value="11630" style=""  >廊坊市</option>
<option value="11631" style=""  >连云港市</option>
<option value="11632" style=""  >洛阳市</option>
<option value="11633" style=""  >马安山市</option>
<option value="11634" style=""  >牡丹江市</option>
<option value="11635" style=""  >南昌市</option>
<option value="11636" style=""  >南京市</option>
<option value="11637" style=""  >南宁市</option>
<option value="11638" style=""  >南通市</option>
<option value="11639" style=""  >宁波市</option>
<option value="11640" style=""  >攀枝花市</option>
<option value="11641" style=""  >平顶山市</option>
<option value="11642" style=""  >齐齐哈尔</option>
<option value="11643" style=""  >秦皇岛市</option>
<option value="11644" style=""  >青岛市</option>
<option value="11645" style=""  >泉州市</option>
<option value="11646" style=""  >汕头市</option>
<option value="11592" style=""  >鞍山市</option>
<option value="11648" style=""  >绍兴市</option>
<option value="11649" style=""  >深圳市</option>
<option value="11650" style=""  >沈阳市</option>
<option value="11651" style=""  >石家庄市</option>
<option value="11652" style=""  >苏州市</option>
<option value="11653" style=""  >太原市</option>
<option value="11654" style=""  >泰州市</option>
<option value="11655" style=""  >唐山市</option>
<option value="11656" style=""  >天津市</option>
<option value="11657" style=""  >威海市</option>
<option value="11658" style=""  >潍坊市</option>
<option value="11659" style=""  >温州市</option>
<option value="11660" style=""  >乌鲁木齐市</option>
<option value="11661" style=""  >无锡市</option>
<option value="11662" style=""  >芜湖市</option>
<option value="11663" style=""  >西安市</option>
<option value="11664" style=""  >西宁市</option>
<option value="11665" style=""  >厦门市</option>
<option value="11666" style=""  >新乡市</option>
<option value="11667" style=""  >徐州市</option>
<option value="11668" style=""  >烟台市</option>
<option value="11669" style=""  >延安市</option>
<option value="11670" style=""  >扬州市</option>
<option value="11671" style=""  >宜宾市</option>
<option value="11672" style=""  >银川市</option>
<option value="11673" style=""  >玉林市</option>
<option value="11674" style=""  >玉溪市</option>
<option value="11675" style=""  >湛江市</option>
<option value="11676" style=""  >漳州市</option>
<option value="11677" style=""  >镇江市</option>
<option value="11678" style=""  >郑州市</option>
<option value="11679" style=""  >中山市</option>
<option value="11680" style=""  >重庆市</option>
<option value="11681" style=""  >珠海市</option>
<option value="11682" style=""  >淄博市</option>
<option value="11683" style=""  >自贡市</option>
<option value="11684" style=""  >遵义市</option>
<option value="11685" style=""  >其他</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2957" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你的出生年份?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[13740].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[13740].id" value="" id="answers[13740].id" />

	<select group="13740" class="selection" id="question_13740" name="answers[13740].value" title="title"  size = "1" >
	<option selected="selected" value="0">请选择</option>
<option value="11222" style=""  >1960以前</option>
<option value="11223" style=""  >1961</option>
<option value="11224" style=""  >1962</option>
<option value="11225" style=""  >1963</option>
<option value="11226" style=""  >1964</option>
<option value="11227" style=""  >1965</option>
<option value="11228" style=""  >1966</option>
<option value="11229" style=""  >1967</option>
<option value="11230" style=""  >1968</option>
<option value="11231" style=""  >1969</option>
<option value="11232" style=""  >1970</option>
<option value="11233" style=""  >1971</option>
<option value="11234" style=""  >1972</option>
<option value="11235" style=""  >1973</option>
<option value="11236" style=""  >1974</option>
<option value="11237" style=""  >1975</option>
<option value="11238" style=""  >1976</option>
<option value="11239" style=""  >1977</option>
<option value="11240" style=""  >1978</option>
<option value="11241" style=""  >1979</option>
<option value="11242" style=""  >1980</option>
<option value="11243" style=""  >1981</option>
<option value="11244" style=""  >1982</option>
<option value="11245" style=""  >1983</option>
<option value="11246" style=""  >1984</option>
<option value="11247" style=""  >1985</option>
<option value="11248" style=""  >1986</option>
<option value="11249" style=""  >1987</option>
<option value="11250" style=""  >1988</option>
<option value="11251" style=""  >1989</option>
<option value="11252" style=""  >1990</option>
<option value="11253" style=""  >1991</option>
<option value="11254" style=""  >1992</option>
<option value="11255" style=""  >1993</option>
<option value="11256" style=""  >1994</option>
<option value="11257" style=""  >1995</option>
<option value="11258" style=""  >1995以后</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2088" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						姓名:
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13741].id" value="" id="answers[13741].id" />
<input type="text" name="answers[13741].value" value="" id="question_13741" group="13741" class="input-text" />

<span class="error-content" id="err_answers[13741].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2090" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						电子邮箱:
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13742].id" value="" id="answers[13742].id" />
<input type="text" name="answers[13742].value" value="" id="question_13742" group="13742" class="input-text" />

<span class="error-content" id="err_answers[13742].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2089" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						电话:
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[13743].id" value="" id="answers[13743].id" />
<input type="text" name="answers[13743].value" value="" id="question_13743" group="13743" class="input-text" />

<span class="error-content" id="err_answers[13743].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="提交" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
	        jQuery("#check-alert-dialog .content").html(html);
	        jQuery("#check-alert-dialog").dialog('open');	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '提交失败：不能提交空报告';
		    jQuery("#check-alert-dialog .content").html(html);
		    jQuery("#check-alert-dialog").dialog('open');
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[


	 Element.hide("q_3026");


var myrules = {
	   
	   "input#13734_1": function(el){
			el.onclick = function(){
				if ($("13734_1").checked){
						Element.hide($("q_3026"));
				}
			}
		}
	,
	   
	   "input#13734_2": function(el){
			el.onclick = function(){
				if ($("13734_2").checked){
						Element.show($("q_3026"));
				}
			}
		}
	,
	   
	   "input#13734_0": function(el){
			el.onclick = function(){
				if ($("13734_0").checked){
						Element.hide($("q_3026"));
				}
			}
		}
}

Behaviour.register(myrules);

// ]]>
-->
</script>
