	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/742" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />
<input type="hidden" name="surveyId" value="Iq9BeiMQjdCU"/>

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3092" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你刷牙的频率是什么？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14043].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14043].id" value="" id="answers[14043].id" />
<ul>
	<li>
			<input group="14043" type="radio" id="14043_0" name="answers[14043].value" value="11912"  class="selection question_radio_14043"  />		<label for="14043_0">少于一天一次</label>
	</li>
	<li>
			<input group="14043" type="radio" id="14043_1" name="answers[14043].value" value="11913"  class="selection question_radio_14043"  />		<label for="14043_1">一天一次</label>
	</li>
	<li>
			<input group="14043" type="radio" id="14043_2" name="answers[14043].value" value="11914"  class="selection question_radio_14043"  />		<label for="14043_2">一天两次</label>
	</li>
	<li>
			<input group="14043" type="radio" id="14043_3" name="answers[14043].value" value="11915"  class="selection question_radio_14043"  />		<label for="14043_3">一天三次</label>
	</li>
	<li>
			<input group="14043" type="radio" id="14043_4" name="answers[14043].value" value="11916"  class="selection question_radio_14043"  />		<label for="14043_4">一天超过三次</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14043  qc_0 radio" type="radio" name="answers[14043].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3093" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你使用下列哪种牙刷？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14044].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14044].id" value="" id="answers[14044].id" />
<ul>
	<li>
			<input group="14044" type="radio" id="14044_0" name="answers[14044].value" value="11917"  class="selection question_radio_14044"  onclick="showOrHide()" />		<label for="14044_0">一般的牙刷</label>
	</li>
	<li>
			<input group="14044" type="radio" id="14044_1" name="answers[14044].value" value="11918"  class="selection question_radio_14044"   onclick="showOrHide()"/>		<label for="14044_1">电动牙刷</label>
	</li>
	<li>
			<input group="14044" type="radio" id="14044_2" name="answers[14044].value" value="11919"  class="selection question_radio_14044"   onclick="showOrHide()"/>		<label for="14044_2">声波牙刷</label>
	</li>
	<li>
			<input group="14044" type="radio" id="14044_3" name="answers[14044].value" value="11920"  class="selection question_radio_14044"   onclick="showOrHide()" />		<label for="14044_3">其他（请详述）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14044  qc_0 radio" type="radio" name="answers[14044].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide(){
		if(document.getElementById("14044_0").checked){
			document.getElementById("q_3098").style.display ="";
			document.getElementById("q_3094").style.display ="none"
			document.getElementById("q_3095").style.display ="none"
		}
		if(document.getElementById("14044_1").checked){
			document.getElementById("q_3095").style.display ="";
			document.getElementById("q_3094").style.display ="none"
			document.getElementById("q_3098").style.display ="none"
		}
		if(document.getElementById("14044_3").checked){
			document.getElementById("q_3094").style.display ="";
			document.getElementById("q_3095").style.display ="none"
			document.getElementById("q_3098").style.display ="none"
		}
}
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3094" style="margin-bottom:0px; display:none" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他牙刷
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14045].id" value="" id="answers[14045].id" />
<input type="text" name="answers[14045].value" value="" id="question_14045" group="14045" class="input-text" />

<span class="error-content" id="err_answers[14045].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3095" style="margin-bottom:0px;display:none" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你使用哪个品牌的电动牙刷？
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14046].id" value="" id="answers[14046].id" />
<input type="text" name="answers[14046].value" value="" id="question_14046" group="14046" class="input-text" />

<span class="error-content" id="err_answers[14046].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3096" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你刷牙的目的是什么？（多选）
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14047].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14047].id" value="" id="answers[14047].id" />




<span id="hint_14047">
</span>
<ul>
	<li>
			<input group="14047" class="question_radio_14047 selection" type="checkbox" id="14047_0" name="answers[14047].value" value="11921" 	onclick=" "/>		<label for="14047_0">预防蛀牙</label>
	</li>
	<li>
			<input group="14047" class="question_radio_14047 selection" type="checkbox" id="14047_1" name="answers[14047].value" value="11922" 	onclick=" "/>		<label for="14047_1">感觉更清新</label>
	</li>
	<li>
			<input group="14047" class="question_radio_14047 selection" type="checkbox" id="14047_2" name="answers[14047].value" value="11923" 	onclick=" "/>		<label for="14047_2">预防口臭</label>
	</li>
	<li>
			<input group="14047" class="question_radio_14047 selection" type="checkbox" id="14047_3" name="answers[14047].value" value="11924" 	onclick=" "/>		<label for="14047_3">防止牙菌斑</label>
	</li>
	<li>
			<input group="14047" class="question_radio_14047 selection" type="checkbox" id="14047_4" name="answers[14047].value" value="11925" 	onclick=" "/>		<label for="14047_4">让牙齿更漂亮</label>
	</li>
	<li>
			<input group="14047" class="question_radio_14047 selection" type="checkbox" id="14047_5" name="answers[14047].value" value="11926" 	onclick=" "/>		<label for="14047_5">保证牙龈健康</label>
	</li>
	<li>
			<input group="14047" class="question_radio_14047 selection" type="checkbox" id="14047_6" name="answers[14047].value" value="11927" 	onclick="showOrHide2() "/>		<label for="14047_6">其他（请详述）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide2(){

	if(document.getElementById("14047_6").checked){
		document.getElementById("q_3097").style.display="";
	}else{
		document.getElementById("q_3097").style.display="none";
	}
		
	
}
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3097" style="margin-bottom:0px;display:none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他目的
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14048].id" value="" id="answers[14048].id" />
<input type="text" name="answers[14048].value" value="" id="question_14048" group="14048" class="input-text" />

<span class="error-content" id="err_answers[14048].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3098" style="margin-bottom:0px;display:none" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你有考虑过购买电动/声波牙刷吗？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14049].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14049].id" value="" id="answers[14049].id" />
<ul>
	<li>
			<input group="14049" type="radio" id="14049_0" name="answers[14049].value" value="11928"  class="selection question_radio_14049" onclick="showOrHide1()" />		<label for="14049_0">没有考虑过</label>
	</li>
	<li>
			<input group="14049" type="radio" id="14049_1" name="answers[14049].value" value="11929"  class="selection question_radio_14049" onclick="showOrHide1()" />		<label for="14049_1">是的，我考虑过</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14049  qc_0 radio" type="radio" name="answers[14049].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
function showOrHide1(){
	
	if(document.getElementById("14049_1").checked){
		document.getElementById("q_3099").style.display="";
	}else{
		document.getElementById("q_3099").style.display="none";
	}
	
}
</script>
		  <div id="q_3099" style="margin-bottom:0px;display:none" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你为什么最终没有购买？（多选）
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14050].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14050].id" value="" id="answers[14050].id" />




<span id="hint_14050">
</span>
<ul>
	<li>
			<input group="14050" class="question_radio_14050 selection" type="checkbox" id="14050_0" name="answers[14050].value" value="11930" 	onclick=" "/>		<label for="14050_0">价格太贵了</label>
	</li>
	<li>
			<input group="14050" class="question_radio_14050 selection" type="checkbox" id="14050_1" name="answers[14050].value" value="11931" 	onclick=" "/>		<label for="14050_1">我觉得没有一般的牙刷好</label>
	</li>
	<li>
			<input group="14050" class="question_radio_14050 selection" type="checkbox" id="14050_2" name="answers[14050].value" value="11932" 	onclick=" "/>		<label for="14050_2">充电和换刷头太麻烦了</label>
	</li>
	<li>
			<input group="14050" class="question_radio_14050 selection" type="checkbox" id="14050_3" name="answers[14050].value" value="11933" 	onclick=" "/>		<label for="14050_3">我希望购买之前有一个尝试的机会</label>
	</li>
	<li>
			<input group="14050" class="question_radio_14050 selection" type="checkbox" id="14050_4" name="answers[14050].value" value="11934" 	onclick=" "/>		<label for="14050_4">用这个太费电了</label>
	</li>
	<li>
			<input group="14050" class="question_radio_14050 selection" type="checkbox" id="14050_5" name="answers[14050].value" value="11935" 	onclick=" "/>		<label for="14050_5">很难习惯使用电动牙刷</label>
	</li>
	<li>
			<input group="14050" class="question_radio_14050 selection" type="checkbox" id="14050_6" name="answers[14050].value" value="11936" 	onclick=" "/>		<label for="14050_6">更换刷头太贵了</label>
	</li>
	<li>
			<input group="14050" class="question_radio_14050 selection" type="checkbox" id="14050_7" name="answers[14050].value" value="11937" 	onclick="showOrHide3() "/>		<label for="14050_7">其他（请详述）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide3(){
	if(document.getElementById("14050_7").checked){
		document.getElementById("q_2832").style.display=""
	}else{
		document.getElementById("q_2832").style.display="none";
	}
}
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2832" style="margin-bottom:0px;display:none" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他原因
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14051].id" value="" id="answers[14051].id" />
<input type="text" name="answers[14051].value" value="" id="question_14051" group="14051" class="input-text" />

<span class="error-content" id="err_answers[14051].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3100" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你多长时间看一次牙医？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14052].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14052].id" value="" id="answers[14052].id" />
<ul>
	<li>
			<input group="14052" type="radio" id="14052_0" name="answers[14052].value" value="11938"  class="selection question_radio_14052"  />		<label for="14052_0">只在牙齿有问题的时候</label>
	</li>
	<li>
			<input group="14052" type="radio" id="14052_1" name="answers[14052].value" value="11939"  class="selection question_radio_14052"  />		<label for="14052_1">少于一年一次</label>
	</li>
	<li>
			<input group="14052" type="radio" id="14052_2" name="answers[14052].value" value="11940"  class="selection question_radio_14052"  />		<label for="14052_2">一年一次</label>
	</li>
	<li>
			<input group="14052" type="radio" id="14052_3" name="answers[14052].value" value="11941"  class="selection question_radio_14052"  />		<label for="14052_3">一年两次</label>
	</li>
	<li>
			<input group="14052" type="radio" id="14052_4" name="answers[14052].value" value="11942"  class="selection question_radio_14052"  />		<label for="14052_4">一年超过两次</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14052  qc_0 radio" type="radio" name="answers[14052].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3101" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你使用牙线吗？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14053].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14053].id" value="" id="answers[14053].id" />
<ul>
	<li>
			<input group="14053" type="radio" id="14053_0" name="answers[14053].value" value="11943"  class="selection question_radio_14053"  />		<label for="14053_0">是的，天天用</label>
	</li>
	<li>
			<input group="14053" type="radio" id="14053_1" name="answers[14053].value" value="11944"  class="selection question_radio_14053"  />		<label for="14053_1">是的，一周使用多次</label>
	</li>
	<li>
			<input group="14053" type="radio" id="14053_2" name="answers[14053].value" value="11945"  class="selection question_radio_14053"  />		<label for="14053_2">是的，一个星期一次</label>
	</li>
	<li>
			<input group="14053" type="radio" id="14053_3" name="answers[14053].value" value="11946"  class="selection question_radio_14053"  />		<label for="14053_3">是的，一个月一次</label>
	</li>
	<li>
			<input group="14053" type="radio" id="14053_4" name="answers[14053].value" value="11947"  class="selection question_radio_14053"  />		<label for="14053_4">是的，但不到一月一次</label>
	</li>
	<li>
			<input group="14053" type="radio" id="14053_5" name="answers[14053].value" value="11948"  class="selection question_radio_14053"  />		<label for="14053_5">没有用过</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14053  qc_0 radio" type="radio" name="answers[14053].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3102" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你之前听说过哪个牌子的电动牙刷？
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14054].id" value="" id="answers[14054].id" />
<input type="text" name="answers[14054].value" value="" id="question_14054" group="14054" class="input-text" />

<span class="error-content" id="err_answers[14054].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3103" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在今天之前，你有听说过“飞利浦声波牙刷”吗？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14055].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14055].id" value="" id="answers[14055].id" />
<ul>
	<li>
			<input group="14055" type="radio" id="14055_0" name="answers[14055].value" value="11949"  class="selection question_radio_14055" onclick="showOrHide4()" />		<label for="14055_0">是</label>
	</li>
	<li>
			<input group="14055" type="radio" id="14055_1" name="answers[14055].value" value="11950"  class="selection question_radio_14055" onclick="showOrHide4()" />		<label for="14055_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14055  qc_0 radio" type="radio" name="answers[14055].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
function showOrHide4(){
	if(document.getElementById("14055_0").checked){
		document.getElementById("q_3104").style.display="";
	}else{
		document.getElementById("q_3104").style.display="none";
	}
}
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3104" style="margin-bottom:0px;display:none" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你在哪里听到这个品牌的？ (多选）
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14056].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14056].id" value="" id="answers[14056].id" />




<span id="hint_14056">
</span>
<ul>
	<li>
			<input group="14056" class="question_radio_14056 selection" type="checkbox" id="14056_0" name="answers[14056].value" value="11951" 	onclick=" "/>		<label for="14056_0">户外广告</label>
	</li>
	<li>
			<input group="14056" class="question_radio_14056 selection" type="checkbox" id="14056_1" name="answers[14056].value" value="11952" 	onclick=" "/>		<label for="14056_1">电视广告</label>
	</li>
	<li>
			<input group="14056" class="question_radio_14056 selection" type="checkbox" id="14056_2" name="answers[14056].value" value="11953" 	onclick=" "/>		<label for="14056_2">杂志广告</label>
	</li>
	<li>
			<input group="14056" class="question_radio_14056 selection" type="checkbox" id="14056_3" name="answers[14056].value" value="11954" 	onclick=" "/>		<label for="14056_3">在线网络广告</label>
	</li>
	<li>
			<input group="14056" class="question_radio_14056 selection" type="checkbox" id="14056_4" name="answers[14056].value" value="11955" 	onclick=" "/>		<label for="14056_4">朋友的推荐</label>
	</li>
	<li>
			<input group="14056" class="question_radio_14056 selection" type="checkbox" id="14056_5" name="answers[14056].value" value="11956" 	onclick=" "/>		<label for="14056_5">牙医的推荐</label>
	</li>
	<li>
			<input group="14056" class="question_radio_14056 selection" type="checkbox" id="14056_6" name="answers[14056].value" value="11957" 	onclick=" showOrHide5()"/>		<label for="14056_6">其他（请详述）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
function showOrHide5(){

	if(document.getElementById("14056_6").checked){
		document.getElementById("q_2776").style.display="";
	}else{
		document.getElementById("q_2776").style.display="none";
	}
	
}
</script>
		  <div id="q_2776" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						其他途径
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14057].id" value="" id="answers[14057].id" />
<input type="text" name="answers[14057].value" value="" id="question_14057" group="14057" class="input-text" />

<span class="error-content" id="err_answers[14057].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3105" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请告诉我们你觉得这款牙刷和其他电动牙刷的区别？
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14058].id" value="" id="answers[14058].id" />
<input type="text" name="answers[14058].value" value="" id="question_14058" group="14058" class="input-text" />

<span class="error-content" id="err_answers[14058].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3106" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你愿意支付458元购买一个飞利浦声波牙刷吗？
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14059].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14059].id" value="" id="answers[14059].id" />
<ul>
	<li>
			<input group="14059" type="radio" id="14059_0" name="answers[14059].value" value="11958"  class="selection question_radio_14059" onclick="showOrHide6()" />		<label for="14059_0">否</label>
	</li>
	<li>
			<input group="14059" type="radio" id="14059_1" name="answers[14059].value" value="11959"  class="selection question_radio_14059" onclick="showOrHide6()" />		<label for="14059_1">如果可以事先尝试一下，我会考虑</label>
	</li>
	<li>
			<input group="14059" type="radio" id="14059_2" name="answers[14059].value" value="11960"  class="selection question_radio_14059" onclick="showOrHide6()" />		<label for="14059_2">是</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14059  qc_0 radio" type="radio" name="answers[14059].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
function showOrHide6(){

	if(document.getElementById("14059_0").checked){
		document.getElementById("q_3107").style.display="";
	}else{
		document.getElementById("q_3107").style.display="none";
	}
}
</script>
		  <div id="q_3107" style="margin-bottom:0px; display:none" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你能接受的价格是多少？
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14060].id" value="" id="answers[14060].id" />
<input type="text" name="answers[14060].value" value="" id="question_14060" group="14060" class="input-text" />

<span class="error-content" id="err_answers[14060].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2088" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						姓名:
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14061].id" value="" id="answers[14061].id" />
<input type="text" name="answers[14061].value" value="" id="question_14061" group="14061" class="input-text" />

<span class="error-content" id="err_answers[14061].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3108" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						性别:
					</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14062].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14062].id" value="" id="answers[14062].id" />
<ul>
	<li>
			<input group="14062" type="radio" id="14062_0" name="answers[14062].value" value="11961"  class="selection question_radio_14062"  />		<label for="14062_0">男</label>
	</li>
	<li>
			<input group="14062" type="radio" id="14062_1" name="answers[14062].value" value="11962"  class="selection question_radio_14062"  />		<label for="14062_1">女</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14062  qc_0 radio" type="radio" name="answers[14062].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2784" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						年龄:
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14063].id" value="" id="answers[14063].id" />
<input type="text" name="answers[14063].value" value="" id="question_14063" group="14063" class="input-text" />

<span class="error-content" id="err_answers[14063].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2090" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						电子邮箱:
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14064].id" value="" id="answers[14064].id" />
<input type="text" name="answers[14064].value" value="" id="question_14064" group="14064" class="input-text" />

<span class="error-content" id="err_answers[14064].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2089" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						电话:
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14065].id" value="" id="answers[14065].id" />
<input type="text" name="answers[14065].value" value="" id="question_14065" group="14065" class="input-text" />

<span class="error-content" id="err_answers[14065].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3109" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						住址:
					</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14066].id" value="" id="answers[14066].id" />
<input type="text" name="answers[14066].value" value="" id="question_14066" group="14066" class="input-text" />

<span class="error-content" id="err_answers[14066].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="提交" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
	        jQuery("#check-alert-dialog .content").html(html);
	        jQuery("#check-alert-dialog").dialog('open');
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '提交失败：不能提交空报告';
		    jQuery("#check-alert-dialog .content").html(html);
		    jQuery("#check-alert-dialog").dialog('open');
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

// ]]>
-->
</script>
