	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/748" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="TMwq2mEKGDXK" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />

<div class="mandatory"><span style="color: red;">* </span>- It is mandatory</div>
<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle"/>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3138" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你一般进行哪些体育运动或者活动呢？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14147].id" value="" id="answers[14147].id" />
<textarea name="answers[14147].value" id="question_14147" cols="40" group="14147" rows="2" class="input-text" ></textarea>
<span class="error-content" id="err_answers[14147].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3139" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						一年中，你花在运动装备（服装、器材）上的费用大约是多少？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14148].id" value="" id="answers[14148].id" />
<input type="text" name="answers[14148].value" value="" id="question_14148" group="14148" class="input-text" />

<span class="error-content" id="err_answers[14148].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3140" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你平时在网上讨论运动装备吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14149].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14149].id" value="" id="answers[14149].id" />
<ul>
	<li>
			<input group="14149" type="radio" id="14149_0" name="answers[14149].value" value="12067"  class="selection question_radio_14149"  />		<label for="14149_0">是</label>
	</li>
	<li>
			<input group="14149" type="radio" id="14149_1" name="answers[14149].value" value="12068"  class="selection question_radio_14149"  />		<label for="14149_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14149  qc_0 radio" type="radio" name="answers[14149].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3141" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						通常你会选择在哪个网站或者论坛讨论运动装备?
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14150].id" value="" id="answers[14150].id" />
<textarea name="answers[14150].value" id="question_14150" cols="40" group="14150" rows="2" class="input-text" ></textarea>
<span class="error-content" id="err_answers[14150].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3142" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						过去的一年，你有买过运动装备吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14151].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14151].id" value="" id="answers[14151].id" />
<ul>
	<li>
			<input group="14151" type="radio" id="14151_0" name="answers[14151].value" value="12069"  class="selection question_radio_14151"  />		<label for="14151_0">是</label>
	</li>
	<li>
			<input group="14151" type="radio" id="14151_1" name="answers[14151].value" value="12070"  class="selection question_radio_14151"  />		<label for="14151_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14151  qc_0 radio" type="radio" name="answers[14151].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3143" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你买了些什么呢？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14152].id" value="" id="answers[14152].id" />
<input type="text" name="answers[14152].value" value="" id="question_14152" group="14152" class="input-text" />

<span class="error-content" id="err_answers[14152].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3144" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						请问你是在哪里买的？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14153].id" value="" id="answers[14153].id" />
<input type="text" name="answers[14153].value" value="" id="question_14153" group="14153" class="input-text" />

<span class="error-content" id="err_answers[14153].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3145" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						在过去的一年，请问你的朋友们有买过运动装备吗？在哪些地方买的呢？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14154].id" value="" id="answers[14154].id" />
<textarea name="answers[14154].value" id="question_14154" cols="40" group="14154" rows="2" class="input-text" ></textarea>
<span class="error-content" id="err_answers[14154].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3146" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你听说过迪卡侬（Decathlon）吗？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14155].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14155].id" value="" id="answers[14155].id" />
<ul>
	<li>
			<input group="14155" type="radio" id="14155_0" name="answers[14155].value" value="12071"  class="selection question_radio_14155"  />		<label for="14155_0">听说过</label>
	</li>
	<li>
			<input group="14155" type="radio" id="14155_1" name="answers[14155].value" value="12072"  class="selection question_radio_14155"  />		<label for="14155_1">没听说过</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14155  qc_0 radio" type="radio" name="answers[14155].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3147" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你是从哪个渠道听说的呢？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14156].id" value="" id="answers[14156].id" />
<input type="text" name="answers[14156].value" value="" id="question_14156" group="14156" class="input-text" />

<span class="error-content" id="err_answers[14156].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3148" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你之前听说过以下哪些品牌？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14157].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14157].id" value="" id="answers[14157].id" />




<span id="hint_14157">
</span>
<ul>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_0" name="answers[14157].value" value="12073" 	onclick=" "/>		<label for="14157_0">newfeel</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_1" name="answers[14157].value" value="12074" 	onclick=" "/>		<label for="14157_1">nike</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_2" name="answers[14157].value" value="12075" 	onclick=" "/>		<label for="14157_2">simond</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_3" name="answers[14157].value" value="12076" 	onclick=" "/>		<label for="14157_3">nabaiji</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_4" name="answers[14157].value" value="12077" 	onclick=" "/>		<label for="14157_4">kalenji</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_5" name="answers[14157].value" value="12078" 	onclick=" "/>		<label for="14157_5">inesis</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_6" name="answers[14157].value" value="12079" 	onclick=" "/>		<label for="14157_6">btwin</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_7" name="answers[14157].value" value="12080" 	onclick=" "/>		<label for="14157_7">fouganza</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_8" name="answers[14157].value" value="12081" 	onclick=" "/>		<label for="14157_8">puma</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_9" name="answers[14157].value" value="12082" 	onclick=" "/>		<label for="14157_9">wed'ze</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_10" name="answers[14157].value" value="12083" 	onclick=" "/>		<label for="14157_10">decathlon</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_11" name="answers[14157].value" value="12084" 	onclick=" "/>		<label for="14157_11">adidas</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_12" name="answers[14157].value" value="12085" 	onclick=" "/>		<label for="14157_12">geonaute</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_13" name="answers[14157].value" value="12086" 	onclick=" "/>		<label for="14157_13">kipstra</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_14" name="answers[14157].value" value="12087" 	onclick=" "/>		<label for="14157_14">geologic</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_15" name="answers[14157].value" value="12088" 	onclick=" "/>		<label for="14157_15">artengo</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_16" name="answers[14157].value" value="12089" 	onclick=" "/>		<label for="14157_16">aptonia</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_17" name="answers[14157].value" value="12090" 	onclick=" "/>		<label for="14157_17">oxelo</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_18" name="answers[14157].value" value="12091" 	onclick=" "/>		<label for="14157_18">caperlan</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_19" name="answers[14157].value" value="12092" 	onclick=" "/>		<label for="14157_19">domyos</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_20" name="answers[14157].value" value="12093" 	onclick=" "/>		<label for="14157_20">northface</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_21" name="answers[14157].value" value="12094" 	onclick=" "/>		<label for="14157_21">solognac</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_22" name="answers[14157].value" value="12095" 	onclick=" "/>		<label for="14157_22">quechua</label>
	</li>
	<li>
			<input group="14157" class="question_radio_14157 selection" type="checkbox" id="14157_23" name="answers[14157].value" value="12096" 	onclick=" "/>		<label for="14157_23">tribord</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3149" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						以下哪个品牌是你最喜欢的？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14158].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14158].id" value="" id="answers[14158].id" />
<ul>
	<li>
			<input group="14158" type="radio" id="14158_0" name="answers[14158].value" value="12097"  class="selection question_radio_14158"  />		<label for="14158_0">newfeel</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_1" name="answers[14158].value" value="12098"  class="selection question_radio_14158"  />		<label for="14158_1">nike</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_2" name="answers[14158].value" value="12099"  class="selection question_radio_14158"  />		<label for="14158_2">simond</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_3" name="answers[14158].value" value="12100"  class="selection question_radio_14158"  />		<label for="14158_3">nabaiji</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_4" name="answers[14158].value" value="12101"  class="selection question_radio_14158"  />		<label for="14158_4">kalenji</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_5" name="answers[14158].value" value="12102"  class="selection question_radio_14158"  />		<label for="14158_5">inesis</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_6" name="answers[14158].value" value="12103"  class="selection question_radio_14158"  />		<label for="14158_6">btwin</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_7" name="answers[14158].value" value="12104"  class="selection question_radio_14158"  />		<label for="14158_7">fouganza</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_8" name="answers[14158].value" value="12105"  class="selection question_radio_14158"  />		<label for="14158_8">puma</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_9" name="answers[14158].value" value="12106"  class="selection question_radio_14158"  />		<label for="14158_9">wed'ze</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_10" name="answers[14158].value" value="12107"  class="selection question_radio_14158"  />		<label for="14158_10">decathlon</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_11" name="answers[14158].value" value="12108"  class="selection question_radio_14158"  />		<label for="14158_11">adidas</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_12" name="answers[14158].value" value="12109"  class="selection question_radio_14158"  />		<label for="14158_12">geonaute</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_13" name="answers[14158].value" value="12110"  class="selection question_radio_14158"  />		<label for="14158_13">kipstra</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_14" name="answers[14158].value" value="12111"  class="selection question_radio_14158"  />		<label for="14158_14">geologic</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_15" name="answers[14158].value" value="12112"  class="selection question_radio_14158"  />		<label for="14158_15">artengo</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_16" name="answers[14158].value" value="12113"  class="selection question_radio_14158"  />		<label for="14158_16">aptonia</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_17" name="answers[14158].value" value="12114"  class="selection question_radio_14158"  />		<label for="14158_17">oxelo</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_18" name="answers[14158].value" value="12115"  class="selection question_radio_14158"  />		<label for="14158_18">caperlan</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_19" name="answers[14158].value" value="12116"  class="selection question_radio_14158"  />		<label for="14158_19">domyos</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_20" name="answers[14158].value" value="12117"  class="selection question_radio_14158"  />		<label for="14158_20">northface</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_21" name="answers[14158].value" value="12118"  class="selection question_radio_14158"  />		<label for="14158_21">solognac</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_22" name="answers[14158].value" value="12119"  class="selection question_radio_14158"  />		<label for="14158_22">quechua</label>
	</li>
	<li>
			<input group="14158" type="radio" id="14158_23" name="answers[14158].value" value="12120"  class="selection question_radio_14158"  />		<label for="14158_23">tribord</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14158  qc_0 radio" type="radio" name="answers[14158].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3150" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						当你想到上述品牌时，哪三个词最先映入你脑海？
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14159].id" value="" id="answers[14159].id" />
<textarea name="answers[14159].value" id="question_14159" cols="40" group="14159" rows="2" class="input-text" ></textarea>
<span class="error-content" id="err_answers[14159].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("14160");
// ]]>
-->
</script>
		  <div id="q_3134" style="margin-bottom:0px; display:none" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						Email:
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14160].id" value="" id="answers[14160].id" />
<input type="text" name="answers[14160].value" value="null" id="question_14160" group="14160" class="input-text" />

<span class="error-content" id="err_answers[14160].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2088" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						姓名:
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14161].id" value="" id="answers[14161].id" />
<input type="text" name="answers[14161].value" value="" id="question_14161" group="14161" class="input-text" />

<span class="error-content" id="err_answers[14161].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2089" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						电话:
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14162].id" value="" id="answers[14162].id" />
<input type="text" name="answers[14162].value" value="" id="question_14162" group="14162" class="input-text" />

<span class="error-content" id="err_answers[14162].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3151" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						城市:
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14163].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14163].id" value="" id="answers[14163].id" />

	<select group="14163" class="selection" id="question_14163" name="answers[14163].value" title="title"  size = "1" >
	<option selected="selected" value="0">请选择</option>
<option value="12121" style=""  >鞍山市</option>
<option value="12122" style=""  >蚌埠市</option>
<option value="12123" style=""  >包头市</option>
<option value="12124" style=""  >宝鸡市</option>
<option value="12125" style=""  >保定市</option>
<option value="12126" style=""  >北京市</option>
<option value="12127" style=""  >沧州市</option>
<option value="12128" style=""  >长春市</option>
<option value="12129" style=""  >长沙市</option>
<option value="12130" style=""  >常州市</option>
<option value="12131" style=""  >郴州市</option>
<option value="12132" style=""  >成都市</option>
<option value="12133" style=""  >大理市</option>
<option value="12134" style=""  >大连市</option>
<option value="12135" style=""  >大庆市</option>
<option value="12136" style=""  >大同市</option>
<option value="12137" style=""  >东莞市</option>
<option value="12138" style=""  >佛山市</option>
<option value="12139" style=""  >福州市</option>
<option value="12140" style=""  >抚顺市</option>
<option value="12141" style=""  >广州市</option>
<option value="12142" style=""  >贵阳市</option>
<option value="12143" style=""  >桂林市</option>
<option value="12144" style=""  >哈尔滨市</option>
<option value="12145" style=""  >海口市</option>
<option value="12146" style=""  >杭州市</option>
<option value="12147" style=""  >合肥市</option>
<option value="12148" style=""  >衡阳市</option>
<option value="12149" style=""  >呼和浩特市</option>
<option value="12150" style=""  >惠州市</option>
<option value="12151" style=""  >吉林市</option>
<option value="12152" style=""  >济南市</option>
<option value="12153" style=""  >嘉兴市</option>
<option value="12154" style=""  >江门市</option>
<option value="12155" style=""  >九江市</option>
<option value="12156" style=""  >开封市</option>
<option value="12157" style=""  >昆明市</option>
<option value="12158" style=""  >兰州市</option>
<option value="12159" style=""  >廊坊市</option>
<option value="12160" style=""  >连云港市</option>
<option value="12161" style=""  >洛阳市</option>
<option value="12162" style=""  >马安山市</option>
<option value="12163" style=""  >牡丹江市</option>
<option value="12164" style=""  >南昌市</option>
<option value="12165" style=""  >南京市</option>
<option value="12166" style=""  >南宁市</option>
<option value="12167" style=""  >南通市</option>
<option value="12168" style=""  >宁波市</option>
<option value="12169" style=""  >攀枝花市</option>
<option value="12170" style=""  >平顶山市</option>
<option value="12171" style=""  >齐齐哈尔</option>
<option value="12172" style=""  >秦皇岛市</option>
<option value="12173" style=""  >青岛市</option>
<option value="12174" style=""  >泉州市</option>
<option value="12175" style=""  >汕头市</option>
<option value="12176" style=""  >上海市</option>
<option value="12177" style=""  >绍兴市</option>
<option value="12178" style=""  >深圳市</option>
<option value="12179" style=""  >沈阳市</option>
<option value="12180" style=""  >石家庄市</option>
<option value="12181" style=""  >苏州市</option>
<option value="12182" style=""  >太原市</option>
<option value="12183" style=""  >泰州市</option>
<option value="12184" style=""  >唐山市</option>
<option value="12185" style=""  >天津市</option>
<option value="12186" style=""  >威海市</option>
<option value="12187" style=""  >潍坊市</option>
<option value="12188" style=""  >温州市</option>
<option value="12189" style=""  >乌鲁木齐市</option>
<option value="12190" style=""  >武汉市</option>
<option value="12191" style=""  >无锡市</option>
<option value="12192" style=""  >芜湖市</option>
<option value="12193" style=""  >西安市</option>
<option value="12194" style=""  >西宁市</option>
<option value="12195" style=""  >厦门市</option>
<option value="12196" style=""  >新乡市</option>
<option value="12197" style=""  >徐州市</option>
<option value="12198" style=""  >烟台市</option>
<option value="12199" style=""  >延安市</option>
<option value="12200" style=""  >扬州市</option>
<option value="12201" style=""  >宜宾市</option>
<option value="12202" style=""  >银川市</option>
<option value="12203" style=""  >玉林市</option>
<option value="12204" style=""  >玉溪市</option>
<option value="12205" style=""  >湛江市</option>
<option value="12206" style=""  >漳州市</option>
<option value="12207" style=""  >镇江市</option>
<option value="12208" style=""  >郑州市</option>
<option value="12209" style=""  >中山市</option>
<option value="12210" style=""  >重庆市</option>
<option value="12211" style=""  >珠海市</option>
<option value="12212" style=""  >淄博市</option>
<option value="12213" style=""  >自贡市</option>
<option value="12214" style=""  >遵义市</option>
<option value="12215" style=""  >其他</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3137" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						你的家庭月收入是多少
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14164].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14164].id" value="" id="answers[14164].id" />
<ul>
	<li>
			<input group="14164" type="radio" id="14164_0" name="answers[14164].value" value="12059"  class="selection question_radio_14164"  />		<label for="14164_0">&lt;￥5,000/月</label>
	</li>
	<li>
			<input group="14164" type="radio" id="14164_1" name="answers[14164].value" value="12060"  class="selection question_radio_14164"  />		<label for="14164_1">￥5,000～10,000/月</label>
	</li>
	<li>
			<input group="14164" type="radio" id="14164_2" name="answers[14164].value" value="12061"  class="selection question_radio_14164"  />		<label for="14164_2">￥10,000～15,000/月</label>
	</li>
	<li>
			<input group="14164" type="radio" id="14164_3" name="answers[14164].value" value="12062"  class="selection question_radio_14164"  />		<label for="14164_3">￥15,000～20,000/月</label>
	</li>
	<li>
			<input group="14164" type="radio" id="14164_4" name="answers[14164].value" value="12063"  class="selection question_radio_14164"  />		<label for="14164_4">￥20,000～25,000/月</label>
	</li>
	<li>
			<input group="14164" type="radio" id="14164_5" name="answers[14164].value" value="12064"  class="selection question_radio_14164"  />		<label for="14164_5">&gt;￥25,000/月</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14164  qc_0 radio" type="radio" name="answers[14164].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2784" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						年龄:
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">
<table width="100%">
<tr>
<td>
<input type="hidden" name="answers[14165].id" value="" id="answers[14165].id" />
<input type="text" name="answers[14165].value" value="" id="question_14165" group="14165" class="input-text" />

<span class="error-content" id="err_answers[14165].value"  class="redFieldError"></span>
</td>

  </tr>
  </table>				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3108" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tr>
				<td width=50% valign="top">
					<div class="question-title">
						性别:
					</div>
							<div class="elementInfoText twoColumnLayout" >
							   
							</div>
				</td>
				<td width=50% valign="top">

<table width="100%" class="select-table">
<tr>
<td>
<span class="error-content" id="err_answers[14166].value"  class="redFieldError" style="display:block"></span>

<input type="hidden" name="answers[14166].id" value="" id="answers[14166].id" />
<ul>
	<li>
			<input group="14166" type="radio" id="14166_0" name="answers[14166].value" value="11961"  class="selection question_radio_14166"  />		<label for="14166_0">男</label>
	</li>
	<li>
			<input group="14166" type="radio" id="14166_1" name="answers[14166].value" value="11962"  class="selection question_radio_14166"  />		<label for="14166_1">女</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14166  qc_0 radio" type="radio" name="answers[14166].value" />
</td>
</tr>

  </table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br/>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button"  style="display:none"  onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" class="button" name="command.submit" value="提交" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
	        jQuery("#check-alert-dialog .content").html(html);
	        jQuery("#check-alert-dialog").dialog('open');
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '提交失败：不能提交空报告';
		    jQuery("#check-alert-dialog .content").html(html);
		    jQuery("#check-alert-dialog").dialog('open');
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[


	 Element.hide("q_3141");
	 Element.hide("q_3143");
	 Element.hide("q_3144");
	 Element.hide("q_3147");


var myrules = {
	   
	   "input#14151_1": function(el){
			el.onclick = function(){
				if ($("14151_1").checked){
						Element.hide($("q_3143"));
						Element.hide($("q_3144"));
				}
			}
		}
	,
	   
	   "input#14155_1": function(el){
			el.onclick = function(){
				if ($("14155_1").checked){
						Element.hide($("q_3147"));
				}
			}
		}
	,
	   
	   "input#14149_1": function(el){
			el.onclick = function(){
				if ($("14149_1").checked){
						Element.hide($("q_3141"));
				}
			}
		}
	,
	   
	   "input#14155_0": function(el){
			el.onclick = function(){
				if ($("14155_0").checked){
						Element.show($("q_3147"));
				}
			}
		}
	,
	   
	   "input#14149_0": function(el){
			el.onclick = function(){
				if ($("14149_0").checked){
						Element.show($("q_3141"));
				}
			}
		}
	,
	   
	   "input#14151_0": function(el){
			el.onclick = function(){
				if ($("14151_0").checked){
						Element.show($("q_3143"));
						Element.show($("q_3144"));
				}
			}
		}
}

Behaviour.register(myrules);

// ]]>
-->
</script>
