	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer" >
	<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/768" style="height:70px; width:301px" />
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content" >
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="" id="id" />
<input type="hidden" name="theme" value="wildfire" id="theme" />
<input type="hidden" name="surveyId" value="mnpbo3PXOPCP"/>

<div class="page-bar-area">
<span id="pageBar">Page:&nbsp;</span>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3253" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你是否喜欢旅游？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14442].value" style="display:block"></span>

<input type="hidden" name="answers[14442].id" value="" id="answers[14442].id">
<ul>
	<li>
			<input group="14442" type="radio" id="14442_0" name="answers[14442].value" value="12413" class="selection question_radio_14442" onclick="showOrHide()">		<label for="14442_0">是</label>
	</li>
	<li>
			<input group="14442" type="radio" id="14442_1" name="answers[14442].value" value="12414" class="selection question_radio_14442" onclick="showOrHide()">		<label for="14442_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14442  qc_0 radio" type="radio" name="answers[14442].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
function showOrHide(){

	if(document.getElementById("14442_0").checked){
		document.getElementById("q_3254").style.display="";
	}else{
		document.getElementById("q_3254").style.display="none";
	}	
}
</script>
		  <div id="q_3254" style="margin-bottom:0px;display:none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						平均多久出去旅行一次？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[14443].id" value="" id="answers[14443].id">
<input type="text" name="answers[14443].value" value="" id="question_14443" group="14443" class="input-text">

<span class="error-content" id="err_answers[14443].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3255" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						是否去过韩国：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14444].value" style="display:block"></span>

<input type="hidden" name="answers[14444].id" value="" id="answers[14444].id">
<ul>
	<li>
			<input group="14444" type="radio" id="14444_0" name="answers[14444].value" value="12415" class="selection question_radio_14444">		<label for="14444_0">是</label>
	</li>
	<li>
			<input group="14444" type="radio" id="14444_1" name="answers[14444].value" value="12416" class="selection question_radio_14444">		<label for="14444_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14444  qc_0 radio" type="radio" name="answers[14444].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
<div style="display:none;">						
						<input type="hidden" name="answers[14445].id" value="" id="answers[14445].id">
						<input type="text" name="answers[14445].value" value="" id="question_14445" group="14445" class="input-text">
						<span class="error-content" id="err_answers[14445].value"></span>
</div>
		  <div id="q_3256" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						讲到韩国，最先想到的三样是什么？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
					
					<input type="hidden" name="answers[14446].id" value="" id="answers[14446].id">
					<input type="text" name="answers[14446].value" value="" id="question_14446" group="14446" class="input-text">
					
					<span class="error-content" id="err_answers[14446].value"></span>
				</td>
			</tr>
			<tr>
				<td></td>
				<td>
					<input type="hidden" name="answers[14447].id" value="" id="answers[14447].id">
					<input type="text" name="answers[14447].value" value="" id="question_14447" group="14447" class="input-text">
					<span class="error-content" id="err_answers[14447].value"></span>
				</td>
			</tr>
			<tr>
				<td></td>
				<td>
					<input type="hidden" name="answers[14448].id" value="" id="answers[14448].id">
					<input type="text" name="answers[14448].value" value="" id="question_14448" group="14448" class="input-text">
					<span class="error-content" id="err_answers[14448].value"></span>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3245" style="margin-bottom:0px; display:none" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						1：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>

</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3246" style="margin-bottom:0px;display:none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						2：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>

</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3247" style="margin-bottom:0px;display:none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						3：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>

</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3257" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						是否会考虑去韩国旅行，为什么？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[14449].id" value="" id="answers[14449].id">
<textarea name="answers[14449].value" id="question_14449" cols="40" group="14449" rows="5" class="input-text"></textarea>
<span class="error-content" id="err_answers[14449].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3258" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						如果去韩国首尔旅行，会想去哪些地方？（可多选）
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14450].value" style="display:block"></span>

<input type="hidden" name="answers[14450].id" value="" id="answers[14450].id">




<span id="hint_14450">
</span>
<ul>
	<li>
			<input group="14450" class="question_radio_14450 selection" type="checkbox" id="14450_0" name="answers[14450].value" value="12417" onclick=" ">		<label for="14450_0">景福宫/昌德宫/昌庆宫</label>
	</li>
	<li>
			<input group="14450" class="question_radio_14450 selection" type="checkbox" id="14450_1" name="answers[14450].value" value="12418" onclick=" ">		<label for="14450_1">东大门</label>
	</li>
	<li>
			<input group="14450" class="question_radio_14450 selection" type="checkbox" id="14450_2" name="answers[14450].value" value="12419" onclick=" ">		<label for="14450_2">明洞</label>
	</li>
	<li>
			<input group="14450" class="question_radio_14450 selection" type="checkbox" id="14450_3" name="answers[14450].value" value="12420" onclick=" ">		<label for="14450_3">首尔塔&amp;泰迪熊博物馆</label>
	</li>
	<li>
			<input group="14450" class="question_radio_14450 selection" type="checkbox" id="14450_4" name="answers[14450].value" value="12421" onclick=" ">		<label for="14450_4">南山谷韩屋村</label>
	</li>
	<li>
			<input group="14450" class="question_radio_14450 selection" type="checkbox" id="14450_5" name="answers[14450].value" value="12422" onclick=" ">		<label for="14450_5">清溪川</label>
	</li>
	<li>
			<input group="14450" class="question_radio_14450 selection" type="checkbox" id="14450_6" name="answers[14450].value" value="12423" onclick=" ">		<label for="14450_6">青瓦台</label>
	</li>
	<li>
			<input group="14450" class="question_radio_14450 selection" type="checkbox" id="14450_7" name="answers[14450].value" value="12424" onclick=" ">		<label for="14450_7">仁寺洞</label>
	</li>
	<li>
			<input group="14450" class="question_radio_14450 selection" type="checkbox" id="14450_8" name="answers[14450].value" value="12425" onclick=" ">		<label for="14450_8">乐天世界</label>
	</li>
	<li>
			<input group="14450" class="question_radio_14450 selection" type="checkbox" id="14450_9" name="answers[14450].value" value="12426" onclick=" ">		<label for="14450_9">光华门</label>
	</li>
	<li>
			<input group="14450" class="question_radio_14450 selection" type="checkbox" id="14450_10" name="answers[14450].value" value="12427" onclick=" ">		<label for="14450_10">弘大/梨花女大</label>
	</li>
	<li>
			<input group="14450" class="question_radio_14450 selection" type="checkbox" id="14450_11" name="answers[14450].value" value="12428" onclick="showOrHide2() ">		<label for="14450_11">其他</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
function showOrHide2(){

	if(document.getElementById("14450_11").checked){
		document.getElementById("q_2646").style.display="";
	}else{
		document.getElementById("q_2646").style.display="none";
	}	
}
</script>
		  <div id="q_2646" style="margin-bottom:0px; display:none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						其他地方
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[14451].id" value="" id="answers[14451].id">
<input type="text" name="answers[14451].value" value="" id="question_14451" group="14451" class="input-text">

<span class="error-content" id="err_answers[14451].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3250" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						以下韩国护肤品&amp;化妆品品牌，你知道哪些?（可多选）
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14452].value" style="display:block"></span>

<input type="hidden" name="answers[14452].id" value="" id="answers[14452].id">




<span id="hint_14452">
</span>
<ul>
	<li>
			<input group="14452" class="question_radio_14452 selection" type="checkbox" id="14452_0" name="answers[14452].value" value="12395" onclick=" ">		<label for="14452_0">兰芝Laneige</label>
	</li>
	<li>
			<input group="14452" class="question_radio_14452 selection" type="checkbox" id="14452_1" name="answers[14452].value" value="12396" onclick=" ">		<label for="14452_1">The Face Shop</label>
	</li>
	<li>
			<input group="14452" class="question_radio_14452 selection" type="checkbox" id="14452_2" name="answers[14452].value" value="12397" onclick=" ">		<label for="14452_2">Missha</label>
	</li>
	<li>
			<input group="14452" class="question_radio_14452 selection" type="checkbox" id="14452_3" name="answers[14452].value" value="12398" onclick=" ">		<label for="14452_3">Skin Food</label>
	</li>
	<li>
			<input group="14452" class="question_radio_14452 selection" type="checkbox" id="14452_4" name="answers[14452].value" value="12399" onclick=" ">		<label for="14452_4">婵真Charmzone</label>
	</li>
	<li>
			<input group="14452" class="question_radio_14452 selection" type="checkbox" id="14452_5" name="answers[14452].value" value="12400" onclick=" ">		<label for="14452_5">爱丽Etude House</label>
	</li>
	<li>
			<input group="14452" class="question_radio_14452 selection" type="checkbox" id="14452_6" name="answers[14452].value" value="12401" onclick=" ">		<label for="14452_6">VOV</label>
	</li>
	<li>
			<input group="14452" class="question_radio_14452 selection" type="checkbox" id="14452_7" name="answers[14452].value" value="12402" onclick=" ">		<label for="14452_7">悦诗风吟INNISFREE</label>
	</li>
	<li>
			<input group="14452" class="question_radio_14452 selection" type="checkbox" id="14452_8" name="answers[14452].value" value="12403" onclick=" ">		<label for="14452_8">梦妆Mamonde</label>
	</li>
	<li>
			<input group="14452" class="question_radio_14452 selection" type="checkbox" id="14452_9" name="answers[14452].value" value="12404" onclick=" ">		<label for="14452_9">Hanskin</label>
	</li>
	<li>
			<input group="14452" class="question_radio_14452 selection" type="checkbox" id="14452_10" name="answers[14452].value" value="12405" onclick=" ">		<label for="14452_10">It’s Skin</label>
	</li>
	<li>
			<input group="14452" class="question_radio_14452 selection" type="checkbox" id="14452_11" name="answers[14452].value" value="12406" onclick=" ">		<label for="14452_11">Hera</label>
	</li>
	<li>
			<input group="14452" class="question_radio_14452 selection" type="checkbox" id="14452_12" name="answers[14452].value" value="12407" onclick=" ">		<label for="14452_12">雪花秀</label>
	</li>
	<li>
			<input group="14452" class="question_radio_14452 selection" type="checkbox" id="14452_13" name="answers[14452].value" value="12408" onclick=" ">		<label for="14452_13">OHUI</label>
	</li>
	<li>
			<input group="14452" class="question_radio_14452 selection" type="checkbox" id="14452_14" name="answers[14452].value" value="12409" onclick=" ">		<label for="14452_14">IOPE</label>
	</li>
	<li>
			<input group="14452" class="question_radio_14452 selection" type="checkbox" id="14452_15" name="answers[14452].value" value="12410" onclick="showOrHide3() ">		<label for="14452_15">其他</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
function showOrHide3(){

	if(document.getElementById("14452_15").checked){
		document.getElementById("q_3202").style.display="";
	}else{
		document.getElementById("q_3202").style.display="none";
	}	
}
</script>
		  <div id="q_3202" style="margin-bottom:0px;display:none" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						其他品牌
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[14453].id" value="" id="answers[14453].id">
<input type="text" name="answers[14453].value" value="" id="question_14453" group="14453" class="input-text">

<span class="error-content" id="err_answers[14453].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3259" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						我的韩国攻略/游记：<br>
						(如果你曾经在网络上发布过有关韩国的攻略/游记等，可以直接将链接粘贴在此，不必再复制全文)
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[14454].id" value="" id="answers[14454].id">
<textarea name="answers[14454].value" id="question_14454" cols="40" group="14454" rows="12" class="input-text"></textarea>
<span class="error-content" id="err_answers[14454].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3252" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						是否愿意公开分享此攻略/游记？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14455].value" style="display:block"></span>

<input type="hidden" name="answers[14455].id" value="" id="answers[14455].id">
<ul>
	<li>
			<input group="14455" type="radio" id="14455_0" name="answers[14455].value" value="12411" class="selection question_radio_14455">		<label for="14455_0">是</label>
	</li>
	<li>
			<input group="14455" type="radio" id="14455_1" name="answers[14455].value" value="12412" class="selection question_radio_14455">		<label for="14455_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14455  qc_0 radio" type="radio" name="answers[14455].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br>
<div style="clear:both"></div>
</div>

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br/>
<div class="fillout-submit">
<input id="nextPageButton" type="button" style="display:none"  class="button" onclick="showNextPage();" value='Next Page' />
<input id="submit" type="submit" class="button" name="command.submit" value="提交" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"/></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"/></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"/></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"/></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"/></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"/></td>
	</tr>
</table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br/>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
	        jQuery("#check-alert-dialog .content").html(html);
	        jQuery("#check-alert-dialog").dialog('open');
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '提交失败：不能提交空报告';
		    jQuery("#check-alert-dialog .content").html(html);
		    jQuery("#check-alert-dialog").dialog('open');
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer" style="display:none;">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/c/methodName/c"  target="_blank">Help</a> | <a href="http://www.ostrakon.org"  target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow" style="display:none;"></div>
	<div style="clear: both"></div>
	
</div> 
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[

// ]]>
-->
</script>
