<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div id="container">
		<div id="header" class="header" style="display: none;">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.ostrakon.org" target="_blank">
					<img src="/survey/logoImage/804" style="height:70px; width:301px">
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation" style="display:none;">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
		</div>
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content">
 		

<div id="content" style="width:100%;">
<script language="JavaScript" type="text/javascript">
	
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="return (checkMandatory() &amp;&amp; checkAnswerSet() &amp;&amp; checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="" id="id">
<input type="hidden" name="theme" value="wildfire" id="theme">
<input type="hidden" name="surveyId" value="APuYc3cTF07b">

<div class="page-bar-area">
<span id="pageBar"></span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle">
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0" style="">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3346" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						您的购物行为类型？
					</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14884].value" style="display:block"></span>

<input type="hidden" name="answers[14884].id" value="" id="answers[14884].id">
<ul>
	<li>
			<input group="14884" type="radio" id="14884_0" name="answers[14884].value" value="12566" class="selection question_radio_14884">		<label for="14884_0">冲动型购买（容易受商品外观、包装或其他促销的刺激，购买时以主观感觉为主，不愿作反复比较）</label>
	</li>
	<li>
			<input group="14884" type="radio" id="14884_1" name="answers[14884].value" value="12567" class="selection question_radio_14884">		<label for="14884_1">习惯型购买（对某种商品或店家的信赖、偏爱而产生的经常性购买）</label>
	</li>
	<li>
			<input group="14884" type="radio" id="14884_2" name="answers[14884].value" value="12568" class="selection question_radio_14884">		<label for="14884_2">理智型购买（购买前对所购商品进行比较仔细研究比较，不轻易相信广告、宣传、促销等）</label>
	</li>
	<li>
			<input group="14884" type="radio" id="14884_3" name="answers[14884].value" value="12569" class="selection question_radio_14884">		<label for="14884_3">经济型购买（购买时特别重视价格，对“大甩卖”、“清仓”等低价促销最感兴趣）</label>
	</li>
	<li>
			<input type="radio" class="selection question_radio_14884" value="12602" name="answers[14884].value" id="14884_4" group="14884">		<label for="14884_4">其他类型</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14884  qc_0 radio" type="radio" name="answers[14884].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3347" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						下面哪些因素会让您考虑跟风购买？
					</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14885].value" style="display:block"></span>

<input type="hidden" name="answers[14885].id" value="" id="answers[14885].id">




<span id="hint_14885">
</span>
<ul>
	<li>
			<input group="14885" class="question_radio_14885 selection" type="checkbox" id="14885_0" name="answers[14885].value" value="12570" onclick=" ">		<label for="14885_0">网络口碑产品</label>
	</li>
	<li>
			<input group="14885" class="question_radio_14885 selection" type="checkbox" id="14885_1" name="answers[14885].value" value="12571" onclick=" ">		<label for="14885_1">达人推荐</label>
	</li>
	<li>
			<input group="14885" class="question_radio_14885 selection" type="checkbox" id="14885_2" name="answers[14885].value" value="12572" onclick=" ">		<label for="14885_2">亲友、同事推荐</label>
	</li>
	<li>
			<input group="14885" class="question_radio_14885 selection" type="checkbox" id="14885_3" name="answers[14885].value" value="12573" onclick=" ">		<label for="14885_3">影视剧明星同款</label>
	</li>
	<li>
			<input group="14885" class="question_radio_14885 selection" type="checkbox" id="14885_4" name="answers[14885].value" value="12574" onclick=" ">		<label for="14885_4">促销给力</label>
	</li>
	<li>
			<input group="14885" class="question_radio_14885 selection" type="checkbox" id="14885_5" name="answers[14885].value" value="12575" onclick=" ">		<label for="14885_5">别人有我也要有！</label>
	</li>
	<li>
			<input group="14885" class="question_radio_14885 selection" type="checkbox" id="14885_6" name="answers[14885].value" value="12576" onclick="showOrHide() ">		<label for="14885_6">其他原因(请说明)</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
	function showOrHide(){
		if(jQuery("#14885_6").attr("checked")=="checked"){
			jQuery("#q_3348").css("display","block");
		}else{
			jQuery("#q_3348").css("display","none");
		}
	}
</script>
		  <div id="q_3348" style="margin-bottom:0px; display:none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						其他原因：
					</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[14886].id" value="" id="answers[14886].id">
<input type="text" name="answers[14886].value" value="" id="question_14886" group="14886" class="input-text">

<span class="error-content" id="err_answers[14886].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3349" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						有没有跟风购买产品的经历？
					</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14887].value" style="display:block"></span>

<input type="hidden" name="answers[14887].id" value="" id="answers[14887].id">
<ul>
	<li>
			<input group="14887" type="radio" id="14887_0" name="answers[14887].value" value="12577" onclick="showOrHide3(this.value)" class="selection question_radio_14887">		<label for="14887_0">没有</label>
	</li>
	<li>
			<input group="14887" type="radio" id="14887_1" name="answers[14887].value" value="12578" onclick="showOrHide3(this.value)" class="selection question_radio_14887">		<label for="14887_1">1-5次</label>
	</li>
	<li>
			<input group="14887" type="radio" id="14887_2" name="answers[14887].value" value="12579" onclick="showOrHide3(this.value)" class="selection question_radio_14887">		<label for="14887_2">5-15次</label>
	</li>
	<li>
			<input group="14887" type="radio" id="14887_3" name="answers[14887].value" value="12580" onclick="showOrHide3(this.value)" class="selection question_radio_14887">		<label for="14887_3">15次以上</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14887  qc_0 radio" type="radio" name="answers[14887].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
function showOrHide3(val){
	if("12577"==val){
		$("#q_3351").css("display","none");
		$("#q_3352").css("display","none");
		$("#q_3354").css("display","none");
	}else{
		$("#q_3351").css("display","");
		$("#q_3352").css("display","");
		$("#q_3354").css("display","");		
	}
}
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3350" style="margin-bottom:0px;display:none" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						小编很佩服你！你是如何hold住诱惑，保护钱包君？求分享！
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[14888].id" value="" id="answers[14888].id">
<textarea name="answers[14888].value" id="question_14888" cols="40" group="14888" rows="5" class="input-text"></textarea>
<span class="error-content" id="err_answers[14888].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3351" style="margin-bottom:0px;display:none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						您跟风购买过的商品的最大金额是：
					</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14889].value" style="display:block"></span>

<input type="hidden" name="answers[14889].id" value="" id="answers[14889].id">
<ul>
	<li>
			<input group="14889" type="radio" id="14889_0" name="answers[14889].value" value="12581" class="selection question_radio_14889">		<label for="14889_0">100元以下</label>
	</li>
	<li>
			<input group="14889" type="radio" id="14889_1" name="answers[14889].value" value="12582" class="selection question_radio_14889">		<label for="14889_1">100-500元</label>
	</li>
	<li>
			<input group="14889" type="radio" id="14889_2" name="answers[14889].value" value="12583" class="selection question_radio_14889">		<label for="14889_2">501-1000元</label>
	</li>
	<li>
			<input group="14889" type="radio" id="14889_3" name="answers[14889].value" value="12584" class="selection question_radio_14889">		<label for="14889_3">1001-5000元</label>
	</li>
	<li>
			<input group="14889" type="radio" id="14889_4" name="answers[14889].value" value="12585" class="selection question_radio_14889">		<label for="14889_4">5000元以上</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14889  qc_0 radio" type="radio" name="answers[14889].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3352" style="margin-bottom:0px;display:none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						您跟风购物的产品类型有：
					</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14890].value" style="display:block"></span>

<input type="hidden" name="answers[14890].id" value="" id="answers[14890].id">




<span id="hint_14890">
</span>
<ul>
	<li>
			<input group="14890" class="question_radio_14890 selection" type="checkbox" id="14890_0" name="answers[14890].value" value="12586" onclick=" ">		<label for="14890_0">食品饮料</label>
	</li>
	<li>
			<input group="14890" class="question_radio_14890 selection" type="checkbox" id="14890_1" name="answers[14890].value" value="12587" onclick=" ">		<label for="14890_1">美容化妆，个人护理</label>
	</li>
	<li>
			<input group="14890" class="question_radio_14890 selection" type="checkbox" id="14890_2" name="answers[14890].value" value="12588" onclick=" ">		<label for="14890_2">母婴用品，玩具</label>
	</li>
	<li>
			<input group="14890" class="question_radio_14890 selection" type="checkbox" id="14890_3" name="answers[14890].value" value="12589" onclick=" ">		<label for="14890_3">服装，箱包，鞋帽</label>
	</li>
	<li>
			<input group="14890" class="question_radio_14890 selection" type="checkbox" id="14890_4" name="answers[14890].value" value="12590" onclick=" ">		<label for="14890_4">珠宝饰品，钟表</label>
	</li>
	<li>
			<input group="14890" class="question_radio_14890 selection" type="checkbox" id="14890_5" name="answers[14890].value" value="12591" onclick=" ">		<label for="14890_5">家居用品，生活电器</label>
	</li>
	<li>
			<input group="14890" class="question_radio_14890 selection" type="checkbox" id="14890_6" name="answers[14890].value" value="12592" onclick=" ">		<label for="14890_6">数码电子产品及配件</label>
	</li>
	<li>
			<input group="14890" class="question_radio_14890 selection" type="checkbox" id="14890_7" name="answers[14890].value" value="12593" onclick=" ">		<label for="14890_7">汽车及配件</label>
	</li>
	<li>
			<input group="14890" class="question_radio_14890 selection" type="checkbox" id="14890_8" name="answers[14890].value" value="12594" onclick=" ">		<label for="14890_8">图书杂志</label>
	</li>
	<li>
			<input group="14890" class="question_radio_14890 selection" type="checkbox" id="14890_9" name="answers[14890].value" value="12595" onclick=" ">		<label for="14890_9">收藏品</label>
	</li>
	<li>
			<input group="14890" class="question_radio_14890 selection" type="checkbox" id="14890_10" name="answers[14890].value" value="12596" onclick="showOrHide2() ">		<label for="14890_10">其他(请说明)</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
	function showOrHide2(){
		if(jQuery("#14890_10").attr("checked")=="checked"){
			jQuery("#q_3353").css("display","block");
		}else{
			jQuery("#q_3353").css("display","none");
		}
	}
</script>
		  <div id="q_3353" style="margin-bottom:0px;display:none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						其他产品:
					</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[14891].id" value="" id="answers[14891].id">
<input type="text" name="answers[14891].value" value="" id="question_14891" group="14891" class="input-text">

<span class="error-content" id="err_answers[14891].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3354" style="margin-bottom:0px;display:none" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						总体来说您对跟风购买的商品是否满意？
					</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14892].value" style="display:block"></span>

<input type="hidden" name="answers[14892].id" value="" id="answers[14892].id">
<ul>
	<li>
			<input group="14892" type="radio" id="14892_0" name="answers[14892].value" value="12597" class="selection question_radio_14892">		<label for="14892_0">非常满意</label>
	</li>
	<li>
			<input group="14892" type="radio" id="14892_1" name="answers[14892].value" value="12598" class="selection question_radio_14892">		<label for="14892_1">比较满意</label>
	</li>
	<li>
			<input group="14892" type="radio" id="14892_2" name="answers[14892].value" value="12599" class="selection question_radio_14892">		<label for="14892_2">一般</label>
	</li>
	<li>
			<input group="14892" type="radio" id="14892_3" name="answers[14892].value" value="12600" class="selection question_radio_14892">		<label for="14892_3">不太满意</label>
	</li>
	<li>
			<input group="14892" type="radio" id="14892_4" name="answers[14892].value" value="12601" class="selection question_radio_14892">		<label for="14892_4">非常不满意</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_14892  qc_0 radio" type="radio" name="answers[14892].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
mandatoryElements.push("14893");
// ]]>
-->
</script>
		  <div id="q_3355" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						如果你没有跟过风，小编很佩服你！求分享你是如何hold住诱惑，保护钱包君的！
若你有过跟风的经历，详细分享一次你的跟风购物经历（不论成功的还是失败的）：<span style="color:red">*</span>
					</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[14893].id" value="" id="answers[14893].id">
<textarea name="answers[14893].value" id="question_14893" cols="40" group="14893" rows="12" class="input-text"></textarea>
<span class="error-content" id="err_answers[14893].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value="Next Page" style="display: none;">
<input id="submit" type="submit" style="" class="button" name="command.submit" value="提交">
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tbody><tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"></td>
	</tr>
</tbody></table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '提交失败：不能提交空报告';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>