	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<div class="main-container-outer">
	<div id="container">
		<!-- <div id="header" class="header">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.88brands.com/" target="_blank">
					<img src="/survey/logoImage/813" style="height:70px; width:301px"> 
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div>  --><!-- header -->
		<div id="nav" class="navigation">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
			<ul>
			</ul>
		</div>	
		
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content">
 		

<div id="content">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://www.marketing-research.cn/fillout" onsubmit="return (checkMandatory() &amp;&amp; checkAnswerSet() &amp;&amp; checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">

<div class="questionnaire-title" style="display: none;">France wine</div>


<input type="hidden" name="id" value="813" id="id">
<input type="hidden" name="theme" value="brucetest" id="theme">
<input type="hidden" name="surveyId" value="813">

<div class="mandatory" style="display: none;"><span style="color: red;">* </span>- It is mandatory</div>
<div class="page-bar-area" style="display: none;">
<span id="pageBar">Page:&nbsp;</span>
<strong class="no-answer">No Answer</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle">
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("14966");
// ]]>
-->
</script>
		  <div id="q_3370" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你喜欢喝葡萄酒么？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14966].value" style="display:block"></span>

<input type="hidden" name="answers[14966].id" value="" id="answers[14966].id">
<ul>
	<li>
			<input group="14966" type="radio" id="14966_0" name="answers[14966].value" value="12623" class="selection question_radio_14966">		<label for="14966_0">喜欢，一个月两次以上</label>
	</li>
	<li>
			<input group="14966" type="radio" id="14966_1" name="answers[14966].value" value="12624" class="selection question_radio_14966">		<label for="14966_1">喜欢，通常半个月喝一次</label>
	</li>
	<li>
			<input group="14966" type="radio" id="14966_2" name="answers[14966].value" value="12625" class="selection question_radio_14966">		<label for="14966_2">喜欢，一般一个月一次</label>
	</li>
	<li>
			<input group="14966" type="radio" id="14966_3" name="answers[14966].value" value="12626" class="selection question_radio_14966">		<label for="14966_3">喜欢，每月不到一次</label>
	</li>
	<li>
			<input group="14966" type="radio" id="14966_4" name="answers[14966].value" value="12627" class="selection question_radio_14966">		<label for="14966_4">不喜欢，但是愿意试试</label>
	</li>
	<li>
			<input group="14966" type="radio" id="14966_5" name="answers[14966].value" value="12628" class="selection question_radio_14966">		<label for="14966_5">一点都不喜欢</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3371" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你最常喝哪种或哪几种酒？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14967].value" style="display:block"></span>

<input type="hidden" name="answers[14967].id" value="" id="answers[14967].id">




<span id="hint_14967">
</span>
<ul>
	<li>
			<input group="14967" class="question_radio_14967 selection" type="checkbox" id="14967_0" name="answers[14967].value" value="12629" onclick=" ">		<label for="14967_0">啤酒</label>
	</li>
	<li>
			<input group="14967" class="question_radio_14967 selection" type="checkbox" id="14967_1" name="answers[14967].value" value="12630" onclick=" ">		<label for="14967_1">白酒</label>
	</li>
	<li>
			<input group="14967" class="question_radio_14967 selection" type="checkbox" id="14967_2" name="answers[14967].value" value="12631" onclick=" ">		<label for="14967_2">黄酒</label>
	</li>
	<li>
			<input group="14967" class="question_radio_14967 selection" type="checkbox" id="14967_3" name="answers[14967].value" value="12632" onclick=" ">		<label for="14967_3">威士忌</label>
	</li>
	<li>
			<input group="14967" class="question_radio_14967 selection" type="checkbox" id="14967_4" name="answers[14967].value" value="12633" onclick=" ">		<label for="14967_4">伏特加</label>
	</li>
	<li>
			<input group="14967" class="question_radio_14967 selection" type="checkbox" id="14967_5" name="answers[14967].value" value="12634" onclick=" ">		<label for="14967_5">白兰地</label>
	</li>
	<li>
			<input group="14967" class="question_radio_14967 selection" type="checkbox" id="14967_6" name="answers[14967].value" value="12635" onclick=" ">		<label for="14967_6">香槟</label>
	</li>
	<li>
			<input group="14967" class="question_radio_14967 selection" type="checkbox" id="14967_7" name="answers[14967].value" value="12636" onclick=" ">		<label for="14967_7">红葡萄酒</label>
	</li>
	<li>
			<input group="14967" class="question_radio_14967 selection" type="checkbox" id="14967_8" name="answers[14967].value" value="12637" onclick=" ">		<label for="14967_8">白葡萄酒</label>
	</li>
	<li>
			<input group="14967" class="question_radio_14967 selection" type="checkbox" id="14967_9" name="answers[14967].value" value="12638" onclick="showOrHide1()">		<label for="14967_9">其他（请举例）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function showOrHide1(){
		if(jQuery("#14967_9").attr("checked")=="checked"){
			jQuery("#q_3372").css("display","");
		}else{
			jQuery("#q_3372").css("display","none");
		}
	}
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3372" style="margin-bottom: 0px; display:none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						其他酒：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[14968].id" value="" id="answers[14968].id">
<input type="text" name="answers[14968].value" value="" id="question_14968" group="14968" class="input-text">

<span class="error-content" id="err_answers[14968].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3373" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你以前喝过哪些地方的葡萄酒？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14969].value" style="display:block"></span>

<input type="hidden" name="answers[14969].id" value="" id="answers[14969].id">




<span id="hint_14969">
</span>
<ul>
	<li>
			<input group="14969" class="question_radio_14969 selection" type="checkbox" id="14969_0" name="answers[14969].value" value="12639" onclick=" ">		<label for="14969_0">中国</label>
	</li>
	<li>
			<input group="14969" class="question_radio_14969 selection" type="checkbox" id="14969_1" name="answers[14969].value" value="12640" onclick=" ">		<label for="14969_1">法国</label>
	</li>
	<li>
			<input group="14969" class="question_radio_14969 selection" type="checkbox" id="14969_2" name="answers[14969].value" value="12641" onclick=" ">		<label for="14969_2">西班牙</label>
	</li>
	<li>
			<input group="14969" class="question_radio_14969 selection" type="checkbox" id="14969_3" name="answers[14969].value" value="12642" onclick=" ">		<label for="14969_3">意大利</label>
	</li>
	<li>
			<input group="14969" class="question_radio_14969 selection" type="checkbox" id="14969_4" name="answers[14969].value" value="12643" onclick=" ">		<label for="14969_4">澳洲</label>
	</li>
	<li>
			<input group="14969" class="question_radio_14969 selection" type="checkbox" id="14969_5" name="answers[14969].value" value="12644" onclick=" ">		<label for="14969_5">南美</label>
	</li>
	<li>
			<input group="14969" class="question_radio_14969 selection" type="checkbox" id="14969_6" name="answers[14969].value" value="12645" onclick=" ">		<label for="14969_6">北美</label>
	</li>
	<li>
			<input group="14969" class="question_radio_14969 selection" type="checkbox" id="14969_7" name="answers[14969].value" value="12646" onclick="showOrHide2()">		<label for="14969_7">其他（请举例）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function showOrHide2(){
		if(jQuery("#14969_7").attr("checked")=="checked"){
			jQuery("#q_3374").css("display","");
		}else{
			jQuery("#q_3374").css("display","none");
		}
	}
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3374" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						其他地区：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[14970].id" value="" id="answers[14970].id">
<input type="text" name="answers[14970].value" value="" id="question_14970" group="14970" class="input-text">

<span class="error-content" id="err_answers[14970].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3375" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你最经常从哪种途径得知葡萄酒的消息？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14971].value" style="display:block"></span>

<input type="hidden" name="answers[14971].id" value="" id="answers[14971].id">




<span id="hint_14971">
</span>
<ul>
	<li>
			<input group="14971" class="question_radio_14971 selection" type="checkbox" id="14971_0" name="answers[14971].value" value="12647" onclick=" ">		<label for="14971_0">电视</label>
	</li>
	<li>
			<input group="14971" class="question_radio_14971 selection" type="checkbox" id="14971_1" name="answers[14971].value" value="12648" onclick=" ">		<label for="14971_1">纸媒</label>
	</li>
	<li>
			<input group="14971" class="question_radio_14971 selection" type="checkbox" id="14971_2" name="answers[14971].value" value="12649" onclick=" ">		<label for="14971_2">户外广告</label>
	</li>
	<li>
			<input group="14971" class="question_radio_14971 selection" type="checkbox" id="14971_3" name="answers[14971].value" value="12650" onclick=" ">		<label for="14971_3">网络</label>
	</li>
	<li>
			<input group="14971" class="question_radio_14971 selection" type="checkbox" id="14971_4" name="answers[14971].value" value="12651" onclick=" ">		<label for="14971_4">广播里</label>
	</li>
	<li>
			<input group="14971" class="question_radio_14971 selection" type="checkbox" id="14971_5" name="answers[14971].value" value="12652" onclick="showOrHide3()">		<label for="14971_5">其他（请举例）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function showOrHide3(){
		if(jQuery("#14971_5").attr("checked")=="checked"){
			jQuery("#q_3376").css("display","");
		}else{
			jQuery("#q_3376").css("display","none");
		}
	}
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3376" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						其他途径：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[14972].id" value="" id="answers[14972].id">
<input type="text" name="answers[14972].value" value="" id="question_14972" group="14972" class="input-text">

<span class="error-content" id="err_answers[14972].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3377" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你收到过别人送的葡萄酒吗？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14973].value" style="display:block"></span>

<input type="hidden" name="answers[14973].id" value="" id="answers[14973].id">
<ul>
	<li>
			<input group="14973" type="radio" id="14973_0" name="answers[14973].value" value="12653" class="selection question_radio_14973">		<label for="14973_0">收到过</label>
	</li>
	<li>
			<input group="14973" type="radio" id="14973_1" name="answers[14973].value" value="12654" class="selection question_radio_14973">		<label for="14973_1">没收到过</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
		<input class="q_14973  qc_0 radio" type="radio" name="answers[14973].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("14974");
// ]]>
-->
</script>
		  <div id="q_3378" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你会自己买葡萄酒吗？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14974].value" style="display:block"></span>

<input type="hidden" name="answers[14974].id" value="" id="answers[14974].id">
<ul>
	<li>
			<input group="14974" type="radio" id="14974_0" name="answers[14974].value" value="12655" class="selection question_radio_14974" onclick="showOrHide4()">		<label for="14974_0">不会</label>
	</li>
	<li>
			<input group="14974" type="radio" id="14974_1" name="answers[14974].value" value="12656" class="selection question_radio_14974" onclick="showOrHide4()">		<label for="14974_1">会，在商店里</label>
	</li>
	<li>
			<input group="14974" type="radio" id="14974_2" name="answers[14974].value" value="12657" class="selection question_radio_14974" onclick="showOrHide4()">		<label for="14974_2">会，在网上买</label>
	</li>
	<li>
			<input group="14974" type="radio" id="14974_3" name="answers[14974].value" value="12658" class="selection question_radio_14974" onclick="showOrHide4()">		<label for="14974_3">会，在餐厅或酒馆</label>
	</li>
	<li>
			<input group="14974" type="radio" id="14974_4" name="answers[14974].value" value="12659" class="selection question_radio_14974" onclick="showOrHide4()">		<label for="14974_4">会，在其他地方(请举例)</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function showOrHide4(){
		if(jQuery("#14974_4").attr("checked")){
				jQuery("#q_3379").css("display","");
				jQuery("#q_3380").css("display","");
				jQuery("#q_3381").css("display","");
			}else if(jQuery("#14974_0").attr("checked")){
				jQuery("#q_3380").css("display","none");
				jQuery("#q_3381").css("display","none");
			}else{
				jQuery("#q_3379").css("display","none");
				jQuery("#q_3380").css("display","");
				jQuery("#q_3381").css("display","");
			}
	}
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3379" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						其他地方：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[14975].id" value="" id="answers[14975].id">
<input type="text" name="answers[14975].value" value="" id="question_14975" group="14975" class="input-text">

<span class="error-content" id="err_answers[14975].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3380" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你买葡萄酒是为了送人还是自己喝？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14976].value" style="display:block"></span>

<input type="hidden" name="answers[14976].id" value="" id="answers[14976].id">
<ul>
	<li>
			<input group="14976" type="radio" id="14976_0" name="answers[14976].value" value="12660" class="selection question_radio_14976">		<label for="14976_0">送人</label>
	</li>
	<li>
			<input group="14976" type="radio" id="14976_1" name="answers[14976].value" value="12661" class="selection question_radio_14976">		<label for="14976_1">自己喝</label>
	</li>
	<li>
			<input group="14976" type="radio" id="14976_2" name="answers[14976].value" value="12662" class="selection question_radio_14976">		<label for="14976_2">都有</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
		<input class="q_14976  qc_0 radio" type="radio" name="answers[14976].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3381" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						如果你会买法国葡萄酒，是由于哪些原因？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14977].value" style="display:block"></span>

<input type="hidden" name="answers[14977].id" value="" id="answers[14977].id">




<span id="hint_14977">
</span>
<ul>
	<li>
			<input group="14977" class="question_radio_14977 selection" type="checkbox" id="14977_0" name="answers[14977].value" value="12663" onclick=" ">		<label for="14977_0">口味</label>
	</li>
	<li>
			<input group="14977" class="question_radio_14977 selection" type="checkbox" id="14977_1" name="answers[14977].value" value="12664" onclick=" ">		<label for="14977_1">产区</label>
	</li>
	<li>
			<input group="14977" class="question_radio_14977 selection" type="checkbox" id="14977_2" name="answers[14977].value" value="12665" onclick=" ">		<label for="14977_2">品质</label>
	</li>
	<li>
			<input group="14977" class="question_radio_14977 selection" type="checkbox" id="14977_3" name="answers[14977].value" value="12666" onclick=" ">		<label for="14977_3">年份</label>
	</li>
	<li>
			<input group="14977" class="question_radio_14977 selection" type="checkbox" id="14977_4" name="answers[14977].value" value="12667" onclick=" ">		<label for="14977_4">名声</label>
	</li>
	<li>
			<input group="14977" class="question_radio_14977 selection" type="checkbox" id="14977_5" name="answers[14977].value" value="12668" onclick=" ">		<label for="14977_5">价格</label>
	</li>
	<li>
			<input group="14977" class="question_radio_14977 selection" type="checkbox" id="14977_6" name="answers[14977].value" value="12669" onclick=" ">		<label for="14977_6">朋友/家人推荐</label>
	</li>
	<li>
			<input group="14977" class="question_radio_14977 selection" type="checkbox" id="14977_7" name="answers[14977].value" value="12670" onclick=" ">		<label for="14977_7">包装/广告</label>
	</li>
	<li>
			<input group="14977" class="question_radio_14977 selection" type="checkbox" id="14977_8" name="answers[14977].value" value="12671" onclick=" ">		<label for="14977_8">随便选，碰碰运气</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("14978");
// ]]>
-->
</script>
		  <div id="q_3382" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						我们将于以下时间在法国领事馆（上海/成都）举行焦点小组现场活动，并且您会得到两瓶葡萄酒。请问你愿意参加吗？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14978].value" style="display:block"></span>

<input type="hidden" name="answers[14978].id" value="" id="answers[14978].id">




<span id="hint_14978">
</span>
<ul>
	<li>
			<input group="14978" class="question_radio_14978 selection" type="checkbox" id="14978_0" name="answers[14978].value" value="12672" onclick=" ">		<label for="14978_0">愿意，上海，7月6日</label>
	</li>
	<li>
			<input group="14978" class="question_radio_14978 selection" type="checkbox" id="14978_1" name="answers[14978].value" value="12673" onclick=" ">		<label for="14978_1">愿意，上海，7月13日</label>
	</li>
	<li>
			<input group="14978" class="question_radio_14978 selection" type="checkbox" id="14978_2" name="answers[14978].value" value="12674" onclick=" ">		<label for="14978_2">愿意，成都，7月13日以后（具体待定）</label>
	</li>
	<li>
			<input group="14978" class="question_radio_14978 selection" type="checkbox" id="14978_3" name="answers[14978].value" value="12675" onclick=" ">		<label for="14978_3">这几个时间都不方便</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("14979");
// ]]>
-->
</script>
		  <div id="q_3383" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你的年龄？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14979].value" style="display:block"></span>

<input type="hidden" name="answers[14979].id" value="" id="answers[14979].id">

	<select group="14979" class="selection" id="question_14979" name="answers[14979].value" title="title" size="1">
	<option selected="selected" value="0">请选择</option>
<option value="12676" style="">&lt; 23岁</option>
<option value="12677" style="">23-34 岁</option>
<option value="12678" style="">35-44 岁</option>
<option value="12679" style="">45-60 岁</option>
<option value="12680" style="">&gt;60岁</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("14980");
// ]]>
-->
</script>
		  <div id="q_3384" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你的性别？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14980].value" style="display:block"></span>

<input type="hidden" name="answers[14980].id" value="" id="answers[14980].id">
<ul>
	<li>
			<input group="14980" type="radio" id="14980_0" name="answers[14980].value" value="12681" class="selection question_radio_14980">		<label for="14980_0">女</label>
	</li>
	<li>
			<input group="14980" type="radio" id="14980_1" name="answers[14980].value" value="12682" class="selection question_radio_14980">		<label for="14980_1">男</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("14981");
// ]]>
-->
</script>
		  <div id="q_3385" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你的家庭月收入是多少？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14981].value" style="display:block"></span>

<input type="hidden" name="answers[14981].id" value="" id="answers[14981].id">

	<select group="14981" class="selection" id="question_14981" name="answers[14981].value" title="title" size="1">
	<option selected="selected" value="0">请选择</option>
<option value="12683" style="">&lt; 5,000/月</option>
<option value="12684" style="">￥5,000～8,000/月</option>
<option value="12685" style="">￥8,000～15,000/月</option>
<option value="12686" style="">￥15,000～20,000/月</option>
<option value="12687" style="">￥20,000～25,000/月</option>
<option value="12688" style="">&gt;25,000/月</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3386" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你的姓名：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[14982].id" value="" id="answers[14982].id">
<input type="text" name="answers[14982].value" value="" id="question_14982" group="14982" class="input-text">

<span class="error-content" id="err_answers[14982].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3387" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你的邮箱：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[14983].id" value="" id="answers[14983].id">
<input type="text" name="answers[14983].value" value="" id="question_14983" group="14983" class="input-text">

<span class="error-content" id="err_answers[14983].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("14984");
// ]]>
-->
</script>
		  <div id="q_3388" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你的电话：
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[14984].id" value="" id="answers[14984].id">
<input type="text" name="answers[14984].value" value="" id="question_14984" group="14984" class="input-text">

<span class="error-content" id="err_answers[14984].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("14985");
// ]]>
-->
</script>
		  <div id="q_2158" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						城市:
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[14985].value" style="display:block"></span>

<input type="hidden" name="answers[14985].id" value="" id="answers[14985].id">

	<select group="14985" class="selection" id="question_14985" name="answers[14985].value" title="title" size="1">
	<option selected="selected" value="0">请选择</option>
<option value="8315" style="">北京市</option>
<option value="8316" style="">上海市</option>
<option value="8317" style="">广州市</option>
<option value="8318" style="">成都市</option>
<option value="8319" style="">保定市</option>
<option value="8320" style="">鞍山市</option>
<option value="8321" style="">沧州市</option>
<option value="8322" style="">长春市</option>
<option value="8323" style="">长沙市</option>
<option value="8324" style="">常州市</option>
<option value="8325" style="">郴州市</option>
<option value="8326" style="">宝鸡市</option>
<option value="8327" style="">大理市</option>
<option value="8328" style="">大连市</option>
<option value="8329" style="">大庆市</option>
<option value="8330" style="">大同市</option>
<option value="8331" style="">东莞市</option>
<option value="8332" style="">佛山市</option>
<option value="8333" style="">福州市</option>
<option value="8334" style="">抚顺市</option>
<option value="8335" style="">包头市</option>
<option value="8336" style="">贵阳市</option>
<option value="8337" style="">桂林市</option>
<option value="8338" style="">哈尔滨市</option>
<option value="8339" style="">海口市</option>
<option value="8340" style="">杭州市</option>
<option value="8341" style="">合肥市</option>
<option value="8342" style="">衡阳市</option>
<option value="8343" style="">呼和浩特市</option>
<option value="8344" style="">惠州市</option>
<option value="8345" style="">吉林市</option>
<option value="8346" style="">济南市</option>
<option value="8347" style="">嘉兴市</option>
<option value="8348" style="">江门市</option>
<option value="8349" style="">九江市</option>
<option value="8350" style="">开封市</option>
<option value="8351" style="">昆明市</option>
<option value="8352" style="">兰州市</option>
<option value="8353" style="">廊坊市</option>
<option value="8354" style="">连云港市</option>
<option value="8355" style="">洛阳市</option>
<option value="8356" style="">马安山市</option>
<option value="8357" style="">牡丹江市</option>
<option value="8358" style="">南昌市</option>
<option value="8359" style="">南京市</option>
<option value="8360" style="">南宁市</option>
<option value="8361" style="">南通市</option>
<option value="8362" style="">宁波市</option>
<option value="8363" style="">攀枝花市</option>
<option value="8364" style="">平顶山市</option>
<option value="8365" style="">齐齐哈尔</option>
<option value="8366" style="">秦皇岛市</option>
<option value="8367" style="">青岛市</option>
<option value="8368" style="">泉州市</option>
<option value="8369" style="">汕头市</option>
<option value="8370" style="">蚌埠市</option>
<option value="8371" style="">绍兴市</option>
<option value="8372" style="">深圳市</option>
<option value="8373" style="">沈阳市</option>
<option value="8374" style="">石家庄市</option>
<option value="8375" style="">苏州市</option>
<option value="8376" style="">太原市</option>
<option value="8377" style="">泰州市</option>
<option value="8378" style="">唐山市</option>
<option value="8379" style="">天津市</option>
<option value="8380" style="">威海市</option>
<option value="8381" style="">潍坊市</option>
<option value="8382" style="">温州市</option>
<option value="8383" style="">乌鲁木齐市</option>
<option value="8384" style="">无锡市</option>
<option value="8385" style="">芜湖市</option>
<option value="8386" style="">武汉市</option>
<option value="8387" style="">西安市</option>
<option value="8388" style="">西宁市</option>
<option value="8389" style="">厦门市</option>
<option value="8390" style="">新乡市</option>
<option value="8391" style="">徐州市</option>
<option value="8392" style="">烟台市</option>
<option value="8393" style="">延安市</option>
<option value="8394" style="">扬州市</option>
<option value="8395" style="">宜宾市</option>
<option value="8396" style="">银川市</option>
<option value="8397" style="">玉林市</option>
<option value="8398" style="">玉溪市</option>
<option value="8399" style="">湛江市</option>
<option value="8400" style="">漳州市</option>
<option value="8401" style="">镇江市</option>
<option value="8402" style="">郑州市</option>
<option value="8403" style="">中山市</option>
<option value="8404" style="">重庆市</option>
<option value="8405" style="">珠海市</option>
<option value="8406" style="">淄博市</option>
<option value="8407" style="">自贡市</option>
<option value="8408" style="">遵义市</option>
<option value="8409" style="">其他</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value="Next Page" style="display: none;">
<input id="submit" type="submit" style="" class="button" name="command.submit" value="提交">
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tbody><tr>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_l_t.gif"></td>
		<td height="9" background="http://www.marketing-research.cn/images/web_dialog_m_t.gif"><img src="http://www.marketing-research.cn/images/web_dialog_m_t.gif"></td>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_r_t.gif"></td>
	</tr>
	<tr>
		<td width="9" background="http://www.marketing-research.cn/images/web_dialog_l_m.gif"><img src="http://www.marketing-research.cn/images/web_dialog_l_m.gif"></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://www.marketing-research.cn/images/web_dialog_r_m.gif"><img src="http://www.marketing-research.cn/images/web_dialog_r_m.gif"></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_l_b.gif"></td>
		<td height="9" background="http://www.marketing-research.cn/images/web_dialog_m_b.gif"><img src="http://www.marketing-research.cn/images/web_dialog_m_b.gif"></td>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_r_b.gif"></td>
	</tr>
</tbody></table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-Previous" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "Next ->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://www.marketing-research.cn/images/spinner.gif' />Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '提交失败：不能提交空报告';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>
<!-- <div class="main-content-outer"><div style="color:#999;width:800; margin-left:20px; margin-right:20px;">我们非常重视对您隐私权的保护。邮件及手机号等个人资料为用户重要隐私，我们承诺不会将个人资料用作它途；承诺不会在未获得用户许可的情况下擅自将用户的个人资料信息出租或出售给任何第三方。如果您对本声明或我们的个人信息处理存在任何疑义，请发送邮件至home@marketing-research.cn联系我们。</div></div> -->
<div class="footer">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link" style="display: none;">
			<p>ostrakon indicate version 2.0</p>
			<p><a href="http://www.ostrakon.org" target="_blank">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a href="/help/index/actionName/s/methodName/s" target="_blank">Help</a> | <a href="http://www.ostrakon.org" target="_blank">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow"></div>
	<div style="clear: both"></div>
	
</div>