
<div class="container">
	<div class="container-inner">

	<script type="text/javascript" language="JavaScript">

	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie &gt; 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length &gt; MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}

	</script>

<script type="text/javascript">

</script>



<div class="main-container-outer">
	<div id="container">
		<!-- <div id="header" class="header">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.88brands.com/" target="_blank">
					<img src="/survey/logoImage/813" style="height:70px; width:301px"> 
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div>  --><!-- header -->
			<div id="nav" class="navigation">
				<div class="nav-left"></div>
				<div class="nav-right"></div>
				<ul>
				</ul>
			</div>	
		
 

			<div style="clear:both;"></div>
			<div class="main-content-outer" id="content">
 		

<div id="content">
	<script language="JavaScript" type="text/javascript">
	<!--
	// <![CDATA[
		mandatoryElements = new Array(); 
	// ]]>
	-->
	</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form onsubmit="return (checkMandatory() &&checkAnswerSet() &&checkCommentAnswers());" action="http://q.xingxinghuo.cn/fillout" method="post" id="fillout">
<div style="display:none" id="mainzone-top-wrapper">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" id="id" value="" name="id">
<input type="hidden" id="theme" value="wildfire" name="theme">
<input type="hidden" value="7Fu2kqat7GW2" name="surveyId">

<div class="mandatory"><span style="color: red;">* </span>- It is mandatory</div>
<div class="page-bar-area">
<span id="pageBar"></span>
<strong class="no-answer">No Answer</strong><img align="absmiddle" src="/images/no_answer.gif" class="no-answer">
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0" style="">
<script type="text/javascript" language="JavaScript">

		 	mandatoryElements.push("14966");

</script>
		  <div class="question-even question-area" style="margin-bottom:0px;" id="q_3370">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你喜欢喝葡萄酒么？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span style="display:block" id="err_answers[14966].value" class="error-content"></span>

<input type="hidden" id="answers[14966].id" value="" name="answers[14966].id">
<ul>
	<li>
			<input type="radio" class="selection question_radio_14966" value="12623" name="answers[14966].value" id="14966_0" group="14966">		<label for="14966_0">喜欢，一个月两次以上</label>
	</li>
	<li>
			<input type="radio" class="selection question_radio_14966" value="12624" name="answers[14966].value" id="14966_1" group="14966">		<label for="14966_1">喜欢，通常半个月喝一次</label>
	</li>
	<li>
			<input type="radio" class="selection question_radio_14966" value="12625" name="answers[14966].value" id="14966_2" group="14966">		<label for="14966_2">喜欢，一般一个月一次</label>
	</li>
	<li>
			<input type="radio" class="selection question_radio_14966" value="12626" name="answers[14966].value" id="14966_3" group="14966">		<label for="14966_3">喜欢，每月不到一次</label>
	</li>
	<li>
			<input type="radio" class="selection question_radio_14966" value="12627" name="answers[14966].value" id="14966_4" group="14966">		<label for="14966_4">不喜欢，但是愿意试试</label>
	</li>
	<li>
			<input type="radio" class="selection question_radio_14966" value="12628" name="answers[14966].value" id="14966_5" group="14966">		<label for="14966_5">一点都不喜欢</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script type="text/javascript" language="JavaScript">

</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

</script>
		  <div class="question-odd question-area" style="margin-bottom:0px;" id="q_3371">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你最常喝哪种或哪几种酒？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span style="display:block" id="err_answers[14967].value" class="error-content"></span>

<input type="hidden" id="answers[14967].id" value="" name="answers[14967].id">




<span id="hint_14967">
</span>
<ul>
	<li>
			<input type="checkbox" onclick=" " value="12629" name="answers[14967].value" id="14967_0" class="question_radio_14967 selection" group="14967">		<label for="14967_0">啤酒</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12630" name="answers[14967].value" id="14967_1" class="question_radio_14967 selection" group="14967">		<label for="14967_1">白酒</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12631" name="answers[14967].value" id="14967_2" class="question_radio_14967 selection" group="14967">		<label for="14967_2">黄酒</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12632" name="answers[14967].value" id="14967_3" class="question_radio_14967 selection" group="14967">		<label for="14967_3">威士忌</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12633" name="answers[14967].value" id="14967_4" class="question_radio_14967 selection" group="14967">		<label for="14967_4">伏特加</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12634" name="answers[14967].value" id="14967_5" class="question_radio_14967 selection" group="14967">		<label for="14967_5">白兰地</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12635" name="answers[14967].value" id="14967_6" class="question_radio_14967 selection" group="14967">		<label for="14967_6">香槟</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12636" name="answers[14967].value" id="14967_7" class="question_radio_14967 selection" group="14967">		<label for="14967_7">红葡萄酒</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12637" name="answers[14967].value" id="14967_8" class="question_radio_14967 selection" group="14967">		<label for="14967_8">白葡萄酒</label>
	</li>
	<li>
			<input type="checkbox" onclick="showOrHide1() " value="12638" name="answers[14967].value" id="14967_9" class="question_radio_14967 selection" group="14967">		<label for="14967_9">其他（请举例）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script type="text/javascript" language="JavaScript">
	function showOrHide1(){
		if(jQuery("#14967_9").attr("checked")=="checked"){
			jQuery("#q_3372").css("display","");
		}else{
			jQuery("#q_3372").css("display","none");
		}
	}
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

</script>
		  <div class="question-even question-area" style="margin-bottom:0px;display:none;" id="q_3372">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						其他酒：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" id="answers[14968].id" value="" name="answers[14968].id">
<input type="text" class="input-text" group="14968" id="question_14968" value="" name="answers[14968].value">

<span id="err_answers[14968].value" class="error-content"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

</script>
		  <div class="question-odd question-area" style="margin-bottom:0px;" id="q_3373">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你以前喝过哪些地方的葡萄酒？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span style="display:block" id="err_answers[14969].value" class="error-content"></span>

<input type="hidden" id="answers[14969].id" value="" name="answers[14969].id">




<span id="hint_14969">
</span>
<ul>
	<li>
			<input type="checkbox" onclick=" " value="12639" name="answers[14969].value" id="14969_0" class="question_radio_14969 selection" group="14969">		<label for="14969_0">中国</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12640" name="answers[14969].value" id="14969_1" class="question_radio_14969 selection" group="14969">		<label for="14969_1">法国</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12641" name="answers[14969].value" id="14969_2" class="question_radio_14969 selection" group="14969">		<label for="14969_2">西班牙</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12642" name="answers[14969].value" id="14969_3" class="question_radio_14969 selection" group="14969">		<label for="14969_3">意大利</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12643" name="answers[14969].value" id="14969_4" class="question_radio_14969 selection" group="14969">		<label for="14969_4">澳洲</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12644" name="answers[14969].value" id="14969_5" class="question_radio_14969 selection" group="14969">		<label for="14969_5">南美</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12645" name="answers[14969].value" id="14969_6" class="question_radio_14969 selection" group="14969">		<label for="14969_6">北美</label>
	</li>
	<li>
			<input type="checkbox" onclick="showOrHide2() " value="12646" name="answers[14969].value" id="14969_7" class="question_radio_14969 selection" group="14969">		<label for="14969_7">其他（请举例）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script type="text/javascript" language="JavaScript">

</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">
	function showOrHide2(){
		if(jQuery("#14969_7").attr("checked")=="checked"){
			jQuery("#q_3374").css("display","");
		}else{
			jQuery("#q_3374").css("display","none");
		}
	}
</script>
		  <div class="question-even question-area" style="margin-bottom:0px;display:none;" id="q_3374">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						其他地区：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" id="answers[14970].id" value="" name="answers[14970].id">
<input type="text" class="input-text" group="14970" id="question_14970" value="" name="answers[14970].value">

<span id="err_answers[14970].value" class="error-content"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

</script>
		  <div class="question-odd question-area" style="margin-bottom:0px;" id="q_3375">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你最经常从哪种途径得知葡萄酒的消息？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span style="display:block" id="err_answers[14971].value" class="error-content"></span>

<input type="hidden" id="answers[14971].id" value="" name="answers[14971].id">




<span id="hint_14971">
</span>
<ul>
	<li>
			<input type="checkbox" onclick=" " value="12647" name="answers[14971].value" id="14971_0" class="question_radio_14971 selection" group="14971">		<label for="14971_0">电视</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12648" name="answers[14971].value" id="14971_1" class="question_radio_14971 selection" group="14971">		<label for="14971_1">纸媒</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12649" name="answers[14971].value" id="14971_2" class="question_radio_14971 selection" group="14971">		<label for="14971_2">户外广告</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12650" name="answers[14971].value" id="14971_3" class="question_radio_14971 selection" group="14971">		<label for="14971_3">网络</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12651" name="answers[14971].value" id="14971_4" class="question_radio_14971 selection" group="14971">		<label for="14971_4">广播里</label>
	</li>
	<li>
			<input type="checkbox" onclick="showOrHide3() " value="12652" name="answers[14971].value" id="14971_5" class="question_radio_14971 selection" group="14971">		<label for="14971_5">其他（请举例）</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script type="text/javascript" language="JavaScript">

</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">
	function showOrHide3(){
		if(jQuery("#14971_5").attr("checked")=="checked"){
			jQuery("#q_3376").css("display","");
		}else{
			jQuery("#q_3376").css("display","none");
		}
	}
</script>
		  <div class="question-even question-area" style="margin-bottom:0px; display:none;" id="q_3376">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						其他途径：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" id="answers[14972].id" value="" name="answers[14972].id">
<input type="text" class="input-text" group="14972" id="question_14972" value="" name="answers[14972].value">

<span id="err_answers[14972].value" class="error-content"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

</script>
		  <div class="question-odd question-area" style="margin-bottom:0px;" id="q_3377">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你收到过别人送的葡萄酒吗？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span style="display:block" id="err_answers[14973].value" class="error-content"></span>

<input type="hidden" id="answers[14973].id" value="" name="answers[14973].id">
<ul>
	<li>
			<input type="radio" class="selection question_radio_14973" value="12653" name="answers[14973].value" id="14973_0" group="14973">		<label for="14973_0">收到过</label>
	</li>
	<li>
			<input type="radio" class="selection question_radio_14973" value="12654" name="answers[14973].value" id="14973_1" group="14973">		<label for="14973_1">没收到过</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input type="radio" name="answers[14973].value" class="q_14973  qc_0 radio">
</td>
</tr>

  </tbody></table>
<script type="text/javascript" language="JavaScript">

</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

		 	mandatoryElements.push("14974");

</script>
		  <div class="question-even question-area" style="margin-bottom:0px;" id="q_3378">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你会自己买葡萄酒吗？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span style="display:block" id="err_answers[14974].value" class="error-content"></span>

<input type="hidden" id="answers[14974].id" value="" name="answers[14974].id">
<ul>
	<li>
			<input type="radio" class="selection question_radio_14974" value="12655" name="answers[14974].value" id="14974_0" group="14974" onclick="showOrHide4()">		<label for="14974_0">不会</label>
	</li>
	<li>
			<input type="radio" class="selection question_radio_14974" value="12656" name="answers[14974].value" id="14974_1" group="14974" onclick="showOrHide4()">		<label for="14974_1">会，在商店里</label>
	</li>
	<li>
			<input type="radio" class="selection question_radio_14974" value="12657" name="answers[14974].value" id="14974_2" group="14974" onclick="showOrHide4()">		<label for="14974_2">会，在网上买</label>
	</li>
	<li>
			<input type="radio" class="selection question_radio_14974" value="12658" name="answers[14974].value" id="14974_3" group="14974" onclick="showOrHide4()">		<label for="14974_3">会，在餐厅或酒馆</label>
	</li>
	<li>
			<input type="radio" class="selection question_radio_14974" value="12659" name="answers[14974].value" id="14974_4" group="14974" onclick="showOrHide4()">		<label for="14974_4">会，在其他地方(请举例)</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script type="text/javascript" language="JavaScript">

</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">
function showOrHide4(){
		if(jQuery("#14974_4").attr("checked")){
				jQuery("#q_3379").css("display","");
				jQuery("#q_3380").css("display","");
				jQuery("#q_3381").css("display","");
			}else if(jQuery("#14974_0").attr("checked")){
				jQuery("#q_3380").css("display","none");
				jQuery("#q_3381").css("display","none");
			}else{
				jQuery("#q_3379").css("display","none");
				jQuery("#q_3380").css("display","");
				jQuery("#q_3381").css("display","");
			}
	}
</script>
		  <div class="question-odd question-area" style="margin-bottom:0px;display:none;" id="q_3379">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						其他地方：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" id="answers[14975].id" value="" name="answers[14975].id">
<input type="text" class="input-text" group="14975" id="question_14975" value="" name="answers[14975].value">

<span id="err_answers[14975].value" class="error-content"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

</script>
		  <div class="question-even question-area" style="margin-bottom:0px; display:none;" id="q_3380">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你买葡萄酒是为了送人还是自己喝？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span style="display:block" id="err_answers[14976].value" class="error-content"></span>

<input type="hidden" id="answers[14976].id" value="" name="answers[14976].id">
<ul>
	<li>
			<input type="radio" class="selection question_radio_14976" value="12660" name="answers[14976].value" id="14976_0" group="14976">		<label for="14976_0">送人</label>
	</li>
	<li>
			<input type="radio" class="selection question_radio_14976" value="12661" name="answers[14976].value" id="14976_1" group="14976">		<label for="14976_1">自己喝</label>
	</li>
	<li>
			<input type="radio" class="selection question_radio_14976" value="12662" name="answers[14976].value" id="14976_2" group="14976">		<label for="14976_2">都有</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input type="radio" name="answers[14976].value" class="q_14976  qc_0 radio">
</td>
</tr>

  </tbody></table>
<script type="text/javascript" language="JavaScript">

</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

</script>
		  <div class="question-odd question-area" style="margin-bottom:0px; display:none;" id="q_3381">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						如果你会买法国葡萄酒，是由于哪些原因？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span style="display:block" id="err_answers[14977].value" class="error-content"></span>

<input type="hidden" id="answers[14977].id" value="" name="answers[14977].id">




<span id="hint_14977">
</span>
<ul>
	<li>
			<input type="checkbox" onclick=" " value="12663" name="answers[14977].value" id="14977_0" class="question_radio_14977 selection" group="14977">		<label for="14977_0">口味</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12664" name="answers[14977].value" id="14977_1" class="question_radio_14977 selection" group="14977">		<label for="14977_1">产区</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12665" name="answers[14977].value" id="14977_2" class="question_radio_14977 selection" group="14977">		<label for="14977_2">品质</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12666" name="answers[14977].value" id="14977_3" class="question_radio_14977 selection" group="14977">		<label for="14977_3">年份</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12667" name="answers[14977].value" id="14977_4" class="question_radio_14977 selection" group="14977">		<label for="14977_4">名声</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12668" name="answers[14977].value" id="14977_5" class="question_radio_14977 selection" group="14977">		<label for="14977_5">价格</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12669" name="answers[14977].value" id="14977_6" class="question_radio_14977 selection" group="14977">		<label for="14977_6">朋友/家人推荐</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12670" name="answers[14977].value" id="14977_7" class="question_radio_14977 selection" group="14977">		<label for="14977_7">包装/广告</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12671" name="answers[14977].value" id="14977_8" class="question_radio_14977 selection" group="14977">		<label for="14977_8">随便选，碰碰运气</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script type="text/javascript" language="JavaScript">

</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

		 	mandatoryElements.push("14978");

</script>
		  <div class="question-even question-area" style="margin-bottom:0px;" id="q_3382">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						我们将于以下时间在法国领事馆（上海/成都）举行焦点小组现场活动，并且您会得到两瓶葡萄酒。请问你愿意参加吗？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span style="display:block" id="err_answers[14978].value" class="error-content"></span>

<input type="hidden" id="answers[14978].id" value="" name="answers[14978].id">




<span id="hint_14978">
</span>
<ul>
	<li>
			<input type="checkbox" onclick=" " value="12672" name="answers[14978].value" id="14978_0" class="question_radio_14978 selection" group="14978">		<label for="14978_0">愿意，上海，7月6日</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12673" name="answers[14978].value" id="14978_1" class="question_radio_14978 selection" group="14978">		<label for="14978_1">愿意，上海，7月13日</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12674" name="answers[14978].value" id="14978_2" class="question_radio_14978 selection" group="14978">		<label for="14978_2">愿意，成都，7月13日以后（具体待定）</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12675" name="answers[14978].value" id="14978_3" class="question_radio_14978 selection" group="14978">		<label for="14978_3">这几个时间都不方便</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script type="text/javascript" language="JavaScript">

</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

		 	mandatoryElements.push("14979");

</script>
		  <div class="question-odd question-area" style="margin-bottom:0px;" id="q_3383">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你的年龄？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span style="display:block" id="err_answers[14979].value" class="error-content"></span>

<input type="hidden" id="answers[14979].id" value="" name="answers[14979].id">

	<select size="1" title="title" name="answers[14979].value" id="question_14979" class="selection" group="14979">
	<option value="0" selected="selected">请选择</option>
<option style="" value="12676">&lt; 23岁</option>
<option style="" value="12677">23-34 岁</option>
<option style="" value="12678">35-44 岁</option>
<option style="" value="12679">45-60 岁</option>
<option style="" value="12680">&gt;60岁</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script type="text/javascript" language="JavaScript">

</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

		 	mandatoryElements.push("14980");

</script>
		  <div class="question-even question-area" style="margin-bottom:0px;" id="q_3384">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你的性别？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span style="display:block" id="err_answers[14980].value" class="error-content"></span>

<input type="hidden" id="answers[14980].id" value="" name="answers[14980].id">
<ul>
	<li>
			<input type="radio" class="selection question_radio_14980" value="12681" name="answers[14980].value" id="14980_0" group="14980">		<label for="14980_0">女</label>
	</li>
	<li>
			<input type="radio" class="selection question_radio_14980" value="12682" name="answers[14980].value" id="14980_1" group="14980">		<label for="14980_1">男</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script type="text/javascript" language="JavaScript">

</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

		 	mandatoryElements.push("14981");

</script>
		  <div class="question-odd question-area" style="margin-bottom:0px;" id="q_3385">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你的家庭月收入是多少？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span style="display:block" id="err_answers[14981].value" class="error-content"></span>

<input type="hidden" id="answers[14981].id" value="" name="answers[14981].id">

	<select size="1" title="title" name="answers[14981].value" id="question_14981" class="selection" group="14981">
	<option value="0" selected="selected">请选择</option>
<option style="" value="12683">&lt; 5,000/月</option>
<option style="" value="12684">￥5,000～8,000/月</option>
<option style="" value="12685">￥8,000～15,000/月</option>
<option style="" value="12686">￥15,000～20,000/月</option>
<option style="" value="12687">￥20,000～25,000/月</option>
<option style="" value="12688">&gt;25,000/月</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script type="text/javascript" language="JavaScript">

</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

</script>
		  <div class="question-even question-area" style="margin-bottom:0px;" id="q_3386">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你的姓名：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" id="answers[14982].id" value="" name="answers[14982].id">
<input type="text" class="input-text" group="14982" id="question_14982" value="" name="answers[14982].value">

<span id="err_answers[14982].value" class="error-content"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

</script>
		  <div class="question-odd question-area" style="margin-bottom:0px;" id="q_3387">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你的邮箱：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" id="answers[14983].id" value="" name="answers[14983].id">
<input type="text" class="input-text" group="14983" id="question_14983" value="" name="answers[14983].value">

<span id="err_answers[14983].value" class="error-content"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

		 	mandatoryElements.push("14984");

</script>
		  <div class="question-even question-area" style="margin-bottom:0px;" id="q_3388">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你的电话：
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" id="answers[14984].id" value="" name="answers[14984].id">
<input type="text" class="input-text" group="14984" id="question_14984" value="" name="answers[14984].value">

<span id="err_answers[14984].value" class="error-content"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

		 	mandatoryElements.push("14985");

</script>
		  <div class="question-odd question-area" style="margin-bottom:0px;" id="q_2158">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						城市:
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span style="display:block" id="err_answers[14985].value" class="error-content"></span>

<input type="hidden" id="answers[14985].id" value="" name="answers[14985].id">

	<select size="1" title="title" name="answers[14985].value" id="question_14985" class="selection" group="14985">
	<option value="0" selected="selected">请选择</option>
<option style="" value="8315">北京市</option>
<option style="" value="8316">上海市</option>
<option style="" value="8317">广州市</option>
<option style="" value="8318">成都市</option>
<option style="" value="8319">保定市</option>
<option style="" value="8320">鞍山市</option>
<option style="" value="8321">沧州市</option>
<option style="" value="8322">长春市</option>
<option style="" value="8323">长沙市</option>
<option style="" value="8324">常州市</option>
<option style="" value="8325">郴州市</option>
<option style="" value="8326">宝鸡市</option>
<option style="" value="8327">大理市</option>
<option style="" value="8328">大连市</option>
<option style="" value="8329">大庆市</option>
<option style="" value="8330">大同市</option>
<option style="" value="8331">东莞市</option>
<option style="" value="8332">佛山市</option>
<option style="" value="8333">福州市</option>
<option style="" value="8334">抚顺市</option>
<option style="" value="8335">包头市</option>
<option style="" value="8336">贵阳市</option>
<option style="" value="8337">桂林市</option>
<option style="" value="8338">哈尔滨市</option>
<option style="" value="8339">海口市</option>
<option style="" value="8340">杭州市</option>
<option style="" value="8341">合肥市</option>
<option style="" value="8342">衡阳市</option>
<option style="" value="8343">呼和浩特市</option>
<option style="" value="8344">惠州市</option>
<option style="" value="8345">吉林市</option>
<option style="" value="8346">济南市</option>
<option style="" value="8347">嘉兴市</option>
<option style="" value="8348">江门市</option>
<option style="" value="8349">九江市</option>
<option style="" value="8350">开封市</option>
<option style="" value="8351">昆明市</option>
<option style="" value="8352">兰州市</option>
<option style="" value="8353">廊坊市</option>
<option style="" value="8354">连云港市</option>
<option style="" value="8355">洛阳市</option>
<option style="" value="8356">马安山市</option>
<option style="" value="8357">牡丹江市</option>
<option style="" value="8358">南昌市</option>
<option style="" value="8359">南京市</option>
<option style="" value="8360">南宁市</option>
<option style="" value="8361">南通市</option>
<option style="" value="8362">宁波市</option>
<option style="" value="8363">攀枝花市</option>
<option style="" value="8364">平顶山市</option>
<option style="" value="8365">齐齐哈尔</option>
<option style="" value="8366">秦皇岛市</option>
<option style="" value="8367">青岛市</option>
<option style="" value="8368">泉州市</option>
<option style="" value="8369">汕头市</option>
<option style="" value="8370">蚌埠市</option>
<option style="" value="8371">绍兴市</option>
<option style="" value="8372">深圳市</option>
<option style="" value="8373">沈阳市</option>
<option style="" value="8374">石家庄市</option>
<option style="" value="8375">苏州市</option>
<option style="" value="8376">太原市</option>
<option style="" value="8377">泰州市</option>
<option style="" value="8378">唐山市</option>
<option style="" value="8379">天津市</option>
<option style="" value="8380">威海市</option>
<option style="" value="8381">潍坊市</option>
<option style="" value="8382">温州市</option>
<option style="" value="8383">乌鲁木齐市</option>
<option style="" value="8384">无锡市</option>
<option style="" value="8385">芜湖市</option>
<option style="" value="8386">武汉市</option>
<option style="" value="8387">西安市</option>
<option style="" value="8388">西宁市</option>
<option style="" value="8389">厦门市</option>
<option style="" value="8390">新乡市</option>
<option style="" value="8391">徐州市</option>
<option style="" value="8392">烟台市</option>
<option style="" value="8393">延安市</option>
<option style="" value="8394">扬州市</option>
<option style="" value="8395">宜宾市</option>
<option style="" value="8396">银川市</option>
<option style="" value="8397">玉林市</option>
<option style="" value="8398">玉溪市</option>
<option style="" value="8399">湛江市</option>
<option style="" value="8400">漳州市</option>
<option style="" value="8401">镇江市</option>
<option style="" value="8402">郑州市</option>
<option style="" value="8403">中山市</option>
<option style="" value="8404">重庆市</option>
<option style="" value="8405">珠海市</option>
<option style="" value="8406">淄博市</option>
<option style="" value="8407">自贡市</option>
<option style="" value="8408">遵义市</option>
<option style="" value="8409">其他</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script type="text/javascript" language="JavaScript">

</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br>
<div class="fillout-submit">
<input type="button" value="Next Page" onclick="showNextPage();" class="button" id="nextPageButton" style="display: none;">
<input type="submit" value="提交" name="command.submit" class="button" style="" id="submit">
</div>
<table cellspacing="0" cellpadding="0" border="0" style="display:none; margin:15px 20px;" id="web-dialog" class="web-dialog">
	<tbody><tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p class="" id="web-dialog-message-text"></p>
			</div>
			<div id="web-dialog-buttons" class="buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"></td>
		<td height="9" background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"></td>
	</tr>
</tbody></table>

<div style="display:none;" id="mask" class="mask"></div>
<script type="text/javascript" language="JavaScript">

	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top &lt; 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement &amp;&amp; document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined &amp;&amp; msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined &amp;&amp; msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined &amp;&amp; callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}

</script>
</form>
</div> 
<div class="clear"></div>
<br>
</div>

<script type="text/javascript" language="JavaScript">
[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex &gt; pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex <pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "&lt;a href='#' onclick='showPrevPage();'&gt;" + "&lt;-Previous" + "&lt;/a&gt;&amp;nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "&lt;a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'&gt;" + (i) + "&lt;/a&gt;&amp;nbsp;";
	  		  }
	  		}else{
	  		  s += "&lt;a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'&gt;" + (i+1) + "&lt;/a&gt;&amp;nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "&lt;a href='#' onclick='showNextPage();'&gt;" + "Next -&gt;" + "&lt;/a&gt;&amp;nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }

</script>

<script type="text/javascript" language="JavaScript">

    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i<checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}

</script>
<script type="text/javascript" language="JavaScript">

	function loading() {
		var html = "&lt;img src='http://q.xingxinghuo.cn/images/spinner.gif' /&gt;Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length &gt; 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = 'Mandatory questions must be filled out';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = 'Can not submit empty questionnaire form';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer < errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined &amp;&amp; elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i<options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();



</script>
</div>
</div> 
</div>

<div style="display:none;" class="footer">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a target="_blank" href="http://www.ostrakon.org">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a target="_blank" href="/help/index/actionName/c/methodName/c">Help</a> | <a target="_blank" href="http://www.ostrakon.org">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div style="display:none;" class="bottom-shadow"></div>
	<div style="clear: both"></div>
	
</div> 



<!-- 
<div class="content" style="background:#fff;">
<div class="buttons-bar"><a href='/public/profilesurvey'>Back</a>
<div style="clear:both;"></div>

</div>
</div>
 -->

</pre>		<div class="clear"></div>
	</div></div>