
<div class="container">
	<div class="container-inner">

	<script type="text/javascript" language="JavaScript">

	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie < 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length < MAX_LENGTH_OF_COMMENT_QUESTION) {
				// element.next().innerHTML = errorMessage;
				// hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}

	</script>

<script type="text/javascript">

</script>



<div class="main-container-outer">
	<div id="container">
		<!-- <div id="header" class="header">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.88brands.com/" target="_blank">
					<img src="/survey/logoImage/813" style="height:70px; width:301px"> 
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div>  --><!-- header -->
			<div id="nav" class="navigation">
				<div class="nav-left"></div>
				<div class="nav-right"></div>
				<ul>
				</ul>
			</div>	
		
 

			<div style="clear:both;"></div>
			<div class="main-content-outer" id="content">
 		

<div id="content">
	<script language="JavaScript" type="text/javascript">

		mandatoryElements = new Array(); 

	</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

	<div style="margin-top:10px;"></div>

<form onsubmit="return (checkMandatory()&&checkAnswerSet()&&checkCommentAnswers());" action="http://q.xingxinghuo.cn/fillout" method="post" id="fillout">
<div style="display:none" id="mainzone-top-wrapper">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" id="id" value="" name="id">
<input type="hidden" id="theme" value="wildfire" name="theme">
<input type="hidden" value="GqO5tYZHgN4S" name="surveyId">

<div class="mandatory"><span style="color: red;">* </span>- It is mandatory</div>
<div class="page-bar-area">
<span id="pageBar"></span>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0" style="">
<script type="text/javascript" language="JavaScript">

		 	mandatoryElements.push("15061");

</script>
		  <div class="question-even question-area" style="margin-bottom:0px;" id="q_3340">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						请问您听说过以下哪些山地户外运动品牌呢？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span style="display:block" id="err_answers[15061].value" class="error-content"></span>

<input type="hidden" id="answers[15061].id" value="" name="answers[15061].id">




<span id="hint_15061">
</span>
<ul>
	<li>
			<input type="checkbox" onclick=" " value="12556" name="answers[15061].value" id="15061_0" class="question_radio_15061 selection" group="15061">		<label for="15061_0">Columbia 哥伦比亚</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12557" name="answers[15061].value" id="15061_1" class="question_radio_15061 selection" group="15061">		<label for="15061_1">The North Face 乐斯菲斯</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12558" name="answers[15061].value" id="15061_2" class="question_radio_15061 selection" group="15061">		<label for="15061_2">Quechua 趣岳</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12559" name="answers[15061].value" id="15061_3" class="question_radio_15061 selection" group="15061">		<label for="15061_3">Kailas 凯乐石</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12560" name="answers[15061].value" id="15061_4" class="question_radio_15061 selection" group="15061">		<label for="15061_4">Toread 探路者</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12561" name="answers[15061].value" id="15061_5" class="question_radio_15061 selection" group="15061">		<label for="15061_5">Jack Wolfskin 狼爪</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12562" name="answers[15061].value" id="15061_6" class="question_radio_15061 selection" group="15061">		<label for="15061_6">LOWA 洛瓦</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12563" name="answers[15061].value" id="15061_7" class="question_radio_15061 selection" group="15061">		<label for="15061_7">ARCTERYX 始祖鸟</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12564" name="answers[15061].value" id="15061_8" class="question_radio_15061 selection" group="15061">		<label for="15061_8">Black Yak 布来亚克</label>
	</li>
	<li>
			<input type="checkbox" onclick=" " value="12565" name="answers[15061].value" id="15061_9" class="question_radio_15061 selection" group="15061">		<label for="15061_9">GORE-TEX 戈尔特斯</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script type="text/javascript" language="JavaScript">

</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

		 	mandatoryElements.push("15062");

</script>
		  <div class="question-odd question-area" style="margin-bottom:0px;" id="q_3421">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						如果您参加过登山或野营等户外运动，可以分享一些你的经历或感受吗？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" id="answers[15062].id" value="" name="answers[15062].id">
<input class="input-text" rows="12" group="15062" cols="40" id="question_15062" name="answers[15062].value"></input>
<span id="err_answers[15062].value" class="error-content"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

</script>
		  <div class="question-even question-area" style="margin-bottom:0px;" id="q_3363">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						您的微博链接地址可以告诉我们吗？（新浪/腾讯/网易等微博皆可。如果没有微博账号请留白）请正确填写，以免影响结果。
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" id="answers[15066].id" value="" name="answers[15066].id">
<input type="text" class="input-text" group="15066" id="question_15066" value="" name="answers[15066].value">

<span id="err_answers[15066].value" class="error-content"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

		 	mandatoryElements.push("15064");

</script>
		  <div class="question-odd question-area" style="margin-bottom:0px;" id="q_3428">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
			请点击<a href="http://detail.tmall.com/item.htm?spm=a1z10.3.w17-8193795924.130.1QO5dA&id=18707281147&" target="_blank" style="color:red" >此链接</a>查看Quechua的Daypack休闲背包，你觉得它最大的优点是什么呢？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" id="answers[15064].id" value="" name="answers[15064].id">
<input class="input-text" rows="12" group="15064" cols="40" id="question_15064" name="answers[15064].value"></input>
<span id="err_answers[15064].value" class="error-content"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

		 	mandatoryElements.push("15065");

</script>
		  <div class="question-even question-area" style="margin-bottom:0px;" id="q_3429">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						当你的朋友准备购买登山包时，您会向她推荐Daypack休闲背包吗？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span id="err_answers[15065].value" class="error-content"></span>
<input type="hidden" id="answers[15065].id" value="" name="answers[15065].id">
<table>
<tbody><tr>

<td>

<div class="left-label">肯定不会</div>
	<table class="rating-table" style="width:220px !important;">
		<tbody><tr class="radio-line">

					<td class="leftRadio" style="background-color: #ffffff;">
<input type="radio" style="background-color: #ffffff" class="question_radio_15065 rating" group="15065" id="15065_1" value="1" name="answers[15065].value">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" style="background-color: #ffffff" class="question_radio_15065 rating" group="15065" id="15065_2" value="2" name="answers[15065].value">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" style="background-color: #ffffff" class="question_radio_15065 rating" group="15065" id="15065_3" value="3" name="answers[15065].value">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" style="background-color: #ffffff" class="question_radio_15065 rating" group="15065" id="15065_4" value="4" name="answers[15065].value">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" style="background-color: #ffffff" class="question_radio_15065 rating" group="15065" id="15065_5" value="5" name="answers[15065].value">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" style="background-color: #ffffff" class="question_radio_15065 rating" group="15065" id="15065_6" value="6" name="answers[15065].value">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" style="background-color: #ffffff" class="question_radio_15065 rating" group="15065" id="15065_7" value="7" name="answers[15065].value">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" style="background-color: #ffffff" class="question_radio_15065 rating" group="15065" id="15065_8" value="8" name="answers[15065].value">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" style="background-color: #ffffff" class="question_radio_15065 rating" group="15065" id="15065_9" value="9" name="answers[15065].value">
					</td>
					<td class="rightRadio" style="background-color: #ffffff;">
<input type="radio" style="background-color: #ffffff" class="question_radio_15065 rating" group="15065" id="15065_10" value="10" name="answers[15065].value">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</tbody></table> <div class="right-label">肯定会</div>

</td>
<td valign="top" class="noanswer-td">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

		 	mandatoryElements.push("15063");

</script>
		  <div class="question-odd question-area" style="margin-bottom:0px;" id="q_3427">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						请问您远足旅行的频率？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span style="display:block" id="err_answers[15063].value" class="error-content"></span>

<input type="hidden" id="answers[15063].id" value="" name="answers[15063].id">

	<select size="1" title="title" name="answers[15063].value" id="question_15063" class="selection" group="15063">
	<option value="0" selected="selected">请选择</option>
<option style="" value="12776">一年三次以上</option>
<option style="" value="12777">一年两到三次</option>
<option style="" value="12778">一年一次</option>
<option style="" value="12779">不到一年一次</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script type="text/javascript" language="JavaScript">

</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

		 	mandatoryElements.push("15067");

</script>
		  <div class="question-even question-area" style="margin-bottom:0px;" id="q_3406">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						请问您的年龄？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span style="display:block" id="err_answers[15067].value" class="error-content"></span>

<input type="hidden" id="answers[15067].id" value="" name="answers[15067].id">

	<select size="1" title="title" name="answers[15067].value" id="question_15067" class="selection" group="15067">
	<option value="0" selected="selected">请选择</option>
<option style="" value="12722">18岁以下</option>
<option style="" value="12723">18~25岁</option>
<option style="" value="12724">26~35岁</option>
<option style="" value="12725">36~45岁</option>
<option style="" value="12726">45岁以上</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script type="text/javascript" language="JavaScript">

</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

		 	mandatoryElements.push("15068");

</script>
		  <div class="question-odd question-area" style="margin-bottom:0px;" id="q_3430">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						您所在的城市？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span style="display:block" id="err_answers[15068].value" class="error-content"></span>

<input type="hidden" id="answers[15068].id" value="" name="answers[15068].id">

	<select size="1" title="title" name="answers[15068].value" id="question_15068" class="selection" group="15068">
	<option value="0" selected="selected">请选择</option>
<option style="" value="12780">北京市</option>
<option style="" value="12781">上海市</option>
<option style="" value="12782">广州市</option>
<option style="" value="12783">成都市</option>
<option style="" value="12784">保定市</option>
<option style="" value="12785">鞍山市</option>
<option style="" value="12786">沧州市</option>
<option style="" value="12787">长春市</option>
<option style="" value="12788">长沙市</option>
<option style="" value="12789">常州市</option>
<option style="" value="12790">郴州市</option>
<option style="" value="12791">宝鸡市</option>
<option style="" value="12792">大理市</option>
<option style="" value="12793">大连市</option>
<option style="" value="12794">大庆市</option>
<option style="" value="12795">大同市</option>
<option style="" value="12796">东莞市</option>
<option style="" value="12797">佛山市</option>
<option style="" value="12798">福州市</option>
<option style="" value="12799">抚顺市</option>
<option style="" value="12800">包头市</option>
<option style="" value="12801">贵阳市</option>
<option style="" value="12802">桂林市</option>
<option style="" value="12803">哈尔滨市</option>
<option style="" value="12804">海口市</option>
<option style="" value="12805">杭州市</option>
<option style="" value="12806">合肥市</option>
<option style="" value="12807">衡阳市</option>
<option style="" value="12808">呼和浩特市</option>
<option style="" value="12809">惠州市</option>
<option style="" value="12810">吉林市</option>
<option style="" value="12811">济南市</option>
<option style="" value="12812">嘉兴市</option>
<option style="" value="12813">江门市</option>
<option style="" value="12814">九江市</option>
<option style="" value="12815">开封市</option>
<option style="" value="12816">昆明市</option>
<option style="" value="12817">兰州市</option>
<option style="" value="12818">廊坊市</option>
<option style="" value="12819">连云港市</option>
<option style="" value="12820">洛阳市</option>
<option style="" value="12821">马安山市</option>
<option style="" value="12822">牡丹江市</option>
<option style="" value="12823">南昌市</option>
<option style="" value="12824">南京市</option>
<option style="" value="12825">南宁市</option>
<option style="" value="12826">南通市</option>
<option style="" value="12827">宁波市</option>
<option style="" value="12828">攀枝花市</option>
<option style="" value="12829">平顶山市</option>
<option style="" value="12830">齐齐哈尔</option>
<option style="" value="12831">秦皇岛市</option>
<option style="" value="12832">青岛市</option>
<option style="" value="12833">泉州市</option>
<option style="" value="12834">汕头市</option>
<option style="" value="12835">蚌埠市</option>
<option style="" value="12836">绍兴市</option>
<option style="" value="12837">深圳市</option>
<option style="" value="12838">沈阳市</option>
<option style="" value="12839">石家庄市</option>
<option style="" value="12840">苏州市</option>
<option style="" value="12841">太原市</option>
<option style="" value="12842">泰州市</option>
<option style="" value="12843">唐山市</option>
<option style="" value="12844">天津市</option>
<option style="" value="12845">威海市</option>
<option style="" value="12846">潍坊市</option>
<option style="" value="12847">温州市</option>
<option style="" value="12848">乌鲁木齐市</option>
<option style="" value="12849">无锡市</option>
<option style="" value="12850">芜湖市</option>
<option style="" value="12851">武汉市</option>
<option style="" value="12852">西安市</option>
<option style="" value="12853">西宁市</option>
<option style="" value="12854">厦门市</option>
<option style="" value="12855">新乡市</option>
<option style="" value="12856">徐州市</option>
<option style="" value="12857">烟台市</option>
<option style="" value="12858">延安市</option>
<option style="" value="12859">扬州市</option>
<option style="" value="12860">宜宾市</option>
<option style="" value="12861">银川市</option>
<option style="" value="12862">玉林市</option>
<option style="" value="12863">玉溪市</option>
<option style="" value="12864">湛江市</option>
<option style="" value="12865">漳州市</option>
<option style="" value="12866">镇江市</option>
<option style="" value="12867">郑州市</option>
<option style="" value="12868">中山市</option>
<option style="" value="12869">重庆市</option>
<option style="" value="12870">珠海市</option>
<option style="" value="12871">淄博市</option>
<option style="" value="12872">自贡市</option>
<option style="" value="12873">遵义市</option>
<option style="" value="12874">其他</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script type="text/javascript" language="JavaScript">

</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

		 	mandatoryElements.push("15069");

</script>
		  <div class="question-even question-area" style="margin-bottom:0px;" id="q_581">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						您的姓名
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
	<input type="hidden" id="answers[15069].id" value="" name="answers[15069].id">
<?php if(null != $this->user->recipients_name) {?>
<input type="text" class="input-text" group="15069" id="question_15069" value=<?php echo $this->user->recipients_name; ?> name="answers[15069].value">
<?php } else {?>
<input type="text" class="input-text" group="15069" id="question_15069" value="" name="answers[15069].value">
<?php } ?>

<span id="err_answers[15069].value" class="error-content"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

		 	mandatoryElements.push("15070");

</script>
		  <div class="question-odd question-area" style="margin-bottom:0px;" id="q_3431">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						您的性别
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span style="display:block" id="err_answers[15070].value" class="error-content"></span>

<input type="hidden" id="answers[15070].id" value="" name="answers[15070].id">
<?php if(null != $this->user->gender) {?>
	<?php if("male" == $this->user->gender) {?>
		<ul>
			<li>
					<input type="radio" class="selection question_radio_15070" value="12875" name="answers[15070].value" id="15070_0" group="15070" checked>		<label for="15070_0">男</label>
			</li>
			<li>
					<input type="radio" class="selection question_radio_15070" value="12876" name="answers[15070].value" id="15070_1" group="15070">		<label for="15070_1">女</label>
			</li>
		</ul>
		<?php }elseif("female" == $this->user->gender){ ?>
			<ul>
			<li>
					<input type="radio" class="selection question_radio_15070" value="12875" name="answers[15070].value" id="15070_0" group="15070">		<label for="15070_0">男</label>
			</li>
			<li>
					<input type="radio" class="selection question_radio_15070" value="12876" name="answers[15070].value" id="15070_1" group="15070" checked>		<label for="15070_1">女</label>
			</li>
		</ul>
		<?php } ?>
<?php } else {?>
<ul>
		<li>
				<input type="radio" class="selection question_radio_15070" value="12875" name="answers[15070].value" id="15070_0" group="15070">		<label for="15070_0">男</label>
		</li>
		<li>
				<input type="radio" class="selection question_radio_15070" value="12876" name="answers[15070].value" id="15070_1" group="15070">		<label for="15070_1">女</label>
		</li>
	</ul>
<?php }?>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script type="text/javascript" language="JavaScript">

</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">


		 	mandatoryElements.push("15071");

</script>
		  <div class="question-even question-area" style="margin-bottom:0px;" id="q_1710">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						您的Email
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" id="answers[15071].id" value="" name="answers[15071].id">
<?php if(null != $this->user->email) {?>
<input type="text" class="input-text" group="15071" id="question_15071" value=<?php echo $this->user->email; ?> name="answers[15071].value">
<?php } else {?>
<input type="text" class="input-text" group="15071" id="question_15071" value="" name="answers[15071].value">
<?php }?>
<span id="err_answers[15071].value" class="error-content"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script type="text/javascript" language="JavaScript">

		 	mandatoryElements.push("15072");

</script>
		  <div class="question-odd question-area" style="margin-bottom:0px;" id="q_3432">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						您的手机号码
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" id="answers[15072].id" value="" name="answers[15072].id">
<?php if(null != $this->user->login_phone) {?>
<input type="text" class="input-text" group="15072" id="question_15072" value=<?php echo $this->user->login_phone; ?> name="answers[15072].value">
<?php }else {?>
<input type="text" class="input-text" group="15072" id="question_15072" value="" name="answers[15072].value">
<?php }?>
<span id="err_answers[15072].value" class="error-content"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br>
<div class="fillout-submit">
<input type="button" value="Next Page" onclick="showNextPage();" class="button" id="nextPageButton" style="display: none;">
<input type="submit" value="提交" name="command.submit" class="button" style="" id="submit">
</div>
<table border="0" cellspacing="0" cellpadding="0" style="display:none; margin:15px 20px;" id="web-dialog" class="web-dialog">
	<tbody><tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_t.gif"></td>
		<td background="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_t.gif"></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_t.gif"></td>
	</tr>
	<tr>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_m.gif"></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p class="" id="web-dialog-message-text"></p>
			</div>
			<div id="web-dialog-buttons" class="buttons">
			</div>
		</td>
		<td width="9" background="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_m.gif"></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_l_b.gif"></td>
		<td background="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_m_b.gif"></td>
		<td width="9" height="9"><img src="http://q.xingxinghuo.cn/images/web_dialog_r_b.gif"></td>
	</tr>
</tbody></table>

<div style="display:none;" id="mask" class="mask"></div>
<script type="text/javascript" language="JavaScript">

	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}

</script>
</form>
</div> 
<div class="clear"></div>
<br>
</div>

<script type="text/javascript" language="JavaScript">

  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex < pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex <pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "&lt;a href='#' onclick='showPrevPage();'&gt;" + "&lt;-Previous" + "&lt;/a&gt;&amp;nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "&lt;a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'&gt;" + (i) + "&lt;/a&gt;&amp;nbsp;";
	  		  }
	  		}else{
	  		  s += "&lt;a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'&gt;" + (i+1) + "&lt;/a&gt;&amp;nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "&lt;a href='#' onclick='showNextPage();'&gt;" + "Next -&gt;" + "&lt;/a&gt;&amp;nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }

</script>

<script type="text/javascript" language="JavaScript">

    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i<checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}

</script>
<script type="text/javascript" language="JavaScript">

	function loading() {
		var html = "&lt;img src='http://q.xingxinghuo.cn/images/spinner.gif' /&gt;Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    
	    
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
	    	
			if(elements.length < 1) {
				
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
				
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = 'Can not submit empty questionnaire form';
			var buttons = ["OK"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer < errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i<options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  /*var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();*/



</script>
</div>
</div> 
</div>

<div style="display:none;" class="footer">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a target="_blank" href="http://www.ostrakon.org">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a target="_blank" href="/help/index/actionName/c/methodName/c">Help</a> | <a target="_blank" href="http://www.ostrakon.org">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div style="display:none;" class="bottom-shadow"></div>
	<div style="clear: both"></div>
	
</div> 



<!-- 
<div class="content" style="background:#fff;">
<div class="buttons-bar"><a href='/public/profilesurvey'>Back</a>
<div style="clear:both;"></div>

</div>
</div>
 -->

</pre>		<div class="clear"></div>
	</div></div>