<div class="container">
	<div class="container-inner">

	<script type="text/javascript" language="JavaScript">

	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie < 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length < MAX_LENGTH_OF_COMMENT_QUESTION) {
				// element.next().innerHTML = errorMessage;
				// hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}

	</script>

<script type="text/javascript">

</script>



<div class="main-container-outer">
	<div id="container">
		<!-- <div id="header" class="header">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			<div class="main-logo" id="main-logo">
				<a href="http://www.88brands.com/" target="_blank">
					<img src="/survey/logoImage/813" style="height:70px; width:301px"> 
				</a>
			</div>
			<div class="image-banner"></div>
			</div> 
		</div>  --><!-- header -->
			<div id="nav" class="navigation">
				<div class="nav-left"></div>
				<div class="nav-right"></div>
				<ul>
				</ul>
			</div>	
		
 

			<div style="clear:both;"></div>
			<div class="main-content-outer" id="content">
 		

<div id="content">
	<script language="JavaScript" type="text/javascript">

		mandatoryElements = new Array(); 

	</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">Fill out survey</div></div></div></h1>-->
<div class="mainOneContent">

	<div style="margin-top:10px;"></div>


<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="return (loading(); checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">

<!-- <div class="questionnaire-title">社交媒体使用调查</div> -->


<input type="hidden" name="id" value="" id="id">
<input type="hidden" name="theme" value="default" id="theme">
<input type="hidden" name="surveyId" value="836">

<div class="mandatory"><span style="color: red;">* </span>- 必填</div>
<div class="page-bar-area">
<span id="pageBar"></span>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0" style="">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("15198");
// ]]>
-->
</script>
		  <div id="q_3463" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						1.年龄
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15198].value" style="display:block"></span>

<input type="hidden" name="answers[15198].id" value="" id="answers[15198].id">

	<select group="15198" class="selection" id="question_15198" name="answers[15198].value" title="title" size="1">
	<option selected="selected" value="0">请选择</option>
<option value="13011" style="">14~19</option>
<option value="13012" style="">20~29</option>
<option value="13013" style="">30~39</option>
<option value="13014" style="">40~49</option>
<option value="13015" style="">50~64</option>
<option value="13016" style="">65以上</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div><br>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("15199");
// ]]>
-->
</script>
		  <div id="q_3464" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						2.性别
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15199].value" style="display:block"></span>

<input type="hidden" name="answers[15199].id" value="" id="answers[15199].id">
<ul>
	<li>
			<input group="15199" type="radio" id="15199_0" name="answers[15199].value" value="13017" class="selection question_radio_15199">		<label for="15199_0">男</label>
	</li>
	<li>
			<input group="15199" type="radio" id="15199_1" name="answers[15199].value" value="13018" class="selection question_radio_15199">		<label for="15199_1">女</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div><br>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("15200");
// ]]>
-->
</script>
		  <div id="q_3465" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						3.所在城市
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[15200].id" value="" id="answers[15200].id">
<input type="text" name="answers[15200].value" value="" id="question_15200" group="15200" class="input-text">

<span class="error-content" id="err_answers[15200].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div><br>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("15201");
// ]]>
-->
</script>
		  <div id="q_3466" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						4.最常登陆以下哪几个社交媒体？（多选）
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15201].value" style="display:block"></span>

<input type="hidden" name="answers[15201].id" value="" id="answers[15201].id">




<span id="hint_15201">
</span>
<ul>
	<li>
			<input group="15201" class="question_radio_15201 selection" type="checkbox" id="15201_0" name="answers[15201].value" value="13019" onclick=" ">		<label for="15201_0">QQ空间</label>
	</li>
	<li>
			<input group="15201" class="question_radio_15201 selection" type="checkbox" id="15201_1" name="answers[15201].value" value="13020" onclick=" ">		<label for="15201_1">腾讯微博</label>
	</li>
	<li>
			<input group="15201" class="question_radio_15201 selection" type="checkbox" id="15201_2" name="answers[15201].value" value="13021" onclick=" ">		<label for="15201_2">新浪微博</label>
	</li>
	<li>
			<input group="15201" class="question_radio_15201 selection" type="checkbox" id="15201_3" name="answers[15201].value" value="13022" onclick=" ">		<label for="15201_3">豆瓣</label>
	</li>
	<li>
			<input group="15201" class="question_radio_15201 selection" type="checkbox" id="15201_4" name="answers[15201].value" value="13023" onclick=" ">		<label for="15201_4">人人网</label>
	</li>
	<li>
			<input group="15201" class="question_radio_15201 selection" type="checkbox" id="15201_5" name="answers[15201].value" value="13024" onclick=" ">		<label for="15201_5">微信</label>
	</li>
	<li>
			<input group="15201" class="question_radio_15201 selection" type="checkbox" id="15201_6" name="answers[15201].value" value="13025" onclick=" ">		<label for="15201_6">博客</label>
	</li>
		<li>
			<input class="question_radio_15201" type="checkbox" id="15201_other" value="0" onclick="showOtherValueInputInCheckBox(this)">			<label for="15201_other">其他</label>
			<input id="15201_other_input" type="text" name="answers[15201].otherValue" value="" style="display:none;">
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div><br>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("15202");
// ]]>
-->
</script>
		  <div id="q_3467" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						5.上题中使用频率最高的常用社交媒体是哪三个？请由高到低写出，并用空格分隔
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[15202].id" value="" id="answers[15202].id">
<input type="text" name="answers[15202].value" value="" id="question_15202" group="15202" class="input-text">

<span class="error-content" id="err_answers[15202].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div><br>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("15203");
// ]]>
-->
</script>
		  <div id="q_3468" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						6.登陆频率 (包含问题4中所有社交媒体)
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15203].value" style="display:block"></span>

<input type="hidden" name="answers[15203].id" value="" id="answers[15203].id">

	<select group="15203" class="selection" id="question_15203" name="answers[15203].value" title="title" size="1">
	<option selected="selected" value="0">请选择</option>
<option value="13026" style="">每天频繁登陆</option>
<option value="13027" style="">每天至少登陆一次</option>
<option value="13028" style="">每周登陆几次</option>
<option value="13029" style="">少于每周一次</option>
<option value="13030" style="">从不登陆社交媒体</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div><br>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("15204");
// ]]>
-->
</script>
		  <div id="q_3469" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						7.在什么时间登陆社交媒体？（多选）
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15204].value" style="display:block"></span>

<input type="hidden" name="answers[15204].id" value="" id="answers[15204].id">




<span id="hint_15204">
</span>
<ul>
	<li>
			<input group="15204" class="question_radio_15204 selection" type="checkbox" id="15204_0" name="answers[15204].value" value="13031" onclick=" ">		<label for="15204_0">早晨醒来后</label>
	</li>
	<li>
			<input group="15204" class="question_radio_15204 selection" type="checkbox" id="15204_1" name="answers[15204].value" value="13032" onclick=" ">		<label for="15204_1">上下班途中</label>
	</li>
	<li>
			<input group="15204" class="question_radio_15204 selection" type="checkbox" id="15204_2" name="answers[15204].value" value="13033" onclick=" ">		<label for="15204_2">工作中</label>
	</li>
	<li>
			<input group="15204" class="question_radio_15204 selection" type="checkbox" id="15204_3" name="answers[15204].value" value="13034" onclick=" ">		<label for="15204_3">工作间休</label>
	</li>
	<li>
			<input group="15204" class="question_radio_15204 selection" type="checkbox" id="15204_4" name="answers[15204].value" value="13035" onclick=" ">		<label for="15204_4">午餐时间</label>
	</li>
	<li>
			<input group="15204" class="question_radio_15204 selection" type="checkbox" id="15204_5" name="answers[15204].value" value="13036" onclick=" ">		<label for="15204_5">晚上下班后</label>
	</li>
	<li>
			<input group="15204" class="question_radio_15204 selection" type="checkbox" id="15204_6" name="answers[15204].value" value="13037" onclick=" ">		<label for="15204_6">睡觉前</label>
	</li>
	<li>
			<input group="15204" class="question_radio_15204 selection" type="checkbox" id="15204_7" name="answers[15204].value" value="13038" onclick=" ">		<label for="15204_7">周末</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div><br>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("15205");
// ]]>
-->
</script>
		  <div id="q_3470" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						8.在什么场合登陆社交媒体？（多选）
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15205].value" style="display:block"></span>

<input type="hidden" name="answers[15205].id" value="" id="answers[15205].id">




<span id="hint_15205">
</span>
<ul>
	<li>
			<input group="15205" class="question_radio_15205 selection" type="checkbox" id="15205_0" name="answers[15205].value" value="13039" onclick=" ">		<label for="15205_0">家</label>
	</li>
	<li>
			<input group="15205" class="question_radio_15205 selection" type="checkbox" id="15205_1" name="answers[15205].value" value="13040" onclick=" ">		<label for="15205_1">公司</label>
	</li>
	<li>
			<input group="15205" class="question_radio_15205 selection" type="checkbox" id="15205_2" name="answers[15205].value" value="13041" onclick=" ">		<label for="15205_2">旅行中</label>
	</li>
	<li>
			<input group="15205" class="question_radio_15205 selection" type="checkbox" id="15205_3" name="answers[15205].value" value="13042" onclick=" ">		<label for="15205_3">朋友聚餐</label>
	</li>
	<li>
			<input group="15205" class="question_radio_15205 selection" type="checkbox" id="15205_4" name="answers[15205].value" value="13043" onclick=" ">		<label for="15205_4">派对/酒吧</label>
	</li>
	<li>
			<input group="15205" class="question_radio_15205 selection" type="checkbox" id="15205_5" name="answers[15205].value" value="13044" onclick=" ">		<label for="15205_5">咖啡店/下午茶</label>
	</li>
	<li>
			<input group="15205" class="question_radio_15205 selection" type="checkbox" id="15205_6" name="answers[15205].value" value="13045" onclick=" ">		<label for="15205_6">交通工具上</label>
	</li>
		<li>
			<input class="question_radio_15205" type="checkbox" id="15205_other" value="0" onclick="showOtherValueInputInCheckBox(this)">			<label for="15205_other">其他</label>
			<input id="15205_other_input" type="text" name="answers[15205].otherValue" value="" style="display:none;">
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div><br>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("15206");
// ]]>
-->
</script>
		  <div id="q_3471" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						9.用什么设备登陆？ （多选）
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15206].value" style="display:block"></span>

<input type="hidden" name="answers[15206].id" value="" id="answers[15206].id">




<span id="hint_15206">
</span>
<ul>
	<li>
			<input group="15206" class="question_radio_15206 selection" type="checkbox" id="15206_0" name="answers[15206].value" value="13046" onclick=" ">		<label for="15206_0">手机</label>
	</li>
	<li>
			<input group="15206" class="question_radio_15206 selection" type="checkbox" id="15206_1" name="answers[15206].value" value="13047" onclick=" ">		<label for="15206_1">笔记本</label>
	</li>
	<li>
			<input group="15206" class="question_radio_15206 selection" type="checkbox" id="15206_2" name="answers[15206].value" value="13048" onclick=" ">		<label for="15206_2">台式电脑</label>
	</li>
	<li>
			<input group="15206" class="question_radio_15206 selection" type="checkbox" id="15206_3" name="answers[15206].value" value="13049" onclick=" ">		<label for="15206_3">平板电脑</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div><br>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("15207");
// ]]>
-->
</script>
		  <div id="q_3472" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						10.使用社交媒体做什么？（多选）
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15207].value" style="display:block"></span>

<input type="hidden" name="answers[15207].id" value="" id="answers[15207].id">




<span id="hint_15207">
</span>
<ul>
	<li>
			<input group="15207" class="question_radio_15207 selection" type="checkbox" id="15207_0" name="answers[15207].value" value="13050" onclick=" ">		<label for="15207_0">与家人和朋友互动</label>
	</li>
	<li>
			<input group="15207" class="question_radio_15207 selection" type="checkbox" id="15207_1" name="answers[15207].value" value="13051" onclick=" ">		<label for="15207_1">分享图片和视频</label>
	</li>
	<li>
			<input group="15207" class="question_radio_15207 selection" type="checkbox" id="15207_2" name="answers[15207].value" value="13052" onclick=" ">		<label for="15207_2">组织聚会或其他活动</label>
	</li>
	<li>
			<input group="15207" class="question_radio_15207 selection" type="checkbox" id="15207_3" name="answers[15207].value" value="13053" onclick=" ">		<label for="15207_3">了解最新的消息和事件</label>
	</li>
	<li>
			<input group="15207" class="question_radio_15207 selection" type="checkbox" id="15207_4" name="answers[15207].value" value="13054" onclick=" ">		<label for="15207_4">搜索某一品牌或行业</label>
	</li>
	<li>
			<input group="15207" class="question_radio_15207 selection" type="checkbox" id="15207_5" name="answers[15207].value" value="13055" onclick=" ">		<label for="15207_5">搜索娱乐事件</label>
	</li>
	<li>
			<input group="15207" class="question_radio_15207 selection" type="checkbox" id="15207_6" name="answers[15207].value" value="13056" onclick=" ">		<label for="15207_6">玩游戏</label>
	</li>
	<li>
			<input group="15207" class="question_radio_15207 selection" type="checkbox" id="15207_7" name="answers[15207].value" value="13057" onclick=" ">		<label for="15207_7">搜索某个想要购买的产品或服务</label>
	</li>
	<li>
			<input group="15207" class="question_radio_15207 selection" type="checkbox" id="15207_8" name="answers[15207].value" value="13058" onclick=" ">		<label for="15207_8">关注某个品牌以获取评价或促销信息</label>
	</li>
	<li>
			<input group="15207" class="question_radio_15207 selection" type="checkbox" id="15207_9" name="answers[15207].value" value="13059" onclick=" ">		<label for="15207_9">寻找有共同爱好的人</label>
	</li>
	<li>
			<input group="15207" class="question_radio_15207 selection" type="checkbox" id="15207_10" name="answers[15207].value" value="13060" onclick=" ">		<label for="15207_10">结识新的朋友</label>
	</li>
	<li>
			<input group="15207" class="question_radio_15207 selection" type="checkbox" id="15207_11" name="answers[15207].value" value="13061" onclick=" ">		<label for="15207_11">关注一些名人</label>
	</li>
	<li>
			<input group="15207" class="question_radio_15207 selection" type="checkbox" id="15207_12" name="answers[15207].value" value="13062" onclick=" ">		<label for="15207_12">对已购买的产品发表一些评论或博文</label>
	</li>
	<li>
			<input group="15207" class="question_radio_15207 selection" type="checkbox" id="15207_13" name="answers[15207].value" value="13063" onclick=" ">		<label for="15207_13">因为周围人都在用所以才使用的</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div><br>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("15208");
// ]]>
-->
</script>
		  <div id="q_3473" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						11.在社交媒体上搜索哪些产品或服务？（多选）
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15208].value" style="display:block"></span>

<input type="hidden" name="answers[15208].id" value="" id="answers[15208].id">




<span id="hint_15208">
</span>
<ul>
	<li>
			<input group="15208" class="question_radio_15208 selection" type="checkbox" id="15208_0" name="answers[15208].value" value="13064" onclick=" ">		<label for="15208_0">时尚/服装</label>
	</li>
	<li>
			<input group="15208" class="question_radio_15208 selection" type="checkbox" id="15208_1" name="answers[15208].value" value="13065" onclick=" ">		<label for="15208_1">家用电器</label>
	</li>
	<li>
			<input group="15208" class="question_radio_15208 selection" type="checkbox" id="15208_2" name="answers[15208].value" value="13066" onclick=" ">		<label for="15208_2">数码电子</label>
	</li>
	<li>
			<input group="15208" class="question_radio_15208 selection" type="checkbox" id="15208_3" name="answers[15208].value" value="13067" onclick=" ">		<label for="15208_3">化妆品/护肤品</label>
	</li>
	<li>
			<input group="15208" class="question_radio_15208 selection" type="checkbox" id="15208_4" name="answers[15208].value" value="13068" onclick=" ">		<label for="15208_4">音乐</label>
	</li>
	<li>
			<input group="15208" class="question_radio_15208 selection" type="checkbox" id="15208_5" name="answers[15208].value" value="13069" onclick=" ">		<label for="15208_5">电脑游戏</label>
	</li>
	<li>
			<input group="15208" class="question_radio_15208 selection" type="checkbox" id="15208_6" name="answers[15208].value" value="13070" onclick=" ">		<label for="15208_6">家居</label>
	</li>
	<li>
			<input group="15208" class="question_radio_15208 selection" type="checkbox" id="15208_7" name="answers[15208].value" value="13071" onclick=" ">		<label for="15208_7">软件/手机APP</label>
	</li>
	<li>
			<input group="15208" class="question_radio_15208 selection" type="checkbox" id="15208_8" name="answers[15208].value" value="13072" onclick=" ">		<label for="15208_8">电影/视频</label>
	</li>
	<li>
			<input group="15208" class="question_radio_15208 selection" type="checkbox" id="15208_9" name="answers[15208].value" value="13073" onclick=" ">		<label for="15208_9">食品</label>
	</li>
	<li>
			<input group="15208" class="question_radio_15208 selection" type="checkbox" id="15208_10" name="answers[15208].value" value="13074" onclick=" ">		<label for="15208_10">汽车</label>
	</li>
	<li>
			<input group="15208" class="question_radio_15208 selection" type="checkbox" id="15208_11" name="answers[15208].value" value="13075" onclick=" ">		<label for="15208_11">母婴/儿童用品</label>
	</li>
	<li>
			<input group="15208" class="question_radio_15208 selection" type="checkbox" id="15208_12" name="answers[15208].value" value="13076" onclick=" ">		<label for="15208_12">书籍</label>
	</li>
	<li>
			<input group="15208" class="question_radio_15208 selection" type="checkbox" id="15208_13" name="answers[15208].value" value="13100" onclick=" ">		<label for="15208_13">健康/养生</label>
	</li>
	<li>
			<input group="15208" class="question_radio_15208 selection" type="checkbox" id="15208_14" name="answers[15208].value" value="13101" onclick=" ">		<label for="15208_14">酒店</label>
	</li>
	<li>
			<input group="15208" class="question_radio_15208 selection" type="checkbox" id="15208_15" name="answers[15208].value" value="13102" onclick=" ">		<label for="15208_15">旅行</label>
	</li>
	<li>
			<input group="15208" class="question_radio_15208 selection" type="checkbox" id="15208_16" name="answers[15208].value" value="13103" onclick=" ">		<label for="15208_16">品牌</label>
	</li>
	<li>
			<input group="15208" class="question_radio_15208 selection" type="checkbox" id="15208_17" name="answers[15208].value" value="13104" onclick=" ">		<label for="15208_17">餐厅</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div><br>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("15209");
// ]]>
-->
</script>
		  <div id="q_3474" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						12.过去的三个月内，你在社交网络上发布了几条评论/回复？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15209].value" style="display:block"></span>

<input type="hidden" name="answers[15209].id" value="" id="answers[15209].id">

	<select group="15209" class="selection" id="question_15209" name="answers[15209].value" title="title" size="1">
	<option selected="selected" value="0">请选择</option>
<option value="13077" style="">没有发布过</option>
<option value="13078" style="">1~10</option>
<option value="13079" style="">11~20</option>
<option value="13080" style="">21~50</option>
<option value="13081" style="">51~100</option>
<option value="13082" style="">&gt;100</option>
	</select> 
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div><br>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("15210");
// ]]>
-->
</script>
		  <div id="q_3475" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						13.你会评论/回复哪些类型的帖子？（多选）
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15210].value" style="display:block"></span>

<input type="hidden" name="answers[15210].id" value="" id="answers[15210].id">




<span id="hint_15210">
</span>
<ul>
	<li>
			<input group="15210" class="question_radio_15210 selection" type="checkbox" id="15210_0" name="answers[15210].value" value="13083" onclick=" ">		<label for="15210_0">时尚/服装</label>
	</li>
	<li>
			<input group="15210" class="question_radio_15210 selection" type="checkbox" id="15210_1" name="answers[15210].value" value="13084" onclick=" ">		<label for="15210_1">家用电器</label>
	</li>
	<li>
			<input group="15210" class="question_radio_15210 selection" type="checkbox" id="15210_2" name="answers[15210].value" value="13085" onclick=" ">		<label for="15210_2">数码电子</label>
	</li>
	<li>
			<input group="15210" class="question_radio_15210 selection" type="checkbox" id="15210_3" name="answers[15210].value" value="13086" onclick=" ">		<label for="15210_3">化妆品/护肤品</label>
	</li>
	<li>
			<input group="15210" class="question_radio_15210 selection" type="checkbox" id="15210_4" name="answers[15210].value" value="13087" onclick=" ">		<label for="15210_4">音乐</label>
	</li>
	<li>
			<input group="15210" class="question_radio_15210 selection" type="checkbox" id="15210_5" name="answers[15210].value" value="13088" onclick=" ">		<label for="15210_5">电脑游戏</label>
	</li>
	<li>
			<input group="15210" class="question_radio_15210 selection" type="checkbox" id="15210_6" name="answers[15210].value" value="13089" onclick=" ">		<label for="15210_6">家居</label>
	</li>
	<li>
			<input group="15210" class="question_radio_15210 selection" type="checkbox" id="15210_7" name="answers[15210].value" value="13090" onclick=" ">		<label for="15210_7">软件/手机APP</label>
	</li>
	<li>
			<input group="15210" class="question_radio_15210 selection" type="checkbox" id="15210_8" name="answers[15210].value" value="13091" onclick=" ">		<label for="15210_8">电影/视频</label>
	</li>
	<li>
			<input group="15210" class="question_radio_15210 selection" type="checkbox" id="15210_9" name="answers[15210].value" value="13092" onclick=" ">		<label for="15210_9">食品</label>
	</li>
	<li>
			<input group="15210" class="question_radio_15210 selection" type="checkbox" id="15210_10" name="answers[15210].value" value="13093" onclick=" ">		<label for="15210_10">汽车</label>
	</li>
	<li>
			<input group="15210" class="question_radio_15210 selection" type="checkbox" id="15210_11" name="answers[15210].value" value="13105" onclick=" ">		<label for="15210_11">母婴/儿童用品</label>
	</li>
	<li>
			<input group="15210" class="question_radio_15210 selection" type="checkbox" id="15210_12" name="answers[15210].value" value="13106" onclick=" ">		<label for="15210_12">书籍</label>
	</li>
	<li>
			<input group="15210" class="question_radio_15210 selection" type="checkbox" id="15210_13" name="answers[15210].value" value="13107" onclick=" ">		<label for="15210_13">健康/养生</label>
	</li>
	<li>
			<input group="15210" class="question_radio_15210 selection" type="checkbox" id="15210_14" name="answers[15210].value" value="13108" onclick=" ">		<label for="15210_14">酒店</label>
	</li>
	<li>
			<input group="15210" class="question_radio_15210 selection" type="checkbox" id="15210_15" name="answers[15210].value" value="13109" onclick=" ">		<label for="15210_15">旅行</label>
	</li>
	<li>
			<input group="15210" class="question_radio_15210 selection" type="checkbox" id="15210_16" name="answers[15210].value" value="13110" onclick=" ">		<label for="15210_16">品牌</label>
	</li>
	<li>
			<input group="15210" class="question_radio_15210 selection" type="checkbox" id="15210_17" name="answers[15210].value" value="13111" onclick=" ">		<label for="15210_17">餐厅</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div><br>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("15211");
// ]]>
-->
</script>
		  <div id="q_3476" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						14.在社交媒体搜索的产品最终购买可能性有多大？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15211].value"></span>
<input type="hidden" name="answers[15211].id" value="" id="answers[15211].id">
<table>
<tbody><tr>

<td>

<!-- <div class="left-label">不认同</div> -->
	<table class="rating-table">
		<tbody><tr class="radio-line">
<td width="43px;">不认同</td>
					<td style="background-color: #ffffff;" class="leftRadio" width="20px;">
<input type="radio" name="answers[15211].value" value="1" id="15211_1" group="15211" class="question_radio_15211 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" width="20px;">
<input type="radio" name="answers[15211].value" value="2" id="15211_2" group="15211" class="question_radio_15211 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" width="20px;">
<input type="radio" name="answers[15211].value" value="3" id="15211_3" group="15211" class="question_radio_15211 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" width="20px;">
<input type="radio" name="answers[15211].value" value="4" id="15211_4" group="15211" class="question_radio_15211 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio" width="20px;">
<input type="radio" name="answers[15211].value" value="5" id="15211_5" group="15211" class="question_radio_15211 rating" style="background-color: #ffffff">
					</td>
							<td>强烈认同</td>
		</tr>

		<tr class="number">
				<td></td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td></td>
		</tr>
	</tbody></table><!--  <div class="right-label">强烈认同</div> -->

</td>
<td valign="top" class="noanswer-td">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div><br>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
		 	mandatoryElements.push("15212");
// ]]>
-->
</script>
		  <div id="q_3477" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						15.对社交媒体上的广告的看法？（多选）
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15212].value" style="display:block"></span>

<input type="hidden" name="answers[15212].id" value="" id="answers[15212].id">




<span id="hint_15212">
</span>
<ul>
	<li>
			<input group="15212" class="question_radio_15212 selection" type="checkbox" id="15212_0" name="answers[15212].value" value="13094" onclick=" ">		<label for="15212_0">我觉得社交网站上有广告挺好的</label>
	</li>
	<li>
			<input group="15212" class="question_radio_15212 selection" type="checkbox" id="15212_1" name="answers[15212].value" value="13095" onclick=" ">		<label for="15212_1">我从来不关注社交网站上的广告</label>
	</li>
	<li>
			<input group="15212" class="question_radio_15212 selection" type="checkbox" id="15212_2" name="answers[15212].value" value="13096" onclick=" ">		<label for="15212_2">有时会点开社交网站上的广告来了解更多信息</label>
	</li>
	<li>
			<input group="15212" class="question_radio_15212 selection" type="checkbox" id="15212_3" name="answers[15212].value" value="13097" onclick=" ">		<label for="15212_3">我喜欢我在社交网站上关注的行业发的广告</label>
	</li>
	<li>
			<input group="15212" class="question_radio_15212 selection" type="checkbox" id="15212_4" name="answers[15212].value" value="13098" onclick=" ">		<label for="15212_4">我会无视没关注的行业的广告</label>
	</li>
	<li>
			<input group="15212" class="question_radio_15212 selection" type="checkbox" id="15212_5" name="answers[15212].value" value="13099" onclick=" ">		<label for="15212_5">我很讨厌在社交网站上看到广告</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div><br>
	


</div> 
<br>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value="下一页" style="display: none;">
<input id="submit" type="submit" style="" class="button" name="command.submit" value="提交">
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tbody><tr>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_l_t.gif"></td>
		<td height="9" background="http://www.marketing-research.cn/images/web_dialog_m_t.gif"><img src="http://www.marketing-research.cn/images/web_dialog_m_t.gif"></td>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_r_t.gif"></td>
	</tr>
	<tr>
		<td width="9" background="http://www.marketing-research.cn/images/web_dialog_l_m.gif"><img src="http://www.marketing-research.cn/images/web_dialog_l_m.gif"></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://www.marketing-research.cn/images/web_dialog_r_m.gif"><img src="http://www.marketing-research.cn/images/web_dialog_r_m.gif"></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_l_b.gif"></td>
		<td height="9" background="http://www.marketing-research.cn/images/web_dialog_m_b.gif"><img src="http://www.marketing-research.cn/images/web_dialog_m_b.gif"></td>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_r_b.gif"></td>
	</tr>
</tbody></table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">

	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			// var left = (width - this.element.offsetWidth) / 5;
			var top = (height - this.element.offsetHeight) / 5;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = "120px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 120, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			// var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = "150px";
			this.element.style.top = top + "px";
			$('mask').style.height = "100px";
			this.element.style.height = "100px";
			if (width != undefined) {
				this.element.style.width = "250px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}

</script>
</form>

</div> 
<div class="clear"></div>
<br>
</div>

<script type="text/javascript" language="JavaScript">

  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex < pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex <pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	// var _pageBar = document.getElementById("pageBar");
  	// if (pageNum==0) {
  	// 	_pageBar.innerHTML = "";
  	// } else {
	  // 	for (i=0; i<=pageNum; i++) {
			// var s ="";
			// if( i == 0 ) {
			// 	s += "&lt;a href='#' onclick='showPrevPage();'&gt;" + "&lt;-Previous" + "&lt;/a&gt;&amp;nbsp;";
			// }

			// if (noPage0){
	  // 		 if (i!=0){ 
	  // 		 	s += "&lt;a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'&gt;" + (i) + "&lt;/a&gt;&amp;nbsp;";
	  // 		  }
	  // 		}else{
	  // 		  s += "&lt;a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'&gt;" + (i+1) + "&lt;/a&gt;&amp;nbsp;";
	  // 		}
	  		
			// if( i == pageNum ) {
			// 	s+= "&lt;a href='#' onclick='showNextPage();'&gt;" + "Next -&gt;" + "&lt;/a&gt;&amp;nbsp;";
			// }
	  // 		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  // 	}		
  	// }
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }

</script>

<script type="text/javascript" language="JavaScript">

    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i<checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}

</script>
<script type="text/javascript" language="JavaScript">

	function loading() {
		var html = "<img src='http://q.xingxinghuo.cn/images/spinner.gif' />请等待……";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    
	    
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
	    	
			if(elements.length < 1) {
				
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
				
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.type == "radio"){
			  		 for(var i=0;i<elements.length;i++){
				  		if(elements[i].checked){
				  				fillMandatory =  true;
				  				break;
				  		}else{
				  		    fillMandatory =  false;
				  		    continue;
				  		}
			  		}
			  	}
			  	if(element.value.strip() == ''||element.value.strip() == '0') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  } else if (element.hasClassName("rating")){
            for(var i=0;i<elements.length;i++){
				  		if(elements[i].checked){
				  				fillMandatory =  true;
				  				break;
				  		}else{
				  		    fillMandatory =  false;
				  		    continue;
				  		}
			  	}
			  }
			}
	    }
	    
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
				jQuery("#check-alert-dialog .content").html(html);
    			jQuery("#check-alert-dialog").dialog('open');
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = 'Can not submit empty questionnaire form';
			jQuery("#check-alert-dialog .content").html(html);
    		jQuery("#check-alert-dialog").dialog('open');
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer < errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i<options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  /*var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();*/



</script>
</div>
</div> 
</div>

<div style="display:none;" class="footer">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link">
			<p>ostrakon indicate version 2.0</p>
			<p><a target="_blank" href="http://www.ostrakon.org">About Us</a> | <a href="mailto:software@ostrakon.org">Contact Us</a> | <a target="_blank" href="/help/index/actionName/c/methodName/c">Help</a> | <a target="_blank" href="http://www.ostrakon.org">Ostrakon.org</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div style="display:none;" class="bottom-shadow"></div>
	<div style="clear: both"></div>
	
</div> 



<!-- 
<div class="content" style="background:#fff;">
<div class="buttons-bar"><a href='/public/profilesurvey'>Back</a>
<div style="clear:both;"></div><br>

</div>
</div>
 -->

</pre>		<div class="clear"></div>
	</div></div>