
	<script language="JavaScript" type="text/javascript">

		jQuery("#submit").val("提交");
		
		
					jQuery("#web-dialog").hide();
					Element.hide("q_3065");
					Element.hide("q_3066");
					Element.hide("q_3059");

		
	});

	
	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie > 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "您的输入过长";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length > MAX_LENGTH_OF_COMMENT_QUESTION) {
				element.next().innerHTML = errorMessage;
				hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}
	// ]]>
	-->
	</script>
<script language="JavaScript" type="text/javascript">

	 var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-16']);
  _gaq.push(['_setDomainName', '.wildfire.asia']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<style>undefined</style><style>undefined</style><script></script><script id="hp_same_"></script><script id="hp_done_"></script></head>

<body>
<div class="main-container-outer">
	<div id="container">
		<div id="header" class="header">
			<div class="header-left"></div>
			<div class="header-content"><div class="user-info">
			</div></div>
			<div class="header-right"></div><div class="logo">
			
			<div class="image-banner"></div>
			</div> 
		</div> <!-- header -->
		<div id="nav" class="navigation">
			<div class="nav-left"></div>
			<div class="nav-right"></div>
			<ul>
			</ul>
		</div>	
		
 

		<div style="clear:both;"></div>
		<div class="main-content-outer" id="content">
 		

<div id="content">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">填写调查</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="return (checkMandatory() &amp;&amp; checkAnswerSet() &amp;&amp; checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="header_tongzhuang"> <img width="998px" height="170px" src="../images/tongzhuang_header.jpg"> <br></div><div id="mainzone">
<div id="mainzone-inner">

<div class="questionnaire-title" style="display: none;">思佳美儿芮欧2013活动后问卷调查</div>


<input type="hidden" name="id" value="" id="id">
<input type="hidden" name="theme" value="tongzhuang" id="theme">
<input type="hidden" name="surveyId" value="854">

<div class="page-bar-area" style="display: none;">
<span id="pageBar"></span>
<strong class="no-answer">不答</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle">
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0" style="">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div style="font-size:12px;width:95%"><br><br><br></div><div id="q_3271" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						在过去的三个月内您向朋友和家人提到过几次Sergent Major 童装？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[15685].id" value="" id="answers[15685].id">
<input type="text" name="answers[15685].value" value="" id="question_15685" group="15685" class="input-text">

<span class="error-content" id="err_answers[15685].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3272" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你总共向多少人提到过Sergent Major 童装？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[15686].id" value="" id="answers[15686].id">
<input type="text" name="answers[15686].value" value="" id="question_15686" group="15686" class="input-text">

<span class="error-content" id="err_answers[15686].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3273" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						在过去三个月，你曾买过童装吗？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15687].value" style="display:block"></span>

<input type="hidden" name="answers[15687].id" value="" id="answers[15687].id">
<ul>
	<li>
			<input group="15687" type="radio" id="15687_0" name="answers[15687].value" value="12455" class="selection question_radio_15687">		<label for="15687_0">是</label>
	</li>
	<li>
			<input group="15687" type="radio" id="15687_1" name="answers[15687].value" value="12456" class="selection question_radio_15687">		<label for="15687_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
		<input class="q_15687  qc_0 radio" type="radio" name="answers[15687].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3537" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你最近三个月内购买过的童装品牌？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15688].value" style="display:block"></span>

<input type="hidden" name="answers[15688].id" value="" id="answers[15688].id">




<span id="hint_15688">
</span>
<ul>
	<li>
			<input group="15688" class="question_radio_15688 selection" type="checkbox" id="15688_0" name="answers[15688].value" value="13330" onclick=" ">		<label for="15688_0">Sergent Major</label>
	</li>
	<li>
			<input group="15688" class="question_radio_15688 selection" type="checkbox" id="15688_1" name="answers[15688].value" value="13331" onclick=" ">		<label for="15688_1">paw in paw</label>
	</li>
	<li>
			<input group="15688" class="question_radio_15688 selection" type="checkbox" id="15688_2" name="answers[15688].value" value="13332" onclick=" ">		<label for="15688_2">E-land Kids</label>
	</li>
	<li>
			<input group="15688" class="question_radio_15688 selection" type="checkbox" id="15688_3" name="answers[15688].value" value="13333" onclick=" ">		<label for="15688_3">OHHO</label>
	</li>
	<li>
			<input group="15688" class="question_radio_15688 selection" type="checkbox" id="15688_4" name="answers[15688].value" value="13334" onclick=" ">		<label for="15688_4">小木马</label>
	</li>
	<li>
			<input group="15688" class="question_radio_15688 selection" type="checkbox" id="15688_5" name="answers[15688].value" value="13335" onclick=" ">		<label for="15688_5">Tweenie Wennie</label>
	</li>
		<li>
			<input class="question_radio_15688" type="checkbox" id="15688_other" value="0" onclick="showOtherValueInputInCheckBox(this)">			<label for="15688_other">其他</label>
			<input id="15688_other_input" type="text" name="answers[15688].otherValue" value="" style="display:none;">
		</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3275" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						在过去的三个月内您购买童装的频度是？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15689].value" style="display:block"></span>

<input type="hidden" name="answers[15689].id" value="" id="answers[15689].id">
<ul>
	<li>
			<input group="15689" type="radio" id="15689_0" name="answers[15689].value" value="12464" class="selection question_radio_15689">		<label for="15689_0">一次</label>
	</li>
	<li>
			<input group="15689" type="radio" id="15689_1" name="answers[15689].value" value="12465" class="selection question_radio_15689">		<label for="15689_1">每月一次</label>
	</li>
	<li>
			<input group="15689" type="radio" id="15689_2" name="answers[15689].value" value="12466" class="selection question_radio_15689">		<label for="15689_2">每月两次</label>
	</li>
	<li>
			<input group="15689" type="radio" id="15689_3" name="answers[15689].value" value="12467" class="selection question_radio_15689">		<label for="15689_3">每月三次</label>
	</li>
	<li>
			<input group="15689" type="radio" id="15689_4" name="answers[15689].value" value="12468" class="selection question_radio_15689">		<label for="15689_4">每月大于三次</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
		<input class="q_15689  qc_0 radio" type="radio" name="answers[15689].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3538" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						您每次购买童装的金额一般是?
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15690].value" style="display:block"></span>

<input type="hidden" name="answers[15690].id" value="" id="answers[15690].id">
<ul>
	<li>
			<input group="15690" type="radio" id="15690_0" name="answers[15690].value" value="13336" class="selection question_radio_15690">		<label for="15690_0">少于100元</label>
	</li>
	<li>
			<input group="15690" type="radio" id="15690_1" name="answers[15690].value" value="13337" class="selection question_radio_15690">		<label for="15690_1">100元-200 元</label>
	</li>
	<li>
			<input group="15690" type="radio" id="15690_2" name="answers[15690].value" value="13338" class="selection question_radio_15690">		<label for="15690_2">200元-400 元</label>
	</li>
	<li>
			<input group="15690" type="radio" id="15690_3" name="answers[15690].value" value="13339" class="selection question_radio_15690">		<label for="15690_3">400元-600 元</label>
	</li>
	<li>
			<input group="15690" type="radio" id="15690_4" name="answers[15690].value" value="13340" class="selection question_radio_15690">		<label for="15690_4">&gt;600 元</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
		<input class="q_15690  qc_0 radio" type="radio" name="answers[15690].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3277" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						在过去三个月，你一次会买多少件童装？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15691].value" style="display:block"></span>

<input type="hidden" name="answers[15691].id" value="" id="answers[15691].id">
<ul>
	<li>
			<input group="15691" type="radio" id="15691_0" name="answers[15691].value" value="12474" class="selection question_radio_15691">		<label for="15691_0">一件</label>
	</li>
	<li>
			<input group="15691" type="radio" id="15691_1" name="answers[15691].value" value="12475" class="selection question_radio_15691">		<label for="15691_1">两件</label>
	</li>
	<li>
			<input group="15691" type="radio" id="15691_2" name="answers[15691].value" value="12476" class="selection question_radio_15691">		<label for="15691_2">三件</label>
	</li>
	<li>
			<input group="15691" type="radio" id="15691_3" name="answers[15691].value" value="12477" class="selection question_radio_15691">		<label for="15691_3">三件以上</label>
	</li>
	<li>
			<input group="15691" type="radio" id="15691_4" name="answers[15691].value" value="12478" class="selection question_radio_15691">		<label for="15691_4">不一定，跟心情有关</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
		<input class="q_15691  qc_0 radio" type="radio" name="answers[15691].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3278" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你一般在哪里给孩子买童装的呢？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15692].value" style="display:block"></span>

<input type="hidden" name="answers[15692].id" value="" id="answers[15692].id">




<span id="hint_15692">
</span>
<ul>
	<li>
			<input group="15692" class="question_radio_15692 selection" type="checkbox" id="15692_0" name="answers[15692].value" value="12479" onclick=" ">		<label for="15692_0">百盛</label>
	</li>
	<li>
			<input group="15692" class="question_radio_15692 selection" type="checkbox" id="15692_1" name="answers[15692].value" value="12480" onclick=" ">		<label for="15692_1">宝大祥青少年儿童购物中心</label>
	</li>
	<li>
			<input group="15692" class="question_radio_15692 selection" type="checkbox" id="15692_2" name="answers[15692].value" value="12481" onclick=" ">		<label for="15692_2">巴黎春天</label>
	</li>
	<li>
			<input group="15692" class="question_radio_15692 selection" type="checkbox" id="15692_3" name="answers[15692].value" value="12482" onclick=" ">		<label for="15692_3">太平洋</label>
	</li>
	<li>
			<input group="15692" class="question_radio_15692 selection" type="checkbox" id="15692_4" name="answers[15692].value" value="12483" onclick=" ">		<label for="15692_4">汇金</label>
	</li>
	<li>
			<input group="15692" class="question_radio_15692 selection" type="checkbox" id="15692_5" name="answers[15692].value" value="12484" onclick=" ">		<label for="15692_5">东方商场</label>
	</li>
	<li>
			<input group="15692" class="question_radio_15692 selection" type="checkbox" id="15692_6" name="answers[15692].value" value="12485" onclick=" ">		<label for="15692_6">请写出您最经常光顾的商区及商场：</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3539" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						百盛相关门店
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15693].value" style="display:block"></span>

<input type="hidden" name="answers[15693].id" value="" id="answers[15693].id">




<span id="hint_15693">
</span>
<ul>
	<li>
			<input group="15693" class="question_radio_15693 selection" type="checkbox" id="15693_0" name="answers[15693].value" value="13341" onclick=" ">		<label for="15693_0">淮海店</label>
	</li>
	<li>
			<input group="15693" class="question_radio_15693 selection" type="checkbox" id="15693_1" name="answers[15693].value" value="13342" onclick=" ">		<label for="15693_1">莘庄店</label>
	</li>
	<li>
			<input group="15693" class="question_radio_15693 selection" type="checkbox" id="15693_2" name="answers[15693].value" value="13343" onclick=" ">		<label for="15693_2">长宁区天山店</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3540" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						宝大祥青少年儿童购物中心相关门店
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15694].value" style="display:block"></span>

<input type="hidden" name="answers[15694].id" value="" id="answers[15694].id">




<span id="hint_15694">
</span>
<ul>
	<li>
			<input group="15694" class="question_radio_15694 selection" type="checkbox" id="15694_0" name="answers[15694].value" value="13344" onclick=" ">		<label for="15694_0">东南店</label>
	</li>
	<li>
			<input group="15694" class="question_radio_15694 selection" type="checkbox" id="15694_1" name="answers[15694].value" value="13345" onclick=" ">		<label for="15694_1">五角场店</label>
	</li>
	<li>
			<input group="15694" class="question_radio_15694 selection" type="checkbox" id="15694_2" name="answers[15694].value" value="13346" onclick=" ">		<label for="15694_2">96广场</label>
	</li>
	<li>
			<input group="15694" class="question_radio_15694 selection" type="checkbox" id="15694_3" name="answers[15694].value" value="13347" onclick=" ">		<label for="15694_3">七宝店</label>
	</li>
	<li>
			<input group="15694" class="question_radio_15694 selection" type="checkbox" id="15694_4" name="answers[15694].value" value="13348" onclick=" ">		<label for="15694_4">大华店</label>
	</li>
	<li>
			<input group="15694" class="question_radio_15694 selection" type="checkbox" id="15694_5" name="answers[15694].value" value="13349" onclick=" ">		<label for="15694_5">中环店</label>
	</li>
	<li>
			<input group="15694" class="question_radio_15694 selection" type="checkbox" id="15694_6" name="answers[15694].value" value="13350" onclick=" ">		<label for="15694_6">江桥万达店</label>
	</li>
	<li>
			<input group="15694" class="question_radio_15694 selection" type="checkbox" id="15694_7" name="answers[15694].value" value="13351" onclick=" ">		<label for="15694_7">四川北路店</label>
	</li>
	<li>
			<input group="15694" class="question_radio_15694 selection" type="checkbox" id="15694_8" name="answers[15694].value" value="13352" onclick=" ">		<label for="15694_8">莘庄店</label>
	</li>
	<li>
			<input group="15694" class="question_radio_15694 selection" type="checkbox" id="15694_9" name="answers[15694].value" value="13353" onclick=" ">		<label for="15694_9">奥莱店</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3541" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						巴黎春天相关门店
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15695].value" style="display:block"></span>

<input type="hidden" name="answers[15695].id" value="" id="answers[15695].id">




<span id="hint_15695">
</span>
<ul>
	<li>
			<input group="15695" class="question_radio_15695 selection" type="checkbox" id="15695_0" name="answers[15695].value" value="13354" onclick=" ">		<label for="15695_0">虹口店</label>
	</li>
	<li>
			<input group="15695" class="question_radio_15695 selection" type="checkbox" id="15695_1" name="answers[15695].value" value="13355" onclick=" ">		<label for="15695_1">定西路店</label>
	</li>
	<li>
			<input group="15695" class="question_radio_15695 selection" type="checkbox" id="15695_2" name="answers[15695].value" value="13356" onclick=" ">		<label for="15695_2">淮海店</label>
	</li>
	<li>
			<input group="15695" class="question_radio_15695 selection" type="checkbox" id="15695_3" name="answers[15695].value" value="13357" onclick=" ">		<label for="15695_3">五角场</label>
	</li>
	<li>
			<input group="15695" class="question_radio_15695 selection" type="checkbox" id="15695_4" name="answers[15695].value" value="13358" onclick=" ">		<label for="15695_4">浦建店</label>
	</li>
	<li>
			<input group="15695" class="question_radio_15695 selection" type="checkbox" id="15695_5" name="answers[15695].value" value="13359" onclick=" ">		<label for="15695_5">七宝店</label>
	</li>
	<li>
			<input group="15695" class="question_radio_15695 selection" type="checkbox" id="15695_6" name="answers[15695].value" value="13360" onclick=" ">		<label for="15695_6">中山公园</label>
	</li>
	<li>
			<input group="15695" class="question_radio_15695 selection" type="checkbox" id="15695_7" name="answers[15695].value" value="13361" onclick=" ">		<label for="15695_7">长寿路店</label>
	</li>
	<li>
			<input group="15695" class="question_radio_15695 selection" type="checkbox" id="15695_8" name="answers[15695].value" value="13362" onclick=" ">		<label for="15695_8">宝山店生活馆</label>
	</li>
	<li>
			<input group="15695" class="question_radio_15695 selection" type="checkbox" id="15695_9" name="answers[15695].value" value="13363" onclick=" ">		<label for="15695_9">天成店</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3542" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						太平洋相关门店
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15696].value" style="display:block"></span>

<input type="hidden" name="answers[15696].id" value="" id="answers[15696].id">




<span id="hint_15696">
</span>
<ul>
	<li>
			<input group="15696" class="question_radio_15696 selection" type="checkbox" id="15696_0" name="answers[15696].value" value="13364" onclick=" ">		<label for="15696_0">淮海店</label>
	</li>
	<li>
			<input group="15696" class="question_radio_15696 selection" type="checkbox" id="15696_1" name="answers[15696].value" value="13365" onclick=" ">		<label for="15696_1">徐汇店</label>
	</li>
	<li>
			<input group="15696" class="question_radio_15696 selection" type="checkbox" id="15696_2" name="answers[15696].value" value="13366" onclick=" ">		<label for="15696_2">不夜店</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3543" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						汇金相关门店
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15697].value" style="display:block"></span>

<input type="hidden" name="answers[15697].id" value="" id="answers[15697].id">




<span id="hint_15697">
</span>
<ul>
	<li>
			<input group="15697" class="question_radio_15697 selection" type="checkbox" id="15697_0" name="answers[15697].value" value="13367" onclick=" ">		<label for="15697_0">徐汇店</label>
	</li>
	<li>
			<input group="15697" class="question_radio_15697 selection" type="checkbox" id="15697_1" name="answers[15697].value" value="13368" onclick=" ">		<label for="15697_1">虹桥店</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3544" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						东方商场相关门店
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15698].value" style="display:block"></span>

<input type="hidden" name="answers[15698].id" value="" id="answers[15698].id">




<span id="hint_15698">
</span>
<ul>
	<li>
			<input group="15698" class="question_radio_15698 selection" type="checkbox" id="15698_0" name="answers[15698].value" value="13369" onclick=" ">		<label for="15698_0">徐汇店</label>
	</li>
	<li>
			<input group="15698" class="question_radio_15698 selection" type="checkbox" id="15698_1" name="answers[15698].value" value="13370" onclick=" ">		<label for="15698_1">杨浦店</label>
	</li>
	<li>
			<input group="15698" class="question_radio_15698 selection" type="checkbox" id="15698_2" name="answers[15698].value" value="13371" onclick=" ">		<label for="15698_2">南东店</label>
	</li>
	<li>
			<input group="15698" class="question_radio_15698 selection" type="checkbox" id="15698_3" name="answers[15698].value" value="13372" onclick=" ">		<label for="15698_3">奉贤店</label>
	</li>
	<li>
			<input group="15698" class="question_radio_15698 selection" type="checkbox" id="15698_4" name="answers[15698].value" value="13373" onclick=" ">		<label for="15698_4">淮海店</label>
	</li>
	<li>
			<input group="15698" class="question_radio_15698 selection" type="checkbox" id="15698_5" name="answers[15698].value" value="13374" onclick=" ">		<label for="15698_5">嘉定店</label>
	</li>
	<li>
			<input group="15698" class="question_radio_15698 selection" type="checkbox" id="15698_6" name="answers[15698].value" value="13375" onclick=" ">		<label for="15698_6">百联中环店</label>
	</li>
	<li>
			<input group="15698" class="question_radio_15698 selection" type="checkbox" id="15698_7" name="answers[15698].value" value="13376" onclick=" ">		<label for="15698_7">宝山店</label>
	</li>
	<li>
			<input group="15698" class="question_radio_15698 selection" type="checkbox" id="15698_8" name="answers[15698].value" value="13377" onclick=" ">		<label for="15698_8">虹口店</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3536" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						请写出您最经常光顾的商区及商场：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[15699].id" value="" id="answers[15699].id">
<input type="text" name="answers[15699].value" value="" id="question_15699" group="15699" class="input-text">

<span class="error-content" id="err_answers[15699].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3520" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						在未来的三个月里您会购买Sergent Major 童装么？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15700].value"></span>
<input type="hidden" name="answers[15700].id" value="" id="answers[15700].id">
<table>
<tbody><tr>

<td>

<div class="left-label" style="float: left;">一定不会购买</div>
	<table class="rating-table" style="float: left;">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15700].value" value="1" id="15700_1" group="15700" class="question_radio_15700 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15700].value" value="2" id="15700_2" group="15700" class="question_radio_15700 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15700].value" value="3" id="15700_3" group="15700" class="question_radio_15700 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15700].value" value="4" id="15700_4" group="15700" class="question_radio_15700 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15700].value" value="5" id="15700_5" group="15700" class="question_radio_15700 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label" style="float: left;">一定会购买</div>

</td>
<td valign="top" class="noanswer-td" style="display: none;">
<input type="radio" name="answers[15700].value" value="" id="answers[15700].value" class="q_15700 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3523" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
			<div class="questionnaireElementIntroText">
				请对Sergent Major这个品牌所展现的个性评分：
			</div>
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						款式时尚/流行
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15701].value"></span>
<input type="hidden" name="answers[15701].id" value="" id="answers[15701].id">
<table>
<tbody><tr>

<td>

<div class="left-label" style="float: left;">完全不同意</div>
	<table class="rating-table" style="float: left;">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15701].value" value="1" id="15701_1" group="15701" class="question_radio_15701 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15701].value" value="2" id="15701_2" group="15701" class="question_radio_15701 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15701].value" value="3" id="15701_3" group="15701" class="question_radio_15701 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15701].value" value="4" id="15701_4" group="15701" class="question_radio_15701 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15701].value" value="5" id="15701_5" group="15701" class="question_radio_15701 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label" style="float: left;">完全统同意</div>

</td>
<td valign="top" class="noanswer-td" style="display: none;">
<input type="radio" name="answers[15701].value" value="" id="answers[15701].value" class="q_15701 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3524" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						款式齐全选择面广
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15702].value"></span>
<input type="hidden" name="answers[15702].id" value="" id="answers[15702].id">
<table>
<tbody><tr>

<td>

<div class="left-label" style="float: left;">完全不同意</div>
	<table class="rating-table" style="float: left;">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15702].value" value="1" id="15702_1" group="15702" class="question_radio_15702 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15702].value" value="2" id="15702_2" group="15702" class="question_radio_15702 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15702].value" value="3" id="15702_3" group="15702" class="question_radio_15702 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15702].value" value="4" id="15702_4" group="15702" class="question_radio_15702 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15702].value" value="5" id="15702_5" group="15702" class="question_radio_15702 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label" style="float: left;">完全同意</div>

</td>
<td valign="top" class="noanswer-td" style="display: none;">
<input type="radio" name="answers[15702].value" value="" id="answers[15702].value" class="q_15702 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3222" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						衣服质量好，耐穿
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15703].value"></span>
<input type="hidden" name="answers[15703].id" value="" id="answers[15703].id">
<table>
<tbody><tr>

<td>

<div class="left-label" style="float: left;">完全不同意</div>
	<table class="rating-table" style="float: left;">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15703].value" value="1" id="15703_1" group="15703" class="question_radio_15703 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15703].value" value="2" id="15703_2" group="15703" class="question_radio_15703 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15703].value" value="3" id="15703_3" group="15703" class="question_radio_15703 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15703].value" value="4" id="15703_4" group="15703" class="question_radio_15703 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15703].value" value="5" id="15703_5" group="15703" class="question_radio_15703 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label" style="float: left;">完全同意</div>

</td>
<td valign="top" class="noanswer-td" style="display: none;">
<input type="radio" name="answers[15703].value" value="" id="answers[15703].value" class="q_15703 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3223" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						价格实惠
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15704].value"></span>
<input type="hidden" name="answers[15704].id" value="" id="answers[15704].id">
<table>
<tbody><tr>

<td>

<div class="left-label" style="float: left;">完全不同意</div>
	<table class="rating-table" style="float: left;">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15704].value" value="1" id="15704_1" group="15704" class="question_radio_15704 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15704].value" value="2" id="15704_2" group="15704" class="question_radio_15704 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15704].value" value="3" id="15704_3" group="15704" class="question_radio_15704 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15704].value" value="4" id="15704_4" group="15704" class="question_radio_15704 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15704].value" value="5" id="15704_5" group="15704" class="question_radio_15704 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label" style="float: left;">完全同意</div>

</td>
<td valign="top" class="noanswer-td" style="display: none;">
<input type="radio" name="answers[15704].value" value="" id="answers[15704].value" class="q_15704 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3525" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						设计有欧美范
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15705].value"></span>
<input type="hidden" name="answers[15705].id" value="" id="answers[15705].id">
<table>
<tbody><tr>

<td>

<div class="left-label" style="float: left;">完全不同意</div>
	<table class="rating-table" style="float: left;">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15705].value" value="1" id="15705_1" group="15705" class="question_radio_15705 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15705].value" value="2" id="15705_2" group="15705" class="question_radio_15705 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15705].value" value="3" id="15705_3" group="15705" class="question_radio_15705 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15705].value" value="4" id="15705_4" group="15705" class="question_radio_15705 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15705].value" value="5" id="15705_5" group="15705" class="question_radio_15705 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label" style="float: left;">完全同意</div>

</td>
<td valign="top" class="noanswer-td" style="display: none;">
<input type="radio" name="answers[15705].value" value="" id="answers[15705].value" class="q_15705 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3226" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						衣服让小孩感觉舒适
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15706].value"></span>
<input type="hidden" name="answers[15706].id" value="" id="answers[15706].id">
<table>
<tbody><tr>

<td>

<div class="left-label" style="float: left;">完全不同意</div>
	<table class="rating-table" style="float: left;">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15706].value" value="1" id="15706_1" group="15706" class="question_radio_15706 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15706].value" value="2" id="15706_2" group="15706" class="question_radio_15706 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15706].value" value="3" id="15706_3" group="15706" class="question_radio_15706 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15706].value" value="4" id="15706_4" group="15706" class="question_radio_15706 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15706].value" value="5" id="15706_5" group="15706" class="question_radio_15706 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label" style="float: left;">完全同意</div>

</td>
<td valign="top" class="noanswer-td" style="display: none;">
<input type="radio" name="answers[15706].value" value="" id="answers[15706].value" class="q_15706 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3526" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						店铺服务热情得体
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15707].value"></span>
<input type="hidden" name="answers[15707].id" value="" id="answers[15707].id">
<table>
<tbody><tr>

<td>

<div class="left-label" style="float: left;">完全不同意</div>
	<table class="rating-table" style="float: left;">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15707].value" value="1" id="15707_1" group="15707" class="question_radio_15707 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15707].value" value="2" id="15707_2" group="15707" class="question_radio_15707 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15707].value" value="3" id="15707_3" group="15707" class="question_radio_15707 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15707].value" value="4" id="15707_4" group="15707" class="question_radio_15707 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15707].value" value="5" id="15707_5" group="15707" class="question_radio_15707 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label" style="float: left;">完全同意</div>

</td>
<td valign="top" class="noanswer-td" style="display: none;">
<input type="radio" name="answers[15707].value" value="" id="answers[15707].value" class="q_15707 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3527" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						陈列有条理
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15708].value"></span>
<input type="hidden" name="answers[15708].id" value="" id="answers[15708].id">
<table>
<tbody><tr>

<td>

<div class="left-label" style="float: left;">完全不同意</div>
	<table class="rating-table" style="float: left;">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15708].value" value="1" id="15708_1" group="15708" class="question_radio_15708 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15708].value" value="2" id="15708_2" group="15708" class="question_radio_15708 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15708].value" value="3" id="15708_3" group="15708" class="question_radio_15708 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15708].value" value="4" id="15708_4" group="15708" class="question_radio_15708 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15708].value" value="5" id="15708_5" group="15708" class="question_radio_15708 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label" style="float: left;">完全同意</div>

</td>
<td valign="top" class="noanswer-td" style="display: none;">
<input type="radio" name="answers[15708].value" value="" id="answers[15708].value" class="q_15708 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3528" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						店铺充满欧洲风情
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15709].value"></span>
<input type="hidden" name="answers[15709].id" value="" id="answers[15709].id">
<table>
<tbody><tr>

<td>

<div class="left-label" style="float: left;">完全不同意</div>
	<table class="rating-table" style="float: left;">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15709].value" value="1" id="15709_1" group="15709" class="question_radio_15709 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15709].value" value="2" id="15709_2" group="15709" class="question_radio_15709 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15709].value" value="3" id="15709_3" group="15709" class="question_radio_15709 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15709].value" value="4" id="15709_4" group="15709" class="question_radio_15709 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15709].value" value="5" id="15709_5" group="15709" class="question_radio_15709 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label" style="float: left;">完全同意</div>

</td>
<td valign="top" class="noanswer-td" style="display: none;">
<input type="radio" name="answers[15709].value" value="" id="answers[15709].value" class="q_15709 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3521" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						还有其他印象
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[15710].id" value="" id="answers[15710].id">
<input type="text" name="answers[15710].value" value="" id="question_15710" group="15710" class="input-text">

<span class="error-content" id="err_answers[15710].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3294" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						您觉得Sergent Major的会员福利如何？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[15711].id" value="" id="answers[15711].id">
<input type="text" name="answers[15711].value" value="" id="question_15711" group="15711" class="input-text">

<span class="error-content" id="err_answers[15711].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3522" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						您会如何向您的家人，同事，朋友推荐Sergent Major？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15712].value"></span>
<input type="hidden" name="answers[15712].id" value="" id="answers[15712].id">
<table>
<tbody><tr>

<td>

<div class="left-label" style="float: left;">一定不会推荐</div>
	<table class="rating-table" style="float: left;">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15712].value" value="0" id="15712_0" group="15712" class="question_radio_15712 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15712].value" value="1" id="15712_1" group="15712" class="question_radio_15712 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15712].value" value="2" id="15712_2" group="15712" class="question_radio_15712 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15712].value" value="3" id="15712_3" group="15712" class="question_radio_15712 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15712].value" value="4" id="15712_4" group="15712" class="question_radio_15712 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15712].value" value="5" id="15712_5" group="15712" class="question_radio_15712 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15712].value" value="6" id="15712_6" group="15712" class="question_radio_15712 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15712].value" value="7" id="15712_7" group="15712" class="question_radio_15712 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15712].value" value="8" id="15712_8" group="15712" class="question_radio_15712 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15712].value" value="9" id="15712_9" group="15712" class="question_radio_15712 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15712].value" value="10" id="15712_10" group="15712" class="question_radio_15712 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</tbody></table> <div class="right-label" style="float: left;">一定会推荐</div>

</td>
<td valign="top" class="noanswer-td" style="display: none;">
<input type="radio" name="answers[15712].value" value="" id="answers[15712].value" class="q_15712 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3529" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						如果你认为Sergent Major童装值得推荐，那么它必须具备的优点应是什么呢？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[15713].id" value="" id="answers[15713].id">
<textarea name="answers[15713].value" id="question_15713" cols="40" group="15713" rows="2" class="input-text"></textarea>
<span class="error-content" id="err_answers[15713].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3297" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						您愿意Sergent Major和您保持联系么, 你将收到Sergent Major的活动或优惠信息?
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15714].value" style="display:block"></span>

<input type="hidden" name="answers[15714].id" value="" id="answers[15714].id">
<ul>
	<li>
			<input group="15714" type="radio" id="15714_0" name="answers[15714].value" value="12487" class="selection question_radio_15714">		<label for="15714_0">愿意</label>
	</li>
	<li>
			<input group="15714" type="radio" id="15714_1" name="answers[15714].value" value="12488" class="selection question_radio_15714">		<label for="15714_1">不愿意</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td" style="display: none;">
		<input class="q_15714  qc_0 radio" type="radio" name="answers[15714].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3298" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						姓名：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[15715].id" value="" id="answers[15715].id">
<input type="text" name="answers[15715].value" value="" id="question_15715" group="15715" class="input-text">

<span class="error-content" id="err_answers[15715].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3195" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						邮箱：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[15716].id" value="" id="answers[15716].id">
<input type="text" name="answers[15716].value" value="" id="question_15716" group="15716" class="input-text">

<span class="error-content" id="err_answers[15716].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3135" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						电话：
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[15717].id" value="" id="answers[15717].id">
<input type="text" name="answers[15717].value" value="" id="question_15717" group="15717" class="input-text">

<span class="error-content" id="err_answers[15717].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value="下一页" style="display: none;">
<input id="submit" type="submit" style="" class="button" name="command.submit" value="提交">
</div>
<div style="font-size:12px;color:#999;width:95%"><br>隐私声明：我们非常重视对您隐私权的保护。邮件及手机号等个人资料为用户重要隐私，我们承诺不会将个人资料用作它途；承诺不会在未获得用户许可的情况下擅自将用户的个人资料信息出租或出售给任何第三方。如果您对本声明或我们的个人信息处理存在任何疑义，请发送邮件至 home@marketing-research.cn 联系我们。<br><br></div><div id="footer_tongzhuang"></div><table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display: none; margin: 15px 20px;">
	<tbody><tr>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_l_t.gif"></td>
		<td height="9" background="http://www.marketing-research.cn/images/web_dialog_m_t.gif"><img src="http://www.marketing-research.cn/images/web_dialog_m_t.gif"></td>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_r_t.gif"></td>
	</tr>
	<tr>
		<td width="9" background="http://www.marketing-research.cn/images/web_dialog_l_m.gif"><img src="http://www.marketing-research.cn/images/web_dialog_l_m.gif"></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://www.marketing-research.cn/images/web_dialog_r_m.gif"><img src="http://www.marketing-research.cn/images/web_dialog_r_m.gif"></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_l_b.gif"></td>
		<td height="9" background="http://www.marketing-research.cn/images/web_dialog_m_b.gif"><img src="http://www.marketing-research.cn/images/web_dialog_m_b.gif"></td>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_r_b.gif"></td>
	</tr>
</tbody></table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-前页" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "后页->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://www.marketing-research.cn/images/spinner.gif' />请稍候...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目（带*）不能为空';
			var buttons = ["确定"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '不能够提交空表单';
			var buttons = ["确定"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"以后继续"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>

<div class="footer">
	<div class="footer-left"></div>
	<div class="footer-content">
		<div class="footer-logo"></div>
		<div class="footer-link" style="display: none;"> 
			<p></p>
			<p><a href="#" target="_blank">About Us</a> | <a href="http://www.marketing-research.cn" target="_blank">Marketing-Research.cn</a></p>
		</div>
	</div>
	<div class="footer-right"></div>
</div>
	<div class="bottom-shadow"></div>
	<div style="clear: both"></div>
	
</div> 



<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[


	 Element.hide("q_3537");
	 Element.hide("q_3275");
	 Element.hide("q_3538");
	 Element.hide("q_3277");
	 Element.hide("q_3539");
	 Element.hide("q_3540");
	 Element.hide("q_3541");
	 Element.hide("q_3542");
	 Element.hide("q_3543");
	 Element.hide("q_3544");
	 Element.hide("q_3523");
	 Element.hide("q_3524");
	 Element.hide("q_3222");
	 Element.hide("q_3223");
	 Element.hide("q_3525");
	 Element.hide("q_3226");
	 Element.hide("q_3526");
	 Element.hide("q_3527");
	 Element.hide("q_3528");
	 Element.hide("q_3521");
	 Element.hide("q_3294");
	 Element.hide("q_3297");
	 Element.hide("q_3536");


var myrules = {
	   
	   "input#15687_1": function(el){
			el.onclick = function(){
				if ($("15687_1").checked){
						Element.hide($("q_3537"));
						Element.hide($("q_3275"));
						Element.hide($("q_3538"));
						Element.hide($("q_3277"));
				}
			}
		}
	,
	   
	   "input#15687_0": function(el){
			el.onclick = function(){
				if ($("15687_0").checked){
						Element.show($("q_3537"));
						Element.show($("q_3275"));
						Element.show($("q_3538"));
						Element.show($("q_3277"));
				}
			}
		}
}


// ]]>
-->
</script>
<script type="text/javascript" async="" src="http://back.5ihaitao.com/cnzz.js"></script><script type="text/javascript">var vglnk = {api_url: '//api.viglink.com/api', key: '084c74521c465af0d8f08b63422103cc'};</script><script type="text/javxascript" async="" src="http://cdn.viglink.com/api/vglnk.js"></script><div><object id="ClCache" click="sendMsg" host="" width="0" height="0"></object></div></body>