<body>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	mandatoryElements = new Array(); 
// ]]>
-->
</script>
<div class="fillout-container">
<!--<h1><div class="round1"><div class="round2"><div class="round3">填写调查</div></div></div></h1>-->
<div class="mainOneContent">

<div style="margin-top:10px;"></div>
<form id="fillout" method="post" action="http://q.xingxinghuo.cn/fillout" onsubmit="return (checkMandatory() && checkAnswerSet() && checkCommentAnswers());">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">


<input type="hidden" name="id" value="" id="id">
<input type="hidden" name="theme" value="default" id="theme">
<input type="hidden" name="surveyId" value="860">

<div class="page-bar-area">
<span id="pageBar"></span>
<strong class="no-answer">不答</strong><img class="no-answer" src="/images/no_answer.gif" align="absmiddle">
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0" style="">
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3558" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						在过去三个月，你曾买过糖果吗？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15795].value" style="display:block"></span>

<input type="hidden" name="answers[15795].id" value="" id="answers[15795].id">
<ul>
	<li>
			<input group="15795" type="radio" id="15795_0" name="answers[15795].value" value="13386" class="selection question_radio_15795">		<label for="15795_0">是</label>
	</li>
	<li>
			<input group="15795" type="radio" id="15795_1" name="answers[15795].value" value="13387" class="selection question_radio_15795">		<label for="15795_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_15795  qc_0 radio" type="radio" name="answers[15795].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3559" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						在过去三个月，你购买糖果的次数是？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15796].value" style="display:block"></span>

<input type="hidden" name="answers[15796].id" value="" id="answers[15796].id">
<ul>
	<li>
			<input group="15796" type="radio" id="15796_0" name="answers[15796].value" value="13388" class="selection question_radio_15796">		<label for="15796_0">1次</label>
	</li>
	<li>
			<input group="15796" type="radio" id="15796_1" name="answers[15796].value" value="13389" class="selection question_radio_15796">		<label for="15796_1">大约一个月一次</label>
	</li>
	<li>
			<input group="15796" type="radio" id="15796_2" name="answers[15796].value" value="13390" class="selection question_radio_15796">		<label for="15796_2">一个月好几次</label>
	</li>
	<li>
			<input group="15796" type="radio" id="15796_3" name="answers[15796].value" value="13391" class="selection question_radio_15796">		<label for="15796_3">大约一周一次</label>
	</li>
	<li>
			<input group="15796" type="radio" id="15796_4" name="answers[15796].value" value="13392" class="selection question_radio_15796">		<label for="15796_4">一周好几次</label>
	</li>
	<li>
			<input group="15796" type="radio" id="15796_5" name="answers[15796].value" value="13393" class="selection question_radio_15796">		<label for="15796_5">每天</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_15796  qc_0 radio" type="radio" name="answers[15796].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3560" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						平常购买糖果时，一般会花多少钱？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15797].value" style="display:block"></span>

<input type="hidden" name="answers[15797].id" value="" id="answers[15797].id">
<ul>
	<li>
			<input group="15797" type="radio" id="15797_0" name="answers[15797].value" value="13394" class="selection question_radio_15797">		<label for="15797_0">不超过50元</label>
	</li>
	<li>
			<input group="15797" type="radio" id="15797_1" name="answers[15797].value" value="13395" class="selection question_radio_15797">		<label for="15797_1">50-100 RMB</label>
	</li>
	<li>
			<input group="15797" type="radio" id="15797_2" name="answers[15797].value" value="13396" class="selection question_radio_15797">		<label for="15797_2">100-200 RMB</label>
	</li>
	<li>
			<input group="15797" type="radio" id="15797_3" name="answers[15797].value" value="13397" class="selection question_radio_15797">		<label for="15797_3">200-400 RMB</label>
	</li>
	<li>
			<input group="15797" type="radio" id="15797_4" name="answers[15797].value" value="13398" class="selection question_radio_15797">		<label for="15797_4">超过400元</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_15797  qc_0 radio" type="radio" name="answers[15797].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3561" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						一般你在哪里买糖果呢？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15798].value" style="display:block"></span>

<input type="hidden" name="answers[15798].id" value="" id="answers[15798].id">




<span id="hint_15798">
</span>
<ul>
	<li>
			<input group="15798" class="question_radio_15798 selection" type="checkbox" id="15798_0" name="answers[15798].value" value="13399" onclick=" ">		<label for="15798_0">大型超市</label>
	</li>
	<li>
			<input group="15798" class="question_radio_15798 selection" type="checkbox" id="15798_1" name="answers[15798].value" value="13400" onclick=" ">		<label for="15798_1">便利店</label>
	</li>
	<li>
			<input group="15798" class="question_radio_15798 selection" type="checkbox" id="15798_2" name="answers[15798].value" value="13401" onclick=" ">		<label for="15798_2">网上购买</label>
	</li>
	<li>
			<input group="15798" class="question_radio_15798 selection" type="checkbox" id="15798_3" name="answers[15798].value" value="13402" onclick=" ">		<label for="15798_3">其他</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3562" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						这次口碑活动之前，你曾听说过悠漫奶焙糖吗？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15799].value" style="display:block"></span>

<input type="hidden" name="answers[15799].id" value="" id="answers[15799].id">
<ul>
	<li>
			<input group="15799" type="radio" id="15799_0" name="answers[15799].value" value="13403" class="selection question_radio_15799">		<label for="15799_0">是</label>
	</li>
	<li>
			<input group="15799" type="radio" id="15799_1" name="answers[15799].value" value="13404" class="selection question_radio_15799">		<label for="15799_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_15799  qc_0 radio" type="radio" name="answers[15799].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3574" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
			<div class="questionnaireElementIntroText">
				请对悠漫这个品牌所展现的个性评分：
			</div>
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						浓郁的奶香
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15800].value"></span>
<input type="hidden" name="answers[15800].id" value="" id="answers[15800].id">
<table>
<tbody><tr>

<td>

<div class="left-label">完全不同意</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15800].value" value="1" id="15800_1" group="15800" class="question_radio_15800 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15800].value" value="2" id="15800_2" group="15800" class="question_radio_15800 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15800].value" value="3" id="15800_3" group="15800" class="question_radio_15800 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15800].value" value="4" id="15800_4" group="15800" class="question_radio_15800 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15800].value" value="5" id="15800_5" group="15800" class="question_radio_15800 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">完全同意</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[15800].value" value="" id="answers[15800].value" class="q_15800 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3575" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						甜度适中
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15801].value"></span>
<input type="hidden" name="answers[15801].id" value="" id="answers[15801].id">
<table>
<tbody><tr>

<td>

<div class="left-label">完全不同意</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15801].value" value="1" id="15801_1" group="15801" class="question_radio_15801 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15801].value" value="2" id="15801_2" group="15801" class="question_radio_15801 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15801].value" value="3" id="15801_3" group="15801" class="question_radio_15801 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15801].value" value="4" id="15801_4" group="15801" class="question_radio_15801 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15801].value" value="5" id="15801_5" group="15801" class="question_radio_15801 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">完全同意</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[15801].value" value="" id="answers[15801].value" class="q_15801 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3576" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						品质高档
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15802].value"></span>
<input type="hidden" name="answers[15802].id" value="" id="answers[15802].id">
<table>
<tbody><tr>

<td>

<div class="left-label">完全不同意</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15802].value" value="1" id="15802_1" group="15802" class="question_radio_15802 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15802].value" value="2" id="15802_2" group="15802" class="question_radio_15802 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15802].value" value="3" id="15802_3" group="15802" class="question_radio_15802 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15802].value" value="4" id="15802_4" group="15802" class="question_radio_15802 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15802].value" value="5" id="15802_5" group="15802" class="question_radio_15802 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">完全同意</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[15802].value" value="" id="answers[15802].value" class="q_15802 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3577" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						质量比其他品牌的奶糖好
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15803].value"></span>
<input type="hidden" name="answers[15803].id" value="" id="answers[15803].id">
<table>
<tbody><tr>

<td>

<div class="left-label">完全不同意</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15803].value" value="1" id="15803_1" group="15803" class="question_radio_15803 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15803].value" value="2" id="15803_2" group="15803" class="question_radio_15803 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15803].value" value="3" id="15803_3" group="15803" class="question_radio_15803 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15803].value" value="4" id="15803_4" group="15803" class="question_radio_15803 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15803].value" value="5" id="15803_5" group="15803" class="question_radio_15803 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">完全同意</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[15803].value" value="" id="answers[15803].value" class="q_15803 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3578" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						最具性价比的选择
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15804].value"></span>
<input type="hidden" name="answers[15804].id" value="" id="answers[15804].id">
<table>
<tbody><tr>

<td>

<div class="left-label">完全不同意</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15804].value" value="1" id="15804_1" group="15804" class="question_radio_15804 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15804].value" value="2" id="15804_2" group="15804" class="question_radio_15804 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15804].value" value="3" id="15804_3" group="15804" class="question_radio_15804 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15804].value" value="4" id="15804_4" group="15804" class="question_radio_15804 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15804].value" value="5" id="15804_5" group="15804" class="question_radio_15804 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">完全同意</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[15804].value" value="" id="answers[15804].value" class="q_15804 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3579" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						包装很漂亮
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15805].value"></span>
<input type="hidden" name="answers[15805].id" value="" id="answers[15805].id">
<table>
<tbody><tr>

<td>

<div class="left-label">完全不同意</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15805].value" value="1" id="15805_1" group="15805" class="question_radio_15805 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15805].value" value="2" id="15805_2" group="15805" class="question_radio_15805 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15805].value" value="3" id="15805_3" group="15805" class="question_radio_15805 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15805].value" value="4" id="15805_4" group="15805" class="question_radio_15805 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15805].value" value="5" id="15805_5" group="15805" class="question_radio_15805 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">完全同意</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[15805].value" value="" id="answers[15805].value" class="q_15805 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3569" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						在未来三个月，你愿意购买悠漫奶焙糖吗？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15806].value"></span>
<input type="hidden" name="answers[15806].id" value="" id="answers[15806].id">
<table>
<tbody><tr>

<td>

<div class="left-label">肯定不会买</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15806].value" value="1" id="15806_1" group="15806" class="question_radio_15806 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15806].value" value="2" id="15806_2" group="15806" class="question_radio_15806 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15806].value" value="3" id="15806_3" group="15806" class="question_radio_15806 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15806].value" value="4" id="15806_4" group="15806" class="question_radio_15806 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15806].value" value="5" id="15806_5" group="15806" class="question_radio_15806 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">肯定会买</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[15806].value" value="" id="answers[15806].value" class="q_15806 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3570" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你会向亲友或同事推荐悠漫奶焙糖吗？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[15807].value"></span>
<input type="hidden" name="answers[15807].id" value="" id="answers[15807].id">
<table>
<tbody><tr>

<td>

<div class="left-label">肯定不会</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[15807].value" value="0" id="15807_0" group="15807" class="question_radio_15807 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15807].value" value="1" id="15807_1" group="15807" class="question_radio_15807 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15807].value" value="2" id="15807_2" group="15807" class="question_radio_15807 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15807].value" value="3" id="15807_3" group="15807" class="question_radio_15807 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15807].value" value="4" id="15807_4" group="15807" class="question_radio_15807 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15807].value" value="5" id="15807_5" group="15807" class="question_radio_15807 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15807].value" value="6" id="15807_6" group="15807" class="question_radio_15807 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15807].value" value="7" id="15807_7" group="15807" class="question_radio_15807 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15807].value" value="8" id="15807_8" group="15807" class="question_radio_15807 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[15807].value" value="9" id="15807_9" group="15807" class="question_radio_15807 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[15807].value" value="10" id="15807_10" group="15807" class="question_radio_15807 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</tbody></table> <div class="right-label">肯定会</div>

</td>
<td valign="top" class="noanswer-td">
<input type="radio" name="answers[15807].value" value="" id="answers[15807].value" class="q_15807 qc_0 radio">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3571" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你曾吃过其他品牌的牛奶糖吗?
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[15808].value" style="display:block"></span>

<input type="hidden" name="answers[15808].id" value="" id="answers[15808].id">
<ul>
	<li>
			<input group="15808" type="radio" id="15808_0" name="answers[15808].value" value="13405" class="selection question_radio_15808">		<label for="15808_0">是</label>
	</li>
	<li>
			<input group="15808" type="radio" id="15808_1" name="answers[15808].value" value="13406" class="selection question_radio_15808">		<label for="15808_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
		<input class="q_15808  qc_0 radio" type="radio" name="answers[15808].value">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	
// ]]>
-->
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3572" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你认为悠漫奶焙糖和其他品牌的奶糖有什么区别？
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[15809].id" value="" id="answers[15809].id">
<input type="text" name="answers[15809].value" value="" id="question_15809" group="15809" class="input-text">

<span class="error-content" id="err_answers[15809].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_2088" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						姓名:
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[15810].id" value="" id="answers[15810].id">
<input type="text" name="answers[15810].value" value="" id="question_15810" group="15810" class="input-text">

<span class="error-content" id="err_answers[15810].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3573" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						E-mail:
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[15811].id" value="" id="answers[15811].id">
<input type="text" name="answers[15811].value" value="" id="question_15811" group="15811" class="input-text">

<span class="error-content" id="err_answers[15811].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
// ]]>
-->
</script>
		  <div id="q_3330" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						电话号码:
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[15812].id" value="" id="answers[15812].id">
<input type="text" name="answers[15812].value" value="" id="question_15812" group="15812" class="input-text">

<span class="error-content" id="err_answers[15812].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value='ccc Page' />
<input id="submit" type="submit" style="display:none" class="button" name="command.submit" value="提交" />
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tbody><tr>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_l_t.gif"></td>
		<td height="9" background="http://www.marketing-research.cn/images/web_dialog_m_t.gif"><img src="http://www.marketing-research.cn/images/web_dialog_m_t.gif"></td>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_r_t.gif"></td>
	</tr>
	<tr>
		<td width="9" background="http://www.marketing-research.cn/images/web_dialog_l_m.gif"><img src="http://www.marketing-research.cn/images/web_dialog_l_m.gif"></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://www.marketing-research.cn/images/web_dialog_r_m.gif"><img src="http://www.marketing-research.cn/images/web_dialog_r_m.gif"></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_l_b.gif"></td>
		<td height="9" background="http://www.marketing-research.cn/images/web_dialog_m_b.gif"><img src="http://www.marketing-research.cn/images/web_dialog_m_b.gif"></td>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_r_b.gif"></td>
	</tr>
</tbody></table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>
</div> 
<div class="clear"></div>
<br>
</div>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex > pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex < pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	var _pageBar = document.getElementById("pageBar");
  	if (pageNum==0) {
  		_pageBar.innerHTML = "";
  	} else {
	  	for (i=0; i<=pageNum; i++) {
			var s ="";
			if( i == 0 ) {
				s += "<a href='#' onclick='showPrevPage();'>" + "<-前页" + "</a>&nbsp;";
			}

			if (noPage0){
	  		 if (i!=0){ 
	  		 	s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i) + "</a>&nbsp;";
	  		  }
	  		}else{
	  		  s += "<a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'>" + (i+1) + "</a>&nbsp;";
	  		}
	  		
			if( i == pageNum ) {
				s+= "<a href='#' onclick='showNextPage();'>" + "后页->" + "</a>&nbsp;";
			}
	  		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  	}		
  	}
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }
// ]]>
-->
</script>

<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i < checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}
// ]]>
-->
</script>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	function loading() {
		var html = "<img src='http://www.marketing-research.cn/images/spinner.gif' />请稍候...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
			if(elements.length > 1) {
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	if(element.value.strip() == '') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  }
			}
	    }
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目（带*）不能为空';
			jQuery("#check-alert-dialog .content").html(html);
   			jQuery("#check-alert-dialog").dialog('open');
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '不能够提交空表单';
			jQuery("#check-alert-dialog .content").html(html);
    		jQuery("#check-alert-dialog").dialog('open');
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer<errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i < options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"以后继续"}
		});
		}, 5);
	*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


	
// ]]>
-->
</script>
</div>
</div> 
</div>


	
</div> 



<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[


	 Element.hide("q_3559");
	 Element.hide("q_3560");
	 Element.hide("q_3561");
	 Element.hide("q_3574");
	 Element.hide("q_3575");
	 Element.hide("q_3576");
	 Element.hide("q_3577");
	 Element.hide("q_3578");
	 Element.hide("q_3579");
	 Element.hide("q_3571");
	 Element.hide("q_3572");


var myrules = {
	   
	   "input#15808_1": function(el){
			el.onclick = function(){
				if ($("15808_1").checked){
						Element.hide($("q_3572"));
				}
			}
		}
	,
	   
	   "input#15799_1": function(el){
			el.onclick = function(){
				if ($("15799_1").checked){
						Element.hide($("q_3574"));
						Element.hide($("q_3575"));
						Element.hide($("q_3576"));
						Element.hide($("q_3577"));
						Element.hide($("q_3578"));
						Element.hide($("q_3579"));
						Element.hide($("q_3571"));
						Element.hide($("q_3572"));
				}
			}
		}
	,
	   
	   "input#15808_0": function(el){
			el.onclick = function(){
				if ($("15808_0").checked){
						Element.show($("q_3572"));
				}
			}
		}
	,
	   
	   "input#15795_0": function(el){
			el.onclick = function(){
				if ($("15795_0").checked){
						Element.show($("q_3559"));
						Element.show($("q_3560"));
						Element.show($("q_3561"));
				}
			}
		}
	,
	   
	   "input#15799_0": function(el){
			el.onclick = function(){
				if ($("15799_0").checked){
						Element.show($("q_3574"));
						Element.show($("q_3575"));
						Element.show($("q_3576"));
						Element.show($("q_3577"));
						Element.show($("q_3578"));
						Element.show($("q_3579"));
						Element.show($("q_3571"));
				}
			}
		}
	,
	   
	   "input#15795_1": function(el){
			el.onclick = function(){
				if ($("15795_1").checked){
						Element.hide($("q_3559"));
						Element.hide($("q_3560"));
						Element.hide($("q_3561"));
				}
			}
		}
}

Behaviour.register(myrules);


// ]]>
-->
</script>
</body>