<div class="container">
	<div class="container-inner">

	<script type="text/javascript" language="JavaScript">

	function msieversion() {
		var ua = window.navigator.userAgent
		var msie = ua.indexOf ( "MSIE " )
		if ( msie < 0 )      // If Internet Explorer, return version number
		   return parseInt (ua.substring (msie+5, ua.indexOf (".", msie )))
		else                 // If another browser, return 0
		   return 0
	}
	var MAX_LENGTH_OF_COMMENT_QUESTION = 100000;
	function checkCommentAnswers() {
		var errorMessage = "Your input is too long";
		var hasError = false;
		$$('input.input-text').each(function(element) {
			var value = element.value;
			if( value.length < MAX_LENGTH_OF_COMMENT_QUESTION) {
				// element.next().innerHTML = errorMessage;
				// hasError = true;
			}
		});
		if( hasError ) {
			locateErrorPage();
		}
		return !hasError;
	}

	</script>

<script type="text/javascript">

</script>



<div class="main-container-outer">
	<div id="container">
			<div id="nav" class="navigation">
				<div class="nav-left"></div>
				<div class="nav-right"></div>
				<ul>
				</ul>
			</div>	
		
 

			<div style="clear:both;"></div>
			<div class="main-content-outer" id="content">
 		

<div id="content">
	<script language="JavaScript" type="text/javascript">

		mandatoryElements = new Array(); 

	</script>
<div class="fillout-container">
<div class="mainOneContent">

	<div style="margin-top:10px;"></div>

<form onsubmit="return (checkMandatory()&&checkAnswerSet()&&checkCommentAnswers());" action="http://q.xingxinghuo.cn/fillout" method="post" id="fillout">
<div id="mainzone-top-wrapper" style="display:none">
  <div id="mainzone-top-left">
    <div id="mainzone-top-right"></div>
  </div>
</div>
<div id="mainzone">
<div id="mainzone-inner">

<input type="hidden" name="id" value="" id="id">
<input type="hidden" name="theme" value="youman" id="theme">
<input type="hidden" name="surveyId" value="892">

<div class="mandatory"><span style="color: red;">* </span>- 必填</div>
<div class="page-bar-area">
<span id="pageBar"></span>
<div class="clear"></div>
</div>
<div class="clear"></div>


	
	<div id="page_0" style="">
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16474");
</script>
		  <div id="q_3687" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						在过去三个月，你买过奶糖吗？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[16474].value" style="display:block"></span>

<input type="hidden" name="answers[16474].id" value="" id="answers[16474].id">
<ul>
	<li>
			<input group="16474" type="radio" id="16474_0" name="answers[16474].value" value="13855" class="selection question_radio_16474">		<label for="16474_0">是</label>
	</li>
	<li>
			<input group="16474" type="radio" id="16474_1" name="answers[16474].value" value="13856" class="selection question_radio_16474">		<label for="16474_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16475");
</script>
		  <div id="q_3688" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						在过去三个月，你购买奶糖的次数是？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[16475].value" style="display:block"></span>

<input type="hidden" name="answers[16475].id" value="" id="answers[16475].id">
<ul>
	<li>
			<input group="16475" type="radio" id="16475_0" name="answers[16475].value" value="13857" class="selection question_radio_16475">		<label for="16475_0">1次</label>
	</li>
	<li>
			<input group="16475" type="radio" id="16475_1" name="answers[16475].value" value="13858" class="selection question_radio_16475">		<label for="16475_1">大约一个月一次</label>
	</li>
	<li>
			<input group="16475" type="radio" id="16475_2" name="answers[16475].value" value="13859" class="selection question_radio_16475">		<label for="16475_2">一个月好几次</label>
	</li>
	<li>
			<input group="16475" type="radio" id="16475_3" name="answers[16475].value" value="13860" class="selection question_radio_16475">		<label for="16475_3">大约一周一次</label>
	</li>
	<li>
			<input group="16475" type="radio" id="16475_4" name="answers[16475].value" value="13861" class="selection question_radio_16475">		<label for="16475_4">一周好几次</label>
	</li>
	<li>
			<input group="16475" type="radio" id="16475_5" name="answers[16475].value" value="13862" class="selection question_radio_16475">		<label for="16475_5">每天</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16476");
</script>
		  <div id="q_3689" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						平常购买奶糖时，一般会花多少钱？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[16476].value" style="display:block"></span>

<input type="hidden" name="answers[16476].id" value="" id="answers[16476].id">
<ul>
	<li>
			<input group="16476" type="radio" id="16476_0" name="answers[16476].value" value="13863" class="selection question_radio_16476">		<label for="16476_0">不超过5元</label>
	</li>
	<li>
			<input group="16476" type="radio" id="16476_1" name="answers[16476].value" value="13864" class="selection question_radio_16476">		<label for="16476_1">5-20元</label>
	</li>
	<li>
			<input group="16476" type="radio" id="16476_2" name="answers[16476].value" value="13865" class="selection question_radio_16476">		<label for="16476_2">20-50元</label>
	</li>
	<li>
			<input group="16476" type="radio" id="16476_3" name="answers[16476].value" value="13866" class="selection question_radio_16476">		<label for="16476_3">50-100元</label>
	</li>
	<li>
			<input group="16476" type="radio" id="16476_4" name="answers[16476].value" value="13867" class="selection question_radio_16476">		<label for="16476_4">100元以上</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16477");
</script>
		  <div id="q_3690" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						一般你在哪里买奶糖呢？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[16477].value" style="display:block"></span>

<input type="hidden" name="answers[16477].id" value="" id="answers[16477].id">




<span id="hint_16477">
</span>
<ul>
	<li>
			<input group="16477" class="question_radio_16477 selection" type="checkbox" id="16477_0" name="answers[16477].value" value="13868" onclick=" ">		<label for="16477_0">大卖场</label>
	</li>
	<li>
			<input group="16477" class="question_radio_16477 selection" type="checkbox" id="16477_1" name="answers[16477].value" value="13869" onclick=" ">		<label for="16477_1">超市</label>
	</li>
	<li>
			<input group="16477" class="question_radio_16477 selection" type="checkbox" id="16477_2" name="answers[16477].value" value="13870" onclick=" ">		<label for="16477_2">便利店</label>
	</li>
	<li>
			<input group="16477" class="question_radio_16477 selection" type="checkbox" id="16477_3" name="answers[16477].value" value="13871" onclick=" ">		<label for="16477_3">网上购买</label>
	</li>
	<li>
			<input group="16477" class="question_radio_16477 selection" type="checkbox" id="16477_4" name="answers[16477].value" value="13872" onclick=" ">		<label for="16477_4">其他</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16478");
</script>
		  <div id="q_3379" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						其他地方：
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[16478].id" value="" id="answers[16478].id">
<input type="text" name="answers[16478].value" value="" id="question_16478" group="16478" class="input-text">

<span class="error-content" id="err_answers[16478].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16479");
</script>
		  <div id="q_3691" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						这次口碑活动之前，你曾通过哪些渠道听说或接触过悠漫奶焙糖？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[16479].value" style="display:block"></span>

<input type="hidden" name="answers[16479].id" value="" id="answers[16479].id">




<span id="hint_16479">
</span>
<ul>
	<li>
			<input group="16479" class="question_radio_16479 selection" type="checkbox" id="16479_0" name="answers[16479].value" value="13873" onclick=" ">		<label for="16479_0">电视广告</label>
	</li>
	<li>
			<input group="16479" class="question_radio_16479 selection" type="checkbox" id="16479_1" name="answers[16479].value" value="13874" onclick=" ">		<label for="16479_1">商店/超市货架</label>
	</li>
	<li>
			<input group="16479" class="question_radio_16479 selection" type="checkbox" id="16479_2" name="answers[16479].value" value="13875" onclick=" ">		<label for="16479_2">户外广告</label>
	</li>
	<li>
			<input group="16479" class="question_radio_16479 selection" type="checkbox" id="16479_3" name="answers[16479].value" value="13876" onclick=" ">		<label for="16479_3">网络</label>
	</li>
	<li>
			<input group="16479" class="question_radio_16479 selection" type="checkbox" id="16479_4" name="answers[16479].value" value="13877" onclick=" ">		<label for="16479_4">其它(请详述)</label>
	</li>
	<li>
			<input group="16479" class="question_radio_16479 selection" type="checkbox" id="16479_5" name="answers[16479].value" value="13878" onclick=" ">		<label for="16479_5">没有接触过</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16480");
</script>
		  <div id="q_3662" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						其他渠道：
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[16480].id" value="" id="answers[16480].id">
<input type="text" name="answers[16480].value" value="" id="question_16480" group="16480" class="input-text">

<span class="error-content" id="err_answers[16480].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16481");
</script>
		  <div id="q_3692" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						那么有哪些内容曾引起了你的注意，让你印象深刻？（例如广告内容、店内货架陈列、网络讨论等等）
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[16481].id" value="" id="answers[16481].id">
<input type="text" name="answers[16481].value" value="" id="question_16481" group="16481" class="input-text">

<span class="error-content" id="err_answers[16481].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16482");
</script>
		  <div id="q_3693" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						这次口碑活动之前，你尝过悠漫奶焙糖吗？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[16482].value" style="display:block"></span>

<input type="hidden" name="answers[16482].id" value="" id="answers[16482].id">
<ul>
	<li>
			<input group="16482" type="radio" id="16482_0" name="answers[16482].value" value="13879" class="selection question_radio_16482">		<label for="16482_0">是</label>
	</li>
	<li>
			<input group="16482" type="radio" id="16482_1" name="answers[16482].value" value="13880" class="selection question_radio_16482">		<label for="16482_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16483");
</script>
		  <div id="q_3694" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
			<div class="questionnaireElementIntroText" style="height:24px">
				以下对悠漫奶焙糖的描述， 你是否同意？
			</div>
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						美味的
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[16483].value"></span>
<input type="hidden" name="answers[16483].id" value="" id="answers[16483].id">
<table>
<tbody><tr>

<td>

<div class="left-label">完全不同意</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[16483].value" value="1" id="16483_1" group="16483" class="question_radio_16483 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16483].value" value="2" id="16483_2" group="16483" class="question_radio_16483 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16483].value" value="3" id="16483_3" group="16483" class="question_radio_16483 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16483].value" value="4" id="16483_4" group="16483" class="question_radio_16483 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[16483].value" value="5" id="16483_5" group="16483" class="question_radio_16483 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">完全同意</div>

</td>
<td valign="top" class="noanswer-td">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16484");
</script>
		  <div id="q_3695" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						有浓醇的牛奶味道
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[16484].value"></span>
<input type="hidden" name="answers[16484].id" value="" id="answers[16484].id">
<table>
<tbody><tr>

<td>

<div class="left-label">完全不同意</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[16484].value" value="1" id="16484_1" group="16484" class="question_radio_16484 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16484].value" value="2" id="16484_2" group="16484" class="question_radio_16484 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16484].value" value="3" id="16484_3" group="16484" class="question_radio_16484 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16484].value" value="4" id="16484_4" group="16484" class="question_radio_16484 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[16484].value" value="5" id="16484_5" group="16484" class="question_radio_16484 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">完全同意</div>

</td>
<td valign="top" class="noanswer-td">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16485");
</script>
		  <div id="q_3575" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						甜度适中
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[16485].value"></span>
<input type="hidden" name="answers[16485].id" value="" id="answers[16485].id">
<table>
<tbody><tr>

<td>

<div class="left-label">完全不同意</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[16485].value" value="1" id="16485_1" group="16485" class="question_radio_16485 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16485].value" value="2" id="16485_2" group="16485" class="question_radio_16485 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16485].value" value="3" id="16485_3" group="16485" class="question_radio_16485 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16485].value" value="4" id="16485_4" group="16485" class="question_radio_16485 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[16485].value" value="5" id="16485_5" group="16485" class="question_radio_16485 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">完全同意</div>

</td>
<td valign="top" class="noanswer-td">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16486");
</script>
		  <div id="q_3696" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						正宗的、纯正的
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[16486].value"></span>
<input type="hidden" name="answers[16486].id" value="" id="answers[16486].id">
<table>
<tbody><tr>

<td>

<div class="left-label">完全不同意</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[16486].value" value="1" id="16486_1" group="16486" class="question_radio_16486 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16486].value" value="2" id="16486_2" group="16486" class="question_radio_16486 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16486].value" value="3" id="16486_3" group="16486" class="question_radio_16486 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16486].value" value="4" id="16486_4" group="16486" class="question_radio_16486 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[16486].value" value="5" id="16486_5" group="16486" class="question_radio_16486 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">完全同意</div>

</td>
<td valign="top" class="noanswer-td">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16487");
</script>
		  <div id="q_3697" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						高档的
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[16487].value"></span>
<input type="hidden" name="answers[16487].id" value="" id="answers[16487].id">
<table>
<tbody><tr>

<td>

<div class="left-label">完全不同意</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[16487].value" value="1" id="16487_1" group="16487" class="question_radio_16487 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16487].value" value="2" id="16487_2" group="16487" class="question_radio_16487 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16487].value" value="3" id="16487_3" group="16487" class="question_radio_16487 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16487].value" value="4" id="16487_4" group="16487" class="question_radio_16487 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[16487].value" value="5" id="16487_5" group="16487" class="question_radio_16487 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">完全同意</div>

</td>
<td valign="top" class="noanswer-td">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16488");
</script>
		  <div id="q_3698" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						高质量的
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[16488].value"></span>
<input type="hidden" name="answers[16488].id" value="" id="answers[16488].id">
<table>
<tbody><tr>

<td>

<div class="left-label">完全不同意</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[16488].value" value="1" id="16488_1" group="16488" class="question_radio_16488 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16488].value" value="2" id="16488_2" group="16488" class="question_radio_16488 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16488].value" value="3" id="16488_3" group="16488" class="question_radio_16488 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16488].value" value="4" id="16488_4" group="16488" class="question_radio_16488 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[16488].value" value="5" id="16488_5" group="16488" class="question_radio_16488 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">完全同意</div>

</td>
<td valign="top" class="noanswer-td">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16489");
</script>
		  <div id="q_3699" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						提供与其他品牌不同的东西
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[16489].value"></span>
<input type="hidden" name="answers[16489].id" value="" id="answers[16489].id">
<table>
<tbody><tr>

<td>

<div class="left-label">完全不同意</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[16489].value" value="1" id="16489_1" group="16489" class="question_radio_16489 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16489].value" value="2" id="16489_2" group="16489" class="question_radio_16489 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16489].value" value="3" id="16489_3" group="16489" class="question_radio_16489 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16489].value" value="4" id="16489_4" group="16489" class="question_radio_16489 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[16489].value" value="5" id="16489_5" group="16489" class="question_radio_16489 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">完全同意</div>

</td>
<td valign="top" class="noanswer-td">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16490");
</script>
		  <div id="q_3700" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						物有所值
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[16490].value"></span>
<input type="hidden" name="answers[16490].id" value="" id="answers[16490].id">
<table>
<tbody><tr>

<td>

<div class="left-label">完全不同意</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[16490].value" value="1" id="16490_1" group="16490" class="question_radio_16490 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16490].value" value="2" id="16490_2" group="16490" class="question_radio_16490 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16490].value" value="3" id="16490_3" group="16490" class="question_radio_16490 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16490].value" value="4" id="16490_4" group="16490" class="question_radio_16490 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[16490].value" value="5" id="16490_5" group="16490" class="question_radio_16490 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">完全同意</div>

</td>
<td valign="top" class="noanswer-td">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16491");
</script>
		  <div id="q_3701" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						适合各种场合的
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[16491].value"></span>
<input type="hidden" name="answers[16491].id" value="" id="answers[16491].id">
<table>
<tbody><tr>

<td>

<div class="left-label">完全不同意</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[16491].value" value="1" id="16491_1" group="16491" class="question_radio_16491 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16491].value" value="2" id="16491_2" group="16491" class="question_radio_16491 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16491].value" value="3" id="16491_3" group="16491" class="question_radio_16491 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16491].value" value="4" id="16491_4" group="16491" class="question_radio_16491 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[16491].value" value="5" id="16491_5" group="16491" class="question_radio_16491 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">完全同意</div>

</td>
<td valign="top" class="noanswer-td">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16492");
</script>
		  <div id="q_3702" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						有吸引人的包装
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[16492].value"></span>
<input type="hidden" name="answers[16492].id" value="" id="answers[16492].id">
<table>
<tbody><tr>

<td>

<div class="left-label">完全不同意</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[16492].value" value="1" id="16492_1" group="16492" class="question_radio_16492 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16492].value" value="2" id="16492_2" group="16492" class="question_radio_16492 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16492].value" value="3" id="16492_3" group="16492" class="question_radio_16492 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16492].value" value="4" id="16492_4" group="16492" class="question_radio_16492 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[16492].value" value="5" id="16492_5" group="16492" class="question_radio_16492 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">完全同意</div>

</td>
<td valign="top" class="noanswer-td">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16493");
</script>
		  <div id="q_3703" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						可靠/值得信赖的
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[16493].value"></span>
<input type="hidden" name="answers[16493].id" value="" id="answers[16493].id">
<table>
<tbody><tr>

<td>

<div class="left-label">完全不同意</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[16493].value" value="1" id="16493_1" group="16493" class="question_radio_16493 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16493].value" value="2" id="16493_2" group="16493" class="question_radio_16493 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16493].value" value="3" id="16493_3" group="16493" class="question_radio_16493 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16493].value" value="4" id="16493_4" group="16493" class="question_radio_16493 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[16493].value" value="5" id="16493_5" group="16493" class="question_radio_16493 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">完全同意</div>

</td>
<td valign="top" class="noanswer-td">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16494");
</script>
		  <div id="q_3704" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						其他评价：
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[16494].id" value="" id="answers[16494].id">
<input type="text" name="answers[16494].value" value="" id="question_16494" group="16494" class="input-text">

<span class="error-content" id="err_answers[16494].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16495");
</script>
		  <div id="q_3569" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						在未来三个月，你愿意购买悠漫奶焙糖吗？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[16495].value"></span>
<input type="hidden" name="answers[16495].id" value="" id="answers[16495].id">
<table>
<tbody><tr>

<td>

<div class="left-label">肯定不会买</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[16495].value" value="1" id="16495_1" group="16495" class="question_radio_16495 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16495].value" value="2" id="16495_2" group="16495" class="question_radio_16495 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16495].value" value="3" id="16495_3" group="16495" class="question_radio_16495 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16495].value" value="4" id="16495_4" group="16495" class="question_radio_16495 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[16495].value" value="5" id="16495_5" group="16495" class="question_radio_16495 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
		</tr>
	</tbody></table> <div class="right-label">肯定会买</div>

</td>
<td valign="top" class="noanswer-td">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16496");
</script>
		  <div id="q_3570" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你会向亲友或同事推荐悠漫奶焙糖吗？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<span class="error-content" id="err_answers[16496].value"></span>
<input type="hidden" name="answers[16496].id" value="" id="answers[16496].id">
<table>
<tbody><tr>

<td>

<div class="left-label">肯定不会</div>
	<table class="rating-table">
		<tbody><tr class="radio-line">

					<td style="background-color: #ffffff;" class="leftRadio">
<input type="radio" name="answers[16496].value" value="0" id="16496_0" group="16496" class="question_radio_16496 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16496].value" value="1" id="16496_1" group="16496" class="question_radio_16496 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16496].value" value="2" id="16496_2" group="16496" class="question_radio_16496 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16496].value" value="3" id="16496_3" group="16496" class="question_radio_16496 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16496].value" value="4" id="16496_4" group="16496" class="question_radio_16496 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16496].value" value="5" id="16496_5" group="16496" class="question_radio_16496 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16496].value" value="6" id="16496_6" group="16496" class="question_radio_16496 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16496].value" value="7" id="16496_7" group="16496" class="question_radio_16496 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16496].value" value="8" id="16496_8" group="16496" class="question_radio_16496 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;">
<input type="radio" name="answers[16496].value" value="9" id="16496_9" group="16496" class="question_radio_16496 rating" style="background-color: #ffffff">
					</td>
					<td style="background-color: #ffffff;" class="rightRadio">
<input type="radio" name="answers[16496].value" value="10" id="16496_10" group="16496" class="question_radio_16496 rating" style="background-color: #ffffff">
					</td>
		</tr>
		<tr class="number">
				<td>0</td>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>10</td>
		</tr>
	</tbody></table> <div class="right-label">肯定会</div>

</td>
<td valign="top" class="noanswer-td">
</td>
</tr>
</tbody></table>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16497");
</script>
		  <div id="q_3571" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你曾吃过其他品牌的牛奶糖吗?
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[16497].value" style="display:block"></span>

<input type="hidden" name="answers[16497].id" value="" id="answers[16497].id">
<ul>
	<li>
			<input group="16497" type="radio" id="16497_0" name="answers[16497].value" value="13405" class="selection question_radio_16497">		<label for="16497_0">是</label>
	</li>
	<li>
			<input group="16497" type="radio" id="16497_1" name="answers[16497].value" value="13406" class="selection question_radio_16497">		<label for="16497_1">否</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16498");
</script>
		  <div id="q_3708" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你吃过哪些牌子呢？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">

<table width="100%" class="select-table">
<tbody><tr>
<td>
<span class="error-content" id="err_answers[16498].value" style="display:block"></span>

<input type="hidden" name="answers[16498].id" value="" id="answers[16498].id">




<span id="hint_16498">
</span>
<ul>
	<li>
			<input group="16498" class="question_radio_16498 selection" type="checkbox" id="16498_0" name="answers[16498].value" value="13890" onclick=" ">		<label for="16498_0">悠哈</label>
	</li>
	<li>
			<input group="16498" class="question_radio_16498 selection" type="checkbox" id="16498_1" name="answers[16498].value" value="13891" onclick=" ">		<label for="16498_1">大白兔</label>
	</li>
	<li>
			<input group="16498" class="question_radio_16498 selection" type="checkbox" id="16498_2" name="answers[16498].value" value="13892" onclick=" ">		<label for="16498_2">旺仔</label>
	</li>
	<li>
			<input group="16498" class="question_radio_16498 selection" type="checkbox" id="16498_3" name="answers[16498].value" value="13893" onclick=" ">		<label for="16498_3">阿尔卑斯</label>
	</li>
	<li>
			<input group="16498" class="question_radio_16498 selection" type="checkbox" id="16498_4" name="answers[16498].value" value="13894" onclick=" ">		<label for="16498_4">怡口莲</label>
	</li>
	<li>
			<input group="16498" class="question_radio_16498 selection" type="checkbox" id="16498_5" name="answers[16498].value" value="13895" onclick=" ">		<label for="16498_5">喔喔</label>
	</li>
	<li>
			<input group="16498" class="question_radio_16498 selection" type="checkbox" id="16498_6" name="answers[16498].value" value="13896" onclick=" ">		<label for="16498_6">不二家</label>
	</li>
	<li>
			<input group="16498" class="question_radio_16498 selection" type="checkbox" id="16498_7" name="answers[16498].value" value="13897" onclick=" ">		<label for="16498_7">金丝猴</label>
	</li>
	<li>
			<input group="16498" class="question_radio_16498 selection" type="checkbox" id="16498_8" name="answers[16498].value" value="13898" onclick=" ">		<label for="16498_8">其他，请详细说明</label>
	</li>
</ul>
 </td>

<td valign="top" class="noanswer-td">
</td>
</tr>

  </tbody></table>
<script language="JavaScript" type="text/javascript">
</script>
				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16499");
</script>
		  <div id="q_3632" style="margin-bottom: 0px; display: none;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						其他品牌：
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[16499].id" value="" id="answers[16499].id">
<input type="text" name="answers[16499].value" value="" id="question_16499" group="16499" class="input-text">

<span class="error-content" id="err_answers[16499].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16500");
</script>
		  <div id="q_3572" style="margin-bottom: 0px; display: none;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						你认为悠漫奶焙糖和其他品牌的奶糖有什么区别？
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[16500].id" value="" id="answers[16500].id">
<input type="text" name="answers[16500].value" value="" id="question_16500" group="16500" class="input-text">

<span class="error-content" id="err_answers[16500].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16501");
</script>
		  <div id="q_3298" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						姓名：
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[16501].id" value="" id="answers[16501].id">
<?php if(null != $this->user->recipients_name) {?>
<input type="text" name="answers[16501].value" value=<?php echo $this->user->recipients_name; ?> id="question_16501" group="16501" class="input-text">
<?php } else {?>
<input type="text" name="answers[16501].value" value="" id="question_16501" group="16501" class="input-text">
<?php } ?>
<span class="error-content" id="err_answers[16501].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16502");
</script>
		  <div id="q_3706" style="margin-bottom:0px;" class="question-even question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						电子邮箱：
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[16502].id" value="" id="answers[16502].id">
<?php if(null != $this->user->email) {?>
<input type="text" name="answers[16502].value" value=<?php echo $this->user->email; ?> id="question_16502" group="16502" class="input-text">
<?php } else {?>
<input type="text" name="answers[16502].value" value="" id="question_16502" group="16502" class="input-text">
<?php } ?>
<span class="error-content" id="err_answers[16502].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
<script language="JavaScript" type="text/javascript">
		 	mandatoryElements.push("16503");
</script>
		  <div id="q_3707" style="margin-bottom:0px;" class="question-odd question-area">
	  	
		<table class="question-table">
			<tbody><tr>
				<td width="50%" valign="top">
					<div class="question-title">
						电话号码：
							<span style="color:red">*</span>
					</div>
							<div class="elementInfoText twoColumnLayout">
							   
							</div>
				</td>
				<td width="50%" valign="top">
<table width="100%">
<tbody><tr>
<td>
<input type="hidden" name="answers[16503].id" value="" id="answers[16503].id">
<?php if(null != $this->user->login_phone) {?>
<input type="text" name="answers[16503].value" value=<?php echo $this->user->login_phone; ?> id="question_16503" group="16503" class="input-text">
<?php } else {?>
<input type="text" name="answers[16503].value" value="" id="question_16503" group="16503" class="input-text">
<?php } ?>
<span class="error-content" id="err_answers[16503].value"></span>
</td>

  </tr>
  </tbody></table>				</td>
			</tr>
	    </tbody></table>
	  </div>
	  <div style="clear:both;"></div>
	


</div> 
<br>
<div style="clear:both"></div>
</div> 
</div> 

<div id="mainzone-bottom-wrapper">
	<div id="mainzone-bottom-left">
		<div id="mainzone-bottom-right">&nbsp;</div>
	</div>
</div>
<br>
<div class="fillout-submit">
<input id="nextPageButton" type="button" class="button" onclick="showNextPage();" value="下一页" style="display: none;">
<input id="submit" type="submit" style="" class="button" name="command.submit" value="提交">
</div>
<table border="0" cellspacing="0" cellpadding="0" class="web-dialog" id="web-dialog" style="display:none; margin:15px 20px;">
	<tbody><tr>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_l_t.gif"></td>
		<td height="9" background="http://www.marketing-research.cn/images/web_dialog_m_t.gif"><img src="http://www.marketing-research.cn/images/web_dialog_m_t.gif"></td>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_r_t.gif"></td>
	</tr>
	<tr>
		<td width="9" background="http://www.marketing-research.cn/images/web_dialog_l_m.gif"><img src="http://www.marketing-research.cn/images/web_dialog_l_m.gif"></td>
		<td bgcolor="#ffffff">
			<div class="web-dialog-message">
				<p id="web-dialog-message-text" class=""></p>
			</div>
			<div class="buttons" id="web-dialog-buttons">
			</div>
		</td>
		<td width="9" background="http://www.marketing-research.cn/images/web_dialog_r_m.gif"><img src="http://www.marketing-research.cn/images/web_dialog_r_m.gif"></td>
	</tr>
	<tr>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_l_b.gif"></td>
		<td height="9" background="http://www.marketing-research.cn/images/web_dialog_m_b.gif"><img src="http://www.marketing-research.cn/images/web_dialog_m_b.gif"></td>
		<td width="9" height="9"><img src="http://www.marketing-research.cn/images/web_dialog_r_b.gif"></td>
	</tr>
</tbody></table>

<div class="mask" id="mask" style="display:none;"></div>
<script language="JavaScript" type="text/javascript">
<!--
// <![CDATA[
	var WebDialog = {
		element : $('web-dialog'),
		onok : function() {},
		oncancel : function() {},
		show : function() {
			var width = document.body.clientWidth;
			var height = document.body.offsetHeight;
			var left = (width - this.element.offsetWidth) / 2;
			var top = (height - this.element.offsetHeight) / 2;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
		},
		alert : function(msg,agree,disagree,onok,oncancel) {
			var buttons = ["OK","Cancel"];
			var callbacks = [onok, oncancel];
			this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
		},
		ok : function() {
			this.onok();
		},
		close : function() {
			this.element.hide();
			$('mask').hide();
			this.oncancel();
		},
		showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions) {
			// icon_type : "none", "alert", "question"
			// msg_align : "left", "center", "right"
			// width : -1 means auto
			
			var width = document.body.clientWidth;
			var height = window.screen.availHeight;
			var left = (width - window_width) / 2;
			var top = (height - 300) / 2;
			var pos = 0;
			if (window.innerHeight) {
		    	pos = window.pageYOffset
		    } else if (document.documentElement && document.documentElement.scrollTop) {
		    	pos = document.documentElement.scrollTop
		    } else if (document.body) {
		    	pos = document.body.scrollTop;
		    }
		    top += pos;
			if (top < 300) {
				top = 300;
			}
			this.element.style.left = left + "px";
			this.element.style.top = top + "px";
			$('mask').style.height = document.body.scrollHeight + "px";
			
			if (width != undefined) {
				this.element.style.width = window_width + "px";
			}
			if (msg != undefined) {
				$('web-dialog-message-text').innerHTML = msg;
			}
			if (icon_type != undefined && msg_align != undefined) {
				$('web-dialog-message-text').className = "icon-"+icon_type+" "+msg_align;
			} else if (icon_type == undefined && msg_align == undefined) {
				$('web-dialog-message-text').className = "icon-none left";
			} else if (icon_type == undefined) {
				$('web-dialog-message-text').className = msg_align;
			} else {
				$('web-dialog-message-text').className = "icon-"+icon_type;
			}
			
			$('web-dialog-buttons').innerHTML = "";
			if (buttons!=undefined && callback_functions!=undefined) {
				for (var i=0; i<buttons.length; i++) {
					if (buttons[i]==undefined || callback_functions[i]==undefined) {
						continue;
					}
					var e = document.createElement('a');
					e.setAttribute('href', '#');
					e.innerHTML = buttons[i];
					e.onclick = callback_functions[i];
					$('web-dialog-buttons').appendChild(e);
				}
			}
			
			
			this.element.show();
			//$('mask').show();
		}
	}
// ]]>
-->
</script>
</form>

</div> 
<div class="clear"></div>
<br>
</div>

<script type="text/javascript" language="JavaScript">

  var pageNum=0;
 
  var noPage0 = false;
  var currentPage=0;
  

  function showPage(_pageIndex) {
    if (_pageIndex <0 || _pageIndex < pageNum) return ;
    if (_pageIndex == pageNum) {
    	Element.hide("nextPageButton");
    } else {
    	Element.show("nextPageButton");
    }
    
    if (_pageIndex <1 && noPage0) return ;
  	var _pageElement = $("page_"+_pageIndex);
  	var _currElement = $("page_"+currentPage);
  	
  	Element.hide(_currElement);
  	Element.show(_pageElement);
	
	if($("pageNum" + _pageIndex) != undefined) {
		$("pageNum" + _pageIndex).style.fontWeight = "bolder"; 
		$("pageNum" + _pageIndex).style.textDecoration = "underline";
	}
    if($("pageNum" + currentPage) != undefined) {		
  		$("pageNum" + currentPage).style.fontWeight = "normal"; 
		$("pageNum" + currentPage).style.textDecoration = "none";
	}
	

  	currentPage = _pageIndex;
	
	if(_pageIndex == pageNum) {
		Element.show($('submit'));
	} else if ( _pageIndex <pageNum) {
		Element.hide($('submit'));
	}
  }
  
  function showNextPage(){
  	showPage(currentPage+1);
  }
  
  function showPrevPage(){
  	showPage(currentPage-1);
  }
  
  function initPages() {
  	var i;

  	for (i=0; i<=pageNum; i++) {
  		Element.hide($("page_"+i));
  	}
  	
 
  	// var _pageBar = document.getElementById("pageBar");
  	// if (pageNum==0) {
  	// 	_pageBar.innerHTML = "";
  	// } else {
	  // 	for (i=0; i<=pageNum; i++) {
			// var s ="";
			// if( i == 0 ) {
			// 	s += "&lt;a href='#' onclick='showPrevPage();'&gt;" + "&lt;-Previous" + "&lt;/a&gt;&nbsp;";
			// }

			// if (noPage0){
	  // 		 if (i!=0){ 
	  // 		 	s += "&lt;a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'&gt;" + (i) + "&lt;/a&gt;&nbsp;";
	  // 		  }
	  // 		}else{
	  // 		  s += "&lt;a id=pageNum" + i + " href='#' onclick='showPage(" + i + ");'&gt;" + (i+1) + "&lt;/a&gt;&nbsp;";
	  // 		}
	  		
			// if( i == pageNum ) {
			// 	s+= "&lt;a href='#' onclick='showNextPage();'&gt;" + "Next -&gt;" + "&lt;/a&gt;&nbsp;";
			// }
	  // 		_pageBar.innerHTML = _pageBar.innerHTML + s ;
	  // 	}		
  	// }
  }
  
  initPages();
  if (noPage0){
  	showPage(1);
  }else{
  	showPage(0);
  }

</script>

<script type="text/javascript" language="JavaScript">

    //do not include radio answers
	if(typeof checkNoAnswer=="undefined") {
		checkNoAnswer=function(index,checkbox) {
			var question = $("question_" + index);
			var checked = checkbox.checked;
			if( checked) {
				question.disabled="disabled";
				checkbox.value=false;
			} else {
				question.disabled="";
				checkbox.value=true;
			}
		};
	};
	
		if(typeof checkRadioNoAnswer=="undefined") {
		checkRadioNoAnswer = function(index,checkbox) {
			var clazz = "question_radio_" +index;
			var radios = document.getElementsByClassName(clazz).each(function(radio) {
				var checked = checkbox.checked;
			    if( checked) {
					if(radio.checked="checked")radio.checked="";
					radio.disabled="disabled";
					checkbox.value=false;
			    } else {
					radio.disabled="";
					checkbox.value=true;
			    }
			});
		};
	}
	
	if(typeof checkSubboxes=="undefined") {
		checkSubboxes = function(qc_id) {
			//get the question context checkbox's value
			var qc_value = $("qc_checkbox_" + qc_id).checked;
			//get the checkBoxed belongs to the above question context
			var checkBoxes = $("mainzone").getElementsByClassName("qc_"+qc_id);
			for(var i = 0; i<checkBoxes.length;i++) {
				var checkBox = checkBoxes[i];
				//to reuse checkRadioNoAnswer and checkNoAnswer
				checkBox.checked=qc_value;
				var clazzName = checkBox.className;
				var question_id = clazzName.split(" ")[0].split("_")[1];
				if( clazzName.indexOf("radio") != -1) {
					checkRadioNoAnswer(question_id,checkBox);
				} else {
					checkNoAnswer(question_id,checkBox);
				}
			}
		}
		
	}

</script>
<script type="text/javascript" language="JavaScript">

	function loading() {
		var html = "&lt;img src='http://q.xingxinghuo.cn/images/spinner.gif' /&gt;Please wait...";
		WebDialog.showMessageBox(html, "none", "center", 600);
	}
	
	function checkMandatory() {
	    var fillMandatory = true;
	    
	    
	    for(var j=0; j < mandatoryElements.length; j++) {
	    	var elements = ($('mainzone-inner').getElementsBySelector('[group="'+ mandatoryElements[j] +'"]'));
	    	
			if(elements.length > 1) {
				
			  var filled = false;
			  for(var i=0; i < elements.length; i++) {
			  	var element = elements[i];
				if(element.checked) {
				  filled = true;
				  break;
				}
			  }
			  if(!filled) {
			  	fillMandatory = false;
			  	break;
			  }
			} else {
				
			  var element = elements[0];
			  if(element.hasClassName("selection")) {
			  	 if(element.type == "radio"){
			  		var filledThis = false;
	            	for(var i=0;i<elements.length;i++){
					  		if(elements[i].checked){
					  				filledThis =  true;
					  				break;
					  		}
				  	}
				  	fillMandatory = fillMandatory && filledThis;
			  	 }
			  	
			  	if(element.value.strip() == ''||element.value.strip() == '0') {
	    			fillMandatory =  false;
	    			break;                                  
	    		}
			  } else if (element.hasClassName("input-text")) {
			 	if(element.value == 0) {
					fillMandatory = false;
					break;
				}
			  } else if (element.hasClassName("rating")){
			  	var filledThis = false;
            	for(var i=0;i<elements.length;i++){
				  		if(elements[i].checked){
				  				filledThis =  true;
				  				break;
				  		}
			  	}
			  	fillMandatory = fillMandatory && filledThis;
			  }
			}
	    }
	    
	    if(!fillMandatory) {
	    	var html = '提交失败：必填的题目不能为空';
			var buttons = ["确定"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
	    }
		return fillMandatory;
	}
	
	function checkMandatoryOfSelectionQuestion() {
	 var mandatory = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}


	function checkAnswerSet() {
		if( checkAnswersOfSelectionQuestions() || checkAnswersOfRatingQuestions() || checkAnswersOfCommentQuestions()) {
		    return true;
		} else {
			var html = '不能提交空报告';
			var buttons = ["确定"];
			var callbacks = [ function() { WebDialog.close();return false;}]; 
			WebDialog.showMessageBox(html, "center", "center", 600, buttons, callbacks);
			return false;
		}
	}
	
	function checkAnswersOfSelectionQuestions() {
	 var filled = false;
	 $$('input.selection').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;
										}
	                                });
	 if(!filled) {
	 $$('select.selection').each(function(element) {
										if(element.value != 0) {
											filled = true;
											throw $break;
										}
	                                });
	 }                      
	  return filled;
	}
	
	function checkAnswersOfRatingQuestions() {
	    var filled = false;
	    $$('input.rating').each(function(element) {
										if(element.checked) {
											filled = true;
											throw $break;  
										}
	                                });

		 return filled;
	}
	
	function checkAnswersOfCommentQuestions() {
	    var filled = false;
	    $$('.input-text').each(function(element) {
	                                    if(element.value.strip() != '') {
	                                        filled = true;
	                                    	throw $break;                                 
	                                    }
	                                });
		 return filled;
	}
	
	function locateErrorPage() {
		var errorElements = $$('span.error-content') ;
		var hasError = false;
		var errorElementsPointer = 0;
		for (errorElementsPointer=0; errorElementsPointer < errorElements.length; errorElementsPointer++) {
			var html = errorElements[errorElementsPointer].innerHTML;
			if (html != "") {
				hasError = true;
				break;
			}
		}
		if( hasError ) {
			var errorParentElement = errorElements[errorElementsPointer].up('div');
			while (errorParentElement != undefined) {
			var elementId = errorParentElement.id;
			if (elementId != undefined && elementId.indexOf('page') != -1) {
				var errorPageNum = parseInt(elementId.substring(elementId.indexOf('_')+1));
				showPage(errorPageNum);
				break;
		}
		errorParentElement = errorParentElement.up('div');
		}
		}
	}
	locateErrorPage();
	
	function showOtherValueInputInSelect(element) {
	    var options = element.options;
	    var selectedOption;
	    for( var i = 0; i<options.length; i++) {
	       if( options[i].selected) {
	       	 selectedOption = options[i];
	       }
	    }
	    var selectedOptionId = selectedOption.id;
	    if( selectedOptionId.indexOf("other") != -1) {
	    	$(element.id + "_other").show();
	    } else {
	        $(element.id + "_other").value = "";
	    	$(element.id + "_other").hide();
	    }
	}
	
	function showOtherValueInputInRadio(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( value == 0 ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}
	function showOtherValueInputInCheckBox(element) {
		var elementId = element.id.split("_")[0];
		var value = element.value;
		if( element.checked ) {
			$(elementId + "_other_input").show();
		} else {
		    $(elementId + "_other_input").value = "";
			$(elementId + "_other_input").hide();
		}
	}

	/*
	new PeriodicalExecuter(function() {
		$('fillout').request({
  			method: 'post',
  			parameters: { 'command.pause':"Continue Later"}
		});
		}, 5);
	*/

  /*var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5436862-10']);
  _gaq.push(['_setDomainName', '.marketing-research.cn']);
  _gaq.push(['setAllowHash', 'false']);

  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();*/



</script>
</div>
</div> 
</div>

	<div style="display:none;" class="bottom-shadow"></div>
	<div style="clear: both"></div>
	
</div>



<script language="JavaScript" type="text/javascript">

	 Element.hide("q_3688");
	 Element.hide("q_3689");
	 Element.hide("q_3690");
	 Element.hide("q_3379");
	 Element.hide("q_3662");
	 Element.hide("q_3694");
	 Element.hide("q_3695");
	 Element.hide("q_3575");
	 Element.hide("q_3696");
	 Element.hide("q_3697");
	 Element.hide("q_3698");
	 Element.hide("q_3699");
	 Element.hide("q_3700");
	 Element.hide("q_3701");
	 Element.hide("q_3702");
	 Element.hide("q_3703");
	 Element.hide("q_3704");
	 Element.hide("q_3571");
	 Element.hide("q_3708");
	 Element.hide("q_3632");
	 Element.hide("q_3572");


var myrules = {
	   
	   "input#16482_1": function(el){
			el.onclick = function(){
				if ($("16482_1").checked){
						Element.hide($("q_3694"));
						Element.hide($("q_3695"));
						Element.hide($("q_3575"));
						Element.hide($("q_3696"));
						Element.hide($("q_3697"));
						Element.hide($("q_3698"));
						Element.hide($("q_3699"));
						Element.hide($("q_3700"));
						Element.hide($("q_3701"));
						Element.hide($("q_3702"));
						Element.hide($("q_3703"));
						Element.hide($("q_3704"));
						Element.hide($("q_3571"));
				}
			}
		}
	,
	   
	   "input#16474_1": function(el){
			el.onclick = function(){
				if ($("16474_1").checked){
						Element.hide($("q_3688"));
						Element.hide($("q_3689"));
						Element.hide($("q_3690"));
				}
			}
		}
	,
	   
	   "input#16497_0": function(el){
			el.onclick = function(){
				if ($("16497_0").checked){
						Element.show($("q_3708"));
						Element.show($("q_3572"));
				}
			}
		}
	,
	   
	   "input#16474_0": function(el){
			el.onclick = function(){
				if ($("16474_0").checked){
						Element.show($("q_3688"));
						Element.show($("q_3689"));
						Element.show($("q_3690"));
				}
			}
		}
	,
	   
	   "input#16482_0": function(el){
			el.onclick = function(){
				if ($("16482_0").checked){
						Element.show($("q_3694"));
						Element.show($("q_3695"));
						Element.show($("q_3575"));
						Element.show($("q_3696"));
						Element.show($("q_3697"));
						Element.show($("q_3698"));
						Element.show($("q_3699"));
						Element.show($("q_3700"));
						Element.show($("q_3701"));
						Element.show($("q_3702"));
						Element.show($("q_3703"));
						Element.show($("q_3704"));
						Element.show($("q_3571"));
				}
			}
		}
	,
	   
	   "input#16497_1": function(el){
			el.onclick = function(){
				if ($("16497_1").checked){
						Element.hide($("q_3708"));
						Element.hide($("q_3572"));
				}
			}
		}
}

Behaviour.register(myrules);

</script>

</pre>		<div class="clear"></div>
	</div></div>