<!-- <div class="article-box">
    <div class="article-box-inner">
        <h1 style="margin-left:0;">
            <?php echo $this->
                translate('INVITATION_MAIL_INTRODUCTION_HEAD'); ?>
        </h1>
        <p>
            <?php echo $this->
                translate('INVITATION_MAIL_INTRODUCTION_CONTENT'); ?>
        </p>
    </div>
</div> -->
<!-- <div class="article-box" style="background:#fff;padding-top:0;">
    <div class="article-box-inner" style="background:#fff;">
        <?php if ($this->notSendMailAmont > 0) { ?>
            <table>
                <tr>
                    <td>
                        <h2>
                            <?php echo $this->translate('INVITATION_MAIL_LIST_PART1'); ?>
                            <?php echo $this->notSendMailAmont; ?>
                            <?php echo $this->translate('INVITATION_MAIL_LIST_PART2'); ?>
                        </h2>
                    </td>
                </tr>
                <tr>
                    <td>
                        <form id='f' action="<?php echo $this->url(array('controller' => 'invitation', 'action' => 'send')); ?>"
                        method="post">
                            <table>
                                <tr>
                                    <td valign="top">
                                        <div align="left">
                                            <?php echo $this->translate("INVITATION_FRIEND"); ?>
                                        </div>
                                        <div>
                                            <?php $temp1="email" . $this->justone ?>
                                            <?php echo $this->sendMailForm->$temp1; ?>
                                        </div>
                                        <div style="clear:both; ">
                                        </div>
                                        <div>
                                            <p style="margin-top:0px; margin-bottom:0px; padding-top:5px; padding-bottom:0px;">
                                                <?php echo $this->translate("INVITATION_MAIL_SUBJECT"); ?>
                                            </p>
                                        </div>
                                        <div class="">
                                            <?php echo $this->sendMailForm->subject; ?>
                                        </div>
                                        <div>
                                            <p style="margin-top:0px; margin-bottom:0px; padding-top:5px; padding-bottom:0px;">
                                                <?php echo $this->translate("INVITATION_MAIL_CONTENT"); ?>
                                            </p>
                                        </div>
                                        <div class="">
                                            <?php echo $this->sendMailForm->message; ?>
                                                <textarea rows="5" cols="100"> Hello. I'm a member of Wildfire, the Chinese word-of-mouth consumer community.Wildfire helps its members spread word of mouth about products and services naturally and honestly through free products, coupons and more. Joining is totally free and there is no obligation involved. Interested in learning more and signing up?
                                                </textarea>
                                        </div>
                                        <div id="notice" style="padding-bottom: 10px; display: none; font-size: 14px; color: #f00; font-weight: bold;">
                                            <?php echo $this->translate('INVITATION_MAIL_SEND_NOTICE') ?>
                                        </div>
                                        <div class="send-invitation">
                                            <input id="submit" type="submit" value="<?php echo $this->translate('INVITATION_MAIL_SEND') ?>"
                                            onclick="onSend();return true;">
                                        </div>
                                        <?php echo $this->sendMailForm->sentMailAmount; ?>
                                            <a tyle='cursor:hand;' id="preview_hide" onclick="show_info()">
                                                <div id="changeable_text" style="width:500px;">
                                                    <img id="img_change" alt="" src="../public/image/colsed.png">
                                                    <?php echo $this->translate('MAIL_PREVIEW') ?>
                                                </div>
                                            </a>
                                    </td>
                                    <td valign="top" width="30%">
                                        <?php echo $this->translate("INVITED_FRIENDS"); ?>
                                        <ul>
                                            <?php for ($i=1 ; $i < $this->
                                                justone - 1; $i++): ?>
                                                <?php $temp="email" . $i ?>
                                                    <li style="width: 150px; overflow: hidden;">
                                                        <?php echo $this->to_str ?>
                                                        <?php echo $this->receivers[$i]['to']; ?>
                                                    </li>
                                                    <?php endfor; ?>
                                        </ul>
                                    </td>
                                </tr>
                            </table>
                            <dl>
                                <div class="invite-emails-include" style="display:none;" id="preview">
                                     <h2><?php echo $this->translate('INVITATION_MAIL_CONTENT_ADD_HINT'); ?></h2>
                                    <p><?php echo $this->translate('INVITATION_MAIL_CONTENT_ADD_1'); ?></p>
                                    <ul>
                                    <li><?php echo $this->translate('INVITATION_MAIL_CONTENT_ADD_2'); ?></li>
                                    <li><?php echo $this->translate('INVITATION_MAIL_CONTENT_ADD_3'); ?></li>
                                    <li><?php echo $this->translate('INVITATION_MAIL_CONTENT_ADD_4'); ?></li>
                                    </ul>
                                    <p><?php echo $this->translate('INVITATION_MAIL_CONTENT_ADD_5'); ?></p>
                                    <p><?php echo $this->translate('INVITATION_MAIL_CONTENT_ADD_6'); ?></p>
                                    <p><?php echo $this->translate('INVITATION_MAIL_CONTENT_ADD_7'); ?></p>
                                    
                                    <img alt="" src="../public/image/demo.png" >
                                </div>
                            </dl>
                        </form>
                    </td>
                </tr>
            </table>
            <?php } else { ?>
                <h1>
                    <?php echo $this->
                        translate('You_currently_have_no_remaining'); ?>
                </h1>
                <p>
                    <?php echo $this->
                        translate('You_can_receive_more_invitations'); ?>
                </p>
                <?php } ?>
    </div>
</div> -->

<div class="article-box" id="selectCampaigns">
    <div class="article-box-inner">
        <h1 style="margin-left:0;">
            <?php echo $this->
                translate('INVITATION_MAIL_CAMPAIGN_INTRODUCTION_HEAD'); ?>
        </h1>
        <p>
        <form action="<?php echo $this->url(array('controller' => 'invitation', 'action' => 'send')); ?>"
                        method="post">
                <table>
                    <tr>
                        <td>Select a campaign:</td>
                        <td>
                            <select onchange="changeMailTemplate(this.value)">
                                <option >Please Choose</option>
                                <?php  foreach ($this->allCampaigns as $activeCampaign): ?>
                                <option id="<?php echo $activeCampaign['id'] ?>" value="<?php echo $activeCampaign['id'] ?>"><?php echo $activeCampaign['name']?></option>
                                <?php endforeach ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>Enter your friends’ email address:</td>
                        <td><?php echo $this->sendMailForm->$temp1; ?></td>
                    </tr>
                </table>
            
        </p>

            <h2>Invite Email Template</h2>
            <!--<?php echo $this->translate("INVITE_FRIENDS_TEMPLATE_105"); ?>-->

           <!--  <iframe width="100%" scrolling="no" height="500px" frameborder="0" src="/public/js/fckeditor/editor/fckeditor.html?InstanceName=htmlmessage&amp;Toolbar=Default" id="htmlmessage___Frame" style="margin: 0px; padding: 0px; border: 0px none; background-color: transparent; background-image: none; width: 100%; height: 500px;"></iframe>
            <div id='htmlMessage' style="padding: 20px; padding-top:0px; margin-left: 20px; width:770px; display:none;"> -->
                <div id='htmlMessage' style="padding: 20px; padding-top:0px; margin-left: 20px; width:580px; " >
                    <?php $this->oFCKeditor->create();?>
                      <!-- Hi!<br><br>
                      &nbsp;&nbsp;&nbsp;&nbsp;Join me in the word-of-mouth campaign for Quality for Life Philippines.
                      <br><br>
                      &nbsp;&nbsp;&nbsp;&nbsp;Kindly answer the survey by clicking the link below. Once you are selected, Wildfire will contact you directly to formally invite you to join this campaign: <a href="https://www.facebook.com/QualityForLifePhilippines/app_127709503932081">https://www.facebook.com/QualityForLifePhilippines/app_127709503932081</a><br><br>
                      &nbsp;&nbsp;&nbsp;&nbsp;For more information about Quality for Life Philippines, you can visit the official Facebook page at <a href="www.facebook.com/QualityForLifePhilippines">www.facebook.com/QualityForLifePhilippines</a>. Please do not forget to click the Like button to receive updates about health, vitamins, and nutrition!<br><br>
                      Have a great day!<br><br> -->
                </div>
                
                 <div class="send-invitation">
                    <input id="submit" type="submit" value="<?php echo $this->translate('INVITATION_MAIL_SEND') ?>"
                    onclick="onSend();return true;">
                 </div>
         </form>
    </div>
</div>

<!-- <div class="article-box" style="background:#fff;padding-top:0;" style="display:none">
    <div class="article-box-inner" style="background:#fff;">

    </div>
</div> -->

<!--
<div class="article-box" style="background:#fff;padding-top:0;">
    <div class="article-box-inner" style="background:#fff;">
        <?php if ($this->notSendMailAmont > 0) { ?>
            <table>
                <tr>
                    <td>
                        <h2>
                            <?php echo $this->translate('INVITATION_MAIL_LIST_PART1'); ?>
                            <?php echo $this->notSendMailAmont; ?>
                            <?php echo $this->translate('INVITATION_MAIL_LIST_PART2'); ?>
                        </h2>
                    </td>
                </tr>
                <tr>
                    <td>
                        <form id='f' action="<?php echo $this->url(array('controller' => 'invitation', 'action' => 'send')); ?>"
                        method="post">
                            <table>
                                <tr>
                                    <td valign="top">
                                        <div align="left">
                                            <?php echo $this->translate("INVITATION_FRIEND"); ?>
                                        </div>
                                        <div>
                                            <?php $temp1="email" . $this->justone ?>
                                            <?php echo $this->sendMailForm->$temp1; ?>
                                        </div>
                                        <div style="clear:both; ">
                                        </div>
                                        <div>
                                            <p style="margin-top:0px; margin-bottom:0px; padding-top:5px; padding-bottom:0px;">
                                                <?php echo $this->translate("INVITATION_MAIL_SUBJECT"); ?>
                                            </p>
                                        </div>
                                        <div class="">
                                            <?php echo $this->sendMailForm->subject; ?>
                                        </div>
                                        <div>
                                            <p style="margin-top:0px; margin-bottom:0px; padding-top:5px; padding-bottom:0px;">
                                                <?php echo $this->translate("INVITATION_MAIL_CONTENT"); ?>
                                            </p>
                                        </div>
                                      <div class="">
                                            <?php echo $this->sendMailForm->message; ?>
                                                <textarea rows="5" cols="100"> Hello. I'm a member of Wildfire, the Chinese word-of-mouth consumer community.Wildfire helps its members spread word of mouth about products and services naturally and honestly through free products, coupons and more. Joining is totally free and there is no obligation involved. Interested in learning more and signing up?
                                                </textarea>
                                        </div>
                                        <div id="notice" style="padding-bottom: 10px; display: none; font-size: 14px; color: #f00; font-weight: bold;">
                                            <?php echo $this->translate('INVITATION_MAIL_SEND_NOTICE') ?>
                                        </div>
                                        <div class="send-invitation">
                                            <input id="submit" type="submit" value="<?php echo $this->translate('INVITATION_MAIL_SEND') ?>"
                                            onclick="onSend();return true;">
                                        </div>
                                        <?php echo $this->sendMailForm->sentMailAmount; ?>
                                            <a tyle='cursor:hand;' id="preview_hide" onclick="show_info()">
                                                <div id="changeable_text" style="width:500px;">
                                                    <img id="img_change" alt="" src="../public/image/colsed.png">
                                                    <?php echo $this->translate('MAIL_PREVIEW') ?>
                                                </div>
                                            </a>
                                    </td>
                                    <td valign="top" width="30%">
                                        <?php echo $this->translate("INVITED_FRIENDS"); ?>
                                        <ul>
                                            <?php for ($i=1 ; $i < $this->
                                                justone - 1; $i++): ?>
                                                <?php $temp="email" . $i ?>
                                                    <li style="width: 150px; overflow: hidden;">
                                                        <?php echo $this->to_str ?>
                                                        <?php echo $this->receivers[$i]['to']; ?>
                                                    </li>
                                                    <?php endfor; ?>
                                        </ul>
                                    </td>
                                </tr>
                            </table>
                            <dl>
                                <div class="invite-emails-include" style="display:none;" id="preview">
                                     <h2><?php echo $this->translate('INVITATION_MAIL_CONTENT_ADD_HINT'); ?></h2>
                                    <p><?php echo $this->translate('INVITATION_MAIL_CONTENT_ADD_1'); ?></p>
                                    <ul>
                                    <li><?php echo $this->translate('INVITATION_MAIL_CONTENT_ADD_2'); ?></li>
                                    <li><?php echo $this->translate('INVITATION_MAIL_CONTENT_ADD_3'); ?></li>
                                    <li><?php echo $this->translate('INVITATION_MAIL_CONTENT_ADD_4'); ?></li>
                                    </ul>
                                    <p><?php echo $this->translate('INVITATION_MAIL_CONTENT_ADD_5'); ?></p>
                                    <p><?php echo $this->translate('INVITATION_MAIL_CONTENT_ADD_6'); ?></p>
                                    <p><?php echo $this->translate('INVITATION_MAIL_CONTENT_ADD_7'); ?></p>
                                    
                                    <img alt="" src="../public/image/demo.png" >
                                </div>
                            </dl>
                        </form>
                    </td>
                </tr>
            </table>
            <?php } else { ?>
                <h1>
                    <?php echo $this->
                        translate('You_currently_have_no_remaining'); ?>
                </h1>
                <p>
                    <?php echo $this->
                        translate('You_can_receive_more_invitations'); ?>
                </p>
                <?php } ?>
    </div>
</div>
-->
<script type="text/javascript">

function changeMailTemplate(val){

}

</script>

<script language="javascript">
    function show_info() {
        var previe_text = document.getElementById("preview");
        var previe_hand = document.getElementById("changeable_text");
        // var img_show=document.getElementById("img_change");
        if (previe_text.style.display == "none") {
            previe_text.style.display = "";
            //img_show.src="../public/image/opened.png";
            previe_hand.innerHTML = '<img id="img_change" alt="" src="../public/image/opened.png">' + '<?php echo $this->translate("FOLD_MAIL")?>';
        } else if (previe_text.style.display == "") {
            previe_text.style.display = "none";
            //img_show.src="../public/image/colsed.png";
            previe_hand.innerHTML = '<img id="img_change" alt="" src="../public/image/colsed.png">' + '<?php echo $this->translate("MAIL_PREVIEW")?>';
        }
    }
    var form = document.getElementById('f');
    form.onsubmit = function() {
        $('submit').disabled = 'disabled';
        $('notice').style.display = "";
    }
    form.submit();
</script>