<div class="article-box" style="height:120px;">
	<div class="article-box-inner">
		<h1 style="margin-left: 0; padding-top:10px;"><?php echo $this->showMessage; ?></h1>
		<br/>
		<div class="buttons-bar">
			<a class="big-button-blue" target="_parent"  href="<?php echo $this->url(array('controller'=>'invitation','action'=>'index'));?>"><?php echo $this->translate('Invites_More_Friends')?></a>
			<a class="big-button-blue" target="_parent"  href="<?php echo $this->url(array('controller'=>'home','action'=>'index'));?>"><?php echo $this->translate('Take_Me_Home')?></a>
		</div>
	</div>	
</div>
