<table id="__01" style="margin: 0pt auto; width: 1001px; height:610px;"  border="0" cellpadding="0" cellspacing="0"  margin="0 auto">
	<tr>
		<td colspan="34">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_01.gif" width="1000" height="16" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="16" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_02.gif" width="26" height="163" alt=""></td>
		<td colspan="6">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/口感不错">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_03.gif" width="205" height="69" border="0" alt=""></a></td>
		<td colspan="2" rowspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_04.gif" width="41" height="82" alt=""></td>
		<td colspan="6">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/朋友">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_05.gif" width="127" height="69" border="0" alt=""></a></td>
		<td>    
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_06.gif" width="77" height="69" alt=""></td>
		<td colspan="6">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/味道不错">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_07.gif" width="194" height="69" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_08.gif" width="23" height="69" alt=""></td>
		<td colspan="9">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/分享">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_09.gif" width="288" height="69" border="0" alt=""></a></td>
		<td rowspan="22">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_10.gif" width="19" height="593" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="69" alt=""></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_11.gif" width="205" height="13" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_12.gif" width="48" height="13" alt=""></td>
		<td colspan="10" rowspan="4">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/早餐">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_13.gif" width="279" height="94" border="0" alt=""></a></td>
		<td colspan="4" rowspan="3">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/牛奶">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_14.gif" width="134" height="80" border="0" alt=""></a></td>
		<td colspan="8" rowspan="2">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/分享">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_09-16.gif" width="248" height="23" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="13" alt=""></td>
	</tr>
	<tr>
		<td colspan="4" rowspan="3">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/喜欢">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_16.gif" width="161" height="81" border="0" alt=""></a></td>
		<td colspan="5" rowspan="3">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/宝宝">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_17.gif" width="133" height="81" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="10" alt=""></td>
	</tr>
	<tr>
		<td colspan="8">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/你是我的太阳">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_18.gif" width="248" height="57" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="57" alt=""></td>
	</tr>
	<tr>
		<td colspan="9" rowspan="4">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/优冠馅饼">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_19.gif" width="283" height="89" border="0" alt=""></a></td>
		<td colspan="3" rowspan="2">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/小麦">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_20.gif" width="99" height="60" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="14" alt=""></td>
	</tr>
	<tr>
		<td rowspan="17">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_21.gif" width="18" height="430" alt=""></td>
		<td colspan="8" rowspan="4">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/卡夫">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_22.gif" width="226" height="113" border="0" alt=""></a></td>
		<td colspan="4" rowspan="3">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/免费">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_23.gif" width="101" height="75" border="0" alt=""></a></td>
		<td colspan="8" rowspan="2">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/早餐">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_13-25.gif" width="254" height="56" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="46" alt=""></td>
	</tr>
	<tr>
		<td colspan="3" rowspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_25.gif" width="99" height="29" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="10" alt=""></td>
	</tr>
	<tr>
		<td colspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_26.gif" width="45" height="19" alt=""></td>
		<td colspan="5" rowspan="3">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/甜">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_27.gif" width="183" height="79" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_28.gif" width="26" height="19" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="19" alt=""></td>
	</tr>
	<tr>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_29.gif" width="28" height="38" alt=""></td>
		<td colspan="5" rowspan="2">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/家乐福">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_30.gif" width="118" height="60" border="0" alt=""></a></td>
		<td colspan="5" rowspan="2">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/口口相传">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_33.gif" width="160" height="60" border="0" alt=""></a></td>
		<td colspan="2" rowspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_32.gif" width="26" height="60" alt=""></td>
		<td colspan="5" rowspan="2">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/口味">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_35.gif" width="189" height="60" border="0" alt=""></a></td>
		<td rowspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_34.gif" width="33" height="60" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="38" alt=""></td>
	</tr>
	<tr>
		<td rowspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_35-36.gif" width="8" height="79" alt=""></td>
		<td colspan="2" rowspan="2">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/高兴">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_38.gif" width="111" height="79" border="0" alt=""></a></td>
		<td colspan="6" rowspan="2">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/饼干">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_39.gif" width="135" height="79" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="22" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_38-39.gif" width="64" height="78" alt=""></td>
		<td colspan="6" rowspan="2">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/方便">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_42.gif" width="151" height="65" border="0" alt=""></a></td>
		<td colspan="3" rowspan="2">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/画画">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_44.gif" width="112" height="65" border="0" alt=""></a></td>
		<td colspan="9" rowspan="4">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/草莓">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_45.gif" width="283" height="98" border="0" alt=""></a></td>
		<td colspan="3">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/色素">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_46.gif" width="99" height="57" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="57" alt=""></td>
	</tr>
	<tr>
		<td colspan="4" rowspan="5">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/营养">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_47.gif" width="143" height="84" border="0" alt=""></a></td>
		<td colspan="5" rowspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_44-45.gif" width="111" height="21" alt=""></td>
		<td colspan="3" rowspan="4">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/智力">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_45-46.gif" width="99" height="58" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="8" alt=""></td>
	</tr>
	<tr>
		<td colspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_46-47.gif" width="18" height="13" alt=""></td>
		<td colspan="5" rowspan="5">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/同事">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_49.gif" width="201" height="92" border="0" alt=""></a></td>
		<td colspan="2" rowspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_48.gif" width="44" height="33" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="13" alt=""></td>
	</tr>
	<tr>
		<td colspan="9" rowspan="3">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/营养丰富">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_54.gif" width="193" height="63" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="20" alt=""></td>
	</tr>
	<tr>
		<td colspan="7" rowspan="4">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/促销">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_55.gif" width="188" height="68" border="0" alt=""></a></td>
		<td colspan="2" rowspan="4">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_51.gif" width="47" height="68" alt=""></td>
		<td colspan="2" rowspan="4">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/月饼">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_57.gif" width="92" height="68" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="17" alt=""></td>
	</tr>
	<tr>
		<td rowspan="3">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/月饼">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_57-54.gif" width="22" height="51" border="0" alt=""></a></td>
		<td colspan="2" rowspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_54-55.gif" width="77" height="51" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="26" alt=""></td>
	</tr>
	<tr>
		<td colspan="13">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_55-56.gif" width="336" height="16" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="16" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_56.gif" width="24" height="138" alt=""></td>
		<td colspan="4" rowspan="3">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/体验">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_62.gif" width="163" height="65" border="0" alt=""></a></td>
		<td colspan="8" rowspan="3">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/早餐馅饼">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_63.gif" width="185" height="65" border="0" alt=""></a></td>
		<td colspan="4" rowspan="2">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/蓝莓">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_64.gif" width="165" height="43" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="9" alt=""></td>
	</tr>
	<tr>
		<td colspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_60.gif" width="138" height="34" alt=""></td>
		<td colspan="4" rowspan="2">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/鸡蛋">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_66.gif" width="97" height="56" border="0" alt=""></a></td>
		<td rowspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_62-63.gif" width="57" height="56" alt=""></td>
		<td colspan="4" rowspan="2">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/节省时间">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_68.gif" width="134" height="56" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="34" alt=""></td>
	</tr>
	<tr>
		<td colspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_64-65.gif" width="97" height="22" alt=""></td>
		<td colspan="4" rowspan="2">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/超市">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_70.gif" width="162" height="75" border="0" alt=""></a></td>
		<td colspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_66-67.gif" width="44" height="22" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="22" alt=""></td>
	</tr>
	<tr>
		<td colspan="4">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/营养成分">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_72.gif" width="163" height="53" border="0" alt=""></a></td>
		<td colspan="4">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/松软">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_73.gif" width="115" height="53" border="0" alt=""></a></td>
		<td colspan="7">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/口碑">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_74.gif" width="167" height="53" border="0" alt=""></a></td>
		<td colspan="7">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/天上掉馅饼">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_75.gif" width="198" height="53" border="0" alt=""></a></td>
		<td colspan="4">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/6/searchText/零食">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_76.gif" width="134" height="53" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="53" alt=""></td>
	</tr>
	<tr>
		<td colspan="30">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/Tag_Cloud_6_72-73.gif" width="939" height="20" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="1" height="20" alt=""></td>
	</tr>
	<tr>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="18" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="8" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="16" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="95" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="24" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="26" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="18" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="26" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="13" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="28" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="48" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="16" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="9" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="9" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="36" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="9" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="77" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="11" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="68" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="18" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="26" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="50" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="21" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="23" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="40" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="10" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="16" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="31" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="57" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="35" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="22" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="44" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="33" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/6/blank.gif" width="19" height="1" alt=""></td>
		<td></td>
	</tr>
</table>