<table id="__01" width="1006" height="618" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td colspan="126">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_01.gif" width="1005" height="27" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="27" alt=""></td>
	</tr>
	<tr>
		<td colspan="27" rowspan="4">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_02.gif" width="230" height="21" alt=""></td>
		<td colspan="16" rowspan="6">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/品牌">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_03.gif" width="108" height="36" border="0" alt=""></a></td>
		<td colspan="83">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_04.gif" width="667" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="39">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_05.gif" width="271" height="12" alt=""></td>
		<td colspan="26" rowspan="8">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/味道">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_06.gif" width="190" height="47" border="0" alt=""></a></td>
		<td colspan="18" rowspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_07.gif" width="206" height="14" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="12" alt=""></td>
	</tr>
	<tr>
		<td colspan="8" rowspan="12">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_08.gif" width="46" height="56" alt=""></td>
		<td colspan="18" rowspan="9">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/参加">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_09.gif" width="142" height="47" border="0" alt=""></a></td>
		<td colspan="13" rowspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_10.gif" width="83" height="10" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="3" rowspan="25">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_11.gif" width="34" height="105" alt=""></td>
		<td colspan="9" rowspan="5">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/淡淡">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_12.gif" width="60" height="29" border="0" alt=""></a></td>
		<td colspan="6" rowspan="8">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_13.gif" width="112" height="45" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="6" alt=""></td>
	</tr>
	<tr>
		<td colspan="11" rowspan="6">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_14.gif" width="117" height="38" alt=""></td>
		<td colspan="11" rowspan="9">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/她们">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_15.gif" width="94" height="47" border="0" alt=""></a></td>
		<td colspan="5" rowspan="21">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_16.gif" width="19" height="89" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="4" rowspan="16">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_17.gif" width="15" height="69" alt=""></td>
		<td colspan="5" rowspan="2">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/呵护">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_18.gif" width="28" height="14" border="0" alt=""></a></td>
		<td colspan="4" rowspan="16">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_19.gif" width="40" height="69" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="13" alt=""></td>
	</tr>
	<tr>
		<td colspan="16" rowspan="6">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_20.gif" width="108" height="26" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="5" rowspan="14">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_21.gif" width="28" height="55" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="7" alt=""></td>
	</tr>
	<tr>
		<td colspan="9" rowspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_22.gif" width="60" height="16" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="4" alt=""></td>
	</tr>
	<tr>
		<td colspan="26" rowspan="7">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_23.gif" width="190" height="26" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="11" alt=""></td>
	</tr>
	<tr>
		<td colspan="7" rowspan="8">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_24.gif" width="68" height="21" alt=""></td>
		<td colspan="3" rowspan="5">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/链接">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_25.gif" width="42" height="14" border="0" alt=""></a></td>
		<td rowspan="8">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_26.gif" width="7" height="21" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="18" rowspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_27.gif" width="142" height="9" alt=""></td>
		<td colspan="6" rowspan="17">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_28.gif" width="27" height="60" alt=""></td>
		<td colspan="8" rowspan="13">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/同事">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_29.gif" width="94" height="46" border="0" alt=""></a></td>
		<td rowspan="112">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_30.gif" width="51" height="530" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="3" rowspan="16">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_31.gif" width="18" height="58" alt=""></td>
		<td colspan="13" rowspan="10">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/光泽">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_32.gif" width="90" height="31" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="6" alt=""></td>
	</tr>
	<tr>
		<td colspan="11" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_33.gif" width="94" height="12" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="5" rowspan="14">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_34.gif" width="23" height="51" alt=""></td>
		<td colspan="4" rowspan="5">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/柔软">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_35.gif" width="28" height="14" border="0" alt=""></a></td>
		<td colspan="17" rowspan="7">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_36.gif" width="137" height="23" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="4" alt=""></td>
	</tr>
	<tr>
		<td colspan="3" rowspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_37.gif" width="42" height="7" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_38.gif" width="14" height="18" alt=""></td>
		<td colspan="4" rowspan="5">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/惊讶">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_39.gif" width="36" height="18" border="0" alt=""></a></td>
		<td colspan="20">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_40.gif" width="140" height="2" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="13" rowspan="6">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_41.gif" width="83" height="29" alt=""></td>
		<td colspan="6" rowspan="3">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/姐妹">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_42.gif" width="42" height="14" border="0" alt=""></a></td>
		<td rowspan="11">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_43.gif" width="15" height="44" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="4" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="23">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_44.gif" width="39" height="96" alt=""></td>
		<td colspan="16" rowspan="7">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/超市">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_45.gif" width="119" height="30" border="0" alt=""></a></td>
		<td colspan="4" rowspan="7">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_46.gif" width="53" height="30" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="3" alt=""></td>
	</tr>
	<tr>
		<td colspan="4" rowspan="9">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_47.gif" width="28" height="37" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="7" alt=""></td>
	</tr>
	<tr>
		<td colspan="6" rowspan="8">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_48.gif" width="42" height="30" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="14" rowspan="6">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_49.gif" width="112" height="23" alt=""></td>
		<td colspan="17" rowspan="10">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/洗发">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_50.gif" width="119" height="59" border="0" alt=""></a></td>
		<td colspan="5" rowspan="21">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_51.gif" width="39" height="87" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="13" rowspan="6">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_52.gif" width="90" height="27" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="12" alt=""></td>
	</tr>
	<tr>
		<td colspan="5" rowspan="6">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/漂亮">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_53.gif" width="48" height="25" border="0" alt=""></a></td>
		<td colspan="8" rowspan="9">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_54.gif" width="35" height="47" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="8" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_55.gif" width="94" height="24" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="4" alt=""></td>
	</tr>
	<tr>
		<td colspan="11">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/超市">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_45-57.gif" width="87" height="1" border="0" alt=""></a></td>
		<td colspan="11" rowspan="11">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/分享">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_57.gif" width="95" height="48" border="0" alt=""></a></td>
		<td colspan="3" rowspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_58.gif" width="9" height="10" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="11" rowspan="15">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_59.gif" width="87" height="65" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="4" alt=""></td>
	</tr>
	<tr>
		<td colspan="4" rowspan="19">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_60.gif" width="23" height="81" alt=""></td>
		<td colspan="4" rowspan="3">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/水润">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_61.gif" width="35" height="19" border="0" alt=""></a></td>
		<td colspan="6" rowspan="6">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_62.gif" width="54" height="38" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="5" alt=""></td>
	</tr>
	<tr>
		<td rowspan="34">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_63.gif" width="2" height="139" alt=""></td>
		<td colspan="24" rowspan="7">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/礼物">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_64.gif" width="143" height="36" border="0" alt=""></a></td>
		<td colspan="3" rowspan="31">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_65.gif" width="23" height="129" alt=""></td>
		<td colspan="4" rowspan="19">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_66.gif" width="15" height="80" alt=""></td>
		<td colspan="11" rowspan="11">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/喜欢">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_67.gif" width="96" height="48" border="0" alt=""></a></td>
		<td rowspan="17">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_68.gif" width="7" height="75" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="10" alt=""></td>
	</tr>
	<tr>
		<td colspan="5" rowspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_69.gif" width="48" height="22" alt=""></td>
		<td rowspan="16">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_70.gif" width="16" height="65" alt=""></td>
		<td colspan="6" rowspan="5">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/烫">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_71.gif" width="72" height="25" border="0" alt=""></a></td>
		<td rowspan="94">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_72.gif" width="6" height="460" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="4" alt=""></td>
	</tr>
	<tr>
		<td colspan="4" rowspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_73.gif" width="35" height="19" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="17" alt=""></td>
	</tr>
	<tr>
		<td colspan="17" rowspan="6">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_74.gif" width="119" height="8" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="3" rowspan="10">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_75.gif" width="33" height="27" alt=""></td>
		<td colspan="5" rowspan="6">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/典雅">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_76.gif" width="28" height="14" border="0" alt=""></a></td>
		<td colspan="5" rowspan="15">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_77.gif" width="22" height="48" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td rowspan="13">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_78.gif" width="10" height="43" alt=""></td>
		<td colspan="7" rowspan="11">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/她们">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_79.gif" width="58" height="29" border="0" alt=""></a></td>
		<td colspan="2" rowspan="13">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_80.gif" width="21" height="43" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="6" rowspan="11">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_81.gif" width="72" height="40" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="24" rowspan="9">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_82.gif" width="143" height="26" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="11" rowspan="7">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_83.gif" width="95" height="22" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="9">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_84.gif" width="17" height="37" alt=""></td>
		<td colspan="6" rowspan="3">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/熟悉">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_85.gif" width="28" height="14" border="0" alt=""></a></td>
		<td colspan="9" rowspan="11">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_86.gif" width="74" height="46" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="7" alt=""></td>
	</tr>
	<tr>
		<td colspan="5" rowspan="4">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_87.gif" width="28" height="13" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="11" rowspan="6">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_88.gif" width="96" height="27" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="5" alt=""></td>
	</tr>
	<tr>
		<td colspan="6" rowspan="18">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_89.gif" width="28" height="75" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="3" alt=""></td>
	</tr>
	<tr>
		<td rowspan="82">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_90.gif" width="28" height="414" alt=""></td>
		<td colspan="11" rowspan="13">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/很好">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_91.gif" width="96" height="47" border="0" alt=""></a></td>
		<td rowspan="21">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_92.gif" width="2" height="83" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="3" alt=""></td>
	</tr>
	<tr>
		<td colspan="3" rowspan="16">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_93.gif" width="17" height="69" alt=""></td>
		<td colspan="6" rowspan="8">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/期待">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_94.gif" width="60" height="31" border="0" alt=""></a></td>
		<td colspan="4" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_95.gif" width="23" height="21" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="4" rowspan="13">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_96.gif" width="28" height="50" alt=""></td>
		<td colspan="6" rowspan="6">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/精致">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_97.gif" width="60" height="29" border="0" alt=""></a></td>
		<td rowspan="19">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_98.gif" width="7" height="79" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="12" rowspan="8">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_99.gif" width="77" height="37" alt=""></td>
		<td colspan="10" rowspan="7">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/滋润">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_100.gif" width="59" height="30" border="0" alt=""></a></td>
		<td colspan="2" rowspan="15">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_101.gif" width="7" height="67" alt=""></td>
		<td colspan="7" rowspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_102.gif" width="58" height="14" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="13" alt=""></td>
	</tr>
	<tr>
		<td colspan="6" rowspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_103.gif" width="76" height="5" alt=""></td>
		<td colspan="8" rowspan="7">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/支持">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_104.gif" width="48" height="24" border="0" alt=""></a></td>
		<td colspan="5" rowspan="14">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_105.gif" width="67" height="54" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="13">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_106.gif" width="10" height="53" alt=""></td>
		<td colspan="14" rowspan="7">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/运气">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_107.gif" width="119" height="25" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="4" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="18">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_108.gif" width="12" height="76" alt=""></td>
		<td colspan="16" rowspan="8">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/迫不及待">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_109.gif" width="96" height="25" border="0" alt=""></a></td>
		<td rowspan="10">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_110.gif" width="28" height="39" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="5" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="10">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_111.gif" width="9" height="43" alt=""></td>
		<td colspan="4" rowspan="6">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/好奇">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_112.gif" width="36" height="18" border="0" alt=""></a></td>
		<td colspan="3" rowspan="10">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_113.gif" width="29" height="43" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="4" alt=""></td>
	</tr>
	<tr>
		<td colspan="6" rowspan="7">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_114.gif" width="60" height="21" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="6" rowspan="8">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_115.gif" width="60" height="38" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="10">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_116.gif" width="59" height="7" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="7" alt=""></td>
	</tr>
	<tr>
		<td colspan="6" rowspan="10">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_117.gif" width="27" height="40" alt=""></td>
		<td colspan="9" rowspan="8">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/朋友">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_118.gif" width="72" height="35" border="0" alt=""></a></td>
		<td colspan="7" rowspan="7">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_119.gif" width="37" height="30" alt=""></td>
		<td colspan="8" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_120.gif" width="48" height="20" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="14" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_121.gif" width="119" height="27" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="11" rowspan="7">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_122.gif" width="96" height="33" alt=""></td>
		<td colspan="4" rowspan="4">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_123.gif" width="36" height="25" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="16" rowspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_124.gif" width="96" height="14" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="5" alt=""></td>
	</tr>
	<tr>
		<td colspan="3" rowspan="6">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_125.gif" width="26" height="29" alt=""></td>
		<td colspan="5" rowspan="4">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/兴奋">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_126.gif" width="48" height="24" border="0" alt=""></a></td>
		<td colspan="2" rowspan="6">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_127.gif" width="14" height="29" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="9" alt=""></td>
	</tr>
	<tr>
		<td colspan="9" rowspan="8">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_128.gif" width="43" height="37" alt=""></td>
		<td colspan="10" rowspan="10">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/护发">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_129.gif" width="96" height="47" border="0" alt=""></a></td>
		<td colspan="6" rowspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_130.gif" width="33" height="10" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="9" alt=""></td>
	</tr>
	<tr>
		<td colspan="9">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_131.gif" width="71" height="1" alt=""></td>
		<td colspan="24" rowspan="8">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/星星火">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_132.gif" width="180" height="35" border="0" alt=""></a></td>
		<td colspan="5" rowspan="7">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_133.gif" width="47" height="28" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="19" rowspan="14">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/力士">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_134.gif" width="113" height="59" border="0" alt=""></a></td>
		<td colspan="4" rowspan="15">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_135.gif" width="35" height="71" alt=""></td>
		<td colspan="5" rowspan="10">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_136.gif" width="28" height="47" alt=""></td>
		<td colspan="5" rowspan="5">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/蛮好">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_137.gif" width="48" height="25" border="0" alt=""></a></td>
		<td rowspan="22">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_138.gif" width="24" height="91" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="5" alt=""></td>
	</tr>
	<tr>
		<td colspan="5" rowspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_139.gif" width="48" height="5" alt=""></td>
		<td colspan="8" rowspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_140.gif" width="66" height="5" alt=""></td>
		<td rowspan="13">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/力士">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_134-142.gif" width="6" height="54" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="3" rowspan="12">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_142.gif" width="22" height="52" alt=""></td>
		<td colspan="5" rowspan="2">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/棒">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_143.gif" width="42" height="14" border="0" alt=""></a></td>
		<td colspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_144.gif" width="32" height="3" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="3" alt=""></td>
	</tr>
	<tr>
		<td rowspan="11">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_145.gif" width="18" height="49" alt=""></td>
		<td colspan="22" rowspan="6">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/希望">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_146.gif" width="144" height="36" border="0" alt=""></a></td>
		<td colspan="7" rowspan="9">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_147.gif" width="62" height="45" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="11" alt=""></td>
	</tr>
	<tr>
		<td colspan="5" rowspan="10">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_148.gif" width="42" height="38" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="4" alt=""></td>
	</tr>
	<tr>
		<td colspan="5" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_149.gif" width="48" height="22" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="12">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_150.gif" width="24" height="55" alt=""></td>
		<td colspan="11" rowspan="7">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/推荐">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_151.gif" width="60" height="29" border="0" alt=""></a></td>
		<td colspan="3" rowspan="34">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_152.gif" width="18" height="148" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="7" alt=""></td>
	</tr>
	<tr>
		<td colspan="24" rowspan="4">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_153.gif" width="180" height="19" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="3" alt=""></td>
	</tr>
	<tr>
		<td colspan="10" rowspan="14">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_154.gif" width="96" height="54" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="9" alt=""></td>
	</tr>
	<tr>
		<td colspan="22" rowspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_155.gif" width="144" height="9" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td rowspan="12">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_156.gif" width="3" height="44" alt=""></td>
		<td colspan="8" rowspan="6">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/贴心">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_157.gif" width="60" height="29" border="0" alt=""></a></td>
		<td rowspan="12">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_158.gif" width="13" height="44" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="6" alt=""></td>
	</tr>
	<tr>
		<td colspan="7" rowspan="4">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_159.gif" width="59" height="18" alt=""></td>
		<td colspan="16" rowspan="7">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/非常">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_160.gif" width="108" height="29" border="0" alt=""></a></td>
		<td rowspan="7">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_161.gif" width="13" height="29" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="18" rowspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_162.gif" width="121" height="4" alt=""></td>
		<td colspan="10" rowspan="9">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/呵呵">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_163.gif" width="70" height="35" border="0" alt=""></a></td>
		<td rowspan="15">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_164.gif" width="15" height="52" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="11" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_165.gif" width="60" height="26" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="3" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="50">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_166.gif" width="17" height="282" alt=""></td>
		<td colspan="8" rowspan="3">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/泽塔琼斯">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_167.gif" width="72" height="18" border="0" alt=""></a></td>
		<td colspan="17" rowspan="9">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_168.gif" width="114" height="37" alt=""></td>
		<td colspan="20" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_169.gif" width="119" height="26" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="12" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="18">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_170.gif" width="17" height="63" alt=""></td>
		<td colspan="6" rowspan="10">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/感兴趣">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_171.gif" width="60" height="30" border="0" alt=""></a></td>
		<td colspan="3" rowspan="22">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_172.gif" width="17" height="81" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="5" alt=""></td>
	</tr>
	<tr>
		<td colspan="8" rowspan="6">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_173.gif" width="60" height="15" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="8" rowspan="4">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_174.gif" width="72" height="13" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="5" alt=""></td>
	</tr>
	<tr>
		<td colspan="15" rowspan="2">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/非常">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_160-176.gif" width="105" height="7" border="0" alt=""></a></td>
		<td colspan="13" rowspan="14">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/不错">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_176.gif" width="96" height="48" border="0" alt=""></a></td>
		<td colspan="2" rowspan="22">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_177.gif" width="4" height="93" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="3" alt=""></td>
	</tr>
	<tr>
		<td colspan="5" rowspan="8">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_178.gif" width="32" height="22" alt=""></td>
		<td colspan="11" rowspan="7">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/损伤">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_179.gif" width="54" height="18" border="0" alt=""></a></td>
		<td colspan="4" rowspan="14">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_180.gif" width="33" height="49" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="4" alt=""></td>
	</tr>
	<tr>
		<td colspan="15" rowspan="9">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_181.gif" width="105" height="22" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="3" rowspan="31">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_182.gif" width="17" height="136" alt=""></td>
		<td colspan="4" rowspan="9">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/精华">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_183.gif" width="48" height="25" border="0" alt=""></a></td>
		<td rowspan="15">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_184.gif" width="7" height="52" alt=""></td>
		<td colspan="10" rowspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_185.gif" width="70" height="10" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td rowspan="27">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_186.gif" width="4" height="120" alt=""></td>
		<td colspan="20" rowspan="13">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/活动">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_187.gif" width="192" height="47" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="5" alt=""></td>
	</tr>
	<tr>
		<td colspan="3" rowspan="13">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_188.gif" width="19" height="46" alt=""></td>
		<td colspan="5" rowspan="5">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/温馨">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_189.gif" width="28" height="14" border="0" alt=""></a></td>
		<td colspan="9">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_190.gif" width="67" height="4" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="4" alt=""></td>
	</tr>
	<tr>
		<td rowspan="12">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_191.gif" width="20" height="42" alt=""></td>
		<td colspan="9" rowspan="7">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/干净">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_192.gif" width="48" height="24" border="0" alt=""></a></td>
		<td colspan="9" rowspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_193.gif" width="69" height="7" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="6" rowspan="8">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_194.gif" width="60" height="33" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="11">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_195.gif" width="54" height="4" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="4" alt=""></td>
	</tr>
	<tr>
		<td colspan="5" rowspan="9">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_196.gif" width="37" height="35" alt=""></td>
		<td colspan="13" rowspan="8">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/购买">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_197.gif" width="90" height="31" border="0" alt=""></a></td>
		<td colspan="8" rowspan="6">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_198.gif" width="43" height="27" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="3" alt=""></td>
	</tr>
	<tr>
		<td colspan="5" rowspan="8">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_199.gif" width="28" height="32" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td rowspan="8">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_200.gif" width="1" height="41" alt=""></td>
		<td colspan="8" rowspan="5">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/适合">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_201.jpg" width="48" height="24" border="0" alt=""></a></td>
		<td colspan="6" rowspan="8">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_202.gif" width="56" height="41" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="4" alt=""></td>
	</tr>
	<tr>
		<td colspan="4" rowspan="6">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_203.gif" width="48" height="27" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="9" alt=""></td>
	</tr>
	<tr>
		<td colspan="9" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_204.gif" width="48" height="18" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="6" alt=""></td>
	</tr>
	<tr>
		<td colspan="13" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_205.gif" width="96" height="22" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="4" alt=""></td>
	</tr>
	<tr>
		<td colspan="3" rowspan="23">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_206.gif" width="16" height="123" alt=""></td>
		<td colspan="13" rowspan="9">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/开心">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_207.gif" width="95" height="48" border="0" alt=""></a></td>
		<td colspan="4" rowspan="4">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_208.gif" width="42" height="18" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="8" rowspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_209.gif" width="48" height="17" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="3" alt=""></td>
	</tr>
	<tr>
		<td colspan="13" rowspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_210.gif" width="90" height="24" alt=""></td>
		<td colspan="20" rowspan="4">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_211.gif" width="192" height="25" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="4" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="16">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_212.gif" width="8" height="84" alt=""></td>
		<td colspan="25" rowspan="9">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/效果">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_213.gif" width="191" height="48" border="0" alt=""></a></td>
		<td rowspan="14">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_214.gif" width="8" height="78" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="10" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="11">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_215.gif" width="18" height="58" alt=""></td>
		<td colspan="7" rowspan="4">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/大方">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_216.gif" width="48" height="24" border="0" alt=""></a></td>
		<td colspan="5" rowspan="11">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_217.gif" width="24" height="58" alt=""></td>
		<td colspan="13" rowspan="12">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/试用">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_218.gif" width="115" height="59" border="0" alt=""></a></td>
		<td colspan="8" rowspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_219.gif" width="55" height="23" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="10" alt=""></td>
	</tr>
	<tr>
		<td rowspan="12">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_220.gif" width="17" height="58" alt=""></td>
		<td colspan="11" rowspan="8">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/感谢">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_221.gif" width="72" height="36" border="0" alt=""></a></td>
		<td rowspan="18">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_222.gif" width="1" height="95" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="10">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_223.gif" width="27" height="48" alt=""></td>
		<td colspan="6" rowspan="3">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/旅游">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_224.gif" width="53" height="19" border="0" alt=""></a></td>
		<td colspan="12" rowspan="4">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_225.gif" width="112" height="24" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="12" alt=""></td>
	</tr>
	<tr>
		<td colspan="5" rowspan="14">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_226.gif" width="40" height="74" alt=""></td>
		<td colspan="7" rowspan="4">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/神奇">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_227.gif" width="28" height="14" border="0" alt=""></a></td>
		<td rowspan="9">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_228.gif" width="9" height="36" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="7" rowspan="7">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_229.gif" width="48" height="34" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="6" alt=""></td>
	</tr>
	<tr>
		<td colspan="13" rowspan="6">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_230.gif" width="95" height="28" alt=""></td>
		<td colspan="6" rowspan="7">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_231.gif" width="53" height="29" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="5" alt=""></td>
	</tr>
	<tr>
		<td colspan="9" rowspan="6">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_232.gif" width="64" height="24" alt=""></td>
		<td colspan="3" rowspan="6">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/舒服">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_233.gif" width="48" height="24" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="7" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_234.gif" width="28" height="22" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="25" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_235.gif" width="191" height="30" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="8" alt=""></td>
	</tr>
	<tr>
		<td colspan="11">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_236.gif" width="72" height="10" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="10" alt=""></td>
	</tr>
	<tr>
		<td colspan="6" rowspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_237.gif" width="49" height="12" alt=""></td>
		<td colspan="4" rowspan="4">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/灵">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_238.gif" width="14" height="13" border="0" alt=""></a></td>
		<td rowspan="9">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_239.gif" width="9" height="49" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td colspan="8" rowspan="8">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_240.gif" width="52" height="47" alt=""></td>
		<td colspan="17" rowspan="5">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/新活炫亮">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_241.gif" width="120" height="31" border="0" alt=""></a></td>
		<td colspan="2" rowspan="16">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_242.gif" width="13" height="131" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="13" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_243.gif" width="115" height="38" alt=""></td>
		<td colspan="4" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_244.gif" width="17" height="38" alt=""></td>
		<td colspan="16" rowspan="4">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/机会">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_245.gif" width="120" height="30" border="0" alt=""></a></td>
		<td colspan="9" rowspan="15">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_246.gif" width="96" height="130" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="9" alt=""></td>
	</tr>
	<tr>
		<td colspan="18" rowspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_247.gif" width="156" height="6" alt=""></td>
		<td colspan="10" rowspan="5">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/很多">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_248.gif" width="70" height="36" border="0" alt=""></a></td>
		<td colspan="5" rowspan="14">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_249.gif" width="39" height="121" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="4" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_250.gif" width="14" height="36" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="5" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="12">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_251.gif" width="10" height="115" alt=""></td>
		<td colspan="10" rowspan="7">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/顺滑">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_252.gif" width="96" height="46" border="0" alt=""></a></td>
		<td colspan="11" rowspan="12">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_253.gif" width="75" height="115" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="15" alt=""></td>
	</tr>
	<tr>
		<td colspan="17" rowspan="4">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_254.gif" width="120" height="24" alt=""></td>
		<td colspan="16" rowspan="7">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_255.gif" width="120" height="35" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="8" alt=""></td>
	</tr>
	<tr>
		<td colspan="4" rowspan="10">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_256.gif" width="47" height="92" alt=""></td>
		<td colspan="16" rowspan="7">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/干燥">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_257.gif" width="120" height="30" border="0" alt=""></a></td>
		<td colspan="2" rowspan="10">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_258.gif" width="5" height="92" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="7" alt=""></td>
	</tr>
	<tr>
		<td colspan="10" rowspan="9">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_259.gif" width="70" height="85" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td rowspan="8">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_260.gif" width="2" height="84" alt=""></td>
		<td colspan="11" rowspan="2">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/感情">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_261.gif" width="56" height="14" border="0" alt=""></a></td>
		<td colspan="5" rowspan="8">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_262.gif" width="34" height="84" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="8" alt=""></td>
	</tr>
	<tr>
		<td colspan="4" rowspan="7">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_263.gif" width="27" height="76" alt=""></td>
		<td colspan="5" rowspan="5">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/给力">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_264.gif" width="58" height="30" border="0" alt=""></a></td>
		<td colspan="8" rowspan="7">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_265.gif" width="35" height="76" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="6" alt=""></td>
	</tr>
	<tr>
		<td colspan="11" rowspan="6">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_266.gif" width="56" height="70" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="10" rowspan="5">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_267.gif" width="96" height="69" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="4" alt=""></td>
	</tr>
	<tr>
		<td colspan="10" rowspan="4">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_268.gif" width="72" height="65" alt=""></td>
		<td colspan="6" rowspan="3">
			<a href="<?php echo $this->baseUrl();?>/dashboard/clientreport/id/8/searchText/免费">
				<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_269.gif" width="48" height="24" border="0" alt=""></a></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="3" alt=""></td>
	</tr>
	<tr>
		<td colspan="16" rowspan="3">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_270.gif" width="120" height="62" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="16" alt=""></td>
	</tr>
	<tr>
		<td colspan="5" rowspan="2">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_271.gif" width="58" height="46" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="5" alt=""></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/jbt_272.gif" width="48" height="41" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="41" alt=""></td>
	</tr>
	<tr>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="28" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="11" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="6" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="5" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="5" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="7" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="6" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="2" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="22" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="18" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="7" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="7" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="2" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="10" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="15" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="2" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="4" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="6" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="20" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="16" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="11" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="3" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="7" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="2" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="3" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="4" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="16" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="2" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="4" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="7" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="8" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="17" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="10" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="4" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="15" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="6" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="13" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="2" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="10" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="9" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="2" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="5" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="9" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="9" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="5" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="4" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="6" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="3" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="10" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="10" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="5" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="8" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="12" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="5" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="2" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="16" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="10" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="8" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="13" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="11" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="6" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="8" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="3" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="6" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="5" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="5" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="8" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="5" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="9" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="9" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="13" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="16" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="2" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="11" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="3" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="11" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="3" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="13" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="9" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="15" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="17" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="5" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="10" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="2" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="6" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="5" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="7" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="3" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="2" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="2" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="8" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="9" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="4" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="26" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="15" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="5" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="28" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="3" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="12" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="3" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="1" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="7" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="16" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="5" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="12" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="7" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="11" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="13" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="24" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="6" height="1" alt=""></td>
		<td>
			<img src="<?php echo $this->baseUrl();?>/images/tagcloud/8/blank.gif" width="51" height="1" alt=""></td>
		<td></td>
	</tr>
</table>