<?php if (count($this->activeCampaigns)>0):?>
<div class="article-box"><div class="article-box-inner">
<div class="images-column"><img
	src="<?php echo $this->baseUrl();?>/images/training_campaign.gif"
	style="padding: 0; border: 0; margin-right: 10px;background:none;" /></div>
<div class="main-column" style="width:450px;">
<h2><?php echo $this->translate('Active_Campaign');?></h2>
<ul class="invited">
<?php foreach($this->activeCampaigns as $campaign) : ?>
	<li><a
		href="<?php echo $this->url(array('controller'=>'campaign',
		'action'=>'description', 'id'=>$campaign['campaign_id']));?>"> <!--<?php echo $campaign['name']?>
		--><!--
		- <?php echo $this->translate("Campaign_simple_description_".$campaign['campaign_id'])?>
		-->
		<?php echo $campaign['simple_description']?>
	</a></li>
	<?php endforeach; ?>
</ul>
</div>
<div style="clear: both;"></div>
</div></div>
	<?php endif?>

	<?php if (count($this->campaignInvitations)):?>
	<?php foreach($this->campaignInvitations as $campaignInvitation) : ?>
<div class="article-box" style=""><div class="article-box-inner" style="">
<div class="images-column"><img
	src="<?php echo $this->baseUrl();?>/images/campaign/campaign_<?php echo $campaignInvitation['campaign_id']?>_03.jpg" /><img
	src="<?php echo $this->baseUrl();?>/images/campaign/campaign_<?php echo $campaignInvitation['campaign_id']?>_04.jpg" /></div>
<div class="main-column" style="width: 320px;">
<h2><?php echo $this->translate('INDEX_YOU_ARE_INVITED')?> <?php echo $campaignInvitation['name']?>
</h2>
<br/>
<p><?php echo $campaignInvitation['invitation_description']?>
</p>
<br/>
<p><?php echo $campaignInvitation['invitation_description2']?></p>
</div>
<div class="buttons-2lines"><a
	href="<?php echo $this->url(array('controller'=>'campaign','action'=>'precampaign', 'id'=>$campaignInvitation['campaign_id']));?>"><?php echo $this->translate('Accept');?></a>
<a
	href="<?php echo $this->url(array('controller'=>'campaigninvitation','action'=>'prereject', 'id'=>$campaignInvitation['campaign_id']));?>"><?php echo $this->translate('Reject');?></a>
</div>
<div style="clear: both"></div>

</div></div>
	<?php endforeach; ?>
	<?php else:?>
<div class="article-box"><div class="article-box-inner">
<div class="images-column"><img
	src="<?php echo $this->baseUrl();?>/images/campaign-invitations.gif"
	style="padding: 0; border: 0; margin-right: 10px;" /></div>
<div class="main-column" style="width:500px">
<h2><?php if (count($this->activeCampaigns)>0):?><?php echo $this->translate('INDEX_SPARK_CAMPAIGN_INVITATION_OTHER');?><?php endif?><?php echo $this->translate('INDEX_SPARK_CAMPAIGN_INVITATION_HEADER');?></h2>
<p style=""><?php echo $this->translate('INDEX_SPARK_CAMPAIGN_INVITATION_CONTENT1');?><?php if (count($this->activeCampaigns)>0):?><?php echo $this->translate('INDEX_SPARK_CAMPAIGN_INVITATION_OTHER_NotCapital');?><?php endif?><?php echo $this->translate('INDEX_SPARK_CAMPAIGN_INVITATION_CONTENT2');?>
</p>
</div>
<div style="clear: both;"></div>
</div></div>
	<?php endif?>

<div class="article-box"><div class="article-box-inner">
<h3><?php echo $this->translate('INDEX_LOOK_FOR_FUN');?></h3>
<p><?php echo $this->translate('INDEX_LOOK_FOR_FUN_CONTENT_PART1');?> <a
	href="<?php echo $this->url(array('controller'=>'profilesurvey','action'=>'index'));?>"><?php echo $this->translate('INDEX_LOOK_FOR_FUN_CONTENT_PART2');?></a>
	<?php echo $this->translate('INDEX_LOOK_FOR_FUN_CONTENT_PART3');?> <a
	href="<?php echo $this->url(array('controller'=>'training','action'=>'index'));?>"><?php echo $this->translate('INDEX_LOOK_FOR_FUN_CONTENT_PART4');?></a>
	<?php echo $this->translate('INDEX_LOOK_FOR_FUN_CONTENT_PART5');?></p>
</div></div>
<script type='text/javascript'>
//<![CDATA[
function acceptInvitation(id){
	url="<?php echo $this->url(array('controller'=>'campaigninvitation','action'=>'accept'));?>";
	var params = 'id='+id;
	// notice the use of a proxy to circumvent the Same Origin Policy. 
	new Ajax.Request(url, 
			{
				method: 'get',   
				parameters:params,
				onSuccess: function(transport) {
				     var tr = $('tr_'+id);    
				     tr.innerHTML = transport.responseText;
				}
	}); 
}

function rejectInvitation(id){
	url="<?php echo $this->url(array('controller'=>'campaigninvitation','action'=>'reject'));?>";
	var params = 'id='+id;
	// notice the use of a proxy to circumvent the Same Origin Policy. 
	new Ajax.Request(url, 
			{
				method: 'get',   
				parameters:params,
				onSuccess: function(transport) {
				     var tr = $('tr_'+id);    
				     tr.innerHTML = transport.responseText;
				}
	}); 
}
//]]>
</script>
