
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/mission.css" />

	<div class="content">
		<!-- menu bar-->
		<!--
		<div class="bar">
			<ul>

				<li class="slogan">bridge brands and influencers</li>

				<li><a href="#" accesskey="i">Internet</a></li>
				<li class="active">People</li>
				<li><a href="#" accesskey="m">Music</a></li>
				<li><a href="#" accesskey="p">Pictures</a></li>
				<li><a href="#" accesskey="s">Services</a></li>
				<li><a href="#" accesskey="r">Products</a></li>

			</ul>
		</div>
		-->

        <?php include('./mission/mission_' . $this->campaign_id . '.phtml');?>

		<div class="bottom">
		<!--  
			-->
		</div>

	</div>
<script language="javascript">

var campaign_id;
function showtip(id){
	var tip = $("tip"+id);
	Element.show(tip);
}

function hidetip(id){
	var tip = $("tip"+id);
	Element.hide(tip);
}

function hideAllUlTabs(){
	var count =  2;
	for (var i=1;i<=count;i++){
		Element.hide("ul_tab_"+i);
		$('campaign_'+i).removeClassName('active');
	}
}

function showUlTab(id){
	hideAllUlTabs();
	var tab = $("ul_tab_"+id);
	Element.show(tab);
	$('campaign_'+id).addClassName('active');

}

function submitURL(campaignId){
	campaign_id = campaignId;
	var url = '/wildfire/public/report/ajaxstoreurl';
	var pars = 'campaignId='+campaignId+'&url='+base64encode($('url_'+campaignId).value);
//	alert(pars);
//	return;
	new Ajax.Request(    
		url,
		{
		method: 'get',      
		parameters: pars,    
		onSuccess: updateURL    
		}
	);
}
var base64EncodeChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
var base64DecodeChars = new Array(
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 62, -1, -1, -1, 63,
    52, 53, 54, 55, 56, 57, 58, 59, 60, 61, -1, -1, -1, -1, -1, -1,
    -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
    15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, -1, -1, -1, -1, -1,
    -1, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
    41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, -1, -1, -1, -1, -1);
function base64encode(str) {
    var out, i, len;
    var c1, c2, c3;

    len = str.length;
    i = 0;
    out = "";
    while(i < len) {
    c1 = str.charCodeAt(i++) & 0xff;
    if(i == len)
    {
        out += base64EncodeChars.charAt(c1 >> 2);
        out += base64EncodeChars.charAt((c1 & 0x3) << 4);
        out += "==";
        break;
    }
    c2 = str.charCodeAt(i++);
    if(i == len)
    {
        out += base64EncodeChars.charAt(c1 >> 2);
        out += base64EncodeChars.charAt(((c1 & 0x3)<< 4) | ((c2 & 0xF0) >> 4));
        out += base64EncodeChars.charAt((c2 & 0xF) << 2);
        out += "=";
        break;
    }
    c3 = str.charCodeAt(i++);
    out += base64EncodeChars.charAt(c1 >> 2);
    out += base64EncodeChars.charAt(((c1 & 0x3)<< 4) | ((c2 & 0xF0) >> 4));
    out += base64EncodeChars.charAt(((c2 & 0xF) << 2) | ((c3 & 0xC0) >>6));
    out += base64EncodeChars.charAt(c3 & 0x3F);
    }
    return out;
}
function updateURL(originalRequest){
	if(originalRequest.responseText){
		$('url_report_notice_'+campaign_id).innerHTML = '你已提交成功，请等待审核';
		$('url_report_submit_'+campaign_id).style.display = "none";
	}
}

var getWidth = function() {
	var w = window;
	var d = document;
	var dd = d.documentElement;
	var width;
	
	if (w.innerWidth)
		width = w.innerWidth;
	else if (dd && dd.clientWidth)
		width = dd.clientWidth;
	else if(d.body)
		width = d.body.clientWidth;
	
	return width;
}
var getHeight = function() {
	var w = window;
	var d = document;
	var dd = d.documentElement;
	var height;
	
	if (w.innerHeight) 
		height = w.innerHeight;
	else if (dd && dd.clientHeight)
		height = dd.clientHeight;  
	else if (d.body)
		height = d.body.clientHeight;
	
	return height;
}
var WebDialog = {
	count:0,
	showpointer:1,
	list:{},
	element : $('web-dialog'),
	onok : function() {},
	oncancel : function() {},
	show : function() {
		var width = document.body.clientWidth;
		width = getWidth();
		var height = document.body.offsetHeight;
		height = getHeight();
		var left = (width - this.element.offsetWidth) / 2;
		var top = (height - this.element.offsetHeight) / 2;
		if (top < 200) {
			top = 200;
		}
		this.element.style.left = left + "px";
		this.element.style.top = top + "px";
	},
	alert : function(msg,agree,disagree,onok,oncancel) {
		var buttons = ["OK","Cancel"];
		var callbacks = [onok, oncancel];
		this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
	},
	ok : function() {
		this.onok();
	},
	close : function() {
					
		Element.hide(this.list[this.showpointer]);
		this.showpointer++;
		if (this.count<this.showpointer){	
			$('mask').hide();
		}else{
			Element.show(this.list[this.showpointer]);
		}
		this.oncancel();
	},
	showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions,elem) {
		// icon_type : "none", "alert", "question"
		// msg_align : "left", "center", "right"
		// width : -1 means auto
		if (elem!=null){
			this.element = $(elem);
		}
		this.count++;
		this.list[this.count] = this.element;
		var width = getWidth();
		var height = getHeight();
		var left = (width - window_width) / 2;
		var top = (height - 250) / 2;
		var pos = 0;
		if (window.innerHeight) {
	    	pos = window.pageYOffset
	    } else if (document.documentElement && document.documentElement.scrollTop) {
	    	pos = document.documentElement.scrollTop
	    } else if (document.body) {
	    	pos = document.body.scrollTop;
	    }
	    top += pos;
		/*
		if (top < 200) {
			top = 200;
		}
		*/
		this.element.style.left = left + "px";
		this.element.style.top = top + "px";
		if (this.count==1){
			this.element.show();
		}
		$('mask').style.width = width + "px";
		$('mask').style.height = height + "px";
		$('mask').show();
	}
}


var html = "aaa";
var buttons = ['aaa','bbb'];
var callbacks = [function(){},function(){}];
	


jQuery(document).ready(function(){
jQuery('#fillout-dialog').dialog({dialogClass: 'ui-fillout-dialog', bgiframe: true, autoOpen: false, resizable: false, modal: true, width: 680, height: 600, title: '提交报告完成任务' });
jQuery('#check-alert-dialog').dialog({title:'错误', bgiframe: true, autoOpen: false, resizable: false, modal: true, buttons: {
		'确定': function() {
			jQuery(this).dialog('close');
		}
	}
});

var button_11 = jQuery("#uploadFile_11"), interval;
//var image_thumb_11 = jQuery("#image_thumb_11"), interval;
new AjaxUpload(button_11,{
    //action: 'upload-test.php', // I disabled uploads in this example for security reasons
    action: '/wildfire/public/report/ajaxstoreimage', 
    //name: 'myfile',
    data: {
        campaign_id : 11    },
    //responseType: 'json',
    onSubmit : function(file, ext){
        if (! (ext && /^(jpg|png|jpeg|gif)$/.test(ext))){
            // extension is not allowed
           jQuery('div#error').text("请上传正确的图片").show().fadeOut(5000);
           // cancel upload
           return false;
        }
    
        // change button text, when user selects file           
        button_11.text('uploading');
        
        // If you want to allow uploading only 1 file at time,
        // you can disable upload button
        this.disable();
    },
    onComplete: function(file, response){
        button_11.text("上传照片");
        // enable upload button
        this.enable();
        eval(response);
    }
});
var button_9 = jQuery("#uploadFile_9"), interval;
//var image_thumb_9 = jQuery("#image_thumb_9"), interval;
new AjaxUpload(button_9,{
    //action: 'upload-test.php', // I disabled uploads in this example for security reasons
    action: '/wildfire/public/report/ajaxstoreimage', 
    //name: 'myfile',
    data: {
        campaign_id : 9    },
    //responseType: 'json',
    onSubmit : function(file, ext){
        if (! (ext && /^(jpg|png|jpeg|gif)$/.test(ext))){
            // extension is not allowed
           jQuery('div#error').text("请上传正确的图片").show().fadeOut(5000);
           // cancel upload
           return false;
        }
    
        // change button text, when user selects file           
        button_9.text('uploading');
        
        // If you want to allow uploading only 1 file at time,
        // you can disable upload button
        this.disable();
    },
    onComplete: function(file, response){
        button_9.text("上传照片");
        // enable upload button
        this.enable();
        eval(response);
    }
});

});

var filloutDialogOpen = function(url) {
jQuery("#fillout-dialog .content").load(url,function(){
});
jQuery("#fillout-dialog").dialog('open');
}
var currentReportPanel = 0;
var showReportPanel = function(panelId) {
var panels = new Array('.submit-report','.uploading-image','.submit-url');
var buttons = new Array('.button-submit-report img','.button-upload-image img','.button-submit-url img');
var buttonsGrey = new Array('tab_button_report_grey.png','tab_button_photo_grey.png','tab_button_url_grey.png');
var buttonsBlue = new Array('tab_button_report_blue.png','tab_button_photo_blue.png','tab_button_url_blue.png');
jQuery(panels[currentReportPanel]).hide();
jQuery(buttons[currentReportPanel]).attr("src","/wildfire/public/images/"+buttonsGrey[currentReportPanel]);
jQuery(buttons[panelId]).attr("src","/wildfire/public/images/"+buttonsBlue[panelId]);
jQuery(panels[panelId]).show('slide');
currentReportPanel = panelId;
}

function move_down(e) {
  var parent = jQuery(jQuery(e).parent());
  if(parent.next().next().attr('class')) {
      parent.hide();
      parent.next().hide();
  	  parent.next().next().show();	
      parent.next().next().next().show();	
  } else {
  	jQuery('div#error').text("已经是最后一个了").show().fadeOut(5000);
  }
}

function move_up(e) {
  var parent = jQuery(jQuery(e).parent());
  if(parent.prev().prev().attr('class')) {
    parent.hide();
    parent.next().hide();
  	parent.prev().show();	
    parent.prev().prev().show();
  } else {
  	jQuery('div#error').text("已经是第一个了").show().fadeOut(5000);
  }
}
</script>
		<div id="fillout-dialog">
<div class="content"></div>
</div>

<script language="text/javascript">
jQuery('#ui-dialog-title-fillout-dialog').html('填写问卷完成任务');
</script>