
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/mission.css" />
    <?php
        if ($this->jQuery()->isEnabled()) {
            $this->jQuery()->addStylesheet($this->baseUrl() . '/css/smoothness/jquery-ui-1.7.2.custom.css')
                           ->setLocalPath($this->baseUrl() . '/js/jquery-1.3.2.min.js')
                           ->setUiLocalPath($this->baseUrl() . '/js/jquery-ui-1.7.2.custom.min.js');
            echo $this->jQuery();
        }
    ?>

	<div class="content">
		<!-- 
		<div class="header">
			<div class="top_info">
				<div class="top_info_right">
					<p><b>You are not Logged in!</b> <br />
					Do you want to <a href="#">Log in</a> or <a href="#">register</a>?</p>
				</div>
				<div class="top_info_left">
					<p>Today is: <b>27th January, 2006</b><br />
					Check <a href="#">brands</a> or <a href="#">todays missions</a></p>
				</div>
			</div>
			<div class="logo">
				<h1><a href="#" title="Centralized Internet Content">XXH Logo</a></h1>
			</div>
		</div>
		 -->
		<!-- menu bar-->
		<!--
		<div class="bar">
			<ul>

				<li class="slogan">bridge brands and influencers</li>

				<li><a href="#" accesskey="i">Internet</a></li>
				<li class="active">People</li>
				<li><a href="#" accesskey="m">Music</a></li>
				<li><a href="#" accesskey="p">Pictures</a></li>
				<li><a href="#" accesskey="s">Services</a></li>
				<li><a href="#" accesskey="r">Products</a></li>

			</ul>
		</div>
		-->
		<div class="search_field">
			<p>Brand Missions is a website that you can play with the <a>bigest brands in the world</a>, leverage them as an <a>influencer</a> and earn <a>rewards</a></p>
		</div>
		<div class="subheader">
			<p>Simple Instruction: sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex.</p>
		</div>
		<div class="left">
			<div class="left_articles">
				<h2><a href="#">Newest Missions</a></h2>
				<!-- new mission list-->
                <?php foreach($this->missions as $mission) { ?>
                <div class="left_message" style="background: #fff url(<?php echo $this->baseUrl();?>/images/mission/type_<?php echo strtolower($mission->type);?>.png) no-repeat center left;">
					<p><a  href="<?php echo $this->url(array('controller'=>'mission','action'=>'description','id'=>$mission->id));?>" style="color:#FE6700;font-weight:bold;"><?php echo $this->escape($mission->title);?></a>&nbsp;<?php echo $this->escape($mission->intro);?></p>
				</div>
                <?php } ?>
				<!-- new mission list end-->
			</div>
            <div class="left_links">
                <div class="left_side">
                    <div style="float: left;">
                        <img src="<?php echo $this->url(array('controller'=>'brand','action'=>'getimage','id'=>$this->brands[0]->id));?>" alt="" style="float: left; width: 90px;" />
                    </div>
                    <div style="float: left;">
                    <?php foreach ($this->brands[0]->getTopMissions() as $mission) { ?>
                        <a href="<?php echo $this->url(array('controller'=>'mission','action'=>'description','id'=>$mission->id));?>"><?php echo $this->escape($mission->title);?></a><br/>
                    <?php } ?>
                    </div>
                </div>
                <div class="right_side">
                    <div style="float: left;">
                        <img src="<?php echo $this->url(array('controller'=>'brand','action'=>'getimage','id'=>$this->brands[1]->id));?>" alt="" style="float: left; width: 90px;"/>
                    </div>
                    <div style="float: left;">
                    <?php foreach ($this->brands[1]->getTopMissions() as $mission) { ?>
                        <a href="<?php echo $this->url(array('controller'=>'mission','action'=>'description','id'=>$mission->id));?>"><?php echo $this->escape($mission->title);?></a><br/>
                    <?php } ?>
                    </div>
                </div>
				<p><b><a href="#">see all brands and missions</a></b></p>
			</div>

			<div class="left_box">
				<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex.</p>
			</div>
		</div>
		<div class="right">
			<!-- 
			<div class="right_login">
				<form action="?" method="post">
					<p>Username: <input type="text" class="login" name="search" /></p>
					<p>Password: <input type="password" class="login" name="search"/> <input type="submit" class="searchSubmit" value="Login"/></p>
				</form>
			</div>
			 -->
			<!-- hero sparks -->
			<div class="right_articles">
				<b>Liukai completed mission <a style="color:#FE6700;font-weight:bold;">take photo in club</a></b><br />
				<p>
				<img style="height:60px;weight:60px;"  src="<?php echo $this->baseUrl();?>/images/mission/profile_1.jpg" alt="Image" title="Image" class="image" />
				<img style="height:60px;weight:60px;" src="<?php echo $this->baseUrl();?>/images/mission/proof_1.jpg" alt="Image" title="Image" class="image" />
				<img style="height:60px;weight:60px;" src="<?php echo $this->baseUrl();?>/images/mission/proof_2.jpg" alt="Image" title="Image" class="image" />
				</p>
			</div>

			<div class="right_articles">
				<b>betty completed <a style="color:#FE6700;font-weight:bold;">choose big idea for Campbells</a></b><br />
				<p>
				<img style="height:60px;weight:60px;"  src="<?php echo $this->baseUrl();?>/images/mission/profile_2.jpg" alt="Image" title="Image" class="image" />
				I like the idea of "being good mom", I don't think making foods is any more important than spending time with your kids.
				</p>
			</div>

			<div class="right_articles">
				<b>PY completed mission <a style="color:#FE6700;font-weight:bold;">share with your friends</a></b><br />
				<p>
				<img style="height:60px;weight:60px;"  src="<?php echo $this->baseUrl();?>/images/no_photo_male.jpg" alt="Image" title="Image" class="image" />
				<img src="<?php echo $this->baseUrl();?>/images/mission/image.gif" alt="Image" title="Image" class="image" />
				</p>
			</div>
			<!-- hero sparks end -->
		</div>
		<div class="footer">
			<p><a href="#">RSS Feed</a> | <a href="#">Contact</a> | <a href="#">Accessibility</a> | <a href="#">Products</a> | <a href="#">Disclaimer</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> and <a href="http://validator.w3.org/check?uri=referer">XHTML</a><br />
			&copy; Copyright 2006 Internet Center, Design: Luka Cvrk, <a title="Awsome Web Templates" href="http://www.solucija.com/">Solucija</a></p>
		</div>

	</div>
