<img src="<?php echo $this->baseUrl();?>/images/popup-fillout-logo.gif" class="logo"/>
<div class="top-content" >
<h1><?php echo ' "'.$this->campaing_name.'" '; ?></h1>

<?php if ($this->surveyId=='631'){?>
<p>我们建议这个创意故事包含以下几个要素：<br/>
参与的人<br/>
与百利的发生的故事（例如用百利做布丁、蛋糕的过程）<br/>
怎样谈论百利的<br/>
你的百利创意搭配<br/>
任何关于口味及搭配的建议<br/>
你们和百利创意照片<br/>

请记住，只有同时提交故事及照片才能获得400积分及参加“百利达人”的评选哦！</p>
<?php }elseif ($this->surveyId=='675'){?>
<p>
你身边有可爱的宝宝嘛？<br/>
你自己的？你亲戚？你同事的？你朋友的？<br/>
那就来参加星星火宝宝秀任务吧！<br/>
至少2张宝宝（或宝宝和家人）的照片<br/>
</p>
<?php }elseif ($this->surveyId == '689'){?>
<p>
你是走街串巷寻找美食的吃货一族？<br>
还是喜爱边走边拍彻头彻尾的微博控？<br>
无论你是哪一种潮流人物，只要善于发现、乐于分享。<br>
星星火新mission——“寻找美食之旅”等待的就是你！<br>
</p>
<?php }elseif ($this->surveyId == '693'){?>
<p>
先有猫叔，后有俊介君，日本两大萌宠秒杀无数人。<br>
星星火来发掘我们自己身边的宠物明星，<br>
它可以是乖巧的、聪明的、调皮的、卖萌的、2的，甚至是贱贱的，<br>
我们来者不拒。快来跟我们分享你和它之间的故事吧，<br>
你们是怎么认识的，它带给你的快乐、感动，<br>
亦或者它的捣蛋事迹，甚至是让你抓狂的事情。<br>
记得还要附上两张宠物的照片哦~！

</p>
<?php }elseif ($this->surveyId == '701'){?>
<p>
写下第一次接触星星火的时间、地点、人物，<br>
并简单的介绍下所参加活动后的感受，以及对我们的评价与期望。<br>
（任何形式的盗用和网上下载的照片将不参加本次评比。）<br>
我们会根据每份报告和照片的质量给予相对应的积分。<br>
对于符合条件且有创意的照片和故事，最高可获得500个积分，<br>
积分积累的越多就能兑换更多新奇好玩的礼品啦！


</p>
<?php }elseif ($this->surveyId == '703'){?>
<p>
只要在12月3日前完成相应的任务并且确认提交，<br>
你就能获得400积分。积分可以用来兑换很多你心仪的礼品！<br>
<p style="color:red">提交成功后将调转到星星火首页</p>
</p>
<?php }elseif ($this->surveyId == '750'){?>
<p>
亲曾经送过什么礼物给父母？还记得第一次送礼物是什么时候，<br>
送了什么东西么？今年，是否已经有打算了呢？是准备给父母一个惊喜呢，<br>
还是直接带着父母，像朋友一样一起去逛街淘宝SHOPPING，<br>
享受一下呢~亲来和我们说说吧~<br><br>

<p style="color:red">提交完成后可继续上传照片</p>
</p>
<?php }elseif ($this->surveyId == '752'){?>
<p>
和星星火一起寻找身边的宠物明星<br>
自家的、朋友的、亲戚的、路上偶遇的，猫猫狗狗、仓鼠兔子、蜥蜴乌龟。<br>
它可以是乖巧的、聪明的、调皮的、卖萌的、天然呆的，甚至是贱贱的，我们统统来者不拒。<br>
和它初见时的朦胧、贴心时的感动、捣蛋后的抓狂、分离时的痛苦。<br>
相信喜爱宠物的你总有一段又一段和宝贝之间说不完道不尽的故事。
<br><br>

<p style="color:red">提交完成后可继续上传照片</p>
</p>
<?php }elseif ($this->surveyId == '753'){?>
<p>
又到毕业季,“遗憾体”风行网络，你的大学有过遗憾吗？<br>
有童鞋吐槽说: 没谈过恋爱，没表白，减肥没成功，没有去旅行，没有疯狂过，没有挂科……，；<br>
还有的说:DOTA不够犀利,WOW没毕业，三国杀没升到150级……。<br>
看着一张张手写的遗憾，真的被感动到了。<br>
也许大学有很多遗憾，很多不舍，但是却让我们成长至今，虽然遗憾但不后悔。<br>
致我们的大学，结束和未结束的……<br>
<br><br>

<p style="color:red">提交完成后可继续上传照片</p>
</p>
<?php }elseif ($this->surveyId == '754'){?>
<p>
不管是到路边大排档，还是高档餐厅，<br>
都可以来分享，美食不问出处。<br>
记录下其所在地区，尝味时间，和你一起分享的人，<br>
并且简单的介绍一下口感等，说说自己的评价~<br>
关于社区，有任何疑问或问题，还可以通过新浪微博联系我们，<br>
星星火社区新浪微博<a href="http://weibo.com/xxhuo">http://weibo.com/xxhuo</a><br>
<br><br>

<p style="color:red">提交完成后可继续上传照片</p>
</p>
<?php }elseif ($this->surveyId == '768'){?>
<p>
那些记载在胶片上的故事哪些触动了你的灵魂，<br>
哪些温暖了你的心房，<br>哪些消磨了你的时光，<br>又有哪些已被你遗忘？<br><br>
无论是已经下档的还是正在热映的，星星火都期待你的分享。<br><br>
关于社区，有任何疑问或问题，还可以通过新浪微博联系我们，<br>
星星火社区新浪微博<a href="http://weibo.com/xxhuo">http://weibo.com/xxhuo</a><br>
<br><br>

<p style="color:red">提交完成后可继续上传照片</p>
</p>
<?php } ?>


</div>
<div class="clear"></div>


<?php 
include('../public/surveys/'.$this->file);
?>

<?php if (isset($this->file)) { ?>
<script language="JavaScript" type="text/javascript">
  $('id').value = '';
  $('submit').disabled='disabled';
  var url = "<?php echo $this->url(array('controller'=>'common','action'=>'getaccesscode'));?>";
  var params = 'surveyId='+ <?php echo $this->surveyId ;?>;
  new Ajax.Request(
      url,
      {
      method: 'get',
      parameters: params,
      onSuccess: function(msg) {
          var accessCode = msg.responseText;
          $('id').value = accessCode.substring(1,accessCode.length-1);
          $('submit').disabled='';
          }
      }
  );
</script>
<?php } ?>





