<div class="edit-profile">
	<form name="form"
		action="<?php echo $this->url(array('controller'=>'consumer','action'=>'changepassword'));?>"
		method="post">
		<h1 style="margin-left: 0px;"><?php echo $this->translate('Change_Password');?></h1>
		<dl>
		<fieldset><?php echo $this->form->email;?></fieldset>
		<fieldset><?php echo $this->form->oldpassword;?></fieldset>
		<fieldset><?php echo $this->form->newpassword;?></fieldset>
		<fieldset><?php echo $this->form->repeat;?></fieldset>
		</dl>
		<h1 style="margin-left: 0px;"><?php if($this->showMessage != null) {echo $this->showMessage; }?></h1>
		
		<div style="clear: both; "></div>
		<div class="buttons-bar">
		<?php echo $this->form->submit;?>
		<a class="big-button" href='<?php echo $this->url(array('controller'=>'consumer','action'=>'edit'));?>'><?php echo $this->translate('Back');?></a>
		</div>
	</form>
</div>
