<div class="article-box"><div class="article-box-inner">
	<h1 style="margin-left: 0px;"><?php echo $this->translate("Your_Spark_History")?></h1>
	<p><?php echo $this->translate("Your_Spark_History_Content")?></p>
</div></div>
<div class="article-box" style="background: #fff; padding: 0; margin-bottom: 0;" align="center"><div class="article-box" style="background:#fff;">
	<ul class="tabbed-buttons" >
		<li class="active"><a
			href="<?php echo $this->baseUrl();?>/history/campaigns"><?php echo $this->translate("His_Campaigns")?></a></li>
		<li><a href="<?php echo $this->baseUrl();?>/history/reports"><?php echo $this->translate("His_Reports")?></a></li>
		<li><a href="<?php echo $this->baseUrl();?>/history/referrals"><?php echo $this->translate("His_Referrals")?></a></li>
		<li><a href="<?php echo $this->baseUrl();?>/history/surveys"><?php echo $this->translate("His_Surveys")?></a></li>
		<li><a href="<?php echo $this->baseUrl();?>/history/stuff"><?php echo $this->translate("His_Stuff")?></a></li>
	</ul>
</div></div>
<div style="clear: both;"></div>
<div class="content" style="background: #fff; padding: 0; margin-bottom: 0; margin-top: 10px; padding-left: 25px;">
	<font style="font-size:14px"><?php echo $this->translate("History_Campaigns_Hints")?></font>
</div>
<div style="clear: both;"></div>
<div class="content" style="background: #fff; padding: 0;" align="center">
	<div class="tabbed-content">
	
		<table class="campaigns-history">
			<colgroup>
				
				<col id="name" />
				<col id="accept-date" />
				<col id="expire-date" />
			</colgroup>
			<tr>
				<th><?php echo $this->translate("His_campaign_name")?></th>
				<th><?php echo $this->translate("His_accept_date")?></th>
				<th><?php echo $this->translate("His_expire_date")?></th>
			</tr>
			<?php 
			foreach ($this->paginator as $campaigns):?>
			<tr>
				
				<td><?php echo $campaigns['name']?></td>
				<td><?php echo $campaigns['accept_date']?></td>
				<td><?php echo $campaigns['expire_date']?></td>
			</tr>
			<?php endforeach;?>
		</table>
		<div class="pagebar" ><?= $this->paginationControl($this->paginator, 'Sliding', 'pagination/pagelist.phtml', array("controller" => $this->controller, "action" => $this->action)); ?></div>
	</div>
	<div style="clear: both;"></div>
</div>
