<div align="center">
	<h2>1Welcome to your personalized Spark Account History.</h2>
	<br/>
	<p>
		<a href="<?php echo $this->url(array('controller'=>'history','action'=>'campaigns'));?>"><?php echo $this->translate("History_Campaigns")?></a>
		<a href="<?php echo $this->url(array('controller'=>'history','action'=>'referrals'));?>"><?php echo $this->translate("History_Referrals")?></a>
		<a href="<?php echo $this->url(array('controller'=>'history','action'=>'surveys'));?>"><?php echo $this->translate("History_Surveys")?></a>
		<a href="<?php echo $this->url(array('controller'=>'history','action'=>'stuff'));?>"><?php echo $this->translate("History_Stuff")?></a>
	</p>
</div>