<div class="article-box"><div class="article-box-inner">
	<h1 style="margin-left: 0px;"><?php echo $this->translate("Your_Spark_History")?></h1>
	<p><?php echo $this->translate("Your_Spark_History_Content")?></p>
</div></div>
<div class="content" style="background: #fff; padding: 0; margin-top: 10px;">
	<ul class="tabbed-buttons">
		<li><a href="<?php echo $this->baseUrl();?>/history/campaigns"><?php echo $this->translate("His_Campaigns")?></a></li>
		<li class="active"><a
			href="<?php echo $this->baseUrl();?>/history/reports"><?php echo $this->translate("His_Reports")?></a></li>
		<li><a href="<?php echo $this->baseUrl();?>/history/referrals"><?php echo $this->translate("His_Referrals")?></a></li>
		<li><a href="<?php echo $this->baseUrl();?>/history/surveys"><?php echo $this->translate("His_Surveys")?></a></li>
		<li><a href="<?php echo $this->baseUrl();?>/history/stuff"><?php echo $this->translate("His_Stuff")?></a></li>
	</ul>
</div>
<div style="clear: both;"></div>
<div class="content style="background: #fff; padding: 0; margin-bottom: 0; margin-top: 10px; padding-left: 25px;">
	<p style="font-size:14px"><?php echo $this->translate("History_Reports_Hints")?></p>
</div>
<div style="clear: both;"></div>
<div class="content" style="background: #fff; padding: 0; " align="center">
	<div class="tabbed-content">
		<table class="survey-history">
			<tr>
				<th><?php echo $this->translate("His_Reports_campaign_name")?></th>
				<th><?php echo $this->translate("His_Reports_date")?></th>
				<th><?php echo $this->translate("His_Reports_state")?></th>	
				<th><?php echo $this->translate("His_Surveys_Points_Earned")?></th>
			</tr>
			<?php 
			foreach ($this->paginator as $report):?>
			<tr>
				<td>
				<a	href="<?php echo $this->url(array('controller'=>'history','action'=>'report','id'=>$report['id']));?>"><?php echo $report['name']?></a></td>
				<td><?php echo $report['create_date']?></td>
				<td>
					<?php 
					if($report['state'] == 'UNAPPROVED'){echo $this->translate("His_Reports_VIEWED");}
					if($report['state'] == 'APPROVED'){echo $this->translate("His_Reports_VIEWED");}
					if($report['state'] == 'NEW'){echo $this->translate("His_Reports_NEW");}
					if($report['state'] == 'LOCKED'){echo $this->translate("His_Reports_NEW");}?>
				</td>
				<td>
				<?php $i = $report['id'];
				if($report['reward_point_transaction_record_id'] && $report['point_amount'] != 0){echo $report['point_amount'];?><?php echo $this->translate("History_Points")?>
				<?php }else{echo $this->translate("His_Reports_No_Point");}?>
				</td>
			</tr>
			<?php endforeach;?>
		</table>
		<div class="pagebar" ><?= $this->paginationControl($this->paginator, 'Sliding', 'pagination/pagelist.phtml', array("controller" => $this->controller, "action" => $this->action)); ?></div>
	</div>
	<div style="clear:both"/>
</div>
