<div align="center" >
<fieldset>
<br/>
<h2><?php echo $this->translate('Admin_48Hour_Exchange_Record')?></h2>
<br/>
<table width="900">
	<tr>
	<th width="20">No.</th>
	<th width="100"><?php echo $this->translate('Consumers_Name'); ?></th>
	<th width="100"><?php echo $this->translate('Email'); ?></th>
	<th width="150"><?php echo $this->translate('Admin_Exchange_Date'); ?></th>
	<th width="100"><?php echo $this->translate('Admin_Exchange_Point'); ?></th>
	</tr>
	
	<?php $count = 1; foreach($this->records as $record) : ?>
	
	<tr<?php if ($count%2 == 10){ ?>  style="background-color: #EEF9EB "<?php }?> >
	<td width="20"><?php echo $count++;?></td>
	<td width="100"><?php echo $record['name'];?></td>
	<td width="100"><?php echo $record['email'];?></td>
	<td width="150"><?php echo $record['create_date']?>
	</td>
	<td width="100"><?php echo $record['point_amount']?>
	</td>
	</tr>
	<?php endforeach; ?>
</table>
</fieldset>


<ul>
<li><a href='<?php echo $this->url(array('controller'=>'campaign','action'=>'adminindex'));?>'><?php echo $this->translate('Back'); ?></a></li>
</ul>
</div>

