<div class="article-box" style="background: #fff;">
	<div class="article-box-inner" style="background: #fff;">
		<div class="main-column">
			  <h2><?php echo $this->translate('Exchange_Header');?></h2>
			  <p><?php echo $this->translate('Exchange_Content1');?></p>
			  <ul>
			  <li><?php echo $this->translate('Total_Spark_Points');?>  <?php echo $this->totalPoints?>	</li>
			  <li><?php echo $this->translate('Exchange_Content2');?> <?php echo $this->totalPoints?> </li>
			  <li><?php echo $this->translate('Exchange_Content3');?> <input type="text" size="5"/> </li>
			  </ul>
		</div>
		<div style="clear: both"></div>
		
		<div class="buttons-bar">
		<a class="big-button" href="#"><?php echo $this->translate('Trade_Now');?></a>
		</div>
		<div style="clear:both"></div>
	</div>
 </div>


