
	<div class="article-box" style="height:90px;">
		<div class="article-box-inner" style="padding-top: 10px;">
			<p><?php echo $this->translate('Thanks_For_Poll_Content1')?> <?php echo $this->point?> <?php echo $this->translate('Thanks_For_Poll_Content2')?></p>
			<div class="buttons-bar" style="padding-top: 10px;">
				<a class="big-button-blue" target="_parent"  href="<?php echo $this->url(array('controller'=>'home','action'=>'index'));?>"><?php echo $this->translate('Take_Me_Home')?></a>
				<a class="big-button-blue" target="_parent"  href="<?php echo $this->url(array('controller'=>'profilesurvey','action'=>'index'));?>"><?php echo $this->translate('More_Polls')?></a>
			</div>
		</div>
	</div>
