<?php 
	$topic = $this->topic;
	if(isset($topic['title'])){
		$title = $topic['title'];
	}else{
		$title = "-";
	}
	if(isset($topic['date_posted'])){
		list($year,$month,$day,$hour,$minute,$second) = $topic['date_posted'];
		$date = date("Y-m-d g:i:s a",mktime($hour,$minute,$second,$month,$day,$year));
	}else{
		$date = "-";
	}
	if(isset($topic['body'])){
		$body = $topic['body'];
	}else{
		$body = "-";
	}
	if(isset($topic['tracker'])){
		$lastestKey = false;
		foreach($topic['tracker'] as $k => $v):
			if(!$lastestKey){
				$lastestKey = $k;
			}else if($lasteKey < $k){
				$lastestKey = $k;
			}
		endforeach;
		$tracker = $topic['tracker'][$lastestKey];
		if(isset($tracker['views'])){
			$views = $tracker['views'];
		}else{
			$views = "-";
		}
		if(isset($tracker['comments'])){
			$comments = $tracker['comments'];
		}else{
			$comments = "-";
		}
	}else{
		$comments = "-";
		$views = "-";
	}
	
?>
<div style="width:100%;" class="topic_head">
	<div style="" class="title_td">
		<div class="row-fluid">
			<div class="span11">
				<i class="babytree" style=""></i>
				<span onclick="toggleDiv(this,'<?php echo urlencode($topic['_id'])?>');" class="title"><a href="javascript:void(0)"><?php echo $title ?></a></span>
			</div>
	        <div span="span2">
	        	<i class="icon-zh-CN" style="float:right"></i>
	        </div>
		</div>
		<div style="display: none;" class="topicPRR">
	    	<div class="posts"><div>Loading...</div></div>
	        <div class="responses">
	        </div>
	        <div class="reply" id="reply_box_1">
				<form action="">
				    <textarea placeholder="在这里填写您想回复的话" style="width:100%" rows="4" class="reply-content"></textarea>
				    <button onclick="addSourceUrl('<?php echo $topic['_id']?>',this);return false;" id="" class="btn btn-primary">添加原帖链接</button>
					<button onclick="saveReply('<?php echo urlencode($topic['_id'])?>',this);return false;" id="submit_button_1" class="btn btn-primary">回复</button>
				</form>
			</div>
		</div>
	</div>
