<?php foreach($this->topics as $topic):?>
	<div class="topic" data="<?php echo urlencode($topic['id'])?>">
		<div style="width:100%;" class="topic_head">
			<div style="" class="title_td">
				<div class="row-fluid">
					<div class="span11">
						<i class="babytree" style=""></i>
						<span onclick="toggleDiv(this,'<?php echo urlencode($topic['id'])?>');" class="title"><a href="javascript:void(0)"><?php echo $topic['value']['title'] ?></a></span>
					</div>
			        <div span="span2">
			        	<i class="icon-zh-CN" style="float:right"></i>
			        </div>
				</div>
				<div style="display: none;" class="topicPRR">
			    	<div class="posts"><div>Loading...</div></div>
			        <div class="responses">
			        </div>
			        <div class="reply" id="reply_box_1">
						<form action="">
						    <textarea placeholder="在这里填写您想回复的话" style="width:100%" rows="4" class="reply-content"></textarea>
						    <button onclick="addSourceUrl('<?php echo $topic['id']?>',this);return false;" id="" class="btn btn-primary add-url">添加原帖链接</button>
						<img onclick="saveReply('<?php echo urlencode($topic['id'])?>',this);return false;" id="submit_button_1" class="weibo-reply-img" style="cursor:pointer;" src="<?php echo $this->baseUrl();?>/images/weiboreply.gif"></img>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
<?php endforeach;?>
<!-- div class="pageInfo">
<?php 
	if($this->page>0){
?>
<span><a onclick="openDetail('<?php echo $this->key?>','<?php echo $this->totalCount?>',<?php echo $this->page-1?>)" href="javascript:void(0);">上一页</a></span>
<?php 
	}
?>
<span><?php echo $this->page."/".$this->totalPage?></span>
<?php 
	if($this->page < $this->totalPage-1){
?>
<span><a onclick="openDetail('<?php echo $this->key?>','<?php echo $this->totalCount?>',<?php echo $this->page+1?>)" href="javascript:void(0);">下一页</a></span>
<?php 
	}
?>
</div-->
