<table>
<thead>
<th>原帖地址</th>
<th>回复内容</th>
<th>时间</th>
</thead>
<tbody>
<?php foreach($this->irrs as $irr):
?>
<tr>
	<td><a href="<?php echo "http://".$irr['topic']?>" target="_blank"><?php echo "http://".$irr['topic']?></a></td>
	<td><?php echo $irr['content']?></td>
	<td><?php echo date($irr['timestamp'])?></td>
</tr>
<?php 
endforeach;?>
</tbody>
</table>
<style type="text/css">
	td,th{
		padding-left:10px;
	}
</style>