  <script type="text/javascript" media="screen"  src="<?php echo $this->baseUrl();?>/js/jquery-1.7.1.min.js" ></script>

<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/qunit.css" type="text/css" media="screen">  
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/qunit.js"></script>


<h1 id="qunit-header">QUnit example</h1>
 <h2 id="qunit-banner"></h2>
 <div id="qunit-testrunner-toolbar"></div>
 <h2 id="qunit-userAgent"></h2>
 <ol id="qunit-tests"></ol>
 <div id="qunit-fixture">test markup, will be hidden</div>
 
 <script type="text/javascript" charset="utf-8">  

 
   $q = jQuery.noConflict(true);
   $ = null;
   jQuery = null;   
</script>  

<div id="qunit-fixture">test markup</div>  
   <iframe style="width:100%;height:600px;" id="testframe" src="/wildfire_php/public/tag"></iframe> 

<script>

   $q(function() {  
	   
   // fire event when iframe is ready  
   $q('#testframe').load(function() {  
      // Get the jQuery Object from the original code
      $ = window.frames[0].jQuery;  
      test('my test', 1, function() {  
         // On start this is visible  
         ok($('#folders').is(':visible')); 
         $('#folders li a').first().click();
      });  
   });  
});
   </script>
   