<div style="padding-bottom:40px;"></div>
<div align="left" style='padding-left:50px;'>
	<div id="maincolumn">
        <div class="path"><span class="breadcrumbs pathway"></div>
		<fieldset class="select-user">
			<br>
			<h2><?php echo $this->translate('Select_User')?></h2>
			<?php echo $this->cpForm; ?>
		</fieldset>
		
		<ul>
			<li><a href='<?php echo $this->url(array('controller'=>'campaign','action'=>'adminindex'));?>'><?php echo $this->translate('Back')?></a></li>
		</ul>
		<span class="article_separator">&nbsp;</span>
	</div>
</div>

