<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('#fillout-dialog').dialog({dialogClass: 'ui-fillout-dialog', bgiframe: true, autoOpen: false, resizable: false, modal: true, width: 680, height: 600, title: '<?php echo $this->translate("Submit_WOM_Report")?>' });
	jQuery('#submit-url').dialog({bgiframe: true, autoOpen: false, resizable: false, modal: true, width: 400, height: 160, title: '<?php echo $this->translate("Submit_WOM_Report")?>' });
	jQuery('#check-alert-dialog').dialog({title:'<?php echo $this->translate("Submit_you_report_error")?>', bgiframe: true, autoOpen: false, resizable: false, modal: true, buttons: {
			'<?php echo $this->translate("Submit_you_report_confirm")?>': function() {
				jQuery(this).dialog('close');
			}
		}
	});
  });

var filloutDialogOpen = function(url) {
    jQuery("#fillout-dialog .content").load(url,function(){
    });
    jQuery("#fillout-dialog").dialog('open');
}
var submitUrlDialogOpen = function() {
    jQuery("#submit-url").dialog('open');
}
</script>
<script type="text/javascript">
<!--
var openSubMenu = function() {
	jQuery('.submit-menu').show();
}
var closeSubMenu = function() {
	jQuery('.submit-menu').hide();
}
//-->
</script>
<?php if ($this->lang=='en'):?>
	<?php include("./description/campaign_".$this->id."_en.html"); ?>
<?php else:?>
	<?php include("./description/campaign_".$this->id.".html"); ?>
<?php endif?>
<div id="fillout-dialog">
<div class="content"></div>
</div>
<div id="check-alert-dialog"><p class="content"></p></div>
<div id="submit-url" class="submit-url submit-url-done">
	<div class="status"><?php echo $this->translate("Home_Submit_URL_Report")?></div>
	<div class="input-url">
		<input id="url_<?php echo $this->id;?>" type="text" name="url" class="text-box" value="<?php if(isset($this->urlReport)){ echo $this->urlReport->url;}?>"/>
		<?php if($this->urlReport == null || $this->urlReport->url == null || $this->urlReport->url == ''){?>
		<input id = "url_report_submit_<?php echo $this->id;?>" type="button" value="<?php echo $this->translate("Home_URL_Report_Submit")?>" class="button" onclick="submitURL(<?php echo $this->id;?>);"/>
		<?php }?>
	</div>
	<div class="intro-text">
		<ul>
		<?php if(isset($this->urlReport) && $this->urlReport->state != null && $this->urlReport->state == 'APPROVED'){?>
			<img src="<?php echo $this->baseUrl();?>/images/action_check.gif" align="absmiddle"/>&nbsp;<?php echo $this->translate("Home_URL_Report_Approved")?>
		<?php }else{?>
			<?php if(isset($this->urlReport) && $this->urlReport->state != null && $this->urlReport->state == 'NEW'){?>
				<li><?php echo $this->translate("Home_URL_Report_Wait_For")?></li>
			<?php }else{?>
				<li id='url_report_notice_<?php echo $this->id;?>'><?php echo $this->translate("Home_URL_Report_Introduction")?></li>
			<?php }?>
			<li><?php echo $this->translate("Home_URL_Report_Introduction2")?></li>
		<?php }?>
		</ul>
	</div>
</div>
<script language="javascript">
var base64EncodeChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
var base64DecodeChars = new Array(
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 62, -1, -1, -1, 63,
    52, 53, 54, 55, 56, 57, 58, 59, 60, 61, -1, -1, -1, -1, -1, -1,
    -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
    15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, -1, -1, -1, -1, -1,
    -1, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
    41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, -1, -1, -1, -1, -1);
function base64encode(str) {
    var out, i, len;
    var c1, c2, c3;

    len = str.length;
    i = 0;
    out = "";
    while(i < len) {
    c1 = str.charCodeAt(i++) & 0xff;
    if(i == len)
    {
        out += base64EncodeChars.charAt(c1 >> 2);
        out += base64EncodeChars.charAt((c1 & 0x3) << 4);
        out += "==";
        break;
    }
    c2 = str.charCodeAt(i++);
    if(i == len)
    {
        out += base64EncodeChars.charAt(c1 >> 2);
        out += base64EncodeChars.charAt(((c1 & 0x3)<< 4) | ((c2 & 0xF0) >> 4));
        out += base64EncodeChars.charAt((c2 & 0xF) << 2);
        out += "=";
        break;
    }
    c3 = str.charCodeAt(i++);
    out += base64EncodeChars.charAt(c1 >> 2);
    out += base64EncodeChars.charAt(((c1 & 0x3)<< 4) | ((c2 & 0xF0) >> 4));
    out += base64EncodeChars.charAt(((c2 & 0xF) << 2) | ((c3 & 0xC0) >>6));
    out += base64EncodeChars.charAt(c3 & 0x3F);
    }
    return out;
}
function submitURL(campaignId){
	campaign_id = campaignId;
	var url = '<?php echo $this->url(array('controller'=>'report','action'=>'ajaxstoreurl'));?>';
	var pars = 'campaignId='+campaignId+'&url='+base64encode($('url_'+campaignId).value);
	new Ajax.Request(    
		url,
		{
		method: 'get',      
		parameters: pars,    
		onSuccess: updateURL    
		}
	);
}
function updateURL(originalRequest){
	if(originalRequest.responseText){
		$('url_report_notice_'+campaign_id).innerHTML = '<?php echo $this->translate("Home_URL_Report_Wait_For")?>';
		$('url_report_submit_'+campaign_id).style.display = "none";
	}
}
</script>