<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>    <?php  if( isset($this->message)  ) { ?>
      <?php echo $this->message; ?>
    <?php } else {?>
      非常感谢您的耐心填写！
   <?php } ?></title>
<style type="text/css">
<!--
.container {
  width:960px;
  height: 750px;
  margin-left:auto;
  margin-right:auto;
  background: url("<?php echo $this->baseUrl();?>/images/kraft/thankyou.jpg");
}

#content {
  text-align:center;
  padding: 0 60px;
  padding-top: 290px;
  font-size: 50px;
  color: #FF0016;
}

-->
</style>
</head>
<body>
<div class="container">
  <div id="content">
    <?php  if( isset($this->message)  ) { ?>
      <?php echo $this->message; ?>
    <?php } else {?>
      非常感谢您的耐心填写！
   <?php } ?>
  </div>
</div> 
</body>
</html>
