<div class="article-box">
<div class="article-box-inner">
<h2><?php echo $this->translate('Spark_Training');?></h2>
<p><?php echo $this->translate('Depending_On_Your_Level_Of_Experience');?></p>
</div>
</div>

<div class="article-box" style="background: #fff;">
<div class="article-box-inner" style="background: #fff;">
<h2><?php echo $this->translate('Intro_To_Wildfire');?></h2>
<p><?php echo $this->translate('This_Short_Slideshow_Covers');?></p>
<div class="buttons-bar"><a class="big-button"
	href="<?php echo $this->url(array('controller'=>'training',	'action'=>'introtowildfire','id'=>'0'));?>"><?php echo $this->translate('Intro_To_Wildfire');?>
</a>
<div style="clear: both;"></div>
</div>
</div>
</div>

<div class="article-box">
<div class="article-box-inner">
<h2><?php echo $this->translate('How_A_Spark_Campaign_Works');?></h2>
<p><?php echo $this->translate('Campaigns_Are_How_Sparks_Learn_About');?></p>
<div style="clear: both;"></div>
<div class="buttons-bar"><a class="big-button-blue"
	href="<?php echo $this->url(array('controller'=>'training',	'action'=>'howitworks','id'=>'0'));?>"><?php echo $this->translate('How_It_Works');?>
</a>
<div style="clear: both;"></div>
</div>
</div>
</div>
