<div class="content">
<h1 style="margin-left:0"><?php echo $this->translate('Spark_Training_Intro_To_Wildfire')?></h1>
<p><?php echo $this->translate('This_Introductory_WOM_Will_Give_You')?></p>
</div>
<div class="content" style="background: #fff">
<div class="guide-box"><?php if ($this->id==0):?>
<div class="guide-content">
<h3><?php echo $this->translate('What_Is_The_Wildfire')?></h3>
<h4><?php echo $this->translate('Welcome_to_wildfire')?></h4>
<p><?php echo $this->translate('Welcome_to_wildfire_conten_1')?></p>
<p><?php echo $this->translate('Welcome_to_wildfire_conten_2')?></p>
<p><?php echo $this->translate('Welcome_to_wildfire_conten_3')?></p>
</div>
<div class="guide-button"><span><?php echo $this->translate('One')?></span> <a
	href="<?php echo $this->baseUrl();?>/training/introtowildfire/id/1">&gt;&gt;</a></div>
<?php endif?> <?php if ($this->id==1):?>
<div class="guide-content">
<h3><?php echo $this->translate('Why_is_it_so_important_to_be_honest')?></h3>
<h4><?php echo $this->translate('Why_is_it_so_important_to_be_honest_content')?></h4>
<ul>
	<li><?php echo $this->translate('Why_is_it_so_important_to_be_honest_content_1')?></li>
	<li><?php echo $this->translate('Why_is_it_so_important_to_be_honest_content_2')?></li>
	<li><?php echo $this->translate('Why_is_it_so_important_to_be_honest_content_3')?></li>
</ul>
</div>
<div class="guide-button"><a
	href="<?php echo $this->baseUrl();?>/training/introtowildfire/id/0">&lt;&lt;</a>
<span><?php echo $this->translate('Two')?></span> <a
	href="<?php echo $this->baseUrl();?>/training/introtowildfire/id/2">&gt;&gt;</a></div>
<?php endif?> <?php if ($this->id==2):?>
<div class="guide-content">
<h3><?php echo $this->translate('You_are_not_saler')?></h3>
<br>
<ul>
	<li><?php echo $this->translate('You_are_not_saler_content_1')?></li>
	<li><?php echo $this->translate('You_are_not_saler_content_2')?></li>
	<li><?php echo $this->translate('You_are_not_saler_content_3')?></li>
	<li><?php echo $this->translate('You_are_not_saler_content_4')?></li>
</ul>
</div>
<div class="guide-button"><a
	href="<?php echo $this->baseUrl();?>/training/introtowildfire/id/1">&lt;&lt;</a>
<span><?php echo $this->translate('Three')?></span> <a
	href="<?php echo $this->baseUrl();?>/training/introtowildfire/id/3">&gt;&gt;</a>
</div>
<?php endif?> <?php if ($this->id==3):?>
<div class="guide-content">
<h3><?php echo $this->translate('You_have_influence')?></h3>
<h4><?php echo $this->translate('You_have_influence_content')?></h4>
<ul>
	<li><?php echo $this->translate('You_have_influence_content_1')?></li>
	<li><?php echo $this->translate('You_have_influence_content_2')?></li>
	<li><?php echo $this->translate('You_have_influence_content_3')?></li>
</ul>
</div>
<div class="guide-button"><a
	href="<?php echo $this->baseUrl();?>/training/introtowildfire/id/2">&lt;&lt;</a>
<span><?php echo $this->translate('Four')?></span> <a
	href="<?php echo $this->baseUrl();?>/training/introtowildfire/id/4">&gt;&gt;</a>
</div>
<?php endif?> <?php if ($this->id==4):?>
<div class="guide-content">
<h3><?php echo $this->translate('What_is_sparks_report')?></h3>
<h4><?php echo $this->translate('What_is_sparks_report_content_1')?></h4>
<ul>
	<li><?php echo $this->translate('What_is_sparks_report_content_2')?></li>
	<li><?php echo $this->translate('What_is_sparks_report_content_3')?></li>
	<li><?php echo $this->translate('What_is_sparks_report_content_4')?></li>
</ul>
</div>
<div class="guide-button">
<p><a
	href="<?php echo $this->baseUrl();?>/training/introtowildfire/id/3">&lt;&lt;</a>
<span><?php echo $this->translate('Five')?></span> <a
	href="<?php echo $this->baseUrl();?>/training/introtowildfire/id/5">&gt;&gt;</a>
</p>
</div>
<?php endif?> <?php if ($this->id==5):?>
<div class="guide-content">
<h3><?php echo $this->translate('Thats_It')?></h3>
<p>&nbsp;</p>
<p><?php echo $this->translate('We_hope_it_is_useful_for_you')?><?php echo $this->translate('Frequently_Asked_Questions')?></p>
<p>&nbsp;</p>
<p style="float: left; padding-left: 70px" class="buttons-bar"><a
	href="<?php echo $this->baseUrl();?>/training/index"><?php echo $this->translate('Training')?></a><a
	href="<?php echo $this->baseUrl();?>/campaigninvitation"><?php echo $this->translate('Campaigns')?></a></p>
</div>
<div class="guide-button"><a
	href="<?php echo $this->baseUrl();?>/training/introtowildfire/id/4">&lt;&lt;</a>
<span><?php echo $this->translate('End')?></span></div>
<?php endif?></div>

</div>
