<div class="article-box"><div class="article-box-inner">
<h1 style="margin-left:0"><?php echo $this->translate('Spark_Training_Sample_Report')?></h1>
<p><?php echo $this->translate('This_Introductory_Training_Will_Give_You')?></p>
</div></div>

<br/>
<?php if ($this->lang=='en'):?>
<!-- <img src="<?php echo $this->baseUrl();?>/images/sample_report_en.png" /> -->
english words
<?php else: ?>
<!-- <img src="<?php echo $this->baseUrl();?>/images/sample_report_zh.png" /> -->
汉语文字
<?php endif;?>
