<script>
	jQuery(function() {
      jQuery( "#tabs" ).tabs();
  });
</script>
<script src="//connect.facebook.net/en_US/all.js"></script>
<div id="fillout-dialog">
    <div class="content"></div>
</div>
<div id="check-alert-dialog">
    <p class="content"></p>
</div>
<?php if (isset($this->recentInvitation)&&$this->recentInvitation):?>
<?php if($this->recentInvitation['type'] == 'mission'){?>
<div id="web-dialog" class="web-dialog" style="display:none;">
    <div class="content-2column">
	<div class="images-column">
            <img style="max-width:80px;" src="<?php echo $this->baseUrl();?>/images/campaign/campaign_<?php echo $this->escape($this->recentInvitation['campaign_id']);?>_01.jpg" />
            <img style="max-width:80px;" src="<?php echo $this->baseUrl();?>/images/campaign/campaign_<?php echo $this->escape($this->recentInvitation['campaign_id']);?>_02.jpg" />
        </div>
        <div class="main-column">
            <h2><?php echo $this->translate('You_Are_Invited_1')?><?php echo $this->recentInvitation['name'];?><?php if($this->recentInvitation['name']=="campaign"){ echo $this->translate('You_Are_Invited_2');} else {echo $this->translate('You_Are_Invited_3');}?></h2>
            <a href="#" class="close-button" onclick="WebDialog.close();return false;"><img src="<?php echo $this->baseUrl();?>/images/web-dialog-close.gif"/></a>
            <p><?php echo $this->recentInvitation['invitation_description']?></p>
            <p><?php echo $this->recentInvitation['invitation_description2']?></p>
        </div>
        <div class="buttons-bar">
        <?php if ($this->recentInvitation["name"]=="内测-美妆达人"){?>
        	<a href="<?php echo $this->url(array('controller'=>'tag','action'=>'index'));?>" class="button"><?php echo $this->translate('Accept');?></a>
        <?php }else {?>
            <a href="<?php echo $this->url(array('controller'=>'mission','action'=>'description', 'id'=>$this->recentInvitation['campaign_id']));?>" class="button"><?php echo $this->translate('Accept');?></a>
        <?php }?>
        </div>
    </div>
</div>

<?php }else{?>
<div id="web-dialog" class="web-dialog" style="display:none;">
    <div class="content-2column">
	<div class="images-column">
            <img  style="max-width:80px;"   src="<?php echo $this->baseUrl();?>/images/campaign/campaign_<?php echo $this->escape($this->recentInvitation['campaign_id']);?>_01.jpg" />
            <img  style="max-width:80px;"   src="<?php echo $this->baseUrl();?>/images/campaign/campaign_<?php echo $this->escape($this->recentInvitation['campaign_id']);?>_02.jpg" />
	</div>
        <div class="main-column">
            <h2>
                <?php echo $this->translate('You_Are_Invited_1')?><?php echo $this->translate('Campaign_name_'.$this->recentInvitation['campaign_id']);?><?php echo $this->translate('You_Are_Invited_2')?>
            </h2>
            <a href="#" class="close-button" onclick="WebDialog.close();return false;"><img src="<?php echo $this->baseUrl();?>/images/web-dialog-close.gif"/></a>
            <p><?php echo $this->translate("Campaign_invitation_description_".$this->recentInvitation['campaign_id'])?></p>
            <?php echo $this->translate("Campaign_invitation_description2_".$this->recentInvitation['campaign_id'])?>
	</div>
	<div class="buttons-bar">
            <a href="<?php echo $this->url(array('controller'=>'campaign','action'=>'precampaign', 'id'=>$this->recentInvitation['campaign_id']));?>" class="button"><?php echo $this->translate('Accept');?></a>
            <a href="<?php echo $this->url(array('controller'=>'campaigninvitation','action'=>'prereject', 'id'=>$this->recentInvitation['campaign_id']));?>" class="button"><?php echo $this->translate('Reject');?></a>
	</div>
    </div>
</div>

<?php }?>
<?php endif?>

<?php if(isset($this->postCampaignNotification)&&$this->postCampaignNotification):?>
<div id="web-dialog2" class="post-campaign-dialog" style="display: none;">
    <div class="content-2column">
	<div class="images-column">
            <img src="<?php echo $this->baseUrl();?>/images/campaign/campaign_<?php echo $this->escape($this->postCampaignNotification['campaign_id']);?>_01.jpg" />
	</div>
	<div class="main-column">
            <h2><?php echo $this->postCampaignNotification['name']?> <?php echo $this->translate('Home_Post_Campaign_Survey_end')?></h2>
            <a href="#" class="close-button" onclick="WebDialog.close();return false;"><img src="<?php echo $this->baseUrl();?>/images/web-dialog-close.gif"/></a>
            <!--<?php echo $this->translate('Campaign_post_survey_notice_'.$this->postCampaignNotification['campaign_id'])?>-->
            <br />
            <?php echo$this->postCampaignNotification['post_survey_notice']?>
	</div>
	<div class="buttons-bar">
            <a href="<?php echo $this->url(array('controller'=>'campaign','action'=>'postcampaign', 'id'=>$this->postCampaignNotification['campaign_id']));?>" class="button"><?php echo $this->translate('Home_Finish_Survey')?></a>
	</div>
    </div>
</div>
<?php endif?>

<?php if (count($this->allInvitations)+count($this->activeCampaigns)==0):?>
<div id="no-campaign" class="post-campaign-dialog" style="display:none;">
	<div class="content-2column">
		<div class="images-column">
		<img src="<?php echo $this->baseUrl();?>/images/no-campaign.png" /> 
		</div>
		<div class="main-column">
			<h2><?php echo $this->translate('This_Spark_Campaign_is_Full')?></h2>
			<a href="#" class="close-button" onclick="WebDialog.close();return false;"><img src="<?php echo $this->baseUrl();?>/images/web-dialog-close.gif"/></a>
			<p style="margin-top:-2px;"><?php echo $this->translate('This_Spark_Campaign_is_Full_Content')?></p>
		</div>

	</div>
</div>
<?php endif?>

<div class="mask" id="mask" style="display:none;"></div>

<!-- notification box  -->
<div class="article-box" style="margin-bottom:15px;display:none;" id="notification-box">

</div>

<div class="article-box" style="margin-bottom: 15px;" >
	<div class="article-box-title">&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-style:blod;">WELCOME TO WILDFIRE!</span></div>
    <div class="article-box-inner" >
		<?php if ($this->consumer!=null){ ?>
			<p style="margin: 10px 0 5px 0;"><?php echo $this->translate("Home_head_content_1")?></p>
			<!--<p style="margin: 0 0 5px 0;font-size:120%;"><?php echo $this->translate("Home_head_content_2_1")?>
			 <a href="<?php echo $this->url(array('controller'=>'training',	'action'=>'howitworks','id'=>'0'));?>"><?php echo $this->translate("Home_head_content_2_2")?></a> 
			</p>-->
			<div class="clear"></div>
		<?php }?>
	</div>
</div>


<div class="article-box-title">&nbsp;&nbsp;&nbsp;&nbsp;MY ACTIVITIES</div>

<div class="spark-report">

<?php $j = 0;foreach ($this->activeCampaigns as $activeCampaign):?>		

	<script>
	jQuery(function() {
      jQuery( "#tabs<?php echo $j?>").tabs();
  });
</script>
	<div class="spark-report-box">

		<div class="spark-report-box-inner">
			<div class="ul-wrapper" id="ul_tab_<?php echo $j?>"<?php if ($j>1):?> style="display:true;"<?php endif;?>>
			<?php if($activeCampaign['type'] == 'campaign'){?>
			<!-- <div class="report-area"> -->
				<div id="tip-div">
					<img onmouseover="showtip(<?php echo $j?>);" onmouseout="hidetip(<?php echo $j?>);" class="help-button" src="<?php echo $this->baseUrl();?>/images/help-button.gif"/>
				</div>
				<div class="tip-wrapper">
					<div id="tip<?php echo $j?>" class="tip-box tip1" style="display:none;">
							<h2 class="tip-box-title" style="font-size:11px;margin-left:38px;"><?php echo $this->translate("What’s_a_Spark_Report?")?></h2>
							<p><?php echo  $this->translate("What’s_a_Spark_Report?_Content_1")?></p>
							<p><?php echo  $this->translate("What’s_a_Spark_Report?_Content_2")?></p>
							<p><?php echo  $this->translate("What’s_a_Spark_Report?_Content_3")?></p>
							<p><?php echo  $this->translate("What’s_a_Spark_Report?_Content_4")?></p>
					</div>
				</div>
				<div id="tabs<?php echo $j?>" class="tabs">
					<ul>
						<li style="width:120px;"><a href="#tabs-contact<?php echo $j?>"><?php echo $this->translate('Tabs_brandinfo')?></a></li>
			      <li style="width:200px;"><a href="#tabs-report<?php echo $j?>"><?php echo $this->translate('Tabs_Report')?></a></li>
			      <li style="width:180px;"><a href="#tabs-url<?php echo $j?>"><?php echo $this->translate('Tabs_Url')?></a></li>
			      <li style="width:120px;"><a href="#tabs-photo<?php echo $j?>"><?php echo $this->translate('Tabs_Photo')?></a></li>
			    </ul>

					 <div id="tabs-contact<?php echo $j?>" class="report-panel">
						<!-- 
						<div class='report-panel-header'>
							<span class="campaign-name"><?php echo $activeCampaign["name"]?></span>
							<span class="tab-description"> <?php echo $this->translate('Report_Contact_Description')?><span>
						</div>
						<div class="contact-text">
							<p><?php echo $this->translate('Contact_Text_Title')?><p> 
					    <p><img src='image/yahoo_message.png'/><?php echo $this->translate('Contact_Text_Yahoo')?></p>
					    <p><img src='image/facebook_icon.png'/><?php echo $this->translate('Contact_Text_Facebook')?></p>
					    <p><img src='image/mobile_icon.png'/><?php echo $this->translate('Contact_Text_Mobile')?></p>
					  </div> 
						-->

						<div class="images-column" style="float:left;margin-top:15px;"><img
							src="<?php echo $this->baseUrl();?>/images/campaign/campaign_105_03.jpg"
							style="padding: 0; border: 0; margin-right: 10px;background:none;" />
						</div>
						<div class="main-column" style="width:450px;float:left;margin-top:-4px;">
							<a href="<?php echo $this->url(array('controller'=>'campaign','action'=>'description','id'=>$activeCampaign['campaign_id'])); ?>"><h2 style="color:#000000" id="campaign_name_<?php echo $activeCampaign['campaign_id'] ?>">Quality for Life™ Philippines Campaign</h2></a>

							<span id="campaign_description_<?php echo $activeCampaign['campaign_id'] ?>">
								A globally recognized brand that supplies high-quality vitamins ingredients to companies worldwide. It aims at improving your education about vitamins to give you peace of mind when you choose food and beverage products.
							</span>

							<!-- </ul> -->
						</div>
						<div style="clear: both;"></div>

					</div>

			    <div id="tabs-report<?php echo $j?>" class="report-panel">
			    	<div class="images-column" style="float:left;margin-top:15px;"><img
							src="<?php echo $this->baseUrl();?>/images/campaign/campaign_105_03.jpg"
							style="padding: 0; border: 0; margin-right: 10px;background:none;" />
						</div>
						<div class="main-column" style="width:450px;float:left;margin-top:11px;">
							<div class='report-panel-header'>
								<!-- <span class="campaign-name"><?php echo $activeCampaign["name"]?></span> -->
								<span class="tab-description"><?php echo $this->translate('Report_Submit_Description');?><span>
							</div>
							<ul class="submit-report">
								<?php $reportCount=1?>
								<?php foreach ($this->allCampaignReports as $report):?>
									<?php if ($report['campaign_id']==$activeCampaign['campaign_id'] && $reportCount<=3):?>
										<div class="li-wrapper">
										<li><?php echo $this->translate("Spark_Report")?>#<?php echo $reportCount?> (0-500 <?php echo $this->translate("points")?>)
											<?php if(array_key_exists($report['id'], $this->approvedCampaignReportPoint)) {?>
											<img src="<?php echo $this->baseUrl();?>/images/action_check.gif" align="absmiddle"/>
											<?php echo $this->translate('earned');?> <?php echo $this->approvedCampaignReportPoint[$report['id']]?> <?php echo $this->translate("points")?>
											<?php } else{?>
											<?php echo $this->translate("Submit_successfully_and_pedding")?>
											<?php }?>
										</li>
										</div>
										<?php $reportCount++?>
									<?php endif;?>
								<?php endforeach;?>
								<?php if ($reportCount == 1):?>
									<div class="li-wrapper">
										<li>
											<a href="<?php echo $this->url(array('controller'=>'report','action'=>'create', 'id'=>$activeCampaign['campaign_id']));?>" onclick="filloutDialogOpen('<?php echo $this->url(array('controller'=>'report','action'=>'create', 'id'=>$activeCampaign['campaign_id']));?>');return false;"><?php echo $this->translate('Click_here_and_submit'); ?><?php echo $this->translate("Spark_Report")?>#1</a> (0-500 <?php echo $this->translate("points")?>)
											
										</li>
									</div>
									<div class="li-wrapper">
										<li>
											<?php echo $this->translate("Spark_Report")?>#2 (0-500 <?php echo $this->translate("points")?>)
											
										</li>
									</div>
									<div class="li-wrapper">
										<li>
											<?php echo $this->translate("Spark_Report")?>#3 (0-500 <?php echo $this->translate("points")?>)

										</li>
									</div>
								<?php endif;?>
							
								<?php if ($reportCount ==2):?>
									<div class="li-wrapper">
										<li>
											<a href="<?php echo $this->url(array('controller'=>'report','action'=>'create', 'id'=>$activeCampaign['campaign_id']));?>" onclick="filloutDialogOpen('<?php echo $this->url(array('controller'=>'report','action'=>'create', 'id'=>$activeCampaign['campaign_id']));?>');return false;"><? echo $this->translate('Click_here_and_submit'); ?><?php echo $this->translate("Spark_Report")?>#2 (0-500 <?php echo $this->translate("points")?>)</a>
										</li>
									</div>
									<div class="li-wrapper">
										<li>
											<?php echo $this->translate("Spark_Report")?>#3 (0-500 <?php echo $this->translate("points")?>)

										</li>
									</div>
								<?php endif;?>
							
								<?php if ($reportCount ==3):?>
									<div class="li-wrapper">
										<li>
											<a href="<?php echo $this->url(array('controller'=>'report','action'=>'create', 'id'=>$activeCampaign['campaign_id']));?>" onclick="filloutDialogOpen('<?php echo $this->url(array('controller'=>'report','action'=>'create', 'id'=>$activeCampaign['campaign_id']));?>');return false;"><? echo $this->translate('Click_here_and_submit'); ?><?php echo $this->translate("Spark_Report")?>#3 (0-500 <?php echo $this->translate("points")?>)</a>
										</li>
									</div>
								<?php endif;?>
								
								<?php if ($reportCount <=3){?>
									<div class="li-wrapper">
										<li>								
											<?php echo $this->translate("Bonus_Report")?> (0-500 <?php echo $this->translate("points")?>)
										</li>
									</div>
								<?php }else{?>
									<div class="li-wrapper">
										<li>						
											<a href="<?php echo $this->url(array('controller'=>'report','action'=>'create', 'id'=>$activeCampaign['campaign_id']));?>" onclick="filloutDialogOpen('<?php echo $this->url(array('controller'=>'report','action'=>'create', 'id'=>$activeCampaign['campaign_id']));?>');return false;">
											<? echo $this->translate('Click_here_and_submit_more'); ?> (0-500 <?php echo $this->translate("points")?>)
											</a>
										</li>
									</div>
								<?php }?>
							</ul>
						</div>
					</div>
					<div id="tabs-photo<?php echo $j?>" class="report-panel">
						<div class="images-column" style="float:left;margin-top:15px;"><img
							src="<?php echo $this->baseUrl();?>/images/campaign/campaign_105_03.jpg"
							style="padding: 0; border: 0; margin-right: 10px;background:none;" />
						</div>
						<div class="main-column" style="width:450px;float:left;margin-top:11px;">					
							<div class='report-panel-header'>
								<!-- <span class="campaign-name"><?php echo $activeCampaign["name"]?></span> -->
								<span class="tab-description"> <?php echo $this->translate('Upload_Photo_Text')?><span>
							</div>
							<div class="uploading-image">
									<?php if(isset($this->activeImageReportsForCampaign[$activeCampaign['campaign_id']])) {?>			
								     <?php foreach($this->activeImageReportsForCampaign[$activeCampaign['campaign_id']] as $imageReport) { ?>
								      <?php $is_first = ($this->activeImageReportsForCampaign[$activeCampaign['campaign_id']][0]['id'] == $imageReport['id'])?>
			                          <div style="text-align:center;<?php if(!$is_first) {echo 'display:none;';}?>" class="image" >
			                            <a onclick="move_up(this);"><img src="<?php echo $this->baseUrl();?>/images/arrow_blue_up.png" /></a>
			                            <a href="<?php echo $this->url(array('controller'=>'image','action'=>'getimage', 'id'=>$imageReport['id']));?>" title="<?php echo $this->translate('Uplaod_Photo_Url_Title')?>" class="thickbox"> 
			                             <img id="image_thumb_<?php echo $imageReport['id'];?>" width='<?php if (isset($imageReport['thumb_width'])){ echo $imageReport['thumb_width']; }else{ echo 80;}?>' height='<?php if (isset($imageReport['thumb_height'])){ echo $imageReport['thumb_height']; }else{ echo 80;}?>' src="<?php echo $this->url(array('controller'=>'image','action'=>'getimage', 'id'=>$imageReport['id']));?>"/>
			                            </a>
			                            <a onclick="move_down(this);"><img src="<?php echo $this->baseUrl();?>/images/arrow_blue_down.png" /></a>
			                          </div>
									  <div class="status" style="<?php if(!$is_first) {echo 'display:none';}?>">
									  <?php if($imageReport['state'] == 'APPROVED' && isset($imageReport['point_amount'])) { ?>
										图片已审核, 您已获得<strong><?php echo $imageReport['point_amount'] ?></strong>分
									  <?php } else if($imageReport['state'] == 'NEW') { ?>
										图片需要审核, 请等待
									  <?php } else if($imageReport['state'] == 'UNAPPROVED') { ?>
									  	图片审核未通过
									  <?php }?>
									  </div>
	                  <?php }?>
                  <?php }?>
								<!-- <div class="intro-text"><?php echo $this->translate('Upload_Photo_Text')?></div> -->
								<div class="upload-photo-button-container">
								  <a href="#" class="btn btn-primary" id="uploadFile_<?php echo $activeCampaign['campaign_id'];?>"><?php echo $this->translate('Uplaod_Photo')?></a>
								  <!-- <div id="error" style="color:red;"></div> -->
								</div>
							    
							</div>
						</div>
					</div>
					<div id="tabs-url<?php echo $j?>" class="report-panel">
						<div class="images-column" style="float:left;margin-top:15px;"><img
							src="<?php echo $this->baseUrl();?>/images/campaign/campaign_105_03.jpg"
							style="padding: 0; border: 0; margin-right: 10px;background:none;" />
						</div>
						<div class="main-column" style="width:450px;float:left;margin-top:11px;">
							<div class='report-panel-header'>
								<!-- <span class="campaign-name"><?php echo $activeCampaign["name"]?></span> -->
								<span class="tab-description"> <?php echo $this->translate('Share_Facebook_Description')?><span>
							</div>
							<div class="share share-done share-container">
								<!-- <div class="status"><?php echo $this->translate("Home_Submit_URL_Report")?></div> -->
								<div class="share-input-container">
									<input class="btn btn-primary" id = "share_submit_<?php echo $activeCampaign['campaign_id'];?>" type="button" value="<?php echo $this->translate("Post_to_Facebook")?>" class="button" onclick="submitShare(<?php echo $activeCampaign['campaign_id'];?>);"/>
								</div>

							</div>
						</div>
					</div>

				</div><!-- end for tabs -->
			
			<?php }else{?>
			  该任务已经完成
			<?php }?>
			<?php $j++;?>
			</div>
		</div>
	</div>
<?php endforeach?>



<?php $i=1; foreach ($this->allInvitations as $invitation):?>
	<div class="spark-report-box">
		<div class="spark-report-box-inner">
			<!-- <h2><?php echo $invitation["name"]?></h2> -->
		
            <div class="ul-wrapper"  id="ul_tab_<?php echo $i?>"<?php if ($i>1):?> style="display:true;"<?php endif;?>>
			<?php $i++;?>
			<ul>
				
				<div style="border:1px dashed #3AB6EB;height:110px;width:630px;margin-top:25px;">
					<div style="float: left;">
						<?php if($invitation['type'] == 'mission'){?>
							<?php if($invitation['name']=="内测-美妆达人"){?>
								<!--<a href="<?php echo $this->url(array('controller'=>'tag','action'=>'index'));?>"><img src="<?php echo $this->baseUrl();?>/images/campaign/campaign_invitation_tab_<?php echo $this->lang; ?>_<?php echo $invitation['campaign_id'];?>.jpg" height="110"/></a>-->
								<div style='float:left;width:515px;'>
									<div style="margin-left:20px;"><strong>分享你的护肤、彩妆经验&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;赢取“我的美丽日记面膜*10片”</strong><br><br>
									星星火在此处为你搜罗了各大论坛、网站最新的美妆贴，你是否同意她们的观点？<br><strong><a href="<?php echo $this->url(array('controller'=>'tag','action'=>'index'));?>">点击此处</a></strong>回复你感兴趣的帖子，说说你的美妆经验吧~！
									<br><br>
									活动时间：2012.8.6——2012.8.19
								    </div>
								</div>
								<div style="float:right;width:115px;height:110px;">
									<img alt="" src="<?php echo $this->baseUrl();?>/images/campaign/testmission.jpg">
								</div>
							<?php }else{ ?>
								<a href="<?php echo $this->url(array('controller'=>'mission','action'=>'description','id'=>$invitation['campaign_id']));?>"><img src="<?php echo $this->baseUrl();?>/images/campaign/campaign_invitation_tab_<?php echo $this->lang; ?>_<?php echo $invitation['campaign_id'];?>.jpg" height="110"/></a>
							<?php }?>
						<?php }else{?>
						<!--
						<a href="<?php echo $this->url(array('controller'=>'campaigninvitation','action'=>'index'));?>"><img src="<?php echo $this->baseUrl();?>/images/campaign/campaign_invitation_tab_<?php echo $this->lang; ?>_<?php echo $invitation['campaign_id'];?>.jpg"  height="110"/></a>
						-->
						<a href="<?php echo $this->url(array('controller'=>'campaign','action'=>'precampaign', 'id'=>$this->recentInvitation['campaign_id']));?>"><img src="<?php echo $this->baseUrl();?>/images/campaign/campaign_invitation_tab_<?php echo $this->lang; ?>_<?php echo $invitation['campaign_id'];?>.jpg"  height="110"/></a>
						
						<?php }?>
					</div>
					<div style="float: left; width:200px; padding:10px;">
						<!--<?php echo $invitation["invitation_description"]."<br>".$invitation["invitation_description2"];?>
					-->
							<?php if($invitation['name']=="内测-美妆达人"){?>
										<!--<?php echo "加入美妆活动，这里有你最想要了解的潮流资讯，也期待你留下自己的心得！<br>
													活动时间：<br>
													2012.7.1——2012.7.31";?>
										-->
										
								<?php }elseif ($invitation['name']=='电影大赏'){ ?>
									<?php echo "夏日电影大赏，无论是记忆中的经典，还是正在热映的新片，来和星星火分享你的电影观感吧！<br>
												活动时间：<br>
												2012.7.15——2012.8.15";?>
							<?php }else{?>
									<!--<?php echo $invitation["invitation_description"];?><br> <span style='color:red'>点击图片参加活动</span>
							-->
									<?php echo $this->translate('Campaign_simple_description_'.$invitation['campaign_id']);?><!--<br> <span style='color:red'>点击图片参加活动</span>
							
							
							--><?php }?>

					</div>
				</div>
			</ul>
			</div>
		</div>
	</div>
<?php endforeach?>



<div class="spark-status">
		<div class="article-box-title">&nbsp;&nbsp;&nbsp;&nbsp;MY PROFILE</div>
	<!--  Tip  -->
	<div class="spark-status-box">
		<img onmouseover="showtip(2);" onmouseout="hidetip(2);" class="help-button" src="<?php echo $this->baseUrl();?>/images/help-button.gif"/>
		<div class="tip-wrapper">
			<div id="tip2" class="tip-box" style="display:none; ">
				<!-- <div class="top"></div> -->
				<div class="middle">
				<h2><?php echo $this->translate("What_is_Status_Header")?></h2>
				<p><?php echo $this->translate("What_is_Status_Content_1")?></p>
				<p><?php echo $this->translate("What_is_Status_Content_2")?></p>
				<p><?php echo $this->translate("What_is_Status_Content_3")?></p>
				<p><?php echo $this->translate("What_is_Status_Content_4")?></p>
				<p><?php echo $this->translate("What_is_Status_Content_5")?></p>
				</div>
				<!-- <div class="bottom"></div> -->
			</div>
		</div>
		<div class="avatar">
			<a href="<?php echo $this->url(array('controller'=>'consumer','action'=>'edit'));?>">
				<?php if($this->consumer[0]['gender']=="1") {?>
				<img src="images/MALE.png">
				<?php }?> 

				<?php if($this->consumer[0]['gender']=="0") {?>
				<img src="images/FEMALE.png">
				<?php }?>

				<?php if($this->consumer[0]['gender']==""){ ?>
				<img src="images/anonymous.jpeg">
				<?php } ?>
			</a>
		</div>
	    <!--  info bar  -->
		<div class="yourinfo">
			<span><?php echo $this->translate("Rank")?><a href="#"><?php  echo $this->consumer[0]['rname']; ?></a></span>
			<!--  Badge  -->
			<div>
				<?php if(count($this->badges)){?>	     
					<?php echo $this->translate("Your_badge")?><br>
				<?php
					foreach($this->badges as $badge){
						echo "<a class='thickbox' style='margin-right:5px' href='".$this->baseUrl()."/images/mission/badge_$badge->badge.jpg'><img src='".$this->baseUrl()."/images/mission/badge_$badge->badge.jpg' width=30 height = 30 style='border:1px solid #ccc'></a>";
					}
				?>
				<?php }?>
			</div><br/>
		    <div>
				<!--<?php echo $this->translate("Home_Your_Info_Completeness")?>-->
				<?php if ($this->consumerextrainfo<40): ?>
				<div class="progressbar-red">
				<?php endif;?>
				<?php if ($this->consumerextrainfo>=40 && $this->consumerextrainfo<70): ?>
				<div class="progressbar-yel">
				<?php endif;?>
				<?php if ($this->consumerextrainfo>=70 && $this->consumerextrainfo<90): ?>
				<div class="progressbar-grey">
				<?php endif;?>
				<?php if ($this->consumerextrainfo>=90): ?>
				<div class="progressbar-blu">
				<?php endif;?>
				<a href="<?php echo $this->url(array('controller'=>'consumer','action'=>'edit'));?>" class="progressbar"><div style="width:<?php echo $this->consumerextrainfo ?>px"></div></a><br><a href="<?php echo $this->url(array('controller'=>'consumer','action'=>'edit'));?>" tyle="font-size:10px;">Edit Your Profile</a></div>
				<span><a href='<?php echo $this->url(array('controller'=>'consumer','action'=>'edit'));?>'><?php echo $this->consumerextrainfo ?>%</a></span>
			</div>
		</div>

        
	
	    <!--  Points  -->
    <div style="float: left;width:120px;">
			<h3 style="margin-left:10px;">&nbsp;&nbsp;<?php echo $this->translate("Home_Spark_Points_Earned")?></h3><br>	
			<div class="spark-status-content">
				<h4><?php echo $this->totalPoints; ?></h4>
				<p><?php echo $this->translate("Spark_Points_Earned_Content_1")?>two<?php echo $this->translate("Spark_Points_Earned_Content_2")?>20<?php echo $this->translate("Spark_Points_Earned_Content_3")?></p>
			</div>
		</div>
		
		<div style="float: left;width:120px;">
			<h3 style="margin-left:10px;">&nbsp;&nbsp;<?php echo $this->translate("Rewards_Ready_to_Redeem")?></h3><br>
			<div class="spark-status-content">
				<h4><?php echo $this->redeemPoints; ?></h4>
			</div>
		</div>
		
		<div style="float: left;width:120px;">
			<h3 style="margin-left:10px;">&nbsp;&nbsp;<?php echo $this->translate("New_points")?></h3><br>
			<div class="spark-status-content">
				<h4><?php echo $this->newPoints; ?></h4>
			</div>
		</div>
		
		<div style="float: right; padding-right:35px;">
			<div class="buttons-bar"><a class="big-button-blue" href="<?php echo $this->url(array('controller'=>'point',	'action'=>'show'));?>" style=""><?php echo $this->translate("Redeem_Points")?></a></div>
			<div class="buttons-bar"><a class="big-button-blue" href="<?php echo $this->url(array('controller'=>'history',	'action'=>'stuff'));?>" style=""><?php echo $this->translate("Check_Points") ?></a></div>
		</div>
	</div>
</div>
	
	
<!-- delete polls 2012.11.21 Bruce.Liu -->
	<!-- <div class="spark-report-box">
		<div class="article-box-title">&nbsp;&nbsp;&nbsp;&nbsp;MY POLLS</div>		
		<div class="spark-report-box-inner">
			<div class='quick-poll-header'>
				<div class='quick-poll-name-container'>
					<span class="quick-poll-name"><?php echo $this->translate("Quick_Polls:_Tell_Us_About_Yourself!")?></span>
				</div>
				<div class='quick-poll-helper-container'>
					<div id="tip3" class="tip-box" style="display:none;">
						<h2><?php echo $this->translate("What_are_Quick_Polls?")?></h2>
						<p><?php echo $this->translate("What_are_Quick_Polls?_Content_1")?></p>
						<p><?php echo $this->translate("What_are_Quick_Polls?_Content_2")?></p>
						<p><?php echo $this->translate("What_are_Quick_Polls?_Content_3")?></p>
						<p><?php echo $this->translate("What_are_Quick_Polls?_Content_4")?></p>
					</div>
					<img  onmouseover="showtip(3);" onmouseout="hidetip(3);" src="<?php echo $this->baseUrl();?>/images/help-button.gif"/>
				</div>
				<div class='clear'></div>
			</div>
			<div class="clear"></div>
			<div class="ul-wrapper">
			<ul class="updates">
			<?php foreach ($this->surveys as $survey) : ?>
			    <?php if(($survey['public'] == 1)||($survey['consumer_id'])){?>
				<?php $flag="new"?>
				<?php foreach ($this->completedPolls as $completedPoll):?>
					<?php if ($completedPoll["poll_id"]==$survey["id"]):?>
						<?php $flag="completed"?>
					<?php endif;?>
				<?php endforeach;?>
				<?php if ($flag=="new") :?>
				<li>
					<?php if ($this->lang=='en'):?> 
						<a href="<?php echo $this->url(array('controller'=>'profilesurvey','action'=>'participate', 'id'=>$survey['id']));?>">
							 <?php echo $survey['english_name'];?> 
						</a>
					<?php else:?>
						<a href="<?php echo $this->url(array('controller'=>'profilesurvey','action'=>'participate', 'id'=>$survey['id']));?>">
							 <?php echo $survey['name'];?> 
						</a>
					<?php endif;?>			 
				( <?php echo $survey['points']?> <?php echo $this->translate("points")?> )
				</li>
				<?php endif;?>	
				<?php }?>
			<?php endforeach; ?>
			
			<?php foreach ($this->surveys as $survey) : ?>	
			    <?php if(($survey['public'] == 1)||($survey['consumer_id'])){?>
				<?php $flag="new"?>
				<?php foreach ($this->completedPolls as $completedPoll):?>
					<?php if ($completedPoll["poll_id"]==$survey["id"]):?>
						<?php $flag="completed"?>
					<?php endif;?>
				<?php endforeach;?>
				<?php if ($flag=="completed") :?>
				<li>
					<?php if ($this->lang=='en'):?> <?php echo $survey['english_name'];?> <?php else:?> <?php echo $survey['name'];?> <?php endif?> ( <?php echo $survey['points']?> <?php echo $this->translate("points")?> ) <img src="<?php echo $this->baseUrl();?>/images/action_check.gif" align="absmiddle"/> <?php echo $this->translate("earned")?> <?php echo $survey['points']?> <?php echo $this->translate("points")?>
				</li>
				<?php endif;?>
				<?php }?>
			<?php endforeach; ?>
			</ul>
			</div>
		</div>
	</div> -->

	<!--<?php if(count($this->activeMissions) || count($this->publicMissions)){?>
	<h2>完成任务，获得礼物和积分奖励！</h2>
	<div class="spark-report-box">
		<div class="spark-report-box-inner">
			<div class="ul-wrapper">
			<ul class="updates">
			    <?php foreach ($this->activeMissions as $mission) : ?>
			    <li>			    
			    <?php echo '<a href="'.$this->url(array('controller'=>'mission','action'=>'description', 'id'=>$mission['id'])).'">'.$mission['name'].'</a>'?>			    
			    </li>		    
			    <?php endforeach;?>
			    <?php foreach ($this->publicMissions as $mission) : ?>
			    <li>			    
			    <?php echo '<a href="'.$this->url(array('controller'=>'mission','action'=>'description', 'id'=>$mission['id'])).'">'.$mission['name'].'</a>'?>			    
			    </li>		    
			    <?php endforeach;?>
			</ul>
			</div>
		 </div>
	  </div>
	<?php }?>
	
	-->
	

</div>
<div id="fb-root"></div>
<script language="javascript">
window.fbAsyncInit = function() {
    // init the FB JS SDK
    FB.init({
      appId      : '234132663359597', // App ID from the App Dashboard
      channelUrl : '//community.wildfire.asia/channel.phtml', // Channel File for x-domain communication
      status     : true, // check the login status upon init?
      cookie     : true, // set sessions cookies to allow your server to access the session?
      xfbml      : true  // parse XFBML tags on this page?
    });


  };
var campaign_id;
function showtip(id){
	var tip = $("tip"+id);
	Element.show(tip);
}

function hidetip(id){
	var tip = $("tip"+id);
	Element.hide(tip);
}

/*
function hideAllUlTabs(){
	var count =  <?php echo count($this->activeCampaigns)+count($this->allInvitations)?>;
	for (var i=1;i<=count;i++){
		Element.hide("ul_tab_"+i);
		$('campaign_'+i).removeClassName('active');
	}
}

function showUlTab(id){
	hideAllUlTabs();
	var tab = $("ul_tab_"+id);
	Element.show(tab);
	$('campaign_'+id).addClassName('active');

}
*/
function submitShare(campaignId){
	FB.ui(
  {
   method: 'feed',
   name: jQuery("#campaign_name_"+campaignId).text(),
   caption: "",
   description: (
      jQuery("#campaign_description_"+campaignId).text()
   ),
   link: 'https://developers.facebook.com/docs/reference/javascript/',
   picture: 'http://www.fbrell.com/public/f8.jpg'
  },
  function(response) {
    if (response && response.post_id) {
      alert('Post was published.');
    } else {
      alert('Post was not published.');
    }
  }
);
}

function submitURL(campaignId){
	campaign_id = campaignId;
	var url = '<?php echo $this->url(array('controller'=>'report','action'=>'ajaxstoreurl'));?>';
	var pars = 'campaignId='+campaignId+'&url='+base64encode($('url_'+campaignId).value);
//alert(pars);
//return;
	new Ajax.Request(    
		url,
		{
		method: 'get',      
		parameters: pars,    
		onSuccess: updateURL    
		}
	);
}
var base64EncodeChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
var base64DecodeChars = new Array(
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 62, -1, -1, -1, 63,
    52, 53, 54, 55, 56, 57, 58, 59, 60, 61, -1, -1, -1, -1, -1, -1,
    -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
    15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, -1, -1, -1, -1, -1,
    -1, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
    41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, -1, -1, -1, -1, -1);
function base64encode(str) {
    var out, i, len;
    var c1, c2, c3;

    len = str.length;
    i = 0;
    out = "";
    while(i < len) {
    c1 = str.charCodeAt(i++) & 0xff;
    if(i == len)
    {
        out += base64EncodeChars.charAt(c1 >> 2);
        out += base64EncodeChars.charAt((c1 & 0x3) << 4);
        out += "==";
        break;
    }
    c2 = str.charCodeAt(i++);
    if(i == len)
    {
        out += base64EncodeChars.charAt(c1 >> 2);
        out += base64EncodeChars.charAt(((c1 & 0x3)<< 4) | ((c2 & 0xF0) >> 4));
        out += base64EncodeChars.charAt((c2 & 0xF) << 2);
        out += "=";
        break;
    }
    c3 = str.charCodeAt(i++);
    out += base64EncodeChars.charAt(c1 >> 2);
    out += base64EncodeChars.charAt(((c1 & 0x3)<< 4) | ((c2 & 0xF0) >> 4));
    out += base64EncodeChars.charAt(((c2 & 0xF) << 2) | ((c3 & 0xC0) >>6));
    out += base64EncodeChars.charAt(c3 & 0x3F);
    }
    return out;
}
function updateURL(originalRequest){
	if(originalRequest.responseText){
		$('url_report_notice_'+campaign_id).innerHTML = '<?php echo $this->translate("Home_URL_Report_Wait_For")?>';
		$('url_report_submit_'+campaign_id).style.display = "none";
	}
}

var getWidth = function() {
	var w = window;
	var d = document;
	var dd = d.documentElement;
	var width;
	
	if (w.innerWidth)
		width = w.innerWidth;
	else if (dd && dd.clientWidth)
		width = dd.clientWidth;
	else if(d.body)
		width = d.body.clientWidth;
	
	return width;
}
var getHeight = function() {
	var w = window;
	var d = document;
	var dd = d.documentElement;
	var height;
	
	if (w.innerHeight) 
		height = w.innerHeight;
	else if (dd && dd.clientHeight)
		height = dd.clientHeight;  
	else if (d.body)
		height = d.body.clientHeight;
	
	return height;
}
var WebDialog = {
	count:0,
	showpointer:1,
	list:{},
	element : $('web-dialog'),
	onok : function() {},
	oncancel : function() {},
	show : function() {
		var width = document.body.clientWidth;
		width = getWidth();
		var height = document.body.offsetHeight;
		height = getHeight();
		var left = (width - this.element.offsetWidth) / 2;
		var top = (height - this.element.offsetHeight) / 2;
		if (top < 200) {
			top = 200;
		}
		this.element.style.left = left + "px";
		this.element.style.top = top + "px";
	},
	alert : function(msg,agree,disagree,onok,oncancel) {
		var buttons = ["OK","Cancel"];
		var callbacks = [onok, oncancel];
		this.showMessageBox(msg, "alert", "left", 400, buttons, callbacks);
	},
	ok : function() {
		this.onok();
	},
	close : function() {
					
		Element.hide(this.list[this.showpointer]);
		this.showpointer++;
		if (this.count<this.showpointer){	
			$('mask').hide();
		}else{
			Element.show(this.list[this.showpointer]);
		}
		this.oncancel();
	},
	showMessageBox : function(msg, icon_type, msg_align, window_width, buttons, callback_functions,elem) {
		// icon_type : "none", "alert", "question"
		// msg_align : "left", "center", "right"
		// width : -1 means auto
		if (elem!=null){
			this.element = $(elem);
		}
		this.count++;
		this.list[this.count] = this.element;
		var width = getWidth();
		var height = getHeight();
		var left = (width - window_width) / 2;
		var top = (height - 250) / 2;
		var pos = 0;
		if (window.innerHeight) {
	    	pos = window.pageYOffset
	    } else if (document.documentElement && document.documentElement.scrollTop) {
	    	pos = document.documentElement.scrollTop
	    } else if (document.body) {
	    	pos = document.body.scrollTop;
	    }
	    top += pos;
		/*
		if (top < 200) {
			top = 200;
		}
		*/
		this.element.style.left = left + "px";
		this.element.style.top = top + "px";
		if (this.count==1){
			this.element.show();
		}
		$('mask').style.width = width + "px";
		$('mask').style.height = height + "px";
		$('mask').show();
	}
}


var html = "aaa";
var buttons = ['aaa','bbb'];
var callbacks = [function(){},function(){}];
<?php if ($this->popup==true):?>
	<?php if(isset($this->postCampaignNotification)&&$this->postCampaignNotification):?>
		WebDialog.showMessageBox(html, "left", "center", 610, buttons, callbacks,'web-dialog2');
	<?php endif;?>
	
	<?php if (isset($this->recentInvitation)&&$this->recentInvitation):?>
		WebDialog.showMessageBox(html, "left", "center", 610, buttons, callbacks,'web-dialog');
	<?php endif;?>

	<?php if (count($this->allInvitations)+count($this->activeCampaigns)==0):?>
	WebDialog.showMessageBox(html, "left", "center", 610, buttons, callbacks,'no-campaign');
	<?php endif?>
<?php endif;?>	


jQuery(document).ready(function(){
jQuery('#fillout-dialog').dialog({dialogClass: 'ui-fillout-dialog', bgiframe: true, autoOpen: false, resizable: false, modal: true, width: 680, height: 600, title: '<?php echo $this->translate("Submit_WOM_Report")?>' });
jQuery('#check-alert-dialog').dialog(
		{title:'<?php echo $this->translate("Submit_you_report_error")?>', bgiframe: true, autoOpen: false, resizable: false, modal: true, buttons: {
		'<?php echo $this->translate("Submit_you_report_confirm")?>': function() {
			jQuery(this).dialog('close');
		}
	}
});

<?php foreach ($this->activeCampaigns as $activeCampaign):?>
var button_<?php echo $activeCampaign['campaign_id'];?> = jQuery("#uploadFile_<?php echo $activeCampaign['campaign_id'];?>"), interval;
//var image_thumb_<?php echo $activeCampaign['campaign_id'];?> = jQuery("#image_thumb_<?php echo $activeCampaign['campaign_id'];?>"), interval;
new AjaxUpload(button_<?php echo $activeCampaign['campaign_id'];?>,{
    //action: 'upload-test.php', // I disabled uploads in this example for security reasons
    action: '<?php echo $this->url(array('controller'=>'report','action'=>'ajaxstoreimage'));?>', 
    //name: 'myfile',
    data: {
        campaign_id : <?php echo $activeCampaign['campaign_id'];?>
    },
    //responseType: 'json',
    onSubmit : function(file, ext){
        if (! (ext && /^(jpg|png|jpeg|gif)$/.test(ext))){
            // extension is not allowed
           jQuery('div#error').text("请上传正确的图片").show().fadeOut(5000);
           // cancel upload
           return false;
        }
    
        // change button text, when user selects file           
        button_<?php echo $activeCampaign['campaign_id'];?>.text('uploading');
        
        // If you want to allow uploading only 1 file at time,
        // you can disable upload button
        this.disable();
    },
    onComplete: function(file, response){
        button_<?php echo $activeCampaign['campaign_id'];?>.text("<?php echo $this->translate('Uplaod_Photo')?>");
        // enable upload button
        this.enable();
        eval(response);
    }
});
<?php endforeach;?>

});

var filloutDialogOpen = function(url) {
	jQuery("#fillout-dialog .content").load(url,function(){
	});
	jQuery("#fillout-dialog").dialog('open');
}
var currentReportPanel = 0;
var showReportPanel = function(panelId) {
	var panels = new Array('.submit-report','.uploading-image','.submit-url');
	var buttons = new Array('.button-submit-report img','.button-upload-image img','.button-submit-url img');
	var buttonsGrey = new Array('tab_button_report_grey.png','tab_button_photo_grey.png','tab_button_url_grey.png');
	var buttonsBlue = new Array('tab_button_report_blue.png','tab_button_photo_blue.png','tab_button_url_blue.png');
	jQuery(panels[currentReportPanel]).hide();
	jQuery(buttons[currentReportPanel]).attr("src","<?php echo $this->baseUrl();?>/images/"+buttonsGrey[currentReportPanel]);
	jQuery(buttons[panelId]).attr("src","<?php echo $this->baseUrl();?>/images/"+buttonsBlue[panelId]);
	jQuery(panels[panelId]).show('slide');
	currentReportPanel = panelId;
}

function move_down(e) {
  var parent = jQuery(jQuery(e).parent());
  if(parent.next().next().attr('class')) {
      parent.hide();
      parent.next().hide();
  	  parent.next().next().show();	
      parent.next().next().next().show();	
  } else {
  	jQuery('div#error').text("已经是最后一个了").show().fadeOut(5000);
  }
}

function move_up(e) {
  var parent = jQuery(jQuery(e).parent());
  if(parent.prev().prev().attr('class')) {
    parent.hide();
    parent.next().hide();
  	parent.prev().show();	
    parent.prev().prev().show();
  } else {
  	jQuery('div#error').text("已经是第一个了").show().fadeOut(5000);
  }
}

loadNotification(jQuery("#notification-box"));
</script>