<div class="article-box" style="height:120px;">
	<div class="article-box-inner">
		<h2>
			<!--<?php echo $this->translate('Thanks_For_report')?>-->
			Post was not published.
		</h2>
        <p style="padding-top:10px">
          Ooops! An error has occurred during the process. Please click the back button and try again!
        </p>
        <div class="buttons-bar" style="padding-top: 10px;">
	             <a class="big-button-blue" target="_parent"  href="<?php echo $this->url(array('controller'=>'home','action'=>'index'));?>">
                          <?php echo $this->translate('Take_Me_Back')?>
                 </a>
    		</div>
	</div>
</div>
